kitchen-tests/cookbooks/end_to_end/recipes/windows.rb
lib/chef/resource/windows_user_privilege.rb
spec/unit/resource/windows_uac_spec.rb
spec/unit/resource/windows_user_privilege_spec.rb

Update the validation of the privilege property on the windows_user_privilege resource

---

lib/chef/resource/ohai.rb
tasks/docs.rb

Make it a bit easier to generate the docs for this resource

Add examples to the ohai resource

---

chef-bin/Rakefile
lib/chef/mixin/versioned_api.rb

Avoid a sort then last and just grab the max.

Resolve Style/RedundantSort warnings

---

RELEASE_NOTES.md
lib/chef/resource/chef_handler.rb
lib/chef/resource/openssl_ec_public_key.rb
lib/chef/resource/openssl_x509_request.rb
lib/chef/resource/powershell_package_source.rb

Docs fixes from review

---

Gemfile.lock
omnibus/Gemfile.lock

Update InSpec to the latest

---

Gemfile.lock
omnibus/Gemfile.lock

Update to the latest license_scout gem

---

lib/chef/provider/link.rb

I've just found a private method that is not being used.

Remove unused method

---

chef-config/lib/chef-config/mixin/train_transport.rb
chef-config/lib/chef-config/workstation_config_loader.rb
lib/chef/provider/package/dpkg.rb

- Use `transform_keys` & `transform_values` to simplify hash keys & values accordingly.
- Minor refactor to avoid a single line begin block to memoization.
Fixes: https://github.com/chef/chef/issues/10441

Simplify Hash transforms & minor code refactoring

---

chef-config/lib/chef-config/config.rb
chef-config/spec/unit/config_spec.rb

Use ChefUtils::Dist::Infra::PRODUCT for locale warning instead of "Chef"

---

RELEASE_NOTES.md

Fixes
```
--
  | Chef encountered an error attempting to load the node data for "chef-cli"
  | ================================================================================
  |  
  | Unexpected Error:
  | -----------------
  | NameError: uninitialized constant Chef::PolicyBuilder::Dynamic::ExpandNodeObject
```

Preparing 16.5 hotfix patch to fix Workstation build issue

---

chef-config/lib/chef-config/config.rb
lib/chef/mixin/uris.rb
lib/chef/resource/apt_repository.rb
lib/chef/search/query.rb

autoload addressable/uri on :URI inside addressable module

---

chef-config/lib/chef-config/config.rb
lib/chef/application.rb
lib/chef/chef_fs/chef_fs_data_store.rb
lib/chef/chef_fs/file_system/repository/chef_repository_file_system_cookbook_entry.rb
lib/chef/cookbook/gem_installer.rb
lib/chef/file_content_management/tempfile.rb
lib/chef/formatters/indentable_output_stream.rb
lib/chef/knife/node_policy_set.rb
lib/chef/knife/node_run_list_add.rb
lib/chef/knife/node_run_list_remove.rb
lib/chef/knife/node_run_list_set.rb
lib/chef/knife/role_env_run_list_add.rb
lib/chef/knife/role_env_run_list_set.rb
lib/chef/knife/role_run_list_add.rb
lib/chef/knife/role_run_list_set.rb
lib/chef/knife/ssh.rb
lib/chef/knife/tag_create.rb
lib/chef/knife/tag_delete.rb
lib/chef/mixin/template.rb
lib/chef/node_map.rb
lib/chef/provider.rb
lib/chef/provider/service/redhat.rb
lib/chef/provider/user/dscl.rb
lib/chef/provider/user/mac.rb
lib/chef/resource.rb
lib/chef/resource/apt_repository.rb
lib/chef/util/backup.rb
lib/chef/win32/file.rb
lib/chef/win32/unicode.rb

I find `array[n..]` more readable than `array[n..-1]` and thought that would not be difficult to applied here.
https://blog.bigbinary.com/2018/07/04/ruby-2-6-adds-endless-range.html

Use Ruby 2.6 endless Range syntax

---

RELEASE_NOTES.md

Update release notes for 16.5.77

---

lib/chef/node/mixin/immutablize_hash.rb

ruby 3.0 adds except/except! to Hash

add ruby-3.0 hash methods to immutabilize_hash

---

lib/chef/mixin/powershell_out.rb
omnibus/omnibus-test.ps1
spec/functional/mixin/powershell_out_spec.rb
spec/spec_helper.rb
spec/support/platform_helpers.rb
spec/unit/mixin/powershell_out_spec.rb

add interpreter arg to powershell_out allowing it to call pwsh.exe

---

lib/chef/data_collector.rb

Remove extra safe navigation

---

Gemfile.lock
omnibus/Gemfile.lock

This includes Passwd support on Windows

Update Ohai to 16.6.1

---

lib/chef/provider/powershell_script.rb
lib/chef/resource/powershell_script.rb
spec/functional/resource/powershell_script_spec.rb
spec/unit/provider/powershell_script_spec.rb
spec/unit/resource/powershell_script_spec.rb

add interpreter to handle pwsh and powershell to powershell_script

---

lib/chef/resource/apt_repository.rb
lib/chef/resource/chef_client_config.rb
lib/chef/resource/chef_client_cron.rb
lib/chef/resource/chef_client_scheduled_task.rb
lib/chef/resource/chef_client_systemd_timer.rb
lib/chef/resource/chef_sleep.rb
lib/chef/resource/cron/cron_d.rb
lib/chef/resource/kernel_module.rb
lib/chef/resource/launchd.rb
lib/chef/resource/mount.rb

Pull in cookstyle fixes
Add formatting

Update examples and descriptions for better automated documentation

---

Gemfile.lock
omnibus/Gemfile.lock

Update cacerts, ohai, and winrm to the latest

---

lib/chef/resource/route.rb
lib/chef/resource/sudo.rb
lib/chef/resource/systemd_unit.rb
lib/chef/resource/windows_certificate.rb
lib/chef/resource/windows_font.rb

A few formatting fixes so that things generate properly

Minor updates for documentation generation

---

lib/chef/resource/powershell_script.rb

Update powershell_script description to match docs site.

---

lib/chef/resource/breakpoint.rb
lib/chef/resource/execute.rb

Resource documentation updates from review

---

lib/chef/provider/registry_key.rb
lib/chef/provider/service/debian.rb
lib/chef/resource/registry_key.rb
tasks/docs.rb

There's still a few of these leftover, but these are the easy wins with obvious wins.

Avoid declaring arrays in loops

---

spec/functional/resource/windows_package_spec.rb

- Added functional test for windows_package with `remote_file_attributes`.
- Added variable `run_context` to fix NameError: undefined local variable.
- Updated `Microsoft Visual C++ 2005 Redistributable` pkg path and checksum to fix `404 Not Found`.
- Updated `Mercurial 3.6.1 (64-bit)` pkg_path to fix `OpenSSL::SSL::SSLError`.
#10179

Added functional test for windows_package with remote_file_attributes.

---

kitchen-tests/cookbooks/end_to_end/recipes/_ifconfig.rb
kitchen-tests/cookbooks/end_to_end/recipes/linux.rb
kitchen-tests/kitchen.yml
lib/chef/resource/ifconfig.rb

We lacked an actual test of this resource. Let's see if it works.

Test ifconfig in Test Kitchen and add examples to the resource

---

Gemfile.lock
omnibus/Gemfile.lock

Update train-core & pull in the faster MSI installs

---

Gemfile.lock
omnibus/Gemfile.lock

Bump Ohai to 16.7 and cacerts to the latest

---

lib/chef/provider/package/powershell.rb
spec/unit/provider/package/powershell_spec.rb

ensure powershell_package commands are run with tls 1.2

---

lib/chef/http.rb
lib/chef/server_api.rb

This was supposed to be in #10548. Oops!

Remove references to monkeypatch method.

---

.expeditor/verify.pipeline.yml
kitchen-tests/kitchen.yml

Add back Oracle 8 Test Kitchen testing

---

chef-utils/spec/unit/dsl/which_spec.rb
lib/chef/chef_fs/data_handler/cookbook_data_handler.rb
lib/chef/chef_fs/file_pattern.rb
lib/chef/cookbook_manifest.rb
lib/chef/cookbook_version.rb
lib/chef/key.rb
lib/chef/mixin/openssl_helper.rb
lib/chef/property.rb
lib/chef/win32/security/sid.rb
spec/support/lib/chef/resource/cat.rb
spec/support/lib/chef/resource/one_two_three_four.rb
spec/unit/mixin/which.rb

So much easier to read and probably faster this way too.

Merge repetitive conditionals

---

chef-config/lib/chef-config/mixin/fuzzy_hostname_matcher.rb

Simplify a weird conditional in chef-config

---

chef-config/lib/chef-config/mixin/dot_d.rb

Nothing real amazing here. Just a note for future folks.

Add a minor comment explaining why we check file types

---

lib/chef/knife/bootstrap/templates/windows-chef-client-msi.erb
lib/chef/knife/core/windows_bootstrap_context.rb

Fix secret options in windows bootstrap

---

omnibus/config/software/more-ruby-cleanup.rb

This cleans up some files we don't need in the install artifact. Shaves a whole 61k off the build.

Remove a few more files from our install artifact

---

chef-config/lib/chef-config/workstation_config_loader.rb
lib/chef/environment.rb
lib/chef/formatters/error_inspectors/compile_error_inspector.rb
lib/chef/formatters/error_inspectors/resource_failure_inspector.rb
lib/chef/knife/core/cookbook_scm_repo.rb
lib/chef/knife/core/gem_glob_loader.rb
lib/chef/mixin/unformatter.rb
lib/chef/provider/package/rubygems.rb
lib/chef/provider/package/yum/rpm_utils.rb
lib/chef/run_lock.rb
spec/functional/resource/apt_package_spec.rb
spec/unit/knife/configure_spec.rb
spec/unit/resource/breakpoint_spec.rb
spec/unit/shell_spec.rb

We're working too hard here. No need for these.

Simplify regexes by removing extra character classes

---

Gemfile.lock

Update ohai to 16.7.9 and rspec to 3.10

---

lib/chef/run_lock.rb

A regex isn't necessary to replace this string.

Use tr where we don't need gsub and a regex

---

Gemfile
Gemfile.lock
omnibus/Gemfile.lock

Remove gemfile gems that are also in the gemspec.

Remove duplicate Gemfile gems + update ohai to 16.7.13

---

.rubocop.yml
Gemfile.lock

Rename the one place we reference a cop name

Update to the new chefstyle

---

lib/chef/file_access_control/windows.rb
lib/chef/node/attribute_collections.rb
lib/chef/provider/cron.rb
lib/chef/provider/package/snap.rb
lib/chef/resource/plist.rb
lib/chef/util/dsc/lcm_output_parser.rb
lib/chef/util/powershell/cmdlet.rb

Write more compact case statements to prevent duplicate branches.

Collapse several duplicate branches down

---

lib/chef/provider/cron.rb
lib/chef/resource_collection/resource_set.rb
spec/functional/resource/apt_package_spec.rb

Collapse more duplicate branches

---

chef-utils/lib/chef-utils/version_string.rb
lib/chef/cookbook_version.rb

Use ||= where we can

---

lib/chef/client.rb
spec/unit/client_spec.rb

- Added deprecation warning for` enforce_path_sanity`
- Ensured chefstyle on the code changes made
Fixes: #10201

Added deprecation warning for enforce_path_sanity

---

Gemfile.lock
omnibus/Gemfile.lock

Update Ohai to 16.7.18 and Fauxhai to 8.4

---

tasks/docs.rb

We updated this in
https://github.com/chef/chef-web-docs/commit/ec546e806366ca315b91e77eb357f65a14e11418
to simplify the yaml we have to generate.

Update the yaml we generate for resource documentation

---

spec/unit/resource/mount_spec.rb

Test the transforms we perform on these inputs

Add additional property coerce specs to mount

---

lib/chef/resource/registry_key.rb

provide a registry_key example that creates a multibyte binary value

---

spec/functional/resource/powershell_package_source_spec.rb

fixes omnibus build. This passed adhoc.

Fix ps specs

---

lib/chef/resource/registry_key.rb

fix chefstyle violations

---

lib/chef/shell/ext.rb

Disable Lint/Debugger complaining out chef-shell using irb

---

lib/chef/knife/bootstrap.rb

As we have used `Net::SSH::AuthenticationFailed` constant in connect! method so it requires net/ssh.
https://github.com/chef/chef/blob/84c6e6f6561230ab178fac8eb7fc9f944c985944/lib/chef/knife/bootstrap.rb#L630
chef-core related fixed: #10637 

knife bootstrap deps require net/ssh

---

lib/chef/provider/package/zypper.rb

Very unclear why this didn't turn up on my local testing, but it seems
legit enough hardening to do here.

Fix zypper_package CI failures

---

lib/chef/resource/execute.rb
spec/support/shared/unit/script_resource.rb
spec/unit/resource/powershell_script_spec.rb

include password in guard inherited attributes

---

Gemfile.lock

Ohai has significant improvements for AIX systems

Update ohai and win32-service to the latest

---

lib/chef/provider/route.rb
spec/functional/mixin/powershell_out_spec.rb
spec/integration/knife/client_key_create_spec.rb
spec/integration/knife/node_create_spec.rb
spec/integration/knife/node_environment_set_spec.rb
spec/integration/knife/node_run_list_add_spec.rb
spec/integration/knife/node_run_list_remove_spec.rb
spec/integration/knife/node_run_list_set_spec.rb
spec/integration/knife/node_show_spec.rb
spec/integration/recipes/notifies_spec.rb
spec/integration/recipes/provider_choice.rb
spec/support/shared/unit/knife_shared.rb
spec/unit/knife/client_create_spec.rb
spec/unit/knife/configure_client_spec.rb
spec/unit/knife/cookbook_delete_spec.rb
spec/unit/knife/cookbook_download_spec.rb
spec/unit/knife/cookbook_list_spec.rb
spec/unit/knife/cookbook_metadata_spec.rb
spec/unit/knife/environment_compare_spec.rb
spec/unit/knife/supermarket_download_spec.rb
spec/unit/knife/supermarket_list_spec.rb
spec/unit/knife/supermarket_search_spec.rb
spec/unit/knife/tag_create_spec.rb
spec/unit/knife/tag_delete_spec.rb
spec/unit/knife/user_create_spec.rb
spec/unit/resource/service_spec.rb

Just makes it a bit easier to read.

Avoid ambiguous regexes

---

lib/chef/provider/mount.rb
lib/chef/provider/mount/mount.rb
spec/functional/resource/mount_spec.rb

- Updated `device_real` method to fix aix test failure.
#10635

Mount: Fixes for Mount resource changes broke specs on AIX

---

Gemfile.lock
omnibus/Gemfile.lock

bump ohai, win32-service, and omnibus deps

---

Gemfile.lock

Update Ohai to 16.7.37

---

RELEASE_NOTES.md

WIP collection of changes until we're ready to ship

Add Chef Infra Client 16.7 release notes

---

Gemfile.lock
omnibus/Gemfile.lock

This *should* fix our macOS pain

Bump omnibus / omnibus-software to the latest

---

Gemfile.lock
lib/chef/cookbook_manifest.rb
lib/chef/encrypted_data_bag_item/assertions.rb
lib/chef/exceptions.rb
lib/chef/provider/git.rb
lib/chef/resource/template.rb
lib/chef/resource_collection/resource_set.rb
lib/chef/win32/api/file.rb
spec/integration/recipes/recipe_dsl_spec.rb
spec/unit/knife/core/node_editor_spec.rb
spec/unit/provider/mount/windows_spec.rb

If we really care we can turn this off, but it seems fine

Resolve new spacing offenses in RuboCop 1.4

---

README.md
docs/dev/design_documents/client_release_cadence.md

There were some things in here that aren't accurate at this point.

Update our release cadence docs

---

.expeditor/release.omnibus.yml

This reverts commit 06091f1153dc02ca74f1d6e59aa2e30d0779056b.

Add back macOS builds to the omnibus pipeline

---

lib/chef/resource/dsc_script.rb
spec/functional/resource/dsc_script_spec.rb

only test dsc_script on 64 bit and document that it will fail on 32 bit clients

---

Gemfile
Gemfile.lock
lib/chef/encrypted_data_bag_item/assertions.rb
lib/chef/provider/git.rb
lib/chef/resource/template.rb
lib/chef/resource_collection/resource_set.rb
omnibus/Gemfile.lock
spec/unit/knife/core/node_editor_spec.rb

The issue that requires pinning has been resolved

Switch back to chefstyle from github

---

spec/functional/resource/dsc_script_spec.rb

only run dsc_script functional tests on 64 bit ruby

---

chef.gemspec
lib/chef/knife/ssh.rb

Fix for deprecation warning in knife ssh

---

lib/chef/resource/windows_certificate.rb
spec/unit/resource/windows_certificate_spec.rb

Improvement in the PFX certificate so as to imported certificate can be exported as user wants.
When we import the PFX certificate, it's unable to export along with its keys so this improvement by adding `exportable` parameter to the underlying function will ensure the certificate to be exportable as well.
- Exported value as integer can be passed to https://github.com/chef/win32-certstore/blob/master/lib/win32/certstore/store_base.rb#L69 so that certificate become exportable.
- Reference doc : https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-pfximportcertstore
Fixes #9355

windows_certificate: Add exportable option to pfx certificate

---

RELEASE_NOTES.md

Add Chef Infra Client 16.8 release notes

---

omnibus_overrides.rb

General improvements in archive support

Bump libarchive to 3.5.0

---

RELEASE_NOTES.md

Add release notes for 16.8.14

---

lib/chef/resource/chef_gem.rb
lib/chef/resource/file.rb
lib/chef/resource/gem_package.rb
lib/chef/resource/http_request.rb
lib/chef/resource/mdadm.rb
lib/chef/resource/osx_profile.rb
lib/chef/resource/remote_directory.rb
lib/chef/resource/ruby.rb
lib/chef/resource/ruby_block.rb
tasks/docs.rb

Add more note values to the descriptions, update a few examples for cookstyle and modern gems, and identify a few more resources as providing package on their platform

Improve our automated resource documentation generation

---

lib/chef/resource/locale.rb

This command can take a while to run so let's give it all the time it needs to complete.
Fixes https://github.com/chef/chef/issues/10737

locale: Update the locale-gen timeout to 1800s

---

Gemfile.lock
omnibus/Gemfile.lock

Update train to 3.4.4

---

lib/chef/compliance/fetcher/automate.rb
lib/chef/compliance/fetcher/chef_server.rb
lib/chef/compliance/reporter/automate.rb
lib/chef/compliance/reporter/chef_server_automate.rb

Depends on chef/chef-web-docs#2781 getting merged.

Update links to Compliance Phase documentation in log messages.

---

.expeditor/config.yml

Setup Expeditor to start the bump

---

Gemfile.lock

This release of FFI works on the M1s

Pull in the new FFI we need for M1 Macs

---

Rakefile
lib/chef/mixin/get_source_from_package.rb
lib/chef/provider/package/portage.rb
lib/chef/provider/service/freebsd.rb
lib/chef/provider/user/dscl.rb
lib/chef/util/dsc/local_configuration_manager.rb
spec/data/cookbooks/openldap/libraries/openldap.rb
spec/unit/knife/core/gem_glob_loader_spec.rb

A few things that the new rubocop-performance called out and then some others that I noticed while digging into those.

Misc minor perf bumps

---

.rubocop.yml
chef-config/spec/unit/config_spec.rb
chef-config/spec/unit/path_helper_spec.rb
lib/chef/chef_fs/file_system.rb
lib/chef/provider.rb
spec/functional/dsl/registry_helper_spec.rb
spec/functional/resource/registry_spec.rb
spec/functional/win32/registry_spec.rb
spec/integration/recipes/recipe_dsl_spec.rb
spec/unit/application/solo_spec.rb
spec/unit/dsl/registry_helper_spec.rb
spec/unit/knife/bootstrap_spec.rb
spec/unit/provider/subversion_spec.rb
spec/unit/resource/windows_task_spec.rb
spec/unit/user_spec.rb
spec/unit/user_v1_spec.rb

Resolve Lint/ParenthesesAsGroupedExpression warnings

---

.rubocop.yml
Gemfile.lock
lib/chef/util/dsc/configuration_generator.rb

Get us closer to a stock config

Cleanup some more disabled style cops

---

lib/chef/knife/core/status_presenter.rb
spec/unit/knife/core/status_presenter_spec.rb

Fix knife status json output for EC2 instance with no public IP.

---

lib/chef/policy_builder/policyfile.rb

I'm not sure why this was passing before but it's fixed now.

Fix typo in comment.

---

cspell.json
lib/chef/knife/core/formatting_options.rb
lib/chef/knife/core/node_presenter.rb
lib/chef/knife/core/status_presenter.rb
lib/chef/knife/node_show.rb
lib/chef/knife/search.rb
lib/chef/knife/status.rb
spec/unit/knife/core/status_presenter_spec.rb

Noticed some hairy code while looking at #10781. Also fixes some chefstyle violations introduced in that PR.

Cleanup knife status

---

.expeditor/verify.pipeline.yml

This is already there. Don't waste time.

Don't install util-linux into the containers in CI

---

.expeditor/verify.pipeline.yml
kitchen-tests/kitchen.yml

This release is not out yet, but we have containers for it now.

Add Test Kitchen testing for Debian 11

---

lib/chef/knife/core/status_presenter.rb
lib/chef/knife/status.rb
spec/unit/knife/core/status_presenter_spec.rb

Backport https://github.com/chef/chef/pull/10781

Fix knife status json output for EC2 instance with no public IP

---

.expeditor/config.yml

Update gemfile.lock when fauxhai is released

---

kitchen-tests/cookbooks/end_to_end/recipes/macos.rb
lib/chef/resource/homebrew_cask.rb

Also add a CI test for installing a small cask

Fix homebrew_cask for the new syntax

---

lib/chef/resource/hostname.rb

Use the darwin? helper instead of looking for a binary that only exists on darwin
Remove the declare_resource usage we don't need anymore

Simplify the code in the hostname resource

---

RELEASE_NOTES.md

Add 16.9 release notes

---

.github/dependabot.yml

Setup omnibus bumping on chef 16/15

---

Dockerfile

These are the same package, but in a while we're get rid of RHEL 6 and
this will break.

Update the Docker file to use the RHEL 7 package

---

RELEASE_NOTES.md

Add 15.15, add older 15 releases, resolve a number of markdown warnings.

Add Chef Infra Client 15.15 release notes

---

Gemfile.lock

We need this for chef-zero to function properly

Update chef-zero to pull in webrick

---

kitchen-tests/Gemfile

Remove the kitchen-azurerm dep for kitchent tests

---

lib/chef/dsl/chef_vault.rb

These get parsed by the vscode snippets repo and these were annoying to
see

Fix yard warnings in the chef_vault dsl

---

Gemfile.lock
chef.gemspec

- Updated `uuidtools` version
Fixes: #10800

Updated uuidtools version

---

.expeditor/verify.pipeline.yml
chef-config/chef-config.gemspec
chef-utils/chef-utils.gemspec

Since the world deps on these we really need a longer Ruby lifecycle
here

Test chef-utils and chef-config on Ruby 2.6 still

---

lib/chef/shell.rb

Resolve chefstyle failure

---

RELEASE_NOTES.md
lib/chef/shell.rb

Resolve spelling failures

---

RELEASE_NOTES.md

Add release notes for 16.9.29

---

chef.gemspec
lib/chef/version_string.rb
omnibus/Gemfile
omnibus/Gemfile.lock

Don't ship dev gems in the shipping artifact

---

chef.gemspec
lib/chef/version_string.rb

Backport of the dev gem removal fix from chef-16/17

---

Gemfile.lock
omnibus/Gemfile.lock

We need this to support the new metadata format in AWS

Pull in the latest Ohai

---

lib/chef/dsl/reboot_pending.rb
lib/chef/file_access_control/windows.rb
lib/chef/file_cache.rb
lib/chef/formatters/error_inspectors/resource_failure_inspector.rb
lib/chef/handler/json_file.rb
spec/unit/dsl/reboot_pending_spec.rb
spec/unit/formatters/error_inspectors/resource_failure_inspector_spec.rb

Replace deprecated File.exists? with File.exist? in more places

---

.rubocop.yml
lib/chef/util/dsc/configuration_generator.rb

Make sure we avoid these in the future. We should probably turn this on in Chefstyle.

Fix an interpolation mistake in an error message + turn on the cop

---

.rubocop.yml
Gemfile.lock

This is something we should keep and eye out for, but there's some false positives in the attributes class to avoid.

Enable Deprecated Constants Cop

---

lib/chef/knife/bootstrap.rb
spec/unit/knife/bootstrap_spec.rb

ATTENTION: Merge first train changes: https://github.com/inspec/train/pull/636
- Add `--su-user` & `--su-password` options.
- Modify perform bootstrap command to execute using `su - USER -c 'COMMAND'`.
- Catch `su: Authentication failure` and re-try with providing suing user password. 
Fixes: https://github.com/chef/chef/issues/10181

handles su - USER session to perform bootstrap

---

RELEASE_NOTES.md

Add 16.9.32 release notes

---

Gemfile
Gemfile.lock
spec/unit/knife/supermarket_share_spec.rb

using a proper instance_double avoids the errors and that's the right
thing to do here.

fix specs for spec 3.10

---

lib/chef/compliance/runner.rb

Drop some compliance log messages down to debug output

---

lib/chef/compliance/runner.rb

Backport https://github.com/chef/chef/pull/10965

these messages should be debug level output

---

Gemfile.lock
omnibus/Gemfile.lock

Update Ohai to 16.10.6

---

chef-utils/lib/chef-utils/dsl/cloud.rb
chef-utils/lib/chef-utils/dsl/windows.rb

These are used when building out descriptions in the vscode plugin so
getting them right is important

Improve chef-utils helper descriptions

---

RELEASE_NOTES.md

Add Release Notes for 16.10

---

RELEASE_NOTES.md
lib/chef/resource/windows_env.rb
lib/chef/resource/windows_security_policy.rb
lib/chef/resource/windows_share.rb
tasks/docs.rb

1) document default actions
2) split out warnings/notes from property descriptions not just resource descriptions

Improve the auto generation of documentation

---

Gemfile.lock
omnibus/Gemfile.lock

Update Ohai to 17.0.17

---

Gemfile.lock

Update Ohai to 17.0.18 for alibabalinux support

---

lib/chef/resource/alternatives.rb
lib/chef/resource/apt_preference.rb
lib/chef/resource/apt_repository.rb
lib/chef/resource/apt_update.rb
lib/chef/resource/archive_file.rb
lib/chef/resource/breakpoint.rb
lib/chef/resource/build_essential.rb
lib/chef/resource/chef_client_config.rb
lib/chef/resource/chef_client_cron.rb

Add more descriptions for docs generation

---

Gemfile.lock
omnibus/Gemfile.lock

Update pry-stack_explorer to 0.6.1

---

lib/chef/resource/powershell_script.rb

- [x ] Chore (non-breaking change that does not add functionality or fix an issue)
- [x ] I have updated the documentation accordingly.

Fix typo in powershell_script.rb

---

.expeditor/habitat-test.pipeline.yml
Gemfile.lock
omnibus/Gemfile.lock

Fix hab promotes + compile with -O3 for performance

---

omnibus/Gemfile.lock

Update to latest omnibus-software dep for openssl signing fix

---

Gemfile.lock
omnibus/Gemfile.lock

Pull in the latest of all our deps

Bump mixlib-archive, mixlib-shellout and omnibus

---

omnibus/Gemfile.lock

Bump omnibus to 8.1.1 for fastmsi fix

---

.expeditor/release.omnibus.yml

Update name of macos builder in Buildkite

---

.expeditor/release.omnibus.yml

It's past our support policy at this point

Stop producing packages for macOS 10.13

---

RELEASE_NOTES.md

16.10.17 notes

---

lib/chef/resource/file.rb
spec/unit/property_spec.rb
spec/unit/provider/group_spec.rb

fixes test broken by #11047 that i merged before coffee.

Fix tests broken by unlazying defaults

---

lib/chef/resource/template.rb

This hash probably needs to be open to mutation

Re-lazy the template variable default

---

lib/chef/resource/macos_userdefaults.rb
lib/chef/resource/mdadm.rb
lib/chef/resource/mount.rb
lib/chef/resource/openssl_ec_private_key.rb
lib/chef/resource/openssl_rsa_private_key.rb
tasks/docs.rb

Fix some markdown generation in the rake task and general cleanup of content in the resources.

Further improve docs generation

---

Gemfile.lock
omnibus/Gemfile.lock

This should fix our failures running chef-client

Update Ohai to 17.0.22

---

.expeditor/config.yml

Avoid needing to manually cut these PRs

Automatically create PRs to update chefstyle

---

lib/chef/compliance/default_attributes.rb
lib/chef/compliance/runner.rb
spec/unit/compliance/runner_spec.rb

The nil default is now the magic behavior while true or false asserts it
and overrides the magic.

Extend node["audit"]["compliance_phase"] to assert phase on or off

---

.expeditor/update_dep.sh

We need to know the dep we're updating throughout this script and if
it's not a gem we don't know the name. Allow passing in the name via arg

Update update_dep to allow passing in the dep to update

---

Gemfile.lock
chef.gemspec

Update our bcrypt_pbkdf dep to allow the final 1.1.0 release

---

kitchen-tests/kitchen.yml

This builds on the prior config which wasn't quite working in order to get appbundler running under devtoolset-8

Fix ffi installs on RHEL6 test-kitchen runs

---

omnibus/resources/chef/msi/localization-en-us.wxl.erb
omnibus/resources/chef/msi/source.wxs.erb

Removes install-as-service option which is not supported

---

.expeditor/config.yml

Automate more of our boring dep bumps

Add dep bump PRs for more win32 gems

---

lib/chef/compliance/default_attributes.rb
lib/chef/compliance/runner.rb
spec/unit/compliance/runner_spec.rb

This backports https://github.com/chef/chef/pull/11115 and https://github.com/chef/chef/pull/11111

Backport the ability to disable / enable compliance phase

---

kitchen-tests/kitchen.yml

Resolve Test Kitchen failures on Oracle 8

---

chef-utils/lib/chef-utils/dsl/introspection.rb
chef-utils/spec/unit/dsl/introspection_spec.rb

This uses our new effortless detection in Ohai

Add effortless? helper to chef-utils

---

cspell.json
kitchen-tests/cookbooks/end_to_end/recipes/_packages.rb

Remove installing htop in test

---

.expeditor/release.omnibus.yml

Use the new macOS 11 setting

---

RELEASE_NOTES.md

Clarify this is not a commercially supported distribution in chef.

Update how we describe Alma Linux in release notes

---

spec/integration/compliance/compliance_spec.rb
spec/unit/compliance/runner_spec.rb

Fix compliance phase specs

---

RELEASE_NOTES.md

Add release notes for Chef Infra Client 16.11

---

azure-pipelines.yml

Our old config does not make sense based on my reading of the docs

Fix Azure to trigger correctly on PRs

---

README.md

No changes, generating a build

---

omnibus/config/software/more-ruby-cleanup.rb

See:
https://github.com/ruby-prof/ruby-prof/pull/300

Fix ruby-prof loading issues

---

omnibus_overrides.rb

Update to the match the chef-16 branch

Update openssl to 1.1.1j and libarchive to 3.5.1

---

.expeditor/update_version.sh

This fails when we use ruby 2.7 on the current setup

Make sure we have Ruby 2.5 before bumping the version

---

.expeditor/update_version.sh

This has bundler out of the box

Use Ruby 2.6.6 in the version script instead

---

.expeditor/build.docker.yml
.expeditor/config.yml
.gitignore
Dockerfile
dobi.yaml

Use Dobi for container building

---

Gemfile
Gemfile.lock
chef.gemspec

Bump highline and remove duplicate deps

---

lib/chef/provider/package/freebsd/pkgng.rb
lib/chef/shell.rb
lib/chef/util/dsc/configuration_generator.rb
spec/unit/provider/package/freebsd/pkgng_spec.rb

Backport several fixes and improvements for Chef 16

---

Gemfile.lock
omnibus/Gemfile.lock

Update InSpec to 4.29.3

---

.expeditor/update_version.sh
.expeditor/verify.pipeline.yml
lib/chef/shell.rb
scripts/bk_tests/bk_container_prep.sh
scripts/bk_tests/bk_win_functional.ps1
scripts/ci/ensure-minimum-viable-hab.ps1

CI fixes backported from Chef 16

---

omnibus/README.md
omnibus/files/openssl-customization/windows/ssl_env_hack.rb
omnibus/kitchen.yml
omnibus/omnibus.rb
omnibus/package-scripts/angrychef/postinst
omnibus/package-scripts/angrychef/postrm

Sync over misc omnibus changes

---

RELEASE_NOTES.md

Add Release notes for 15.16

---

knife/lib/chef/knife.rb
knife/lib/chef/knife/bootstrap/chef_vault_handler.rb
knife/lib/chef/knife/bootstrap/train_connector.rb
knife/lib/chef/knife/supermarket_download.rb
lib/chef/cookbook/synchronizer.rb
lib/chef/cookbook_loader.rb
lib/chef/formatters/error_inspectors/resource_failure_inspector.rb
lib/chef/provider/git.rb
lib/chef/provider/package.rb
lib/chef/provider/package/rubygems.rb
lib/chef/provider/package/windows.rb
lib/chef/provider/service/freebsd.rb
lib/chef/provider/subversion.rb
lib/chef/provider/template/content.rb
lib/chef/provider/user/mac.rb
lib/chef/resource/dmg_package.rb
lib/chef/resource/windows_share.rb
spec/support/matchers/leak.rb
spec/unit/knife/core/gem_glob_loader_spec.rb

Get us ready for some additional detections in RuboCop 1.12

Remove more redundant begins detected by rubocop

---

Gemfile.lock
omnibus/Gemfile.lock

Update to the latest cheffish

---

lib/chef/provider/file.rb
spec/support/shared/unit/provider/file.rb

only run file verifiers when the contents changed

---

lib/chef/provider/service/macosx.rb
lib/chef/resource/chef_client_launchd.rb
spec/unit/provider/service/macosx_spec.rb

Signed-off-by: Jeff Johnson <jeff@jeffs-tech.com>

use full path for launchctl calls

---

Gemfile.lock
omnibus/Gemfile.lock

Update Ohai to 16.12.3

---

.expeditor/verify.pipeline.yml

Remove testing of Amazon Linux 201X

---

habitat/plan.ps1

Per mwrock we need to remove this core/git now.

Fix hab package builds

---

RELEASE_NOTES.md

Add 16.12.0 release notes

---

spec/spec_helper.rb

The inverted logic here hurts my head

Fix the cron skip on macOS logic

---

Gemfile.lock

Minor dep bump for parser

---

chef-utils/spec/unit/dsl/platform_family_spec.rb

Don't specify exact versions. Let fauxhai do what it does

Fix failing Fauxhai related specs

---

Gemfile.lock

Update Ohai to 16.13

---

omnibus/Gemfile.lock

revert change to bundler version

---

README.md

Trigger a new build of 15.x

---

RELEASE_NOTES.md

A small release to get the dsc fix out and the Ubuntu FIPS support out

Add 16.13 release notes

---

.expeditor/scripts/bk_run_choco.ps1
.expeditor/verify.pipeline.yml
.github/workflows/chefstyle.yml
.github/workflows/func_spec.yml
.github/workflows/lint.yml

Move some testing to GitHub Actions

---

.expeditor/verify.pipeline.yml
.github/workflows/spellcheck.yml
RELEASE_NOTES.md

Test running spellcheck in Github Actions

---

RELEASE_NOTES.md

This is the last 15. For realz this time.

Add release notes for 15.17

---

.expeditor/release.omnibus.yml

Produce packages for FreeBSD 13

---

lib/chef/win32/registry.rb

fix uninitialized Win32 constant

---

lib/chef/compliance/reporter/json_file.rb
lib/chef/compliance/runner.rb

Compliance Phase preflight validation updates

---

.expeditor/release.omnibus.yml

Disable FreeBSD builds for now

---

.github/workflows/unit_specs.yml

Add macos unit testing with GitHub actions

---

habitat/plan.sh

Update the habitat plan for Linux to Ruby 3

---

lib/chef/compliance/runner.rb

Also reduce logging level to debug for some output that isn't
generally going to be used in the normal case where everything goes
right.
This closes #11107.

Add start/end of compliance phase logging

---

Gemfile.lock

Add back the windows deps

---

tasks/rspec.rb

This should speed up our unit tests a good amount

Cache all our gems during spec runs

---

lib/chef/resource/apt_repository.rb
lib/chef/resource/chef_sleep.rb
lib/chef/resource/chocolatey_source.rb
lib/chef/resource/rhsm_errata.rb
lib/chef/resource/rhsm_errata_level.rb
lib/chef/resource/rhsm_register.rb
lib/chef/resource/rhsm_repo.rb
lib/chef/resource/rhsm_subscription.rb
lib/chef/resource/windows_env.rb

Make sure we properly generate docs

Improve the auto generated docs

---

omnibus/Gemfile

Signed-off-by: jayashri garud <jgarud@msystechnologies.com>
Added environment variables to load `omnibus` and `omnibus-software` gem dynamically from different repositories and branches
- [ X] Chore (non-breaking change that does not add functionality or fix an issue)
- [X ] I have read the **CONTRIBUTING** document.
- [X ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

updating Gemfile to support environment variables

---

habitat/plan.ps1

Update the Effortless package for Windows to Ruby 3

---

spec/integration/ohai/ohai_spec.rb

Put this back after we get a build out.

Disable the ohai time test so we can ship 17.0

---

knife/knife.gemspec

Fix building knife and make it require Ruby 2.7

---

RELEASE_NOTES.md

Document the unified_mode deprecation warning

---

RELEASE_NOTES.md

Update release notes to clarify windows change

---

knife/knife.gemspec

The way we shipped these blew up Ruby installs

Remove the specs from knife for now

---

.expeditor/verify.pipeline.yml

This was moved to the chef-boneyard.

Remove Chef Sugar from CI testing matrix

---

lib/chef/compliance/reporter/automate.rb
lib/chef/compliance/runner.rb

Update URLs in our Compliance Phase errors

---

.gitignore

Add gem files to the gitignore

---

spec/functional/resource/yum_package_spec.rb

Use the RecipeDSLHelper and disable all the repos for most of the tests

Yum func spec modernization

---

omnibus/Gemfile.lock

Update omnibus to unbreak builds

---

lib/chef/provider/directory.rb
spec/unit/chef_fs/file_system/repository/directory_spec.rb

Resolve File.exists? in directory provider

---

omnibus/Gemfile.lock

Add back windows deps to omnibus

---

lib/chef/node.rb

Stop the endless File.exists? spam from chef/node

---

lib/chef/provider/package/yum/python_helper.rb
lib/chef/provider/package/yum/yum_helper.py
spec/functional/resource/yum_package_spec.rb

This sync's the yum provider back up with the further work done
on the dnf provider.

Use buffered i/o for yum and disable repos in testing

---

cspell.json
kitchen-tests/cookbooks/end_to_end/recipes/windows.rb
lib/chef/resource/hostname.rb

Make sure the docs get generated correctly

Add introduced to the new hostname properties

---

.github/workflows/kitchen.yml
kitchen-tests/cookbooks/end_to_end/recipes/linux.rb

Test more platforms in Dokken / GH Actions

---

cspell.json
lib/chef/provider/mount/linux.rb
lib/chef/provider/mount/mount.rb
spec/unit/provider/mount/linux_spec.rb

This reverts commit 1d0ad75f33e74f1b9248f19c6f940deeaa3f5af7.

Revert "Kept a check in pattern matching for a mount of type loop"

---

.expeditor/config.yml

Remove knife from the expeditor config

---

lib/chef/resource/windows_task.rb
lib/chef/resource/windows_uac.rb
lib/chef/resource/windows_workgroup.rb
lib/chef/resource/yum_package.rb
lib/chef/resource/zypper_package.rb
lib/chef/resource/zypper_repository.rb

There should not be a space here

Fix markdown code blocks

---

lib/chef/resource/chef_client_config.rb
lib/chef/resource/chef_client_launchd.rb
lib/chef/resource/chef_client_scheduled_task.rb
lib/chef/resource/chef_client_systemd_timer.rb

Add additional action descriptions for docs

---

.github/workflows/kitchen.yml

Fix failing Test Kitchen tests in GitHub actions

---

lib/chef/resource/hostname.rb

Add introduced fields to the hostname resource

---

tasks/docs.rb

Properly generate the docs markdown notes sections

---

Gemfile.lock
omnibus/Gemfile.lock

Pull in the latest of everything

Update InSpec to 4.37.17 and bump omnibus

---

lib/chef/data_bag.rb
lib/chef/data_bag_item.rb
spec/unit/data_bag_item_spec.rb
spec/unit/data_bag_spec.rb

Signed-off-by: sanga17 <sausekar@msystechnologies.com>
Fixed incorrect regex, used for validating databag and databag item names.
Fixed: 1) https://github.com/chef/chef/issues/3697

knife: Raise an error when attempting to create data bags or data bag items with a period in the name

---

lib/chef/resource/inspec_waiver_file_entry.rb

inspec_waiver_file_entry: Autoload yaml and use dist file

---

knife/knife.gemspec

This is necessary for ruby-3.0 in chef-workstation

Bump the knife ffi dep

---

omnibus/Gemfile.lock

Update omnibus deps to the latest

---

lib/chef/resource/group.rb
lib/chef/resource/homebrew_cask.rb
lib/chef/resource/homebrew_package.rb
lib/chef/resource/homebrew_tap.rb
lib/chef/resource/homebrew_update.rb
lib/chef/resource/openbsd_package.rb
lib/chef/resource/osx_profile.rb
lib/chef/resource/plist.rb
lib/chef/resource/reboot.rb
lib/chef/resource/rhsm_repo.rb
lib/chef/resource/ssh_known_hosts_entry.rb
lib/chef/resource/sudo.rb

Get a few more resources to the point where they are 100% automatically generated. For others there's a long road ahead.

Improve the automatically generated docs

---

omnibus/Gemfile.lock

This should fix gem installs on windows

Update omnibus-software to the latest

---

lib/chef/resource/homebrew_package.rb

Add additional new lines to homebrew_package docs

---

RELEASE_NOTES.md

Add 17.2 release notes

---

Gemfile
Gemfile.lock
kitchen-tests/cookbooks/end_to_end/recipes/_packages.rb
omnibus/Gemfile.lock

We need to make sure this actually works

Add testing of installing knife into the client

---

lib/chef/resource/dsc_resource.rb
lib/chef/resource/execute.rb

Improve the content we generate

Minor improvements for our self documented resources

---

kitchen-tests/kitchen.azure.yml
kitchen-tests/kitchen.yml

Enable slow resource reporting in our kitchen tests

---

knife/knife.gemspec

Add the x25519 gem to knife

---

lib/chef/data_bag.rb
lib/chef/data_bag_item.rb
spec/unit/data_bag_item_spec.rb
spec/unit/data_bag_spec.rb

This reverts commit 19f127b7ff177bed0a0ebdfd2e0720f6acfc6bd2.
closes #11692

Revert "Fixed Validation failed while creating databag and databag item"

---

.github/workflows/kitchen.yml

Run Linux Kitchen jobs on Ruby 3

---

lib/chef/provider/file.rb
spec/support/shared/unit/provider/file.rb
spec/unit/provider/apt_update_spec.rb

cleaning up our own rspec output and ruby deprecations

eliminate some File.exists? from the file provider

---

Gemfile
Gemfile.lock
omnibus/Gemfile.lock

Get these builds working again.

Pin pry and fix omnibus gemfile.locki

---

.expeditor/release.omnibus.yml

Intel coming at a future date.

Produce packages for macOS 12 on Arm

---

.expeditor/release.omnibus.yml

We're doing this already with Chef 17

Enable FIPS on PPC RHEL builds

---

knife/spec/integration/cookbook_download_spec.rb
lib/chef/client.rb
lib/chef/json_compat.rb
lib/chef/provider/lwrp_base.rb
lib/chef/resource/lwrp_base.rb
spec/functional/mixin/from_file_spec.rb
spec/integration/recipes/recipe_dsl_spec.rb
spec/integration/recipes/resource_action_spec.rb

New engine found a few new things

Chefstyle fixes for RuboCop 1.18.3

---

omnibus/Gemfile.lock

Update omnibus/omnibus-software to the latest

---

lib/chef/resource/chef_client_cron.rb
lib/chef/resource/chef_client_launchd.rb
lib/chef/resource/chef_client_scheduled_task.rb
lib/chef/resource/chef_client_systemd_timer.rb

Signed-off-by: Ian Maddaus <Ian.Maddaus@progress.com>
Fix links to master agreement.

Fix links to master agreement

---

lib/chef/resource/chef_client_trusted_certificate.rb
lib/chef/resource/gem_package.rb
lib/chef/resource/habitat/habitat_package.rb
lib/chef/resource/habitat/habitat_sup.rb
lib/chef/resource/habitat_config.rb
lib/chef/resource/habitat_install.rb
lib/chef/resource/habitat_service.rb
lib/chef/resource/habitat_user_toml.rb

Update versions and get ready to generate 17.3 docs

Minor updates to fix docs generation

---

lib/chef/deprecated.rb
lib/chef/policy_builder/policyfile.rb
spec/unit/policy_builder/policyfile_spec.rb

Nobody on the planet should be using this.

Deprecate the old policyfile compat mode

---

lib/chef/resource/chef_client_config.rb
lib/chef/resource/support/client.erb

Make this super simple to enable.

chef_client_config: Add the ability to set policy_persist_run_list

---

.expeditor/release.omnibus.yml

Produce macOS m1 monterey packages

---

RELEASE_NOTES.md

Add release notes for 16.14

---

.expeditor/build-docker-images.sh
.expeditor/docker-manifest-create.sh
.expeditor/promote-docker-images.sh

Update use of environment variable when artifact is promoted

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/config.yml

Add adhoc canary pipeline for testing new omnibus workers

---

lib/chef/formatters/error_mapper.rb

Chef -> Chef Infra Client in error message

---

kitchen-tests/cookbooks/end_to_end/metadata.rb

Changes here broke running this cookbook on macOS / opensuse

Pin users cookbook in testing

---

knife/knife.gemspec

The failures in this gem have been resolved.

Add x25519 dependency back to knife

---

lib/chef/provider/execute.rb
lib/chef/provider/launchd.rb
lib/chef/resource/inspec_waiver_file_entry.rb
lib/chef/resource/launchd.rb
lib/chef/resource/remote_file.rb
tasks/docs.rb

Simplify how we remove the sensitive properties so we don't have to do
it multiple times.
Add missing action descriptions
Improve formatting on some property descriptions

Improve docs generation + update property / action descriptions

---

lib/chef/provider/subversion.rb
lib/chef/provider/systemd_unit.rb
lib/chef/provider/yum_repository.rb
lib/chef/provider/zypper_repository.rb
lib/chef/resource/ruby_block.rb
lib/chef/resource/scm/subversion.rb
lib/chef/resource/sysctl.rb
lib/chef/resource/systemd_unit.rb
lib/chef/resource/yum_package.rb

Improve the automatically generated docs.

Add more descriptions to actions for documentation

---

knife/lib/chef/knife/cookbook_upload.rb
knife/spec/unit/knife/cookbook_upload_spec.rb

Sometimes you just want to upload cookbooks without worrying about whether or not the dependencies exist on Chef Infra Server. The actual call to check if all cookbooks exist is somewhat expensive on servers with a lot of cookbooks so giving folks the ability to bypass that could be useful for scaling.
N/A

Optionally check for cookbook dependencies when using knife cookbook upload

---

RELEASE_NOTES.md

Add Chef Infra Client 17.4 release notes

---

Gemfile.lock
omnibus/Gemfile.lock

Update InSpec to 4.41

---

.buildkite/hooks/pre-command
.expeditor/config.yml
.expeditor/scripts/install-hab.sh
.expeditor/update_bundler_dep.sh
.expeditor/update_dep.sh
.expeditor/verify.pipeline.yml
.github/workflows/func_spec.yml
.github/workflows/kitchen.yml
.github/workflows/lint.yml
Gemfile
Gemfile.lock
omnibus_overrides.rb

Fixes some of the old references.  I have a bit of a suspicion that we have a catch-22 and need to merge this to make more stuff green.

testing main

---

lib/chef/formatters/doc.rb
lib/chef/formatters/minimal.rb
spec/unit/formatters/doc_spec.rb

- Make it clear when Infra Phase starts
- Make capitalizations consistent
- Use Policyfile branding

Improve phase logging

---

Gemfile.lock
kitchen-tests/Gemfile
kitchen-tests/README.md
omnibus/Gemfile.lock

Cutover some branches and update some docs while I'm here

Fix Test Kitchen tests

---

.expeditor/verify.pipeline.yml
tasks/bin/run_external_test

These are still on master for now

Fix chefspec and berkshelf tests

---

lib/chef/compliance/reporter/automate.rb
lib/chef/compliance/runner.rb
lib/chef/formatters/doc.rb
lib/chef/formatters/minimal.rb

Be more clean when infra phase starts and ends and what the compliance
report is.

More updates to logging wording

---

Gemfile.lock

Remove the yanked parallel 1.20.2 gem

---

knife/lib/chef/knife/client_create.rb
knife/spec/integration/client_create_spec.rb
knife/spec/unit/knife/client_create_spec.rb

Fix knife client create

---

.expeditor/release.omnibus.yml

Build packages on Intel macOS 12

---

knife/knife.gemspec

Disable x25519 until we fix RHEL 7 failures

---

.buildkite/hooks/pre-command
.expeditor/scripts/bk_win_prep.ps1
.expeditor/verify.pipeline.yml
kitchen-tests/Gemfile
omnibus/Gemfile

Signed-off-by: swati keshari <swatikeshari4@gmail.com>

Replace deprecated --without flag with bundle config

---

lib/chef/resource/chef_client_scheduled_task.rb

Add a description to use_consistent_splay

---

omnibus_overrides.rb

Update libarchive and openssl to the latest

---

.expeditor/release.omnibus.yml

Build on macOS 12 x86

---

lib/chef/dsl/secret.rb

Make the beta warning less scary

---

lib/chef/provider/registry_key.rb
lib/chef/resource/registry_key.rb

Create the `values` property using DSL. This also fixes the bug with the property that was reported in #11877 
#7066 
#11877

registry_key: convert values to a real property

---

lib/chef/resource/homebrew_cask.rb
spec/unit/resource/homebrew_cask_spec.rb

Backport https://github.com/chef/chef/pull/11842

Support '-' and '@' for homebrew cask name

---

lib/chef/resource/systemd_unit.rb
spec/unit/resource/systemd_unit_spec.rb

Backport https://github.com/chef/chef/pull/11856

systemd_unit generates invalid units when passing a hash issue fix

---

lib/chef/win32/api.rb

Backport https://github.com/chef/chef/pull/11472

use int64 on x64 architecture for LPARAM and LONG_PTR types

---

cspell.json
lib/chef/provider/template/content.rb

Backport https://github.com/chef/chef/pull/11540

Fix a typo setting up cookbook_name value in templates

---

lib/chef/resource/homebrew_cask.rb

Backport https://github.com/chef/chef/pull/11607

pass homebrew_path, owner props to homebrew_tap if installing cask

---

spec/functional/resource/group_spec.rb
spec/functional/resource/link_spec.rb

Backport https://github.com/chef/chef/pull/12004

Fix tests for new omnibus test systems

---

lib/chef/resource/user_ulimit.rb
spec/unit/resource/user_ulimit_spec.rb

Backport https://github.com/chef/chef/pull/12000

ulimit: Fix sensitive property

---

lib/chef/resource/windows_uac.rb

Backport https://github.com/chef/chef/pull/11987

windows_uac: fix registry settings for consent_behavior_users

---

lib/chef/http.rb

Backport https://github.com/chef/chef/pull/11945

Downgraded the Log level to warn as per AHA idea I-25

---

lib/chef/cookbook_version.rb
lib/chef/exceptions.rb
spec/unit/cookbook_version_spec.rb

Backport https://github.com/chef/chef/pull/11629

Support recipes that end in .yaml as well as .yml 

---

kitchen-tests/cookbooks/end_to_end/recipes/_chef_client_config.rb
lib/chef/resource/support/client.erb

Backport https://github.com/chef/chef/pull/11766

Fix handling of ohai properties in chef_client_config

---

lib/chef/deprecated.rb

Backport https://github.com/chef/chef/pull/11749

Fix edge condition in deprecation silence checker

---

lib/chef/resource/mount.rb
spec/unit/resource/mount_spec.rb

Backport https://github.com/chef/chef/pull/12022

Coerce mount_point only when it is not root directory

---

chef-config/lib/chef-config/config.rb
lib/chef/data_collector/run_end_message.rb
lib/chef/deprecated.rb
lib/chef/node.rb
spec/unit/data_collector_spec.rb

https://github.com/chef/chef/pull/11674

Support attribute block/allow list in data collector

---

lib/chef/provider/package/powershell.rb
spec/unit/provider/package/powershell_spec.rb

Backport https://github.com/chef/chef/pull/11793

Add user provided options to powershell_package commands 

---

lib/chef/resource/windows_security_policy.rb

Backport https://github.com/chef/chef/pull/11533

windows_security_policy: Add AuditPolicyChange and LockoutDuration capabilities

---

kitchen-tests/cookbooks/end_to_end/recipes/windows.rb
lib/chef/resource/windows_security_policy.rb
spec/unit/resource/homebrew_cask_spec.rb

Backport https://github.com/chef/chef/pull/10699

Refactor the code for windows_security_policy resource

---

lib/chef/resource/rhsm_subscription.rb
spec/unit/resource/rhsm_subscription_spec.rb

Backport https://github.com/chef/chef/pull/11534

Flush package cache after attaching to rhsm subscription

---

.github/workflows/kitchen.yml

Test on Windows 2022 in GitHub actions

---

omnibus/omnibus-test.sh
omnibus/package-scripts/angrychef/postinst
omnibus/package-scripts/chef/postinst

We've been setting up broken symlinks to knife which no longer ships with this package.

Don't setup broken symlink to knife

---

.expeditor/verify.pipeline.yml

try a build with no vendor caching

---

spec/functional/resource/archive_file_spec.rb
spec/spec_helper.rb
spec/support/ruby_installer.rb
spec/unit/resource/archive_file_spec.rb

Fix unit and integration tests in CI environment on Windows.
- #11907

Fix windows CI for archive_file

---

.expeditor/config.yml

Manually specify what should happen when we promote via Slack.

Specify promotion actions in .expeditor/config.yml

---

.expeditor/config.yml
spec/unit/resource/archive_file_spec.rb

Manually specify what should happen when we promote via Slack.

Add promotion logic to .expeditor/config.yml

---

.expeditor/config.yml

fix typo in promotion command

---

.expeditor/release.omnibus.yml

Add Debian / Windows 11 / Windows 2022 packages

---

.expeditor/release.omnibus.yml

Add Windows 11, Windows 2022, and Debian 11 builds

---

.expeditor/announce-release.sh

We need to make sure these commands don't actually get run when the script executes.
Signed-off-by: Tom Duffield <github@tomduffield.com>

Escape special characters in announce-release

---

.expeditor/announce-release.sh

Don't run commands when evaluating the script.
Signed-off-by: Tom Duffield <github@tomduffield.com>

Fix announce script

---

lib/chef/resource/inspec_input.rb
lib/chef/resource/inspec_waiver.rb

Signed-off-by: Ian Maddaus <Ian.Maddaus@progress.com>
Docs edits for inspec_insput and inspec_waiver to match what is in chef-web-docs.

Docs edits for inspec_input and inspec_waiver resources

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/release.omnibus.yml

Revert "Remove EOL FreeBSD 11 builds"

---

lib/chef/resource/powershell_package_source.rb

Fix some invalid ruby

---

omnibus/Gemfile.lock

https://github.com/chef/omnibus-software/pull/1453

Fix compilation of openssl with -DOPENSSL_TRUSTED_FIRST_DEFAULT

---

spec/integration/knife/delete_spec.rb
spec/integration/knife/download_spec.rb
spec/integration/knife/upload_spec.rb

Backport CI fixes for policy_group_list changes in knife

---

omnibus/Gemfile.lock

Fixes Gemfile.lock conflicts with dependabot

Bump gems manually

---

lib/chef/resource.rb
lib/chef/resource/execute.rb
lib/chef/resource/launchd.rb

Add string to umask properties in all resources

---

lib/chef/compliance/default_attributes.rb
lib/chef/compliance/runner.rb
spec/unit/compliance/runner_spec.rb

Make the compliance CLI reporter always run

---

lib/chef/compliance/default_attributes.rb
lib/chef/compliance/runner.rb
spec/unit/compliance/runner_spec.rb

Copies the API from the audit cookbook including the same attributes

Implement compliance phase interval runs

---

spec/unit/provider/package/rubygems_spec.rb

Rubygems 3.2.x spec fixes

---

.rubocop.yml
kitchen-tests/cookbooks/end_to_end/recipes/_powershell_package.rb
lib/chef/provider/package/powershell.rb
spec/unit/provider/package/powershell_spec.rb

As discussed, I've created this PR to put back the changes reverted after the original PR was merged. 
Related comment https://github.com/chef/chef/issues/10926#issuecomment-964487573

use powershell exec in powershell resource

---

lib/chef/resource/chef_client_config.rb
lib/chef/resource/powershell_package_source.rb
lib/chef/resource/rhsm_register.rb

These came out of https://github.com/chef/chef-web-docs/pull/3592

Resource docs update from docs review

---

spec/functional/resource/dnf_package_spec.rb

This synchronizes them better with the yum provider.

Update the DNF spec tests with a helper

---

lib/chef/provider/cron.rb
lib/chef/provider/directory.rb
lib/chef/provider/ifconfig.rb
lib/chef/provider/package.rb
lib/chef/resource/apt_package.rb
lib/chef/resource/chocolatey_package.rb
lib/chef/resource/cron/cron.rb
lib/chef/resource/cron/cron_d.rb
lib/chef/resource/windows_task.rb

Get closer to generating resources from the codebase.

Move more documentation into the code

---

.expeditor/announce-release.sh
chef-utils/lib/chef-utils/dist.rb
docs/dev/how_to/building_and_installing.md
lib/chef/resource/cron/cron.rb

Things are in different places now.

Update for the new downloads site

---

spec/functional/resource/yum_package_spec.rb

I absolutely do not understand this failure case or how to
fix or even necessarily how to debug it.

Disable one yum test on rhel6

---

.expeditor/config.yml

It's causing lots of failures
https://github.com/chef/infra-packages-team/issues/30#issuecomment-998754197

Disable omnibus caching in buildkite

---

spec/functional/resource/yum_package_spec.rb

still trying to beat on RHEL6 to get it to work

correctly bounce the helper a couple of times

---

spec/functional/resource/yum_package_spec.rb

It was never getting to the first bounce

Bounce the yum tests more aggressively

---

tasks/docs.rb

Resolve Style/MapToHash chefstyle warning

---

chef-config/lib/chef-config/config.rb
knife/lib/chef/knife/acl_bulk_add.rb
knife/lib/chef/knife/acl_bulk_remove.rb
knife/lib/chef/knife/core/subcommand_loader.rb
knife/spec/knife_spec_helper.rb
lib/chef/cookbook/syntax_check.rb
spec/spec_helper.rb

Simplify how we collect or reject data based on regex matches

Resolve Style/SelectByRegexp warnings

---

chef-config/lib/chef-config/config.rb
knife/spec/support/platform_helpers.rb
lib/chef/provider/package.rb
lib/chef/resource_reporter.rb
lib/chef/run_lock.rb
spec/support/platform_helpers.rb
spec/support/shared/functional/file_resource.rb
spec/support/shared/unit/provider/useradd_based_user_provider.rb
spec/unit/dsl/registry_helper_spec.rb
spec/unit/guard_interpreter/resource_guard_interpreter_spec.rb
spec/unit/lwrp_spec.rb
spec/unit/provider/dsc_script_spec.rb
spec/unit/provider/group/usermod_spec.rb
spec/unit/provider/ifconfig/aix_spec.rb
spec/unit/provider/ifconfig/debian_spec.rb
spec/unit/provider/ifconfig/redhat_spec.rb
spec/unit/provider/ifconfig_spec.rb
spec/unit/provider/remote_file/cache_control_data_spec.rb
spec/unit/provider/service/gentoo_service_spec.rb
spec/unit/provider/service/upstart_service_spec.rb
spec/unit/resource/conditional_spec.rb
spec/unit/resource_spec.rb

Internally it's all a symbol so skip the conversion

Resolve Performance/StringIdentifierArgument warnings

---

knife/lib/chef/knife/core/generic_presenter.rb
knife/spec/unit/knife/environment_list_spec.rb

Simplify and speed up the sorts

Resolve Performance/RedundantSortBlock warnings

---

lib/chef/application/exit_code.rb
lib/chef/provider/user/mac.rb
lib/chef/resource/launchd.rb
lib/chef/resource/remote_file.rb

I'm confused how this works with classes, but :shrug:

Resolve all Performance/RedundantEqualityComparisonBlock warnings

---

.expeditor/release.omnibus.yml

Add Amazon 2022 to our pipeline

---

Gemfile.lock
omnibus/Gemfile.lock

Bump package gems and omnibus gems

---

lib/chef/resource/habitat/habitat_sup.rb

Signed-off-by: Ian Maddaus <ian.maddaus@progress.com>
private.net is owned by somebody. It should really be example.com.
See also chef/chef-web-docs#3656
chef/chef-web-docs#3655

replace links in resource doc examples

---

.expeditor/config.yml

Add an expeditor corefoundation subscription

---

chef-utils/lib/chef-utils/dist.rb

Add constant for ChefServer system user
Add constant for ChefServer system user, related to https://github.com/chef/chef-server/pull/3101

Add constant for ChefServer system user

---

lib/chef/resource/lwrp_base.rb

Suppress deprecation warning for chef-client-updater cookbook

---

chef-utils/lib/chef-utils/dist.rb

Add constant for ChefServer`s docs url
Add constant for ChefServer system user, related to chef/chef-server#3101

Chef 18 - Added constant with Server`s docs url

---

chef-utils/lib/chef-utils/dist.rb

Add constant for ChefServer`s docs url
Add constant for ChefServer system user, related to chef/chef-server#3101

Chef 16 - Add constant for ChefServer`s docs url

---

chef-config/lib/chef-config/config.rb
cspell.json

Adding support to move the client.pem to secure storage

---

knife/docs/dev/README.md

Signed-off-by: Vikram Karve <vikram.karve@progress.com>
Helps new developers get familiar with the development setup and overall structure of knife.
https://github.com/chef/chef/issues/11955

Initial draft of knife developer guide

---

lib/chef/resource/archive_file.rb
spec/functional/resource/archive_file_spec.rb
spec/spec_helper.rb
spec/unit/resource/archive_file_spec.rb

Closes #12228
Extensive details in https://github.com/chef/chef/issues/12228
Replaces #12375

Eager load ffi-libarchive to resolve centos-7 failures

---

lib/chef/resource/archive_file.rb
spec/unit/resource/archive_file_spec.rb

(Backport) Eager load ffi-libarchive to resolve centos-7 failures

---

Gemfile.lock
chef.gemspec
omnibus/Gemfile.lock

net-ftp isn't bundled in Ruby 3.1 anymore so dep on it

---

kitchen-tests/kitchen.yml

Make sure network scripts dir exists on alma

---

lib/chef/compliance/default_attributes.rb
lib/chef/compliance/reporter/compliance_enforcer.rb
lib/chef/compliance/runner.rb
spec/unit/compliance/reporter/compliance_enforcer_spec.rb

Signed-off-by: Collin McNeese <cmcneese@chef.io>
- Updates to fix error in #12589 for `audit-enforcer` reporter.
- Adds `compliance-enforcer` as an available reporter option to eventually replace `audit-enforcer`.  Does **not** remove `audit-enforcer` as a reporter at this time so that this is not a breaking change.
#12589

fixes for #12589 for compliance audit-enforcer reporter

---

Gemfile.lock
chef.gemspec
kitchen-tests/cookbooks/end_to_end/recipes/_chef_gem.rb
omnibus/Gemfile.lock

Chef-17 backport of diff-lcs pin update

---

kitchen-tests/kitchen.yml

Upgrade compilers on centos-7 kitchen tests

---

lib/chef/api_client.rb
lib/chef/policy_builder/expand_node_object.rb
lib/chef/policy_builder/policyfile.rb
lib/chef/provider/package/rubygems.rb
lib/chef/provider/service/windows.rb
lib/chef/provider/user/windows.rb

This fixes spec failures that came in with the recent point release of rspec and some of the code changes may fix actual ruby 3.0 errors in chef-17/18

More ruby 3.0 fixes

---

.expeditor/config.yml

Signed-off-by: Tim Smith <tsmith84@gmail.com>

Add train version update subscriptions

---

kitchen-tests/kitchen.yml

This trips me up literally every time

Stop cleaning the dokken sandbox

---

lib/chef/provider/package/yum/python_helper.rb
spec/functional/resource/dnf_package_spec.rb
spec/functional/resource/yum_package_spec.rb

This fixes regressions from #10823
Closes #12557
addresses chef/customer-bugs#602 and chef/customer-bugs#599

Fix multiple regressions in yum_package provider

---

omnibus_overrides.rb

Signed-off-by: Tim Smith <tsmith84@gmail.com>

Update to libffi 3.4.2

---

chef-utils/lib/chef-utils/dist.rb

This will be useful in getting proper seamless community distribution support in test-kitchen (and likely other places).

Add OMNITRUCK_URL dist constant

---

chef-utils/lib/chef-utils/dist.rb

This will be useful in getting proper seamless community distribution support in test-kitchen (and likely other places).

Chef 17: Add OMNITRUCK_URL dist constant

---

lib/chef/provider/package/yum/python_helper.rb
spec/functional/resource/dnf_package_spec.rb
spec/functional/resource/yum_package_spec.rb

This fixes regressions from #10823
Closes #12557
addresses chef/customer-bugs#602 and chef/customer-bugs#599

Chef-17 backport: Fix multiple regressions in yum_package provider

---

lib/chef/provider/http_request.rb
spec/unit/provider/http_request_spec.rb

No changes to implementation, just doing some code cleanup.

Modernize the http_request resource code and specs

---

.github/workflows/kitchen.yml

forward port the work john did on chef-17

Fix windows kitchen tests

---

.expeditor/promote-docker-images.sh

Minor fix to conditional in promote-docker-images.sh

---

Gemfile.lock
lib/chef/provider/package/powershell.rb

Package resource was calling a non-existent error method

---

.github/workflows/kitchen.yml

Removed Windows Server 2016 from testing per Github

---

chef-utils/lib/chef-utils/mash.rb
lib/chef/node/attribute.rb
lib/chef/node/mixin/deep_merge_cache.rb

backport of https://github.com/chef/chef/pull/12742

Fix attribute performance issues in node.read (Chef-16)

---

omnibus_overrides.rb

Fixes xml2-config check in configure script

Bump libxslt to 1.1.35

---

omnibus/Gemfile.lock

Bump omnibus-software in Gemfile.lock

---

knife/lib/chef/knife/user_create.rb
knife/spec/unit/knife/user_create_spec.rb

This Change is already [merged](https://github.com/chef/chef/pull/12619) in the main branch. Raising PR for to merge in `chef-17` branch
- https://github.com/chef/chef-workstation/issues/2505

Fix pem generation when user created

---

Gemfile.lock
omnibus/Gemfile.lock

Bundle update to update update Gemfile.lock and omnibus/Gemfile.lock

Chef 17: Update all dependencies with bundle update

---

Gemfile.lock
omnibus/Gemfile.lock

main - Update bundle

---

lib/chef/resource/support/client.erb

backport https://github.com/chef/chef/pull/12817 to chef-16

Fix chef_client_config template rendering

---

lib/chef/dsl/secret.rb
lib/chef/run_context.rb
spec/unit/dsl/secret_spec.rb
spec/unit/run_context_spec.rb

Backport #12140 to chef-17

---

omnibus/omnibus-test.ps1

Use Throw instead of Exit to ensure the CI job fails when a command has
a non-zero exit code.

Fix omnibus-test.ps1

---

lib/chef/compliance/input_collection.rb
lib/chef/compliance/profile_collection.rb
lib/chef/compliance/waiver_collection.rb

adding exception to bypass nil class error in the compliance phase
https://github.com/chef/customer-bugs/issues/671

handling exception for compliance phase error during chef spec run

---

knife/lib/chef/knife/configure.rb

This will resolve
https://gitlab.com/cinc-project/distribution/workstation/-/issues/22.

Chef 17: Use dist constant when invoking knife configure

---

.expeditor/config.yml

Signed-off-by: Prajakta Purohit <prajakta@chef.io>

Update the command to enable adhoc jobs for chef/chef main pipeline

---

lib/chef/resource/locale.rb

Signed-off-by: Hans Rakers <hans@shoq.com>
See #12832 for details
#12832

Backport to 16: Stop executing locale-gen on every chef run

---

.expeditor/release.omnibus.yml

Signed-off-by: poornima <poorndm@progress.com>

Add AIX-7.3 to Build Matrix

---

knife/spec/support/platform_helpers.rb
spec/functional/resource/group_spec.rb
spec/spec_helper.rb
spec/support/platform_helpers.rb

Signed-off-by: Poornima <94897054+poorndm@users.noreply.github.com>
Currently the adhoc pipeline on FreeBSD fails with Permission denied errors when functional tests are being run to create groups.
Reference  Failed build: https://buildkite.com/chef/chef-chef-main-omnibus-adhoc/builds/1154#01818f4e-6b47-401e-837c-61edd38a2146
**Error** 
`3) Chef::Resource::Group group modify action when there is a group behaves like correct group management when no users exist when append is not set should raise an error
Failure/Error: shell_out!(command)
Mixlib::ShellOut::ShellCommandFailed:
group[grp3997] (dynamically defined) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of ["pw", "groupadd", "grp3997", "-g", "3997"] ---- …

Skip tests on FreeBSD-13

---

chef-config/lib/chef-config/workstation_config_loader.rb

Many other packages require `etc` but when using chef-config directly without requiring `etc` first, the code fails with a NameError at runtime. This only happens inconsistently and varies by ruby version because many other tools and packages require `etc`.
```ruby
~/scratch $ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
~/scratch $ irb
WARNING: This version of ruby is included in macOS for compatibility with legacy software.
In future versions of macOS the ruby runtime will not be available by
default, and may require you to install an additional package.
irb(main):001:0> Etc.getlogin
Traceback (most recent call last):
4: from /usr/bin/irb:23:in `<main>'
3: from /usr/bin/irb:23:in `load'
2: from /Library/Ruby/Gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in …
```

Require etc library

---

docs/dev/how_to/adding_documentation_to_infra_resources.md

Added how to doc with details about documentation for infra client resources

---

habitat/config/client.rb
habitat/default.toml
habitat/hooks/run
habitat/plan.ps1
habitat/plan.sh

This just adds a habitat  windows plan and updates the plan.sh for ther `chef-14` branch. We would like to possibly be ablt to provide this legacy habitat package for future work.

update habitat plans to package chef 14

---

.expeditor/config.yml
.expeditor/scripts/verify-plan.ps1

Added custom environment variables to the config.yml to get the builds automated
Added custom environment variables to the config.yml to get the builds automated

Tweaking env variables in the config.yml file

---

omnibus/Gemfile
omnibus/Gemfile.lock

omnibus-software version was previously forced to point at a fix branch, but now the omnibus-software update has been merged, so we're restoring back the original spec with override with a one time checksum update.

Force omnibus version

---

omnibus/Gemfile.lock
spec/functional/shell_spec.rb
spec/unit/daemon_spec.rb

[Fix Solaris tests](https://chefio.atlassian.net/browse/INFC-274)

Fix term and privilege related broken tests in Solaris build

---

.expeditor/verify.pipeline.yml

All the OpenSUSE tests were failing in the verify pipeline with checksum mismatches when downloading various packages needed by Chef. After some trial and error, the issue turned out to be that the default 'repo-oss' repo was corrupt somehow and I got past that by specifying a new repo with a higher priority that had the same attributes as the default repo did. There is a LOT that goes into package management on some Linux distros. The solution was to modify the verify-pipline.yml and add the following command to the top of the command list for all 3 test phases.
This command causes zypper to create a new repo, add the url for it, and set it to autorefresh. The default priority for built-in repositories is 99; meaning that all others …

Adding a new repository to ensure images match the cache

---

docs/dev/how_to/releasing_chef_infra.md

Signed-off-by: Bapu L <bapu.labade@progress.com>
Updated release notes to consider cook style verification step
Updated release notes to consider cook style verification step

Updated release notes to consider cookstyle verification point

---

.expeditor/verify.pipeline.yml

Correcting the repos for OpenSUSE
The default repos used by openSUSE are failing for some reason. We add this new one in with a higher priority to solve the problem.

[Chef-17] Adding a new Zypper repo with a higher priority

---

omnibus/Gemfile.lock
spec/functional/shell_spec.rb
spec/unit/daemon_spec.rb

Signed-off-by: Bapu L <bapu.labade@progress.com>
Update omnibus version to fix read_shared_libs to fix solaris adhoc pipeline issue

[chef-17] Update omnibus version to fix read_shared_libs to fix solaris adhoc pipeline issue

---

.github/workflows/kitchen.yml

17 should be tested with 17 on 17.

Fix chef-17 pipelines

---

.expeditor/scripts/bk_win_functional.ps1
.expeditor/verify.pipeline.yml

We see below error when trying activate ruby 2.7.1 using uru. 
```
Enable Ruby 2.7
Add Uru to Environment PATH
Register Installed Ruby Version 2.7 With Uru
---> unable to find registered ruby matching `271`
ruby : The term 'ruby' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\bk0183d1ce43cae537744f\.expeditor\scripts\bk_win_functional.ps1:20 char:1
+ ruby -v
```
We concluded that we would get rid of the patch version so that it will activate the corresponding installed ruby 2.7.x version accordingly.
Also updated the **timeout** set for running functional tests on windows due to …

[chef-16] Fix windows functional test ruby activation failure under verify pipeline 

---

CHEF_MVPS.md

Adds recipients of Awesome Chef Awards 2021/2022 as per https://www.chef.io/blog/21-awesome-chef-awards and https://www.chef.io/blog/chefconf-22-recap-product-announcements-key-takeaways
Congratulations, winners, Jeff , Ben, Lamont, Lance, Brittany, and Takuya:
- @sam1el
- @bmhughes
- @lamont-granquist
- @ramereth
- @bnwoods
- @tnir
Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)
Community Slack thread: https://chefcommunity.slack.com/archives/C1P99AXGV/p1663862509310589
- [n/a] I have run the pre-merge tests locally and they pass.
- [n/a] I have added tests to cover my changes.
- [n/a] All new and existing tests passed.

Add recipients of Awesome Chef Awards 2021/2022

---

.github/workflows/kitchen.yml

#13362 incorrectly made changes to main kitchen tests instead of chef-16
INFC-366

Switch main back to current for kitchen

---

cspell.json
docs/dev/how_to/releasing_chef_infra.md

Updated post Chef-18 to clarify how to release

---

.expeditor/config.yml

Adding Knife back into the list of gems to release automagically

---

.expeditor/config.yml

Remove additional space in nightly scheduler, update chef16 nightlies to run every day instead of only Tue and Thu.

[Chef-16] Fix issue in nightlies

---

.github/workflows/lint.yml
.rubocop.yml
chef-config/chef-config.gemspec
chef-utils/chef-utils.gemspec
chef.gemspec

Rolling back Ruby2.7 support to Ruby 2.6

---

.expeditor/config.yml

The version bumps are not working for sometime, I trying out if due to changes to config file, though correct.
I'm trying to bring the config file to state before things stopped working, to see if things start working again

[Chef-16] Remove IGNORE_CACHE true from expeditor file

---

kitchen-tests/Gemfile

[Chef-16] Updating Berkshelf to point to the chef repo

---

lib/chef/win32/version.rb

Updating the windows version file to include Windows 11

---

Gemfile
Gemfile.lock

recorrecting the ssl errors in chef-16

---

.expeditor/release.omnibus.yml
omnibus/omnibus-test.ps1
spec/integration/client/fips_spec.rb
spec/spec_helper.rb
spec/support/platform_helpers.rb

Neither the system that we're building the 32-bit Windows distribution on nor the operating system that it's being tested on are 32-bit Windows distributions.

INFC-373 Disable 32-bit Windows for Chef 16

---

Gemfile.lock
knife/Gemfile.lock
knife/lib/chef/knife/download.rb
knife/lib/chef/knife/upload.rb
lib/chef/chef_fs/file_system.rb
spec/unit/chef_fs/file_system_spec.rb

Signed-off-by: Vinay Satish <vinay.satish@progress.com>

updating file_system to send back the copy status

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/verify.pipeline.yml

s390x images were throwing errors when loading updates because they were attempting to connect to the localhost instead of the Internet to get updates.
The issue for this turned out to be that at some point in the automation process before the chef-client code runs, something is creating/adding Zypper respositories that point to the localhost. That is totally busted since there are no files locally to support that and there is no way to pull down new files outside of the busted local repos. 
The cause of that issue has not been fully determined but we did workaround that issue by doing 2 things: 1) Sean manually deleted the borked repos on those images. (they don’t get recycled like other OS images do). and 2) I added to code to …

Updating Zypper to overcome repository errors

---

lib/chef/resource/rhsm_register.rb

Backport https://github.com/chef/chef/pull/12828 to chef-16

backport to 16: flush package cache after registering or unregistering with rhsm_register

---

.buildkite/verify.pipeline.sh

Updating Dynamic Pipeline To Use Heredocs

Updating Dynamic Pipeline To Use Heredocs

---

lib/chef/resource/dsc_script.rb
lib/chef/resource/launchd.rb
lib/chef/resource/rhsm_register.rb
lib/chef/resource/selinux_fcontext.rb
lib/chef/resource/selinux_permissive.rb
lib/chef/resource/selinux_port.rb
lib/chef/resource/selinux_state.rb
lib/chef/resource/service.rb
lib/chef/resource/user.rb
lib/chef/resource/windows_user_privilege.rb

Signed-off-by: Ian Maddaus <ian.maddaus@progress.com>
This updates resources description text to match what is on docs.chef.io

Edit resources description text

---

CONTRIBUTING.md
cspell.json
docs/dev/how_to/releasing_chef_infra.md

Update documentation to prevent accidental blocking of parts of the release process by manual intervention or skipping of the documentation step.

Docs and release details

---

lib/chef/provider/cron.rb
spec/unit/provider/cron_spec.rb

Fix false updates on cron resource when using integers.
This PR backports https://github.com/chef/chef/pull/13147 to Chef16.
https://github.com/chef/chef/issues/12311

[Chef-16] [Backport 13147]: Fix false updates on cron when using integers

---

kitchen-tests/kitchen.yml

Signed-off-by: Gregory Schofield <grschofi@progress.com>
Change the environment variable from BUILDKITE_COMMIT since these tests run in github actions.

Change to github commit sha.

---

Gemfile.lock
omnibus/Gemfile.lock

Signed-off-by: John McCrae <mccrae@progress.com>

Updating gems

---

lib/chef/resource/apt_repository.rb
spec/unit/provider/apt_repository_spec.rb

This makes it so that the apt keys are updated if the expiration of a key is updated without changing the fingerprint.
See: https://gitlab.com/gitlab-cookbooks/cookbook-gitlab-runner/-/merge_requests/37/diffs#35cd6a49d9e22469db42af7a30c5f3a76487e3c7
Fixes: #13308
Signed-off-by: Thayne McCombs

fix(apt_repository): Detect changes to expiration in key

---

.expeditor/habitat-test.pipeline.yml
.expeditor/scripts/ensure-minimum-viable-hab.ps1
.expeditor/scripts/habitat-test.ps1

Habitat test pipeline has below error:
```
error: The following required arguments were not provided:
<PKG_IDENT_OR_ARTIFACT>...
USAGE:
hab.exe pkg install <PKG_IDENT_OR_ARTIFACT>... --binlink-dir <BINLINK_DIR> --channel <CHANNEL>
For more information try --help
Unable to install
At C:\bk01862687c5f0c27d3878\.expeditor\scripts\habitat-test.ps1:10 char:16
+ ... (-not $?) { throw "Unable to install $EXPEDITOR_PKG_IDENTS_CHEFINFRAC ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Unable to install :String) [], RuntimeException
+ FullyQualifiedErrorId : Unable to install
```
Ref: https://buildkite.com/chef/chef-chef-chef-16-habitat-test/builds/260#01862687-1d8e-4d …

[Chef-16] Fix habitat test pipeline windows

---

omnibus/config/software/chef-local-source.rb

Signed-off-by: Sean Simmons <ssimmons@progress.com>
This is an incorrect path and that is being fixed in this PR.
Solves the incorrect path to the file location.

fixing the path here

---

cspell.json
docs/dev/how_to/debugging_effortless.md

Added a document for debugging effortless.

hab debugging doc

---

cspell.json
omnibus/package-scripts/angrychef/preinst
omnibus/package-scripts/chef/preinst

Script now updated to first attempt direct folder deletion. Fall back to existing move-delete strategy only if that doesn't work, likely due to EBUSY error on RHEL, as suggested by @jaymzh

Update pre-install cleanup

---

omnibus/Gemfile.lock

Updating Omnibus

---

docs/dev/how_to/releasing_chef_infra.md

Add more details about releasing chocolatey package
Correct name `nuspec` file name per the file here https://github.com/chef/chocolatey-packages/blob/main/chef/chef.nuspec

Add more details about releasing chocolatey package

---

.buildkite/hooks/pre-command

Sean simmons progress/bugfix/precommand

---

.buildkite/verify.pipeline.sh

fixing one small missed step

---

Gemfile.lock

Small PR to get a version bump so we can release a full, clean set of associated gems

minor gem update to get the version bumped

---

.expeditor/verify.pipeline.yml
kitchen-tests/Gemfile

Move berkshelf repo reference to chef/berkshelf and pick up explicit hash change to fix tests

Fix berkshelf on chef 17

---

Rakefile

Updating the Rakefile to move away from using the shell command

[Chef-17] 4 of X - Updating the Rakefile

---

.expeditor/scripts/bk_win_functional.ps1
.expeditor/verify.pipeline.yml
.rubocop.yml
chef-config/chef-config.gemspec
chef-utils/chef-utils.gemspec
chef.gemspec
knife/knife.gemspec

Chef-17 Ruby versions need to be updated to reflect dropping Ruby 2.6 support and being consistent about Ruby 2.7 & 3.0 support

[Chef-17] 1 of X - Updating Ruby versions

---

docs/dev/how_to/running_cookbook_as_hab+effortless_package.md

Add documentation for running a cookbook as hab+effortless package

---

omnibus_overrides.rb

Updating ncurses to get past testing errors

[chef-17] 8 of X - Updating ncurses

---

kitchen-tests/cookbooks/end_to_end/recipes/windows.rb

The test images have a version of git installed. It conflicts with the tested version in the end_to_end cookbook. We're forcefully removing any existing versions here so we don't have to update the test images.

[Chef-17] 6 of X - Updating Git version for end_to_end testing

---

.buildkite/build-test-omnibus.sh
.buildkite/hooks/pre-command
.expeditor/adhoc-canary.omnibus.yml
.expeditor/release.omnibus.yml
omnibus/Gemfile.lock

This is re-enabling AIX builder and testers as they have been re-configured for a tiny bit more hardware. 
Our AIX builders were running slow, as they are on slower hardware. We asked the admins of the hosts to add more CPU if we could, which led to the aix71 and aix72 boxes being rebuilt. We also enabled a higher timeout on the AIX machines as the tests still take just a bit over 1h50m to complete. 
Here is a screenshot of the tests passed:

Sean simmons progress/18.2 enable aix

---

Gemfile.lock
omnibus/Gemfile.lock

I am updating gem dependencies to codify using a specific Berkshelf branch among other updates here. I did a 
```
rake dependencies:update
```

[Chef-17] 10 of X - Updating gem dependencies

---

lib/chef/win32/version.rb

Version.rb had to be updated for Windows 11, this is a backport from chef-18

[chef-17] 16 of X - Updating Windows Version Strings

---

.github/workflows/kitchen.yml

Remove deprecated Debian 9

---

spec/unit/client_spec.rb

Tests for EOL verification were failing in the AdHoc pipeline. The cause was that the original test had a malformed date in it. That is corrected here.

[chef-17] 27 of X - Tweaking EOL Support

---

Gemfile.lock
chef-universal-mingw-ucrt.gemspec

Use an updated [chef-powershell-shim](https://github.com/chef/chef-powershell-shim/pull/196) to clean up memory initialization and boundary checking with `wcscpy_s` for the results coming back from chef-powershell C++ code

18.0.2 chef-powershell with wcscpy_s calls

---

lib/chef/mixin/properties.rb
lib/chef/resource.rb
spec/unit/resource_spec.rb

Backporting this PR https://github.com/chef/chef/pull/13014 to chef-17

Backporting a chef-18 fix for sensitive properties

---

Gemfile.lock
cspell.json
omnibus/Gemfile.lock
tasks/dependencies.rb

This is a backport of a fix that Neah put into Chef-16 to keep omnibus using Ruby 3.1 correctly [PR #13304 ](https://github.com/chef/chef/pull/13304)

Updating omnibus to use ucrt

---

.buildkite-platform.json

Update for chef-foundation version to pick openssl-1.0.2ze

---

Gemfile.lock
chef-universal-mingw-ucrt.gemspec

Bump chef-powershell to 18.1.0 to use "store callback" strategy
* CHEF-3601
* CHEF-2819

Bump chef-powershell to 18.1.0

---

.github/workflows/kitchen.yml

While sorting out Chef-17 builds a while ago it was necessary to fall back to using the 'stable' branch in testing as the current branch had nothing in it. Somehow this didn't get switched back. This PR updates that.

switching testing branches to current

---

.buildkite/build-test-omnibus.sh
.expeditor/adhoc-canary.omnibus.yml
.expeditor/release.omnibus.yml
omnibus/Gemfile
omnibus/Gemfile.lock

Add RockyLinux-8

---

.expeditor/update_version.sh

Backport from Chef-18. This updates how we manage version changes.

[backport] Updating the updater

---

.buildkite-platform.json

Pinned chef-foundation version - 1.0.2zf  CHEF-4567

---

lib/chef/mixin/homebrew_user.rb
lib/chef/resource/apt_repository.rb
lib/chef/resource/homebrew_package.rb

Clean up some UI text that ends up in docs.
https://github.com/chef/chef-web-docs/pull/4179
https://github.com/chef/chef/pull/13728
https://github.com/chef/chef/pull/13669

Correct some UI text

---

spec/unit/compliance/reporter/chef_server_automate_spec.rb

Updating test to be RFC2119 compliant

---

docs/dev/how_to/building_chef_client_and_related_gems.md

Update slack channel name for contact to #chef-infra-dev

---

CONTRIBUTING.md

Per conversations at Chef Conf '23, update the
gem udpate prootocols in our documentation.
Include instructions for individual gem updates and regular gem maintenance.
Update CONTRIBUTING.md to include protocol & instructions for individual gem updates. (Ensure that the `--conservative` flag is used)
Include the protocol for the chef maintainers to quarterly update the Gemfile.
N/A

Update gem update protocols

---

.github/workflows/kitchen-fips.yml

This changes adds Github actions workflow by running a windows box with FIPS enabled on it. Then running the omnibus package for Infra client on it.
Most of the times this is where Infra Client throws errors and since there hasn't been any automation testing around it, things used to go unnoticed until client is released and issues are reported by end users. This will give us some form of reliability.

[WIP][Chef-18] Github actions tests to test Infra Client with FIPS enabled on windows

---

lib/chef/provider/user.rb
spec/unit/provider/user/linux_spec.rb

The sensitive item property was not being honored during user creation. This is a backport from https://github.com/chef/chef/pull/13897

[Chef-17 Backport] Updating Sensitive Items

---

lib/chef/resource/apt_package.rb

Addressing https://github.com/chef/chef/pull/13873#discussion_r1338663868 in this PR. 
Corresponding docs side changes are here https://github.com/chef/chef-web-docs/pull/4156

Add documentation review changes to apt_package resource

---

.expeditor/config.yml
Gemfile.lock
cspell.json
omnibus/Gemfile.lock
omnibus/config/projects/chef.rb

Final updates needed to pull in changes to omnibus-software and the buildkite msi signing process.

Pulling in final changes to sign pacakges and move DLL's around

---

.expeditor/config.yml
.github/workflows/selfhosted-fips.yml

Adding FIPS self-hosted testing

Adding self-hosted fips testing support

---

lib/chef/resource/support/sudoer.erb

Fixes broken erb template
Fixes Case# 01234688 / CHEF-2186

Fix sudoer.erb

---

kitchen-tests/cookbooks/end_to_end/recipes/linux.rb

Extracting the OpenSUSE kitchen test that @hunter86bg added to [#14024] for individual traceability.

Fix OpenSUSE tests

---

.buildkite-platform.json
.buildkite/build-test-omnibus.sh
.expeditor/adhoc-canary.omnibus.yml
.expeditor/release.omnibus.yml
omnibus/Gemfile.lock
omnibus/config/projects/chef.rb

Bump omnibus dependencies to add Rocky Linux 9 support, which includes [CHEF-5815: Update signing of all msi packages with new cli tool - smctl omnibus#1128](https://github.com/chef/omnibus/pull/1128) and [Update metadata with rocky platform omnibus#1125](https://github.com/chef/omnibus/pull/1125)

Adding rockylinux-9

---

.buildkite/hooks/pre-command
.expeditor/scripts/omnibus_chef_build.sh
omnibus/Gemfile

rpm-sign is not enabled for RockyLinux pkgs.
gpg secret keys are missing.

Rocky Pkg - signing

---

.expeditor/verify.pipeline.yml

Remove downloading of the `vendor.tar.gz` vendor cache(s)
`https://core-buildkite-cache-chef-oss-prod.s3.us-west-2.amazonaws.com/chef-chef-chef-17-verify/chef-zero_gem_:ruby:_3.0/vendor.tar.gz` contains a broken tar file last uploaded September 26, 2023, 08:12:49 UTC
[Chef changes](https://github.com/chef/chef/compare/bc00cdc...895297a) and 
[Ohai changes](https://github.com/chef/ohai/compare/c756b22eeb0424956ba32d04016c886fe7902304...cdb81a32f8612a9200ae8e212576a90b2dc412d6) between the [last good](https://buildkite.com/chef-oss/chef-chef-chef-17-verify/builds/1430) and the [first broken](https://buildkite.com/chef-oss/chef-chef-chef-17-verify/builds/1487) verify build don't indicate any differences and I cannot locate a build that would have been responsible for uploading the 2023-09-26 …

Turn off vendor cache usage in verify.pipeline.yml

---

.buildkite/build-test-omnibus.sh

Add platform  sles-x86-64

---

lib/chef/resource/sudo.rb

Minor text fixes related to #14024

Minor text fixes for sudo resource

---

.github/workflows/selfhosted-fips.yml

The FIPS tester in Azure was accidentally deleted, updating the code to reflect it here.

Updating for a new fips tester

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/release.omnibus.yml

Rocky package signing is busted. We need to release chef-17 now so we're commenting out the artifacts for now.

Temporarily remove Rocky

---

Dangerfile

Looks like `github.pr_authr` should have been `github.pr_author`

Correct pr_authr

---

.github/workflows/labeler.yml

Pin labeler to v4, since v5 is making breaking changes.
Was getting a failure on GitHub Actions for labeler:
```
The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api
Error: Error: found unexpected type for label 'documentation' (should be array of config options)
Error: found unexpected type for label 'documentation' (should be array of config options)
```
https://github.com/actions/labeler/issues/710

Pin labeler version... actions/labeler v5 in beta

---

.expeditor/scripts/omnibus_chef_build.ps1

just cleaning up a write-output thats not needed.

removing write output here

---

.github/workflows/labeler.yml

Change the pinned labeler version from Main to v4.3.0

[chef-17] labeler update

---

.buildkite-platform.json
omnibus/Gemfile
omnibus/Gemfile.lock

Updating openssl to 1.0.2zi temporarily to get past CVE's until we can officially upgrade to Openssl 3.x

Jfm/chef18 openssl 1.0.2zi

---

.expeditor/announce-release.sh

Send users to `chef.io/downloads` instead of a direct download URL

Update DL link to be generic

---

.buildkite-platform.json

Update chef-foundation from [3.1.10 to 3.1.14](https://github.com/chef/chef-foundation/compare/3.1.10...3.1.14) to pick up OpenSSL changes and Rocky Linux arm builder availability.
Internal: CHEF-8585

3.1.14 chef-foundation bump for 1.0.2zi openssl

---

.buildkite-platform.json

Updating Chef-Foundation to ensure compliance

Updating to Chef-Foundation 3.1.15

---

CONTRIBUTING.md

Bumping the version in preparation for a release

Minor doc change to trigger a version update

---

Gemfile.lock

Per a borked omnibus update, I am updating PLIST to 3.7.1

Updating PLIST

---

Gemfile.lock

Updating net-ssh to version 7.2.1

[chef-17] Updating net-ssh

---

lib/chef/client.rb
spec/unit/client_spec.rb

Hardcoding EOL to November 2024

Updating chef-17 EOL to November 2024

---

.expeditor/config.yml

Signed-off-by: Prajakta Purohit <prajakta@chef.io>

Adding an adhoc build for the Chef-17 pipeline to be run every Sunday and Wednesday UTC

---

chef-config/lib/chef-config/config.rb

Clean up on aisle 3 - The configuration options below were slated to be removed by Chef-18. Now removing them.

Removing deprecated attributes

---

.buildkite/build-test-omnibus.sh
.buildkite/hooks/pre-command

merging fixes into dev branch.

Sean simmons progress/hotfix/testamazon2023

---

.buildkite-platform.json
.buildkite/build-test-omnibus.sh
.buildkite/hooks/pre-command
.expeditor/adhoc-canary.omnibus.yml
.expeditor/release.omnibus.yml
.expeditor/scripts/omnibus_chef_build.sh
omnibus/Gemfile.lock

This pr changes are for adding support for amazon 2023 for infra-client along with  it will enable rpm package signing and also support for arm architecture images

Chef 2041 infra client release amazon 2023/muthuja

---

.expeditor/config.yml

Remove nightly build schedule for chef-16 branch

Remove nightly build schedule for chef-16

---

lib/chef/resource/chef_client_config.rb
lib/chef/resource/support/client.erb

fix bug in client.rb when listed property is a bool and checks for .empty? generates undefined method error.
#14254 
- [ x All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

fix bug in chef_client_config resource template for client.rb

---

Gemfile
Gemfile.lock

Updating Rubocop, parser et al for a downstream update I need

Refactoring for Rubocop

---

Gemfile.lock
chef-universal-mingw32.gemspec

Unbounding Chef-PowerShell to get v18 and the associated updated gems

Chef-PowerShell to v18

---

chef-config/lib/chef-config/path_helper.rb
knife/lib/chef/knife/core/subcommand_loader.rb
knife/spec/unit/knife/core/hashed_command_loader_spec.rb
spec/functional/resource/remote_file_spec.rb
spec/unit/provider/package/windows_spec.rb

remove repetitive words

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/release.omnibus.yml

remove macos10.15 support

---

omnibus/Gemfile.lock

Pulling in the updated omnibus-software version that correctly patches resolv.rb

Updating omnibus-software

---

.buildkite/build-test-omnibus.sh

moving back to supported release version of the plugin

---

lib/chef/resource/execute.rb

[trivial] add missing markdown fence

---

docs/dev/policy/release_and_support_schedule.md
lib/chef/client.rb
spec/unit/client_spec.rb

Since there is no specific timeline for major version releases this code is irrelevant now.
#14365

Remove EOL Warning

---

chef-config/lib/chef-config/path_helper.rb

[PathHelper#join] Reduce allocations

---

Gemfile.lock
chef.gemspec

```txt
❯ bundle update --conservative vault
Resolving dependencies.......
Using rake 13.0.6
Using public_suffix 5.0.1
Using concurrent-ruby 1.2.2
Using aws-eventstream 1.2.0
Using rack 2.2.6.4
Using aws-partitions 1.739.0
Using webrick 1.8.1
Using diff-lcs 1.5.0
Using iniparse 1.5.0
Using faraday-net_http 3.0.2
Using ruby2_keywords 0.0.5
Using tty-color 0.6.0
Using strings-ansi 0.2.0
Using unicode-display_width 2.4.2
Using unicode_utils 1.4.0
Using tty-screen 0.8.1
Using wisper 2.0.1
Using debug_inspector 1.1.0
Using builder 3.2.4
Using parallel 1.22.1
Using …
```

conservative update of vault

---

lib/chef/resource/chef_gem.rb

Remove an extra asterisk from the chef_gem resource examples.
This asterisk shows up in the [examples for this resource](https://docs.chef.io/resources/chef_gem/#examples) and someone asked what it was relating to.

Remove extra asterisk

---

lib/chef/resource/chef_client_config.rb
lib/chef/resource/support/client.erb

Backporting this bug and related fix: https://github.com/chef/chef/pull/14255

backport fix for chef-client-config

---

lib/chef/cookbook/chefignore.rb

Reduces unnecessary object allocation on each non-space string in a Chefignore file

[Chefignore#parse_ignore_file] Use strip! on lines

---

.buildkite-platform.json

Updating Chef-Foundation to pull in updates from Omnibus-Software that fix this issue: [Ruby Patches](https://github.com/chef/omnibus-software/pull/1914) : WIndows throwing encoding (utf-8) errors when retrieving data from the registry.

Updating Chef Foundation

---

lib/chef/provider/package/dnf/python_helper.rb

Found while troubleshooting, for https://github.com/chef/chef/blob/main/lib/chef/provider/package/dnf/dnf_helper.py

[trivial] fix typo dnf-helper.py -> dnf_helper.py

---

.expeditor/adhoc-canary.omnibus.yml

Updating build targets

---

docs/dev/how_to/bumping_the_major_version.md

updating steps

---

Gemfile.lock
chef.gemspec
knife/knife.gemspec

`bundle install` was conducted for a manual version bump of `ohai`

Update Ohai to 19

---

Gemfile
Gemfile.lock

Rdoc, as installed by the base Ruby in v3.0.3 has a CVE in it. For more details, see this bug: https://chefio.atlassian.net/browse/CHEF-13657. Also, [here](https://www.ruby-lang.org/en/news/2024/03/21/rce-rdoc-cve-2024-27281/)

[Chef-17] Updating RDOC to get past a CVE

---

lib/chef/provider/package/chocolatey.rb
spec/functional/resource/chocolatey_package_spec.rb
spec/unit/provider/package/chocolatey_spec.rb

Backport https://github.com/chef/chef/pull/13935

[Chef-17][Backport #13935] Fix regression in calling `choco --version`

---

.github/workflows/kitchen.yml
kitchen-tests/kitchen.yml

Centos 7 and 8 are EOL. The repos built into them point to dead url's. Here we update them to usable spots so the tests will work

Updating kitchen.yml to update Centos

---

lib/chef/mixin/openssl_helper.rb

Backport of this [PR](https://github.com/chef/chef/pull/14553), Here I slightly tweaked it to ensure the older code path executed for those OS's that are still running Openssl 1.0.2zi

Backporting openssl update

---

.github/workflows/danger.yml
.github/workflows/func_spec.yml
.github/workflows/kitchen-fips.yml
.github/workflows/kitchen.yml
.github/workflows/labeler.yml
.github/workflows/lint.yml
.github/workflows/selfhosted-fips.yml
.github/workflows/sonarqube.yml
.github/workflows/unit_specs.yml
.gitignore
cspell.json
kitchen-tests/cookbooks/end_to_end/recipes/default.rb
kitchen-tests/cookbooks/end_to_end/recipes/freebsd.rb
kitchen-tests/cookbooks/end_to_end/recipes/macos.rb
kitchen-tests/kitchen.linux.ci.yml
lib/chef/mixin/openssl_helper.rb

fix pipeline tests
remove EOL centos-7
fix openssl helper public key immutable error
fix macos homebrew package install with new package, old one has issues bin linking
add freebsd vm tests and fix shell command issue

[backport chef-18] fix pipeline tests

---

omnibus_overrides.rb
spec/integration/client/open_ssl_spec.rb

AIX should build out ok with the later Openssl version

bumping aix to openssl 3.0.9

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/release.omnibus.yml

Removing support for EL6. That OS is EOL as of June

Updating the builders and testers to remove EL-6 support

---

.buildkite/build-test-omnibus.sh
.expeditor/scripts/omnibus_chef_build.ps1

Updating signing key thumbprint to correspond to the new signing certificate.

updated signing key thumbprint

---

Gemfile

Porting this fix back up to Chef-18
https://github.com/chef/chef/pull/14534

Conditional install of openssl via install_if

---

Gemfile

Porting this fix back up to main
https://github.com/chef/chef/pull/14534

Use install_if for openssl gem

---

docs/dev/how_to/community_pr_review_checklist.md

Removing and updating list

---

.bldr.toml
.buildkite/verify.pipeline.sh
.expeditor/habitat-test.pipeline.yml
lib/chef/provider/package/habitat.rb
lib/chef/resource/habitat_install.rb

Removing support for the Kernel 2

removing kernel 2 support

---

Gemfile
Gemfile.lock
chef-bin/Gemfile
chef-config/Gemfile
chef-utils/Gemfile
kitchen-tests/Gemfile
knife/Gemfile

Updating to get past this [CVE](https://nvd.nist.gov/vuln/detail/CVE-2020-8130)

CVE update

---

Gemfile
Gemfile.lock
chef-bin/Gemfile
chef-config/Gemfile
chef-utils/Gemfile
kitchen-tests/Gemfile
knife/Gemfile

Updating to get past this [CVE](https://nvd.nist.gov/vuln/detail/CVE-2020-8130)

Updating rake to overcome a CVE

---

lib/chef/shell.rb

Make `chef-shell` available only as licensed feature
Make sure if the user has a valid license and entitlement to run `chef-shell`

CHEF-15487 enable licensing checks for `chef-shell`

---

docs/dev/how_to/adding_documentation_to_infra_resources.md

This change is only to test out whether expeditor bumps versions on merge

---

cspell.json
lib/chef/resource/homebrew_tap.rb

Obvious fix
Picked from #13703

Add example to homebrew_tap resource.

---

Gemfile.lock

Bump ohai to 19.0.3

---

.expeditor/config.yml

had some internal discussions and we are still going to be publishing these rubygems to rubygems.org

re-enabling

---

.expeditor/scripts/verify-plan.ps1

Set channel for habitat plan script in verify pipeline to LTS-2024 for windows platforms

---

Gemfile
Gemfile.lock

Revert "Updating Ohai"

---

.buildkite/build-test-omnibus.sh
.expeditor/adhoc-canary.omnibus.yml
.expeditor/config.yml
.expeditor/release.omnibus.yml

Removing Macos support while we get the builds sorted out.

Temporarily removing MacOS

---

habitat/plan.ps1

The build error specifics are in the comments below
also wanted to add debugging messages as we have many levels of where this build is happening, for example this the plan.ps1 file runs inside a docker container, which is why the errors were orginally not presented to the console build output
we should also figure out how to add docker logs to the build output
We had an error that was being masked in a docker container, that couldn't get around this:
```--- Creating archive at C:\hab\cache\src\chef-infra-client-19.0.34.zip... in plan.ps1
fatal: detected dubious ownership in repository at 'C:/src'
'C:/src' is owned by:
(inconvertible) (S-1-5-21-2976033035-1159192925-1851228977-1014)
but the current user is:
User Manager/ContainerAdministrator (S-1-5-93-2-1)
To add an exception for this …
```

This is addressing a build error on habitat

---

omnibus/Gemfile.lock

Bump train-core to 3.12.7 in omnibus

---

omnibus/config/projects/chef.rb

This is a backport of https://github.com/chef/chef/pull/14672. The regex is updated to match a few variants of the chef-log.dll path.

[backport] Updating the regex glob

---

.expeditor/adhoc-canary.omnibus.yml

Temporarily removing Windows from the adhoc pipeline

Temporarily removing windows from AdHoc

---

docs/dev/how_to/bumping_the_major_version.md

Document updating GitHub Actions workflows for new release/stable branches

Added docs for GHA workflows for new release branches

---

.expeditor/hab-export-pipeline.yml

Here is the completed pipeline for the s3 upload process that will allow us to do a RC1 release for the exported tarball of the chef-infra-client hab package. 
the pipeline installs chef-infra-client
we will hab export tar to the filesystem
we then upload the binary to: buildkite-artifacts for further use, then we also upload it to unstable-habitat-tarball
We export from the stable bldr channel channel, and from the chef origin if that needs to change we can.

Sean simmons progress/chef 16390 hab export upload s3

---

.expeditor/hab-export-pipeline.yml

Updating to the unstable channel to target RC1.

Sean simmons progress/chef 16390 hab export upload s3 channel

---

omnibus/package-scripts/chef/preinst

[Chef-18] Set default mask to allow infra client to run uninterrupted on hardened systems

---

kitchen-tests/cookbooks/end_to_end/recipes/macos.rb

Replace do-not-disturb with an actively maintained cask

---

lib/chef/provider/package/rubygems.rb

Backport gem package fix to chef-18

---

.expeditor/adhoc-canary.omnibus.yml

Updating to add Windows builders back

---

.buildkite-platform.json

- openssl.so fix for Windows
- Ruby 3.1.6
- perl and curl fixes

Bump .buildkite-platform.json for 3.2.12 chef-foundation

---

.github/workflows/kitchen.yml
kitchen-tests/cookbooks/end_to_end/recipes/default.rb
kitchen-tests/cookbooks/end_to_end/recipes/freebsd.rb
kitchen-tests/kitchen.linux.ci.yml
kitchen-tests/kitchen.yml

Revert "[CHEF-18] Remove Freebsd testing"

---

Gemfile.lock

The bump pulls in fixes for Target mode.
```
`bundle update cheffish --conservative`
Resolving dependencies.............
Using aws-partitions 1.1001.0
Using minitest 5.25.1
Using logger 1.5.3
Using tty-screen 0.8.2
Using uri 0.13.1
Using tty-color 0.6.0
Using diff-lcs 1.5.1
Using tty-cursor 0.7.1
Using rainbow 3.1.1
Using uuidtools …
```

Bump cheffish to 17.1.8

---

.github/workflows/func_spec.yml
.github/workflows/unit_specs.yml

Backport the bundle update removal on GA unit spec

---

.github/workflows/func_spec.yml

Update macos GA func_spec to use 13, 14, 15 and latest

---

.github/workflows/kitchen.yml

remove eol'd platforms from testing

---

.github/workflows/kitchen.yml
kitchen-tests/kitchen.dokken.yml
kitchen-tests/kitchen.exec.macos.yml

* add symlink for  /bin/install on debian-11 and leap
---------

try symlink for install (#14799)

---

cspell.json
lib/chef/dsl/reader_helpers.rb
lib/chef/provider/package/yum_tm.rb
lib/chef/resource/yum_package.rb
lib/chef/scan_access_control.rb
lib/chef/target_io/train/dir.rb

Solves the base issues in Target Mode related to yum package handling and extends supported resources

Fixes for yum packages and various other failing resources

---

.expeditor/scripts/build-infra-deb.sh

Issue : [CHEF-17360](https://progresssoftware.atlassian.net/browse/CHEF-17360) [CHEF-18112](https://progresssoftware.atlassian.net/browse/CHEF-18112)
[CHEF-17360]: https://progresssoftware.atlassian.net/browse/CHEF-17360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHEF-18112]: https://progresssoftware.atlassian.net/browse/CHEF-18112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added deb installer for chef infra-client

---

.expeditor/scripts/build-infra-rpm.sh
.expeditor/scripts/chef-infra-client.spec

Prepare the Habitat-based Chef Infra Client by leveraging the chef-migrate and Chef Client Habitat tar files.
This PR includes the script and the spec file necessary to prepare the Habitat-based Chef Infra Client. The script can be executed by running the following command:
```bash
.expeditor/scripts/build-infra-rpm.sh
```
The script requires two tarballs as input:
- Migration Tool Tarball: Contains the migration tools.
- Chef Infra Client Tarball: Exported using the hab pkg export tar command.
The two necessary input files need to be set through environment variables:
```bash
export CHEF_INFRA_MIGRATE_TAR=/path/to/migration-tools_Linux_x86_64.tar.gz
export CHEF_INFRA_HAB_TAR=/path/to/chef-chef-infra-client-19.0.54-20241121145703.tar.gz
``` …

Prepare hab based chef-infra-client rpm

---

.buildkite/build-test-omnibus.sh
.expeditor/scripts/bk_container_prep.sh
.expeditor/scripts/omnibus_chef_build.ps1
.expeditor/scripts/omnibus_chef_build.sh
.expeditor/scripts/prep_and_run_tests.ps1
.expeditor/scripts/prep_and_run_tests.sh

Revert "Removing Chef-Foundation from the builds"

---

knife/lib/chef/knife/bootstrap.rb

In https://github.com/chef/chef/pull/14669, we have introduced a warning message when the user runs the knife bootstrap command with a valid license to introduce them to the licensing. This PR will update the warning message with more information.

Updated the license warning message

---

.buildkite-platform.json
.buildkite/hooks/pre-command
.buildkite/verify.pipeline.sh
.expeditor/scripts/bk_container_prep.sh

Removing chef-foundation from the build process.

Updating chef to remove foundation during builds

---

Gemfile.lock

Chef-16831 in Atlassian. This update overcomes CVE-2024-49761
```sh
> bundle update --conservative rexml
Fetching https://github.com/chef/ohai.git
Resolving dependencies..................................
Using ffi 1.16.3 (x64-mingw-ucrt)
Using wmi-lite 1.0.7
Using aws-partitions 1.981.0
Using rack 2.2.9
Using uuidtools 2.2.0 …
```

Updating rexml to get past a cve

---

lib/chef/cookbook/metadata.rb

More readable, and avoids creating an unnecessary Regexp object.

[Metadata#recipes_from_cookbook_version] Use end_with?

---

.expeditor/update_version.sh
docs/dev/how_to/releasing_chef_infra.md

This is housekeeping PR for knife.
https://github.com/chef/chef/pull/14820 needed some changes before merge which we are taking care of here.
1. Code cleanup to remove commented code block: We can always get back any code we need from commit history, no need to keep it there commented.
2. Documentation update: Since we have chef pinned at specific versions inside knife/Gemfile.lock, to make sure whenever a new version of Infra18 is released, that is also pulled in inside knife we have updated the doc to reflect the same

Housekeeping changes for Knife

---

.buildkite/verify.pipeline.sh

Linux 2 was temporarily disabled due to it being missing from the latest hab. That was resolved shortly after, but not before the build for the merge disabled it passed.

Re-add Linux 2 plan to verify pipeline

---

knife/Gemfile
knife/Gemfile.lock
knife/knife.gemspec

[knife] Migrate from Chefstyle to Cookstyle gem

---

lib/chef/cookbook/remote_file_vendor.rb

[Chef18][RemoteFileVendor#get_filename] Do O(1) search for filename

---

docs/dev/how_to/community_pr_review_checklist.md

These projects are tangential to the Chef Infra client, and we've historically reviewed them when time allows

Add other commonly-reviewed community PR projects

---

cspell.json
lib/chef/resource/apt_repository.rb
spec/unit/provider/apt_repository_spec.rb

Backport of #14131 Support Signed-By option for apt repository

---

.buildkite-platform.json

Picking the latest version of chef-foundation where we have deprecated mac 11 and updated 12 as builder pr for reference : https://github.com/chef/chef-foundation/pull/151

pick latest version of chef-foundation

---

.expeditor/publish-release-notes.sh

updating publish release notes to correct branch

---

chef-utils/README.md
chef-utils/lib/chef-utils/dsl/cloud.rb
chef-utils/spec/unit/dsl/cloud_spec.rb

OCI is a supported cloud since Ohai 18.0.27 (chef/ohai#1780)
Add `oci?` helper to DSL to simplify cloud-specific conditions.

Add oci? helper

---

.expeditor/config.yml

Moving the pipeline for pushing to artifactory into habitat build/test chain.

move gem pipeline to habitat chain

---

lib/chef/data_collector.rb
spec/unit/data_collector_spec.rb

backport 14953 for chef-18

---

lib/chef/monkey_patches/net-http.rb

Cleanup debug in net-http monkeypatch

---

lib/chef/resource_reporter.rb

This is porting #14961 patch to `main`

Forward port resource reporter truncation

---

.buildkite/build-test-omnibus.sh

Picking latest version of omnibus-buildkite-plugin https://github.com/chef/omnibus-buildkite-plugin/pull/167 where we have remote-host env assigned dynamically for mac arm64 platforms too and modifying the condition based on it

pick latest version of omnibus-buildkite-plugin

---

.github/workflows/func_spec.yml

Functional choco tests on windows GHA runner have started failing from last week
```
An error occurred while loading ./spec/functional/resource/chocolatey_package_spec.rb. - Did you mean?
rspec ./spec/functional/resource/apt_package_spec.rb
rspec ./spec/functional/resource/zypper_package_spec.rb
rspec ./spec/functional/resource/yum_package_spec.rb
Failure/Error: require "webmock/rspec"
LoadError:
127: The specified procedure could not be found.   - C:/hostedtoolcache/windows/Ruby/3.1.7/x64/lib/ruby/gems/3.1.0/gems/date-3.4.0/lib/date_core.so
No examples found.
Finished in 0.00004 seconds (files took 1.68 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```
Something seems changed on the GHA windows runner image which results in the missing `date_core.so` file …

Temporary bandaid to fix choco spec failures in GHA

---

.editorconfig
.gitignore
.vscode/extensions.json
.vscode/settings.json
cspell.json

Addes default editor config files for formatting files the same when using IDE's that support them. 
See https://EditorConfig.org

add editor config files

---

.expeditor/gem_push_artifactory.pipeline.yml
.expeditor/scripts/gem_push_artifactory.ps1
.expeditor/scripts/gem_push_artifactory.rb
habitat/plan.ps1

This PR adds a powershell script that basically follows the same process as its bash counterpart and reuses the `gem_push_artifactory.rb` to push the gems to the artifactory path.

configure pipeline to push windows gem

---

.buildkite-platform.json

This PR updates the chef foundation version to 3.2.23

[chef-18] update chef foundation to 3.2.23

---

kitchen-tests/cookbooks/end_to_end/recipes/_apt.rb
lib/chef/resource/apt_repository.rb
spec/unit/provider/apt_repository_spec.rb

...also rename `key_type` to `key_resource_type`
#15048

Fix dearmoring idempotency

---

chef-config/lib/chef-config/mixin/credentials.rb
chef-config/lib/chef-config/mixin/train_transport.rb
lib/chef/file_content_management/deploy/target_io.rb
lib/chef/provider/cron.rb
lib/chef/target_io.rb
lib/chef/target_io/support.rb
lib/chef/target_io/train/dir.rb
lib/chef/target_io/train/etc.rb
lib/chef/target_io/train/file.rb
lib/chef/target_io/train/fileutils.rb
lib/chef/target_io/train/http.rb
lib/chef/target_io/train/shadow.rb

Add staging area to allow sudo-based upload and download of privileged files; Code cleanups; Added CHEF_CREDENTIALS_FILE environment variable

Add sudo capabilities to Target Mode; Cleanups

---

lib/chef/chef_fs/file_system/repository/chef_repository_file_system_cookbook_entry.rb

Signed-off-by: David Crosby <dcrosby@fb.com>

[ChefRepositoryFileSystemCookbookEntry#children] Use in-place mutations

---

kitchen-tests/cookbooks/end_to_end/recipes/_habitat_win_package.rb
kitchen-tests/cookbooks/end_to_end/recipes/_habitat_win_service.rb

In debugging issues with the package https://github.com/chef/chef/pull/15099 added a fix that wasn't added to `main`. Applying here + the added stability fix for windows-2022

Apply new version and stability fix for hab package to main

---

docs/dev/how_to/community_pr_review_checklist.md

Add shields to the PR review page

---

.github/CODEOWNERS

Adding myself to codeowners for chef-17

---

knife/lib/chef/knife/bootstrap.rb
knife/spec/unit/knife/license_spec.rb

This branch has been tested with Ruby 3.1.7 and fixed the specs which are failing. Also checked for the CVEs using the bundle-audit, and no CVEs were found.

[CHEF-23856] knife 18 ruby upgrade and CVE fixes

---

.buildkite-platform.json
.expeditor/scripts/omnibus_chef_build.sh
.expeditor/update_version.sh
Gemfile
Gemfile.aix.lock
Rakefile
bundle-for-aix
chef.gemspec
omnibus/config/software/chef-local-source.rb
scripts/README.md
scripts/bundle-hook.rb
scripts/bundle-with-aix.sh
tasks/bundle.rb

+ nokogiri bump (via omnibus_overrides.rb in chef-foundation)
+ thor upper bound bump
Adding a script also to maintain a separate AIX `Gemfile.aix.lock` so that AIX can stay on Ruby 3.0 compatible gem versions.

Updated chef-foundation to 3.2.32 to pick up typeprof/rbs gem removal 

---

post-bundle-install.rb

Don't try to (re)install ruby-shadow on AIX even if it happens to be on the box in the first place.

---

.buildkite-platform.json
lib/chef/resource/archive_file.rb

Also fix the following warning from archive_file.rb:
```
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.8.8-universal-mingw-ucrt/lib/chef/resources.rb:24: warning: argument of top-level return is ignored
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.8.8-universal-mingw-ucrt/lib/chef/resources.rb:24: warning: argument of top-level return is ignored
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.8.8-universal-mingw-ucrt/lib/chef/resources.rb:24: warning: argument of top-level return is ignored
Chef Infra Client: 18.8.8
```
Confirmed that rbs is removed and that activesupport does not have the 7.0.x version.
```
Selecting previously unselected package chef.
(Reading database ... 4376 files and directories currently installed.)
Preparing to unpack …
```

Update .buildkite-platform for gem uninstall rbs -x, fix a warning message on resource

---

kitchen-tests/cookbooks/end_to_end/recipes/_homebrew_tap.rb

Add test for #14369

---

.github/copilot-instructions.md
.vscode/mcp.json

This change introduces the mcp server setup and an initial copilot instructions file in an effort to enable ai assisted development workflow.

set up ai assisted development workflow

---

knife/lib/chef/knife/bootstrap.rb
knife/lib/chef/knife/bootstrap/client_builder.rb
knife/lib/chef/knife/config_use.rb
knife/lib/chef/knife/configure_client.rb
knife/lib/chef/knife/core/bootstrap_context.rb
knife/lib/chef/knife/core/cookbook_scm_repo.rb
knife/lib/chef/knife/core/object_loader.rb
knife/lib/chef/knife/core/ui.rb
knife/lib/chef/knife/core/windows_bootstrap_context.rb
knife/lib/chef/knife/edit.rb
knife/lib/chef/knife/exec.rb
knife/lib/chef/knife/raw.rb
knife/lib/chef/knife/ssl_check.rb
knife/lib/chef/knife/user_edit.rb
knife/lib/chef/knife/xargs.rb
knife/lib/chef/knife/yaml_convert.rb
knife/spec/unit/knife/bootstrap_spec.rb

This is a PR to the main branch with the same fixes introduced on https://github.com/chef/chef/pull/15185.

[CHEF-23856] knife code scan fixes

---

.buildkite/hooks/pre-command
.buildkite/validate-adhoc.rb
.expeditor/scripts/chef_adhoc_build.sh
.expeditor/scripts/validate_adhoc_build.sh
spec/integration/client/open_ssl_spec.rb

correcting adhoc builders

---

.github/workflows/ci-main-pull-request-checks.yml
.github/workflows/ci-main-pull-request-stub.yml
kitchen-tests/kitchen.linux.ci.yml

Adding a new yaml file to get the SBOM outputting

Jfm/chef18 SBOM update
