.expeditor/release.omnibus.yml, chef-config/lib/chef-config/workstation_config_loader.rb, spec/integration/client/client_spec.rb
fixes #10616 
On Solaris, setting `Mixlib::ShellOut`'s `:cwd` does not update the `pwd` environment variable. Based on some follow up research I could not find evidence that the `pwd` environment variable is guaranteed to reflect the `pwd` command. It feels like there might be a cleaner approach here - like just using `Dir.pwd` across the board. I'd think that should work everywhere. However there may be a reason (and perhaps a good one, or not) why we prefer the environment variable.
=> Fix failing tests on Solaris / Enable Solaris builds again

lib/chef/resource/hostname.rb
Addresses this failure mode:
```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
execute[set HostName via scutil] (/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/resource/hostname.rb line 132) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/sbin/scutil --get HostName ----
STDOUT: 
STDERR: HostName: not set
---- End output of /usr/sbin/scutil --get HostName ----
Ran /usr/sbin/scutil --get HostName returned 1
lib/chef/resource/hostname.rb:134
not_if { shell_out!("/usr/sbin/scutil --get HostName").stdout.chomp == new_resource.hostname }
```
=> hostname: Avoid erroring out when hostname is not set on mac

omnibus_overrides.rb
use the latest library
https://fossies.org/diffs/libiconv/1.15_vs_1.16/ChangeLog-diff.html
=> Update libiconv to 1.16

lib/chef/knife/ssh.rb
Signed-off-by: Robert Vežnaver <rveznaver@users.noreply.github.com>
The `knife ssh` command will silently fail if it starts with `sudo` and will not prompt for a password. The proposed change shall error out of `open_session` on `sudo` complaining about not having a TTY and will retry the command with a PTY.
This fixes a regression introduced in #9482 by requesting a PTY only when `open_session` errors out. In addition, it also requires `tty-prompt` as once a PTY is allocated the prompt fails with #10705.
=> Raise error and retry with PTY on sudo password prompt

lib/chef/compliance/reporter/chef_server_automate.rb, lib/chef/compliance/runner.rb, spec/unit/compliance/runner_spec.rb
* Fixes #10729. Added code equivalent to what was missing and added some basic unit tests to make sure the code can execute.
* Refactored the reporter creation from the report sending to make the tests less mock-and-stub heavy.
* In the spirit of not failing silently with bad configuration, changed the behavior when an unrecognized reporter type is specified to raise an exception rather than just logging an error and continuing.
* Removed a check for an impossible case. There was code handling the case where `Chef::Config[:chef_server_url]` was nil, but that has a default value and has a guard against setting it to a non-URL value.
=> Fix broken code in compliance runner's send_report.

spec/unit/mixin/openssl_helper_spec.rb
The module this is testing does not have an `included` method, and it autoloads OpenSSL at the top of the file so this will always be defined by referencing it: https://github.com/chef/chef/blob/master/lib/chef/mixin/openssl_helper.rb#L17
=> Remove a useless test.

lib/chef/knife/core/windows_bootstrap_context.rb
Bootstrapping on Windows generates a weirdly slashed trusted_certs path resulting in the following error when trying to use `Chef::Config[:trusted_certs_dir]` in a resource:
```
directory("C:ef/trusted_certs") do
action [:create]
default_guard_interpreter :default
declared_type :directory
cookbook_name "Base"
recipe_name "certificates"
recursive true
owner nil
group nil
mode nil
path "C:\bef/trusted_certs"
end
```
the bootstrap sets the path too `echo.trusted_certs_dir "C:\chef/trusted_certs"`
compared to the other paths using the escape helper the difference is clear
```
echo.file_cache_path   "C:\\chef\\cache"
echo.file_backup_path  "C:\\chef\\backup"
echo.trusted_certs_dir "C:\chef/trusted_certs"
```
=> knife bootstrap: Windows Trusted cert path slashes fix

lib/chef/compliance/default_attributes.rb, lib/chef/compliance/runner.rb, spec/unit/compliance/runner_spec.rb
I removed this early on because it was complicating some things, but it's mentioned in the audit cookbook README that has turned into chef/chef-web-docs#2781, so it either needs to get added for backwards compatibility or deprecated and removed from the docs.
=> Add audit cookbook's chef_node_attribute_enabled to Compliance Phase.

.expeditor/verify.pipeline.yml
Windows can take a while to run now.
=> Extend the PR verification timeout to 45 minutes

spec/data/trusted_certs_empty/README.md, spec/unit/knife/bootstrap_spec.rb
In #10751, I initially tried adding a binary-encoded SSL cert to `spec/data/trusted_certs` and that caused failures in these tests. I was going to try adding a friendlier error message for that case but the changes got pretty invasive since the exception raised happened far away from where the certs are read. This cleanup of the tests seemed worth salvaging from the code that I otherwise threw away.
=> Cleanup bootstrap's trusted_certs_dir tests.

kitchen-tests/cookbooks/end_to_end/recipes/macos.rb
The macOS kitchen end-to-end tests are failing because of an apparent conflict in one of vim's dependencies. `nethack` has no dependencies, is unlikely to be pre-installed in a CI image, and is likely to be maintained for a long time.
Example failure:
https://dev.azure.com/chef-software/chef/_build/results?buildId=3497&view=logs&j=b911c377-bd81-5cf7-b87f-ce01442373ee&t=43d8696b-e497-570b-b2fc-abebc77456ed
=> Switch macOS kitchen test homebrew package.

lib/chef/provider/package/rubygems.rb, spec/unit/provider/package/rubygems_spec.rb
Rubygems 1.8 came out May 4, 2011 and we're still checking for rubygems older than that.
For the record the other checks for Rubygems 2.7 are Nov 2017+
=> Chef 17: Assume Rubygems 1.8 in the rubygems provider / specs

.expeditor/release.omnibus.yml
=> Remove EOL RHEL 6 32bit builds

lib/chef/resource/cron/cron_d.rb
Fixes `cron_d` resource not being aware of the `sensitive` property, potentially leaking sensitive data into Chef Client's stdout.
The `create_template` function of the `CronD` class ignored the `sensitive` property.
#10766
=> Fixed cron_d resource ignoring sensitive property in Chef 17

lib/chef/resource/cron/cron_d.rb
Fixes `cron_d` resource not being aware of the `sensitive` property, potentially leaking sensitive data into Chef Client's stdout.
The `create_template` function of the `CronD` class ignored the `sensitive` property.
#10766
=> Fixed cron_d resource ignoring sensitive property in Chef 16

lib/chef/resource/cron_d.rb
Fixes `cron_d` resource not being aware of the `sensitive` property, potentially leaking sensitive data into Chef Client's stdout.
The `create_template` function of the `CronD` class ignored the `sensitive` property.
#10766
=> Fixed cron_d resource ignoring sensitive property in Chef 15

.expeditor/release.omnibus.yml, .expeditor/verify.pipeline.yml, kitchen-tests/kitchen.yml, omnibus/kitchen.yml
By the time we ship Chef 17 Ubuntu 16.04 will be EOL.
=> Remove support for Ubuntu 16.04

tasks/spellcheck.rb
After cspell's recent update, it's default output got much more verbose because it prints the path of every file it is checking. This makes it hard to see what the errors are when you get a spellcheck violation.
The other task didn't work anymore and it was only useful to me when I was initially implementing the spellcheck task, so I removed it rather than trying to get it working again.
An example of the newer verbose output is here: https://buildkite.com/chef-oss/chef-chef-master-verify/builds/7390#fef4f0ea-c7ef-413b-a370-844c7dfd4693
=> Update spellcheck task for new version of cspell.

lib/chef/provider/package.rb, lib/chef/provider/package/dnf.rb, lib/chef/provider/package/dnf/dnf_helper.py, lib/chef/provider/package/dnf/python_helper.rb, spec/functional/resource/dnf_package_spec.rb
This does two things:
1.  Fixes the filtering by name, version + arch.  This introduces one incompatibility which is that putting the arch in the version property was supported at one point in time with a test that I committed which doesn't seem to be used anywhere.  But we also now should correctly support mixing and matching the name with versions and arches in them combined with a version property and/or arch property.  Which is a bit crazy but it supports doing `package "openssl.i686"` with a version property.  It should now behave the same using either the property or putting the version and arch into the name.
2.  It changes the meaning of the "current_version" in the superclass (or confusingly the "installed_version" in the subclass) so that if a version of the package is …
=> Fix dnf_package version and arch property support and idempotency

.expeditor/scripts/bk_container_prep.sh, .expeditor/scripts/bk_linux_exec.sh, .expeditor/scripts/bk_win_functional.ps1, .expeditor/scripts/bk_win_prep.ps1, .expeditor/verify.pipeline.yml, omnibus_overrides.rb
We don't update it in our builds anymore. We just use the version that's built into Ruby. This omnibus override was only used for CI and we had to match the versions, which was a real pain and pretty pointless.
=> Stop updating bundler in CI

omnibus_overrides.rb
We no longer update this and the only software def in omnibus-software that deps on it is bundler, which nothing else deps on at this point.
=> Removed unused rubygems from the omnibus overrides file

kitchen-tests/kitchen.yml
These are the terrible things you get to do to support an EOL platform.
=> Ensure we can still install RHEL 7 GCC on RHEL 6 in testing

.expeditor/verify.pipeline.yml, kitchen-tests/kitchen.yml
The version of ld on Amazon Linux 201x cannot handle the ffi gem so these tests are going to fail forever now. This is a RHEL 6 based distro that is EOL as of the end of 2020.
https://aws.amazon.com/blogs/aws/update-on-amazon-linux-ami-end-of-life/
=> Remove Test Kitchen tests for Amazon Linux 201X

.expeditor/verify.pipeline.yml, kitchen-tests/kitchen.yml
These containers are alpha/beta quality, but we should start testing on
this since it'll be out when Chef Infra 17 is released.
=> Replace Ubuntu 20.10 testing with 21.04

lib/chef/resource/windows_certificate.rb
This is not getting rendered correctly.
=> Fix escaping in doc string.

lib/chef/resource/windows_certificate.rb, spec/functional/resource/windows_certificate_spec.rb
Attempt to fix #10696.
These tests were identified as running slowly on CI. This PR takes their runtime from ~50s to ~18s in my local Windows 2019 VM.
=> Consolidate Windows cert tests to improve CI runtime

.expeditor/config.yml
This should reduce the number of hand created PRs to update the Gemfile.lock.
=> Add expeditor update subscriptions for all our gem deps

kitchen-tests/cookbooks/end_to_end/recipes/windows.rb, spec/unit/resource/user/windows_user_spec.rb
Fixes #10454. Followup to #10797.
I ended up including the `rescue` call because it made the error message much nicer.
without `rescue`:
```
TypeError:
can't convert Hash into Integer
```
with `rescue`:
```
Chef::Exceptions::ValidationFailed:
Property uid must be one of: String, Integer, NilClass!  You passed {:woot=>"i found it"}.
```
After this PR, the uid of the user doesn't actually change (probably related to #10657), but this fixes the crash.
=> Coerce uid to integer in Windows user resource.

Gemfile.lock, chef.gemspec, omnibus/Gemfile.lock
RC2 now includes support for Ruby 3
=> Update bcrypt_pbkdf to support Ruby 3

omnibus/Gemfile
We can let dependabot manage the bumps to this file if we remove these. It's worth having to hand edit the file with extra test gems. It's going to save a ton of time.
=> Remove the evals in the omnibus gemfile for Dependabot

CHANGELOG.md, chef.gemspec
This ensures we have all the links on Rubygems now
Backports https://github.com/chef/chef/pull/10809
=> Add gemspec metadata

Gemfile, Gemfile.lock
This ohai should fix build failures and we don't need to pull chefstyle from git anymore since we only want the latest coming in on chef/chef master.
=> Update Ohai to 16.8.2 and pin chefstyle

lib/chef/provider/yum_repository.rb, lib/chef/resource/yum_repository.rb
This lets you optionally add/remove repo configs from a non-standard dir.
Resolves https://github.com/chef/chef/issues/9618
=> Add a new `reposdir` property in the `yum_repository` resource

lib/chef/provider/service/systemd.rb, spec/unit/provider/service/systemd_service_spec.rb
Refactors how `load_current_resource` gathers state for systemd services by requesting all pieces of state in a single call and memoizing the results.
The only material change here is in how `masked-runtime` is handled; previously it was reported as 'masked', but I think that's incorrect.  Asserting whether a unit is masked should be against the persistent system state (not volatile).  The remaining service states are all the same.
Performance outcomes are demonstrated with a naive loop, against a system where no such services are running:
```
(1..100).each do |x|
service "josh#{x}" do
action [:stop, :disable]
end
end
```
Previously this takes ~15s; with this patch, ~6s.  This testing was done with an older version of chef which has fewer …
=> load_current_resource for systemd service more efficiently

Dockerfile
We need to still install on RHEL 6 so we get GLIBC 2.12 support
=> Make sure our containers work on RHEL 6

lib/chef/compliance/runner.rb, spec/unit/compliance/runner_spec.rb
The expanded_run_list doesn't capture any recipes which are not in the
run_list but are dynamically `include_recipe`'d.  This change uses the
recipes list, which by the end of the run should be complete and
accurate.
=> Compliance phase: change the audit cb checker to use the recipes list on the node.

lib/chef/compliance/runner.rb, spec/unit/compliance/runner_spec.rb
The expanded_run_list doesn't capture any recipes which are not in the
run_list but are dynamically include_recipe'd. This change uses the
recipes list, which by the end of the run should be complete and
accurate.
Backports https://github.com/chef/chef/pull/10864
=> Compliance phase: change the audit cb checker to use the recipes list on the node

lib/chef/provider/package/freebsd/pkgng.rb, spec/unit/provider/package/freebsd/pkgng_spec.rb
The exit code for pkgng changed with https://github.com/freebsd/pkg/commit/f446c790707993656934e0c378b64ae28cb96575 from `70` to `1` making the provider fail on any non-converged node because `pkg info <pkg>` raises an error now. E.g.
```
Error executing action `install` on resource 'freebsd_package[tmux]'
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0, 70], but received '1'
---- Begin output of ["pkg", "info", "tmux"] ----
STDOUT:
STDERR: pkg: No package(s) matching tmux
---- End output of ["pkg", "info", "tmux"] ----
Ran ["pkg", "info", "tmux"] returned 1
```
I'm a bit …
=> adapt to FreeBSD pkgng sysexit changes

spec/functional/resource/aixinit_service_spec.rb
Fix misspelling in `spec/functional/resource/aixinit_service_spec.rb`.
Obvious fix.
Changed `valide_symlinks` to `valid_symlinks` in `spec/functional/resource/aixinit_service_spec.rb`.
n/a, typo
- n/a, this is within a test, which furthermore is for AIX, a platform I do not have access to. However, it's a simple typo fix so it shouldn't break anything.
- NA, obvious fix
=> Fix misspelling in spec/functional/resource/aixinit_service_spec.rb.

lib/chef/resource/alternatives.rb, lib/chef/resource/chef_client_launchd.rb
Match our current format and make it more clear that launchd == macos
=> Update the alternatives and chef_client_launchd descriptions

spec/functional/resource/ohai_spec.rb, spec/spec_helper.rb
1. this speeds it up by avoiding the sleep and the old ohai data
2. this fixes it because it was totally broken and the old uptime value was nil anyway
=> Fix ohai resource spec

lib/chef/compliance/runner.rb, spec/unit/compliance/runner_spec.rb
This detects if the audit cookbook's library files have been parsed,
which is mildly brittle but this constant has been stable back to 2017.
This catches the case where a site:
1. Has the audit cookbook as a cookbook dependency so it is in the run_list.
2. The wrapper cookbook is loading the attributes.
3. But the audit cookbook is not run every time and is controlled by
"include_recipe" with a conditional wrapper.
It may also catch cases where the site uses a named_run_list in a
PolicyFile since the cookbook set is the same no matter what named_run_list
you are running (pretty sure that's a feature of how PolicyFiles work).
What it can't do is catch old-style override run_lists with the audit
cookbook normally not in the cookbook set at all.  That is quite
literally impossible to detect.
=> Compliance Phase: even better audit cookbook detection

lib/chef/shell.rb
This brings chef-shell a bit closer to behaving properly. This code is
tons of copy-pasta and needs some love. Because it's not using *any* of
`Chef::Application` (not `Application` or `Application::Base` or even
it's own fork of `Application` like half the other stuff in the repo),
it doesn't have access to _any_ of the many versions of
`load_config_file` (note to self: collapse those into one).
Pulling in Application will be a significant chunk of work, so in the
mean time I did the minimal amount of work to make the `parse_opts` in
shell.rb create the right bits so that Chef::Config and Mixin::DotD can
work... so while this doesn't fix the problem that we're invoking our
own config parsing, it at least uses as much of the common code as I can
without reworking the entirety of …
=> Add support for client.d files in chef-shell

.expeditor/scripts/bk_linux_exec.sh, .expeditor/verify.pipeline.yml
This PR replaces the use of Ruby from `omnibus-toolchain` in the verify pipeline's kitchen tests with a version of Ruby defined in `omnibus_overrides.rb`.
=> Manually install necessary Ruby for verify pipeline

.expeditor/verify.pipeline.yml
=> Remove Ruby 2.6 tests

chef-utils/lib/chef-utils/mash.rb, lib/chef/delayed_evaluator.rb, lib/chef/node/attribute.rb, lib/chef/node/immutable_collections.rb, lib/chef/node/mixin/deep_merge_cache.rb, spec/unit/node_spec.rb
Implements #10345
This is very much not the poise-derived solution.
This allows the user to store procs/lazy-evaluators into the attribute tree.  Those are saved into the merged view of the node object.  On access, the proc is evaluated before the value is given back to the user.
This allows the user to lazy derived attributes:
```ruby
default['user'] = "Avasarala"
default['homedir'] = lazy { "/home/#{node['user']}" }
```
Since the proc is saved in the deep merge cache rather than the evaluated value, the result is truly lazy:
```ruby
default['user'] = "Avasarala"
default['homedir'] = lazy { "/home/#{node['user']}" }
puts node['homedir']
override['user'] = "Amos"
puts node['homedir']
```
The user can arbitrarily mess with the dependent variable in recipe code and the lazied attribute …
=> Add support for lazy attributes

lib/chef/resource/windows_task.rb, lib/chef/util/backup.rb
Adds backup property to windows_task, allowing the XML of the task to be saved for rollback purposes.
Allows rollbacks and history for windows tasks modified or deleted by chef
https://github.com/chef/chef/issues/10883
=> Add backup functionality to windows_task

spec/unit/provider_spec.rb
The original intent was to remove the use_inline_resources method from
the codebase. We have a Cookstyle rule cleaning that up, but there's
really no value to customers in removing the empty method. It doesn't
bloat the app or cause us any additional maint effort. We can just
remove them via cookstyle as we find them and carry on with our life
within chef-client. Removing the method just makes upgrades harder for
customers.
=> Remove pending test for use_inline_resources

omnibus_overrides.rb
The omnibus-software defn no longer exists.
=> Remove ohai from omnibus_overrides

lib/chef/provider/systemd_unit.rb, spec/unit/provider/systemd_unit_spec.rb
Refactors how load_current_resource gathers state for systemd_unit resources by requesting all pieces of state in a single call and memoizing the results.
The only material change here is in how masked-runtime is handled; previously it was reported as 'masked', but I think that's incorrect. Asserting whether a unit is masked should be against the persistent system state (not volatile). The remaining systemd_unit resource states are all the same.
Performance outcomes are demonstrated with a naive loop, against a system where no such services are running:
```
(1..100).each do |x|
systemd_unit "josh#{x}.service" do
action [:stop, :disable]
end
end
```
Previously this takes ~26s; with this patch, ~6s.  More actions (like :delete) compound this …
=> load_current_resource for systemd_unit more efficiently

Gemfile.lock
This resolves metadata failures on OpenStack
=> Update Ohai to 17.0.10

lib/chef/resource/systemd_unit.rb
Fixes `Style/BracesAroundHashParameters: Redundant curly braces around a hash parameter.` as recent versions of Cookstyle now complain about this code example.
No related issue
=> Update systemd_unit.rb to make Cookstyle compliant

lib/chef/provider/package.rb, lib/chef/provider/package/dnf/dnf_helper.py, spec/unit/provider/package/dnf/python_helper_spec.rb
Also suppresses a version comparison that normally fails when it is
called on the dnf provider which was ignorable.
=> Fix DNF version comparison bug

Gemfile.lock
This maps almalinux into the rhel platform_family
=> Bump Ohai to 17.0.12 for Alma Linux support

lib/chef/provider/service/systemd.rb, spec/unit/provider/service/systemd_service_spec.rb
When deciding on enabled status of a systemd service, if the version of systemd is sufficiently old, and the service is not a native systemd service but instead relies on the systemd-sysv-generator, shellout to `is-enabled` to determine whether the service is enabled.  
Idempotency for action :enable on systemd service was broken (due to https://github.com/chef/chef/pull/10776), such that every chef run triggered enablement despite the service already being enabled.
NA
=> Handle sysv compat mode when checking enabled status for systemd service

lib/chef/resource.rb, lib/chef/resource_inspector.rb, spec/integration/recipes/resource_action_spec.rb, spec/unit/resource_inspector_spec.rb, spec/unit/resource_spec.rb, tasks/docs.rb
This will allow us to generate better documentation by including
action descriptions in the resource help, and includes updates to the
resource inspector and doc generation task to include action descriptions
in resource action data.
This change permits actions to be defined with the optional new
'description' parameter as follows:
```
action :my_action, description: "my_action changes the state of this world"
...
end
```
Action description can be looked up using the
`.action_description(action)` method of the resource class.  Action
descriptions are inheritable and overridable.
---
Replaces #10930 
Implements #10660
=> Add support for resource action descriptions

lib/chef/resource.rb, lib/chef/resource_inspector.rb, spec/integration/recipes/resource_action_spec.rb, spec/unit/resource_inspector_spec.rb, spec/unit/resource_spec.rb, tasks/docs.rb
This backports #10952 into Chef Infra Client 16. 
This will allow us to generate better documentation by including
action descriptions in the resource help, and includes updates to the
resource inspector and doc generation task to include action descriptions
in resource action data.
This change permits actions to be defined with the optional new
'description' parameter as follows:
```
action :my_action, description: "my_action changes the state of this world"
...
end
Action description can be looked up using the
`.action_description(action)` method of the resource class.  Action
descriptions are inheritable and overridable.
=> Add support for resource action descriptions (Backport 10952)

lib/chef/provider/package/dnf/dnf_helper.py, lib/chef/provider/package/yum/yum_helper.py
For people with ABRT logging every exit of chef-client would have ABRT
errors due to readline returning '' for EOF and then the JSON parsing
throwing.
This causes it to exit gracefully.
AFAIK there was actually no impact to this bug and chef was behaving
entirely correctly in terms of doing its job, but the python helper was
shutting down uncleanly.
closes #10108
=> DNF/YUM package: fix abrt errors

lib/chef/provider/package/apt.rb, spec/functional/resource/apt_package_spec.rb, spec/unit/provider/package/apt_spec.rb
`apt_package` never even looks at `new_resource.version` when deciding
what version to install. That's silly.
This fixes that. It requires the version be exact (as the `yum_package`
did for most of Chef's history), and if you specify a non-existent
version, it'll raise an exception.
The unit tests for this provider are a bit of a mess, so I kinda stuck
in the tests where I could.
```
[2021-02-07T15:59:35-08:00] TRACE: apt_package[hub] installed version for hub is 2.14.2-1vcrs.1
[2021-02-07T15:59:35-08:00] TRACE: apt_package[hub] candidate version for hub is 2.14.2-1vcrs.1
[2021-02-07T15:59:35-08:00] TRACE: apt_package[hub] hub 2.14.2-1vcrs.1 needs updating to 2.7.0~ds1-1vcrs.1
[2021-02-07T15:59:38-08:00] INFO: apt_package[hub] installed hub at 2.7.0~ds1-1vcrs.1
```
=> Fix downgrades in apt_package

RELEASE_NOTES.md, lib/chef/dsl/reboot_pending.rb, lib/chef/resource/user_ulimit.rb, spec/unit/dsl/reboot_pending_spec.rb
This works on Debian as well and we want to check it on all
Ubuntu-derivatives.
=> Extend the reboot_pending? helper to all debian-ish platforms

Gemfile.lock, RELEASE_NOTES.md, chef-utils/README.md, chef-utils/lib/chef-utils/dsl/cloud.rb, chef-utils/spec/unit/dsl/cloud_spec.rb, omnibus/Gemfile.lock
This is a fully supported cloud now
```
[root@1234 mixin]# ohai alibaba
{
"meta_data": {
"dns_conf_": "nameservers",
"eipv4": "47.89.242.123",
"hibernation_": "configured",
"hostname": "1234",
"image_id": "aliyun_2_1903_x64_20G_alibase_20210120.vhd",
"instance_id": "i-rj996x25ht5omuhhzod7",
"instance_": {
"instance_type": "ecs.t6-c2m1.large",
"last_host_landing_time": "2021-02-07 19:10:04",
"max_netbw_egress": 81920,
"max_netbw_ingress": 81920,
"virtualization_solution": "ECS Virt",
"virtualization_solution_version": 2.0
},
"mac": "00:16:3e:00:d9:01",
"network_type": "vpc",
"network_": "interfaces/",
"ntp_conf_": "ntp-servers",
"owner_account_id": 1234,
"private_ipv4": "172.25.58.242",
"region_id": "us-west-1",
"serial_number": "ac344378-4d5d-4b9e-851b-1234",
"source_address": …
```
=> Add alibaba? helper and pull in Ohai with alibaba support

lib/chef/compliance/fetcher/automate.rb, spec/unit/compliance/fetcher/automate_spec.rb
This is largely copypasta directly out of the audit cookbook.
I've preserved the original backcompat in the cookbook because
it seems more important for this code to be correct than to try
to mess around deprecating code that isn't hurting anything.
closes #10862
=> Fix automate compliance fetcher for profiles with at signs

lib/chef/provider/mount/mount.rb, spec/unit/provider/mount/mount_spec.rb
PR #10614 introduce a bug which can impact network mounts which try to mount from the root level (i.e. server:/). Specifically, we run into this on cephfs where this is pretty common. This adds some logic to detect if this is a network mount at the root level and doesn't strip the '/'.
This resolves #10764.
=> mount: Fix for network mounts which use the root level as the device

.bldr.toml, .expeditor/habitat-test.pipeline.yml, .expeditor/verify.pipeline.yml
RHEL 6 is EOL. Stop shipping these packages
=> Stop producing Habitat kernel2 packages

lib/chef/provider/service/upstart.rb
None of these include upstart at this point
=> Don't make upstart service to service on any debian platform families

lib/chef/provider/service/upstart.rb, spec/unit/provider/service/upstart_service_spec.rb
=> Remove an Upstart check for Ubuntu 8.04-9.04

.expeditor/release.omnibus.yml
We support N-2 macOS releases so 10.13 can be dropped now that Big Sur
is out.
=> Remove macOS 10.13 from the build matrix

.expeditor/release.omnibus.yml
This reverts commit dbd0234e87c7e324f8349f6ed3a04187e681bcf3.
There is some errors with upstream logic that prevent us from doing this right now.
=> Revert "Update name of macos builder in Buildkite"

.expeditor/release.omnibus.yml
=> Rename macOS target from 11 to 11.0 to avoid logic issue in Omnitruck

kitchen-tests/cookbooks/end_to_end/attributes/default.rb, kitchen-tests/cookbooks/end_to_end/recipes/linux.rb, kitchen-tests/cookbooks/end_to_end/recipes/macos.rb
Recently, the Sous Chefs released a new resource driven resolver cookbook and removed the default recipe, thus breaking tests. This should fix the tests related to this.
=> Update resolver cookbook usage in test-kitchen tests

.expeditor/config.yml
Avoid the need to manually create PRs when a PR is merged to Ohai
=> Create a PR any time Ohai is bumped

lib/chef/compliance/default_attributes.rb, lib/chef/compliance/runner.rb, spec/unit/compliance/runner_spec.rb
Setting node["audit"]["compliance_mode"] to be false should force the
compliance mode to not run.
This is for sites which run override run lists which have the audit
cookbook in them, but the rest of their cookbooks define profiles so
that in normal running they still have those profiles defined but
they're manually running the cookbook.
That is likely a pretty bad pattern since the cookbook_synchronizer will
be thrashing on at least the audit cookbook being downloaded and then
removed, but it seems people have settled on this as their solution
which breaks the assumptions we had for the compliance_mode.
To sort this out those sites should set node["audit"]["compliance_mode"]
to be false on their runs which aren't supposed to run audits.  Instead
of an override run list with the audit …
=> Add a compliance_mode node attribute

RELEASE_NOTES.md, lib/chef/property.rb, lib/chef/resource/template.rb, spec/unit/mixin/params_validate_spec.rb, spec/unit/property_spec.rb, spec/unit/provider/group_spec.rb
This largely makes frozen default value errors go away.  Each
copy of a resource will get a dup of the default.  Defaults are
still frozen so we have defense-in-depth against them being
mutated.  This eliminates the need to `default: lazy{ {} }`
things like Hashes or Arrays.
=> Dup default property values

lib/chef/resource/windows_security_policy.rb
This is faster if we're not using a regex in the replacement
=> Use .tr instead of .gsub where we can

lib/chef/resource/chef_client_cron.rb, spec/unit/resource/chef_client_cron_spec.rb
Backport of #11124
This changes from using the cli `-L` option for writing the log file to using shell redirection when `append_log_file` is set to true. Currently, if ruby encounters any deprecation warnings, it will still be sent to stderr which can fill up cron email unexpectedly.
This mimics how this already works if `append_log_file` is false.
=> Use shell redirection in chef_client_cron when append_log_file is true

Gemfile.lock, chef.gemspec, omnibus/Gemfile.lock
This should be the same thing except they did a non-RC release.
=> Update our bcrypt_pbkdf dep to allow the final 1.1.0 release

lib/chef/provider/package/dnf/dnf_helper.py, lib/chef/provider/package/yum/yum_helper.py
For people with ABRT logging every exit of chef-client would have ABRT
errors due to readline returning '' for EOF and then the JSON parsing
throwing.
This causes it to exit gracefully.
AFAIK there was actually no impact to this bug and chef was behaving
entirely correctly in terms of doing its job, but the python helper was
shutting down uncleanly.
Fixes: https://github.com/chef/customer-bugs/issues/322
=> [Backport to chef-16] DNF package: fix abrt errors

docs/dev/devtools/README.md, docs/dev/devtools/chef-apply.md
After discussion in last week's Chef Triage meeting, there are tools
which are unsupported, confusing to new users, and shouldn't be confused
with the "right" ways to use Chef products. However, those tools are
often useful to developers or sufficiently advanced users and should be
documented somewhere else where it's clear you're off the beaten path.
We decided this is the correct place, so I'm taking the recently removed
chef-apply docs
(https://github.com/chef/chef-workstation/blob/5af407dc6bd1432994cd89cc56ae00cf95cbb37f/docs-chef-io/content/workstation/ctl_chef_apply.md) and putting them here
=> Build place for documenting internal/dev/unsupported commands

Gemfile.lock, chef-universal-mingw32.gemspec, omnibus/Gemfile.lock
0.6.0 is causing build failures
=> Pin win32-certstore to 0.5.x until we resolve failures

omnibus/package-scripts/chef/postinst
You shouldn't need to create this by hand post install. Chef should be
as ready to go as we can possibly get it.
=> Make the /etc/chef directory as part of the install

lib/chef/provider/file.rb, spec/support/shared/unit/provider/file.rb
Only run file verifiers when the file contents have actually changed
Only run file verifiers when the file contents have actually changed.  This prevents unnecessary verifier overhead, as well as verifier failures unrelated to chef changes.
#11170
=> only run file verifiers when the contents changed

omnibus/package-scripts/chef/postinst
This matches the permissions we give this file in the chef_client_config resource and in the chef-client cookbook
=> Create client.rb in postinst with 640 perms not 644

.expeditor/release.omnibus.yml
Enables M1 mac builds.
Clearly most of the work not done here.
=> M1 Mac arm builds

lib/chef/provider/package/dnf/dnf_helper.py, lib/chef/provider/package/yum/yum_helper.py
For people with ABRT logging every exit of chef-client would have ABRT
errors due to readline returning '' for EOF and then the JSON parsing
throwing.
This causes it to exit gracefully.
AFAIK there was actually no impact to this bug and chef was behaving
entirely correctly in terms of doing its job, but the python helper was
shutting down uncleanly.
PR merged on master : https://github.com/chef/chef/pull/10991
Fixes : https://github.com/chef/chef/issues/10108
NOTE : Originated in chef-15 per https://github.com/chef/chef/issues/10108
=> [Backport to chef-15] DNF package: fix abrt errors

.expeditor/config.yml, .expeditor/update_bundler_dep.sh
The more I hacked on the previous script the more I realized they're not
doing the same thing. This script is not concerned with things that
happened via rubygems promotes. It's just running bundle update when a
new commit is available in the repo.
=> Add an expeditor script specific to bundler updated gems

kitchen-tests/cookbooks/end_to_end/recipes/linux.rb, kitchen-tests/cookbooks/end_to_end/recipes/macos.rb, kitchen-tests/cookbooks/end_to_end/recipes/windows.rb, kitchen-tests/data_bags/users/adam.json
The use of data bags in the users cookbook was removed in 6.0.0 [1]. This applies the recommended workaround and allow the integration tests to pass.
[1] https://github.com/sous-chefs/users/blob/master/CHANGELOG.md#600---2021-03-12
=> Fix users_manage usage in kitchen-tests

kitchen-tests/kitchen.yml
Oracle 8 docker image no longer ships with yum
=> Use DNF on Oracle / CentOS kitchen tests

Gemfile, Gemfile.lock, omnibus/Gemfile.lock, omnibus_overrides.rb
Minor fixes in libarchive for the archive_file resource, but we need to
bump FFI for the new Macs
=> Update FFI to 1.15 for M1 Macs + libarchive to 3.5.1

lib/chef/provider/execute.rb, lib/chef/resource/execute.rb, spec/support/shared/unit/script_resource.rb, spec/unit/resource/powershell_script_spec.rb
This implements https://github.com/chef/mixlib-shellout/pull/78 in the
execute resource.  Default stays the same.
Using `login true` useful things happen like the environment being
set correctly including USER and HOME.
=> Add login option to execute resource

omnibus/Gemfile.lock, omnibus/config/software/more-ruby-cleanup.rb, spec/unit/provider/package/rubygems_spec.rb
This switches omnibus to using the post-bundle-install hook
One fix here to avoid some tests that no longer work on ruby < 3.0 (rubygems changed so the stubs need to change, our code isn't any different)
=> Fix the ruby-3 omnibus builds/tests

habitat/plan.sh, kitchen-tests/kitchen.yml, omnibus/Gemfile.lock, omnibus/config/software/more-ruby-cleanup.rb, post-bundle-install.rb, tasks/bin/run_external_test
This is necessary to build against current omnibus-software and should hopefully be more reliable and is more flexible in terms of being able
to pull git gems into the appbundle.
=> Chef 16: backport the post-bundle-install support

omnibus/package-scripts/chef/postinst
This change builds on my earlier PR (#11158) that created the /etc/chef/* directories necessary to get started. With this change, we now give them a sample /etc/chef/client.rb that they can edit to get started. Also, point them to the docs that tell them what all the config options are.
/etc/chef/client.rb:
```
#
```
=> Drop off a sample client.rb config on *nix

lib/chef/data_bag_item.rb
This should fix our spec tests breaking in buildkite on
the #to_plist method and actually makes DataBagItem's marginally
more useful since they'll lazily delegate those kinds of methods which
are monkeypatched into Hash as well.
=> Use method_missing for data bag item delegation

Gemfile, Gemfile.lock, chef-universal-mingw32.gemspec, chef.gemspec, omnibus/Gemfile.lock
Add version ceilings, allow for the new mixlib-shellout, pin win32-certstore.
=> Update gem pins to better match changes in chef 16

Gemfile, Gemfile.lock, omnibus/Gemfile.lock
This should fix our spec failures in buildkite
=> Resolve failures in testing due to an old rspec_junit_formatter

lib/chef/provider/user/windows.rb
If we're not trying to set a password - which given #10455 is probably
the case - we will always think it's wrong and try to set it. This fixes
that.
Note it does *not* fix #10657 - do not close that one!
=> Fix windows_user password idempotency

lib/chef/provider/mount.rb, spec/unit/provider/mount/mount_spec.rb
Resolves #11255
This is basically a continuation of #11031 where I fixed it in one place but then created a regression with idempotency as noted in #11255. This ensures that the /etc/fstab file actually gets the output we expect with network mounts using a root device.
=> Fix idempotency issues with network mounts

lib/chef/provider/mount.rb, spec/unit/provider/mount/mount_spec.rb
Resolves #11255 and a backport of #11261
This is basically a continuation of #11031 where I fixed it in one place but then created a regression with idempotency as noted in #11255. This ensures that the /etc/fstab file actually gets the output we expect with network mounts using a root device.
=> Chef 16: Fix idempotency issues with network mounts

spec/functional/resource/cron_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb
These don't run due to security changes in the OS.
=> Skip the cron tests on macOS 11+

lib/chef/compliance/runner.rb, spec/unit/compliance/runner_spec.rb
The `#enabled?` method needs a node object  to answer the question,
and the node object is not always available to it
(for example, `#run_failed` when config is wrong).
Fixes #11289 
=> Report compliance runner not enabled if the node is not available

spec/functional/resource/cron_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb
These don't run due to security changes in the OS.
=> Skip the cron integration tests on macOS 11+

lib/chef/resource/hostname.rb
Signed-off-by: smriti <sgarg@msystechnologies.com>
- Create a new property with name 'fqdn'
- While creating a entry in `/etc/hosts` file made sure `fqdn` is considered
- If `fqdn` is not passed by user, it works the same as now.
for resource without specifying fqdn like - 
```
hostname 'aws-ubuntu-1804.kitchen' do
aliases ['aws-ubuntu-1804.kitchen.example.com']
ipaddress node['ipaddress']
end
```
output - for command `hostname -f` 
`aws-ubuntu-1804.kitchen`
but with fqdn property like : - 
```
hostname 'aws-ubuntu-1804.kitchen' do
fqdn 'aws-ubuntu-1804.kitchen.example.com'
ipaddress node['ipaddress']
end
```
output for command `hostname -f` is 
`aws-ubuntu-1804.kitchen.example.com`
[Issue 10694](https://github.com/chef/chef/issues/10694)
=> Added new property fqdn and made sure hosts entry includes the same

.expeditor/release.omnibus.yml, .expeditor/verify.pipeline.yml, kitchen-tests/kitchen.yml, omnibus/kitchen.yml
Ubuntu 16.04 goes EOL at the end of April. Stop producing packages for
this release.
=> Remove soon to be EOL Ubuntu 16.04 packages

chef-utils/lib/chef-utils/dsl/platform.rb, chef-utils/spec/unit/dsl/platform_spec.rb
~~This checks `/etc/os-release` to see if the system is CentOS Stream.~~
This checks `node['lsb']['id']` data to see if the system is the CentOS Stream.
This replaces what was attempted in https://github.com/chef/ohai/pull/1643.
=> Add centos_stream_platform? helper

chef-utils/lib/chef-utils/dsl/platform.rb, chef-utils/spec/unit/dsl/platform_spec.rb
Backport of #11296
- Add `centos_stream_platform?` helper
- Switch to using lsb/id node data for `centos_stream_platform?` helper
- Fall back to `lsb` data if `os_release` data is missing
=> Chef 16: Add centos_stream_platform? helper

.expeditor/release.omnibus.yml
=> Update name of macos 11 in expeditor config

.expeditor/release.omnibus.yml
Ubuntu Pro has FIPS modules. We should enable FIPS builds here since
we're already held to legacy OpenSSL on Linux as is.
=> Produce FIPS builds on Ubuntu as well

chef-utils/lib/chef-utils/dist.rb, lib/chef/provider/package/rubygems.rb, spec/unit/provider/package/rubygems_spec.rb
This resolves the following issue [1] which impacts community distributions when using the `gem_package` provider. Instead of using static names, use proper distribution constants which can be easily set by distributions.
TODO: We should update chefdk with Workstation constants once those are created.
[1] https://gitlab.com/cinc-project/distribution/client/-/issues/31
=> Use dist constants in rubygems provider for is_omnibus? method

chef-utils/lib/chef-utils/dist.rb, lib/chef/provider/package/rubygems.rb, spec/unit/provider/package/rubygems_spec.rb
Backport of #11326
- Use dist constants in rubygems provider for `is_omnibus?` method
- Update to use chef-workstation instead of chefdk
- Create `ChefUtils::Dist::Workstation::DIR_SUFFIX` dist constant
=> Chef 16: Use dist constants in rubygems provider for is_omnibus? method

.expeditor/release.omnibus.yml
Resolves https://github.com/chef/customer-bugs/issues/257
=> Allow FIPS 140-2 OpenSSL FOM to build on PPC EL platforms

lib/chef/resource/macos_userdefaults.rb, lib/chef/resource/plist.rb, lib/chef/resource/windows_firewall_profile.rb, lib/chef/resource/windows_printer.rb, lib/chef/resource/windows_printer_port.rb, lib/chef/resource/windows_security_policy.rb, lib/chef/resource/windows_share.rb, lib/chef/resource/windows_shortcut.rb
Resolves a lack of continuity of the use of the `#load_current_value` API. Both the [chef docs](https://docs.chef.io/custom_resources/#load_current_value) and the [caller](https://github.com/chef/chef/blob/4d3b847aee1b917bb139862c623e9633d180fb31/lib/chef/resource/action_class.rb#L49) of `#load_current_value` both refer to `new_resource` (not `desired`).
Well this is confusing, I just saw that on the same set of docs it references `desired`, see [here](https://docs.chef.io/custom_resources/#multiple-properties).
N/A
=> Use new_resource for load_current_value blocks

.expeditor/release.omnibus.yml
=> Update the Buildkite pipeline for the macOS 11 builder naming

omnibus/omnibus-test.ps1, omnibus/omnibus-test.sh
Updated tests to support the use of skip-artifactory-platforms within the shim pipeline definition where packages will be downloaded directly from the buildkite artifacts api.
=> Update tests to handle local omnibus packages from Buildkite artifacts api

lib/chef/knife/core/windows_bootstrap_context.rb, spec/unit/knife/core/windows_bootstrap_context_spec.rb
www.chef.io/chef/download has been deprecated; we should be using
omnitruck.chef.io/chef/download.
Backport of #11400 to chef-16
=> Update the download URL for windows MSI

cspell.json, lib/chef/compliance/default_attributes.rb, lib/chef/compliance/fetcher/automate.rb, lib/chef/compliance/reporter/automate.rb, lib/chef/compliance/reporter/chef_server_automate.rb, lib/chef/compliance/reporter/cli.rb, lib/chef/compliance/reporter/compliance_enforcer.rb, lib/chef/compliance/reporter/json_file.rb, lib/chef/compliance/runner.rb, spec/unit/compliance/fetcher/automate_spec.rb, spec/unit/compliance/reporter/automate_spec.rb, spec/unit/compliance/reporter/chef_server_automate_spec.rb, spec/unit/compliance/reporter/compliance_enforcer_spec.rb, spec/unit/compliance/runner_spec.rb
Because it is important that when possible, the compliance run
get associated with the converge  that preceded it (via run-id) this PR updates
compliance mode to pre-validate for most common issues before the
converge occurs.
This is a change of behavior, in that previously we would
wait until it was time to send the report after the converge before
validating, which would cause the report to not get captured for current
converge (run-id) if config errors were present.
This also adds error numbers to each of the failure conditions we
detect, in order to simplify providing the operator help with resolving
the errors.
Resolves #11106 and #11105
=> Move most compliance validation to pre-run

omnibus/Gemfile.lock
This reverts commit e5d273f8c70adb18d553faf996da9d36298666b0.
Windows buildings failing on require 'win32/process'
fixes. [https://github.com/chef/chef-workstation/issues/1893](url)
=> Revert "Bump omnibus-software from `0dcaeb1` to `810a6c4` in /omnibus"

Gemfile
We don't support <= 16 due to removal of the ChefFS parallelizer
=> Lock cheffish to 17

spec/unit/chef_fs/diff_spec.rb, spec/unit/chef_fs/file_system_spec.rb
ruby 2.7 is buggy and will always be buggy:
https://bugs.ruby-lang.org/issues/16852
ruby 3.0 is fixed.
=> omit cheffs tests from ruby 2.7

lib/chef/compliance/reporter/json_file.rb, lib/chef/compliance/runner.rb
We were previously logging it earlier in the run, and it could get lost
in backscroll.  With this change, we'll log it at/near the end, at the
time we write the report.
closes #11108
=> Make json-file compliance report path  visible

spec/functional/resource/dnf_package_spec.rb
This is temporary until we can track down why they're running
long enough to consistently timeout.
The Dnf issue itself is tracked in https://github.com/chef/chef/issues/11414
=> Disable Dnf tests for fedora

lib/chef/deprecated.rb, lib/chef/resource/lwrp_base.rb, spec/data/lwrp/resources/bar.rb, spec/data/lwrp/resources/buck_passer.rb, spec/data/lwrp/resources/buck_passer_2.rb, spec/data/lwrp/resources/embedded_resource_accesses_providers_scope.rb, spec/data/lwrp/resources/foo.rb, spec/data/lwrp/resources/inline_compiler.rb, spec/data/lwrp/resources/monkey_name_printer.rb, spec/data/lwrp/resources/paint_drying_watcher.rb, spec/data/lwrp/resources/thumb_twiddler.rb, spec/data/lwrp/resources_with_default_attributes/nodeattr.rb, spec/data/lwrp_const_scoping/resources/conflict.rb, spec/data/lwrp_override/resources/foo.rb, spec/data/run_context/cookbooks/circular-dep1/resources/resource.rb, spec/data/run_context/cookbooks/circular-dep2/resources/resource.rb, spec/data/run_context/cookbooks/dependency1/resources/resource.rb, spec/data/run_context/cookbooks/dependency2/resources/resource.rb, spec/data/run_context/cookbooks/no-default-attr/resources/resource.rb, spec/data/run_context/cookbooks/test-with-circular-deps/resources/resource.rb, spec/data/run_context/cookbooks/test-with-deps/resources/resource.rb, spec/data/run_context/cookbooks/test/resources/resource.rb, spec/integration/recipes/accumulator_spec.rb, spec/integration/recipes/lwrp_inline_resources_spec.rb, spec/integration/recipes/lwrp_spec.rb, spec/integration/recipes/notifies_spec.rb, spec/integration/recipes/notifying_block_spec.rb, spec/integration/recipes/use_partial_spec.rb, spec/unit/lwrp_spec.rb
This also adds coverage in a way for crazy different ways of writing resources and that they just work correctly in unified_mode.
=> Add warning for resources not running in unified_mode

lib/chef/resource/lwrp_base.rb
This changes the deprecation warning from:
```
Deprecated features used!
The test_test resource in the test cookbook should declare `unified_mode true` at 1 location:
- /Users/lamont/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/forwardable.rb:238:in `setup_run_context'
See https://docs.chef.io/deprecations_unified_mode/ for further details.
```
To:
```
Deprecated features used!
The test_me resource in the test cookbook should declare `unified_mode true` at 1 location:
- /Users/lamont/zero/local-mode-cache/cache/cookbooks/test/resources/test.rb
See https://docs.chef.io/deprecations_unified_mode/ for further details.
```
=> Fix location and resource_name of unified_mode deprecation message

lib/chef/formatters/doc.rb, lib/chef/resource/lwrp_base.rb
There was some confusion around this message, make it clear
that it is a warning, and that the timeframe for fixing the
issues is before the next major version drops.
=> Make deprecation warning message more explicit

lib/chef/win32/api.rb
This addresses an issue where `FFI::MemoryPointer.from_string("SOME_STRING").address` is an integer outside of the bounds of a 32 bit signed integer to an `LPARAM` typed win32 function argument. This can happen on 64 bit architecture. See https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types
=> use int64 on x64 architecture for LPARAM and LONG_PTR types

lib/chef/compliance/default_attributes.rb, spec/unit/compliance/runner_spec.rb
This makes it much easier to use out of the box by showing something
real in addition to saving a file to disk.
=> Make CLI one of the default reporters for Compliance Phase

.expeditor/verify.pipeline.yml, .github/workflows/kitchen.yml, .github/workflows/lint.yml, Gemfile, Gemfile.lock, knife/Gemfile
It's a 5 meg gem on windows and it serves very little value.
=> Remove the ruby-prof gem from omnibus packages

spec/integration/client/client_spec.rb
This test requires the gem and we removed the gem so we need to remove
the test
=> Remove profile-ruby tests

lib/chef/cookbook/cookbook_version_loader.rb, spec/spec_helper.rb
This will give us a bit of a prewarning before Ruby breaks our code (assuming we exercise it with a spec)
=> Enable deprecation warnings in our specs

lib/chef/provider/service/systemd.rb, spec/unit/provider/service/systemd_service_spec.rb
Resolves #11496
This adds a missing double splat which is required when using Ruby 3.0.
I confirmed this fixes an issue I was noticing while working on the etcd cookbook.
=> Fix systemd service state detection

lib/chef/provider/systemd_unit.rb, spec/unit/provider/systemd_unit_spec.rb
In #10925 the method of fetching the current systemd unit status was changed.
In this change a typo was introduced which caused the systemctl command which
should look like this
`/usr/bin/systemctl --system show -p UnitFileState -p ActiveState apache2.service`
to instead look like this
`/usr/bin/systemctl --system show -p UnitFileState -p ActiveState apache2.service {}`
The result is that instead of a response like this
```
ActiveState=active
UnitFileState=enabled
```
Chef gets
```
ActiveState=active
UnitFileState=enabled
ActiveState=inactive
UnitFileState=
```
which is the status of the service followed by the status of a bogus service called "{}"
This results in Chef always thinking that systemd unit's are not active and not enabled
and every Chef run attempts to enable and start the …
=> Fix bug causing systemd units to always re-enable and re-start

omnibus/omnibus-test.ps1, omnibus/omnibus-test.sh
This logic has been moved into the Omnibus Buildkite Plugin.
These scripts can now be used outside of the Buildkite pipelines.
Signed-off-by: Tom Duffield <github@tomduffield.com>
=> Remove pipeline-specific logic from test scripts

lib/chef/provider/package/yum/python_helper.rb, spec/unit/provider/package/yum/python_helper_spec.rb
Reset the singleton instance before starting the test, because
singletons.
Also better clears up some internal state when the daemon gets reaped
=> Fix yum specs

lib/chef/dsl/declare_resource.rb, lib/chef/resource_builder.rb, spec/integration/recipes/unified_mode_spec.rb
This makes edit_resource "atomic" so that in unified_mode the block is
played against the resource being built before it is added to the
resource collection and unified_mode fires the resource.
closes #11495
=> Fix edit_resource usage in unified_mode

lib/chef/resource.rb, lib/chef/resource/lwrp_base.rb
This suppresses the unified_mode warning for any resources that have been
deprecated via the chef_version_for_provides mechanism.
=> Suppress unified mode deprecation warning for deprecated resources

lib/chef/resource/windows_security_policy.rb
'LockoutThreshold' is actually implemented by Windows as LockoutBadCouunt. What shows up in an Account Lockout Policy is Account Lockout Threshold but what gets written to disk when you change it is LockoutBadCount. That item is available in the list of existing policy objects. I updated the code to add AuditPolicyChange; that was missing. I also added ResetLockoutCount which pairs with the Lockout Threshold so users aren't permanently locked out. The last item, LockoutObservationWindow, does not appear in a Security Policy as exported by secedit but you can get to it via PowerShell. It is part of a customized fine grain password policy. [Read more here:](http://woshub.com/fine-grained-password-policy-in-windows-server-2012-r2/) 
Signed-off-by: John McCrae <jmccrae@chef.io>
=> windows_security_policy: Add AuditPolicyChange and LockoutDuration capabilities

lib/chef/provider/package/dnf/dnf_helper.py, lib/chef/provider/package/dnf/python_helper.rb, spec/functional/resource/dnf_package_spec.rb
- stabilization fixes to the provider
- we now no longer retry in specs and fail on any errors
- we disable all the repos in the specs for speed
- we only reap the daemon to flush the cache in the specs
- we also only reap the daemon after having setup repos
- all the func specs have been converted to inline resources
- all the i/o is now blocking+flushing instead of nonblocking+confusing
(how did it all ever work?  why did i use nonblocking i/o?)
=> DNF provider update

cspell.json, lib/chef/resource/hostname.rb
Updated the Windows code to use Rename-Computer instead of WMI, added properties for a domain username and password.
Signed-off-by: John McCrae <jmccrae@chef.io>
=> Update Hostname resource to account for newer versions of PowerShell being standard

lib/chef/win32/api.rb
32-on-64 also needs "long" instead of "int64" the same as 32-bit.
(which seems backwards to me, but this gets our tests all green)
=> Treat 32bit-on-64bit the same as 32bit

spec/unit/provider/package/dnf/python_helper_spec.rb
More stable helper now survives the func tests and now throws this test off.
=> Reset the DNF helper to greenify tests

.expeditor/release.omnibus.yml
Avoid the EL7 package name that causes issues with some security scanners
=> Build RHEL 8 packages on RHEL 8 boxes

spec/unit/provider/package/dnf/python_helper_spec.rb
The rspec expectation is remaining attached to the singleton
=> Really fix the DNF spec tests

lib/chef/cookbook/gem_installer.rb
Signed-off-by: Joseph J. Nuspl Jr. <nuspl@nvwls.com>
If a cookbook depends on a gem, chef-client uses `bundle install`. Since it is running as root, you get a scary sounding log message
```
[2021-05-08T15:03:38+00:00] INFO: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
```
Since it is safe, we should silence the warning.
=> Silence `bundle install` warning when installing gems for cookbooks

cspell.json, lib/chef/provider/mount/linux.rb, lib/chef/provider/mount/mount.rb, spec/unit/provider/mount/linux_spec.rb
Signed-off-by: smriti <sgarg@msystechnologies.com>
For the mount type `loop`, I have put in a check to verify the mount point already exists in the system or not.
This PR resolves issue - [#10918](https://github.com/chef/chef/issues/10918)
While iterating output of comman `findmnt -rn` for the mount of type `loop`  name of device is not included in the output. For example for a mount resource as following : - 
```
mount "/var/www/mnt/disk3" do
device "/mnt/public/hdat2cd_lite_71.iso"
device_type :device
options "loop"
action %i{mount enable}
end
```
Once the mount action is performed, the output of `findmnt -rn` will be
`/var/www/mnt/disk3 /dev/loop2 ext2 rw,relatime,seclabel`
Hence in this case we cannot verify if the mount point exist by using this Regexp. where `device_mount_regex` is …
=> mount: Fix idempotentency for loopback mounts

chef-utils/lib/chef-utils/internal.rb
```
[24] pry(#<Ohai::NamedPlugin::Virtualization>)> __env_path
=> "/bin:/sbin:/usr/bin:/usr/sbin\n"
```
This results in a busted /usr/sbin
```
[27] pry(#<Ohai::NamedPlugin::Virtualization>)> __env_path.split(File::PATH_SEPARATOR) + Array(extra_path)
=> ["/bin", "/sbin", "/usr/bin", "/usr/sbin\n", "/usr/local/sbin", "/usr/local/bin", "/usr/sbin", "/usr/bin", "/sbin", "/bin"]
```
=> Strip the __env_path variable in the which helper

knife/lib/chef/knife/ssl_fetch.rb
There is a bad require call in knife/lib/chef/knife/ssl_fetch.rb where a path was accidentally doubled. This fixes that by removing the extraneous extra keyword.
Fixes  knife ssl fetch broken with bad require call in ssl_fetch.rb [#11580](https://github.com/chef/chef/issues/11580)
=> Remove extraneous double mixin for the require.

kitchen-tests/cookbooks/end_to_end/recipes/windows.rb, lib/chef/resource/windows_security_policy.rb
The `net account /LockoutWindow` command which underlies the setting of the ResetLockoutCount property is not limited to 30 minutes.  That is a default because it is the default for the LockoutDuration setting.  This update changes the validation for the ResetLockoutCount security policy so that it is limited by the LockoutDuration setting and not the 30 minute default.
=> Update validation on the ResetLockoutCount to limit it to LockoutDuration rather than limiting it to 30 minutes

.bldr.toml, .expeditor/habitat-test.pipeline.yml, .expeditor/verify.pipeline.yml
Signed-off-by: Collin McNeese <cmcneese@chef.io>
Re-enables the publishing of `kernel2` Habitat packages to allow for Chef Infra Client 17 deployments of Effortless Infra scaffolding with `chef/scaffolding-chef-infra`.
=> Enables kernel2 habitat package builds/promotions

knife/Gemfile
Since
https://github.com/rubygems/rubygems/commit/58f74018dfef25704a42f38467094c4c1391e54f
the previous behaviour of gemspec was restored, so the comment is no
longer relevant on recent bundler versions.
This is the same as #11550, but for another Gemfile.
#11150.
=> Remove comment no longer relevant

.expeditor/habitat-test.pipeline.yml
Signed-off-by: Collin McNeese <cmcneese@chef.io>
Re-enables the promotion of kernel2 Habitat packages to `current` channel which will allow for Chef Infra Client 17 deployments of Effortless Infra scaffolding with chef/scaffolding-chef-infra.
=> Adds promotion of kernel2 package to current channel in expeditor config

lib/chef/resource/homebrew_cask.rb
when `homebrew_cask` is used with a homebrew_path attribute, it will try to install homebrew/cask by default with default options. this can fail in instances of non-standard homebrew paths or for arm64 macs that dont use the default /usr/local installation path. so pass along homebrew_path and owner props to the cask install `homebrew_tap` resource.
Signed-off-by: Matt Kulka <mkulka@parchment.com>
=> pass homebrew_path, owner props to homebrew_tap if installing cask

chef-utils/lib/chef-utils/dist.rb
This starts the process of migrating chef-cli and eventually InSpec to using chef-utils for centralized dist constant management.
For chef-cli, all constants are set here [1] and will be replaced with what's included in this patch eventually. I excluded the "Chef Delivery" constant since it's set to EOL soon anyway.
Since it already references InSpec, I went ahead and ensured we included anything mentioned in inspec's dist.rb [2].
[1] https://github.com/chef/chef-cli/blob/77bb4462183db64f8677cbc6b884b85f91004aa1/lib/chef-cli/dist.rb
[2] https://github.com/inspec/inspec/blob/66a372d71539b9132789aeb92b62690087ed34f2/lib/inspec/dist.rb
=> Additional dist constants used in chef-cli and InSpec

lib/chef/resource/openssl_x509_certificate.rb
I'd like to remove the sensitive flag from the creation of the SSL certificate so that it's possible to pull the certificate through logs without logging onto the host.
N/A
=> Do not set sensitive true for SSL certificate

.expeditor/update_dep.sh
We need to make sure we create pr release branches. Right now the
chef-16 one gets the branch and then the master one uses that same
branch and the PR is busted.
=> Make sure we can run dep update on 2+ branches

CHEF_MVPS.md
Add Joshua Timberman to the Lifetime Community Chef Award Recipient list
Joshua Timberman received a Lifetime Community Chef Award at ChefConf 2018 (the one in Chicago) but is absent from the list.
N/A
=> Update Lifetime Community Chef Award Recipients

.github/workflows/lint.yml
Due to https://github.com/rubocop/rubocop/issues/9832 we're pulling in
configs from vendor dirs in the GitHub Actions job. If you set it with
-c you avoid that.
=> Use our config in RuboCop to prevent pulling in others

lib/chef/action_collection.rb, lib/chef/application.rb, lib/chef/application/base.rb, lib/chef/client.rb, lib/chef/data_collector.rb, lib/chef/event_dispatch/base.rb, lib/chef/handler.rb, lib/chef/handler/slow_report.rb, lib/chef/resource_reporter.rb
By default it looks like this:
```
Starting Chef Infra Client, version 17.2.12
Patents: https://www.chef.io/patents
resolving cookbooks for run list: ["test"]
Synchronizing Cookbooks:
- test (0.0.1)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: test::default
* file[/tmp/foo.xzy] action create (up to date)
Running handlers:
Top 1 slowest resource:
resource           elapsed_time cookbook recipe  source
------------------ ------------ -------- ------- ----------------------------------------
file[/tmp/foo.xzy] 0.015114     test     default test/recipes/default.rb:2:in `from_file'
- Chef::Handler::SlowReport
Running handlers complete
Chef Infra Client finished, 0/1 resources updated in 03 seconds
```
It supports `--no-slow-report` to turn it off.  It …
=> Add a slow resources report to chef-client

knife/lib/chef/knife/configure.rb
I don't think the defined? Ohai was working correctly above. Confirmed
locally this works
=> Make sure we load ohai in knife configure correctly

lib/chef/cookbook_version.rb, lib/chef/exceptions.rb, spec/unit/cookbook_version_spec.rb
This adds support for recipe files that end in the '.yaml'
extension in addition to existing support for '.yml', because
both are valid and common extensions for yaml files.
Of note is that the message we log when a recipes/default.y[a]ml
and a root_files/recipe.y[a]ml both exist will be slightly off, in that
we don't capture the actual extension of each file. This seems to be
more complexity than it was worth, for a message that is shown at the
beginning of the run and largely ignored.
I also tried to add a bit of localized unit testing for
`recipe_yml_filenames_by_name` because we didn't before.  Mostly focuses
on this use case (yaml, yml both work) but we could probalby improve
that by including tests for a mix of yaml/yml files.
In addition, we will now fail the run when a cookbook …
=> Support recipes that and in .yaml as well as .yml

lib/chef/handler/slow_report.rb, spec/unit/handler_spec.rb
The slow report now walks through action records instead of
the resources and should have unique records for elapsed_time and
will report the slowest actions.
=> Fix Chef::Handler specs and slow report behavior

knife/lib/chef/knife/org_user_add.rb
This fixes the following error when using `knife org user add`: 
```
[redacted]/lib/chef/knife/org_user_add.rb:32:in `require_relative': cannot load such file -- /[redacted]/lib/chef/org (LoadError)
```
=> Fix incorrect require_relative causing failures in `knife org user add`

lib/chef/resource/windows_pagefile.rb, spec/functional/resource/windows_pagefile_spec.rb, spec/unit/resource/windows_pagefile_spec.rb
=> Updated the Windows Pagefile resource to use PowerShell over WMI, added a corresponding test file

lib/chef/resource/windows_printer.rb
Minor improvement here to cleanup the logging when you delete and make it a bit faster.
=> windows_printer: use powershell_exec to delete the printer instead of slower/double logging powershell_script

kitchen-tests/cookbooks/end_to_end/recipes/_windows_printer.rb, kitchen-tests/cookbooks/end_to_end/recipes/windows.rb, lib/chef/resource/windows_printer_port.rb
- Avoid double logging caused by converge_by and powershell_script
- Remove all the slow use of powershell_script
- Set the default for portname on the resource instead of calculating it the same in 3 places
- Load the state fully / remove the exists? method
- Delete the power with the powershell cmdlet
- Add updating to the create action
- Deprecate the description property which never did anything
=> Cleanup windows_printer_port and allow updating the port

Gemfile, Gemfile.lock
This lets folks workaround not having knife by installing it back on
windows. This gets removed in 18.
=> Add ed25519 gem back to the omnibus install

lib/chef/resource/windows_firewall_rule.rb, spec/unit/resource/windows_firewall_rule_spec.rb
Updated the spec file to account for the change in data types
=> windows_firewall_rule: allow for multiple remote addresses

chef-config/lib/chef-config/config.rb, lib/chef/data_collector/run_end_message.rb, lib/chef/deprecated.rb, lib/chef/node.rb, spec/unit/data_collector_spec.rb
With this change the attribute block and allow list filtering has been extended to the Automate data collector. This will make captured attributes consistent across Automate and Chef Infra Server. 
Fixes #10895
=> Support attribute block/allow list in data collector

chef-utils/README.md, chef-utils/lib/chef-utils/dsl/platform_family.rb, chef-utils/lib/chef-utils/parallel_map.rb, chef-utils/spec/unit/dsl/platform_family_spec.rb, chef-utils/spec/unit/parallel_map_spec.rb
This is useful for internal use when we are in a class context or
whenever we are before load_node/build_node.
It might also be useful for users to gate requires that are
macos-specific for macos only gems, or something like that.
=> Add macos_ruby? helper and wire to the macos? helper

lib/chef/handler/slow_report.rb
When a resource is marked sensitive, the source_line is nil and you can't gsub on it. So if a sensitive resource is slow, it should not crash the SlowReport because it has no source_line.
Fixes chef/chef#11690
=> Handle source_line being nil gracefully

kitchen-tests/cookbooks/end_to_end/recipes/_windows_printer.rb, lib/chef/resource/windows_printer.rb, lib/chef/resource/windows_printer_port.rb
The windows_printer_port resource offers a number of options for
creating an advanced printer port. Let users create a printer that
attaches to a port.
This also properly builds current_resource and nukes the terrible
printer_exists?
=> windows_printer: Install drivers, allow skipping port creation, and load state properly

Gemfile.lock, omnibus/Gemfile.lock
=> Update Ohai to 17.2, InSpec to 4.37.20 and add back windows deps

lib/chef/deprecated.rb
Catches a case where deprecations can be thrown against eval'd code.
```
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.2.29/lib/chef/deprecated.rb:82:in `initialize'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.2.29/lib/chef/deprecated.rb:82:in `open'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.2.29/lib/chef/deprecated.rb:82:in `silenced?'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.2.29/lib/chef/formatters/doc.rb:369:in `deprecation'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.2.29/lib/chef/event_dispatch/dispatcher.rb:78:in `call'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.2.29/lib/chef/event_dispatch/dispatcher.rb:78:in `block in call_subscribers'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.2.29/lib/chef/event_dispatch/dispatcher.rb: …
```
=> Fix edge condition in deprecation silence checker

Gemfile, Gemfile.lock
This permits `pry-byebug` to continue working with it, until
either https://github.com/pry/pry/pull/2177 is merged,
or  https://github.com/deivid-rodriguez/pry-byebug/issues/343 is
otherwise resolved.
=> Pin `pry` to 0.13.0

.expeditor/release.omnibus.yml
This ensures they have el8 in their name
=> Build RHEL 8 packages on RHEL 8

kitchen-tests/cookbooks/end_to_end/recipes/_chef_client_config.rb, lib/chef/resource/support/client.erb
These 2 properties don't match the config format so the existing logic didn't work.
=> Fix handling of ohai properties in chef_client_config

lib/chef/policy_builder/policyfile.rb, spec/unit/policy_builder/dynamic_spec.rb, spec/unit/policy_builder/policyfile_spec.rb
Extends override run_lists to work within the policyfiles framework.
- No additional depsolving is done so the cookbook set does not change, and it will be impossible to run any recipe which isn't already being sychronized to the node.  This is a difference between how override run_lists work in a berks workflow where the chef-client redepsolves with the override run_list, prunes and resychronizes its cookbook set pulling in all the latest versions of any cookbook.  In a policyfile world the recipe(s) used in the override run_list must be already shipped to the node by the policyfile.  All that has to happen is any cookbook in the cookbook set must depend on the cookbook(s) providing the override run_lists.  It may be useful to have a set of utility override run_list in a cookbook which …
=> Support override run_lists in policyfiles

lib/chef/provider/package/powershell.rb, spec/unit/provider/package/powershell_spec.rb
Adds the ability for the user to pass options to  the `powershell_package` resource.
I made an effort to de-duplicate options since some are passed by default but its not comprehensive by any means. 
Resolves #9129
=> Add user provided options to powershell_package commands

lib/chef/dsl/secret.rb, spec/unit/dsl/secret_spec.rb
When a resource block contains usage of the secrets DSL,
auto-mark that resource sensitive to help reduce the potential for
sensitive data to be output to logs/stdout.
=> Mark resource blocks containing secrets sensitive

chef-config/lib/chef-config/config.rb, knife/lib/chef/knife/core/bootstrap_context.rb, knife/lib/chef/knife/core/windows_bootstrap_context.rb, knife/spec/unit/knife/core/bootstrap_context_spec.rb, knife/spec/unit/knife/core/windows_bootstrap_context_spec.rb
Adds bootstrap path configs
Adds bootstrap path configs, taking feedback from #11189 the goal is to fix a bug in bootstrap where the workstation pathing configs make it to the remote machine.
#10964, https://github.com/chef/customer-bugs/issues/239, [#9094](https://github.com/chef/chef/issues/9094) and #10367
=> adds unix_bootstrap and windows_bootstrap path configs

lib/chef/resource/habitat/habitat_package.rb, lib/chef/resource/habitat/habitat_sup.rb, lib/chef/resource/habitat_config.rb, lib/chef/resource/habitat_install.rb, lib/chef/resource/habitat_service.rb, lib/chef/resource/habitat_user_toml.rb, tasks/docs.rb
- Use our standard description format
- Indent the properties to make them easier to read
- Remove defaults from the property descriptions since that's generated
- Skip documenting the state properties
=> Update descriptions for the new habitat resources

Gemfile.lock, chef.gemspec, lib/chef/dsl/secret.rb, lib/chef/secret_fetcher.rb, lib/chef/secret_fetcher/aws_secrets_manager.rb, spec/unit/secret_fetcher_spec.rb
In a recipe, usage will look like the following:
```ruby
value = secret(name: "test1", service: :aws_secrets_manager, config: { region: "us-west-1" })
log "My secret is #{value.secret_string}"
```
Note the use of `secret_string` to determine the secret value. The
returned object here is `Aws::Types::GetSecretValueResponse` from the AWS SDK.
This beta implementation supports ec2/imds instance profile
authentication but also checks standard locations for credentials
configuration -- see documentation [1] for a description of default credentials search behavior.
[1] https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SecretsManager/Client.html#initialize-instance_method
=> Experimental support for an AWS Secrets Fetcher

omnibus/config/software/more-ruby-cleanup.rb
We need that file. Also remove the fauxhai cleanup since we don't ship
that gem anymore.
=> Don't cleanup the VERSION file in the aws gem install

.expeditor/verify.pipeline.yml
These fail as they require chef 17 and we don't really care here because
workstation ships chef / knife from master so nothing on this branch
impacts that.
=> Remove external testing on the chef-16 branch

chef-config/lib/chef-config/config.rb, lib/chef/policy_builder/policyfile.rb, spec/unit/policy_builder/policyfile_spec.rb
This will allow temporarily setting the run list to a different
setting and still having the node saved (complimentary to setting
an override run list which does not save the node).
This can be used inside of test-kitchen for setting the run_list
to a fixture cookbook that is not in the policyfile without
needing to go through named_run_lists.
This can also be used with -j or -r on provisioning to run a
bootstrapping recipe, which will then be overridden by the
policyfile.
A switch is included to cause the node.run_list setting from the
-j or -r setting (or setting via code with `node.run_list <<`) to
persist and to override the policyfile.  This is for sites which
have adopted complicated run_list mutating workflows to make it so
they can set Chef::Config[:policy_persist_run_list] to …
=> Support command line setting of run_list with policyfiles

lib/chef/dsl/secret.rb, lib/chef/exceptions.rb, lib/chef/secret_fetcher.rb, lib/chef/secret_fetcher/aws_secrets_manager.rb, lib/chef/secret_fetcher/azure_key_vault.rb, lib/chef/secret_fetcher/base.rb, lib/chef/secret_fetcher/example.rb, spec/unit/dsl/secret_spec.rb, spec/unit/secret_fetcher/azure_key_vault_spec.rb, spec/unit/secret_fetcher_spec.rb
Adds fetcher for azure key vault and adds support for version to the DSL and existing fetchers.
In a recipe, usage will look like the following:
```
value = secret(name: "test1", service: :azure_key_vault, config: { vault: "my-test-vault" })
log "My secret is #{value}"
```
`:version` is a supported option (to specify the version of the secret):
```
value = secret(name: "test1", version: "1", service: :azure_key_vault, config: { vault: "my-test-vault" })
log "My secret is #{value}"
```
=> Secrets: Azure Key Vault fetcher; versioned secret support

lib/chef/dsl/secret.rb
Ensure that people know the secret DSL is subject to change, and should
be used with caution.
Fixes #11835
=> Add warning to secret DSL usage

lib/chef/secret_fetcher/aws_secrets_manager.rb
THis was accidentally removed when removing validation requirements
for this fetcher.
=> secrets: Ensure provided config is passed into AWS

lib/chef/resource/systemd_unit.rb, spec/unit/resource/systemd_unit_spec.rb
- Fixed generates systemd service should not have spaces around the equal signs.
- Fixed testcase failure.
#9259
=> systemd_unit generates invalid units when passing a hash issue fix

lib/chef/dsl/secret.rb, lib/chef/secret_fetcher.rb, lib/chef/secret_fetcher/aws_secrets_manager.rb, lib/chef/secret_fetcher/base.rb, spec/unit/dsl/secret_spec.rb, spec/unit/secret_fetcher/aws_secrets_manager_spec.rb, spec/unit/secret_fetcher/azure_key_vault_spec.rb, spec/unit/secret_fetcher_spec.rb
This change provides access to the `run_context` for secrets fetchers and specifically allows the ec2 fetcher to determine region from ohai data. 
The config fetch priority is: 
- explicitly provided config
- aws global config
- node ohai data 
This provides a sane and predictable way to play nicely with AWS SDK's
default config loading behavior while still supporting loading config based on node/ohai attributes
TLDR - `region` is not required to fetch an AWS secret, assuming that the ec2 ohai plugin is not disabled. 
Closes #11851
=> secrets: add support for default config from ohai data 

lib/chef/resource/homebrew_cask.rb, spec/unit/resource/homebrew_cask_spec.rb
Some cask name include '-' and '@' so I fix regular expressions for
cask name validation.
I change regular expression for cask name validation to support '-' and '@'
Some cask name like emacs-plus@28 include '-' and '@' but it can't accept by validation.
No related issues found.
=> Support '-' and '@' for homebrew cask name

knife/lib/chef/knife/bootstrap.rb, knife/lib/chef/knife/bootstrap/train_connector.rb, knife/spec/unit/knife/bootstrap_spec.rb
Signed-off-by: sanga17 <sausekar@msystechnologies.com>
Fixed issues facing while bootstrapping the node using ssh config file.
Fixed: 1) https://github.com/chef/chef/issues/7053
2) https://github.com/chef/customer-bugs/issues/271
=> Fixed issues facing while bootstrapping the node using ssh config file.

.expeditor/build-docker-images.sh, .expeditor/config.yml, .expeditor/docker-build.pipeline.yml, .expeditor/docker-manifest-create.sh, .expeditor/promote-docker-images.sh
=> Add custom docker pipeline for multiarch builds

lib/chef/exceptions.rb, lib/chef/secret_fetcher/azure_key_vault.rb, spec/unit/secret_fetcher/azure_key_vault_spec.rb
This modifies the `:azure_key_vault` fetcher so that it's possible
to fetch a secret by embedding the vault name in the secret name
instead of providing it in configuration. This continues down the path
of making secrets accessible with less typing and sane default
expectations.
Example:
```
file "/home/ubuntu/test2" do
content secret(name: "test-chef-infra-secrets/test-secret-1", service: :azure_key_vault)
end
```
Specifying vault name via configuration is still supported, but if it is
specified in the secret name as well that will take precedence.
Fixes: #11852 
=> Allow az vault name to be included in secret name

lib/chef/compliance/default_attributes.rb, spec/unit/compliance/runner_spec.rb
Getting Chef Infra attributes into Chef Inspec inputs is a FAQ and this
seems like an obviously better default.
We are unaware of any breaking change this would cause.
=> Turn on chef_node_attribute_enabled for compliance phase by default

.expeditor/build-docker-images.sh, .expeditor/docker-manifest-create.sh, .expeditor/promote-docker-images.sh
Make scripts have sane defaults for ENV VARS and login to docker when running the bash action to authenticate to the chef docker organization.
=> clean up scripts and docker login to auth to chef docker org

.expeditor/build-docker-images.sh, Dockerfile
Update Dockerfile to pull in the correct version of chef when building for arm
=> update dockerfile to use correct package for os/arch

lib/chef/compliance/default_attributes.rb, lib/chef/compliance/runner.rb, spec/unit/compliance/runner_spec.rb
Supports attributes as a fallback.
Blows up if you set both.
Closes #11572
=> Rename inspec attributes to inputs in compliance phase

knife/lib/chef/knife/core/windows_bootstrap_context.rb, knife/spec/unit/knife/core/windows_bootstrap_context_spec.rb
Signed-off-by: smriti <sgarg@msystechnologies.com>
log_level while being set in client.rb was referring to wrong hash variable
` knife bootstrap -o winrm IPaddress -U 'USERNAME' -P 'PASSWORD' -c /.chef/config.rb -N NODENAME -V`
" -V " verbose option plays a role in value of final log_level setting in client.rb
To set `log_level` it searches in `config[:config_log_level]` which is wrong hash variable, hence file being created with default log_level = auto always it should look for log_level in `chef_config[:config_log_level]`
https://github.com/chef/chef/issues/11367
- [] I have updated the documentation accordingly.
=> knife bootstrap windows: log_level should be updated as in client.rb

lib/chef/provider/user/mac.rb
Signed-off-by: Gilbert Liu <zpak@fb.com>
Moving mac_user `create_user` to use `dscl` to create user when running without full disk access
The UID is different than what Chef specifies in the `sysadminctl` command, and this causes later Chef run to fail.
Running `sysadminctl` command on M1 Mac mini, both macOS 11.4 and 12.0, SIP on, default security level.
```
2021-06-15 18:29:41.702 sysadminctl[64046:1889653] ----------------------------
2021-06-15 18:29:41.702 sysadminctl[64046:1889653] No clear text password or interactive option was specified (adduser, change/reset password will not allow user to use FDE) !
2021-06-15 18:29:41.702 sysadminctl[64046:1889653] ----------------------------
2021-06-15 18:29:41.748 sysadminctl[64046:1889653] Creating user record…
2021-06-15 18:29:41.796 …
```
=> fix mac_user create_user for running without full disk access

lib/chef/provider.rb, lib/chef/provider_resolver.rb, lib/chef/resource.rb, lib/chef/resource_inspector.rb, spec/integration/recipes/resource_action_spec.rb, spec/unit/provider_spec.rb, spec/unit/resource_spec.rb
Often actions are defined on the provider and not on the resource.  This
change updates Provider to support a description opt when declaring the
action, which lets us improve our generated documentation.
This also updates ResourceInspector to look at the provider if the
resource itself does not offer an action description for a given action.
Example:
action :foo, description: "bar" do
...
end
=> Add support for provider action description

lib/chef/application.rb
=> Make the stacktrace.out message more visible

lib/chef/resource/rhsm_subscription.rb, spec/unit/resource/rhsm_subscription_spec.rb
This will ensure that recently attached subscription packages will be resolved by Chef Infra Client.
- Closes #10722
=> Flush package cache after attaching to rhsm subscription

.expeditor/scripts/bk_win_prep.ps1, .expeditor/verify.pipeline.yml, .github/workflows/kitchen.yml, omnibus/Gemfile, omnibus/README.md
Replacing **--without** flag with **bundle config** to get rid of bundler deprecated warning :
[DEPRECATED] The --without flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use bundle config set without 'development doc', and stop using this flag
Signed-off-by: jayashri garud <jgarud@msystechnologies.com>
=> Replace deprecated --without flag with bundle config

lib/chef/provider/group/dscl.rb
When executing `:create` action for a group that already exists and passing the `gid` as `Integer`, the resource ends up in `set_gid` block and raise the error on this line https://github.com/chef/chef/blob/eb34e97386cb393c5558e4814adbc3174f532620/lib/chef/provider/group/dscl.rb#L103
This PR fixes the issue by making sure the comparison between `current_resource.gid` and `new_resource.gid` is correctly performed by using `to_s` on `new_resource.gid` since `current_resource.gid` is always a string.
#11624
=> group: fix gid in use error on macOS

lib/chef/provider/user/mac.rb
This reverts the changes in #11731 
This introduces CI failures that we need to look into further. Meanwhile, reverting so that it does not block a release.
=> Revert 11731

lib/chef/provider/group/dscl.rb
Backporting the following change made in https://github.com/chef/chef/pull/11927 to `chef-16`.
> When executing `:create` action for a group that already exists and passing the `gid` as `Integer`, the resource ends up in `set_gid` block and raise the error on this line https://github.com/chef/chef/blob/eb34e97386cb393c5558e4814adbc3174f532620/lib/chef/provider/group/dscl.rb#L103
> 
> This PR fixes the issue by making sure the comparison between `current_resource.gid` and `new_resource.gid` is correctly performed by using `to_s` on `new_resource.gid` since `current_resource.gid` is always a string.
#11624
=> Backport: group: fix gid in use error on macOS

lib/chef/provider/user/mac.rb
After merging https://github.com/chef/chef/pull/11731 our functional tests started failing. It turns out we're not being defensive about data missing when we parse the dscl -> plist -> current resource. On my mac after creating a single user 'foo' with all defaults the shell data is nil as is the is_hidden data. The way we try to get the first item in the array fails on a method missing error for nilclass.
=> Fix failures in mac_user when not all user fields are present

lib/chef/compliance/default_attributes.rb, spec/integration/compliance/compliance_spec.rb, spec/unit/compliance/runner_spec.rb
This indirectly fixes #11585 and avoids the json logger silently
consuming disk space.  By reverting back to a single value we also
avoid the attributes array merging issues.
This might conceivably change behavior to people who were reliant
on the additive array-merge behavior, but the compliance phase
has been considered experimental.
=> Remove the default json logger from the compliance API

Gemfile.lock, chef.gemspec, lib/chef/secret_fetcher.rb, lib/chef/secret_fetcher/aws_secrets_manager.rb, lib/chef/secret_fetcher/azure_key_vault.rb, lib/chef/secret_fetcher/hashi_vault.rb, spec/unit/secret_fetcher/hashi_vault_spec.rb
Vault secrets are stored as key-value pairs, so the return value
from a secret lookup is always a Hash.
Example:
```
file "/home/user/test1" do
content secret(name: "secret/example",
service: :hashi_vault,
config: {
vault_addr: "vault.example.com",
role_name: "example-role"
})[:answer]
end
```
As shown above, we are expecting a hash from Vault, and are populating the file
content based on the value of `:answer` in that hash.
Limitations:
* This iteration only supports instance authentication via a Vault
role connected to an IAM profile.
* This iteration does not support versioned secrets
=> Add support for secrets stored in HashiCorp Vault

lib/chef/resource/windows_uac.rb
…_users
`windows_uac` was trying to set `2` for `ConsentPromptBehaviorUser` key under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System` which isn't valid. Updated it based on the documentation: https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/user-account-control-group-policy-and-registry-key-settings#registry-key-settings 
I couldn't think of any appropriate symbol name to put at index 2 without potentially creating mild confusion. Instead of adding checks, I have inserted `nil` at that index to imply that the index is unused as a registry value. Added a comment to go with it as well. 
#11570
=> windows_uac: fix registry settings for consent_behavior_users

lib/chef/resource/windows_user_privilege.rb
Signed-off-by: snehaldwivedi <sdwivedi@msystechnologies.com>
`Windows_user_privilege` resource throws the error `privilege is required` even when it was set. As the value for `privilege` was not getting copied. As privilege is part of the identity that should get copied to the current resource rather than loaded in load_current_value so added `identity: true` for it.
https://github.com/chef/customer-bugs/issues/413
https://github.com/chef/chef/issues/11744
=> windows_user_privilege.rb : fixed exception: privilege is a required property, even when it was set

lib/chef/resource/user_ulimit.rb, spec/unit/resource/user_ulimit_spec.rb
Signed-off-by: Ashwin <avarma@msystechnologies.com>
- Sensitive property was not working on user_ulimit.
- Added required specs.
https://github.com/chef/chef/issues/11892
=> ulimit: Fix sensitive property

spec/functional/resource/group_spec.rb, spec/functional/resource/link_spec.rb
For some reason our temporary AIX 7.2 system does not correctly report group membership immediately after changes have been made. Adding a 2 second delay for this platform is enough to get correct results. We hope to remove this delay after we get more permanent AIX 7.2 systems in our CI pipeline. reference: https://github.com/chef/release-engineering/issues/1617
Use a higher starting uid for tests. Some of our new test infrastructure has uids that are colliding with the 30000 starting point.
=> Fix tests for new omnibus test systems

lib/chef/secret_fetcher/hashi_vault.rb, spec/unit/secret_fetcher/hashi_vault_spec.rb
Token-based auth is common in automated environments, so this
change adds support for token-based authentication to the Hashi Vault
secret fetcher.
A new configuration item has been added `:auth_method`, which must be
one of `:iam_role` or `:token`.  When `auth_method` is not specified, it
defaults to `:iam_role` for backward compatibility with the initial
implementation.
All authentication methods require a `:vault_addr` configuration entry
If using `auth_method: :token`, a :token configuration entry must also
be provided.
If using `auth_method: :iam_role`, a :role_name configuration entry must
also be provided.
Fixes #11963 
=> Update HashiCorp Vault fetcher to support token auth

lib/chef/secret_fetcher.rb, lib/chef/secret_fetcher/akeyless_vault.rb, lib/chef/secret_fetcher/hashi_vault.rb, spec/unit/secret_fetcher/akeyless_vault_spec.rb
This iteration uses AKeyless's Hashi Vault compatibility proxy.  To use it, ensure that  `hvp.akeyless.io` is accessible from the nodes being converged. 
Example usage: 
```
file "/home/user/test1" do
content secret(name: "/secret/data/MySecret",
service: :akeyless_vault,
config: {
access_key: "....api access key here...",
access_id: "...api access id here...", 
}).to_s
end
```
Fixes #11825 
=> Add AKeyless Vault support

lib/chef/provider/link.rb, lib/chef/provider/template.rb, spec/unit/provider/link_spec.rb, spec/unit/provider/template_spec.rb
For the link provider around line 155 it was stubbing `File.exists?("#{CHEF_SPEC_DATA}/fofile-link")` to true for the provider, while `File.exist?("#{CHEF_SPEC_DATA}/fofile-link")` was false because it didn't exist inside of ScanAccessControl which would effectively NOP the evaluation of ScanAccessControl in load_current_resource.  By setting up the expectation on `File.exist?` to true now that means that ScanAccessControl would run which would blow up.  The whole thing made my head kind of hurt a bit and I'm not certain that the expectations in the specs are even correct.  But I've hit my hard timebox for this so I just preserved the original behavior the way I found it.
The best thing to do would probably be to junk all the link provider specs entirely and start over clean, with no …
=> Clean up some more File.exists? uses

lib/chef/resource/chef_client_scheduled_task.rb, spec/unit/resource/chef_client_scheduled_task_spec.rb
…t splay and snapped start time for predictable actual start times
Signed-off-by: George Holt <George.Holt@bwater.com>
=> Enable chef-client scheduled task to behave like chef_client_cron, with consistent delay calculated once from splay

lib/chef/resource/mount.rb, spec/unit/resource/mount_spec.rb
Signed-off-by: JiSoo Kim <jskim910118@gmail.com>
Since #10614, mount resource is updated to have coerce in mount_point attribute. root directory
There were several issues around for root of the network mount, but the same change is also affecting the plain root directory. After the coercion, it is simply going to be nil. This PR is trying to address the issue by not applying the coercion when mount_point is either root directory or root of network mount.
https://github.com/chef/chef/issues/12021
=> Coerce mount_point only when it is not root directory

.expeditor/scripts/bk_linux_exec.sh, .expeditor/scripts/bk_win_prep.ps1, .expeditor/verify.pipeline.yml, .github/workflows/kitchen.yml, tasks/rspec.rb
[Bundler](https://bundler.io/) is/has deprecated the `--path` argument to `bundle install`. This updates all uses of `bundle install --path=vendor/bundle` to the new `bundle config set --local path 'vendor/bundle'`
N/A
=> Update bundle config set path

cspell.json, lib/chef/http.rb, lib/chef/http/basic_client.rb, lib/chef/provider/remote_file/http.rb, lib/chef/resource/remote_file.rb, spec/unit/http/basic_client_spec.rb, spec/unit/http_spec.rb, spec/unit/provider/remote_file/http_spec.rb
This lets the remote_file resource set any of the Chef::HTTP options.
It also exposes the Net::HTTP settings like "ssl_timeout" through a "nethttp" sub-hash.
Note that "rest_timeout" can set be set at the higher level which is the Chef::HTTP/Chef::Config option that winds up setting both the read_timeout and open_timeout to the same value at the lower nethttp setting.  Setting the nethttp settings explicitly will override those completely.
The defaults on the read_timeout and open_timeout are 300 seconds (due to needing to work around crushed chef-servers caused by thundering herd starts of hundreds of chef-clients at the same time).  Since that may also happen with thundering herds of chef-clients hammering on some expensive remote_file resource at the same time that default is …
=> Add http_options property to remote_file

spec/functional/resource/archive_file_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb, spec/unit/resource/archive_file_spec.rb
This aims to exclude testing archive_file in CI environments where libarchive loading is broken. This is intended to be temporary while working through issues in various CI pipelines.
N/A
=> Exclude running libarchive tests on platforms where loading libarchive is broken

.expeditor/adhoc-canary.omnibus.yml, .expeditor/release.omnibus.yml
FreeBSD 11 goes EOL at the end of Sept 2021.
=> Remove EOL FreeBSD 11 builds

.expeditor/release.omnibus.yml
Ubuntu 16.04 had its support lifecycle extended to a full 10 years so it goes EOL April 2026 now.
=> Add Ubuntu 16.04 back to the builds

cspell.json, kitchen-tests/test/integration/end-to-end/_openssl.rb, lib/chef/resource/openssl_x509_certificate.rb
Checking for csr_file wasn't correct, because that's not what we're
using to load the ca key.
This also adds an inspec verification to ensure that the generated
`openssl_x509_certificate` in the _openssl.rb test is valid. It fails
without the supporting change.
Fixes #12091 
=> Check for ca_key_file before loading ca key

lib/chef/win32/version.rb
Add windows server 2022 version info to lib/chef/win32/version.rb
Signed-off-by: Wade Peacock wade.peacock@alida.com
=> Windows Server 2022 - version / build information ADD

lib/chef/win32/version.rb
Add windows server 2022 version info to lib/chef/win32/version.rb
Signed-off-by: Wade Peacock <wade.peacock@alida.com>
=> CHEF16 - Win2k22 - version / build information ADD

lib/chef/win32/version.rb
Update lib/chef/win32/version.rb - Add less than 2022 build number
This was an oversight
Follow up to: https://github.com/chef/chef/pull/12096
Signed-off-by: Wade Peacock <wade.peacock@alida.com>
=> CHEF16 - Windows2019 - Version ceiling lib/chef/win32/version.rb

lib/chef/win32/version.rb
Update lib/chef/win32/version.rb - Add less than 2022 build number
This was an oversight
Follow up to: https://github.com/chef/chef/pull/12094
Signed-off-by: Wade Peacock <wade.peacock@alida.com>
=> CHEF17 - Windows2019 - Version ceiling lib/chef/win32/version.rb

lib/chef/resource/execute.rb
Fix a small typo
N/A
- [N/A] I have run the pre-merge tests locally and they pass.
- [N/A] I have added tests to cover my changes.
- [N/A] All new and existing tests passed.
=> Fix small documentation typo in execute.rb

lib/chef/resource/chef_client_launchd.rb
`chef_client_launchd` resource was not working for macos since load and unload calls for system tasks need sudo. due to this, script in chef.restarter failed silently and was unable to launch the chef-client service to run periodically. this pull request addresses this issue by adding sudo to the both load and unload calls. 
https://github.com/chef/desktop-config/issues/444
=> chef_client_launchd: fix silent fail on reloading chef client service via restarter daemon

lib/chef/provider/package/zypper.rb, spec/functional/resource/zypper_package_spec.rb
Specifically this fixes `:remove` when there's no candidate_version, but is more correct and may fix other behaviors as well.
=> Fix zypper_package behavior when there is no candidate_version

lib/chef/resource/macos_userdefaults.rb, spec/functional/resource/macos_userdefaults_spec.rb
The input type is validated against the coerced values, which makes the userdefaults resource throw an error when using `:current` or `:all`. Removed coerce and uses the methods directly to transform values.
=> fix invalid ffi type error after coerce in macos_userdefaults

.expeditor/release.omnibus.yml
We support N-2 macOS releases which is 12, 11, and 10.15 now.
=> Stop producing macOS 10.14 packages

lib/chef/mixin/why_run.rb, lib/chef/provider.rb, spec/unit/file_access_control_spec.rb, spec/unit/mixin/why_run_spec.rb, spec/unit/provider/group/groupadd_spec.rb, spec/unit/provider/group/usermod_spec.rb, spec/unit/provider/ifconfig_spec.rb, spec/unit/provider/package/bff_spec.rb, spec/unit/provider/package/solaris_spec.rb, spec/unit/provider/service/arch_service_spec.rb, spec/unit/provider/service/debian_service_spec.rb, spec/unit/provider/service/gentoo_service_spec.rb, spec/unit/provider/service/macosx_spec.rb, spec/unit/provider/service/redhat_spec.rb, spec/unit/provider/service/simple_service_spec.rb, spec/unit/provider/user_spec.rb
define_resource_requirements should not parse assertions for actions
which are not being run.
This came up in the context of this code in the Chef::Provider::Package superclass:
```
def define_resource_requirements
requirements.assert(:install) do |a|
a.assertion { candidates_exist_for_all_forced_changes? }
a.failure_message(Chef::Exceptions::Package, "No version specified, and no candidate version available for #{forced_packages_missing_candidates.join(", ")}")
a.whyrun("Assuming a repository that offers #{forced_packages_missing_candidates.join(", ")} would have been configured")
end
....
end
```
During an `:remove` that isn't relevant at all, but DRR is still parsed and prior to this change the assertion for the :install action was being built.  This doesn't cause an issue for the …
=> Do not run assertions for actions that are not being executed

lib/chef/resource/chef_client_config.rb, lib/chef/resource/support/client.erb
Add 2 config items to the chef infra client config generator
Not every chef infra server can talk to an automate instance or people running chef solo need a way to send their data to automate.
This is [documented](https://docs.chef.io/automate/data_collection/#configure-chef-infra-client-to-use-the-data-collector-endpoint-in-chef-automate) and this PR brings that functionality into the resource.
N/A
=> Add data collector config items for infra config

.expeditor/release.omnibus.yml
We support N-2 which is 12, 11, 10.15 now.
=> Remove support for macOS 10.14

.github/workflows/kitchen.yml, kitchen-tests/kitchen.yml
There's a docker container for the nightly builds of this version now.
=> Replace Ubuntu 21.10 testing with 22.04 testing

lib/chef/resource/homebrew_tap.rb
brew tap --full is no longer supported and there is no replacement.
Fixes #12345
=> Remove the full option from homebrew_tap

lib/chef/provider.rb
Problem: Currently when using [#build_resource](https://github.com/chef/chef/blob/main/lib/chef/dsl/declare_resource.rb#L309-L310) it references both the recipe name and cookbook name. Because the `Chef::Provider` class doesn't redirect this onto `new_resource` it gets missed and ends up building a resource with a `cookbook_name` defined, but *not* a `recipe_name`.
This ensures that child resource(s) actually get the correct recipe name for where they were built.
N/A
=> Add #recipe_name to Chef::Provider

lib/chef/resource/windows_feature_powershell.rb
since the data returned is already in json, `from_json` call is not required in the `parsed_feature_list` method. 
#12349
=> remove unnecessary from_json call in windows_feature_powershell

tasks/spellcheck.rb
Fixes the reference to the main branch for chef/chef_dictionary.
=> Fix reference to chef/chef_dictionary main branch

.github/workflows/kitchen.yml
This ensures that we cannot silently start failing to appbundle without
failing these tests.
There's a fairly bad bug here where the bundle install is failing due to
native gems (that apparently we don't actually need) and it doesn't seem
to matter for testing (all kinds of junk that kitchen-inspec brings in)
Once that is fixed, the bundle install should no longer be ignored, and
then the manual install of berkshelf can be removed.
=> Properly fail on windows tests

.github/CODEOWNERS, .github/labeler.yml, .github/workflows/labeler.yml
Make sure that things the docs team should review are auto labeled so it shows up on their zenhub board. This will create false positives, but that's better than missing stuff.
=> Setup auto issue labeler for docs

chef-utils/lib/chef-utils/dsl/virtualization.rb
Adds `vmware_desktop?` and `vmware_vsphere?` helpers. Depends on [Ohai PR #1720](https://github.com/chef/ohai/pull/1720) to work.
Minor flexibility update.
=> Add helpers to detect VMware desktop vs server platforms

knife/lib/chef/knife/bootstrap.rb, knife/spec/unit/knife/bootstrap_spec.rb
Signed-off-by: kasif <kadnan@progress.com>
Knife bootstrap was not working with winrm, when max wait was specified.
This PR fixes the problem.
#12281
=> fix knife bootstrap issue when max wait is specified ref#12281

kitchen-tests/kitchen.yml
Hopefully this gets us working opensuse tests again
=> Update the pid_one_command for opensuse tests

cspell.json, lib/chef/secret_fetcher/hashi_vault.rb, spec/unit/secret_fetcher/hashi_vault_spec.rb
Signed-off-by: Collin McNeese <cmcneese@chef.io>
Adds _approle_ support for `secret` helper `Chef::SecretFetcher::HashiVault` 
Supports the following approle auth types:
- Explicitly providing the `approle_id` and `approle_secret_id`.  This provides all the required information to connect to a Vault instance with an approle
- Providing the `approle_secret_id` along with an `approle_name`.  This allows for a known `secret_id` to be used and the associated `approle_id` will be fetched via lookup from the Vault instance.  A `token` may be supplied or omitted with this option depending on deployment requirements.
- Providing an `approle_name` (and optionally a `token`).  This type will use the `create_secret_id` method from Vault::Approle and dynamically generate an approle `secret_id`.  A …
=> Adds approle support for Chef::SecretFetcher::HashiVault

lib/chef/provider/package/yum/python_helper.rb
aarch64 is the one we really care about and is breaking our CI.
the rest of them can't hurt.
this was missed in #10823
=> Update list of possible RPM arches

spec/functional/resource/yum_package_spec.rb
Really shouldn't but it cleans up a file descriptor leak on
RHEL6 so that we can ship.
=> Bounce the yum helper a few more times during the run

lib/chef/secret_fetcher/azure_key_vault.rb
When trying to use this class outside of the full scope of the chef infra client this throws exceptions due to missing require statements.
Even if ya'll aren't desiring to use/support other contexts it is abusing best practices to not require what the class/file requires.
=> Add missing require statements

lib/chef/resource.rb
In the direct resource example, the intention is to show that you can subscribe to the resource using a reference to the resource, instead of a string. The subscribes line should therefore reference `bar`. This is similar to the multiple string vs direct resource examples that follow just below.
=> Fix typo in subscribes method documentation

Gemfile, kitchen-tests/cookbooks/end_to_end/recipes/_habitat_service.rb, knife/lib/chef/knife/core/gem_glob_loader.rb, knife/lib/chef/knife/core/subcommand_loader.rb, lib/chef/cookbook_version.rb, lib/chef/provider/ifconfig.rb, lib/chef/resource.rb, lib/chef/resource/habitat/habitat_sup.rb, lib/chef/resource/habitat/habitat_sup_windows.rb, lib/chef/resource/inspec_waiver_file_entry.rb, lib/chef/secret_fetcher/azure_key_vault.rb, spec/support/ruby_installer.rb
Do regex checks without creating objects for the results.
=> Resolve Performance/RegexpMatch warnings

lib/chef/secret_fetcher/azure_key_vault.rb
Use .count not .select and .length
=> Resolve Performance/Count warning

knife/lib/chef/knife/bootstrap.rb
Right now for terrible reasons knife bootstrap gets initialized during every knife command due to sadness in knife-cloud. That wouldn't be nearly as bad if we were a bit more lazy in the bootstrap plugin.
1. JSON compat is actually used in the options so it needs to be required outside deps method. This works right now because we're not lazy all over the place and this thing gets loaded in 20 places
2. Net::SSH doesn't even appear to be used here. This plugin is all train now so we shouldn't have to require that.
3. Erubis should only get called when we're rendering out the template
Before:
```
There were 642 requires
The total time spend requiring was: 1.167499999748543
```
After
```
There were 429 requires
The total time spend requiring was: 0.6953230001963675
```
Signed-off-by: Tim …
=> Reduce 213 requires from each knife call

lib/chef/chef_fs/file_system/chef_server/cookbook_file.rb, lib/chef/chef_fs/file_system/repository/base_file.rb, lib/chef/chef_fs/file_system/repository/file_system_entry.rb, lib/chef/cookbook_uploader.rb, lib/chef/util/dsc/configuration_generator.rb, spec/functional/resource/cookbook_file_spec.rb, spec/functional/resource/dsc_script_spec.rb, spec/functional/resource/template_spec.rb, spec/integration/client/client_spec.rb, spec/support/shared/functional/file_resource.rb, spec/support/shared/functional/http.rb, spec/unit/provider/user/solaris_spec.rb
This is a new RuboCop cop that moves things to file.read an file.binread vs. an open and then a read.
=> Simplify file reads

omnibus/config/software/more-ruby-cleanup.rb
new jmespath gem uses the VERSION file.
=> Fix ruby cleanup breaking builds

lib/chef/resource/chef_sleep.rb
Signed-off-by: Jose Hernandez <jhboricua@gmail.com>
Quick fix to example in chef-sleep resource documentation
The quotes are not placed correctly in the documentation example.
#12385
=> fix typo in chef-sleep resource documentation example block

lib/chef/provider/user/mac.rb
Don't fail with a NoMethodError error if home is not defined. We're seeing this failure in our specs right now.
=> user: handle nil home dirs on macOS

lib/chef/resource/lwrp_base.rb
We need to support the chef_client_updater cookbook running on Chef 12 with the same code as runs on Chef 17/18 so we need to make one hardcoded exception in the universe for specifically this cookbook.
=> Suppress deprecation warning for chef-client-updater cookbook

habitat/plan.sh
No idea why I had to do this last year for omnibus builds and
now this year for everything else.
=> Fix habitat builds by using `rake install:local`

chef-config/lib/chef-config/config.rb, chef-config/spec/unit/config_spec.rb
Running chef-apply we calculated this value 5 times. We also have several other resources that use this method which would again have to be calculated. Each of those calculations run the PathHelper.join which involves a whole series of terrible string manipulations. Just calculate this once and be done with it.
Duplicates PR #10562
=> Avoid calculating etc_chef_dir multiple times on startup

lib/chef/resource.rb, spec/unit/resource_spec.rb
When missing a closing ] in the resources passed to subscribes, it will be silently ignored whereas notifies checks the syntax and raises an error. To fix this we are validating the resources passed to subscribes and raising an exception when it is invalid.
- lib/chef/resource.rb
- spec/unit/resource_spec.rb
#8908
=> Validate resource spec passed to subscribes

kitchen-tests/cookbooks/end_to_end/recipes/_chef_gem.rb
This causes horrible issues.
We are installing knife in a TK virt and can't really build it and
install it as a test (hacking up appbundler to do this would largely
invalidate the test since we wouldn't be testing customer behavior)
and as such it needs to be installed from rubygems.  That means
installing knife-17, which pulls down chef-17 which currently has
a dep on diff-lcs 1.3.x which conflicts with 1.5.x which throws
the errors around the binstubs conflicting (which may or may not be
a rubygems bug, I investigated that a bit and couldn't determine
why that is happening since the 3rd line has the magic rubygems
comment).  We can't just use "--force" as an option since that'll
ignore deps and stuff as well which is precisely the kinds of things
that we're trying to catch.  So for now …
=> Disable knife gem install in kitchen tests

.github/workflows/kitchen.yml
Just delete the binstubs that already exist and let the gem install replace them.
This is likely caused by diff-lcs version thrashing and conflicts over htmldiff which may be rubygems bugs ultimately (don't have a good repro case though to cut a bug there, and I while there's relevantish bugs there nothing made any sense to me, and I looked at it long enough to figure out that our binstubs do have the magic 3rd line on them, so AFAIK that error should never be happening, yet it does...)
=> Workaround binstub conflicts with diff-lcs gem 

spec/functional/shell_spec.rb, spec/functional/version_spec.rb, spec/integration/client/client_spec.rb, spec/integration/client/exit_code_spec.rb, spec/integration/client/ipv6_spec.rb, spec/integration/compliance/compliance_spec.rb, spec/integration/recipes/accumulator_spec.rb, spec/integration/recipes/lwrp_inline_resources_spec.rb, spec/integration/recipes/lwrp_spec.rb, spec/integration/recipes/notifies_spec.rb, spec/integration/recipes/notifying_block_spec.rb, spec/integration/recipes/remote_directory.rb, spec/integration/recipes/unified_mode_spec.rb, spec/integration/recipes/use_partial_spec.rb, spec/integration/solo/solo_spec.rb
Currently when integration tests fail, they give no useful output other than to "check the stacktrace.out file" which is in a tempfile on the CI build server which we don't have easy access to and the tempdir probably gets wiped after the test anyway. So we will make use of --always-dump-stacktrace option which was introduced recently. 
Several of them also haven't been updated for the binary name change with cinc-client and need to use the ChefUtils::Dist::Infra::CLIENT constant instead of the literal string "chef-client".
Also "bundle exec chef-solo" and "bundle exec chef-shell" need to use ChefUtils::Dist::Solo::EXEC and ChefUtils::Dist::Infra::SHELL respectively.
#12580
=> Add --always-dump-stacktrace to integration tests that use chef-client

.github/workflows/kitchen.yml
We get good enough coverage from centos-6/7 and alma-8
=> Remove oraclelinux from kitchen testing

tasks/rspec.rb
Updated Rspec to add verbose logging  for the purposes of tracking down intermittent failures in Integration and Unit testing on Windows. When these happen we get weird, random output regarding Libyajl that don't make sense. 
(https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
=> Updated Rspec to add verbose logging 

knife/lib/chef/knife/user_create.rb, knife/spec/unit/knife/user_create_spec.rb
Fix PEM file generation when user created via knife. 
This issue arises because of ~~changes in infra API response~~ create_key is missing from body params. And not accessing the `private_key` in the correct way
- https://github.com/chef/chef-workstation/issues/2505
=> Fix PEM file generation when user is created

lib/chef/provider.rb, lib/chef/resource.rb
caller_location.first.absolute_path returns nil sometimes on ruby 3.1
switch to .path which is going to always be an absolute path anyway, but
which ruby 3.1 doesn't return nil for.
i have no idea why.  smells like a ruby language bug.
=> Ruby 3.1 fixes

lib/chef/resource/chef_client_launchd.rb
Currently the chef client launchd resource configures the services properly, but the periodic run only starts after a system restart. This change fixes that and makes sure that chef client service runs without a restart.
https://chefio.atlassian.net/browse/DESKTOP-25
=> update chef client launchd to run at load

.expeditor/scripts/bk_win_functional.ps1, .expeditor/scripts/bk_win_integration.ps1, .expeditor/verify.pipeline.yml
Update bk_win_integration.ps1 script to allow for different ruby versions
Update bk_win_functional.ps1 in verify pipeline. Remove some unnecessary things from the script and update the verify pipeline to show that the test is using ruby 2.7.
=> IPACK-136 Improve some verify pipeline windows tests

lib/chef/dsl/secret.rb, lib/chef/run_context.rb, spec/unit/dsl/secret_spec.rb, spec/unit/run_context_spec.rb
This gives users the ability to set a default secret service and secret service configuration
Initially I wrote no tests. I want to get in sync on the high level API before diving in to testing.
```ruby
value1 = secret(name: "test1", service: :aws_secrets_manager, config: { region: "us-west-1" })
value2 = secret(name: "test2", service: :aws_secrets_manager, config: { region: "us-west-1" })
value3 = secret(name: "test3", service: :aws_secrets_manager, config: { region: "us-west-1" })
```
```ruby
default_secret_service(:aws_secrets_manager)
default_secret_config(region: "us-west-1")
value1 = secret(name: "test1")
value2 = secret(name: "test2")
value3 = secret(name: "test3")
with_secret_service(:aws_secrets_manager) do
with_secret_config(region: "us-west-1") do
value1 = secret(name: "test1") …
```
=> Add support for default secret service and config

lib/chef/resource/plist.rb, spec/functional/resource/plist_spec.rb
Signed-off-by: Jacob Zaval <jazava@microsoft.com>
When creating a new plist, the `plist` resource passes an empty hash with the `to_plist` method (`{}.to_plist`) to the `content` property of `file` resource. However, the `file` resource interprets this first as a block, as demonstrated in #12678. This PR assigns the empty plist to a variable first, so it can be properly evaluated before being passed to `file`.
Also, during the addition of a functional spec test with a `Hash` for `value`, I discovered a bug with the "add" case for a new dictionary and updated accordingly (similar solution to the `Hash` "set" case).
#12678
=> avoid coercion to block for new plist file content, fix adding a new dictionary 

kitchen-tests/cookbooks/end_to_end/recipes/_chef_client_config.rb, kitchen-tests/test/integration/end-to-end/_chef_client_config.rb, lib/chef/resource/chef_client_config.rb, lib/chef/resource/support/client.erb, spec/unit/resource/chef_client_config_spec.rb
Adds a `rubygems_url` property to the `chef_client_config` resource to configure the same such property in `client.rb`
Fixes #12711
=> Add rubygems_url property to chef_client_config resource

chef-utils/lib/chef-utils/mash.rb, lib/chef/node/attribute.rb, lib/chef/node/mixin/deep_merge_cache.rb
=> Fix attribute performance issues in node.read (Chef-17)

lib/chef/resource/support/client.erb
This pull request is for two fixes for the chef_client_config resource to update the template to properly write out the values for the datacollector parameters. They were not being properly quoted previously.
#12713 - chef_client_config resource doesn't generate data_collector.url and data_collector.token properly in client.rb
=> Updates for the chef_client_config resource

.expeditor/adhoc-canary.omnibus.yml, .expeditor/release.omnibus.yml, omnibus/Gemfile.lock
Add Amazon Linux 2022 arm64, FreeBSD 13 amd64, Ubuntu 22.04 arm64 and amd64.
Update omnibus and omnibus-software so Windows builds use new omnibus Windows images and build logic.
=> Add platforms

.expeditor/adhoc-canary.omnibus.yml, .expeditor/release.omnibus.yml, omnibus/Gemfile.lock
Build on FreeBSD 12 and remove FreeBSD 11 since it is EOL.
Update omnibus and omnibus-software so Windows builds use new omnibus Windows images and build logic.
=> IPACK-126 Add platforms to chef-17

.expeditor/release.omnibus.yml, omnibus/Gemfile.lock
Build on FreeBSD 12 and remove FreeBSD 11 since it is EOL.
Update omnibus and omnibus-software so Windows builds use new omnibus Windows images and build logic.
=> IPACK-126 add platforms to chef-16

omnibus/omnibus-test.ps1
Use Throw instead of Exit to ensure the CI job fails when a command has
a non-zero exit code.
=> Fix omnibus-test.ps1

lib/chef/secret_fetcher/azure_key_vault.rb
Signed-off-by: sanga1794 <sausekar@msystechnologies.com>
There is a private method named as `object_id` due to which getting below warning:
```warning: redefining `object_id' may cause serious problems```
=> Renamed private method as conflicting to inbuilt method and getting warning

lib/chef/compliance/input_collection.rb, lib/chef/compliance/profile_collection.rb, lib/chef/compliance/waiver_collection.rb
adding exception to bypass nil class error in the compliance phase
When utilizing the Compliance phase, and more specifically when an Inspec profile exists within the cookbook structure, Chef Spec does not appear to be able to handle at least one of the new methods in Chef to load the Compliance Profiles.
Chef Spec returns undefined method 'compliance_profile_loaded' for nil:NilClass.
I have validated this behavior on several versions of Chef workstation including the latest we have installed which is 22.2.807
To Reproduce
Within the cookbook tree structure, create an Inspec profile complete with controls and inspec.yml and place it in /compliance/profiles.
Define any type of unit test in a spec.rb file within /spec/unit/recipes
Run chef exec rspec
Any test should fail referencing the …
=> Handling compliance phase error

lib/chef/resource/rhsm_register.rb
This ensures that the Chef Infra Client internal package cache gets flushed after registering with Red Hat Satellite and newer packages are available. I also went ahead and added the inverse situation as well which is unsubscribing and losing access to content that may have previously been cached by the Chef Infra Client.
- Closes https://github.com/chef/chef/issues/12829
- https://github.com/chef/chef/pull/11534
=> flush package cache after registering via rhsm_register

omnibus/omnibus-test.ps1
The last line of the script had the statement "Throw $exit". In reviewing recent Windows builds, it seems that this statement was firing no matter what causing false positive build failure errors. The last statement was updated to only throw in the event of a non-zero exit code.
=> updating throw statement to only execute on non-zero exit codes

lib/chef/cookbook/syntax_check.rb, spec/unit/cookbook/syntax_check_spec.rb
Signed-off-by: snehaldwivedi <sdwivedi@msystechnologies.com>
When uploading a file with a syntax error the error message was not specifying the file name where the issue exists. Fixed it by displaying the name of the file.
https://github.com/chef/chef/issues/9378
=> Knife upload: bad error message when a recipe has a syntax error

lib/chef/resource/rhsm_register.rb
Backport https://github.com/chef/chef/pull/12828 to chef-17
=> backport to 17: flush package cache after registering or unregistering with rhsm_register

cspell.json, lib/chef/client.rb, lib/chef/http/authenticator.rb, spec/unit/http/authenticator_spec.rb
This code is a completion of some previously started work on moving certificates to the Windows Certificate Store. The work in this PR solves 2 problems. The first is that if the chef-client is already running on a given node and the admin wants to move keys to the certstore, what do they do? They set the flag `migrate_key_to_keystore true` in the client.rb and then the code creates a pfx object, extracts the public key from it, sends that to the chef-server and then stores the pfx in the \\LocalMachine\My store. The second problem that this updates is certificate lifetimes. We put a 90 day lifespan on certificates to increase security. The code in this PR checks to see if the given keys are expiring and then creates a new pfx on the fly and …
=> Updated files to account for pem storage in the Certificate Store

.expeditor/adhoc-canary.omnibus.yml, .expeditor/release.omnibus.yml, omnibus/Gemfile.lock
Update omnibus/Gemfile.lock for compatibility with omnibus-toolchain 3.0.0
Add RHEL 9 to build matrix
=> Update omnibus/Gemfile.lock for compatibility with omnibus-toolchain 3.0.0

Gemfile.lock, omnibus/Gemfile.lock, omnibus_overrides.rb
Per https://buildkite.com/chef/chef-chef-main-omnibus-release/builds/1678#_
Updating ncurses gem to overcome freebsd build failures.
=> Updated ncurses and gems

lib/chef/dsl/secret.rb
As we have tested all the Secret Manager in recipe, we will remove the beta warning that shows up when using it.
=> Remove the beta feature warning which shows up when using Secret Manager

kitchen-tests/cookbooks/end_to_end/recipes/_chef_client_config.rb, kitchen-tests/test/integration/end-to-end/_chef_client_config.rb, lib/chef/resource/chef_client_config.rb, lib/chef/resource/support/client.erb, spec/unit/resource/chef_client_config_spec.rb
Signed-off-by: Joseph Larionov <jlarionov@webmd.net>
Original PR: #12724
Adds a `rubygems_url` property to the `chef_client_config` resource to configure the same such property in `client.rb`.
Fixes #12711
=> Backport to 17: Add rubygems_url property to chef_client_config resource

omnibus/Gemfile.lock
The multipart-post gem changed the way it ships the license out. License Scout was failing as a result. We updated and released License Scout. We're updating that new version dependency here.
=> Bumping license_scout version

spec/integration/client/client_spec.rb
Integration Tests are failing with certificate creation on versions of PowerShell < 5. The function "New-SelfSignedCertificate" uses different syntax on those versions. The previous code to create certificates was too specific and needed to be amended to capture any version of PowerShell < 5.
=> refactoring the version check

lib/chef/resource/cron/cron_d.rb, spec/unit/resource/cron_d_spec.rb
This commit restrict the `cron_d` job name property to the character set
according to the cron specification:
> Additionally, cron reads the files in /etc/cron.d [...] Files must
> conform to the same naming convention as used by run-parts(8): they
> must consist solely of upper- and lower-case letters, digits,
> underscores, and hyphens.
closes #12165
Signed-off-by: Mario Haustein <mario.haustein@hrz.tu-chemnitz.de>
The `cron_d` resource allows some special characters which aren't allowed.
This lets cron ignore the cron jobs silenty.
- #12165
=> Fix cron_d job name character set

knife/lib/chef/knife/core/ui.rb, knife/lib/chef/knife/edit.rb, knife/lib/chef/knife/user_edit.rb, lib/chef/resource/chef_client_scheduled_task.rb
Obvious fix.
Current documentation says "/etc/" for a Windows-only resource.
```ruby
chef_client_scheduled_task 'name' do
...
config_directory          String # default value: "/etc/chef"
...
end
```
=> Fix documentation for chef_client_scheduled_task

spec/integration/client/client_spec.rb
Correcting Cert creation for rspec tests
We create self-signed certificates in ./spec/integration/client/client_spec.rb. Previously that code was updated to account for older versions of Windows but it did not correctly account for PowerShell 5.1 builds which are radically different between various shipping versions. Build 22000, shipping in current versions, has the certificate fields needed to correctly create the certificates we need. Older builds do not. This update corrects for that.
=> Correcting Cert creation for rspec tests

spec/integration/client/client_spec.rb
The test verifies that code in authenticator.rb is correctly creating a password for retrieving certificates with. The test relies on a PowerShell snippet to check the registry for that password. That snippet relies on a built-in method that changed between versions of PowerShell. This update corrects for that.
=> Refactored tests for older Windows versions

kitchen-tests/cookbooks/end_to_end/recipes/linux.rb
Added condition to prevent installation of nscd on fedora in end_to_end kitchen tests as package has been removed from fedora 35 onward.
Kitchen tests had been failing on fedora with error 
`nscd` package has been removed from fedora 35. It was warned for deprecation in fedora 34.
Currently `systemd-resolved` is enabled by default for DNS caching in Fedora, and `sssd` is capable of caching the remaining named services that `nscd` handles.
Our kitchen instance is running on fedora 36, hence it throws `nscd` package not being available error.
More details can be found at https://fedoraproject.org/wiki/Changes/RemoveNSCD
- [] I have read the **CONTRIBUTING** document.
=> Fix fedora kitchen test failure

lib/chef/resource/windows_pagefile.rb, spec/functional/resource/windows_pagefile_spec.rb
Refactored code to be more readable and changed a test to correct for starting out with Auto-Managed being false by default
Windows Ad Hoc jobs were failing on a pagefile settings test. Windows nodes were randomly starting up with the pagefile "autmatically managed" set to True and False so the pagefile tests were failing. I updated some of the code to make it more readable, I updated one test to verify the state, and finally I added a method to set the pagefile state before the first test.
=> AdHoc Pipeline Windows PageFile Test errors

lib/chef/property.rb
This clarifies the use of `:required` in the property DSL.
=> update property DSL docs

lib/chef/run_context.rb
Providing a better explanation by changing a somewhat confusing error message related to missing dependencies, which, if misunderstood like I did, could cause a bit of confusion. 
May prevent a misunderstanding of the instructions the error message provides to remedy the missing dependency. 
N/A
Per CONTRIBUTING guidelines: I consider this a "Chef Obvious Fix." However I am including DCO because I forgot to name the commit appropriately as "obvious."
Signed-off-by: Armand <armandminassian1@gmail.com>
=> Wording change in error for missing recipe dependency ("Obvious Fix")

lib/chef/resource/windows_user_privilege.rb
Signed-off-by: Corey Hemminger <hemminger@hotmail.com>
Helps remove confusion on values for principal property as documented in the url added to the resources description on line 26.
#10420
=> add url for principal names

lib/chef/resource/sysctl.rb, spec/unit/resource/sysctl_spec.rb
If the sysctl file doesn't end with a newline, then Ubuntu's CIS audit won't correctly
detect the sysctl configuration. Also, it is UNIX best practice to include a newline at the
end of the last line of text files.
Obvious fix.
Signed-off-by: Thayne McCombs <thayne@lucid.co>
- [?] Breaking change (fix or feature that would cause existing functionality to change)
=> Add newline to end of sysctl files

.expeditor/release.omnibus.yml, Gemfile.lock, omnibus/config/projects/chef.rb
* Supersedes [PR 13158](https://github.com/chef/chef/pull/13158)
* ruby cleanup dependencies
* Disabling Win 8 (broken, won't fix) and Amazon 2022 (no builders available) builds.
See [PR 13165](https://github.com/chef/chef/pull/13165) for original changes.
=> Bundle with for 2.3.7 and cleanup with minimal gem bumps

.github/workflows/kitchen.yml, Gemfile.lock, omnibus/Gemfile.lock
Signed-off-by: tpowell-progress <104777878+tpowell-progress@users.noreply.github.com>
Resolve error with ruby cleanup and multiple bundler versions.
=> Move Gemfile.locks to 2.3.7 and disable .github kitchen install of 2.3.18

.expeditor/update_version.sh
We only want to bump the version of the chef related gems in Gemfile.lock
but the `bundle update --conservative` would frequently bump the version
of other gems that are direct dependencies.
=> Use sed to bump version of chef gems in Gemfile.lock

omnibus/Gemfile.lock
Omnibus update for windows 10 string was not handled in the version of omnibus included in `omnibus/Gemfile.lock`.
Updated the sha and version spec.
Example error:
```
C:/opscode/omnibus-toolchain/embedded/lib/ruby/gems/3.1.0/bundler/gems/omnibus-83d8428abde4/lib/omnibus/metadata.rb:223:in `truncate_platform_version': Unknown platform version `10' for windows! (Omnibus::UnknownPlatformVersion)
```
=> Update omnibus gem hash as well

CHEF_MVPS.md
During the Advisory Council meeting, there was discussion of community
recognition - and the fact that this used to exist came up. I went to go
dig up this to share it with Jeff and George. But in doing so, I noticed
there was both a markdown format error and that the HoF was out of date
(I swear I didn't do this to add myself, it just worked out that way).
HoF math:
```
[phil@rider (main) chef]$ egrep '\[Client|Chef' CHEF_MVPS.md | awk -F\| '{print $4}' | sed -e 's/, /\n/g' -e 's/^ //g' -e 's/ $//g' | sort | uniq -c | sort | tail -5
2 Xabier de Zuazo
3 Jeff Blaine
3 Matthew Kent
3 Phil Dibowitz
```
=> Cleanup MVPs file

.github/workflows/kitchen.yml, Dockerfile, Gemfile.lock
Remove chef17 move and git clone that were added as part of debugging ruby 3.1 build.
Update hash of rest-client.
`chef17` `mv` and `git clone` were causing trouble (resetting the branch to `main`)
INFC-267 
- [] I have run the pre-merge tests locally and they pass.
=> Remove the chef17 git clone step

Gemfile.lock, habitat/plan.ps1
During the upgrade to Ruby 3.1 for Chef 18, we noticed that we were getting failures in the verify pipeline related to installing and consuming the rest-client gem on Windows (Specifically, the Windows Plan fails as executed by .\.expeditor\scripts\verify-plan.ps1. That script ultimately calls \habitat\plan.ps1). This only happens when the gem is being call via habitat. In investigating this further, we discovered some odd behavior that we had not encountered before. The error looks like this:
```shell
chef-infra-client:  -- installing C:\hab\studios\bk01835b8d701e3fb37dc6\hab\pkgs\ci\chef-infra-client\18.0.147\20220920154415\vendor\bundler\gems\rest-client-badd0bea3c31
rake aborted!
Bundler::Dsl::DSLError:
[!] There was an error …
```
=> Windows Verify Plan fails during "Rake Install rest-client"

.expeditor/update_version.sh, knife/Gemfile.lock
To continue maintaining separate gemspecs for windows and non windows platforms for Chef, we have added Gemfile.lock for knife, as it consumes chef repo from path and not as a released gem. 
This script will make sure that Chef's version in Knife's Gemfile.lock is upto date after every version bumps.
=> Update Chef version in Gemfile.lock under knife

chef.gemspec
We have not been able to build ruby 3.1 on AIX at this time. Until we are able to do so, we are leaving chef-18 on Ruby 3.0 for that platform.
Replaces #13205 
=> Permit ruby 3.0 for AIX

lib/chef/provider/user.rb, lib/chef/provider/user/aix.rb, spec/unit/provider/user_spec.rb
The AIX platform does not support ruby-shadow, but we always attempt to load it. The load fails  on the AIX platform, which later causes our requirement assertion that `@shadow_lib_ok` be true to fail.
Instead we allow user resource providers to override `supports_ruby_shadow?` if they do not support it, so that we don't assert that it is required in those cases. We default the return value to `true` because most platforms are supported by this gem.
Replaces #13212
=> Allow user providers to declare no support for ruby-shadow

omnibus/Gemfile.lock
This change adds new system libraries for solaris to the omnibus health check whitelist.
=> Update to latest omnibus

.expeditor/release.omnibus.yml
Temporarily disabling platforms that are still under development for chef 18, so that we can release the chef-18 RC without blocking on them.
=> Disable platforms still under development

.expeditor/release.omnibus.yml, spec/functional/resource/group_spec.rb, spec/functional/resource/link_spec.rb
We have found on AIX 7.x, it can be a varying amount of time before
the system reflects that member(s) have been added to a group.  This
change increases the delay on AIX from 2 seconds to 3 after adding a
user to a group.
This ensures that the new group members are visible before we verify
that they are added correctly.
This change also removes the limitation that only applies this delay on AIX 7.2
since we have found it affects 7.3 as well. For consistency, it is now applied
on all AIX platform versions.
With these tests passing, it is now possible to re-enable the AIX
pipeline (which has also been done in this change).
=> On AIX, add delay to ensure members added to group are visible to tests

lib/chef/win32/handle.rb, spec/unit/platform/query_helpers_spec.rb
On Windows 2012, we are seeing frequent errors during the finalizer for
Win32::Handle, which invokes CloseHandle:
'The handle is invalid' (error code 6)
Debugging and testing has shown that every instance of this error is
caused by the handle 18446744073709551615 (which converts to "ffffffffffffffff").  We have also seen
that this matches the value passed into the constructor of Handle,
provided directly from GetCurrentHandle.
We were previously comparing this to the const `ffffffff` and skipping
the CloseHandle call on the assumption that `ffffffff == (HANDLE)-1`
based on the docs here: http://msdn.microsoft.com/en-us/library/windows/desktop/ms683179(v=vs.85).aspx
But given that we are directly seeing the GetCurrentHandle returning
"ffffffffffffffff", it seems HANDLE (a LPVOID) is 64 bit …
=> Do not raise if we can't close win resource handle

.expeditor/release.omnibus.yml
MP recently merged a change to account for problems with handles in server 2012. Now we need the actual server 2012 images to show up in the pipelines to verify this all works as expected.
=> updating builders to add server 2012 back in

lib/chef/provider/user/linux.rb, spec/functional/resource/user/linux_user_spec.rb, spec/unit/provider/user/linux_spec.rb
d4c3b8ad111ec7ff6b32ebccf9edd1b6a2f9e8e2 introduced a bug making `compare_user` on Linux systems return `%i{expire_date inactive}` instead of wether `@change_desc` is empty.
=> Fixes bug in compare_user on Linux systems

spec/functional/resource/user/linux_user_spec.rb, spec/unit/provider/user/linux_spec.rb
#13223 fixed a bug in `compare_user` and tests were added to prevent regression in the future. However, the tests were not tagged to run on Linux only, and therefore pipeline breakage occurred on non-Linux Unix-like platforms, including macOS.
[Pipeline breakage on linux user specs running on non-linux.](https://chefio.atlassian.net/browse/INFC-304)
=> Add linux_only: true to new linux user specs

lib/chef/resource/windows_user_privilege.rb
Better clarification on how to use :add and :set actions for users or principals. Principal option and users option are mutually exclusive when using :add or :set actions. Furthermore Principal does not take system users or groups but rather special identity groups found in this list. https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-special-identities-groups
=> better clarify user and principal in windows_user_privilege resource

.expeditor/verify.pipeline.yml
We are seeing similar failures in verify pipeline for OpenSUSE for chef16 as seen on main (e.g [build](https://buildkite.com/chef-oss/chef-chef-chef-16-verify/builds/1186#0183cc9d-b8a4-40c6-97ea-54bc17761c3e)
This change backports fix here https://github.com/chef/chef/pull/13237 but keeping the changes as per chef16 not main.
=> [Chef-16] Fix OpenSUSE failures in verify pipeline

omnibus/Gemfile.lock, spec/functional/shell_spec.rb, spec/unit/daemon_spec.rb
This change backports fixes here https://github.com/chef/chef/pull/13230/, adding as new commits instead of cherrypick as there are multiple commits
Solaris builds are failing with error
```
export/home/chef-ci/builds/chef/chef-chef-chef-16-omnibus-adhoc/omnibus/vendor/bundle/ruby/3.1.0/bundler/gems/omnibus-83d8428abde4/lib/omnibus/health_check.rb:108:in `block (2 levels) in run!': undefined method `include?' for nil:NilClass (NoMethodError)
bad_omnibus_libs, bad_omnibus_bins = bad_libs.keys.partition { |k| k.include? "embedded/lib" }
^^^^^^^^^`
```
This change updates the omnibus SHA in omnibus/Gemfile.lock so as to pull in those fixes from 
(https://github.com/chef/omnibus/pull/1083)
(https://github.com/chef/omnibus/pull/1082) …
=> [Chef-16] Fix solaris build and test failures in adhoc pipeline

kitchen-tests/cookbooks/end_to_end/recipes/linux.rb
Kitchen tests on linux systems fail with the following error:
```ruby
Error executing action `set` on resource 'resolver_config[/etc/resolv.conf]'
Errno::EBUSY
------------
template[/etc/resolv.conf] (end_to_end::linux line 99) had an error: Errno::EBUSY: Device or resource busy @ rb_file_s_rename - (/etc/.chef-resolv20221019-2104-c7pfwm.conf, /etc/resolv.conf)
```
This PR addresses that by backporting the fix from Chef-18
=> [Chef-17] Backporting a fix for the Linux testers that fixes a resolver_conf issue

.expeditor/scripts/bk_win_functional.ps1
the bk_win_functional.ps1 test script is failing when using Uru to switch Ruby to version 2.7x. Previously, we determined that you only need to specify the major and minor version numbers so this is now set to 27 instead of 271
=> [Chef-17] Backporting the fix from Chef-18 to get uru to work correctly

.expeditor/scripts/ensure-minimum-viable-hab.ps1, .github/workflows/kitchen.yml
In some instances, Habitat is not installed on Windows already and the version check in the verify plan fails. This resolves that by ensuring a version is either installed or updated as appropriate
=> [Chef-17] Correcting for Hab not being installed

.github/workflows/kitchen.yml
Reenable the "Upgrade Chef/Ohai Appbundler" build stage in kitchen tests for GitHub Actions, with a slight tweak for 3.1 directory structure.
[INFC-321 Investigate "Upgrade Chef/Ohai Appbundler removal" in kitchen tests](https://chefio.atlassian.net/browse/INFC-321)
=> INFC-321 Uncomment "Upgrade Chef/Ohai Appbundler" build stage in kitchen tests

lib/chef/dsl/rest_resource.rb, lib/chef/resource/_rest_resource.rb
Added missing require of `addressable/template` to parse REST URL templates.
Fixed returns from `rest_get` method
none
=> Fix missing require and small error in REST implementation

.expeditor/scripts/ensure-minimum-viable-hab.ps1, .expeditor/scripts/verify-plan.ps1
Windows plan throws below erros:
e.g build https://buildkite.com/chef-oss/chef-chef-chef-16-verify/builds/1191#0183d1ca-9779-4c20-bdad-b436cd528647
```
install-habitat : The term 'install-habitat' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\bk0183d1cab436cd528647\.expeditor\scripts\ensure-minimum-viable-hab.ps1:4 char:5
+     install-habitat --version 0.85.0.20190916
+     ~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (install-habitat:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
Hab version is older than 0.85 and could not …
```
=> [chef-16] Fix hab package failures under windows plan in verify pipeline

.expeditor/verify.pipeline.yml, kitchen-tests/Gemfile
chef/berkshelf was updated to fix a test failure in mock expectations, but the repo and builds were pointing to berkshelf/berkshelf.
=> Point berkshelf spec at chef/berkshelf

lib/chef/resource/windows_package.rb
Fixes to `windows_package` docs:
* 7zip examples used an incorrect checksum.
* Mercurial example used an old hostname in the `source` URL property that lead to a HTTPS certificate validation error.
=> Docs: Fix windows package docs examples

lib/chef/mixin/checksum.rb, lib/chef/provider/file.rb, lib/chef/provider/package/windows.rb, spec/unit/mixin/checksum_spec.rb
This fixes a bug where checksum validation fails when creating/updating files because the two checksums are in different letter cases. The existing checksum validation logic was using case sensitive equality checks.
Fixes #13208 
[remote_file resource checksum validation fails due to case sensitivity #13208](https://github.com/chef/chef/issues/13208)
=> Bugfix: checksum validation

habitat/plan.ps1
This uses `core/git` as a build dependency and ensures it will be on the path in the plan execution. I have run this through the buildkite habitat pipeline with success: https://buildkite.com/chef/chef-chef-main-habitat-build/builds/1924#01843952-1516-44b4-bb33-6590c4c55e07/142.
=> Fix windows habitat git

omnibus/omnibus-test.ps1
Was going through this and noticed that we double install this in a few places. 
To save build time, the idea here is not to install it if it already exists on your AMI / Docker image, ect..
Just created a powershell function to test if the choco application is installed, and if its not installed, install it.
=> adding choco function to test if it exists already

.buildkite/hooks/pre-command
This removes the call to run "free" in the buildkite environment as that binary isn't present. The call to "free" gives this error
```
C:/bk018435762483229395ad/.buildkite/hooks/pre-command: line 9: free: command not found
```
=> Remove "free" command from buildkite run as it's not supported

lib/chef/resource/chef_client_config.rb
fix bug in log_location directory creation when property is not a directory.
#13345
=> fix bug in chef_client_config resource

omnibus/omnibus-test.ps1
Updating the habitat-test.ps1 to properly check for Windows PowerShell (vs PowerShell 7) and set a TLS security value appropriately.
Windows PowerShell and PowerShell each handle TLS security for downloads slightly differently. For PS7, TLS is set for you but in Windows PowerShell you have to set a TLS version. The code was trying to download Chocolatey and dying on Windows PowerShell because TLS was not set. 
=> Adding TLS for Habitat-test.ps1 under Windows PowerShell

omnibus/omnibus.rb
Chef16 is now built using ruby31. By disabling the caching for s3 and git on omnibus we are able to build artificats successfully.
**When we can revert this change:**  Ruby version mentioned under [omnibus-toolchain](https://github.com/chef/omnibus-toolchain/blob/main/config/projects/omnibus-toolchain.rb#L57) is used while building chef-16 /17/18. 
Builds done post  [PR](https://github.com/chef/omnibus-toolchain/pull/210/files#diff-731e46d2ddb93c0e237870155dac5c311c63648bcda4e2c4f4bbae0570723853L45-R52) merge are using ruby 3.1.2 and prior to this PR merge, ruby 2.7.5 version was used.
So until we have separate build environments and corresponding configuration for doing that depending upon of version of Chef that is getting built, …
=> [Chef-16] Disable caching for s3 and git to successfully build aritifacts using ruby31

lib/chef/property.rb, spec/unit/property/validation_spec.rb
Signed-off-by: Steve Abatangle <sabat@area51.org>
(Lamont has seen this patch before. It was never merged because of some confusion in the conversation, about a year ago. The bug remains in the most current Infra release.)
The `get` and `set` methods in the Property class (for resource validation) check that a property is required if its value is nil. However, they don't check to see whether the property was required for the *specific action* the resource is using, so any use of `get` and `set` will throw an exception if used with a resource that doesn't use a required property, even when the property is not required for that action.
What I'm describing is easier to understand with an example: the current version of the chef-client cookbook has a recipe (cron.rb) with a resource that uses …
=>     Res validation should be aware of action prop reqs.

omnibus/Gemfile.lock, spec/integration/client/fips_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb
New version of omnibus-software should have disable-dynamicbase option on for the all DLLs involve with openssl for FIPS build as well as keying off of mingw64 "platform" argument to ./Configure script.
OpenSUSE RubyDistros build has a FIPS ruby but the docker image has a fingerprint error as well. Otherwise, having OpenSSL itself tell us that FIPS is enabled `OpenSSL::OPENSSLFIPS`
INFC-289
=> Update omnibus-software for FIPS issues

lib/chef/resource/rhsm_register.rb
Currently when using activation keys to register to RHSM/Satellite you cannot specify the release version. As activation keys do not necessarily specify the release version this causes failures when it tries to flush the cache.
https://github.com/chef/chef/issues/13351
- [] I have read the **CONTRIBUTING** document.
- [] I have run the pre-merge tests locally and they pass.
- [] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.
- [] All new and existing tests passed.
- [] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
=> Added option to set release version when using activation keys

.github/workflows/unit_specs.yml
in `generate_key!': pkeys are immutable on OpenSSL 3.0 (OpenSSL::PKey::PKeyError)
Two tests were broken in GitHub Actions on the upgrade from Ruby 3.1.2 to Ruby 3.1.3
rspec ./spec/unit/mixin/openssl_helper_spec.rb:94 # Chef::Mixin::OpenSSLHelper#dhparam_pem_valid? When the dhparam.pem file does exist, and does contain a vaild dhparam key returns true
[16363](https://github.com/chef/chef/actions/runs/3568070229/jobs/5996516177#step:6:16364)
rspec ./spec/unit/mixin/openssl_helper_spec.rb:320 # Chef::Mixin::OpenSSLHelper#gen_ec_priv_key When a proper curve is given Generates an ec key object
INFC-357
=> Lock ruby to 3.1.2 for GitHub Actions unit specs

lib/chef/provider/launchd.rb, lib/chef/resource/launchd.rb
Example of what it will look like in a plist
```
<key>AssociatedBundleIdentifiers</key>
<array>
<string>bundle.id.of.app.signed.by.same.team</string>
</array>
```
Apple docs: https://developer.apple.com/documentation/servicemanagement/updating_helper_executables_from_earlier_versions_of_macos
13287
- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have read the **CONTRIBUTING** document.
=> New launchd key for associating a bundle identifier with Login Items

.github/workflows/kitchen.yml, kitchen-tests/kitchen.yml
Kitchen tests on ubuntu2204 for chef16 fail when restarting `apparmor` fired by [ntp cookbook](https://github.com/sous-chefs/ntp/blob/main/recipes/apparmor.rb#L29)
```
Recipe: nscd::default
* service[nscd] action restart
- restart service service[nscd]
* template[/etc/cron.allow] action create
- create new file /etc/cron.allow
- update content in file /etc/cron.allow from none to 5bc5d0
(diff output suppressed by config)
- change mode from '' to '0600'
* template[/etc/cron.deny] action create
- create new file /etc/cron.deny
- update content in file /etc/cron.deny from none to b3dea1
(diff output suppressed by config)
- change mode from '' to '0600'
Running handlers:
[2022-11-28T06:43:38-08:00] ERROR: Running exception handlers …
```
=> [Chef-16] Fix kitchen test failure on ubuntu2204

kitchen-tests/cookbooks/end_to_end/recipes/_habitat_config.rb, kitchen-tests/cookbooks/end_to_end/recipes/_habitat_service.rb, kitchen-tests/cookbooks/end_to_end/recipes/_habitat_sup.rb, kitchen-tests/cookbooks/end_to_end/recipes/_habitat_user_toml.rb, kitchen-tests/cookbooks/end_to_end/recipes/_habitat_win_config.rb, kitchen-tests/cookbooks/end_to_end/recipes/_habitat_win_service.rb, kitchen-tests/cookbooks/end_to_end/recipes/_habitat_win_sup.rb, kitchen-tests/cookbooks/end_to_end/recipes/_habitat_win_user_toml.rb
This changes "hab sup status" calls to "hab svc status" calls to avoid this deprecation notice :
> * ruby_block[wait-for-sup-default-startup] action runØ 'hab sup status' as an alias for 'hab svc status' is deprecated. Please update your automation and processes accordingly.
=> Update deprecated "hab sup status" call (do not merge until hab / test pipeline is green again)

.expeditor/config.yml
Nightly scheduler needs to be in that branch, so the block for chef16/17 is really not doing anything.
We are moving it to corresponding chef16/17 branch.
=> Remove redundant code for chef16/17 nightlies from main branch

.expeditor/config.yml
Run a nightly build for chef-16 every Tuesday and Thursday.
=> [Chef-16] Add nightly adhoc builds for chef-16

lib/chef/resource/macos_userdefaults.rb
Signed-off-by: Jared Weyer <v-jaredweyer@microsoft.com>
Switch from Boolean to String type as value for the `deprecated` property option.
#13326
=> macos_userdefaults: Use string for property deprecated message

.expeditor/habitat-test.pipeline.yml, .expeditor/scripts/habitat-test.ps1
The habitat-test.yml file was calling PowerShell command directly. This is hugely problematic since things like the $env variable weren't respected and that resulted in errors;  for example calling `$env:path` would result in an error similar to `:path is not recognized` notice that the `$env` variable was chopped. In total this resulted in improper and incomplete execution. This update fixes that by moving the offending code to a distinct .ps1 file and calling on that; which does work.
=> Correcting the habitat pipeline issue for Windows

.expeditor/config.yml
I'm trying to see if that addition of nightly block caused version bumps to stop https://github.com/chef/chef/commits/chef-16
=> [Chef-16]Remove nightly for chef16 which may be has stopped version bumps

.github/workflows/kitchen.yml, .github/workflows/unit_specs.yml
Github actions has deprecated macos10.15 and is going to completely remove it on Dec22, so replace it with macos11, for which we have been getting warning in builds.
Refer https://github.com/actions/runner-images/issues/5583
=> [Chef-16] Replace deprecated macos-10.15 instances with macos-11

.expeditor/update_version.sh
Version bumps on PR merge are not working from last few days for chef16.
https://github.com/chef/chef/commits/chef-16
My guess is may be `bundle update` in update_version.sh causing something to break (?)
So trying to backport https://github.com/chef/chef/pull/13005, which something we should do anyways to avoid bumping gems instead of just VERSION
=> [Chef-16] fix version bumps

.expeditor/config.yml
The version bumps are not getting triggered for chef16. So I was trying to bring back config.yml to stage when it last triggered and hence removed nightly builds. But that hasn't fixed the bumping. So adding it back
=> [Chef-16]Add back nightly adhoc builds for chef16

omnibus/omnibus-test.ps1
Omnibus-test.ps1 does a generic ```Throw $exit``` on the last line of the script. This will ALWAYS cause the script to halt and exit improperly. It needs to be wrapped in an if/else which we have added here.
=> Tweaking omnibus-test to fail properly on Windows

lib/chef/win32/version.rb
In the previous PR I neglected to properly fence the windows 10 build numbers so Windows 11 tests were being weird. Now corrected.
=> Versions were overlapping with Windows 10. This corrects

lib/chef/provider/yum_repository.rb, lib/chef/resource/yum_repository.rb, spec/unit/resource/yum_repository_spec.rb
adds a `makecache_fast` property to the `yum_repository` resource/provider, to enable downloading only the minimum require metadata when refreshing the cache
in recent RHEL releases (and possibly other related distros like CentOS etc) additional multi-Gb metadata is downloaded by the standard `yum makecache` command, which is fairly wasteful of both disk space and bandwidth, for example:
```
total 8.9G
-rw-rw-r-- 1 root root 629M Aug 23  2021 filelists.xml
-rw-r--r-- 1 root root 330M May 24 04:30 filelists.xml.sqlite
-rw-rw-r-- 1 root root 3.6G Aug 23  2021 other.xml
-rw-r--r-- 1 root root 3.7G May 24 04:32 other.xml.sqlite
-rw-r--r-- 1 root root 374M Aug 23  2021 primary.xml
-rw-r--r-- 1 root root 454M May 23 05:01 primary.xml.sqlite
-rw-r--r-- 1 root root  23M Aug 23  2021 …
```
=> Adds 'makecache_fast' property to `yum_repository` minimise cached repodata

.expeditor/scripts/zypper_prep.sh, .expeditor/verify.pipeline.yml, .github/workflows/kitchen.yml
To overcome some issues with expired zypper repositories borking builds and tests, we created a chefzypper-repo (in code) that points to a working zypper mirror on the interwebs and we put that as a step in the verify-pipeline.yml file.
=> CHEF-17 - Rewriting the zypper code to run only on openSUSE 15

.expeditor/habitat-test.pipeline.yml, .expeditor/scripts/ensure-minimum-viable-hab.ps1, .expeditor/scripts/habitat-test.ps1
* Refactor tests into `habitat-test.ps1`, similar to `main`, to prevent missing `hab` issue.
* Pass `$EXPEDITOR_PKG_IDENTS_CHEFINFRACLIENTX86_64WINDOWS` to `habitat-test.ps1`
* Add error handling for `habitat-test.ps1`
INFC-397 - Fix habitat-test pipeline for chef 16
=> Fix Chef 16 Habitat Test pipeline

lib/chef/resource/bash.rb
Let's show an example of doubled escape characters.
The chef-client bash interpreter gets one, and find gets one.
Signed-off-by: Sean Horn <sean_horn@opscode.com>
=> Example of bash resource doubled escape characters

.buildkite/build-test-omnibus.sh, .buildkite/verify.pipeline.sh, .expeditor/config.yml, omnibus/config/projects/chef.rb, spec/spec_helper.rb
Signed-off-by: Evan Ahlberg <evanahlberg@gmail.com>
- Omnibus release is currently failing because chef-foundation isn't installed on all platforms.  This reverts the changes made to Omnibus to remove chef-foundation.
- Fix Integration tests related to fips and Windows
- Rename verify* pipelines because they are running on every PR
- Increase timeout to 120 mins on Windows Omnibus builds
=> revert chef-foundation changes in chef omnibus config

.github/workflows/kitchen.yml
Oracle Linux 7: INFC-384 and INFC-385
Move Oracle Linux 7 and Amazon Linux 2 kitchen tests to Ubuntu 20.04 host
=> Fix kitchen tests for Amazon Linux 2 and

.github/workflows/kitchen.yml
Break out Amazon Linux to run on Ubuntu 20.04 due to systemctl issues on 22.04
```
* timezone[America/Los_Angeles] action set
2           
3           ================================================================================
4           Error executing action `set` on resource 'timezone[America/Los_Angeles]'
5           ================================================================================
6           
7           RuntimeError
8           ------------
9           There was an error running the timedatectl command
10           
11           Resource Declaration:
12           ---------------------
13           # In /opt/kitchen/cache/cookbooks/end_to_end/recipes/linux.rb
14           
15            26: timezone …
```
=> Run Amazon Linux 2 kitchen tests on ubuntu-20.04

Gemfile.lock, omnibus/Gemfile.lock
Just bumping gem versions to get the new release of license_scout pulled in.
=> Bumping gems to pull in a valid license_scout version

lib/chef/application/base.rb
Running Chef and fetching a cookbook bundle from S3 via `--recipe-url` crashes if EC2 instance profiles are used, instead of local configuration.
#13524
=> Fix for missing S3 region if run with EC2 instance profile

.buildkite/hooks/pre-command, omnibus/omnibus-test.sh
Signed-off-by: Evan Ahlberg <evanahlberg@gmail.com>
Make the pre-command run on the new validate adhoc/release pipelines.
Revert change to omnibus-test.sh to fix failing centos 6 test changed in this PR:
https://github.com/chef/chef/pull/13489
=> fix adhoc pipelines and centos 6 omnibus test

.expeditor/scripts/omnibus_chef_build.ps1
Omnibus Chef Build silently fails if intermediate bundler steps fail. Throw an exception instead if `$?` is non-zero
=> Force errors after bundler in omnibus_chef_build

cspell.json, tasks/spellcheck.rb
`cspell` and `cspell-action` now support fetching remote dictionaries.
In order to spell check the repository, the shared [chef_dictionary](https://github.com/chef/chef_dictionary) has to be downloaded. This change will have `cspell` download the dictionary instead.
Note: I am adding Chef to cspell integration tests to ensure that changes to cspell don't break spell checking the Chef repository when I hit a error because `chef_dictionary.txt` was missing.
Signed-off-by: Jason Dent <jason@steetsidesoftware.nl>
=> chore: Use the `chef_dictionary` directly.

.github/workflows/unit_specs.yml, spec/unit/provider/package/rubygems_spec.rb
When the API server doesn't have a response, we expect nil, not a Ruby version. This was already fixed on 18, I'm just backporting.
Also we only run uint tests on mac, so don't call them "mac" - just like 18.
=> Fix rubygem tests for 17

.expeditor/scripts/prep_and_run_tests.ps1, chef-config/lib/chef-config/config.rb, lib/chef/client.rb, lib/chef/http/authenticator.rb, spec/integration/client/client_spec.rb, spec/unit/client_spec.rb, spec/unit/http/authenticator_spec.rb
Signed-off-by: John McCrae [john.mccrae@progress.com](mailto:john.mccrae@progress.com)
Description
Reference Bug - https://chefio.atlassian.net/browse/INFC-407
Reference Bug - https://github.com/chef/chef/issues/13402#issuecomment-1401633050
Updated - 2/5/2023 - This PR takes over from ~#13539
We moved to allowing private keys to be stored in a secure manner as part of a "no certs on disk" initiative. So client.pem gets stored somewhere safely.
That initially meant for windows users that we would store the private key as part of a pfx object into a certificate store. Then we would extract the private key and use that as the client secret to connect to Chef Server with. But as part of that process, Windows requires you to use a password to export the private key with. That meant …
=> Correcting cert retrieval issues for multiple user scenarios

.github/workflows/func_spec.yml, lib/chef/resource/macos_userdefaults.rb, spec/functional/resource/macos_userdefaults_spec.rb, spec/unit/resource/macos_user_defaults_spec.rb
`user` property was not being used when `host` isn't passed. This is because how the native corefoundation APIs work where we can either pass both to `CFPreferencesSetValue` or pass none to `CFPreferencesSetAppValue`. This PR sets default values for user and host as current user and any host. 
https://github.com/chef/customer-bugs/issues/657
=> set default values for user and host on userdefaults

.buildkite-platform.json
While the chef gem dependency is updated via https://github.com/chef/chef/pull/13617, chef-foundation's reference needed to be updated.
=> Update chef-foundation for proxifier2 

.buildkite/build-test-omnibus.sh, .expeditor/release.omnibus.yml
Temporarily build 18.2 without AIX and without Windows 10/11 testers
- [X ] All new and existing tests passed.
- [X ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
=> Temporarily build 18.2 without AIX and without Windows 10/11 testers

post-bundle-install.rb
Kitchen tests on windows fail when installing gems with error:
```
1 gem installed
Successfully built RubyGem
Name: rest-client
Version: 2.1.0
File: rest-client-2.1.0.gem
Successfully installed rest-client-2.1.0
1 gem installed
WARNING:  licenses is empty, but is recommended.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
WARNING:  See https://guides.rubygems.org/specification-reference/ for help
Successfully built RubyGem
Name: proxifier
Version: 1.0.3
File: proxifier-1.0.3.gem
ERROR:  Error installing proxifier-1.0.3.gem:
"pirb" from proxifier conflicts with installed executable from proxifier2
post-bundle-install.rb:27:in `block (2 levels) in <main>': gem install failed (RuntimeError)
from post-bundle-install.rb:25:in `chdir'
from …
```
=> FIx kitchen test failures in windows boxes due to dependency issue in proxifier

lib/chef/http/authenticator.rb
Small change to the ternary operator so that it returns the machine store and not an object named 'store' with the correct store label assigned to it.
=> Updating cert code to adjust user vs localmachine keys

lib/chef/provider/remote_file/http.rb, spec/unit/provider/remote_file/http_spec.rb
This PR comes to us from https://github.com/chef/chef/issues/13446 which describes the problem of a mis-spelled property returning a nil for a date value. The fix is to correct the spelling for the object which we are doing here.
=> Correcting a typo in the resource

lib/chef/win32/handle.rb, lib/chef/win32/security.rb
Windows runs of Chef get intermittent `ArgumentError`s for "Invalid Memory Object". This is due to an attempt to compare a legitimate Windows `HANDLE` retrieved from `GetCurrentProcess` with an `FFI::Pointer`. The "Invalid Memory Object" error itself comes from trying to compare a memory object (`FFI::Pointer` with the return value from `GetCurrentProcess()`, a `HANDLE` from Windows)
[Windows data types](https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types)
These errors do not result in breakage because of their happening in a finalizer, but 
```
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.9-x64-mingw-ucrt/lib/chef/win32/handle.rb:45:in `==': Invalid Memory object (ArgumentError)
from C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.9-x64-mi …
```
=> Avoid Invalid Memory Object error

lib/chef/provider/package/zypper.rb, spec/unit/provider/package/zypper_spec.rb
Installing the `apache2-mod_wsgi-python3` package is not idempotent due to the fact that zypper will also return the `apache2-mod_wsgi` package. The `resolve_available_version` method, incorrectly assumes this will only return one item, but in this case it returns four items and will pick the first package listed.
To work around this, we should verify that the package name listed in the output matches what we are expecting to install.
=> zypper_package: Fix idempotency issue

Gemfile
The previous version option was pulling in an incompatible version of cheffish.
=> [Chef-17] 3 of X - Updating Cheffish version

.expeditor/adhoc-canary.omnibus.yml, .expeditor/release.omnibus.yml
We no longer build for 32-bit processors. This PR removes support for that from the adhoc and release pipelines.
=> [Chef-17] 2 of X - Removing i386 support

spec/functional/resource/windows_font_spec.rb
The Windows font spec tests hang on Chef-16 and Chef-17. We essentially comment them out here to allow testing to complete.
=> [Chef-17] 11 of X - Updating windows_font_spec

omnibus/Gemfile.lock, omnibus/config/projects/chef.rb
Signed-off-by: poorndm@progress.com
The size of the installer on platforms has doubled after moving to chef-foundation.
Fix Includes cleanup of the bundler caches. This will remove ohai,rest-client,ruby-proxifier,and ruby-shadow caches. On cleaning the cache and bundler folder reduces the overall package size.
=> Add ruby-cleanup to clear the bundler/gems and cache folder

lib/chef/resource/launchd.rb
Man page for launchd specifies ProgramArguments should be an array of strings 
```
ProgramArguments <array of strings>
This key maps to the second argument of [execvp(3)](https://www.manpagez.com/man/3/execvp/).  This key is required
in the absence of the Program key. Please note: many people are confused
by this key. Please read [execvp(3)](https://www.manpagez.com/man/3/execvp/) very carefully! 
```
Recently my org discovered launchd behaves oddly (kernel panics)  if an integer value is passed to program_arguments. (We have a open case with Apple as well)  To address this,  we've added this patch to our fleet and looking to fix the issue upstream.  
- [ X] Bug fix (non-breaking change which fixes an issue)
- [ X] I have read the **CONTRIBUTING** document.
- [ X] All commits have been …
=> [launchd] Force string values for program_arguments property

.github/workflows/kitchen.yml, omnibus/config/projects/chef.rb
Updating the cert SHA for the builders in the adhoc pipeline. Also removed the caching flag that was suppressing the kitchen-tests from running.
=> [chef-17] 14 of X - Correcting the build cert SHA

omnibus/omnibus-test.ps1
omnibus-test.ps1 is throwing exit errors even when the tests all pass. This corrects that.
=> [chef-17] 17 of X - Correcting Omnibus test error handling

cspell.json, kitchen-tests/cookbooks/end_to_end/recipes/_chef_client_trusted_certificate.rb
This is a Backport from Chef-16 - https://github.com/chef/chef/pull/13714 - We are constantly running into the issue of updating the certs from the badssl.com website. We use that cert for testing when we "trust" that cert that we can still connect to the site it represents. The part we're testing is not the cert but that the trust mechanisms are working correctly. This code automates the process of retrieving the certificate and trusting it so we don't have to keep manually adding a new certificate blob to our files every 45 days.
=> [chef-17] 18 of X - Refactoring the badssl.com code

knife/lib/chef/knife/core/generic_presenter.rb, knife/spec/integration/cookbook_bulk_delete_spec.rb, knife/spec/integration/cookbook_list_spec.rb, knife/spec/integration/cookbook_show_spec.rb, knife/spec/unit/knife/cookbook_list_spec.rb, knife/spec/unit/knife/core/ui_spec.rb
This PR turns the output from the following:
```json
$ knife cookbook list -a -F json
[
"7-zip                       1.0.2",
"api_docs                    0.1.0",
"apt                         1.1.1",
"ark                         4.0.0  3.1.1  0.9.0  0.3.0",
"audit-cis                   0.4.0",
"authenticator               0.1.5  0.1.4",
"aws-static-ip-ha            0.1.0",
"aws-tools                   0.0.5"
]
```
to this
```json
$ knife cookbook list -a -F json
{
"7-zip": [
"1.0.2"
],
"api_docs": [
"0.1.0"
],
"apt": [
"1.1.1"
],
"ark": [
"4.0.0",
"3.1.1",
"0.9.0",
"0.3.0"
],
"audit-cis": [
"0.4.0"
],
"authenticator": [
"0.1.5",
"0.1.4"
],
"aws-static-ip-ha": [
"0.1.0"
],
"aws-tools": [
"0.0.5"
]
}
```
This has a potential of breaking peoples script if they adjusted to the broken format, …
=> Fix output of cookbook list/show

kitchen-tests/cookbooks/end_to_end/recipes/_chef_client_trusted_certificate.rb
We switched to using a code block to update the certs we test with. It was mostly working but failed on Windows, Centos and Linux 2004 (Amazon and OracleLinux) with errors saying it could not verify the certificate against the website. The main culprit was that we were not providing enough specificity in the first shellOut. We have corrected that here
=> [chef-17] 19 of X - Refactoring the badssl.com code

cspell.json, lib/chef/resource/apt_repository.rb, spec/unit/provider/apt_repository_spec.rb, spec/unit/resource/apt_repository_spec.rb
This allows specifying additional options to apt repositories, in addition to `trusted` and `arch`.
By using an array of strings we also allow using multivalue operators like -= and +=
Fixes: #13727
=> feat(apt_repository): Allow specifying arbitrary options

spec/functional/resource/windows_certificate_spec.rb
We had been using an Azure resource group to host the test.cer to download from. That proved to be a maintenance issue. Here, we backport a better approach from Chef-18 where we stub in a cert to simulate the download with.
=> [Chef-17] 21 of X - Updating Windows Functional Spec

spec/functional/resource/windows_certificate_spec.rb
Original test used an Azure resource to serve a test certificate, but it was accidentally deleted. Makes more sense for an otherwise static cert to just be served by a web mock
=> Stub test cert body to fix tests

omnibus/Gemfile.lock
This is the second PR to pull in the updated omnibus-software version that has a fix for Libxslt failures on Solaris2-5.11 images. That failure occurred because a new version of that library was pulled into the build and was not patched correctly. Now updated.
=> [Chef-17] 22 of X - Updating Libxslt, but surgically

lib/chef/win32/version.rb
Previously I updated the Win32 versions in lib/chef/win32/versions.rb to include Windows 11 but missed this qualifier that excludes Windows 10. Adding it here.
=> [Chef-17] 23 of X - Updating the windows versions

lib/chef/resource/windows_certificate.rb
```
C:/projects/chef/lib/chef/resource/windows_certificate.rb:443:in `exists?': warning: File.exists? is deprecated; use File.exist? instead (StructuredWarnings::BuiltInWarning)
```
Note: we define `.exist?` methods, so need to research and confirm that we aren't invoking those still. Ultimately, we need to deal with the deprecation, but it could get messy.
=> File exists? -> exist? deprecation

lib/chef/mixin/checksum.rb, lib/chef/provider/file.rb, lib/chef/provider/package/windows.rb, spec/unit/mixin/checksum_spec.rb
Original PR: https://github.com/chef/chef/pull/13210.
This fixes a bug where checksum validation fails when creating/updating files because the two checksums are in different letter cases. The existing checksum validation logic was using case sensitive equality checks.
=> [chef-17] 25 of X - Backport Checksum Validation

spec/unit/client_spec.rb
Tests are failing on all Linux flavors but pass on Windows. Tweaking the second test to match the first so the Time.now value is consistent.
=> [chef-17] 27 of X - Updating EOL Support, Again

cspell.json, lib/chef/provider/mount/mount.rb
efivarfs is a non-existent device that can be mounted using mount command and/or fstab.
The following fails at `:mount` because of this. This PR adds that as it is ok for it to not exist.
```
mount "/sys/firmware/efi/efivars" do
device "efivarfs"
fstype "efivarfs"
options "nosuid,noexec,nodev"
pass 0
action [:enable, :mount]
end
```
=> Add efivarfs to list of non-existent mount devices

knife/lib/chef/knife/bootstrap.rb, knife/spec/unit/knife/bootstrap_spec.rb
`sudo_password` is set to nil while making a ssh connection on knife bootstrap execution which leads to sudo_missing_terminal error in the latest versions of EL8.
We are setting this sudo_password with the password given when its prompted in terminal and than make a call to train gem for ssh connection which makes a successful Knife bootstrap execution without exposing their admin password in shell
fixed:  #13271
=> Setting the sudo_password to fix the sudo_missing_terminal error for latest versions of EL8

lib/chef/monkey_patches/net-http.rb
Something with Windows 2012r2 loading makes `Resolv` interpreted as in the namespace of `Net::HTTP`:
```
--
  | #   uninitialized constant Net::HTTP::Resolv
  | #
  | #             when Resolv::IPv4::Regex, Resolv::IPv6::Regex
```
=> Attempt to explicitly include Resolv

.expeditor/scripts/bk_win_functional.ps1
Current windows images are pulling in an incompatible version of chocolatey. This update ensures we are using a suitable version. This update should be considered a temporary one and we should update all the chocolatey tests to use the correct syntax for "choco list" introduced in version 2.0 of choco May 2023
=> Ensuring a version of choco < 2.0 is installed

.github/workflows/kitchen.yml, lib/chef/mixin/homebrew_user.rb
PR https://github.com/chef/chef/pull/13669 refactored some code and private method `homebrew_bin_path`  was added, which was being called in other resource files after requiring the file.
Kitchen tests on macos have below failures:
```
* homebrew_tap[homebrew/cask] action tap (up to date)
Error executing action `install` on resource 'homebrew_cask[do-not-disturb]'
NoMethodError
-------------
undefined method `homebrew_bin_path' for #<#<Class:0x000000010fce5148>:0x00000001112ef290 @new_resource=<homebrew_cask[do-not-disturb] @name: "do-not-disturb" @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :install, …
```
=> Make action homebrew_bin_path public which is used in other hombrew resources

lib/chef/cookbook/synchronizer.rb
The existing implementation of the remove_deleted_files method is inefficient on large numbers of cached files.
As an example, assume you have 100 active cookbooks with 25 recipes each. In the old code, this meant:
- [`cookbook_segment`](https://github.com/dafyddcrosby/chef/blob/main/lib/chef/cookbook/synchronizer.rb#L115) called 2500 times (which isn't cheap, see [files_for](https://github.com/dafyddcrosby/chef/blob/main/lib/chef/cookbook_manifest.rb#L173))
- `manifest_segment.select` bit means 2500 array creations, with 25 manifest_record comparisons for every file (62,500 total)
The proposed new version:
- `cookbook_segment` called 100 times
- `manifest_record_paths` has 100 array creations
- `to_be_removed` has 100 arrays created, 100 array comparisons
=> Optimize Chef::CookbookSynchronizer#remove_deleted_files

lib/chef/provider/yum_repository.rb
When running the yum_repository.rb, we can face the current issue: FATAL: TypeError: yum_repository[xxx] (xxx) had an error: TypeError: no implicit conversion of false into String There is probably a precedence issue which can be easily solved by parenthesis addition
https://github.com/chef/chef/issues/13829
=> Prevent TypeError to be raised in condition evaluation

lib/chef/resource/windows_security_policy.rb
The windows_security_policy resource uses the Windows command line tool `secedit` to modify configuration. This command line includes the path to a temporary file stored in a user-specific temporary directory. If the username of the user running chef-client includes a space, then the command line is built without quotes around the path which can cause `secedit` to fail.
fixes #13791
=> Adding double-quotes around path for Windows 'secedit' command line

chef-config/spec/unit/config_spec.rb, lib/chef/client.rb, lib/chef/cookbook_version.rb, lib/chef/http/ssl_policies.rb, lib/chef/provider/launchd.rb, lib/chef/provider/mount/linux.rb, lib/chef/provider/mount/mount.rb, spec/functional/resource/execute_spec.rb, spec/unit/client_spec.rb, spec/unit/provider/launchd_spec.rb, spec/unit/provider/mount/aix_spec.rb, spec/unit/provider/mount/linux_spec.rb, spec/unit/provider/mount/mount_spec.rb, spec/unit/provider/package/rpm_spec.rb
This removes all uses of deprecated `::File.exists?` so that when Chef adopts Ruby 3.2 there won't be problems. This is also helpful for folks who happen to use Ruby 3.2 when unit testing Chef outside of Chef Workstation.
=> update ::File.exists? to ::File.exist?

lib/chef/resource.rb, spec/unit/resource_spec.rb
Small change to support recursive resource partials in a cookbook. 
The current implementation crashes on chaining two `use` keywords inside a cookbook with ` FATAL: Errno::ENOENT: No such file or directory @ rb_sysopen - /_base_resource.rb`.
Chef 16's resource partials provide a way to create reusable code for resources by using composition, not inheritance. As a result you can overlay different logical elements to compose a completely new resource from.
For example, you could write a base partial to support an entirely new class of remote system interaction and then `use` it from multiple other resources to distinguish base functionality vs specific resource functionality.
This provides a clean, DSL-driven way to create e.g. REST resources but is applicable to all non-traditional …
=> Add support for recursive, in-cookbook resource partials

lib/chef/node/mixin/state_tracking.rb
The prior line shouldn't return nil, and `send_reset_cache` can get called a lot.
=> StateTracking#send_reset_cache - Remove redundant nil check

.expeditor/scripts/omnibus_chef_build.ps1, .github/workflows/kitchen.yml, Gemfile.lock, omnibus/Gemfile.lock
`libyajl2` and `ffi-yajl` `2.4` have already been installed in the stable `omnibus` image, and an attempt to `bundle install` a different `ffi-yajl` version results in an inability to locate `libyajldll.a` due to it being an artifact that was previously cleaned up, and no attempt is made to recreate it since `libyajl2` already exists.
=> ffi-yajl 2.6 bump with patch to omnibus build to uninstall libyajl2 gem

.github/workflows/kitchen.yml
Similar to #13847 but actually *before* the `bundle install` in the kitchen test phase instead
=> uninstall libyajl2 to avoid kitchen-tests base image conflict (Chef 17's Version)

spec/functional/resource/yum_package_spec.rb
@sean-simmons-progress and I looked at an EL6 instant and it appears that the repo that is the default for EL6 is no more.
I suspect there is an extended LTS repo that requires authentication or other arrangement. EL6 still builds and is tested, but yum package tests are skipped for EL6 specifically. They still get validated for other yum package using environments, including EL7 and 8.
=> Add not_rhel6 to EL6 yum resource tests to disable

lib/chef/node/attribute_collections.rb, spec/unit/node/vivid_mash_spec.rb
I've been doing some investigation into DeepMergeCache invalidation, and one result that was surprising was that doing something like the following triggers a full DeepMergeCache invalidation:
```
node.default['foo']['bar'] = [1, 2]
node.default['foo']['bar'] << 3
```
That means that any cached values for `node['unrelated']` would be blown away by that concatenation to 'foo'.
This is because [mutating methods in AttrArray aren't provided with `__path__`](https://github.com/chef/chef/blob/bed5613cf8f9b4f90c7b10c29196fa2e0150cfef/lib/chef/node/attribute_collections.rb#L34-L45).
On the face of it this might seem a minor problem, but this can rack up a lot of unnecessary full cache resets. In something like the [Facebook API model for Chef …
=> AttrArray#<<: Use __path__ when invalidating cache

.expeditor/scripts/omnibus_chef_build.ps1
On the Windows build agent, instead of the pinned chef-foundation version as defined in [.buildkite-platform.json](https://github.com/chef/chef/blob/main/.buildkite-platform.json#L2) file, the latest version of chef-foundation gets installed.
=> Fix  to pick pinned  version of  chef-foundation  on windows

.github/workflows/func_spec.yml, lib/chef/resource/macos_userdefaults.rb, spec/functional/resource/macos_userdefaults_spec.rb, spec/unit/resource/macos_user_defaults_spec.rb
Backporting the fix made in #12791 to chef-17
> `user` property was not being used when `host` isn't passed. This is because how the native corefoundation APIs work where we can either pass both to `CFPreferencesSetValue` or pass none to `CFPreferencesSetAppValue`. This PR sets default values for user and host as current user and any host. 
https://github.com/chef/customer-bugs/issues/657
=> Backport: (macos_userdefaults) fix for user attr bug

lib/chef/delayed_evaluator.rb, spec/unit/delayed_evaluator_spec.rb
Finishing up what @steakknife started in #13570. I've removed the whitespace, and rebased to main.
From #13570:
>  `path #<Chef::DelayedEvaluator:0x012345812384 path/to/file>` is unhelpful in resource logs and stack traces. This change fixes that. It assumes dumb, non-idempotent stuff doesn't happen in the lazy evaluation runtime phase. This will hopefully go away when `unified_mode` is possible to use with our API cookbook model.
>
>  `path lazy { (evaluates to) "C:\Program Files\Foobar\Widgets.exe" }`
>
>  `path lazy { (evaluates to) "/home/foo/.your-magic-file" }`
>
> are much nicer.
=> Inspect lazy result (was #13570)

.github/workflows/kitchen.yml
https://github.com/chef/chef/pull/13144/files#diff-e8ec3ff5286f76fd71f48ae74b5f16bcc3522ddb5bd22a9ae1c78b4ecea8009bR20 seems have added redundant ruby installation steps to kitchen tests.
The kitchen tests step under github actions uses Test Kitchen to test various linux systems using their docker containers  whereas...
on Windows and Mac it **does not** use Test kitchen rather we directly install the corresponding omnibus package (because those boxes are available directly under GHA) and run chef-client in local mode using `chef-client -z`, which has ruby embedded inside it, so ruby setup is redundant there .
=> Removing redundant ruby setup from kitchen tests

spec/unit/compliance/reporter/chef_server_automate_spec.rb
The test had a malformed body element for the response object. It was causing tests to fail with new networking gems
=> updated the test to be RFC2119 compliant

lib/chef/chef_fs/file_pattern.rb, lib/chef/chef_fs/path_utils.rb
Found while profiling the cookbook resolution code.
In #join alone there are three references. This leads to a ton of calls to `windows?`, which shouldn't change during the course of a run.
=> Use constant for ChefFS::PathUtils regexp_path_separator

lib/chef/mixin/homebrew_user.rb
fix homebrew path when which() returns false
#13934
=> fix homebrew path when which() returns false

lib/chef/provider/package/chocolatey.rb, spec/functional/resource/chocolatey_package_spec.rb, spec/unit/provider/package/chocolatey_spec.rb
https://github.com/chef/chef/pull/13833 added `choco --version`, but this binary may not be in the path.
Fix this by using `choco_exe` and promoting the calls to instance methods.
=> chocolatey: fix regression in calling `choco --version`

kitchen-tests/cookbooks/end_to_end/recipes/_tests.rb
In troubleshooting an end-to-end test failure, I noticed the "umlaut u" code in the "wrong encoding Latin-1" test (added with [#5335](https://github.com/chef/chef/pull/5335/files)) is `\xFD` which is `ý` and not `ü` if you force encoding to latin 1 (`.force_encoding(Encoding::ISO_8859_1)`) and then `.encode('utf-8')`
```ruby
file "/tmp/chef-test-\xFDmlaut" do
content "testing illegal UTF-8 char in the filename"
end
```
The proper code in ISO-8859/Latin-1 is `\xFC`, which is a trivial detail unless you happen to break graceful handling and you're trying to find a way to match the "bad" Latin-1 string to the UTF-8 string in the case above it.
=> Fix the latin-1 hex value for ü to \xFC

Gemfile, chef.gemspec
FFI versions through 1.16.2 have a [`dlopen` issue](https://github.com/chef/chef/actions/runs/6331945729/job/17197911747#step:5:609) with macOS. Pinning to `~> 1.15.5` for now
=> FFI versions through 1.16.2 have a dlopen issue with macOS. Pinning to ~> 1.15.5 for now

lib/chef/monkey_patches/net-http.rb
The monkey patch for net/http issues pre-Ruby 3.2 added `puts` statements without converting them to `Chef::Log.debug`
[About Monkey patch ruby for net/http added verbosity in #13745](https://github.com/chef/chef/issues/13936)
=> Chef::Log.debug the puts debugs

CONTRIBUTING.md
Fix contribution documentation
Summary:
The documentation tells people to push to remote branches, but they
cannot, so make this clearer.
Thanks to @steph-hickman9 for pointing this out.
Test Plan:
none
=> Fix contribution documentation

lib/chef/cookbook/synchronizer.rb
Should address #13940. The usage of Sets over Arrays was only a minor speedup IIRC, and we can take another pass it once we've figured out why `.to_set` wasn't working with the earlier `require`. `Set` became a built-in in [Ruby 3.2](https://docs.ruby-lang.org/en/3.2/NEWS_md.html), so could also wait until that's the running version before using that `Set` more extensively in the client
#13940
=> Chef::CookbookSynchronizer#remove_deleted_files: Use Array instead of Set

.github/workflows/sonarqube.yml
Don't try to run SonarQube on forked-based PRs
Summary:
It fails anyway, no point in running it
Test Plan:
this is the test!!
=> Don't try to run SonarQube on forked-based PRs

Gemfile.lock
Attempt to make Gemfile.lock stable
Summary:
As it stands today doing a `bundle install` will change `Gemfile.lock`
because the `PLATFORMS` section doesn't list all the platforms.
Used CLIs to fix this:
```shell
[phil@rider RBENV(3.1.1) chef]$ bundle lock --add-platform x64-mingw32
Resolving dependencies....^[[A...
Writing lockfile to /home/phil/src/git/chef/Gemfile.lock
[phil@rider RBENV(3.1.1) chef]$ bundle lock --add-platform x86-mingw32
Resolving dependencies.........
Writing lockfile to /home/phil/src/git/chef/Gemfile.lock
[phil@rider RBENV(3.1.1) chef]$ bundle lock --add-platform arm64-darwin-21
Resolving …
```
=> Attempt to make Gemfile.lock stable

cspell.json, lib/chef/provider/service.rb, lib/chef/provider/service/systemd.rb, lib/chef/resource/service.rb, spec/unit/provider/service/systemd_service_spec.rb
Add hook to service resource for non-enable-able services
Summary:
There are many hacks in `system_service` around non-enable-able services (such as `masked` or `static` services). While this allows for the right underlying behavior, the parent class having no understanding that this can happen means you get weird output like:
```
[2020-06-02T16:56:33-07:00] TRACE: service[gdm] cannot be disabled: it is static
[2020-06-02T16:56:33-07:00] INFO: service[gdm] disabled
```
So this adds a small hook into the service parent class called `enableable?` which subclasses can use to denote (and log why) a service is or isn't enable-able.
This replaces #9949.
Test Plan:
So far, tests all pass, but more testing to come
=> Add hook to service resource for non-enable-able services

.github/workflows/sonarqube.yml
Disable SonarQube wholesale
Summary:
It doesn't work for any users - internal or external - ever.
Test Plan:
This PR will pass :)
=> Disable SonarQube wholesale

.github/workflows/kitchen.yml, .github/workflows/prep_and_run_macos_kitchen_tests.sh
This somehow prevents ffi signature issues with macOS on kitchen tests 
Ohai and other Chef 17 dependencies have ffi < 1.16.0 added but the `gem install berkshelf` in `.github/workflows/kitchen.yml` was installing berkshelf from rubygems which picks up the newest ffi ~> 1.9
match which conflicts with what's installed chef current. `gem build` and
`gem install` from the cached gemspec appears to behave equivalent to bundler
in using the ffi already installed (1.15.5 at the time of this writing) instead of installng the latest (1.16.3 at this moment)
[ffi/ffi#836](https://github.com/ffi/ffi/issues/836)
=> try fixing kitchen tests for macOS

lib/chef/node.rb, lib/chef/recipe.rb, spec/unit/node_spec.rb
Moving the `untag` method the same way `tag` was moved from recipe to node in this commit https://github.com/chef/chef/commit/9e954aeb26e83bb77a645c76a184df5a265161d6
https://github.com/chef/chef/issues/13993
=> Move untag to the node to match tag

kitchen-tests/cookbooks/end_to_end/recipes/windows.rb, lib/chef/resource/locale.rb
[chef#12833](https://github.com/chef/chef/pull/12833/files) broken locale code on Windows by trying to assert that `locale-gen` is in the path, which it won't likely be unless the Windows machine has bash for Windows or similar. The original `shell_out` invocation also errored but the result was non-`nil` so it validated fine for Windows.
```
<Mixlib::ShellOut::Windows::ThingThatLooksSortOfLikeAProcessStatus:0x00000120ff7ffaa0 @exitstatus=1> stdout: '' stderr: ''locale-gen' is not recognized as an internal or external command,
operable program or batch file.' child_pid: 
```
CHEF-3003
=> Fix validation on locale-gen to account for the fact that Windows install does not have it on the path.

lib/chef/resource/support/sudoer.erb
This reverts commit 44a2ae648c68911d6c2e1f13187bd471dae303bf.
Kitchen tests broke without surfacing to the PR status and a fix appears to be more complicated than first anticipated. Reverting this PR for now.
=> Revert "Update sudoer.erb (#14015)"

lib/chef/resource/chef_client_systemd_timer.rb, spec/unit/resource/chef_client_systemd_timer_spec.rb
Added percent sign to the CPUQuota value.
systemd does not accept integer values for a unit's CPU quota. The value must be defined as a percentage.
https://github.com/chef/chef/issues/14009
=> Fix invalid CPUQuota value

Gemfile, Gemfile.lock
The chefstyle group had been inadvertently [commented out in the Ruby 3.1 effort](https://github.com/chef/chef/commit/2f5dbd1ee69c970fc06870477dbbca6c5c3555c4#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR61)
This means that chefstyle (and the rest of the RuboCop toolchain) has been in infra client RPMs since it hasn't been [properly excluded from omnibus](https://github.com/chef/chef/blob/d493cfa966903f8bb03973cee4a96e1d69197352/omnibus/config/software/chef-local-source.rb#L70). This has lead to a significant amount of on-disk install size (at least 10MB, didn't bother to dig into exact numbers since 10MB is enough for me).
I've not modified Gemfile.lock yet since there's not yet a policy for that.
=> Put chefstyle gem back in chefstyle group

cspell.json, kitchen-tests/cookbooks/end_to_end/recipes/_sudo.rb, kitchen-tests/cookbooks/end_to_end/recipes/linux.rb, lib/chef/resource/sudo.rb
Main points with CHEF-2186 are:
The sudo resource documentation is misleading (managed to fool even the support team - nobody found out that I was using the resource wrongly)
The 'commands' option doesn't defaults to the the Cmnd_Aliases' names.
The second one we cannot fix it without breaking someone's code, but the first one can be safely fixed. Can you help with the Spec tests ? I can't make them work, while the suse stuff is "fixed".
=> Update command aliases documentation

Gemfile, Gemfile.lock
Reverts chef/chef#13927
Windows plan on the verify pipeline is failing from the addition of `chefstyle` that was not noticed prior to merging the above PR
```
chef-infra-client:  ** 'rake install' any gem sourced as a git reference so they'll look like regular gems.
--
  | chef-infra-client:  -- installing C:\hab\studios\bk018b4871551a20e31bff\hab\pkgs\ci\chef-infra-client\18.3.39\20231019150510\vendor\bundler\gems\chefstyle-71ae97744713
  | rake aborted!
  | Gem::MissingSpecError: Could not find 'rubocop' (>= 0) among 220 total gem(s)
  | Checked in 'GEM_PATH=C:/hab/studios/bk018b4871551a20e31bff/hab/pkgs/ci/chef-infra-client/18.3.39/20231019150510/vendor;C:/hab/studios/bk018b4871551a20e31bff/hab/pkgs/chef/ruby31-plus-devkit/3.1.2/20220715234242/lib/ruby/gems/3.1.0' , execute `gem env` …
```
=> Revert "Put chefstyle gem back in chefstyle group"

.expeditor/release.omnibus.yml
Looks like [this commit](https://github.com/chef/chef/commit/2827202a5013491d97ecc6d3cbe2ff519efd9fd8) accidentally removed i386 Solaris builds whereas they are [still built in `main`](https://github.com/chef/chef/blob/main/.expeditor/release.omnibus.yml#L75-L76)
=> Re-add solaris i386 because it exists in 18

lib/chef/provider/package/chocolatey.rb, lib/chef/resource/chocolatey_package.rb, spec/unit/provider/package/chocolatey_spec.rb
When we instrumented, chocolatey resources were a major (>30% run time) contibutor to our idempotent run time.  This reduces that to around 2%, via the following optimizations:
* Cache choco list/search command output in order to reduce queries to the nuget servers.  This saves significant wall clock time when installing >50 packages
* Attempt to batch queries as much as possible, either by walking the resource tree, or with a non-default resource property of "bulk_query".  This also significantly reduces load on upstream package servers, since queries are expensive.  Note that on _some_ nuget implementations, bulk_query gets a bad result from the server on v2.x - this is reproducable outside of chef, however.  The public repositories work for this, but it should always be non-default …
=> Optimize chocolatey when doing large numbers of operations, by batching and caching

.github/workflows/lint.yml, Dangerfile, cspell.json
Add Danger CI
Summary:
OK this is a bit complicated. As of now this will work on branch-based PRs
all the time and will often fail on fork-based PRs (but not always). SOOO, what
we do is DETECT that failure and *NOT* fail the PR, but if there are real
issues detected, then we do fail the PR.
There's basically two problems going on here:
1. The GITHUB token given to PRs cannot comment on the PR, and while we
could make a token that does, it would have to have `public_repo` which gives
it full read/write access to the all public repos. Boo. Details throughout
https://github.com/danger/danger/issues/1103
2. There's some combination of bugs/race conditions that cause Danger to
not always see the PR commit, even though it has both remotes. This is discussed
here: …
=> Add Danger CI

lib/chef/node/attribute_collections.rb, lib/chef/node/immutable_collections.rb, lib/chef/node/mixin/state_tracking_array.rb
The State tracking feature is nice, especially as it allows to get an event when an attribute is updated.
However, mutating operations on Arrays were not properly tracked, at least for the "attribute_changed" event.
For instance, `default['array'] << 1` was not triggering an event.
The new code, ensure that all identified mutating methods are properly implementing the State Tracking feature.
To do it, it leverages existing DISALLOWED_MUTATOR_METHODS constant.
#13995
=> Enable state tracking on mutating Array operations

.github/workflows/fips-validation.yml, .github/workflows/kitchen.yml
It appears (as evidenced by a rerun of [kitchen run for 17.10.94 bump](https://github.com/chef/chef/actions/runs/6669026848/job/18125907355)) that the underlying Ruby on the Chef 17 branch GitHub Actions runners now has multiple `ansidecl.h` files as well. Backport the `[0]` selection if it's an Array.
It also appears likely that the file we're trying to copy will actually be in place already, so `SilentlyContinue` the `Move-Item` call.
=> Account for multiple ansidecl.h files found

knife/lib/chef/knife/core/gem_glob_loader.rb
Method untaint does not exist anymore https://bugs.ruby-lang.org/issues/16131
Removed the call to untaint as it can cause crash
While trying to launch a simple command, eg.
`bundle exec knife update roles` I faced the following issue
```
bundle exec knife upload roles
bundler: failed to load command: knife (/xxx/.rbenv/versions/3.2.2/bin/knife)
/xxx/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/knife-18.3.0/lib/chef/knife/core/gem_glob_loader.rb:81:in `block in find_files_latest_gems': undefined method `untaint' for "/xxx/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/knife-18.3.0/lib/chef/knife/acl_add.rb":String (NoMethodError)
end.flatten.select { |file| File.file? file.untaint }
```
This methods seems [not to exist anymore](https://bugs.ruby-lang.org/issues/16131)
I just removed the …
=> Do not use untaint

kitchen-tests/cookbooks/end_to_end/recipes/windows.rb, lib/chef/guard_interpreter/resource_guard_interpreter.rb, lib/chef/provider/powershell_script.rb, lib/chef/resource/powershell_script.rb, spec/unit/provider/powershell_script_spec.rb, spec/unit/resource/powershell_script_spec.rb
This adds support for the powershell_script resource to use powershell.dll directly instead of going through the powershell_out process - this is _significantly_ faster if you're doing a lot of small powershell changes.  For our environment, doing things this way instead of via powershell_out yields a 28% reducition in chef run time.
It is not, and should not be, default behaviour because there are a bunch of semantic differences - most notably, you can't stream output, and you can't switch user.  But for a significant number of powershell use cases, the large performance improvement makes this worth the compromise.  This is particularly true for idempotent runs, where executing guards can be a significant user of cycles from constantly starting powershell.exe/pwsh.exe
It can be seen to …
=> Add support for use_inline_powershell for powershell_script

Gemfile, Gemfile.lock, chef.gemspec
Updating Chef-17 to get past CVE's in Inspec and update selected gems to get past failures in the testers.
=> Updating Inspec and its dependencies

lib/chef/provider/package/zypper.rb, spec/functional/resource/zypper_package_spec.rb
The latest version of zypper in SLES 15 SP5 returns a 104 return code when querying or removing packages that do not exist in the repository. As a result, listing packages that should not exist on a system in the 'zypper' resource of chef results in the chef recipe failing due to a non-zero exit code.
Note, you may need to update packages first to trigger the error:
```sh
sudo zypper ref
sudo zypper update
```
Running `chef-apply recipe.rb` on the following recipe.rb should trigger the error on latest SLES 15 zypper:
```ruby
package "bork" do
action :remove
end
```
[package resource sub item zypper_package cannot handle removing non-present packages
](https://chefio.atlassian.net/browse/CHEF-8848) (internal issue)
=> Capture a '104' return from zypper info

lib/chef/provider/service/windows.rb
Backport of this [PR 14064](https://github.com/chef/chef/pull/14064)
When using windows_service to create/configure Windows services, if you specify a description, it will trigger a change on every execution due to the value not being discovered in load_current_value
=> [chef-17] backport pr14064

lib/chef/resource/chef_client_systemd_timer.rb, spec/unit/resource/chef_client_systemd_timer_spec.rb
Backport of this [PR 14011](https://github.com/chef/chef/pull/14011) - Fix invalid CPUQuota value
=> [chef-17] backport pr14011

.github/workflows/kitchen.yml, cspell.json, lib/chef/mixin/homebrew_user.rb, lib/chef/resource/homebrew_cask.rb, lib/chef/resource/homebrew_package.rb, lib/chef/resource/homebrew_tap.rb, spec/unit/mixin/homebrew_user_spec.rb
Backporting PR13669 and PR13937 to fix homebrew
=> [chef17] backport homebrew prs

lib/chef/file_access_control/windows.rb
This PR corrects issues in Chef-18 only where executing the chef_client_config resource results in permissions on the \chef folder being removed or otherwise borked. Please see the following issues:
[Github](https://github.com/chef/chef/issues/14170)
[Jira](https://chefio.atlassian.net/jira/software/c/projects/CHEF/boards/492?selectedIssue=CHEF-3839)
The `file_access_control\windows.rb` file has a bug in it. It appears to be a Ruby issue. On line 327 when checking to see if permissions need to be updated, the acls object is nil entering this statement:
`acls.nil? ? nil : Chef::ReservedNames::Win32::Security::ACL.create(acls)`
When the clause acls.nil? executes, it returns false which is incorrect because the damned thing IS empty. That causes the secondary part of the ternary to execute …
=> Correcting security issue

.github/workflows/lint.yml, spec/functional/resource/zypper_package_spec.rb
Linting is failing in the verify pipeline. This is because of this [bug](# Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0').
=> Overcoming Ruby linting error

.buildkite-platform.json, omnibus/Gemfile.lock
Bump `chef-foundation` and `omnibus` to pick up [Truncate depend fmri version specifiers to allow Solaris install flexibility](https://github.com/chef/omnibus/pull/1144)
`bundle update --conservative omnibus` in `/omnibus`:
```
❯ bundle update --conservative omnibus
Fetching https://github.com/chef/omnibus-software.git
Fetching https://github.com/chef/omnibus.git
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies..................
Using public_suffix 5.0.3
Using artifactory 3.0.15
Using awesome_print 1.9.2
Using rack 2.2.6.4
Using uuidtools 2.2.0
Using webrick 1.8.1
Using diff-lcs 1.5.0
Using iniparse 1.5.0
Using faraday-net_http 3.0.2
Using ruby2_keywords 0.0.5
Using tty-color …
```
=> Bump buildkite-platform and omnibus for solaris issue

Gemfile, Gemfile.lock, chef.gemspec
We had temporarily locked `ffi` gem to `~> 1.15.5` due to issues similar to https://github.com/ffi/ffi/issues/836 in https://github.com/chef/chef/pull/13964
However, on revisiting the upgrade, it appears that the GitHub Actions macOS workers were having issues at the time.
=> Unbound ffi upgrades and bundle update --conservative

knife/knife.gemspec, knife/lib/chef/knife/bootstrap.rb, knife/spec/unit/knife/bootstrap_spec.rb
This is a rebuild of https://github.com/chef/chef/pull/13534. The underlying branch was deleted somehow?
These changes supported protocols for knife bootstrap to dynamic detection of installed Train transports instead of just static ssh and winrm.
With this, alternative connection options such as AWS Systems Manager, Telnet, Serial/USB, and others get viable for easy onboarding of Chef nodes.
=> Updating Train Support to allow for more connection types

.expeditor/verify.pipeline.yml, knife/knife.gemspec
=> Try pinning to 0.10.1 if Ruby 3.0.0 specifically is in use (for Fedora rubydistro)

.buildkite/verify.pipeline.sh, .expeditor/config.yml
Removing this docker build from the subscriptions to get around the `/promote` command in expeditor cli. 
We dont even pull from the stable branch on the docker file, and produces an image that isnt being used.
using skip all here, to re-load the expeditor config, then we can do the 'expeditor promote' command.
=> modifying this setting for the release

.buildkite/build-test-omnibus.sh
this is pointing incorrectly to a docker image that we dont create or is used.
We have an issue where on the generated pipeline at runtime, it was selecting the docker image for the arm builders as:
```
plugins:
- docker#v3.5.0:
image: chefes/omnibus-toolchain-rhel-9-arm:3.0.0
```
This is incorrect, the value should be:
```
plugins:
- docker#v3.5.0:
image: chefes/omnibus-toolchain-rhel-9:3.0.0
```
As example. 
From there we do swap the build queue, as that will automatically select the proper aarch based off the docker host its running:
=> removing the arm value here

.buildkite/verify.pipeline.sh
[chefspec#6](https://github.com/chef/chefspec/pull/6) has fixed the rspec private API change issue temporarily, but the chefspec step was pointing at `chefspec/chefspec` instead of `chef/chefspec`
- [ X] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
=> chefspec verify needs to point to chef/chefspec

lib/chef/node.rb
Using `self` does a DeepMergeCache build on `:recipes`, which worsens as the array grows with included recipes since appending the recipe to the array causes the DeepMergeCache to drop for `:recipes`. `loaded_recipe` uses the `:recipes` array as a an ordered set, and doing writes to `:recipes` outside of automatic precedence doesn't make sense. Avoid reads from the other precedence levels entirely and read directly from the automatic precedence.
Potentially worth discussing - should we also change the `#recipe?` method?
=> Avoid DeepMergeCache flap in Chef::Node#loaded_recipe

Gemfile, Gemfile.lock, knife/Gemfile, omnibus/omnibus-test.sh
AIX and macOS (ARM only?) builds are failing on attempting to bundle `bigdecimal`. AIX is due to the bundle requiring `bigdecimal` on a test environment without a compiler to build the native extension and macOS ARM is failing with a code signature error:
```txt
Failure/Error: require "webmock/rspec"
--
  |  
  | LoadError:
  | dlopen(/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/bigdecimal-3.1.5/lib/bigdecimal.bundle, 9): no suitable image found.  Did find:
  | /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/bigdecimal-3.1.5/lib/bigdecimal.bundle: code signature in (/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/bigdecimal-3.1.5/lib/bigdecimal.bundle) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or …
```
=> Fix bigdecimal error with webmock / crack in macOS and AIX builds

Gemfile, Gemfile.lock, knife/Gemfile
Cherry-pick backport of (#14243) from `main`
* restrict crack (dependency of webmock) to < 0.4.6 due to update for bigdecimal being extracted from ruby 3.4.0 as default gem.
---------
=> Fix bigdecimal error with webmock / crack in macOS and AIX builds 

lib/chef/resource/chef_client_systemd_timer.rb
Add property to modify the Service UMask directive in the SystemD unit content. This allows fixing of the chef-client umask for files and directories created by chef-client. Hardened systems change the system default which then breaks chef-client package installs and file creations for configuration management.
=> add umask to chef_client_systemd_timer

.buildkite/hooks/pre-command, .expeditor/scripts/omnibus_chef_build.ps1, .expeditor/scripts/prep_and_run_tests.ps1
Change to `pre-command` is to prevent:
```
C:/bk018dc96f97171dc5b89d/.buildkite/hooks/pre-command: line 19: [: ==: unary operator expected
```
The change in `prep_and_run_tests.ps1` is to match `omnibus_chef_build.ps1` in using `${env:CHEF_FOUNDATION_VERSION}` instead of `$CHEF_FOUNDATION_VERSION`. The environment variable `CHEF_FOUNDATION_VERSION` gets forwarded via `--env CHEF_FOUNDATION_VERSION` in the `docker` invocation, but that will population the `$env:` variable inside the container.
=> Safeguard for undefined and fix reference to CHEF_FOUNDATION_VERSION

chef.gemspec
Fixes a problem that most recently manifested in a `bundle install` in `chef/cheffish` but we've since other manifestations elsewhere. The problem is that the `eval(IO.read("chef-utils/lib/chef-utils/version_string.rb"))` doesn't fix the fact that `chef-utils/version_string` isn't in the load path for the later `require "chef-utils/version_string"` another solution might be to just `eval` or `require "chef-utils/version_string"` but the `eval` feels like unnecessary messiness.
Example error:
```
[!] There was an error while loading `chef-universal-mingw-ucrt.gemspec`: cannot load such file -- chef-utils/version_string. Bundler cannot continue.
>  gemspec = instance_eval(File.read(File.expand_path("chef.gemspec", __dir__)))
```
=> Fix requiring of chef-utils/version_string.

.expeditor/verify.pipeline.yml
As part of the update for the new Ohai, we pull in a new inspec build as well. That tool relies on the uri gem which will fail to load if we don't force an update first.
The failure in the fedora builds is because we need to merge this update: https://github.com/chef/chef/pull/14271
=> Forcing bundle update to get the URI gem to load properly

chef.gemspec
fedora tests are failing again on the uri gem. This happens in Chef now (instead of just Knife) because of a pending update for Inspec that pulls in a new version of uri. That PR is pending
=> Updating to properly load URI for Fedora

Gemfile, Gemfile.lock, chef.gemspec
Updating inspec version requirements to ensure that CVE and ActiveSupport dependency fix from 5.22.40 are the minimum version requirements for Chef 17.
=> Bumping inspec-core minimum version requirement

lib/chef/provider/package/chocolatey.rb, spec/unit/provider/package/chocolatey_spec.rb
Make `use_choco_list` actually not use choco list when set to false
This fixes a regression that happened in a refactor, where the `use_choco_list` logic got flipped when changing how the global option worked.  Additionally, this fixes a bug that was introduced with multi-case package name compares not being downcased correctly.  The other half of the caching was the bigger win in my test environment, so i didn't catch the performance regression until I deployed the chef18 code more widely in our org.
Additionally, it didn't fail tests because the selection regression actually stopped the broken code from being hit at all.  This updates the tests to have the two mechanisms return different output, so the tests can tell that the correct one is being hit.
=> correct logic for `use_choco_list` in chocolatey_package provider

lib/chef/formatters/doc.rb
Deprecation warnings currently use a hardcoded product name, which could instead use the distro-specific product string.
```
Deprecation warnings that must be addressed before upgrading to Chef Infra 19:
The resource in the cookbook should declare `unified_mode true` at 1 location:
- /Users/foo/.cinc/local-mode-cache/cache/cookbooks/example/resources/test.rb:34:in `block in class_from_file'
See https://docs.chef.io/deprecations_unified_mode/ for further details.
```
=> Replace Chef trademark with distro name in deprecation warnings.

.expeditor/scripts/bk_win_functional.ps1
The Windows images on buildkite have 2 discrete installs of Ruby on them. One is version 3.0.0 and the other is 3.0.3p157 - the URU option is set to choice option '30' which brings up a screen prompt to choose the version. Here I am forcing the version.
=> Amending URU to be more version specific

lib/chef/resource/habitat_install.rb
We have a bug against the hab installer here [Bug](https://chefio.atlassian.net/browse/CHEF-627). In a nutshell, the installer is calling a random bash executable. One problem is that we explicitly call bash from our script. Here we update the bash script (per comments from Marc Paradise in the bug) to remove the call to bash and let the hab_installer.sh figure it out. Then we set the downloaded script to mode 0755 so it's executable. That will be easier for customers to use and solve for which bash shell gets called.
=> Cleaning up the installer

.buildkite/build-test-omnibus.sh, .expeditor/adhoc-canary.omnibus.yml, .expeditor/release.omnibus.yml
Removing OSX 10.15 support per request from Build Services
=> Removing OSX 10.15 support per request from Build Services

lib/chef/resource/snap_package.rb
The docs for `snap_package` don't make it clear that you need to specify classic confinement like so:
```ruby
snap_package 'hello' do
options 'classic'
end
```
closes #10589
=> Add examples to snap_package resource.

omnibus/Gemfile.lock
We have an issue with an update to Ohai. A correction to windows fqdn name resolution required use of the 'Resolv' class which in turn (re)loaded the Win32/Registry class. That PR is [here](https://github.com/chef/ohai/pull/1816). That action - reloading the Win32/Registry class, stepped all over the Win32/Registry monkey patch we have in place to get data out of the Registry encoded in UTF-8. That was fixed in [omnibus-software](https://github.com/chef/omnibus-software/compare/8a87f3b2b842abe80bc997de9da3e43696ea5c36...763ae8b0f5c60b90ee0451b61d4dca2022229315#diff-67082374705e880301df0ba02632f9467cf1be3b7aaf484c4e3ecf33f821b806R2) via a patch to `ext/win32/lib/win32/resolv.rb`
This update pulls that patch in for testing and ultimately a release.
=> Pulling in updated Omnibus and Omnibus-Software

knife/lib/chef/knife.rb, knife/spec/unit/knife_spec.rb
In the chef config, there are two different options to set the log level. One is the `log_level` and the other is the `verbose`. The verbose has more preference, meaning that if it is set, it will overwrite the log_level based on the verbosity level. 
Currently, If the verbosity is not set, the code will default the log_level to `warn` even if the user specifies a different log_level on the config.rb or the credentials file.
This PR will update that flow so that, if the verbosity is not set, it will use whatever value is already set on the log_level and if that is `:auto`(the default value), it will default to `warn`.
=> Fixed the issue with log level on the chef config

Gemfile.lock, chef.gemspec, knife/knife.gemspec
Updating Ohai and FFI to pull in needed updates from them.
[Admin] PS C:\localrepo\chef2 (jfm/chef17-update-gems) bundle update --conservative ohai ffi
I am (re)loading the Resolv Class
Loading The Base Win32/Registry class
I am in the win32/Resolv class
Fetching https://github.com/chef/ohai.git
Resolving dependencies.......
Using rake 13.1.0
Using public_suffix 5.0.4
Using concurrent-ruby 1.2.2
Using ffi 1.16.3 (x64-mingw32)
Using wmi-lite 1.0.7
Using aws-eventstream 1.2.0
Using aws-partitions 1.809.0
Using bundler 2.3.18
Using debug_inspector 1.1.0
Using builder 3.2.4 …
=> Updating gems

.expeditor/adhoc-canary.omnibus.yml, .expeditor/release.omnibus.yml
Freebsd version 12 is no longer being used. Updating testers
=> Updating Freebsd versions

lib/chef/policy_builder/policyfile.rb
When chef_vault_item was moved into chef client in #9477  the node attributes chef-vault and databag_fallback were never set. Any call to chef_vault_item in test kitchen will result in undefined method '[]' for nil:NilClass for node["chef-vault"]["databag_fallback"].
Setting this attribute to the node `node.default["chef-vault"]["databag_fallback"] = true`, this will fixed the undefined method '[]' for nil:NilClass for node["chef-vault"] and will also preserve the fall back to loading an unencrypted data bag item if the item we're trying to load isn't actually a vault item
Fixes : 
https://github.com/chef/customer-bugs/issues/761
https://github.com/chef/chef/issues/13084
=> Added the databag_fallback attribute

lib/chef/resource/execute.rb
There is some confusion about `add_account_right` and whether it can take immediate effect in Windows in the same Chef run. Also updated the example for setting rights to use `windows_privilege_resource`
=> Add note about adding account rights not taking immediate effect.

lib/chef/provider/service/windows.rb
Reverts chef/chef#14064
`Struct::ServiceConfigInfo` doesn't have `description` and `win32-service` is in a state in which it can't be rolled out at the moment.
```ruby
NoMethodError
undefined method "description' for #<struct Struct::ServiceConfigInfo service_type="own process"
```
=> Revert "Add missing `description` to windows_service load_current_resource for idempotent check to be successful"

lib/chef/provider/service/windows.rb
Reverts chef/chef#14151
`Struct::ServiceConfigInfo` doesn't have `description` and `win32-service` is in a state in which it can't be rolled out at the moment.
```ruby
NoMethodError
undefined method "description' for #<struct Struct::ServiceConfigInfo service_type="own process"
```
=> Revert "[chef-17] backport pr14064"

.buildkite/build-test-omnibus.sh, omnibus/config/software/chef-local-source.rb
Bundle install on new IBM hosts were taking more time. Update the bundle install command to improve the build time.
update [omnibus-plugin](https://github.com/chef/omnibus-buildkite-plugin/compare/v0.2.86...v0.2.88) version to pick the new IBM hosts .
Since freebsd-12 EOL, updated the freebsd-13 as builder and deprecated the freebsd-12 support.
=> Chef 10065 - Support new IBM hosts

chef-utils/lib/chef-utils/dsl/virtualization.rb, chef-utils/spec/unit/dsl/virtualization_spec.rb
Signed-off-by: Mike Butler <michael.butler@progress.com>
hyperv was missing from the virtualization helpers. There is no host, only guest.
=> hyperv added to virtualization helper

lib/chef/mixin/openssl_helper.rb, omnibus/omnibus-test.ps1, spec/unit/mixin/openssl_helper_spec.rb
Extracting fixes for EC syntax and modulo length that will generate errors in OpenSSL 3.0. Gem installs of chef on 3.1 (see: unit tests in GitHub Actions) are already flagging this due to the update of `macOS@latest` runners to use ARM which has OpenSSL 3 installed.
=> EC and modulo length update for OpenSSL 3 compatibility

spec/integration/client/fips_spec.rb
Add a test to validate FIPS' invalidation of MD5 hashes from the OpenSSL library.
Integration on CentOS, RHEL, Ubuntu, and Windows should show the following in the [Chef OSS Verify Pipeline](https://buildkite.com/chef-oss/chef-chef-main-verify/) (FIPS enabled/linked)
```
chef-client fips
Do not error enabling fips_mode if FIPS linked
Error on MD5 if fips_mode
```
Debian and SLES integration tests should show the FIPS disabled results
```
chef-client fips
Error enabling fips_mode if FIPS not linked
Do not error on MD5 if not fips_mode
```
=> Test FIPS MD5

.github/workflows/kitchen.yml, lib/chef/provider/package/snap.rb
Snap has been erroring for 18.04 in kitchen-test with the following error in API body that is being parsed:
`ERROR cannot reload udev rules: exit status 2\nudev output:` 
Moving to the vagrant + virtualbox section (`vm_lnx_x86_64`)
=> Move Ubuntu 18.04 kitchen test to Virtualbox + Vagrant 

.buildkite/hooks/pre-command
The freebsd 13 image was not working with the aws calls. It was missing a region ENV. This is to address that. 
We also dont want to have to rely on connections back to vault. I updated those to pull directly from parameter store as well.
=> Sean simmons progress/chef 11286 freebsd13 fix

knife/lib/chef/chef_fs/knife.rb
=> [Knife#pattern_arg_from] Use start_with?

.github/workflows/kitchen.yml, kitchen-tests/kitchen.dokken.yml, kitchen-tests/kitchen.exec.macos.yml, kitchen-tests/kitchen.linux.ci.yml, kitchen-tests/kitchen.yml
Add ubuntu 24.04 to tests and fix macos-latest is now run on apple silicon vs x86 in github actions.
=> update kitchen-tests platforms

lib/chef/node/mixin/state_tracking.rb
`compact` creates a new Array object, which is unnecessary here. Use `compact!` instead
=> [StateTracking] Do in-place compact

docs/dev/policy/release_and_support_schedule.md, lib/chef/client.rb, spec/unit/client_spec.rb
Since there is no specific schedule for major releases having an eol message is irrelevant.
=> Backport: Chef-17 - Remove EOL warning

lib/chef/node/immutable_collections.rb
One of the reasons DeepMergeCache flaps are so bad for performance is that we `dup` new objects that aren't Hashes/Arrays during the creation of the cache, but we also freeze the new objects well. Freezing an Object makes further modification of the object result in RuntimeError, which means they are already immutable.
Given the expectation that the objects aren't able to be further modified, creating duplicate objects (which are then also frozen) appears to be needless, since we can instead pass the frozen object during ImmutableMash/ImmutableArray creation.
This *significantly* cuts the number of `Kernel#dup` calls in a run.
References:
- https://docs.ruby-lang.org/en/master/Object.html#method-i-freeze
- https://docs.chef.io/release_notes_client/#13.0.113-freezing-immutable-merged-attrib …
=> [Immutablize#convert_value] return already frozen String objects

lib/chef/cookbook/cookbook_version_loader.rb
Simple string comparison is cheaper than a `stat`
=> [CookbookVersionLoader#load_all_files] Do directory test after name check

lib/chef/node/attribute.rb
Saw this while doing some profiling of attributes reads/writes. By moving the `merge_with == NIL` conditional out of the `deep_merge!` and `hash_only_merge!` methods, there's less method overhead over the course of a run since attribute keys generally aren't set on every attribute type (ie default/force_default/normal/override/force_override/automatic).
=> Move attribute merge NIL checks into inject 

lib/chef/file_cache.rb, spec/unit/file_cache_spec.rb
This moves pre-computable values from the inner loop of `#find` to outside of the loop.
=> [FileCache#Find] N to 1 calls for file matching

chef-config/lib/chef-config/config.rb
These two methods get hit with each call to [cache_path](https://github.com/dafyddcrosby/chef/blob/f52a96dafa46968fd5ca21db35b83f649acb387f/chef-config/lib/chef-config/config.rb#L374-L375), and are essentially constant values.
=> [ChefConfig] Add memoization to var_root_dir and var_chef_dir methods

.buildkite-platform.json, .buildkite/build-test-omnibus.sh, .expeditor/scripts/download_built_omnibus_pkgs.sh, Gemfile, Gemfile.lock, omnibus/Gemfile, omnibus/Gemfile.lock, omnibus/omnibus-test.sh, spec/integration/client/fips_spec.rb, spec/integration/client/ipv6_spec.rb, spec/integration/client/open_ssl_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb
`chef-foundation` bump to `3.2.8` for build and environment fixes.
Leave AIX on `chef-foundation` version `3.1.20`
Force `OPENSSL_FIPS` before installation and build of anything that builds `openssl` gem.
Include `openssl` gem in `Gemfile` to ensure that a FIPS enabled version of `openssl` is used, versus the default for the ruby install.
Determine whether to do `fips_mode` tests by a list of platforms carried from the `chef-foundation` `release.omnibus.yml` `fips-platforms` and mapped to associated testers.
`mixlib-shellout` version `bundle update` for fixes to build.
```bash
❯ bundle update --conservative mixlib-shellout
Resolving dependencies...
Using rake 13.0.6
Using public_suffix 5.0.1
Using …
```
=> Chef 18.5: OpenSSL 3 / chef-foundation split version

omnibus/Gemfile, omnibus/Gemfile.lock
Windows Builds in the Ad-Hoc pipeline keep breaking because they say they can't find the win32-process gem. Here I am explicitly loading it to get past that error message
=> forcing win32-process

Gemfile, Gemfile.lock, lib/chef/http/ssl_policies.rb, lib/chef/mixin/openssl_helper.rb, omnibus/Gemfile, omnibus/Gemfile.lock, omnibus_overrides.rb, spec/integration/client/fips_spec.rb, spec/integration/client/open_ssl_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb, spec/unit/mixin/openssl_helper_spec.rb
* install openssl 3.2.0 to backfill for custom openssl
* Set OpenSSL version to 1.0.2zi for Windows due to FIPS challenges and 3.0.9 for others.
* `::File.exists?` -> `::File.exist?` for `ssl_policies.rb` 
* Fix `EC` and modulus length for OpenSSL 3 compatibility
* OpenSSL validation checks
=> OpenSSL 3 bump for Chef 17

.github/workflows/kitchen.yml, spec/functional/resource/group_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb
A number of the 'groups' specific tests are not working correctly for FreeBSD 13. The spec file is really circuitous and could use a rewrite. To be clear, the code runs correctly on Freebsd13 but our testing does not. Here we bypass some of the problematic sections to move the build forward.
=> Freebsd testing updates to get past group_spec errors

lib/chef/compliance/runner.rb, lib/chef/licensing.rb, lib/chef/licensing_config.rb
This PR adds a software entitlement check for the compliance phase. With this check to run the compliance phase in Infra, the user's license must include entitlements for both Infra and InSpec.
CHEF-12738: Ensure that there is a separate software_entitlement_check call for compliance phase
CHEF-11810: InSpec Validation by Infra License
=> CHEF-12738: Ensure that there is a separate software_entitlement_check call for compliance phase

lib/chef/provider/cron.rb, spec/unit/provider/cron_spec.rb
Fix false updates on cron resource when using integers.
This PR backports https://github.com/chef/chef/pull/13147 to Chef17.
=> [Chef-17][Backport #13147] Fix false updates in cron resource when using integers

Gemfile, Gemfile.lock
The RDoc gem, as installed by base Ruby and not chef, has a CVE. Here we explicitly add/update the rdoc version to overcome that CVE. Notes here: https://www.ruby-lang.org/en/news/2024/03/21/rce-rdoc-cve-2024-27281/. Chef Bug here - https://chefio.atlassian.net/browse/CHEF-13657
=> Updating the rdoc version for Chef-18

spec/functional/resource/group_spec.rb
In this [PR](https://github.com/chef/chef/pull/14528) we updated some code in the groups_spec.rb to overcome problems with running the tests on freebsd. However, that update broke tests for macos. This update corrects that
=> rolling back changes to ohai platform and os detection

spec/functional/resource/group_spec.rb
AIX 7.2 is also dying on the same test blocks that macos is. I am removing testing for these 2 blocks.
=> Updating group_spec to filter out AIX on some tests

kitchen-tests/cookbooks/end_to_end/recipes/linux.rb
The ntp::apparmor service does not work properly on our testers in test-kitchen. Bypassing that test here.
=> Removing the ntp test for Ubuntu 22.04

.expeditor/adhoc-canary.omnibus.yml, .expeditor/release.omnibus.yml
We need to have chef running correctly on Amazon Linux 2023. Adding AdHoc and Release builders/testers here
=> Add Amazon Linux 2023 builders and testers to adhoc and release pipelines.

.expeditor/config.yml
* Disable pushing of build artifacts to omnitruck via disabling of `/release` pipelines.
* Disable Expeditor promotion of chef builds to Rubygems.
https://chefcommunity.slack.com/archives/C042KK33E8K/p1722972507202219 
With the new PI upcoming this is a start to ensure we dont build an omnibus production release. This is an initial step so that we can begin work on the new habitat release(s)
=> disabling omnibus production builds

.github/workflows/lint.yml
Obvious fix
Partially resolves this warning:
> The following actions use a deprecated Node.js version and will be forced to run on node20: carlosperate/download-file-action@v2.0.0, streetsidesoftware/cspell-action@v2.12.0. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> Obvious fix: replace lint download action with curl

.expeditor/scripts/omnibus_chef_build.sh
The GPG keys for signing RPM packages for Chef Infra Client are still using SHA1, which is deprecated in EL9.
Hence updating the .rpmmacros to sign the package with SHA256.
=> modify .rpmmacros to sign the rpms with SHA256

.expeditor/build-docker-images.sh, .expeditor/config.yml, Dockerfile
chef/chef docker builds were disabled due to broken pipeline. I found the pipeline was broken due to the dockerfile using the RHEL-6 OS for downloading the chef-client rpm build. Since RHEL-6 is EOL chef-client isn't built for that platform anymore it thus is breaking the docker pipelines. This bumps it up to use a more modern rpm for RHEL-9.
These builds are needed for kitchen-dokken driver as the chef/chef volume for the desired version is then downloaded and mounted to all docker containers instead of bootstrapped individually on all containers decreasing run times and giving a faster feedback loop.
=> [CHEF-18] fix docker builds

lib/chef/provider/link.rb, lib/chef/resource/link.rb
=> Fix #6238 - handle link :delete action without `to`

cspell.json, kitchen-tests/cookbooks/end_to_end/recipes/_windows_user_privilege.rb, lib/chef/provider/user/windows.rb, lib/chef/win32/security.rb, spec/unit/provider/user/windows_spec.rb
<details><summary>When a security principal is granted a Windows user right and then deleted any future attempt to manage that user right using the windows_user_privilege will cause a converge failure.</summary>
Reproduction case:
```ruby
user "testuser"
windows_user_privilege "SeNetworkLogonRight" do
privilege "SeNetworkLogonRight"
users ["BUILTIN\\Administrators", "NT AUTHORITY\\Authenticated Users", "testuser"]
action :set
end
user "testuser" do
action :remove
end
windows_user_privilege "SeNetworkLogonRight" do
privilege "SeNetworkLogonRight"
users ["BUILTIN\\Administrators", "NT AUTHORITY\\Authenticated Users"]
action :set
end
```
</details>
Clear user permissions prior to deleting.
[chef/chef Issue #12212](https://github.com/chef/chef/issues/12212) 
Internal issue: …
=> Clear user privileges before deleting user in Windows

cspell.json, kitchen-tests/cookbooks/end_to_end/recipes/_windows_user_privilege.rb, lib/chef/provider/user/windows.rb, lib/chef/win32/security.rb, spec/unit/provider/user/windows_spec.rb
* Clear user privileges before deleting user in Windows
* Add test for `windows_user_privilege`
Porting of https://github.com/chef/chef/pull/14575 back to main
=> Clear user privileges before deleting user in Windows (#14575)

Gemfile.lock, chef-universal-mingw-ucrt.gemspec, lib/chef/provider/package/chocolatey.rb, lib/chef/win32/registry.rb, spec/unit/provider/package/chocolatey_spec.rb
Chocolatey dumps a deprecation warning for `list` command if you're on *1.4* in addition to the deprecation in version 2.
Use `search` if on 1.4 or later.
`bundle update --conservative` is not necessary, as the chef (windows) gem spec is the reason for the `Gemfile.lock` update. Use `universal` for the Windows `gemspec` to prevent losing the Windows section on `bundle install`
Proactively include `win32/resolv` so that it's loaded prior to forcing a monkey patch on the `export_string` method.
=> Search for choco 1.4, chef-powershell bundle fix, and resolv registry patch fix

.buildkite/build-test-omnibus.sh, .buildkite/verify.pipeline.sh
Removing all the esoteric platforms as they are not supported for Chef-19. We also need to be aware of the testers in the verify pipeline - we are relying on centos but the versions we are using are all EOL and we need to find suitable replacements
=> Reducing the list of esoteric platforms

.github/workflows/lint.yml
Backport of #14562 to `chef-18`
=> Backport: replace lint download action with curl in .github lint

omnibus/Gemfile.lock
Current build failures:
```
Encountered error(s) with project's licensing information.
--
  | Failing the build because :fatal_licensing_warnings is set in the configuration.
  | Error(s):
  |  
  | Can not automatically detect licensing information for 'chef' using license_scout. Error is: 'Network error while fetching 'https://raw.githubusercontent.com/ruby/time/master/LICENSE.txt'
  | 404 Not Found'
  |  
  | If you are encountering missing license or missing license file errors for **transitive** dependencies, you can provide overrides for the missing information at https://github.com/chef/license_scout/blob/1-stable/lib/license_scout/overrides.rb#L93.
  | Promote license_scout to Rubygems with `/expeditor promote chef/license_scout:1-stable X.Y.Z` in slack.
  |  
  |  
  | …
```
=> [Chef-19]Bump license_scout to 1.3.11

omnibus/Gemfile.lock
Current build failures:
```
Encountered error(s) with project's licensing information.
--
  | Failing the build because :fatal_licensing_warnings is set in the configuration.
  | Error(s):
  |  
  | Can not automatically detect licensing information for 'chef' using license_scout. Error is: 'Network error while fetching 'https://raw.githubusercontent.com/ruby/time/master/LICENSE.txt'
  | 404 Not Found'
  |  
  | If you are encountering missing license or missing license file errors for **transitive** dependencies, you can provide overrides for the missing information at https://github.com/chef/license_scout/blob/1-stable/lib/license_scout/overrides.rb#L93.
  | Promote license_scout to Rubygems with `/expeditor promote chef/license_scout:1-stable X.Y.Z` in slack.
  |  
  |  
  | …
```
=> [Chef-18]Bump license_scout to fix build failures

knife/Gemfile.lock
While separating chef18 and 19 branches, `knife/Gemfile.lock` was left at chef 18 due to which it is pulling in chef18 which is breaking knife gem due to incorrect dependencies. 
This will also fix automated version bumps on a PR merge not bumping chef versions in `knife/Gemfile.lock`
=> [Chef-19] Fix knife/Gemfile.lock to pull correct chef 19 version instead of 18

.expeditor/update_version.sh
`update_version.sh` should be pointing to `chef-18` but is still pointing to `main` due to which the script has been failing to update Chef version in Gemfile.lock and knife/Gemfile.lock.
=> [Chef-18] Fix issue in automated expeditor version bump not bumping the versions in Gemfile.lock

lib/chef/resource_inspector.rb, spec/unit/resource_inspector_spec.rb
[backport]
This enhances chef-resource-inspector to understand LWRP files which contain multiple resources.  This allows for using the resource inspector in documenation flows where these resources have been generated outside chef, as an example
=> [chef18] Enhance resource inspector to understand LWRP files containing multiple resources

Gemfile.lock, knife/Gemfile.lock
Note: `bundle update --conservative` constraint not applicable due to fixing of a manual update process.
This is [part2] of fixing expeditor automated version bumps. We the script here https://github.com/chef/chef/pull/14610
In this PR we update Chef version manually in Gemfile.lock and knife/Gemfile.lock so that the script can update the versions there correctly. (Because we fixed the command with `git show chef-18:VERSION` to find the older version to be replaced in lock files, but the versions there were stuck at a value which `sed` could not find hence the script was still failing partly.)
=> [Chef-18] Fix Chef versions in lock files manually as the script was not working before

.github/workflows/kitchen.yml
backport fix for linux tests to chef-18 branch
=> [chef-18] backport fix vm tests

habitat/plan.sh, habitat/tests/test.sh
In bash shell, 'rspec' was not available on the path and that resulted in the hab pkg exec command failing. We correct that here
=> Fixing missing rspec in hab plan testing

.buildkite-platform.json, .buildkite/build-test-omnibus.sh, .buildkite/verify.pipeline.sh, Gemfile.lock, chef-universal-mingw-ucrt.gemspec, chef.gemspec, lib/chef/provider/package/chocolatey.rb, lib/chef/win32/registry.rb, spec/integration/client/open_ssl_spec.rb, spec/support/platform_helpers.rb, spec/unit/provider/package/chocolatey_spec.rb
Have query_command check look for 1.3 instead of 1.4 Use Gem::Dependency to check < 1.4
Use universal gemspec
Force win32/resolv load and then patch
`bundle install` instead of `bundle update --conversative` due to the change in `.gemfile` for Windows
Old-ish output from `bundle install`
```
❯ bundle install
Resolving dependencies....
Using rake 13.0.6
Using public_suffix 5.0.1
Using aws-eventstream 1.3.0 (was 1.2.0)
Fetching aws-partitions 1.970.0 (was 1.739.0)
Using debug_inspector 1.1.0
Using builder 3.3.0 (was 3.2.4)
Using concurrent-ruby 1.2.2
Using …
```
=> Choco deprecation, windows chef-powershell, and Ruby 3.1.6 chef-foundation 

Gemfile, Gemfile.lock
Updating Ohai to 19.0.3 as a gem instead of from the repo
=> Updating Ohai

habitat/plan.ps1
Fixes the Windows plan that resolves the issue of failing to load the openssl.so file.
The OpenSSL gem is unable to resolve the OpenSSL libraries installed with core/openssl. This PR installs the OpenSSL gem with flags that point to the core/openssl Habitat package.
=> Fix windows plan

.buildkite/build-test-omnibus.sh
Updating the builders after removing Macos temporarily. Since the esoteric builders array was null, it was causing a silent failure further down which resulted in nothing being built or tested in the AdHoc pipeline.
=> Testing for what broke adhoc

habitat/plan.ps1
We had an issue with the existing plan not pulling in openssl correctly and the chef would die during testing. This PR solves that. It's a backport of [This](https://github.com/chef/chef/pull/14655)
One curious issue in testing was that the running plan tried to enumerate test files in a pretend yum repo (located under /spec/functional/assets/yumrepo-empty) and was dying due the windows filename length limitations. I opted to temporarily add/remove long filename support to overcome that rather than renaming those files as we had done in previous instances of that error.
=> Backporting Hab Plan

.expeditor/habitat-test.pipeline.yml, Gemfile, Gemfile.lock, habitat/plan.ps1, habitat/tests/spec.ps1, habitat/tests/test.sh, spec/functional/shell_spec.rb, spec/integration/client/open_ssl_spec.rb, spec/integration/solo/solo_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb, spec/unit/provider/package/rubygems_spec.rb
In order to support a Habitat-only pipeline, tests need to be expanded to run against habitat.
Windows tests will be broken until the next push of a hab package so there are currently prevented from triggering errors.
CHEF-15034
=> Habitat test expansion

lib/chef/node/mixin/immutablize_array.rb, lib/chef/node/mixin/immutablize_hash.rb
This PR updates the immutablize mixins for Array and Hash by incorporating additional methods inspired by ActiveSupport.
This change is necessary to facilitate the upcoming licensing integration (#14467), which utilizes the [`chef-licensing`](https://rubygems.org/gems/chef-licensing) library that depends on ActiveSupport. By aligning our mixins with ActiveSupport conventions, we ensure smoother integration and compatibility.
CHEF-11803: Infra 19 available for Free-tier, trial and commercial users in non-airgapped environment
=> Add ActiveSupport-like methods to Immutablize Mixins for Array and Hash

Gemfile.lock
Instead of `bundle update --conservative` this is running a `bundle install` on the `install_if` Gemfile
```sh
❯ bundle install
Resolving dependencies........
Using public_suffix 5.0.1
Using aws-partitions 1.958.0
Using debug_inspector 1.1.0
Using concurrent-ruby 1.2.2
Using rack 2.2.6.4
Using webrick 1.8.1
Using diff-lcs 1.5.0
Using iniparse 1.5.0
Using ruby2_keywords 0.0.5
Using tty-color …
```
=> Commit the Gemfile.lock from fixed Gemfile

Gemfile.lock, omnibus/Gemfile.lock, omnibus/config/projects/chef.rb
There are errors on windows and mac os 11 arm 64 platforms on chef-18
Windows is failing due to regex mis match for windows gem platform name for chef , so modified that to match it with the gem name. since it expects folder suffix to be universal-mingw-ucrt while the available match is for x64-mingw-ucrt
Mac os 11 arm64 is failing due to psych and stringio gem code sign , lowering the versions of these two given the success build
adhoc run against this pr : https://buildkite.com/chef/chef-chef-chef-18-validate-adhoc/builds/165#_
=> Fix for mac 11 arm64 and windows platforms for chef-18 adhoc build

.buildkite/build-test-omnibus.sh, .expeditor/adhoc-canary.omnibus.yml, .expeditor/config.yml, .expeditor/release.omnibus.yml, omnibus/kitchen.yml
As we come to the final builds of Chef-18, we need to do some cleanup to ensure we are testing and building on supported platforms using current toolsets. I updated some of the kitchen testers to more modern versions and generally removed anything to do with Windows 2012 - it has not been supported by anyone for a while now.
=> Updating builders and testers

Gemfile.lock, omnibus/Gemfile.lock
`bundle update --conservative` not included here, but also there aren't extra gem updates.
Webrick 1.8.1 has a CVE in it. Updating here to overcome that.
https://nvd.nist.gov/vuln/detail/CVE-2024-47220
=> Updating Webrick to overcome a CVE

lib/chef/application.rb, lib/chef/context.rb, lib/chef/formatters/doc.rb, lib/chef/licensing_config.rb, spec/unit/context_spec.rb
This PR implements the simpler solution for the #14663 by checking the test-kitchen context using the env variable which was set by the test-kitchen during the kitchen run.
=> Checking the Test-kitchen context with env variable

lib/chef/provider/package/rubygems.rb, spec/support/platform_helpers.rb
* force rubygems/package to be required if `:new` is an empty method - A change to
[rubygems_ext.rb](https://github.com/rubygems/rubygems/commit/d478ec403ff5dc5c1205eb6948029816bbdd6f12#diff-dd13cb568c0fc396fbad7bc3665465e0fc81ce91042afc2d0d537d08a31c649eR437) as of at least bundler 2.5.23 broken the autoloading of `Gem::Package` due to an empty `Gem::Package` already being declared.
* remove hab test debugging
=> GitHub Actions test cleanup

spec/integration/client/open_ssl_spec.rb, spec/spec_helper.rb
Addresses
OpenSSL check breakage on [Integration windows-2019](https://buildkite.com/chef-oss/chef-chef-main-verify/builds/18409#01933f1d-4e71-477e-a0b9-91aad063cb47)
=> skip openssl version check unless adhoc (nightly) omnibus pipeline

lib/chef/application/base.rb, lib/chef/licensing.rb
Temporarily bypass licensing in kitchen until Progress solves this
Summary:
People need to get work done. Until progress figures out how they want licensing to work in their pipelines, let tests work.
Test Plan:
Tests pass.
=> Temporarily bypass licensing in kitchen until Progress solves this

kitchen-tests/kitchen.dokken.yml
Fix fedora-latest tests: install dnf
fedora-latest defaults to dnf5, and we need to install dnf4 libs to
keep Chef working.
=> Fix fedora-latest tests: install dnf

kitchen-tests/kitchen.dokken.yml
fedora-latest defaults to dnf5, and we need to install dnf4 libs to keep Chef working.
=> Fix fedora-latest tests: install dnf (#14710)

kitchen-tests/cookbooks/end_to_end/recipes/_snap.rb
`kitchen-tests` for `snap` are failing inconsistently in both VM and Docker in GitHub Actions. Trying on a local Hyper-V VM raised the possibility that this is just a timing issue. Doubled the sleep after start just in case.
=> Give snapd a bit more time to boot?

kitchen-tests/cookbooks/end_to_end/recipes/_snap.rb
Backport of kitchen-test tweak on `main` doubling the `sleep` for `_snap.rb` test.
=> Given snapd a bit more time to boot? (#14726)

.buildkite/build-test-omnibus.sh
Adding windows testers back in
=> Updating to add Windows builders back

kitchen-tests/cookbooks/end_to_end/recipes/_snap.rb, kitchen-tests/cookbooks/end_to_end/recipes/linux.rb
* `service "snapd"` wasn't generally ready after the original 5 second timeout. Swap static sleep for 2 retries with a 15 second interval.
* uncomment `_tests` recipe since the UTF-8 error should be addressed.
=> Reenable _tests, allow snap retry on problem calls

lib/chef/cookbook/remote_file_vendor.rb
=> [Chef18][RemoteFileVendor#get_filename] only do one files_for

kitchen-tests/cookbooks/end_to_end/recipes/_snap.rb, kitchen-tests/cookbooks/end_to_end/recipes/linux.rb
retry on the problematic `snap_package` lines
Backport of #14731
=> [Chef-18 Backport] Reenable _tests to trigger GA (#14731)

lib/chef/cookbook/remote_file_vendor.rb
`#files_for` can be expensive, only do it once.
=> [RemoteFileVendor#get_filename] only do one files_for

spec/functional/resource/cookbook_file_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb, spec/support/shared/functional/file_resource.rb
The file resource tests behave unpredictably on some VM's running Windows 11 or later while the code runs correctly on a local physical machine. Here we comment out the offending tests. 
(Note from @tpowell-progress: Verified that this works locally on two of my Windows 11 machines as well, both 22H2 and 23H2, only consistently reproducing on a Buildkite VM hosted on Azure)
=> Updating Windows file resource tests

spec/spec_helper.rb
OpenSSL version for adhoc builds not guaranteed to be consistent as of Chef 19, due to Habitat build becoming primary release route.
=> disable openssl check unless hab test

.buildkite/build-test-omnibus.sh
we need to modify these values so that we can cut a new release for chef-18 pipeline. 
This solves the issue where the create build record, and promote to current pipeline steps are missing on the validate release pipeline.
=> updating slug to correct chef-18 release pipeline

.github/workflows/kitchen.yml, kitchen-tests/kitchen.exec.macos.yml
=> Remove macos-12 from GA kitchen-tests

omnibus/config/projects/chef.rb
chef-18 omnibus build is failing (https://buildkite.com/chef/chef-chef-main-validate-adhoc/builds/1908) to find chef log dll since it expects folder suffix to be `x64-mingw-ucrt` while the available match is for `universal-mingw-ucrt`. This change updates the glob to `chef-[0-9]*-mingw-ucrt/ext/win32-eventlog/chef-log.dll` so it matches both suffixes.
adhoc run: https://buildkite.com/chef/chef-chef-chef-18-validate-adhoc/builds/143
=> update glob string for chef-log.dll

spec/functional/resource/cookbook_file_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb, spec/support/shared/functional/file_resource.rb
Backporting this to Main branch - https://github.com/chef/chef/pull/14746.
The file resource tests behave unpredictably on some VM's running Windows 11 or later while the code runs correctly on a local physical machine. Here we comment out the offending tests.
(Note from @tpowell-progress: Verified that this works locally on two of my Windows 11 machines as well, both 22H2 and 23H2, only consistently reproducing on a Buildkite VM hosted on Azure)
=> [Backport] - Updating Windows 11 testing

.expeditor/build-docker-images.sh, Dockerfile
This fixes the docker container error when loading: unable to load libcrypt.so.2 due to newer package used at time of build that is not available in older OS versions.
#14760 
- [] All new and existing tests passed.
=> [chef-18] Fix docker container

.github/workflows/kitchen.yml
=> [Backport] remove EOL'd OS docker tests

.buildkite/build-test-omnibus.sh, .expeditor/adhoc-canary.omnibus.yml, .expeditor/release.omnibus.yml
Windows 2012* should be retired and now adhoc builds are failing with
```
Failure/Error: win32certstore.add_pfx(tempfile, password, CRYPT_EXPORTABLE)
--
  |  
  | SystemCallError:
  | The specified network password is not correct. - Unable to Add a PFX certificate.
```
Remove the testers.
=> Remove 2012 testers from bk adhoc

.expeditor/scripts/verify-plan.ps1, .expeditor/scripts/verify-plan.sh, habitat/plan.sh
The plan.sh is failing in the verify pipeline. The problems stemmed from an update that Hab took recently that requires us to specify a "refresh channel" to ensure that packages are pulling from the correct source
=> Updating the plan file

kitchen-tests/kitchen.dokken.yml, kitchen-tests/kitchen.linux.ci.yml
In docker images (VMs don't exhibit this)
Debian 11 `install` is in `/usr/bin/install`
Debian 12 `install` is in `/bin/install`
No references to this in the `ruby/json` repo and couldn't find hard reference in 2.7.6 of json to indicate that this is a common problem.
=> try symlink for install

.buildkite/build-test-omnibus.sh, .expeditor/scripts/bk_container_prep.sh, .expeditor/scripts/omnibus_chef_build.ps1, .expeditor/scripts/omnibus_chef_build.sh, .expeditor/scripts/prep_and_run_tests.ps1, .expeditor/scripts/prep_and_run_tests.sh
Why in the world are we still using chef-foundation when the entire project should be Hab based?
=> Removing Chef-Foundation from the builds

lib/chef/dsl/chef_vault.rb
Obvious fix; When the using the `chef_vault_item()` helper the method produces an `undefined method '[]' for nil:NilClass` error if the `chef-vault` attribute key is undefined.
=> Fix for error when 'chef-vault' attr undefined

Gemfile.lock
https://github.com/chef/mixlib-shellout/pull/254 had  fixes related to Target mode. We are pulling those in here with version 3.3.6
```
bundle update mixlib-shellout --conservative
Resolving dependencies........................
Using minitest 5.25.1
Using aws-partitions 1.1001.0
Using tty-screen 0.8.2
Using uri 0.13.1
Using json 2.7.6
Using logger 1.5.3
Using tty-color 0.6.0
Using tty-cursor 0.7.1
Using wisper …
```
=> Bump mixlib-shellout to 3.3.6 to pull in Target mode fixes

lib/chef/compliance/default_attributes.rb, lib/chef/compliance/runner.rb
This change fixes the issue where the compliance report was being reported to standard output when the quiet mode was set to true. Removing `cli` from the reporter list when quiet mode is set to true fixes this issue. 
Before applying the fix:
```
Chef Infra Client, version 19.0.61
Patents: https://www.chef.io/patents
Infra Phase starting
Resolving cookbooks for run list: ["sample-compliance-cookbook@0.1.7"]
Synchronizing cookbooks:
- sample-compliance-cookbook (0.1.7)
Installing cookbook gem dependencies:
Compiling cookbooks...
Loading Chef InSpec profile files:
- sample-compliance-cookbook::custom-resource (0.1.0)
- sample-compliance-cookbook::profile-sensitive (0.1.0)
Loading Chef InSpec input files:
Loading Chef InSpec waiver files:
Converging 0 resources
Running handlers:
Running …
```
=> fix compliance phase reporting when quiet mode is set to true

Gemfile, Gemfile.lock, omnibus/Gemfile, omnibus/Gemfile.lock
See https://github.com/chef/ohai/pull/1860 and https://github.com/ffi/ffi/issues/1139
```ruby
❯ bundle install
Resolving dependencies......
Using aws-partitions 1.981.0
Using rack 2.2.9
Using uuidtools 2.2.0
Using webrick 1.8.2
Using diff-lcs 1.5.1
Using iniparse 1.5.0
Using parallel 1.26.3
Using racc 1.8.1
Using rainbow 3.1.1
Using ruby-progressbar 1.13.0
Using unicode-display_width 2.6.0
Using json 2.7.2 …
```
=> Limit ffi to 1.17.0 max via Ohai bump.

knife/lib/chef/utils/licensing_handler.rb
In https://github.com/chef/chef/pull/14669, we have introduced a warning for non-licensed users when they run the knife bootstrap command to familiarise them with the chef-infra-19 licensing. They can get rid of it by activating a license.
This issue happens when the licensing service hits the `v1/listLicenses` API to determine whether it is a global or on-prem local licensing service. This will work fine on the global one, but it will raise an exception when the user uses an air-gapped environment and doesn't have the local licensing server URL set in the env variable(`CHEF_LICENSE_SERVER`).
This PR will fix the connection issue with the global licensing service on airgapped envs.
=> [CHEF-18381] Fixed the issues with knife bootstrap failing on the airgapped envs

lib/chef/compliance/default_attributes.rb, lib/chef/compliance/runner.rb
This PR backports the changes from https://github.com/chef/chef/pull/14779 into chef-18. Fixes the issue where the compliance report was being reported to standard output when the quiet mode was set to true. Removing cli from the reporter list when quiet mode is set to true fixes this issue.
=> [backport] quiet mode fix for compliance phase

lib/chef/resource/archive_file.rb, spec/unit/resource/archive_file_spec.rb
There is a bug in the current implementation of archive_file which causes it to lock the compressed file for remainder of the chef-client run. This prevents you from deleting a compressed file after extracting it within the same execution.
The bug stems from incorrect usage of the Archive::Reader API. When opening a file using open_filename, you need to explicitly close it again afterwards to release the lock that your Ruby process holds on the compressed file.
=> Release file handles after extraction

lib/chef/resource/ohai.rb, spec/functional/resource/ohai_spec.rb
fix_automatic_attributes does some tricks like promote platform_version to a Chef::VersionString for easy comparisons; if ohai.reload is called it clobbers this and resets node['platform_version'] back to a normal string. this fixes that
=> ohai resource: ensure fix_automatic_attributes is called

lib/chef/cookbook/remote_file_vendor.rb
Calls to files_for can be expensive on cookbook segments with lots of files, and really only makes sense when you're needing to iterate over manifest records. In `get_filename`'s case we're not looking for a list of manifest records, just a single manifest record. By using `manifest_records_by_path`, the cost of finding the manifest record in the segment goes from `O(files)` to `O(1)`.
=> [RemoteFileVendor#get_filename] Do O(1) search for filename

lib/chef/provider/package/dnf/dnf_helper.py
When attempting to remove a package, the `whatinstalled` command is run in the helper to run a `dnf` query to check what installed package `provides` the subject.
Usually `provides` is the package **name** (according to [the docs](https://docs.chef.io/resources/dnf_package/#properties) it always is, with the resource property `package_name`), but it does not **have to be**.
As long as there is *any* available package that has the same name as `provides`, everything works just fine - `whatinstalled` will report that the package is not installed. However, if there is no *available* package named `provides`, then `whatinstalled` may report a different package  that provides `provides`.
The **availability** constraint is important, because `dnf-plugin-versionlock` makes some packages …
=> dnf: ignore sack excludes in 'whatinstalled'

spec/functional/resource/registry_spec.rb
Use `instance_method`/`define_method` to save / restore the implementation of `scrub_values` in `Chef::Resource::Registry` to minimize leakage into other tests/classes.
=> Use instance_method / refine_method to patch Chef::Resource::Registry

kitchen-tests/cookbooks/end_to_end/recipes/_snap.rb, lib/chef/provider/package/snap.rb
If `case result["result"]["status"]` results in `"Abort", "Hold", "Error"` then the original code was raising `result`, which is a hash and results in the error: 
```
[2025-02-19T19:51:56+00:00] FATAL: TypeError: snap_package[hello] (end_to_end::_snap line 9) had an error: TypeError: exception class/object expected
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-19.0.87/lib/chef/provider/package/snap.rb:226:in `raise'
```
Adding the following to keep Ubuntu 18.04 working for now
```ruby
snap_package "core" do
action :install
channel "stable"
retries 2
retry_delay 15
end
```
=> raise a string instead of a hash object, patch 18.04 snap

Gemfile, Gemfile.lock, chef.gemspec, knife/knife.gemspec
Constraining FFI to prevent loading 1.17.x which are broken
I have used --conservative
$ bundle update --conservative ffi
Fetching https://github.com/chef/rest-client
Fetching https://github.com/chef/ohai.git
Resolving dependencies.....
Fetching public_suffix 6.0.1
Fetching minitest 5.25.1
Fetching concurrent-ruby 1.3.4
Installing minitest 5.25.1
Installing concurrent-ruby 1.3.4
Installing public_suffix 6.0.1
Fetching ffi 1.16.3
Using wmi-lite 1.0.7
Fetching aws-eventstream 1.3.0
Installing ffi 1.16.3 with native extensions
Installing aws-eventstream 1.3.0
Fetching aws-partitions 1.1001.0
Installing aws-partitions 1.1001.0
Fetching jmespath 1.6.2
Installing jmespath 1.6.2
Using …
=> Updating ffi support

chef-utils/README.md
Unlike everything else in super_family that's `_based?`, fedora is
`_derived?` - but the docs still said `_based?`.
I'd fix the code, but honestly, people probably use this so I'll just
fix the docs.
=> Fix chef-utils README

lib/chef/provider/package/dnf/dnf_helper.py
Backport of #14821
Summary:
When attempting to remove a package, the `whatinstalled` command is run in the helper to run a `dnf` query to check what installed package `provides` the subject.
Usually `provides` is the package **name** (according to [the docs](https://docs.chef.io/resources/dnf_package/#properties) it always is, with the resource property `package_name`), but it does not **have to be**.
As long as there is *any* available package that has the same name as `provides`, everything works just fine - `whatinstalled` will report that the package is not installed. However, if there is no *available* package named `provides`, then `whatinstalled` may report a different package  that provides `provides`.
The **availability** constraint is important, because `dnf-plugin-versionlock` …
=> [Chef18] dnf: ignore sack excludes in 'whatinstalled'

.github/workflows/kitchen.yml, Gemfile, Gemfile.lock, kitchen-tests/cookbooks/end_to_end/recipes/_chef_gem.rb, kitchen-tests/kitchen.dokken.yml, kitchen-tests/kitchen.linux.ci.yml
Per https://www.ruby-lang.org/en/news/2024/03/21/rce-rdoc-cve-2024-27281/
Affected versions:
* Ruby 3.0.6 or lower
* Ruby 3.1.4 or lower
* Ruby 3.2.3 or lower
* Ruby 3.3.0
* RDoc gem 6.3.3 or lower, 6.4.0 through 6.6.2 without the patch versions (6.3.4, 6.4.1, 6.5.1)
Adding the fix for 3.1.6 was unnecessary and is complicating the dependency resolution with AWS gems.
=> [Backport 18] Remove rdoc since 3.1.6 has patch version already

lib/chef/cookbook/metadata.rb
=> [Chef18][Metadata#recipes_from_cookbook_version] Use end_with?

kitchen-tests/kitchen.dokken.yml, kitchen-tests/kitchen.exec.macos.yml, kitchen-tests/kitchen.exec.windows.yml, kitchen-tests/kitchen.linux.ci.yml
`appbundle-updater` will receive updates in `main` (versions 19.0...) to support hab, but will potentially break chef-18 CI, so pin chef-18 to the `1.0.x` versions.
=> Pin appbundle-updater gem install to ~> 1.0.36 to avoid hab version

lib/chef/cookbook_version.rb
String comparison instead of Regexp
=> [CookbookVersion] Use end_with?

lib/chef/provider/registry_key.rb, lib/chef/resource/registry_key.rb, spec/functional/resource/registry_spec.rb, spec/unit/provider/registry_key_spec.rb
Per discussions with the customer who opened the ticket and reasoning about the nature of registry keys and values, it was determined that the more surprising and error prone behavior was to report all values within a key, regardless of change. Switching the default due to this.
=> Reverse the default for only_record_changes

lib/chef/provider/registry_key.rb, lib/chef/resource/registry_key.rb, spec/functional/resource/registry_spec.rb, spec/unit/provider/registry_key_spec.rb
Per discussions with the customer who opened the ticket and reasoning about the nature of registry keys and values, it was determined that the more surprising and error prone behavior was to report all values within a key, regardless of change. Switching the default due to this.
=> [Backport 18] Reverse the default for only_record_changes 

.github/workflows/kitchen.yml
plus trivial PR for minor version bump
Remove EOLed Ubuntu 18.04 from CI kitchen-tests as a trivial change to bump minor version for 19 RC2
=> Remove 18.04 kitchen tests from main as cleanup

cspell.json, lib/chef/resource/apt_repository.rb, spec/unit/provider/apt_repository_spec.rb
If it is used, it will avoid using the deprecated apt-key command.
Fixes: #13168
Add support for a `signed_by` property for apt_repository. 
If true, and a key is supplied, it will install the key in a repo-specific keyring, and reference that in the Signed-By option. 
If a string, it will pass that string to the Signed-By option. 
I'm not sure what the behavior should be if signed_by is a string, and a key is also supplied. Currently it will install the key in a repo-specific location, but use the value of the string in the signed-by field. 
Other options for the case where key and signed-by are both specified could be:
1. install the key in /etc/apt/trusted.gpg.d, and use signed-by as is
2. try to interpret the first entry (comma seprated) as a file path, and install the key at that …
=> feat: Support Signed-By option for apt repository

knife/lib/chef/knife/supermarket_share.rb
in case of same cookbook version exists in private supermarket in getting failed to delete tmp dir fixed the exit case and now no exception is raised in case same cookbook shared twice
=> Knife supermarket share error when cookbook exists

lib/chef/util/powershell/ps_credential.rb, spec/unit/util/powershell/ps_credential_spec.rb
The default ruby implementation of inspect outputs the @'d variables in plaintext, which is unfortunate because this includes the plaintext credential.  Found out when I logged it.... oops!  This resolves that by only showing the username in the .inspect output.
Note that to_s and to_text both leak a hashed password - I haven't looked into where the seed is for that, but that's probably also not ideal.  However, the way this object is currently used requires a bigger refactor to remove that, and it's at least not plaintext
=> Chef::Util::Powershell::PSCredential leaks plaintext on .inspect

Gemfile, Gemfile.lock, chef.gemspec
The current build config loads mixlib-log-3.2.0. This version is incompatible with Ruby 3.0 which we're using on AIX only. This update locks 3.1.1 for all platforms
=> [Chef-18] Updating for Mixlib-Log

.buildkite/build-test-omnibus.sh, .expeditor/release.omnibus.yml, Gemfile.lock
Since mac 11 is old we are deprecating it and also making mac 12 as builder . along with this change picked latest version of omnibus-buildkite-plugin
=> removing mac11 from pipeline as its EOL and make 12 as builder

Gemfile.lock, chef.gemspec, knife/spec/tiny_server.rb, spec/tiny_server.rb
pulling an update forward from chef-18 to update cherf-zero and rack
$ bundle update --conservative rack
Resolving dependencies...
Resolving dependencies...
Using rack 3.1.12 (was 2.2.10)
Using chef-zero 15.0.17 (was 15.0.11)
Fetching inspec-core 7.0.38.beta
Installing inspec-core 7.0.38.beta
Fetching inspec-core-bin 7.0.38.beta
Installing inspec-core-bin 7.0.38.beta
Bundle updated!
=> updating rack and chef-zero in main

Gemfile.lock, chef.gemspec, lib/chef/provider/execute.rb, lib/chef/resource/execute.rb
This is the first diff needed to add support for cgroupsv2. The code will be in mixlib-shellout, but we need to add this attribute first.
Output from `bundle update --conservative mixlib-shellout`:
```
Resolving dependencies....
Using minitest 5.25.1
Using uri 0.13.1
Using tty-color 0.6.0
Using wisper 2.0.1
Using aws-partitions 1.1001.0
Using json 2.7.6
Using logger 1.5.3
Using tty-cursor 0.7.1
Using tty-screen 0.8.2
Using …
```
=> Add cgroup attribute to execute module

habitat/x86_64-windows/plan.ps1
When adding an environment with multiple paths, the correct syntax is to push each path via `Push-RuntimeEnv` rather than setting the entire semi-colon delimited value with `Set-RuntimeEnv`. This will work fine when using the package directly ala `hab pkg exec chef/chef-infra-client` but it will break a build when using this package as a dependency. The build program does some path parsing magic when reassembling the paths for a parent package which breaks with a multivalued variable.
NOTE: this does make me think that we should have some logic in habitat that would fail a build if it sees you are trying to set multiple paths with `Set-RuntimeEnv`.
=> fix RUBY_DLL_PATH setting in hab plan

cspell.json, habitat/plan.ps1
Under certain scenarios, running the chef-client as part of a hab package (hab pkg exec chef...)  results in the chef-client throwing a Powershell.dll missing error. This error is erroneous. The real culprit is missing MSVC2015 libraries. The existing command of Set-RuntimeEnv had the effect in comes cases of truncating the runtime path resulting in the error. Here we explicitly PUSH the updated path on to the RUBY_DLL_PATH.
Forward ported from #14914
=> [Port] Updating Hab paths for openssl

lib/chef/action_collection.rb
after hook resource skipped cause FATAL error when current record is nil and cause entire CDV fail (even tho tests passed successfully). This is ruby fatal error.
when running CDV for cinc 18.x and 19.x , after hook resource skipped with current record is nil will cause ruby FATAL error because it attempted to set something not exist
```
2024-08-28 22:45:05 +0000 resource_skipped hook called for execute[test.sh] with action [:run] and conditional #<Chef::Resource::Conditional:0x00007fd770528c18>
#<Chef::Resource::Conditional:0x00007fd770528c18 @positivity=:only_if, @command_opts=nil, @command=nil, @block=#<Proc:0x00007fd770528ab0 /etc/cinc/local-mode-cache/cache/cookbooks/test/recipes/build.rb:52>, @block_given=true, @parent_resource=<execute[test.sh] @name: "test.sh" @before: nil …
```
=> added nil check for current_record in resource skipped

.buildkite/hooks/pre-command
This change updates the buildkite pre-command hook at .buildkite/hooks/pre-command to conditionally include the artifactory configuration to the pipeline for pushing gems built via habitat.
=> update pre-command hook for pushing gem

kitchen-tests/cookbooks/end_to_end/recipes/_apt.rb, lib/chef/resource/apt_repository.rb
[The backport](https://github.com/chef/chef/commit/218772abb7f55099e4dea0dc8373e783a7c32702) of https://github.com/chef/chef/pull/14131 erroneously kept the namespace of `TargetIO` on the new code, which only exists in Chef 19 and beyond. This tests and then fixes that inclusion.
=> Trigger keyring code in kitchen-tests and fix accidental inclusion of TargetIO code

.buildkite/hooks/pre-command
reverts chef/chef#14917. `pre-command` hook does not seem to be working for the `gem-push` change. after consulting with @sean-simmons-progress , we are going to move this to the scripts for now to get this moving forward. once that is fixed, we can move this change back in to the hook.
=> revert: "update pre-command hook for pushing gem"

lib/chef/provider/registry_key.rb, lib/chef/resource/registry_key.rb, spec/functional/resource/registry_spec.rb, spec/unit/provider/registry_key_spec.rb
There are situations in which the `only_record_changes` option breaks idempotency, but it can't be reliably reproduced. Backing this out to take a different tactic with limiting the output.
[Original PR in main](https://github.com/chef/chef/pull/14767)
[Reversing the default to `true`](https://github.com/chef/chef/pull/14881)
=> Back out only_record_changes property

Gemfile, Gemfile.lock, chef.gemspec
mixlib-log 3.1.1 has a regression that was fixed in 3.1.2. 3.2.0 according to this PR https://github.com/chef/chef/pull/14905 it has issues with ruby 3.0 and aix. So bumping dep to < 3.2.0.
❯ sudo bundle update mixlib-log --conservative
Resolving dependencies...
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
stringio (>= 0)
Available/installed versions of this gem:
- 3.1.2
- 3.0.1.2
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
Using concurrent-ruby 1.3.5
Using minitest 5.25.5
Using aws-partitions 1.1048.0
Using jmespath …
=> [Chef-18] logger regression fix

.expeditor/config.yml
this is a value that tells expeditor to do things with packages and omnibus builds. This one in particular is apart of some logic for omnibus packages and yum/apt repo binary creation. 
this is going to be one of many configuration updates before we get this ready to be promoted via expeditor.
NOTE: Packages will still be available in Chef 19 - but they'll be hab-based RPM/Debs, not omnibus-based ones.
=> disabling this value

lib/chef/data_collector.rb, spec/unit/data_collector_spec.rb
Filtering the before property on the resource side broke idempotency, so I moved the filtering to the data collector side.
=> Filter before to match after for registry keys

lib/chef/resource/registry_key.rb
Add the `only_record_changes` property back to the `registry_key` resource, in case any users of 18.7.3 modified their recipes to use it. It will effectively be a no-op.
=> Add unimplemented property back

lib/chef/data_collector.rb, lib/chef/resource_reporter.rb, spec/unit/resource_reporter_spec.rb
This is a stop gap for an edge case that can hopefully be patched with a more reasonable solution of filtering the `:before` to match the `:after`
=> Truncate resource reporter :before to empty hash if over 500_000 bytes

cspell.json, lib/chef/resource/apt_repository.rb
Always make sure that keys installed with `signed_by true` are dearmored.
This is required for `apt` to see the keys inside `.gpg` files.
I fixes a regression #14942 introduced in #14131
=> fix: ensure apt_repository keys are always dearmored

.github/workflows/kitchen.yml, kitchen-tests/kitchen.linux.ci.yml
This seems to fix the kitchen flakiness issues.
=> Revert kitchen tests to run on Ubuntu 22.04 VMs

.github/workflows/kitchen.yml, cspell.json, lib/chef/resource/apt_repository.rb
Fixes: #14942
Also added setting of the kitchen vm tests to run on ubuntu 22.04 to stabilize builds.
Also disabled EOLed Ubuntu 18.04 as was done in #14891 as the tests are now consistently failing.
=> fix: ensure apt_repository keys are always dearmored (#14944)

.github/ISSUE_TEMPLATE/BUG_TEMPLATE.md
obvious fix
Closes https://github.com/chef/chef/issues/13966
=> Replace reference to ChefDK with Chef Workstation (obvious fix)

lib/chef/cookbook/cookbook_version_loader.rb
When Chef client enumerates files in the cookbook parent directory it should ignore all hidden directory entries for compatibility reasons. However if a link to a directory exists and it is broken, it is not evaluated as a directory but as a file, therefore being included in the top_path array.
When the broken link is passed to Find.find() it throws an exception and breaks the client execution.
* https://github.com/ruby/find/issues/18
- [ x] Bug fix (non-breaking change which fixes an issue)
=> fix: ensure load_all_files ignores broken links in the cookbook dir CHEF-1958

.expeditor/scripts/omnibus_chef_build.ps1, .expeditor/scripts/omnibus_chef_build.sh
We had been pulling our copy of Chef Foundation from the 'current' channel but that has been proven, lately, to be problematic. We are now pulling from the stable channel.
=> Updating the builders to pull from the stable channel

cspell.json, habitat/plan.sh
If I run `hab pkg exec chef/chef-infra-client/19.1.14/20250404144140 irb` and then `require "ffi-libarchive"`, I get an error that it is unable to load ffi-libarchive because libarchive cannot be found. With the change here, the require succeeds.
=> make sure the right paths get put in the native ffi gem runpath

lib/chef/resource/apt_repository.rb, spec/unit/provider/apt_repository_spec.rb
`keyring_key_is_valid` will return true even though the key does not exist.
The keyring_key_is_valid function will run the following:
```
$ gpg --no-default-keyring --keyring  /etc/apt/keyrings/ring.gpg --list-public-keys fingerprint
gpg: error reading key: No public key
$ echo $?
2
```
the `stdout none?` matcher will return true for this error and the key will be delcared "valid" even though it does not exist. This will cause the `not_if` block called from `install_key_from_keyserver_to_keyring` to skip the execute and the key will not be installed.
This updates the function so that it also checks the `exitstatus` of the `shell_out` and will return `false` when the status is not equal to 0.
#14943
=> Bug fix for apt_repository when creating a new keyring

post-bundle-install.rb, spec/integration/client/open_ssl_spec.rb, spec/spec_helper.rb
The ssl_env_hack.rb file that sets SSL_CERT_FILE to `cacert.pem` in Windows isn't getting loaded due to the reinstall of the `openssl` gem. Edit `post-bundle-install.rb` to fix.
* Patch constant SSL_ENV_CACERT_PATCH into all instances of
ssl_env_hack.rb
* Add test for constant that is defined in ssl_env_hack.rb.
* Add ssl_env_hack.rb during post-bundle-install to look for openssl.rb in lib path and gem hierarchies
due to reinstalling openssl gem
=> Add test of loading of ssl_env_hack.rb and fix.

lib/chef/resource/windows_task.rb
This is no longer relevant since the code has changed, plus Ruby 2.7 was dropped in #14260.
=> Obvious fix: remove stale TODO

spec/spec_helper.rb
Unit/Functional/Integration tests won't have a ruby with the ssl_env_hack on it.
=> Disable pre build tests for ssl hack

kitchen-tests/kitchen.linux.ci.yml
Refresh cache/metadata for Rocky Linux 9 to resolve failures on kitchen vm
=> Just a random attempt for rocky linux 9

habitat/plan.sh
We use appbundle-updater in kitchen tests to update installed habitat package of Infra client to a commit SHA. First bundle install is run to install the gems. Recently we added a [bug fix](https://github.com/chef/chef/pull/15038) related to `ffi` not loading when hab package is run. But this change had a side effect causing bundler no longer existing at `vendor/gems` directory of habitat package. Due to this appbundle-updater will fail to apply commit SHA to installed package. To fix it we tried modifying the script to use [packaged ruby's bundler directly ](https://github.com/chef/appbundle-updater/pull/120/files), but this even if it works without error fails to update the package. Found that it is due to how habitat environment sets up GEH_HOME and GEM_PATH to `vendor/bin` due to …
=> Add bundler to hab package's vendor/gems

.expeditor/config.yml
With omnibus and chef-foundation removed, the nightlies no longer mean anything in their current form. Temporarily disabling them in lieu of a future workflow.
=> Disable no-op omnibus nightlies that run

lib/chef/http.rb, lib/chef/http/basic_client.rb
When running run_external_test against chef-zero, we started to get errors about an undefined "Net < Protocol"
Why This Happens Specifically in [run_external_test](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)
The issue occurs specifically in the [run_external_test](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) framework because:
Different Load Order: When running external gems through [run_external_test](vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html), the load order of Chef components differs from standalone gem tests
Bundler …
=> Adding explicit loads for net/http

lib/chef/cookbook_version.rb, lib/chef/recipe.rb, spec/unit/cookbook_version_spec.rb, spec/unit/recipe_spec.rb
This uses the same underlying `from_hash` mechanism as YAML recipes, so the schemas are fundamentally the same.
(see main branch PR for discussion #15094 )
=> [Chef 18] Support JSON recipes

Gemfile.lock, chef.gemspec
Updating Chef-Zero to pull in an updated rack gem. < 3.1.12 has a CVE in it.
```
❯ bundle update --conservative chef-zero rack
Resolving dependencies....
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
stringio (>= 0)
Available/installed versions of this gem:
- 3.1.7
- 3.0.1.2
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
Using concurrent-ruby 1.3.5
Using minitest 5.25.5
Using aws-partitions 1.1048.0 …
```
=> Updating Chef-Zero

chef-config/lib/chef-config/exceptions.rb, chef-config/lib/chef-config/mixin/credentials.rb, chef-config/lib/chef-config/mixin/train_transport.rb, chef-config/spec/unit/credentials_spec.rb, spec/unit/train_transport_spec.rb
Enables sensitive credentials to be served from a HashiCorp Vault instance.
Any value inside the `credentials` file can be forwarded to a secrets provider by not providing a literal string, but a map instead:
```toml
sudo_password = {
secret = "/chef/sudo_password",
field = "password"
}
```
If the secrets provider returns a plain string, the `field` statement is not needed. Otherwise, it can be used to grab a specific field from the returned value via JMESPath syntax.
You can set a default secrets provider at the top-level of the credentials file. Currently, only `hashicorp-vault` is supported but has to be explicitly referenced for future compatibility. Parameters beyond `name` and `endpoint` match the ones from the [official HashiCorp vault gem](https://github.com/hashicorp/vault-ruby). …
=> Add support for secrets in credentials file

Gemfile, Gemfile.lock, chef.gemspec
We need to get uri updated to 1.0.3 to get past a CVE in 1.0.2. The main challenge is that it is a transient dependency from net-http. We are forcing the updated version in the Gemfile until net-http releases a new version that includes an update to uri
bundle update --conservative uri    
Resolving dependencies.....
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
stringio (>= 0)
Available/installed versions of this gem:
- 3.1.7
- 3.0.1.2
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
Using concurrent-ruby 1.3.5
Using minitest 5.25.5
Using aws-partitions 1.1048.0
Using …
=> Updating uri to 1.0.3

.buildkite/verify.pipeline.sh
pinning berkshelf to an older commit to get past broken verify pipeline builds.
=> temporarily pin berkshelf in verify

.expeditor/scripts/verify-plan.ps1, .expeditor/scripts/verify-plan.sh, Gemfile, Gemfile.lock, chef.gemspec
Chef-Zero has a transient dependency on Activesupport via it's dependency on oc-chef-pedant. What's been happening is that Windows nodes tend to load random versions of activesupport which may be susceptible to https://github.com/advisories/GHSA-2p68-f74v-9wc6 (7.0.8.6 is vulnerable). Here we force the version constraint to ensure a consistent experience across *nix and Windows nodes.
We updated the ruby-shadow block because some versions of bundler were allowing ruby-shadow to be installed on Windows.
We also updated the hab_origin in the testers to match the plan files.
$ bundle update --conservative activesupport
Resolving dependencies.....
WARN: Unresolved or ambiguous specs during Gem::Specification.reset: …
=> Forcing a version constraint for activesupport for CVE-2020-8165

Gemfile.aix.lock, Gemfile.lock
```sh
❯ bundle update --conservative thor
Resolving dependencies...
Using bigdecimal 3.1.9
Using concurrent-ruby 1.3.5
Using connection_pool 2.5.3
Using mutex_m 0.3.0
Using drb 2.2.3
Using minitest 5.25.5
Using aws-partitions 1.1048.0
Using bundler 2.3.27
Using uuidtools 2.2.0
Using rack 3.1.16
Using unf_ext 0.0.8.2
Using webrick 1.9.1
Using diff-lcs 1.5.1
Using parallel 1.26.3 …
```
=> bundle update --conservative thor to < 1.5.0

cspell.json, habitat/plan.ps1, lib/chef/resource/archive_file.rb
Include libarchive in DLL search path for windows habitat package which otherwise throws error `ffi-libarchive could not be loaded, libarchive is probably not installed on system, archive_file will not be available`
Additional error backtrace:
```
hab pkg exec chef/chef-infra-client irb
irb(main):001:0> require "ffi-libarchive"
C:/hab/pkgs/chef/chef-infra-client/19.1.58/20250722210356/vendor/gems/ffi-1.17.2-x64-mingw-ucrt/lib/ffi/dynamic_library.rb:94:in `load_library': Could not open library 'libarchive.so.13': Failed with error 126: The specified module could no (LoadError)
.
Could not open library 'libarchive.so.13.dll': Failed with error 126: The specified module could not be found.
.
Could not open library 'libarchive.13': Failed with error 126: The specified module could not be …
```
=> Fix ffi-libarchive load error from habitat package on windows

kitchen-tests/cookbooks/end_to_end/recipes/_apt.rb, kitchen-tests/test/integration/end-to-end/_apt.rb, lib/chef/resource/apt_repository.rb
Currently, when having multiple apt_repository resources that use the same key url (e.g. Debian bookworm, bookworm-updates and bookworm-backports), only the first apt_repository resource that gets executed will have its key imported into a keyring.
The other apt_repository resources using the same key will not get their keyrings imported, as the remote_file is up to date.
By notifying the import if the key does not exist, we work around this problem.
I also removed the `:delete` notification of the keyring file when the `remote_file` resource changes, as it caused unwanted deletes of the actual keyring file _after_ the `gpg --import`.
This doesn't break anything, as `gpg --import` does not require the keyring file to be missing, it just imports the new key in the same file if it exists.
=> fix: multiple apt_repos with same key url should be signed-by

chef-bin/bin/chef-shell, lib/chef/shell.rb
`irb` 1.14.x included in ruby 3.4 also includes these updates:
- `save-history` extension was moved to core irb. this change meant that there is no `save-history` to load at that path and what we need is now included by default. https://github.com/ruby/irb/pull/613
- we can't modify aliases anymore, but `irb` now provides apis to override commands by registering them again. https://github.com/ruby/ruby/blob/d2930f8e7a5db8a7337fa43370940381b420cc3e/lib/irb/command.rb#L16-L21
https://docs.ruby-lang.org/en/3.3/IRB/Command.html
=> fix irb errors in functional tests

lib/chef/chef_fs/file_system/repository/chef_repository_file_system_cookbook_dir.rb, lib/chef/chef_fs/file_system/repository/chef_repository_file_system_cookbook_entry.rb
This is kind of a "Facebook-scale" issue, but when you have *lots* of cookbooks and files, creating big arrays of child objects that are checked only for non-zero lengths can add whole seconds to Chef Zero cookbook resolution. Instead of creating the big arrays, simply detect if there's at least one child and return accordingly.
=> [ChefRepositoryFileSystemCookbookEntry] Add `any_children?` method

.github/workflows/kitchen.yml
Latest chef-workstation release with latest test-kitchen breaks exec driver used by windows and macos kitchen tests
- [] Bug fix (non-breaking change which fixes an issue)
=> fix chef-workstation install

.expeditor/habitat-test.pipeline.yml, .expeditor/scripts/habitat-test.ps1, .expeditor/scripts/habitat-test.sh, habitat/tests/spec.ps1, spec/functional/resource/git_spec.rb
This PR fixes a bunch of stuff in habitat/verify pipeline
- The #15301 PR missed the `-E` flag when executing the linux script which is making the installation fail for infra client package in our tests. 
- Missing CHEF_LICENSE_SERVER env was making the tests fail with licensing errors.
- Fixed silent test failures on Windows runners (spec.ps1 in habitat/tests was the culprit)
- Fixed failing tests for git in windows. details in commit message: https://github.com/chef/chef/pull/15303/commits/0e17a4e6860b03ba5837a6e3c694c3209a383e91
Passing build: https://buildkite.com/chef-oss/chef-chef-main-habitat-verify/builds/13
=> fix errors on habitat/verify

lib/chef/property.rb
instance_variable_name creates objects, and they can add up when you call it a million times or more.
=> [Chef::Property][get_value,set_value,value_is_set?] Only call instance_variable_name once
