chef/chef

MAINTAINERS.md
This adds me (martinisoft) as a maintainer for FreeBSD officially. From what I can gather, this was informally decided upon with past Chef Developer meetings in IRC and as far as I know I already have commit bit with the freebsd cookbook.
=> Add martinisoft to missing FreeBSD platform

MAINTAINERS.md
Per conversation today in #chef-hacking I am moving myself to the FreeBSD Lieutenants list to help guide decisions with FreeBSD releases.
=> Update martinisoft to FreeBSD Lieutenant

lib/chef/provider/package/macports.rb, lib/chef/resource/macports_package.rb, spec/unit/provider_resolver_spec.rb
macports needs to provide macports_package to `darwin`, not `mac_os_x`. `mac_os_x` is the platform, `darwin` is the OS.
This resolves #2691. 
@jaymzh will do the merge so it's under his CCLA.
=> correct filters for MacPorts package provider

spec/functional/resource/execute_spec.rb
Added a check to see how long executing sleep 600 with a timeout of 0.1 takes, so it is broken on windows. Disable the broken test.
These can be renabled with our next release of mixlib-shellout
Knowing 10 mins are being added to each run is annoying.
cc @opscode/client-engineers
=> Fail execute test if it takes too long

CHANGELOG.md, lib/chef/mixin/shell_out.rb, spec/unit/mixin/shell_out_spec.rb
if we don't force LANGUAGE then package installs will still fail, etc
due to taking precedence over even LC_ALL, force LANG as well for
good measure which should cover all the bases hopefully.
fixes #2695
=> add forcing of LANG and LANGUAGE env vars

CHANGELOG.md, lib/chef/resource/chef_gem.rb, spec/unit/resource/chef_gem_spec.rb
the default is still the same, but will warn that users should start
being explicit.  setting compile_time false will become the new
default in chef-13 and is encouraged to avoid the compile_time arms
race.
=> add a compile_time flag to chef_gem resource

CHANGELOG.md, lib/chef/dsl/recipe.rb, lib/chef/resource.rb, lib/chef/resource_builder.rb, spec/unit/recipe_spec.rb, spec/unit/resource_builder_spec.rb, spec/unit/resource_spec.rb
Turns the 3694 warning into a debug message if the prior resource is
identical to the current resource.  Suggestion for opscode/chef-rfc#76
=> Skip 3694 warnings on trivial resource cloning

lib/chef/platform/provider_priority_map.rb, lib/chef/provider/package/macports.rb, lib/chef/resource/macports_package.rb
The MacPorts provider should provide package so that you can change the
precedence in provider mappings, with a statement like this:
Chef::Platform::ProviderPriorityMap.instance.priority(
:package, Chef::Provider::Package::Macports, :os => 'darwin'
)
This resolves #2690. 
@jaymzh will do the merge so it falls under his CCLA.
=> Macports provider - provide package

lib/chef/provider/user/dscl.rb, spec/unit/provider/user/dscl_spec.rb
Some system users don't have salts. This exception is fixed by this
commit:
NoMethodError: undefined method `size' for nil:NilClass
@jaymzh will merge this so it falls under his CCLA.
=> OS X user provider - fix exception if no salt is found

lib/chef/provider/user/dscl.rb, spec/unit/provider/user/dscl_spec.rb
We need to compare with the UID, not a GUID. So we need to map the
correct field for comparison.
Also fix a bug in determining used uids.
This fixes this exception when the specified uid is actually in use by the
correct user:
Chef::Exceptions::RequestedUIDUnavailable: uid 48 is already in use
This resolves #2667.
@jaymzh will do the merge so it falls under his CCLA.
=> bugfix dscl provider

CHANGELOG.md, lib/chef/node/attribute.rb, spec/unit/node_spec.rb
In 12.0.0 we introduced a cache for the merged attributes for the
top-level node attribute keys.  This fixes this so that node['foo']
and node[:foo] are not cached separately.  This also showed up in bugs
as issues between node['foo'] access and node.foo access because
node.foo is translated into node[:foo].
fixes #2700 #2712 #2745
=> deep_merge_cache fixes for bugs in 12.0.0

CONTRIBUTING.md, README.md
This should help people figure out the appropriate place to open
an issue so they don't have to experience opening an issue to only have
it be closed and then told to reopen it somewhere else.
=> Clarify where issues should be filed

lib/chef/platform/query_helpers.rb, lib/chef/win32/version.rb
This seems to stop ruby from seg faulting on Windows when we use ruby 2.x
@adamedx might be able to explain more why as it was his idea to try this.
cc @opscode/client-engineers
=> Removing ole_initialize/uninitialize

lib/chef/chef_fs/data_handler/user_data_handler.rb
@jkeiser & I are working on compatibility for Cheffish with Enterprise chef.
Add support for user full name string as display_name to Chef::ChefFS::DataHandler::UserDataHandler.
=> Add display_name handling to Chef::ChefFS::DataHandler::UserDataHandler

lib/chef/application/client.rb
This fixes [2769](https://github.com/opscode/chef/issues/2769).
Chef-client defaults to auto if not specified in the client.rb.
=>  Update chef-client help with auto.

lib/chef/provider/powershell_script.rb, spec/functional/resource/powershell_spec.rb
1.) You can't set $LASTEXITCODE directly, doing so creates a local
variable. I've changed it to $global:LASTEXITCODE
2.) $LASTEXITCODE can be $null. No longer using `-ne 0` to compare
This should resolve Issue #2348 
cc @btm @smurawski @ksubrama
=> Fix up powershell script

lib/chef/data_bag_item.rb, spec/unit/chef_fs/file_pattern_spec.rb, spec/unit/data_bag_item_spec.rb
This fixes a warning in Ruby 2.2 about circular argument references in data_bag_item.rb
See this ruby issue for more details: https://bugs.ruby-lang.org/issues/10314
=> FIX data_bag_item.rb:161: warning: circular argument reference - data_bag

lib/chef/guard_interpreter/resource_guard_interpreter.rb, lib/chef/mixin/why_run.rb, lib/chef/resource/execute.rb, spec/functional/resource/execute_spec.rb, spec/unit/resource/execute_spec.rb
The fix for https://github.com/opscode/chef/issues/2694.  The idea is that we're now marking guard resources as able to converge even during why_run mode.
\cc @opscode/client-core @opscode/client-engineers 
I need to cherry pick this into 12-stable after reviewing.
=> Guard resources are executed in why_run mode

lib/chef/chef_fs/chef_fs_data_store.rb, lib/chef/chef_fs/config.rb, lib/chef/chef_fs/data_handler/policy_data_handler.rb, lib/chef/chef_fs/file_system.rb, lib/chef/chef_fs/file_system/chef_repository_file_system_policies_dir.rb, lib/chef/chef_fs/file_system/chef_repository_file_system_root_dir.rb, lib/chef/config.rb, lib/chef/policy_builder/policyfile.rb, spec/unit/chef_fs/config_spec.rb, spec/unit/policy_builder/policyfile_spec.rb
* Adds support for the native policy API. Since this won't be released in Chef Server for a while, it's disabled by default. Setting `policy_document_native_api true` in the appropriate config file enables it.
* Adds policy storage to ChefFS. Using this with https://github.com/opscode/chef-zero/pull/111 I am able to create and update policies with persistent/file-based storage.
ChefFS has no unit tests. I will look into the integration tests, but I'm not sure if stuff like `knife upload` will work with policies, since the current iteration of the policies API is simplified (uses PUT for create and update, for example). I plan to propose an updated policies API as a RFC soon.
@chef/delivery @chef/client-engineers
=> Policyfile Native API Support and ChefFS Policy Support

README.md
Didn't see an open PR for this in the first few pages.
@chef/client-engineers
=> Convert opscode.com and getchef.com to chef.io in README

spec/stress/win32/file_spec.rb
The values here are arbitrarily set and don't work well on ephemeral slaves
because they're not necesssairly stable when the tests start running.
So we'll mark them as volatile until someone decides what to do with them,
mostly to preserve the code.
Cherry-pick of a commit from #2662
=> Disable win32 memory leak tests

lib/chef/knife.rb
Just a trivial message that I came across today. I mainly see value in updating this so ChefDK users don't start sudoing their gem commands and introduce issues for themselves later.
=> Update knife missing gem message for ChefDK

chef.gemspec
rspec 3.2.0 release changed some private APIs in rspec that we were using for audit
mode and broke our master (kind of expected/understandable).
=> pin rspec to 3.1.x for now

CHANGELOG.md, lib/chef/provider/lwrp_base.rb, lib/chef/resource.rb, lib/chef/resource/lwrp_base.rb, spec/unit/lwrp_spec.rb
* providers had the same bug as CHEF-4117 on resources
* removed the strict_const_defined method on Chef::Resource since
ruby 1.8.7 deprecation made that method entirely trivial
* added tests, verified the failure cases really work
* todo added since i think we're leaking state in-between tests
closes #2575
=> fix LWRP constant lookups

lib/chef/knife/bootstrap/chef-full.erb
Pretty sure this is safe to do, modulo operational issues with SSL certificates & chains on old OSes which we should just fix if those turn out to be problems
=> Make chef-full bootstrap use chef.io URL.

CHANGELOG.md, DOC_CHANGES.md, RELEASE_NOTES.md, lib/chef/mixin/get_source_from_package.rb, lib/chef/provider/package.rb, lib/chef/provider/package/apt.rb, lib/chef/provider/package/rubygems.rb, lib/chef/provider/package/yum.rb, lib/chef/resource/package.rb, spec/unit/provider/package/aix_spec.rb, spec/unit/provider/package/apt_spec.rb, spec/unit/provider/package/dpkg_spec.rb, spec/unit/provider/package/ips_spec.rb, spec/unit/provider/package/rubygems_spec.rb, spec/unit/provider/package/solaris_spec.rb, spec/unit/provider/package/yum_spec.rb, spec/unit/provider/package_spec.rb
Allow the `package` provider to take an array of packages to handle in one
transaction.
This solves two large problems:
* There are times when you cannot install two packages in sequence, like when a
binary is moving between two packages - they *must* be done in the same
transaction.
* When using Chef to install the vast majority of your base system, it
can make imaging take a very, very long time because executing yum or apt once
for every single package is painfully slow.
This solves both. The scaffolding is all there in the Package HWRP, plus the
underlying implementation for both apt and yum, the two I have access to test.
=> Multipackge support

lib/chef/resource_builder.rb
When this got extracted into its own class `self` no longer outputs the
resource which is being built.
Closes #2838
=> fix warning output

lib/chef/config.rb, lib/chef/exceptions.rb, spec/spec_helper.rb, spec/unit/config_spec.rb
Adds infrastructure so we can treat deprecation warnings as errors. In a feature I'm working on currently, I am deprecating some stuff that's used in a few places in Chef (conversion of cookbooks to JSON for uploads), and I needed a way to make sure that Chef wasn't triggering deprecation warnings from itself.
To address this, I've added a config option to treat deprecation warnings as errors, which defaults to false. It can be set to true directly, or by setting the environment variable `CHEF_TREAT_DEPRECATION_WARNINGS_AS_ERRORS`. In the spec helper, both of these are set, so when you're running tests, any usage of deprecated behavior will be an error. The environment variable makes this setting persist in child processes, such as when the integration tests run `chef-client` or `knife`. …
=> Deprecation warnings as errors

CHANGELOG.md
The way this reads now makes it sound like there are 3000+ warnings produced for cloning.
=> Improve changelog note about CHEF-3694 warnings

lib/chef/provider/dsc_script.rb, lib/chef/resource/dsc_script.rb, lib/chef/util/dsc/configuration_generator.rb, spec/unit/provider/dsc_script_spec.rb, spec/unit/resource/dsc_script_spec.rb, spec/unit/util/dsc/configuration_generator_spec.rb
This allows the dsc_script resource to import dsc resources
when specifying code. For example:
```ruby
dsc_script 'RDP' do
imports "cRDPEnabled" => ["PSHOrg_cRDPEnabled"]
code <<-EOH
cRDPEnabled "enablerdp"
{
Enabled = $True
}
EOH
end
```
cc @smurawski @adamedx @btm @ksubrama
=> Allow dsc_script to import dsc resources

lib/chef/knife/cookbook_site_download.rb, lib/chef/knife/cookbook_site_list.rb, lib/chef/knife/cookbook_site_search.rb, lib/chef/knife/cookbook_site_share.rb, lib/chef/knife/cookbook_site_show.rb, lib/chef/knife/cookbook_site_unshare.rb, spec/unit/knife/cookbook_site_download_spec.rb, spec/unit/knife/cookbook_site_share_spec.rb
Minimally-fix #2777 
While @lamont-granquist's comment on that issue is correct (about ripping & refactoring), at least we shouldn't leave these commands in a broken state.
=> Move supermarket.getchef.com to supermarket.chef.io

lib/chef/provider/package/dpkg.rb, spec/unit/provider/package/dpkg_spec.rb
@btm @jdmundrawala this fixes a 12.1.0 regression.
not sure how this ever worked but dpkg_package was not setting candidate_version so the define_resource_requirements in the superclass package provider blew up.   i don't know if this got broken by the multipackage stuff becoming more strict or if this was a regression from some other edit to the dpkg provider.  this code should be correct tho.
=> fix dpkg regression

CHANGELOG.md, lib/chef/mixin/params_validate.rb, lib/chef/resource.rb, lib/chef/resource/deploy.rb, lib/chef/resource/lwrp_base.rb, spec/unit/mixin/params_validate_spec.rb, spec/unit/resource/deploy_spec.rb
introduced nillable_set_or_return so that we can actually set a nil value
on a resource from the DSL.
this fixes the case where you want to do (and we document) setting
symlink_before_migrate to nil on the deploy resource.
to implement this better also moved up the attribute DSL method to the
base Chef::Resource class.
all LWRP resources are now nillable as well.
=> nillable deploy resource + nillable LWRP args

lib/chef/dsl/recipe.rb
As they are in Cheffish.  The include is a couple of lines below what the Github diff shows.
=> Missing require - causes `missing Constant` error when files are loaded in unexpected order

lib/chef/application/windows_service.rb, lib/chef/config.rb, spec/unit/windows_service_spec.rb
Solves https://github.com/chef/chef/issues/2985
cc @btm @smurawski @ksubrama @adamedx
=> Chef client running as a windows service should have a configurable timeout

lib/chef/provider/package/yum.rb, spec/unit/provider/package/yum_spec.rb
This was removed in #2924, however it breaks at least the yum
provider.
Without this patch, I was getting:
```
NoMethodError
-------------
undefined method `output_of_command' for #<Chef::Provider::Package::Yum:0x00000003a5f278>
```
when trying to execute
```ruby
package "gdb" do
action :install
end
```
on Centos 6.5
Chef was breaking in weird ways and it didn't produce a stacktrace.out,
which was a little concerning, however that's a different bug
This is required for Chef 12.1 as it a regression that would really suck to ship (it breaks the apache cookbook for sure).
cc @btm @lamont-granquist @jonlives
=> Adding Chef::Mixin::Command back to Package provider base class

lib/chef/provider/package.rb
I think we should add this back in. I don't like that we changed the public interface of the package provider.
Thoughts?
This fixes https://github.com/chef/chef/issues/3011
cc @chef/client-core @chef/client-engineers
=> Adding Chef::Command::Mixin back into the package provider

lib/chef/knife/ssh.rb
Currently, if something goes wrong in a `knife ssh` session we'll swallow the exception and exit status and move on.  This commit retains backwards compatibility but adds the option to exit if something goes wrong.  This has been previously discussed on [CHEF-2627](https://tickets.opscode.com/browse/CHEF-2627) and reported via support on [ZD 2760](https://getchef.zendesk.com/agent/tickets/2760)
```shell
ryan@~/c/oc/chef(ryan/knife_ssh_on_error):> knife ssh name:test* "some command"; echo $?
WARNING: Failed to connect to test-standalone.localdomain -- SocketError: getaddrinfo: nodename nor servname provided, or not known
0
ryan@~/c/oc/chef(ryan/knife_ssh_on_error):> knife ssh name:test* "some command" -e; echo $?
ERROR: Network Error: getaddrinfo: nodename nor servname provided, or not …
```
=> Add --exit-on-error option to knife ssh

CHANGELOG.md, lib/chef/platform/provider_mapping.rb, lib/chef/provider/batch.rb, lib/chef/provider/cron.rb, lib/chef/provider/cron/aix.rb, lib/chef/provider/env.rb, lib/chef/provider/env/windows.rb, lib/chef/provider/group/dscl.rb, lib/chef/provider/group/groupmod.rb, lib/chef/provider/group/usermod.rb, lib/chef/provider/group/windows.rb, lib/chef/provider/mdadm.rb, lib/chef/provider/mount/windows.rb, lib/chef/provider/package/homebrew.rb, lib/chef/provider/powershell_script.rb, lib/chef/provider/user/dscl.rb, lib/chef/provider/user/windows.rb, lib/chef/resource/batch.rb, lib/chef/resource/cron.rb, lib/chef/resource/env.rb, lib/chef/resource/group.rb, lib/chef/resource/homebrew_package.rb, lib/chef/resource/mdadm.rb, lib/chef/resource/mount.rb, lib/chef/resource/powershell_script.rb, lib/chef/resource/user.rb, spec/functional/resource/env_spec.rb, spec/unit/platform_spec.rb, spec/unit/provider_resolver_spec.rb
- move macosx providers to dynamic resolution
- move windows providers to dynamic resolution
- move openbsd/netbsd providers to dynamic resolution
- move all cron providers to dynamic resolution
- move mdadm to static mapping
=> provider_resolver migration from provider_mapping

MAINTAINERS.md
Thom is now the Lieutenant for Core, no need to also be a maintainer
=> Remove @thommay as Core Maintainer

lib/chef/mixin/params_validate.rb, lib/chef/provider/deploy.rb, lib/chef/provider/git.rb, lib/chef/resource/deploy.rb, lib/chef/resource/git.rb, spec/functional/resource/deploy_revision_spec.rb
This finishes #2956 with the provider half of the changes.  Adds deploy provider func tests for the case where the array/hash things are cleared and set to nil.  This will make it substantially easier for users to clear out the capistrano bias from the deploy resource and will make our docs work.
=> add specs for nilling deploy parameters

spec/functional/resource/user/dscl_spec.rb, spec/spec_helper.rb
Not sure why travis didn't catch this, but i've broken specs on everything except mac.
=> dscl specs should only run on mac

lib/chef/config.rb
according to lib/chef/resource/chef_gem.rb#after_created, `true` and `nil` are the same.
```ruby
if compile_time || compile_time.nil?
Array(action).each do |action|
self.run_action(action)
end
Gem.clear_paths
end
```
=> chef_gem_compile_time's nil is the same as true

spec/spec_helper.rb, spec/unit/application/client_spec.rb
I built an omnibus-chef package and didn't see the failures we have seen for the past few days.  Failure:
```
Failures:
1) Chef::Application::Client run_application when sent SIGTERM when converging in forked process should exit hard with exitstatus 3
Failure/Error: expect(result.exitstatus).to eq(3)
expected: 3
got: 0
(compared using ==)
```
My theory is that the machine is slow and only waiting 1 second doesn't give enough time for the Kill statement to propagate.
=> Chef-DK nightlies on debian and el6 have been failing on these timing-based tests, doing a quick fix

spec/functional/resource/user/useradd_spec.rb
We are seeing failures in our CI relating to state not being cleaned
up in a previous run:
```
1) Chef::Provider::User::Useradd action :create when the user already exists and home directory is updated and manage_home is enabled moves the home directory to the new location
Failure/Error: user_resource.run_action(:create)
Mixlib::ShellOut::ShellCommandFailed:
user[TEST USER RESOURCE] (dynamically defined) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '12'
---- Begin output of ["usermod", "-d", "/home/bar", "-m", "cf-test"] ----
STDOUT:
STDERR: usermod: directory /home/bar exists
---- End output of ["usermod", "-d", "/home/bar", "-m", "cf-test"] ----
Ran ["usermod", "-d", "/home/bar", "-m", "cf-test"] returned 12
```
=> Cleanup user directories if state was leftover from previous run

spec/functional/resource/powershell_spec.rb
This case has never worked before 6c724e866274a728bc66740ab352db7da7d7958f.
It was fixed for 4, however it seems that does not apply to versions < 4.
cc @smurawski @btm
=> Mark failing test as pending on versions of powershell < 4

lib/chef/platform/provider_priority_map.rb, lib/chef/provider/package/macports.rb, lib/chef/resource/macports_package.rb
This reverts commit c793d2d5a4fe69c3e636239145139c0afb02fec1.
Fixes #3022.
Homebrew became the default package provider in Chef 12 via #1709, but some
users wanted to keep macports as their default provider so they didn't have
to update all their recipes for Chef 12. #2722 attempted to allow you to easily
change the defaults, but that caused a regression due to which resource was
being loaded, which was filed as #3022.
=> Revert "Macports provider - provide package"

lib/chef/application/client.rb, lib/chef/audit/audit_reporter.rb, lib/chef/client.rb, lib/chef/exceptions.rb, lib/chef/formatters/doc.rb, lib/chef/run_context.rb, spec/unit/audit/audit_reporter_spec.rb
We have been a little inconsistent in the use of the term "audit" versus "control" or "control group" in audit mode. This will confuse customers, particularly those who are security-oriented, so I'd like to fix it. To wit:
* A "control" is a condition you define about system correctness
* A "control_group" is a list of one or more controls
* An "audit" is an operation you run to test your "controls". Hence, "audit mode" is correctly named. However, it makes no sense to have "audits" fail. What we actually mean is that one or more controls failed, which caused the audit as a whole to fail. You also don't "run audits" -- you perform an audit (singular), which runs one or more controls.
I'll leave it to the team to decide whether the ivars, class names, etc. should be renamed. For example, …
=> make audit terminology consistent

chef.gemspec
1.x still works fine, so leaving the lower floor in place.
=> bumping ffi-yajl to pick up 2.x

lib/chef/provider/group.rb
Given these resources
``` ruby
user = 'dave'
group = 'operations'
hasaccess = true
user "Create account #{user}" do
username user
home "/home/#{user}"
gid 'voxer'
action :create
end
user "Manage account #{user}" do
username user
action hasaccess ? :unlock : :lock
end
group "Add #{user} to group #{group}" do
group_name group
members user
append true
action :modify
end
```
This currently generates output like this (using a variation of the minimal formatter)
```
* user[Create account dave]
- create user dave
* user[Manage account dave]
- unlock user dave
* group[Add dave to group operations]
- modify group group[Add dave to group operations]
```
with this patch, the output becomes
```
* user[Create account dave]
- create user dave
* user[Manage account dave]
- unlock user dave
* group[Add …
```
=> alter messages generated by group provider to show group_name

lib/chef/audit/runner.rb
Minimally fixes #2973 
Needs tests, and probably adult supervision :grin:
=> Remove UNIX-specific assumptions from audit runner.

lib/chef/provider/package/openbsd.rb, spec/unit/provider/package/openbsd_spec.rb
This provider was broken in just the right ways when  it was merged that it sort of worked. There were references to methods that didn't exist that just happened not to get called ever.
Since we just released this, and it does not work as is, I'm going to change a few things:
- I've simplified the candidate_version search...I didn't quite understand what the original was wanting to do
- This package provider had a weird usage for source (completely inconsistent with the rest of our package providers), and it was not happy with @jaymzh's patch https://github.com/jaymzh/chef/commit/1f380f9f180f39581f2e124061af1ee927a23e0c. I've decided to explicitly make `source` unsupported for this provider
- It now correctly deals with multiple valid candidates by failing the run instead of picking one …
=> Fix openbsd package provider

lib/chef/knife/bootstrap/templates/chef-full.erb
chef.io is served by a CDN.  The SSL certificate served will have
*.chef.io as a Subject-Alternative-Name. Unfortunately, the wget
version contained in RHEL5 (and potentially other old OS versions)
does not support SAN.
If we want to stay with chef.io, some alternative approaches include:
- Documenting that users of RHEL5 should use --bootstrap-url if their
OS image contains wget [0]
- Prefering other download methods to wget.
[0] EC2s stock RHEl5 images do not contain wget, but our bento-box
images do.
=> Use opscode.com rather than chef.io in the bootstrap script.

spec/functional/util/powershell/cmdlet_spec.rb
cmdlet.rb uses stream redirection, which is not available in
powershell 2. Since this is a helper class for our `dsc_script`
and `dsc_resource`, this is a fairly safe change.
While the verbose stream redirection is currently unused, it
will be useful if Invoke-DscResource logs its verbose output
to the verbose stream.
Fixes #3137
cc @adamedx @btm @ksubrama @smurawski
=> Disable Cmdlet tests on old versions of powershell

lib/chef/cookbook/remote_file_vendor.rb, lib/chef/cookbook_manifest.rb, lib/chef/cookbook_version.rb, lib/chef/policy_builder/policyfile.rb, spec/unit/cookbook/file_vendor_spec.rb, spec/unit/cookbook_manifest_spec.rb, spec/unit/cookbook_uploader_spec.rb, spec/unit/policy_builder/policyfile_spec.rb
In conjunction with https://github.com/chef/oc_erchef/pull/119 and forthcoming ChefDK PR, this gets policyfiles into a demo-able state with Erchef.
Most of the changes are confined to policyfile-specific code paths, which you need to opt-in to with a feature flag, so it should be pretty safe. The RemoteFileVendor change touches a pretty important code path, which is why I went with the ugly but simple change. I'll follow up with another PR that improves the file vendor API so it doesn't rely on the format of the manifest hash so much.
@chef/client-core @jdmundrawala
=> Policyfile erchef integration

lib/chef/application/apply.rb, lib/chef/application/client.rb, lib/chef/application/solo.rb, lib/chef/client.rb, lib/chef/config.rb, spec/integration/client/client_spec.rb, spec/integration/client/ipv6_spec.rb, spec/integration/recipes/lwrp_inline_resources_spec.rb, spec/integration/solo/solo_spec.rb, spec/unit/client_spec.rb
:construction: needs specs, though it works in integration
Add a minimal ohai mode that skips most ohai plugins and reduces overall chef-client run time. This shaves a few seconds off of each integration test that runs chef-client, saving a few minutes overall. Results obviously will depend on a lot of factors.
=> Add minimal ohai mode option flag

lib/chef/knife/ssh.rb, spec/unit/knife/ssh_spec.rb
This supersedes #2935 which seems to have been abandoned before it was fixed (and also lacks the requisite unit test).
=> For knife ssh: Do not try to use item[:cloud][:public_hostname] for the hostname if it is empty

lib/chef/provider/service/macosx.rb, lib/chef/resource/macosx_service.rb, lib/chef/resource/service.rb, spec/unit/provider/service/macosx_spec.rb
Proposed changes to chef mac osx service provider. This adds two
resource parameters, @plist and @session_type and changes logic to Load
LaunchAgents as Console user.
@plist: Adds the logic to handle
(https://github.com/chef/chef/issues/2200) by Giving the user the
option to pass a plist, in the case that the plist name and label name
don't match.
@session_type to help account launching
the service as the console user with a different session type.
( Im a Facebook employee and PhilD will do the final merge. )
=> Load LaunchAgents as console user, adding plist and session_type options

lib/chef/knife/status.rb
Fixes race condition on presenter loading in status
=> explicitly require node presenter

appveyor.yml
I broke universal gems in https://github.com/bundler/bundler/pull/3553
We can unpin once a fix is released
=> Pin bundler to 1.9.2 in appveyor.yml

lib/chef/http/basic_client.rb, spec/unit/http/basic_client_spec.rb
This change adds support to Chef's core http libs to
honor a proxy uri set in the environment not just
chef/knife config. It also adds support for username
and password both in uri and env.
The order of precidence for values is uri, env, config.
=> Fixes 2140 - Honor Proxy from Env

CHANGELOG.md, RELEASE_NOTES.md, lib/chef.rb, lib/chef/chef_class.rb, lib/chef/client.rb, lib/chef/mixin/provides.rb, lib/chef/platform/provider_priority_map.rb, lib/chef/platform/resource_priority_map.rb, lib/chef/policy_builder/expand_node_object.rb, lib/chef/policy_builder/policyfile.rb, lib/chef/provider.rb, lib/chef/provider_resolver.rb, lib/chef/resource.rb, lib/chef/resource_resolver.rb, spec/data/lwrp/providers/buck_passer.rb, spec/data/lwrp/resources/bar.rb, spec/unit/chef_class_spec.rb, spec/unit/provider_resolver_spec.rb, spec/unit/recipe_spec.rb, spec/unit/resource_spec.rb
Add dynamic resource resolver to Chef, similarly to the dynamic provider Resolver.
This lets multiple resources wire up to the same typed command (e.g. "package" resolving to either Homebrew or MacPorts resource on macs) and let manipulation of the priorities influence which one gets selected.  This also makes the implementation of resource resolution more closely match implementation of provider resolution (but there are some important differences since resources don't implement the `#supports` api like providers do).
=> add resource_resolver and resource_priority_map

lib/chef/search/query.rb, spec/unit/search/query_spec.rb
If a search doesn't return a full result, and there was no row
limit specified, then increment the start pointer by the number
of rows returned, not zero.
This should fix #3099
=> Ensure that a search query makes progress

lib/chef/audit/runner.rb
Fixes https://github.com/chef/chef/issues/3234.
According to [serverspec documentation](https://github.com/serverspec/serverspec/blob/master/WINDOWS_SUPPORT.md) we need to make below configuration on windows:
```
set :backend, :cmd
set :os, :family => 'windows'
```
Looks like we have missed one line.
/cc: @mcquin, @juliandunn, @chef/client-windows
=> Configure serverspec correctly on windows.

.travis.yml
I think our IPv6 tests are failing on Travis because of this: https://github.com/travis-ci/travis-ci/issues/3302
Thoughts?
=> Disable Travis CI container infrastructure due to broken IPv6 support

lib/chef/client.rb, lib/chef/run_status.rb, spec/unit/client_spec.rb
Patch for issue https://github.com/chef/chef/issues/3180
Actual problem:
missing recipe present in run_list - exception handlers work as expected
missing role present in run_list - exception handlers do not fire.
Exception handlers require @run_status to be set.
Moving the declaration to initialisation block ensures it's always available.
'node' is nil at that stage and is set again here https://github.com/chef/chef/blob/master/lib/chef/client.rb#L244
big thanks to @jonlives, Coderanger and @thommay your help
=> patch to always run exception handlers

lib/chef/win32/api/installer.rb
This was broken in #3034. The issue is that the package does not get detected
as installed because the version that is installed has \x00 at the end,
while the version from the msi does not. This fails comparison, and we fall
into code that does not use source and thus requires candidate version and we
die. (Or something like that)
Solves #3316
=> windows_package is idempotent again

CHANGELOG.md, lib/chef/provider/file.rb, lib/chef/resource.rb, lib/chef/resource/file.rb, lib/chef/resource_reporter.rb, spec/support/shared/unit/provider/file.rb
this line violates the rule that we never mutate the new resource.
in Chef 12 this causes real problems because if a file resource is
notified (run twice) then the rendered content is loaded into the
new resource and if the file resource content changes (i.e. its a
template with logic which changes when its notified) then it will
cause a failure because the rendered content will not match the
'requested' checksum.  where the 'requested' checksum is actually
the checksum loaded by this line.
fundamentally we have three different states that we're trying to
track:
- current state
- initial state
- requested state
the removed line tries to use the @new_resource for reporting initial
state, which then bleeds over into what chef thinks is requested state
in the next invokation.
without …
=> don't mutate the new resource

lib/chef/provider/package/aix.rb, spec/unit/provider/package/aix_spec.rb
Raise exception if a BFF provided by 'source' doesn't actually provide that package
Fixes #3108
=> fix AIX package installs using a 'source' attribute

CHANGELOG.md, lib/chef/formatters/error_inspectors/api_error_formatting.rb, lib/chef/formatters/error_inspectors/cookbook_resolve_error_inspector.rb, lib/chef/formatters/error_inspectors/cookbook_sync_error_inspector.rb, lib/chef/formatters/error_inspectors/node_load_error_inspector.rb, lib/chef/formatters/error_inspectors/registration_error_inspector.rb, lib/chef/formatters/error_inspectors/run_list_expansion_error_inspector.rb, lib/chef/http/authenticator.rb, lib/chef/knife.rb, spec/unit/formatters/error_inspectors/api_error_formatting_spec.rb, spec/unit/http/authenticator_spec.rb, spec/unit/knife_spec.rb, spec/unit/rest_spec.rb
Ping @chef/lob @marcparadise 
Implemented `X-Ops-Server-API-Version` header and error handling for unsupported server API versions. This takes advantage of `Chef::HTTP::Authenticator.handle_request`. After the `authentication_headers` have been merged, it adds:
`{'X-Ops-Server-API-Version' => Chef::HTTP::Authenticator::SERVER_API_VERSION}`
`Chef::HTTP::Authenticator::SERVER_API_VERSION` should correspond to the max version of the server the client is compatible with. We are starting at `"0"`.
I also removed outer level lets `:base_header` and `:req_with_body_headers` from `rest_spec.rb` as they were never used anywhere. Another `:base_header` was defined in a tighter scope of the spec and was only used in that scope, and `:req_with_body_headers` was never used anywhere.
+ …
=> Implemented X-Ops-Server-API-Version in Chef requests

lib/chef/file_access_control/unix.rb, spec/support/shared/functional/securable_resource.rb
On Linux updating the group or owner unsets the suid bit for security
reasons, so check for group and owner updates whether or not to set the
mode.
This is in reference to issue #2951
=> update mode if group or owner change to keep suid bit

distro/common/markdown/man1/chef-shell.mkd, distro/common/markdown/man1/knife-bootstrap.mkd, distro/common/markdown/man1/knife-client.mkd, distro/common/markdown/man1/knife-configure.mkd, distro/common/markdown/man1/knife-cookbook-site.mkd, distro/common/markdown/man1/knife-cookbook.mkd, distro/common/markdown/man1/knife-data-bag.mkd, distro/common/markdown/man1/knife-environment.mkd, distro/common/markdown/man1/knife-exec.mkd, distro/common/markdown/man1/knife-index.mkd, distro/common/markdown/man1/knife-node.mkd, distro/common/markdown/man1/knife-role.mkd, distro/common/markdown/man1/knife-search.mkd, distro/common/markdown/man1/knife-ssh.mkd, distro/common/markdown/man1/knife-status.mkd, distro/common/markdown/man1/knife-tag.mkd, distro/common/markdown/man1/knife.mkd, distro/common/markdown/man8/chef-client.mkd, distro/common/markdown/man8/chef-expander.mkd, distro/common/markdown/man8/chef-expanderctl.mkd, distro/common/markdown/man8/chef-server-webui.mkd, distro/common/markdown/man8/chef-server.mkd, distro/common/markdown/man8/chef-solo.mkd, distro/common/markdown/man8/chef-solr.mkd, lib/chef/cookbook/metadata.rb, lib/chef/cookbook_loader.rb
I ran into an error message that still referenced the wiki site.  Seemed like a good idea to nuke all the old links
=> Convert wiki links to docs.chef.io links

lib/chef/cookbook_site_streaming_uploader.rb, spec/unit/cookbook_site_streaming_uploader_spec.rb
This change provides a simple fix to the SSL errors encountered in this issue: https://github.com/chef/chef/pull/3324  by using `Chef::HTTP::BasicClient` instead of `Net::HTTP` directly.  
Without this fix, initial connections to Private Supermarket work fine but the cookbook upload stage mysteriously fails.
ChangeLog-Entry: Fix SSL policy and Proxy handling in CookbookSiteStreamingUploader to work like other components in Chef.
For review by: @chef/client-core
=> Apply an SSL Policy to CookbookSiteStreamingUploader, fixing SSL errors uploading to private Supermarkets

lib/chef/event_dispatch/dispatcher.rb, spec/unit/event_dispatch/dispatcher_spec.rb
I need this so I can properly assert that the `ChefRunner` class in chef-dk has correctly configured a 'doc' formatter for its embedded chef-client run. Currently I have to use `instance_variable_get` as a workaround :hankey: 
/cc @chef/client-core
=> Allow inspection of event dispatch's subscribers

lib/chef/http/basic_client.rb, spec/unit/http/basic_client_spec.rb
We need to check if the env variable is set to empty string. If we don't we can get in an edge case where we blow up trying to call URI.parse.
=> Check if proxy env_var is empty

lib/chef/knife/ssh.rb, spec/functional/knife/ssh_spec.rb, spec/unit/knife/ssh_spec.rb
PR to fix  https://github.com/chef/chef/issues/2325
and also https://tickets.opscode.com/browse/CHEF-4962?focusedCommentId=46454&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-46454
My argument for this is as follows:
all manual overrides should take priority over whatever the default/automatic lookups that exist.
the priority list for the host attribute is as follows:
1. command line
2. knife.rb :ssh_attribute value
3. cloud.public_hostname value
4. fqdn parameter
the last 2 are essentially defaults.
=> Prioritise manual ssh attribute over defaults

lib/chef/formatters/error_inspectors/resource_failure_inspector.rb, spec/unit/formatters/error_inspectors/resource_failure_inspector_spec.rb
Should fix #3055
The unit tests repros the issue, but does not fail. Ruby seems to be logging a warning somewhere internally
=> Escape string inside regex

lib/chef/provider/remote_file/content.rb, lib/chef/provider/remote_file/fetcher.rb, lib/chef/provider/remote_file/network_file.rb, lib/chef/providers.rb, lib/chef/resource/remote_file.rb, spec/unit/provider/remote_file/fetcher_spec.rb, spec/unit/provider/remote_file/network_file_spec.rb, spec/unit/resource/remote_file_spec.rb
```ruby
remote_file 'C:\Foo.tar.gz' do
source "\\\\foohost\\fooshare\\Foo.tar.gz"
end
```
cc @btm @ksubrama @smurawski
=> remote_file support for windows network shares

lib/chef/provider.rb, lib/chef/provider/package.rb, spec/unit/provider/package_spec.rb, spec/unit/provider_spec.rb
Added a lifecycle method to check if the resource makes sense for the provider. That way, we can fail before loading it. Will add specs if we want to solve the problem this way :)
Fixed #3075 as an example
cc @jaymzh @chef/client-core
=> Add check_resource_semantics! lifecycle method to provider

lib/chef/mixin/uris.rb, lib/chef/provider/package/windows.rb, lib/chef/resource/windows_package.rb, spec/unit/mixin/uris_spec.rb, spec/unit/provider/package/windows_spec.rb, spec/unit/resource/windows_package_spec.rb
This patch allows people to specify a url for source for the `windows_package` resource.
cc @btm @smurawski @ksubrama
=> Modify windows package provider to allow url

lib/chef/cookbook/metadata.rb, lib/chef/knife.rb, spec/integration/knife/upload_spec.rb, spec/unit/cookbook/metadata_spec.rb, spec/unit/knife_spec.rb
cookbooks with self-deps:
name 'foo'
depends 'foo'
are useless and can waste cycles in the depsolver (particularly in
the non-solution case), and likely limit the possible choices of
depsolvers that we could pick at some point to replace gecode.
filtering out the self-dep here will prevent the chef server depsolver
from seeing the self-dep and needing to do the work to strip it.
also warn the user so that they can remove the self-dep.
in the future this will be a hard error.
foodcritic also has a [PR in for a] rule about removing these.
=> warn on cookbook self-deps

Rakefile
When https://github.com/chef/chef/pull/3270 is accepted, we will need to update omnibus to build subprojects in Chef's git repo, as implemented in https://github.com/chef/omnibus-software/pull/430
For future builds of Chef 11 to work, either omnibus needs to build 11 and 12 differently, or 11 needs to be forward compatible with 12 as far as build commands. This patch makes Chef 11 forward compatible, as it's the cleaner easier solution.
=> Add install_components task for forward compat w/ 12

spec/functional/shell_spec.rb
seems to fix the timeouts on the exceedingly slow sparc boxes in CI
=> bump timeout up to 300 seconds

lib/chef/knife/bootstrap.rb, spec/unit/knife/bootstrap_spec.rb
When bootstrapping with chef-vault or with user credentials we create
the node and client on the Chef Server before we bootstrap the node. As
it is possible to specify a server address that is not the node name we
need to enforce that the user pass a node name with -N.
At present if you omit the the node name you'll be prompted to delete
nonexistent clients and nodes.
cc @lamont-granquist 
closes #3204
=> Enforce passing a node name with validatorless bootstrapping

lib/chef/resource/lwrp_base.rb, spec/unit/lwrp_spec.rb
This PR fixes different behavior in cases then we set action during resource call and then actions sets from default_action method.
If we call resource and set action directly:
```
foo_resource 'bar' do
action :add
end
```
variable ```@action``` will be always an array, no matter if we gave an array or a symbol to the method action.
If we call resource without action:
```
foo_resource 'bar'
```
and in its declaration contains:
```
default_action :add
```
variable ```@action``` will be an array if we gave an array to the method default_action or a symbol if we gave a symbol.
I fixed this difference so that the variable ```@action``` always has been an array.
=> Not consistent behavior of methods `default_action` in `Chef::Resource::LWRPBase` class and `action` in `Chef::Resource` class.

lib/chef/win32/net.rb
This should fix our internal CI
cc @thommay @chef/client-windows
=> Don't call get_last_error for net api

appveyor.yml, lib/chef/formatters/error_inspectors/compile_error_inspector.rb, spec/unit/formatters/error_inspectors/compile_error_inspector_spec.rb
If you have code like `include_recipe "cookbook_exists::RECIPE_DOESNT_EXIST"`, you don't get the cookbook trace or error context because `RecipeNotFound` is assumed to have originated from a bad run list in chef-solo (I think). What we should be checking for is whether we are able to locate the proper recipe context or not. I found this relevant commit https://github.com/chef/chef/commit/abefd661954fd533c227e17ff74065bf114e8b24, but didn't find the PR it was from, so I could not locate the original bug report. I added a regression test for what I suspect the original bug was, so I think this should not regress the original issue.
=> Show trace for RecipeNotFound errors when it originates from include recipe

appveyor.yml
Based on
* http://help.appveyor.com/discussions/questions/585-what-setup-for-build-cache-is-require-for-bundle-install
* http://www.appveyor.com/docs/installed-software
I think these are the right settings for caching rubygems.
=> Enable caching of rubygems in appveyor

chef-config/lib/chef-config/config.rb, spec/unit/knife_spec.rb, spec/unit/policy_builder/policyfile_spec.rb
Policyfile APIs are going to be enabled by default in the next Chef Server release (and they're enabled in hosted now). This should be the default. Technically this is a breaking change but this has been labeled an experimental feature since the beginning so IMO we can follow the pre-1.0 semver rules.
=> Make native mode the default for policyfiles

lib/chef/mixin/uris.rb, lib/chef/provider/remote_file/content.rb, lib/chef/provider/remote_file/local_file.rb, lib/chef/resource/remote_file.rb, spec/unit/mixin/uris_spec.rb, spec/unit/provider/remote_file/local_file_spec.rb, spec/unit/resource/remote_file_spec.rb
Fixes #1848 
The following example now works
```ruby
remote_file "c:\\nospaces" do
source "file:///c:/foo bar"
end
```
cc @chef/client-windows @sean-horn
=> Allow spaces in files for remote_file

lib/chef/provider/service/freebsd.rb, spec/functional/resource/link_spec.rb, spec/functional/resource/user/useradd_spec.rb, spec/support/shared/functional/file_resource.rb, spec/support/shared/functional/securable_resource.rb, spec/support/shared/functional/securable_resource_with_reporting.rb, spec/unit/chef_fs/file_pattern_spec.rb, spec/unit/cookbook_spec.rb, spec/unit/cookbook_version_spec.rb, spec/unit/mixin/command_spec.rb, spec/unit/provider/ifconfig/debian_spec.rb, spec/unit/provider/package/openbsd_spec.rb, spec/unit/provider/package/rubygems_spec.rb, spec/unit/provider/remote_directory_spec.rb, spec/unit/provider/service/freebsd_service_spec.rb, spec/unit/provider/user_spec.rb, spec/unit/resource/template_spec.rb
Mass purge of pending specs. These have been around and not been worked on for a very long time, so they're an unfunded mandate that vomit a bunch of test output and don't do much else.
=> RSpec isn't a bug database or kanban board

spec/functional/resource/user/useradd_spec.rb
This was causing this error in Ci:
```
1) Chef::Provider::User::Useradd action :create when the user does not exist beforehand and the username contains a single quote ensures the user exists
Failure/Error: skip(reason)
ArgumentError:
wrong number of arguments (1 for 0)
```
=> Fix overridden method `skip` causing arity failures

lib/chef/application/client.rb
Fixes issue for when environment variable is not set and chef_repo_path expects one.
tl;dr - if you have something like this in a config.rb/knife.rb:
```chef_repo_path ENV['SOMETHING']```
and $SOMETHING is not set, when running ```chef-client -z``` it will throw a wonderful error like so:
```[2015-05-22T13:11:58-07:00] FATAL: NoMethodError: undefined method `map' for nil:NilClass```
Which gives you nothing to go on. This issues a warning and resets the config to default value.
=> Fix cli issue with unset chef_repo_path

spec/functional/resource/user/useradd_spec.rb
Otherwise we run useradd provider prior to the before block with the
example-level `skip` being called.
=> Move `skip` for useradd test to metadata

spec/spec_helper.rb
although appveyor does, so must have cygwin?
=> windows does not have uname

Rakefile, chef-config/Rakefile
When bundler 1.10 is installed, running these tasks w/ bundler causes
`gem install` to fail with no output
=> Run `gem install` tasks w/o bundler's env

lib/chef/provider/dsc_resource.rb
It looks like the April preview returns data in a different structure than the February preview
=> Fix dsc_resource to work with wmf5 april preview

spec/unit/knife/core/subcommand_loader_spec.rb
https://github.com/chef/chef/commit/e19aacce268f37e147228a379396b3adb4f648ce https://github.com/chef/chef/pull/3281 was merged with a broken test. Based on the discussion there, I think the intent of the test was that this element ("universal" platform gem) is supposed to be included.
@chef/client-core @chef/client-windows
=> Fix subcommand loader test

lib/chef/provider/package/rubygems.rb, spec/unit/provider/package/rubygems_spec.rb
Ruby 2.0 is the oldest release we support, and it ships with Rubygems
2.0: https://github.com/ruby/ruby/blob/v2_0_0_0/lib/rubygems.rb#L11
This may fix issues we see in Ci, which have a stack trace like this:
```
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:762:in `block in _resort!': undefined method `name' for nil:NilClass (NoMethodError)
from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:761:in `sort!'
from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:761:in `_resort!'
from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:713:in `_all'
from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:896:in `each'
from …
```
=> Drop support for rubygems 1.x

lib/chef/server_api.rb
this is probably pulled in by chef/http at the top, but make it
explict (lazy to break circular deps).
=> add lazy require for 'chef/config'

lib/chef/guard_interpreter/default_guard_interpreter.rb
This should fix the issue where doing
```ruby
require 'chef/resource'
```
throws an exception because Chef::Mixin::ShellOut is not loaded
=> Add missing require

kitchen-tests/.kitchen.travis.yml
m3 has newer CPUs on SSDs.  should be substantially faster.
there is no m3.small
=> try m3.medium over m1.small

.travis.yml
It only matters on Windows and so it gets run in
appveyor
=> We don't need to run ruby 2.0 in travis.

lib/chef/mixin/convert_to_class_name.rb, spec/integration/recipes/lwrp_spec.rb, spec/unit/lwrp_spec.rb
has a regression test for provider priority map setting with cookbooks with hyphens in the name. Currently doesn't have the fix. I did some refactoring in the first commit, so you might want to focus on the second commit.
@sdelano @jkeiser
=> Hyphenated LWRP

CHANGELOG.md, lib/chef/provider/lwrp_base.rb, spec/support/lib/chef/provider/openldap_includer.rb, spec/support/lib/chef/resource/openldap_includer.rb, spec/unit/recipe_spec.rb
allows include_recipe "build-essential" to work from provider
code.
=> allow include_recipe from LWRP provider code

kitchen-tests/Gemfile
Because https://github.com/test-kitchen/kitchen-ec2/issues/148 has been fixed, travis should no longer break
=> Using master of kitchen-ec2 for travis integration tests

CHANGELOG.md, lib/chef/guard_interpreter/resource_guard_interpreter.rb, spec/unit/guard_interpreter/resource_guard_interpreter_spec.rb
Addresses #3485 -- the `RunContext` alters the private state of the node passed to the `RunContext#initialize`. The node passed in this case is the actual `Node` instance being tracked by the Chef Client run, so unpredictable side-effects may occur, though so far we have only one known issue related to this problem. The limited observations are possibly due to the internals of Chef using the `RunContext` instance referenced from sources other than the corrupt `Node` instance.
Passing a duplicate of the `Node` instance to the `initialize` method of `RunContext` avoids this problem while still meeting the requirements of `guard_interpreter` resource execution.
=> Issue#3485: Fix corruption of run_context when guard interpreters are executed

lib/chef/application/client.rb, spec/unit/application/client_spec.rb
I'm going to suggest we remove this to avoid freaking out customers since we have been shipping this mode for some time.
/cc @chef/analytics-data-integrations
=> Remove experimental warning on audit mode.

lib/chef/provider/package/rpm.rb, spec/unit/provider/package/rpm_spec.rb
Fixes the issue described in #3496 
The tilde character '~' is valid in package versions and has some useful benefits and was implemented in our Omnibus builds last December: https://github.com/chef/omnibus/pull/401
The regex we use to examine the package version in `rpm_package` silently fails on these packages because it doesn't look for that ~ character: http://rubular.com/r/u63jqN7OJI
This PR adds the ~ character to the regex.  
CC: @chef/client-maintainers @chef/release-engineers
=> fix rpm_package when sourced packages have a tilde character in the version

lib/chef/mixin/params_validate.rb, lib/chef/resource.rb, lib/chef/resource/lwrp_base.rb, spec/unit/property/state_spec.rb, spec/unit/property/validation_spec.rb, spec/unit/property_spec.rb
Implements most of the [https://github.com/chef/chef-rfc/blob/jk/property/new/property.md](Property RFC), which is set to be accepted shortly.
- `property` can now be written in Resource:
```ruby
class Foo < Chef::Resource
resource_name :foo
property :x, String
end
foo 'blah' do
x 'hi'
end
```
- It is now possible to set a property to `nil` *if* the type allows it:
```ruby
class Foo < Chef::Resource
resource_name :foo
property :x, [ String, nil ], default: 'hi'
end
foo 'blah' do
x nil
end
```
- lazy defaults are now possible and run in the context of the instance:
```ruby
class Foo < Chef::Resource
resource_name :foo
property :base, Integer, default: 1
property :x, Integer, default: lazy { 10 + base }
end
foo 'blah' do
puts x #=> 11
end
```
- coercion is implemented:
```ruby
class Foo < …
```
=> Allow properties to be defined on resources

lib/chef/platform/provider_mapping.rb, spec/integration/recipes/recipe_dsl_spec.rb
This should fix sethvargo-cookbooks/swap#22
Here's what was happening:
The cookbooks creates a Resource using the LWRP base. This dynamically
creates a class. We used to create this class with the name
Chef::Resource::SomeResourceName. In 12.4, this change to something like
"LWRP resource some_resource_name from cookbook CookbookName". When
searching for a provider, it couldn't be found because it wasn't explicitly
set, as it would have been if it was a LW provider, and it wasn't found
in Chef::Provider, because Chef::Provider had a provider SomeResourceName
instead of "LWRP resource some_resource_name from cookbook CookbookName".
cc @jkeiser @sethvargo @chef/client-maintainers
=> Fix to allow LW resources to be used with HW providers

MAINTAINERS.md, MAINTAINERS.toml
Per the RFC submitted in chef-rfc PR 131:
https://github.com/chef/chef-rfc/pull/131
We need lieutenants, maintainers for all the tier 1 and tier 2 platforms. Thom May and Lamont Granquist have volunteered for various platforms.
Lamont volunteered for AIX but only interim until someone else can step up.
Still outstanding:
=> add maintainers/Lts for tier 1 & 2 support

lib/chef/run_context.rb
Adds actual implementation for deprecated setters, and re-adds the accidentally removed resource_collection= setter. Fixes #3585.
Ping @jdmundrawala for inclusion in next build.
=> Fix deprecated setters.

lib/chef/provider/powershell_script.rb, spec/functional/resource/powershell_spec.rb
@ksubrama, @btm, @jdmundrawala  thanks for merging #3080. Here's an addendum based on a few pieces of feedback I didn't follow up on:
1. Took @jdmundrawala 's feedback that preserving behavior of other script resources that let you suppress syntax errors just added complexity at the expense of obscuring a much more likely scenario: user expects a (failure) return code of 1, but the script itself has a syntax error. In that case, the script needs to be fixed by the user, but the user isn't aware because Chef reports no error. The `powershell_script` resource hasn't been around long enough to need such strict backwards compatibility to justify the complexity in code (evidenced by numerous questions in the #3080 conversation) and the difficulty of the aforementioned scenario.
2. Feedback …
=> Issue #3455: powershell_script: do not allow suppression of syntax errors

lib/chef/guard_interpreter/resource_guard_interpreter.rb, lib/chef/resource.rb, spec/functional/provider/whyrun_safe_ruby_block_spec.rb, spec/integration/recipes/resource_action_spec.rb, spec/unit/lwrp_spec.rb, spec/unit/provider/deploy_spec.rb, spec/unit/recipe_spec.rb, spec/unit/resource/breakpoint_spec.rb, spec/unit/resource/cron_spec.rb, spec/unit/resource/directory_spec.rb, spec/unit/resource/dsc_resource_spec.rb, spec/unit/resource/dsc_script_spec.rb, spec/unit/resource/env_spec.rb, spec/unit/resource/erl_call_spec.rb, spec/unit/resource/file_spec.rb, spec/unit/resource/group_spec.rb, spec/unit/resource/link_spec.rb, spec/unit/resource/mdadm_spec.rb, spec/unit/resource/mount_spec.rb, spec/unit/resource/ohai_spec.rb, spec/unit/resource/registry_key_spec.rb, spec/unit/resource/route_spec.rb, spec/unit/resource/ruby_block_spec.rb, spec/unit/resource/user_spec.rb, spec/unit/resource/windows_service_spec.rb, spec/unit/resource_spec.rb
This means it always coerces to an Array. Also ensures that
Resource#action= goes through the same validation.
Fixes #3604.
=> Rework Resource#action to match the 12.3 API.

lib/chef/resource.rb, lib/chef/resource/lwrp_base.rb, spec/unit/lwrp_spec.rb
Repro
=====
The following cookbook would repro the issue
cookbooks/lwrptest/resources/my_lwrp.rb
---------------------------------------
```ruby
```
cookbooks/lwrptest/providers/my_lwrp.rb
---------------------------------------
```ruby
```
cookbooks/lwrptest/recipes/default.rb
-------------------------------------
```ruby
module Something
def something
puts 'something here'
end
end
::Chef::Resource::LwrptestMyLwrp.send(:include, Something)
lwrptest_my_lwrp 'blah' do
something
end
```
Why it does not work
====================
Running this in 12.4.0 produces the error
```
NoMethodError
-------------
undefined method `something' for LWRP resource lwrptest_my_lwrp from cookbook lwrptest
```
The problem is that LWRP usage through `Chef::Resource::MyLwrp` and
`Chef::Provider::MyLwrp` is …
=> Fix ability to monkey match LWRP through Chef::Resource::MyLwrp

lib/chef/application/solo.rb, spec/unit/application/solo_spec.rb
Using C:\Users\Administrator>chef-solo -i 30 -s 5 -c C:/monsoon/solo.rb -j http://foo-bar/get-run -r http://foo-bar.com/cookbooks.tar.gz
failled with error : 
[2015-06-25T15:01:52+02:00] DEBUG: ---- End output of tar zxvf C:/chef/recipes.t
gz -C C:/chef ----
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/command.rb:140:in `block in ou
tput_of_command': undefined method `exitstatus' for nil:NilClass (NoMethodError)
from C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/command.rb:122:in
`chdir'
from C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/command.rb:122:in
`output_of_command'
from C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/command.rb:101:in
`run_command_and_return_stdout_stderr'
from C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/command.rb:79:in
`run_command'
from …
=> Use Mixlib::Shellout instead of Chef::Mixin::Command

lib/chef/resource.rb, lib/chef/resource/lwrp_base.rb, spec/unit/lwrp_spec.rb
Our logic for creating the deprecation class was too complicated and had
a lot of edge cases. Simplifying here to only deprecate when
`:treat_deprecation_warnings_as_errors` is set. This means that warnings
will no longer be printed, however this is a lot less risky.
Loading the lwrp multiple times causes problems when comparing classes
due to the their dynamic nature. It worked fine when we were overriding
the things that checked.
I've left the tests mostly as is, other than the fact that the test
lwrp is loaded only once. The tests should still hold true, even
with the new implementation.
=> Simplify LWRP Deprecations Proposal 1

lib/chef/mixin/params_validate.rb, spec/unit/property/validation_spec.rb
Right now we evaluate required before name_attribute, which means we didn't know it had a value.
=> Make required name attributes work

lib/chef/constants.rb, lib/chef/delayed_evaluator.rb, lib/chef/exceptions.rb, lib/chef/mixin/params_validate.rb, lib/chef/property.rb, lib/chef/resource.rb, spec/unit/mixin/params_validate_spec.rb, spec/unit/property/state_spec.rb, spec/unit/property/validation_spec.rb, spec/unit/property_spec.rb, spec/unit/resource_spec.rb
Adds a Property class to encapsulate property behavior with getters, setters, and defaults; stores identity and desired_state on them; drives identity_attr and state_attrs based on that.
=> Add "property" with identity and desired_state

chef-config/spec/unit/workstation_config_loader_spec.rb
We keep seeing this randomly
```
1) Chef::WorkstationConfigLoader loading the config file when the config file exists and raises a ruby exception during evaluation raises a ConfigurationError
Failure/Error: expect { config_loader.load }.to raise_error(Chef::Exceptions::ConfigurationError)
expected Chef::Exceptions::ConfigurationError, got #<Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/Chef-WorkstationConfigLoader-rspec-test20150707-35300-f9yfb6> with backtrace:
```
I think the issue is that the tempfile gets GC'd, and when it gets GC'd, it deletes the file.
If it is cleaned up before it is used, then the test fails.
=> Try fix for failing config test

MAINTAINERS.md, MAINTAINERS.toml
This PR piggybacks on top of https://github.com/chef/chef/pull/3525 and adds myself as an Archlinux maintainer
=> Add myself as an Archlinux maintainer

lib/chef/resource.rb, spec/unit/property/state_spec.rb
If you call state_properties :x, and there is no
property :x yet, it assumes you are working with a custom
getter/setter like "def x". This is fine, but when you say
"property :x", it won't override that (and will treat the
property as if the getter/setter were already defined instead
of creating a new one).
=> Fix issue where DSL is not emitted if state_properties happens before property

spec/unit/json_compat_spec.rb
This all assumes freebsd tests are failing for the reason they did in  #3101 and ruby is doing what i think it is doing 
Freebsd 10.1 i386 testers keep getting:
```
/opt/chef/embedded/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `load': stack level too deep (SystemStackError)
from /opt/chef/embedded/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
from /opt/chef/embedded/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `each'
from /opt/chef/embedded/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `load_spec_files'
from /opt/chef/embedded/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:102:in `setup'
from …
```
=> Rewrite nested json test to not use stack

lib/chef/platform/rebooter.rb, spec/functional/rebooter_spec.rb
Correct the command used to reboot Windows machines so that it converts
a given delay_mins option to the appropriate number of seconds.
Fixes #3673
=> Correct Windows reboot command to delay in minutes

DOC_CHANGES.md, lib/chef/node.rb, spec/unit/node_spec.rb
Allows users to have `"chef_environment": "some_environment"` in their JSON attributes file (e.g., `/etc/chef/first_boot.json`). Setting `"chef_environment"` in the attributes JSON has the same effect as running `chef-client -E some_environment`.
Note [this comment on CLI option precedence](https://github.com/chef/chef/blob/64e0a1da0826f5befababb5693d8bb5b8de913e9/lib/chef/node.rb#L351-L360). I've struggled to come up with a reasonable workaround which doesn't involve completely reworking the interaction between`Chef::Config` and CLI `config`.
\cc @chef/client-core @charlesjohnson @alexpop
=> Set chef_environment in attributes JSON

lib/chef/resource/file/verification.rb, spec/unit/resource/file/verification_spec.rb
=> Interpolate `%{path}` in verify command

lib/chef/platform/handler_map.rb, spec/integration/recipes/recipe_dsl_spec.rb, spec/unit/recipe_spec.rb
These are high-volume, difficult to silence, and often not actually an error (in which case they may be impossible to silence forever). Worse, doing what the error says and setting override:true without understanding what that does can have unexpected effects (https://github.com/jssjr/git/issues/70). If we want to keep them, they should be moved to debug, but as they often don't indicate any error, I think they should be removed.
Opening this for discussion. /cc @jkeiser @lamont-granquist @someara
=> Remove warnings about hander overrides.

DOC_CHANGES.md, lib/chef/property.rb, lib/chef/provider.rb, lib/chef/resource.rb, spec/integration/recipes/resource_load_spec.rb
Per [RFC](https://github.com/chef/chef-rfc/pull/127).
An example:
```ruby
class MyFile < Chef::Resource
property :path, String, name_property: true
property :content, String
load_current_value do
value_does_not_exist! if !::File.exist?(path)
content IO.read(path)
end
action :create do
if !current_resource
converge_by "Create #{path} with content #{content}" do
IO.write(path, content)
end
elsif content != current_resource.content
converge_by "Update #{path} with content #{content}" do
IO.write(path, content)
end
end
end
end
```
`current_resource` on the provider will be `nil` if the file does not exist, and will be a `MyFile` resource with `path` and `content` filled in if it does exist. Additionally, it fixes a subtle and easy-to-have issue with simple code like above, which happens when …
=> Add Resource.load_current_value

lib/chef/provider.rb, spec/integration/recipes/resource_action_spec.rb
=> Make Resource.action work with non-standard names

lib/chef/cookbook/synchronizer.rb, lib/chef/event_dispatch/base.rb, lib/chef/event_dispatch/dispatcher.rb, lib/chef/formatters/doc.rb, lib/chef/formatters/minimal.rb, spec/unit/event_dispatch/dispatcher_spec.rb, spec/unit/formatters/doc_spec.rb
This has bugged me forever. It does change the API of the Formatter system in a ~non-back-compat way but I don't think I've actually seen any formatters outside of core Chef so how much do we want to worry about this? We could write a shim in `Chef::EventDispatcher::Dispatcher` to check the arity of the method if needed.
Ping @chef/client-core.
=> Make the doc formatter actually show what version of a cookbook is being used.

lib/chef/property.rb, lib/chef/resource.rb, spec/unit/property_spec.rb
Relies on https://github.com/chef/mixlib-log/pull/10
=> Remove freeze of defaults, add warning for array/hash constant defaults

Gemfile, chef.gemspec, lib/chef/config.rb, spec/unit/config_spec.rb
We need a way for `Chef::Config` to pick up `Ohai::Config.ohai` configurables so that Ohai is properly configured at the start of a `chef-client` run.
Adding an empty `ohai` configuration context to `Chef::Config` means append/modify operations (e.g., `ohai.plugin_path << some_path` or `ohai.plugin_path += [ some_path_1, ..., some_path_N ]`) won't work and it's not DRY to copy default values here.
Since the new Ohai configuration uses `ChefConfig::Config`, a `require 'ohai/config'` will make the Ohai configurables available to `Chef::Config`.
Requires a release of Ohai including (at least) [this change](https://github.com/chef/ohai/pull/574).
=> Add ohai configuration context to config.

chef-config/lib/chef-config/path_helper.rb, lib/chef/provider/directory.rb, spec/unit/provider/directory_spec.rb
Currently, Chef will fail to create /usr/local as /usr is no longer writable on OS X 10.11.
To work around this, If a path cannot be written, we do the following:
* Check to see if the path is writable. If is, continue as we normally would.
* Check to see if we are on 10.11 and if it is a SIP path.
* If it is 10.11 and it is a SIP path, check to see if it is on the exception list. If so, return true.
* If it is not 10.11 or a SIP path, return false as you normally would.
I'm sure this could use some tweaking, but I wanted to get the PR up so we could start discussions on it. Without this functionality, Chef will simply break on 10.11 while trying to write /usr/local and any other folder that is an exception path for SIP.
I am with Facebook, so as soon as we are happy with this PR, @jaymzh …
=> Add support for OS X 10.11 SIP paths

chef.gemspec
I see a few uses of `highline` inside core Chef:
```
lib/chef/formatters/indentable_output_stream.rb:          require 'highline'
lib/chef/knife/bootstrap.rb:        require 'highline'
lib/chef/knife/core/ui.rb:          require 'highline'
lib/chef/knife/list.rb:        require 'highline'
```
=> highline is used by core Chef; therefore remove this misleading comment

lib/chef/formatters/error_inspectors/compile_error_inspector.rb, spec/unit/formatters/error_inspectors/compile_error_inspector_spec.rb
Augument runtime errors with additional information that explains why an object might be frozen, and how frozen resource properties are a good thing.
Fixes #3734, for [accepted RFC 55](https://github.com/chef/chef-rfc/pull/135).
=> Add additional helpful section for frozen objects

lib/chef/provider/service/aix.rb, spec/unit/provider/service/aix_service_spec.rb
It will raise an exception if the service is not a group; instead what we want is to check the return code. If 0, it's a group, otherwise, it is not.
Fixes #3730.
=> Don't use shell_out! on "lssrc -g" 

lib/chef/provider/package/rubygems.rb, spec/unit/provider/package/rubygems_spec.rb
This fixes #3382. Let me know if I should add a test to `spec/unit/provider/package/rubygems_spec.rb`, and if so, what it should look like.
Thanks!
=> gem_package should install to the systemwide Ruby when using ChefDK.

lib/chef/provider/service/upstart.rb, spec/unit/provider/service/upstart_service_spec.rb
Custom `status_command`s aren't useable with Upstart, due to this small misconception.
=> shell_out! returns an object not an integer

lib/chef/application/apply.rb
This change simply copies the formatter, force-logger and force-formatter
options across from chef-client/chef-solo to chef-apply. The options are
honored without further changes, and this allows you to force doc formatting
output with chef-apply when the output isn't a terminal.
To test:
```
$ chef-apply -F doc -e "log 'hello world'" | cat # Should use doc formatter instead of logging
$ chef-apply --force-formatter -e "log 'hello world'" | cat # Should use doc formatter instead of logging
$ chef-apply --force-logger -e "log 'hello world'" # This prints double entries in my tests, but the behavior is the same on chef solo
```
=> Add formatter and force-logger/formatter options to chef-apply

chef-config/lib/chef-config/config.rb
With `~/.chef/knife.rb` like below,
```ruby
cookbook_path [
'/home/polamjag/some-chef-repo/cookbooks',
'/home/polamjag/some-chef-repo/site-cookbooks'
]
```
error like this occurs:
```
% knife vault create secrets somesystem '{"foo_passwd": "p@ssw0rd"}' -V
INFO: Using configuration from /home/polamjag/.chef/knife.rb
ERROR: Errno::ENOENT: No such file or directory @ dir_s_mkdir - /home/polamjag/some-chef-repo/data_bags/home/polamjag/some-chef-repo/data_bags/secrets
```
This PR fixes that.
=> uniquify chef_repo_path

lib/chef/resource/deploy.rb, spec/unit/resource/deploy_spec.rb
This change would allow to override depth on deploy.
include_recipe 'deploy'
r = resources('deploy[/srv/www/simpleapp]')
r.depth 1
this also would allow to set depth when creating a deploy resource.
deploy 'test repo with depth' do
repo 'https://github.com/renanvicente/lab_ecommerce_simple'
user 'root'
depth 1
deploy_to '/tmp/test_with_depth'
action :deploy
end
why we need that?
Some times you may have a git repo with a large .git and you do not want to clone everything because it will take to long. We have shallow_clone but it only allow changing it to 5.
=> Add support for override depth and adding test in overriding depth

CHANGELOG.md, lib/chef/mixin/template.rb, lib/chef/provider/template/content.rb, lib/chef/resource.rb, spec/data/cookbooks/openldap/templates/default/helpers.erb, spec/unit/cookbook/syntax_check_spec.rb, spec/unit/provider/template/content_spec.rb
adds:
- cookbook_name
- recipe_name
- recipe_line_string
- recipe_path
- recipe_line
- template_name
- template_path
accessible both as instance var (@-) and method (bare), like @node/node.
closes #2984
=> CHEF-5012: add methods for template breadcrumbs

CHANGELOG.md, lib/chef/cookbook/metadata.rb, spec/unit/cookbook/metadata_spec.rb
This adds a `privacy` flag to `metadata.rb` which will mark a cookbook as private (or not).  If you try to upload a cookbook marked private to Supermarket, and Supermarket is configured to enforce privacy, then the upload will fail.
Here is the original issue this was spawned from:  https://github.com/opscode/supermarket/issues/832
Here is the matching PR to Supermarket itself:  https://github.com/opscode/supermarket/pull/912
I tested this by doing `knife cookbook upload` of a cookbook with the `privacy` attribute set to true, against Chef Server 12.2.0.dev.0 running in a local VM and it succeeded.
Is there any further testing I should do or anything I've overlooked here?
=> Add privacy flag

spec/unit/provider/directory_spec.rb
do_selinux needs to be mocked out so it does not actually do anything.
Otherwise, it will be available on rhel and the tests are no longer
unit and will fail
=> Fix failing directory unit tests on rhel

lib/chef/provider/group/pw.rb
This was causing the
```
Chef::Resource::Group
group modify action
when there is a group
behaves like correct group management
when the users exist
when append is not set
when group already contains some users
should remove all existing users and only add the new users to the group
```
spec to fail. The test passes an array which gets modified which breaks the test.
=> Don't modify members of new_resource in pw group implmentation

lib/chef/mixin/windows_architecture_helper.rb, lib/chef/provider/batch.rb, lib/chef/provider/powershell_script.rb, lib/chef/provider/windows_script.rb, lib/chef/win32/api/system.rb, lib/chef/win32/process.rb, lib/chef/win32/system.rb, spec/functional/resource/powershell_script_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb, spec/unit/mixin/windows_architecture_helper_spec.rb
Adding in support for 64-bit Ruby for Windows Powershell & Batch scripts.
Primarily, the change involves support for the :i386 architecture flag - which, if set when running under a 64-bit Ruby environment, will override the binary path for Powershell or cmd.exe to the appropriate SysWow64 location.
Sample test recipe:
powershell_script '64demo32' do
code 'echo hello'
architecture :i386
end
@adamedx @ksubrama @chef/client-windows
=> Enable 64-bit support for Powershell and Batch scripts

spec/functional/resource/dsc_script_spec.rb
dsc_script_spec.rb currently fails under 64-bit Ruby. The fix here is to make sure we ensure that the node architecture for the test is always set to 64-bit (since dsc is not supported on 32-bit Windows).  
@adamedx @jaym
=> Fix dsc_script spec failure on 64-bit Ruby

lib/chef/platform/provider_mapping.rb, spec/integration/recipes/recipe_dsl_spec.rb
The warning incorrectly said that the provider was missing
`resource_name :resource` when it should have said it was
missing `provides :resource`
I also switched from using `begin`...`rescue` since it isn't needed and
needlessly slow things up.
I think I got the logic right, but would appreciate a careful review.
Fixes #3614
=> Fix error message for providers without `provides`

lib/chef/provider/powershell_script.rb, spec/functional/resource/powershell_script_spec.rb
Powershell script validation did not use same architecture as
executing the script. This caused configuring the LCM to fail.
=> Fix powershell_script validation 

CHANGELOG.md, lib/chef/provider/service.rb, lib/chef/provider/service/freebsd.rb, lib/chef/provider/service/gentoo.rb, lib/chef/provider/service/init.rb, lib/chef/provider/service/openbsd.rb, lib/chef/provider/service/redhat.rb, lib/chef/provider/service/simple.rb, lib/chef/resource/service.rb, spec/unit/provider/service/gentoo_service_spec.rb, spec/unit/provider/service/openbsd_service_spec.rb, spec/unit/provider/service/redhat_spec.rb, spec/unit/resource/service_spec.rb
- redhat provider now allows the user to override :status
- gentoo provider now allows the user to override :status and :restart
- service providers now dup the status hash and mutate their private
copy instead of mutating the new_resource
closes #2168
=> fix supports hash issues in service providers

chef.gemspec
This is causing problems now that i've released mixlib-shellout 2.2.0.rc.0. Omnibus builds are failing with:
```
Error:
ERROR:  While executing gem ... (Gem::DependencyError)
Unresolved dependency found during sorting - mixlib-shellout (~> 2.0) (requested by chef-config-12.5.0.current.0)
C:/rubies/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/omnibus-bd748305e15c/lib/omnibus/util.rb:101:in `rescue in shellout!'
C:/rubies/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/omnibus-bd748305e15c/lib/omnibus/util.rb:97:in `shellout!'
C:/rubies/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/omnibus-bd748305e15c/lib/omnibus/builder.rb:701:in `shellout!'
C:/rubies/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/omnibus-bd748305e15c/lib/omnibus/builder.rb:239:in `block in gem' …
```
=> Use same mixlib-shellout version pin in chef, ohai, and chef-config

lib/chef/knife/node_run_list_remove.rb, spec/unit/knife/node_run_list_remove_spec.rb
This adds a warning when the item to be removed doesn't exist in the runlist.
A simple quality of life improvement for people who might try to remove an item without wrapping it in 'recipe[]'.  Previously, the feedback was the unchanged runlist without any reason why the remove operation didn't do anything.
=> Add warnings to 'knife node run list remove ...' 

lib/chef/provider/deploy.rb, spec/functional/resource/deploy_revision_spec.rb, spec/unit/provider/deploy_spec.rb
Should help with troubleshooting failed migrations
Solves [CHEF-2861](https://tickets.opscode.com/browse/CHEF-2861)
=> Migrated deploy resource to use shell_out instead of run_command

lib/chef/knife/bootstrap.rb, lib/chef/knife/bootstrap/client_builder.rb, lib/chef/knife/core/bootstrap_context.rb, spec/unit/knife/bootstrap/client_builder_spec.rb, spec/unit/knife/core/bootstrap_context_spec.rb
I can set attributes, environment, and run_list during a `knife bootstrap`, but why not tags?
Some of our recipes are driven off of tags, such as for sudo access or
membership in a load balancing pool.
If this patch is accepted then I will add the corresponding feature to
[knife-vsphere](https://github.com/ezrapagel/knife-vsphere).
=> Allow tags to be set on a node during bootstrap

lib/chef/provider/subversion.rb, lib/chef/resource/subversion.rb, spec/unit/provider/subversion_spec.rb, spec/unit/resource/subversion_spec.rb
output_of_command doesn't work properly on Windows (see chef/chef#1533)
=> Replace output_of_command with shell_out! in subversion provider

Gemfile, lib/chef/formatters/doc.rb, spec/unit/formatters/doc_spec.rb
This pull request will convert elapsed time from seconds to minutes and seconds if it's more than 60 seconds, convert it to hours, minutes and seconds if it's more than 3600 seconds to contribute for more human readable output.
=> Human friendly elapsed time in log

CHANGELOG.md, lib/chef/deprecation/provider/remote_directory.rb, lib/chef/provider/remote_directory.rb, spec/unit/provider/remote_directory_spec.rb
- Huge speed and memory perf boost.  In the prior code if you were
copying 10 dotfiles to a home directory with a million files in it,
would slurp all million directory entries into a ruby Set object even if you were
not ultimately going to purge the unmanaged files.  This code inverts
the logic and tracks managed files and then iterates through the
filesystem without slurping a list into memory.
- Only do file purging logic if purging is set.
- Fixes mutation of new_resource.overwrite.
- Fixes mutation of new_resource.rights (subtle).
- Adds helper delegators to the new_resource properties.
- Deprecates (instead of removes) now-unused methods.
- Renamed a method (with deprecated alias preserved) for consistency.
- Adds YARD for everything.
- Changes protected to private because protected …
=> refactor remote_directory provider

Gemfile, pedant.gemfile
We're seeing two sets of failing test. The first is due to a release of chef-zero. It makes assumptions of V1 apis, breaking some of the integration tests.
The other is due to a release of cheffish. This will be fixed by https://github.com/chef/cheffish/pull/73
=> Fix the failing tests

lib/chef/monkey_patches/win32/registry.rb, lib/chef/win32/api/registry.rb, lib/chef/win32/registry.rb, spec/functional/win32/registry_helper_spec.rb, spec/unit/registry_helper_spec.rb
Re-creation of #3870 for @mcquin because I couldn't force AppVeyor to re-run.
- Adds monkeypatches for Win32::Registry#delete_key and Win32::Registry#delete_value. 
- Rewrites Chef::Win32::Registry#delete_key to use Win32::Registry#delete_key.
(Note: Once this is merged, I will move the [Win32::Registry#write monkeypatch](https://github.com/chef/chef/blob/master/lib/chef/win32/unicode.rb#L62-L87) into `lib/chef/monkey_patches/win32/registry.rb` for consistency. Doing so here is outside the scope of this PR.)
=> Monkeypatch Win32::Registry methods delete_key, delete_value

lib/chef/monkey_patches/win32/registry.rb, lib/chef/win32/unicode.rb
Moves the monkeypatch for `Win32::Registry#write` from some random file into the file with all the other `Win32::Registry` monkeypatches.
=> Put all Win32::Registry monkeypatches together

spec/functional/win32/registry_spec.rb, spec/unit/win32/registry_spec.rb
Two files are testing `Chef::Win32::Registry`. Their spec paths should be `spec/*/win32/registry_spec.rb`.
=> Modify registry specs to adhere to spec naming conventions

appveyor.yml
Appveyor was running on 2012R2 - I guess Windows Server 2012 was just a shorthand for R2.  I've changed it to make this explicit.
=> Update appveyor.yml to correct OS version

lib/chef/win32/crypto.rb
The issue here is the user profile does not get loaded when
running over winrm / as a service. This user profile is needed
to use the DPAPI to encrypt the data for the current user.
Should fix #3246 
The other solution is to call `LoadUserProfile` and `UnloadUserProfile` for the current user. This is complicated as it is slow and requires managing the profile handle through the entire chef run as we need to clean it up after we are done. The benefit is that in order to decrypt the data, you need to control the account. With `CRYPTPROTECT_LOCAL_MACHINE`, logging onto the machine is sufficient the decrypt.
cc @smurawski @btm @adamedx @ksubrama
=> Fix issue where ps_credential does not work over winrm

lib/chef/platform/query_helpers.rb, lib/chef/provider/dsc_resource.rb, spec/functional/resource/dsc_resource_spec.rb, spec/unit/platform/query_helpers_spec.rb, spec/unit/provider/dsc_resource_spec.rb
Remove implicit test assumption that the machine is configured so that `'RefreshMode'` is `'Disabled'` for DSC resource.
=> Skip tests unless RefreshMode is Disabled

spec/unit/mixin/enforce_ownership_and_permissions_spec.rb
This should fix the remaining failures for ruby 2.1 (#3894). Seems like the passwd struct changed. `describe_changes` also called platform specific things on windows, which started failing.
cc @chef/client-windows
=> Modify enforce_ownership_and_permissions_spec to be more unit-like

lib/chef/local_mode.rb, lib/chef/monkey_patches/webrick-utils.rb
Ruby 2.1 introduces a regression on Windows in WEBrick.
create_listeners does not throw an exception when we're
already listening on a port. This seems to only be an
issue on Windows. This patch reverts it back to what it
was in Ruby 2.0
It seems the regression was introduced in
https://github.com/ruby/ruby/commit/b1f493dcd1092fe17cccec998e175516ed5c6e47#diff-4b178393150b2b3a5ec9d77eced1f09e
This should fix the failures in the knife integration tests (see #3894)
cc @chef/client-windows @jkeiser
=> Add monkey patch for webrick

spec/functional/resource/windows_service_spec.rb
We thing that these tests may be causing instability on our
jenkins slaves.
cc @sersut @chef/client-windows
=> Allow windows_service_spec to only run in appveyor

lib/chef/dsl/reboot_pending.rb, spec/functional/dsl/reboot_pending_spec.rb, spec/unit/dsl/reboot_pending_spec.rb
The pending reboot functional tests fail on checks for HKLM\SOFTWARE\Microsoft\Updates\UpdateExeVolatile with the value of 1-3. A clean 2k8r2 sp1 machine has a 3 which persists after reboots. The only way to remove it is to do so manually.
This key was introduced in the windows package installer on windows server 2003 and windows XP. It indicates that a previously installed update requires a reboot in order to complete. See https://support.microsoft.com/en-us/kb/832475
There are many folks running into issues installing various products and being told that a reboot is required and they get stuck because they receive this message after every reboot. This seems to occur most commonly with older office or sharepoint products. The guidance tends to be to delete this key. Apparently it can be …
=> remove pending reboot check for HKLM\SOFTWARE\Microsoft\Updates\UpdateExeVolatile

spec/support/shared/unit/provider/file.rb
The verify tests were not correctly mocking things out. This was causing the tests to actually shellout
for verify, it this started breaking because of an implementation detail that was part of the mixlib-shellout 2.2.1 release
=> Fix failing specs on Windows

lib/chef/resource.rb, spec/integration/client/client_spec.rb, spec/unit/property_spec.rb
1.  the deploy resource and other internal chef resources trigger this.
2.  this is largely a non-problem since people have been happily using
the deploy resource for years and nobody has showed up in any of our
bugtrackers due to mutating the default hash.  we simply don't need to
annoy people this badly over this.
=> move warning to debug

lib/chef/resource.rb, spec/integration/recipes/resource_load_spec.rb
Resolves https://github.com/chef/chef/issues/3897
@jkeiser @jaymzh @chef/client-core
=> Rename current_resource method on Chef::Resource as current_value.

chef-config/lib/chef-config/config.rb, lib/chef/client.rb, lib/chef/exceptions.rb, lib/chef/knife/core/node_presenter.rb, lib/chef/knife/search.rb, lib/chef/node.rb, lib/chef/policy_builder.rb, lib/chef/policy_builder/dynamic.rb, lib/chef/policy_builder/expand_node_object.rb, lib/chef/policy_builder/policyfile.rb, spec/unit/client_spec.rb, spec/unit/node_spec.rb, spec/unit/policy_builder/dynamic_spec.rb, spec/unit/policy_builder/expand_node_object_spec.rb, spec/unit/policy_builder/policyfile_spec.rb
This patch integrates `policy_name` and `policy_group` into the node object, with the following behavior changes:
- Policyfile attributes can be set on `Chef::Node` objects
- Policyfile attributes are included in the serialization format (JSON)
- Policyfile attributes are persisted between runs, when using a Chef Server that supports them
- Policyfile attributes can be set in the JSON file passed to `chef-client -j JSON_FILE`
- Policyfile attributes are shown by `knife search` and `knife node show`, if present
- Policyfile attributes are searched in the `knife search` "fuzzy" query (which is invoked when the given query doesn't match the `key:value` format).
- The `use_policyfile` feature flag in config is effectively a no-op.
See also the related Chef Server change, which will be …
=> Policyfile node integration

chef-config/lib/chef-config/config.rb, lib/chef/application/client.rb, lib/chef/policy_builder/policyfile.rb, spec/unit/application/client_spec.rb, spec/unit/policy_builder/policyfile_spec.rb
Named run list support has existed for quite a while in ChefDK, this allows the user to actually select a named run list. I need to do an end-to-end test, but the code is ready for review.
@chef/client-core @kisoku
=> Policyfile named run list support

spec/support/shared/context/win32.rb, spec/unit/platform/query_helpers_spec.rb, spec/unit/provider/service/windows_spec.rb, spec/unit/win32/registry_spec.rb
Calling `Object.send(:remove_const, 'Win32')` in spec after blocks causes failures in specs which include libraries with rely on Win32.
=> Safely clean up Win32 namespace after specs

lib/chef/platform/query_helpers.rb, lib/chef/provider/package/windows/msi.rb, spec/unit/platform/query_helpers_spec.rb
This change loads the MSI Installer API only if the platform supports it.  This is currently mostly an issue for Windows Nano.  The current check for MSI uses the registry directly - a longer term change will probably use a Ohai plug-in or other mechanism.
cc @chef/client-windows @chef/client-core
=> Lazy load MSI provider, add check for MSI support

lib/chef/property.rb, lib/chef/resource.rb, spec/unit/property_spec.rb
Fixes #3950 . The issue is that in 12.4.1, if you specify both `default` and `name_attribute` in an attribute, it will pick whichever comes first. In 12.5, it always picks `default`. This restores the old (weird) behavior for backwards compatibility's sake.
=> Honor the ordering of whichever `name_attribute` or `default` comes first

bin/chef-service-manager
we are currently running from instead of guessing where it is
=> Run the chef service executable from the bin directory

lib/chef/knife/bootstrap.rb, lib/chef/knife/bootstrap/client_builder.rb, lib/chef/knife/core/bootstrap_context.rb, spec/unit/knife/bootstrap/client_builder_spec.rb, spec/unit/knife/bootstrap_spec.rb, spec/unit/knife/core/bootstrap_context_spec.rb
Adds `--policy-name` and `--policy-group` options to knife bootstrap, which will be passed on to the node via the first-boot JSON file.
Note that this changes the bootstrap behavior for non-policyfile usage when the user does _not_ specify an environment. Before this patch, knife would pass `-E _default` to the node, whereas now it does not give a `-E` option in the default case. The node should still default to an environment of `_default`. Looking in the git history, I didn't find a specific reason for the existing behavior.
=> Add policyfile support to `knife bootstrap`

chef-config/lib/chef-config/config.rb, chef-config/spec/unit/config_spec.rb
This resolves an issue where running `chef-client -c client.rb -z` will
attempt to create the local mode cache at the filesystem root with an
error like:
```
ERROR: Permission denied @ dir_s_mkdir - /local-mode-cache
```
=> Derive config locations from absolute path to config file

chef-config/lib/chef-config/config.rb, chef-config/spec/unit/config_spec.rb
Allows `knife` and such to parse config files with `chefdk.settting` in
them without error.
I have tested this via manually patching my chefdk, and I am able to set `config_strict_mode true` in chef-dk while allowing the config context to be non-strict when knife evaluates it.
=> Create empty config context for chefdk

RELEASE_NOTES.md
Pending https://github.com/chef-cookbooks/windows/pull/278
@chef/client-windows
=> Windows cookbook dependencies should be updated for Chef 12.5

lib/chef/property.rb, spec/unit/property_spec.rb
Currently this will fail:
```
class X < Chef::Resource
property :x, name_property: true
end
class Y < X
property :x, name_attribute: true
end
```
Because when `name_property` is inherited to `name_attribute`, the properties conflict.
=> Make sure name_attribute works on derived properties

lib/chef/policy_builder/expand_node_object.rb, spec/unit/policy_builder/expand_node_object_spec.rb
Some third-party tools are using this, we need it to work.
In particular, we are seeing these in ChefDK's verification tests for ChefSpec:
```
ERROR: Chef failed to converge: undefined method `load_node' for #<Chef::PolicyBuilder::ExpandNodeObject:0x007fb49bbf8c48>
```
=> Un-remove ExpandNodeObject#load_node, deprecate it

lib/chef/file_content_management/tempfile.rb, lib/chef/provider/template/content.rb, spec/unit/provider/template/content_spec.rb
The template resource should honor the file_staging_uses_destdir flag. The current behavior is that the rendered templates are always created in the 'tmp' directory. This change switches over the template provider to have the same behavior as the file provider.
@chef/client-core @adamedx
=> Use Chef::FileContentManagement::Tempfile to create temp file

lib/chef/node.rb, lib/chef/run_list/versioned_recipe_list.rb, spec/unit/client_spec.rb, spec/unit/run_list/versioned_recipe_list_spec.rb
Prior to chef 12.2 we included unexpanded 'cookbook' names for default
recipes. In 12.2, we moved to expanded ('cookbook::default') names,
which broke some searches.
However, some of our users have now moved to searching for expanded,
so we need to cater for both.
Fixes #3767
cc @lamont-granquist @chef/client-core
=> Ensure that our list of recipes is backwards compat

lib/chef/provider/service/redhat.rb
Fixing https://github.com/chef/chef/issues/3992 
Instead of just checking for the missing service, check if a custom command was provided for the action as well. If neither is provided throw Chef::Exceptions::Service pointing at a missing init.d script or custom command for action.
=> Fix for #3992: Add check for custom command in redhat service provider

lib/chef/resource/windows_script.rb, spec/functional/resource/powershell_script_spec.rb, spec/spec_helper.rb, spec/support/shared/functional/windows_script.rb, spec/unit/resource/powershell_script_spec.rb
Raise an error when specifying `architecture :i386` for the `powershell_script` resource or guard on Windows Nano Server.
=> Raise error when running 32-bit scripts on Windows Nano.

lib/chef/application/apply.rb, lib/chef/application/client.rb, lib/chef/application/knife.rb, spec/unit/application/client_spec.rb, spec/unit/application/knife_spec.rb
Older terminal applications on Windows displayed garbage characters instead of altering the color of text in the terminal as a response to color escape sequences. In Win2k12 and newer, the default Windows terminal displays colored text correctly. To reflect this, the defaults on chef-cient, chef-apply, and knife are being changed to be like all other operating systems and use color by default. cc @jaym, @mwrock, @chefsalim, @ksubrama, @McQuin.
=> Windows cli tools should have color true by default

lib/chef/provider/user/windows.rb, spec/functional/resource/user/windows_spec.rb, spec/unit/provider/user/windows_spec.rb
This fixes #4024 and ignores the `gid` attribute on the windows platform. This also emits a warning if the gid is used on windows and suggests that the user use the `group` resource.
I had originally addressed this fix by implementing the gid/user association and adding the user to the group. However, I have switched to this approach for the following reasons:
1. The `gid` in linux refers to a user's "primary" group. Technicaly there is such a term in the windows API but it is conceptually different from linux and has no mapping to a specific local windows group.
2. Treating the gid as a local windows group is awkward because the gid/uid relationship in linux is 1 user to 1 group while windows users can be assigned to many local groups.
3. The implementation in windows is fairly verbose …
=> ignore gid in the user resource on windows

Gemfile, lib/chef/application/apply.rb, lib/chef/application/client.rb, lib/chef/application/solo.rb, lib/chef/client.rb, spec/integration/client/client_spec.rb
dumps a large call graph into /var/chef/cache/graph_profile.out
=> add optional ruby-profiling with --profile-ruby

lib/chef/application/apply.rb
The chef-apply option flags should trail the recipe or recipe text
that is being applied.
This updates the chef-apply banner to show the correct usage.
Fixes #2372
=> Fix chef-apply usage banner

lib/chef/mixin/properties.rb, lib/chef/resource.rb, spec/unit/mixin/properties_spec.rb
It'd be nice to be able to write:
```ruby
module SecureThing
include Chef::Property::Mixin
property :mode
property :user
property :group
end
class File < Chef::Resource
property :path, name_property: true
include SecureThing
property :content, String
end
class Directory < Chef::Resource
property :path, name_property: true
include SecureThing
property :content, String
end
```
Also, I'd love to separate out this functionality so we can use it in things that aren't resources.
=> Make property modules possible

CHANGELOG.md, lib/chef/chef_fs/file_system/file_system_entry.rb, spec/integration/knife/download_spec.rb
A FileSystemEntry with a nil parent is a "root directory" and thus
should exists so long as its filesystem path exists. This was preventing
the download of files such as invitation.json whose parent directory is
a root directory.
=> Allow downloading of root_files in a chef repository

lib/chef/application/windows_service.rb, spec/unit/windows_service_spec.rb
This adds a logger to shellout when spawning a client run in the windows service so that any debug logging regarding process creation/destruction can be captured. This accompanies but can be deployed independently of https://github.com/chef/mixlib-shellout/pull/110
=> add logger to windows service shellout

README.md
Also updated CodeClimate badge URL. Either will work, but 'chef' and not 'opscode' is now canonical.
=> Mailing list has moved to Discourse.

lib/chef/cookbook/cookbook_collection.rb, lib/chef/cookbook/metadata.rb, lib/chef/exceptions.rb, lib/chef/policy_builder/expand_node_object.rb, lib/chef/policy_builder/policyfile.rb, spec/integration/client/client_spec.rb, spec/integration/knife/upload_spec.rb, spec/integration/solo/solo_spec.rb, spec/unit/cookbook/metadata_spec.rb, spec/unit/policy_builder/policyfile_spec.rb
This allows knife to upload cookbooks containing chef_version and ohai_version.  When the chef-client downloads cookbooks with constraints it checks them and throws an exception if the constraints do not match.  The knife command will upload cookbooks which do not match the version constraint (this is deliberate in the case where knife workstation versions differ from chef-client production versions -- injecting the production chef-client version into knife to prevent uploads is out-of-scope).
Also out of scope - including these into /universe, teaching berkshelf and the policyfile depsolver to avoid them, injecting production chef-version values into policyfiles, teaching the cookbook_versions endpoint to filter based on chef_version, etc, etc, etc, etc, etc....  This is only step number …
=> RFC-037:  add chef_version and ohai_version metadata

CHANGELOG.md, lib/chef/knife/core/bootstrap_context.rb, spec/unit/knife/core/bootstrap_context_spec.rb
A customer noticed this issue when using `knife bootstrap` with vCO and the color bits messing up the logging of the chef-client's output.
@btm suggested the line to add in `bootstrap_context.rb`.  I updated some existing tests to pass and added a new one "when color is true".
Submitting PR for merge.
=> Update knife bootstrap command to honor --no-color flag in chef-client run that is part of the bootstrap process.

lib/chef/property.rb, spec/unit/property_spec.rb
The scenario: I'd like to use a custom property type so I can override `emit_dsl` and make the property's method a little different. But Property.derive doesn't retain the class by default--it just creates a Property, losing the class information.
=> Make Property.derive create derived properties of the same type

CHANGELOG.md, lib/chef/knife.rb, spec/unit/knife_spec.rb
ChefFS-based commands have a superclass (Chef::ChefFS::Knife) which
defines its own inherited method that calls super. This breaks our
detection of where the subcommand is defined since the file with
the definition is no longer at the top of the call stack.
This commit special-cases subclasses with a superclass of
Chef::ChefFS::Knife to account for this.
Fixes #4089
=> Improve detection of ChefFS-based commands in `knife rehash`

lib/chef/http.rb, spec/unit/http_spec.rb
Includes https://github.com/chef/chef/pull/3444 and fixes pull request comments, adds retries for connection resets, and adds tests for retries for the Chef::HTTP base class.
=> SSL and Connection Reset Error Retries

lib/chef/http.rb
if this is always required then everything that uses Chef::HTTP will
load up chef-zero which will load up Webrick, which does DNS lookups
of the current host which causes a DNS lookup and possible timeout.
it also likely isn't doing pretty things to chef-client memory usage
and load times there as well.
=> lazy the socketless require in Chef::HTTP

lib/chef/application/windows_service.rb, lib/chef/application/windows_service_manager.rb, spec/unit/windows_service_spec.rb
Currently the windows service manager passes a log_location to the windows service at startup. Once the service is installed, this lof_location cannot be changed and overrides any log_location set in the client.rb. This PR allows a windows service to be installed with no log_location passed to the windows service. In such a case, the service will always use what is in the client.rb or the typical default path if none is configured.
=> windows service uses log file location from config if none is given on commandline

spec/unit/knife_spec.rb
This was failing on both my and btm's machine. No idea how it passes
in other places.
=> Fixed knife_spec unit test

lib/chef/knife/bootstrap.rb, spec/unit/knife/bootstrap_spec.rb
IMO it's a bug in knife-ec2 but it worked before and there could be lots of plugins relying on the behavior so it needs to just work.
Fixes https://github.com/chef/chef/issues/4131
@btm
=> Handle nil run list option in knife bootstrap

lib/chef/knife.rb, spec/unit/knife_spec.rb
When something goes wrong in knife it is common to get an error like:
```Exception: NoMethodError: undefined method `empty?' for nil:NilClass```
Without a file and line number, you can't tell even which project this came
from, e.g. core chef or knife-ec2?
The current message suggests collecting -VV output for filing a bug report,
which will now include the backtrace and be incredibly helpful.
=> don't squash Chef::Config[:verbosity] on subsequent instances of Chef::Knife::Bootstrap

lib/chef/application/windows_service.rb, spec/unit/windows_service_spec.rb
The changes made here in 20728416579f40c30e0a9c08bdfd86ecd7391cbe had an incorrect assumption about the default `Chef::Config[log_location]`. It assumed `nil` when it is actually `STDOUT`. This PR uses the following logic to determine where the windows service tells `chef-client` to send logging:
* If a location is sent on the command line, that is merged with `Chef::Config` and used for logging
* ELSE If a file path is configured in the config file, that is used
* ELSE if `STDOUT` (the default) is configured, then the `DEFAULT_LOG_LOCATION` path is used
* ELSE we have some other logging class configured (not a file path) like an event viewer and no log_location is sent to chef-client
=> fix log location resolution in windows service

MAINTAINERS.toml
Supermarket uses this file to track maintainers and is currently
case-sensitive. `agentmeerkat` is [`AgentMeerkat`](https://github.com/agentmeerkat)
under the hood.
=> Correct capitalization of GitHub username of a maintainer

.gitignore, lib/chef/resource/lwrp_base.rb
- add pedant.gemfile.lock to .gitignore
- remove redundant `def lazy` from LWRPBase now that Chef::Resource implements it
=> Minor tree cleanup I noticed

lib/chef/knife/core/node_presenter.rb, lib/chef/node.rb, lib/chef/recipe.rb, spec/unit/node_spec.rb, spec/unit/recipe_spec.rb, spec/unit/resource/chef_gem_spec.rb
Fixes ``` undefined method `include?' for nil:NilClass``` when using tag() in the recipe DSL.
=> Use the initializer to avoid NoMethodError on nil.include?

lib/chef/provider/package/yum.rb, spec/unit/provider/package/yum_spec.rb
Fedora 21+ use dnf as the primary package manager.  Lamont added code in
12.5 to allow for a yum compat mode. This doesn't entirely work though
as we need yum-dump.py to correctly run.  We were parsing the shabang in
the yum binary to find the path to python.  On a dnf system the yum
binary is a bash script though so we were trying to run yum-dump.py
using bash which obviously fails.  I added a fallback method to use
python if the shebang parsing returns bash. With this in place AND the
yum package installed you can use the package resource on Fedora.
Before this patch:
Before:
Error executing action `install` on resource 'yum_package[java-1.8.0-openjdk]' …
=> Use the proper python interpretor for yum-dump.py on Fedora 21+

lib/chef/provider/package/solaris.rb
This follows the same convention that the [AIX package provider](https://github.com/johnbellone/chef/blob/master/lib/chef/provider/package/aix.rb#L122) has done and adds an alias_method.
/cc @pburkholder @acaiafa
=> package/solaris: Adds alias method for upgrade_package.

lib/chef/digester.rb, lib/chef/provider/remote_file/cache_control_data.rb, spec/unit/provider/remote_file/cache_control_data_spec.rb
We want to support a fips mode, and doing MD5 with fips mode enabled
is wrong/hard. In this case, the type of checksum does not
matter, so let's just use sha256 since fips mode will be happy
with that.
For cases where the cache control data exists, we update it
to provide a seamless upgrade.
=> Modify remote_file cache_control_data to use sha256 for its name 

chef-config/lib/chef-config/config.rb, chef-config/spec/unit/config_spec.rb, lib/chef/event_dispatch/dispatcher.rb, lib/chef/event_dispatch/events_output_stream.rb, lib/chef/formatters/base.rb, lib/chef/formatters/indentable_output_stream.rb, lib/chef/provider/execute.rb, lib/chef/resource/execute.rb, spec/support/shared/unit/execute_resource.rb, spec/unit/provider/execute_spec.rb, spec/unit/provider/script_spec.rb
This brings live streaming of execute resource output to the output
formatters. It also adds a mechanism for checking to see if an output
formatter is in use through the event dispatch system.
It adds a new configuration option, "always_stream_execute", which does
what it says on the tin.
(This is a rebase and fixup of Adam's work in #2788, cc @adamhjk @chef/client-core)
Fixes #2788
=> Implement live streaming for execute resources

chef.gemspec
pinning to 3.3.x as a temp fix
=> rspec 3.4.0 broke master

chef.gemspec, lib/chef/audit/runner.rb, spec/functional/audit/runner_spec.rb
to be the cookbooks (see http://rspec.info/blog/2015/11/rspec-3-4-has-been-released/, Better Failure Source Detection, for more info)
=> Restore rspec 3.4 by setting project_source_dirs

CHANGELOG.md, lib/chef/provider/package.rb, lib/chef/provider/package/openbsd.rb, lib/chef/resource/package.rb, lib/chef/resource/windows_package.rb, spec/unit/provider/package_spec.rb
This allows a subclass of Chef::Provider::Package to declare package_class_supports_arrays which will cause the superclass to only pass arrays into the child class.  This gets rid of most of the need for the subclass to have `.is_a?(Array)` checks everywhere and just use Arrays internally.
I developed this against #4106, but that got stalled due to unrelated chocolatey.org issues, and want to use this in the Zypper provider to rework #4102 (along with eventually using this in the yum and apt providers, but those are large yaks for another day...)
=> Multipackage internal API improvements

lib/chef/application/client.rb
nil default in application/client.rb shadowed any value from config when executing chef-client (but not chef-shell -z)
default in config is set to nil at https://github.com/chef/chef/blob/b0dbe243d469cc36477ba8102b74a8456b6f276d/chef-config/lib/chef-config/config.rb#L363, so otherwise this change is a no-op
=> Allow named_run_list to be loaded from config

DOC_CHANGES.md, lib/chef/platform/query_helpers.rb, lib/chef/provider/dsc_resource.rb, lib/chef/resource/dsc_resource.rb, spec/unit/provider/dsc_resource_spec.rb, spec/unit/resource/dsc_resource_spec.rb
Closes #4156 
Adds the reboot_action to dsc_resource
```
dsc_resource 'Install AD' do
resource :windowsfeature
property :name, 'ad-domain-services'
reboot_action :reboot_now
end
```
and 
Allows the LCM to stay enabled for PowerShell builds of 10586 or newer.
=> WMF 5 and Win 10 Threshold 2 Allow dsc_resource with the LCM enabled.

README.md
Per @btm's suggestion and the conversation at today's Developers Meeting, add some links to provide an easy way to join IRC and view read-only channel logs.
Looks like my editor automatically stripped some extra whitespace too. Let me know if you want me to remove that from the PR, but I'm assuming it shouldn't have been there anyway.
=> Documentation update: add README.md links to join IRC channels

lib/chef/provider/dsc_resource.rb
This fixes a regression in the Nov 2015 update of Windows 10 where we are not putting any output in the converge description.  This is because the Nov 2015 update has started using the verbose stream instead of stdout. This is actually a good thing, as the use of stdout was a hack.  But now we need to check for both conditions.
@btm @adamedx @smurawski @jaym
=> Update dsc_resource to use verbose stream output

CHANGELOG.md, lib/chef/provider/package/dpkg.rb, spec/unit/provider/package/dpkg_spec.rb
- :update and :install are now treated the same way and throw the
same exceptions
- :remove and :purge don't require the source at all, so don't do
any checking on that
- fix some convoluted side-effecty logic in load_current_resource
- load_current_resource now correctly gets the dpkg state on
:remove and :purge when the file does not exist (pretty sure
the old logic did not)
- fixed the FIXME about using en_US.UTF-8 (the default for shell_out!)
- just use shell_out! to throw exceptions
- clean up all the specs and remove all the instance vars from the code
=> dpkg provider cleanup

lib/chef/resource/dsc_resource.rb, lib/chef/util/powershell/ps_credential.rb, spec/unit/util/powershell/ps_credential_spec.rb
See the following use of a DSC resource -- note that it dumps out the password (which itself was not obvious in the code because an environment variable was used to obtain it). On failure (failure was expected in this case), the password, in this case '\\sea-adamed1', is displayed on the screen.
```
Resource Declaration:
---------------------
4: dsc_resource 'Create Test User' do
5:   resource :user
6:   #  property :username, 'testuserps5'
7:   property :username, 'testuserps5__\\'
8:   property :password, ps_credential(ENV['COMPUTERNAME'])
9:   property :ensure, 'Present'
10: end
11:
Compiled Resource:
------------------
dsc_resource("Create Test User") do
action [:run]
retries 0
retry_delay 2
default_guard_interpreter :default
properties {:username=>"testuserps5__\\", …
```
=> Prevent inspect on PsCredential from printing out plain text password

lib/chef/provider/service.rb
add better docs on why we mutate the new-resource in the service provider for reporting
=> add better docs on why we mutate the new-resource in the service provider for reporting

lib/chef/knife/ssh.rb
I ran into a NameError when trying to run https://github.com/matschaffer/knife-solo/blob/master/test/knife_bootstrap_test.rb#L14 that this fixes.
My suspicion is that under normal operation shell_out gets required via the application or platform. And prior to moving config into its own project it was being required in chef/config.rb
In my tests since I end up loading knife ssh directly without the surrounding application things don't work out.
I'll likely just add a line to my test helper for now but wanted to open this for comment or future improvement.
=> Require ShellOut before Knife::SSH definition

spec/tiny_server.rb, spec/unit/knife/ssl_check_spec.rb
we can't fork off tinyserver without a lot of work in the test
codebase, so instead save a copy of the old rspec signal handler and then
after tinyserver has started (and we're sure that rack has scribbled
over the signal handler), restore the rspec signal handler.
there's an obvious race if someone hits ctrl-c after tinyserver has
scribbled over the sigint handler but before we restore it, but this is
99.9% better of a solution than nothing.
closes #2520
=> fix rspecs-ctrl-c

lib/chef/provider/package.rb, lib/chef/provider/package/dpkg.rb
this is just code rearrangement, no changes to behavior at
all.  pushes the source_array and resolved_source_array up
into the superclass so that other providers can use it (as it
was intended, but that slipped out of the last PR).  also
renamed it to something a little longer and less likely to
clash with variables (which it was already doing).
the block comment also refers to an earlier iteration that used
coercions, which had to be backed out because of chefspec.
=> fix couple of issues in dpkg cleanup

lib/chef/provider/package/dpkg.rb, spec/unit/provider/package/dpkg_spec.rb
Previously dpkg -s would allow a 0 or 1 exit status and it wasn't
entirely clear why this was so either from the code or the tests.
This restores throwing an exception if we are outside of the [0,1]
range, and then adds tests for both behaviors:
- on old ubuntu/debian we get an exit(0) and output on stdout if the
file is not installed
- on newer ubuntu/debian we get an exit(1) and output on stderr if
the file is not installed
Added tests for both those cases, and the case where dpkg -s does
some other kind of exitcode barf and we should raise.
=> restore handling of dpkg -s returns codes (w/tests)

CHANGELOG.md, DOC_CHANGES.md, RELEASE_NOTES.md, lib/chef/exceptions.rb, lib/chef/provider/package/windows.rb, lib/chef/provider/package/windows/exe.rb, lib/chef/provider/package/windows/msi.rb, lib/chef/provider/package/windows/registry_uninstall_entry.rb, lib/chef/win32/api/file.rb, lib/chef/win32/file.rb, lib/chef/win32/file/version_info.rb, spec/functional/resource/windows_package_spec.rb, spec/functional/win32/version_info_spec.rb, spec/unit/provider/package/windows/exe_spec.rb, spec/unit/provider/package/windows/msi_spec.rb, spec/unit/provider/package/windows_spec.rb
This initial commit is a direct port from the Windows cookbook. There will be some implementation changes particularly around installer detection and idempotency but this is the basic structure I'm proposing:
* Keep the current `windows_package` provider with its `MSI` as an inner class
* Add a new inner class `Exe` to encapsulate the other installers
I don't think we need separate classes for each installer type because the implementation is almost identical with the only difference being in the installer flags. They are different enough from MSI to warant their own class.
Note that the private methods of the `Exe` class may be undergoing changes so hold off on reviewing the specifics of that code. Also expect the `installer_type` detection to change because we cant be opening up hundred …
=> adds support for installer types inno, nsis, wise and installshield to windows_package resource

lib/chef/provider/dsc_resource.rb, lib/chef/resource/dsc_resource.rb, spec/unit/resource/dsc_resource_spec.rb
`dsc_resource` was missing a timeout resource. Some resources,
such as `xSQLServerSetup` were taking longer than the default
of 10 minuites set by mixlib-shellout.
Fixes #4232 
cc @chef/client-windows
=> Add timeout attribute to dsc_resource

.travis.yml, chef-config/lib/chef-config/config.rb, chef-config/spec/unit/config_spec.rb, chef.gemspec, lib/chef/application.rb, lib/chef/application/apply.rb, lib/chef/knife.rb, lib/chef/knife/ssl_check.rb, lib/chef/knife/ssl_fetch.rb, lib/chef/mixin/proxified_socket.rb, spec/functional/application_spec.rb, spec/unit/application_spec.rb, spec/unit/knife/ssl_check_spec.rb, spec/unit/knife/ssl_fetch_spec.rb, spec/unit/mixin/proxified_socket_spec.rb
https://github.com/samuelkadolph/ruby-proxifier is a gem which gives the ability to have `TCPSocket` respect the proxy environment variables.  It does this by sending a `CONNECT` request to the proxy - see https://github.com/samuelkadolph/ruby-proxifier/blob/master/lib/proxifier/proxies/http.rb
\cc @jkeiser @chef/client-maintainers
Fixes https://github.com/chef/chef/issues/4215
**EDIT**
To get the tests passing for this I needed to modify Knife to run the logic which exports `Chef::Config[:http_proxy]` to `ENV['http_proxy']`.  I decided to move the exporting logic into `Chef::Config` because that is where we want it to be able to leverage that logic in Test Kitchen and Berkshelf.
=> Enabling 'knife ssl check/fetch' commands to respect proxy environment variables and moving proxy environment variables export to Chef::Config

lib/chef/chef_class.rb, lib/chef/log.rb, lib/chef/property.rb, lib/chef/resource.rb, lib/chef/resource/action_class.rb, spec/integration/recipes/resource_action_spec.rb
(User will expect "x x" to grab the parent property.)
=> Warn when user sets a property of an inline resource to itself.

lib/chef/property.rb, spec/integration/recipes/resource_action_spec.rb
If a user has a property named `template` and then tries to declare a template with the same name, we silently set the property on the resource and ignore the block. This patch causes us to at least toss an exception.
=> Get rid of ambiguity with `template 'x' do ...`

chef-config/lib/chef-config/config.rb, lib/chef/client.rb, lib/chef/knife.rb, spec/unit/client_spec.rb, spec/unit/rest/auth_credentials_spec.rb
All supported Chef servers support the 1.1 signing protocol.
There is no reason to continue using 1.0, and removing it
as the default allows us to remove a bunch of code that tries
to upgrade 1.0 to 1.1 when the node name is too long.
If the user specifies 1.0 as the auth protocol version from
this point on, they will have to guarantee that the node
name is not too long.
=> Use signing protocol 1.1 by default

appveyor.yml
Our tests are getting backed up. 2 hours is unreasonable.
Removing ruby 2.0 32 bit from the matrix
=> Reduce appveyor matrix

chef-config/lib/chef-config/config.rb, chef-config/spec/unit/config_spec.rb
Setting a value for `no_proxy` caused ruby to crash.
=> Fix no_proxy setting in chef-config

lib/chef/property.rb, lib/chef/resource.rb, lib/chef/resource_builder.rb, spec/integration/recipes/resource_action_spec.rb
There are a number of cases where people will construct a resource, initialize it, and then use properties from the resource to calculate other things during compilation. We want to not warn on these; we are really only trying to get rid of ambiguities during the `resource :x do ... end` block.
=> Only warn about potentially duplicate properties during the resource initializer.

lib/chef/node.rb, lib/chef/node/attribute.rb, lib/chef/node/attribute_collections.rb, spec/unit/node_spec.rb
previously if the node had a { normal: { tags: nil } } that we read
since the key existed (but was nil) we would not initialize with an
array.  replacing the code with a call to node.set_unless revealed that
set_unless was similarly buggy.  fixed both issues by fixing set_unless.
=> tags always an array; fix set_unless

DOC_CHANGES.md, RELEASE_NOTES.md, lib/chef/exceptions.rb, lib/chef/provider/package/windows.rb, lib/chef/provider/package/windows/exe.rb, lib/chef/provider/package/windows/msi.rb, lib/chef/resource/windows_package.rb, spec/functional/resource/windows_package_spec.rb, spec/unit/provider/package/windows_spec.rb
Currently one can use a package `source` location as a package name:
```
package 'http://mercurial.selenic.com/release/windows/Mercurial-3.6.1-x64.exe' do
checksum 'febd29578cb6736163d232708b834a2ddd119aa40abc536b2c313fc5e1b5831d'
end
```
In the case of non-`:msi` `installer_type`s, this will result in package resources reconverging an `:install` action even though the package has been previously installed.
The reason is that when the `windows_package` scans the registry for all current software installations, it cannot search by install path or url. So it searches by the `DisplayName` property in the registry keys mentioned above. If you use a source path as the name of a non `:msi` `windows_package` it will not find any currently installed package and will therefore attempt to reinstall …
=> non msi packages must explicitly provide a source attribute on install

lib/chef/knife/bootstrap/templates/chef-full.erb
In the past we have had issues with SAN and SNI certificates on RHEL 5.
As a result, the fix was to keep pointing at www.opcode.com which used a
cert that matched what we needed. With recent changes to the
infrastructure omnitruck.chef.io and omnitruck-direct.chef.io are now
available. omnitruck.chef.io is fronted by Fastly and as a result has
the same certificate issues that have kept us using www.opscode.com.
omnitruck-direct.chef.io is what Fastly (and now www.opscode.com) hits
to serve traffic. While we don't get the benefit of the CDN and caching
goodness, this will still do a bit to clean up the codebase.
Bootstrapping was verified on the following platforms:
```
opscode-centos-6.4        running (virtualbox)
opscode-centos-7.1        running (virtualbox)
debian-6.0.10 …
```
=> Updates the template to use omnitruck-direct.chef.io

spec/tiny_server.rb
AIX seems to raise Errno::EHOSTUNREACH when the server
is not ready yet. Our tests on AIX fail with:
```
Errno::EHOSTUNREACH:
No route to host - connect(2) for "localhost" port 9000
Shared Example Group: "a file with the wrong content" called from ./spec/support/shared/functional/file_resource.rb:936
Shared Example Group: "a configured file resource" called from ./spec/support/shared/functional/file_resource.rb:279
Shared Example Group: "a file resource" called from ./spec/functional/resource/remote_file_spec.rb:122
```
=> tiny_server should retry Errno::EHOSTUNREACH

spec/functional/resource/aix_service_spec.rb, spec/functional/resource/mount_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb
One cannot create a ramdisk in a WPAR, since it shares filesystem with the LPAR host. Since we use ramdisk for the test, mount tests only work in LPARs. In the future we should find a way to test this code.
@btm @jaym
=> Disabled mount tests on AIX

lib/chef/api_client/registration.rb, lib/chef/knife/bootstrap.rb, lib/chef/knife/bootstrap/chef_vault_handler.rb, lib/chef/knife/bootstrap/client_builder.rb, spec/unit/api_client/registration_spec.rb, spec/unit/knife/bootstrap/chef_vault_handler_spec.rb, spec/unit/knife/bootstrap/client_builder_spec.rb, spec/unit/knife/bootstrap_spec.rb
Now that chef_vault can take a ApiClient, we can pass the one generated during bootstrap along instead of having the vault wait for a client to come back from search.
=> no longer wait on node search to refresh vault but pass created ApiCient instead

lib/chef/provider/service/windows.rb, lib/chef/win32/api.rb, lib/chef/win32/api/security.rb, lib/chef/win32/error.rb, lib/chef/win32/security.rb, spec/functional/resource/windows_service_spec.rb, spec/unit/provider/service/windows_spec.rb
Currently adding a user in the form of `{domain or host}\{user name}` is broken for the `run_as_user` attribute of `windows_service`. It only works with user names prepended with `.\`. This fixes that.
This also now uses the win32 LSA functions and adds the `SeServiceLogonRight` to the user and only if that user does not already have the right. Currently the service clobbers all current users with that right with the `run_as_user`.
=> fix run_as_user of windows_service

spec/unit/resource_spec.rb
I was trying to answer a question I had today about whether a resource would be executed when multiple guards are assigned. Unfortunately, I could not find any info on this subject within the web docs. So I checked the specs, and found the resource spec with some relevant tests. 
I noticed that there were a few extra tests that could be included to fully answer my question. This pull request adds them.
=> Add extra tests around whether to skip with multiple guards

README.md
I hit an issue when trying to run the steps for local installation. 
I saw an issue that resolved it but the documentation didn't reference this step. I made a change to include the call to bundle exec rake gem
=> Issue 3859 Text Update to Readme. Obvious Fix

lib/chef/provider/package/chocolatey.rb, lib/chef/providers.rb, lib/chef/resource/chocolatey_package.rb, lib/chef/resources.rb, spec/unit/provider/package/chocolatey_spec.rb, spec/unit/provider/package/zypper_spec.rb, spec/unit/resource/chocolatey_package_spec.rb
* Adds `chocolatey_package` as a core-chef resource
* Does not conflict with the `chocolatey` provider in the cookbook
* Uses the semantics of the core-chef package resource instead of chocolately (:remove instead of :uninstall)
* Implements multipackage install/remove/upgrade to the extent possible
Bonus is that it adds features to the core package provider to make it much easier to write multipackage-enabled subclasses.
One difference between this provider and the chocolatey provider in the cookbook is that we only take a string of options not a hash, again for consistency with the base package provider code in core chef.
=> add chocolatey_package to core chef

.rubocop.yml, .travis.yml, Gemfile, Rakefile
This commit enables ChefStyle, but with no active cops. Cops will be
added per the RFC (one at a time, with a supporting PR to this repo) as
we go on.
=> Per RFC 64, do style checking of the Chef repo

lib/chef/provider/package/windows/exe.rb, spec/functional/resource/windows_package_spec.rb, spec/unit/provider/package/windows/exe_spec.rb
Currently we attempt to detect installer version of exes by examining their version resource information embedded in the installer file. Unfortunately there is no guarantee that this version will line up with the version information in the installer's uninstall registry data. This uncertainty is not new but I had misunderstood idempotency dynamics when no version is explicitly given as an attribute. I thought such packages would always reconverge when no source was given. That's not the case. Therefore it is better to not autodetect because if no source is given and the version we autodetect is different from that in the installation metadata, the resource will not be idempotent. Removing the autodetection and not specifying source will only cause the resource to converge if no package is …
=> fixes #4354 and fixes #4372 stop trying to auto detect versions for exe installers

lib/chef/cookbook/metadata.rb, spec/data/cookbooks/supports-platform-constraints/metadata.rb
Using the cookbook version parser means that some platforms cannot be properly parsed by the supports method in metadata.
The included test metadata are two cases where it fails to parse because both are invalid cookbook versions but valid platform versions.
=> use platform parser with metadata supports

lib/chef/application/knife.rb, spec/functional/knife/smoke_test.rb
Request to have Help command return zero when executed
https://github.com/chef/chef/issues/4268
=> Ensuring running Help returns an exit code of 0

lib/chef/data_bag_item.rb, lib/chef/mixin/why_run.rb, lib/chef/provider/service/macosx.rb, spec/data/invalid-metadata-chef-repo/invalid-metadata/metadata.rb, spec/functional/run_lock_spec.rb, spec/unit/chef_fs/parallelizer.rb
fixes:
Lint/UnreachableCode
Lint/NonLocalExitFromIterator
Lint/LiteralInCondition
Lint/EmptyEnsure
Lint/DefEndAlignment
Lint/CircularArgumentReference
=> more rubocop fixes

lib/chef/provider/lwrp_base.rb, lib/chef/resource/lwrp_base.rb, spec/unit/lwrp_spec.rb
These tally up pretty fast. I'd prefer they weren't on the default log level:
```
[2015-12-28T22:34:18-08:00] INFO: LWRP provider /var/folders/1k/xm6r9n6d26b63qsh0m6nlz6m0000gn/T/d20151228-11523-mvxs61/cookbooks/chef_handler/providers/default.rb from cookbook chef_handler has already been loaded!  Skipping the reload.
[2015-12-28T22:34:18-08:00] INFO: Custom resource /var/folders/1k/xm6r9n6d26b63qsh0m6nlz6m0000gn/T/d20151228-11523-mvxs61/cookbooks/chef_handler/resources/default.rb from cookbook chef_handler has already been loaded!  Skipping the reload.
[2015-12-28T22:34:18-08:00] INFO: LWRP provider /var/folders/1k/xm6r9n6d26b63qsh0m6nlz6m0000gn/T/d20151228-11523-mvxs61/cookbooks/windows/providers/auto_run.rb from cookbook windows has already been loaded!  Skipping the reload. …
```
=> Warn (v. info) when reloading resources

spec/unit/provider/service/aixinit_service_spec.rb
so, this is a bit special...
the API for "priority" is clearly broken.  but this broken API comes
from the service resource itself which appears to have been broken
by design since at least 2010.
just fixing the code for how it behaves and dropping in FIXMEs
for now, since this uncovered a fairly massive API-breaking yak.
=> fix Lint/DuplicatedKey

lib/chef/environment.rb
this was missed in the great REST fire.
cc @chef/client-maintainers @afiune
=> inflate an environment after loading it

lib/chef/knife/core/node_editor.rb, spec/unit/knife/core/node_editor_spec.rb
Fixes #4364
/cc @chef/client-core 
Fix Chef::Knife::NodeEditor to correctly display and consume `policy_name` and `policy_group` properties.
- Add specs for Chef::Knife::NodeEditor.
- Add `policy_name` and `policy_group` to properties compared in `NodeEditor#updated?`.
- Add `policy_name` and `policy_group` to Hash returned by `NodeEditor#view`.
- Use `Node.from_hash` in `NodeEditor#apply_updates` instead of duplicating functionality.
- Add some YARD docs for Chef::Knife::NodeEditor.
=> Correctly save policy_name and policy_group with `knife node edit`

Rakefile
if you 'bundle install --without development test' then the Rakefile
will be broken without this.
breaks appbundle-updater, so not sure how our kitchen tests are
passing...
=> make chefstyle optional in the Rakefile

chef.gemspec
All the components of the ChefDK are being updated.  See https://github.com/chef/chef-dk/pull/640 for more details.
\cc @chef/maintainers
=> Updating to the latest release of net-ssh to consume https://github.com/net-ssh/net-ssh/pull/280

omnibus/resources/chef/msi/source.wxs.erb
If a user installs chef to a directory other than c:\opscode\chef via MSI and installs the chef-client service as well., the service will not run because it points to the default location.
I have validated this fix by building a chef client with the changed wix.
=> configure chef client windows service to the correct chef directory

spec/functional/resource/chocolatey_package_spec.rb
This should help diagnose if build machines fail to install chocolatey
=> die die die if functional test fails to install chocolatey

lib/chef/cookbook/metadata.rb
The metadata class is now referencing this constant, but the code isn't loaded if you're selectively requiring it (this occurs in the code that loads cookbooks for policyfiles), so ChefDK bails with:
```
(NameError) uninitialized constant Chef::VersionConstraint::Platform
/Users/ddeleo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/chef-c53d73f77c8c/lib/chef/cookbook/metadata.rb:749:in `validate_version_constraint'
/Users/ddeleo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/chef-c53d73f77c8c/lib/chef/cookbook/metadata.rb:379:in `provides'
/Users/ddeleo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/chef-c53d73f77c8c/lib/chef/cookbook/metadata.rb:454:in `block in recipes_from_cookbook_version'
```
=> Require Chef::VersionConstraint::Platform b/c it's used here

lib/chef/property.rb, spec/integration/recipes/resource_action_spec.rb
unless using properties on the resource
closes #4334
=> Fix #4334: don't warn about ambiguous property usage

spec/functional/resource/user/useradd_spec.rb
This fixes the test failure we were seeing on Nexus7 bots.  Already went through Manhattan.  Because Nexus7 is a derivative of RHEL then this behavior is correct.
\cc @chef/maintainers
=> Seeing a useradd failure in Nexus7 functional tests

chef.gemspec
Using bundler to install from git via `gem 'chef', github: 'chef/chef'` only the last path is added to `$LOAD_PATH` when using `require_path` in gemspec. `require_paths` fixes this. This fixes knife-windows builds.
=> use require_paths and not path so bundler grabs all paths from a git reference

lib/chef/provider/package/zypper.rb, spec/unit/provider/package/zypper_spec.rb
=> zypper multipackage patch

spec/functional/resource/user/useradd_spec.rb
According to https://abcofaix.wordpress.com/tag/usermod/, the value
can be up to 200. We were seeing tests on our aix testers fail with
```
1) Chef::Provider::User::Useradd action :create when the user does not exist beforehand when a system user is specified ensures the user has the properties of a system user
Failure/Error: expect(pw_entry.uid.to_i).to be < uid_min.to_i
expected: < 100
got:   101
```
cc @chef/client-aix @chef/client-core
=> Set range of system user/group id to max of 200

chef-config/lib/chef-config/config.rb, chef.gemspec, ci/verify-chef.bat, ci/verify-chef.sh, lib/chef/application.rb, lib/chef/application/apply.rb, lib/chef/application/client.rb, lib/chef/formatters/doc.rb, lib/chef/formatters/minimal.rb, lib/chef/http/authenticator.rb, lib/chef/knife.rb, lib/chef/knife/bootstrap.rb, lib/chef/knife/core/bootstrap_context.rb, omnibus/config/projects/chef-fips.rb, spec/spec_helper.rb, spec/support/chef_helpers.rb, spec/support/platform_helpers.rb, spec/unit/api_client/registration_spec.rb, spec/unit/application_spec.rb, spec/unit/client_spec.rb, spec/unit/encrypted_data_bag_item_spec.rb, spec/unit/http/authenticator_spec.rb, spec/unit/http/ssl_policies_spec.rb, spec/unit/rest/auth_credentials_spec.rb
This adds a feature flag to tell openssl to run in fips mode. We will be including the fips object module in our omnibus builds. This shouldn't affect anybody unless they explicitly ask for openssl to be run in fips mode.
=> Default Chef with FIPS OpenSSL to use sign v1.3

chef-config/lib/chef-config/config.rb, chef-config/spec/unit/config_spec.rb, lib/chef/chef_fs/chef_fs_data_store.rb, lib/chef/chef_fs/config.rb, lib/chef/local_mode.rb, spec/integration/knife/chef_fs_data_store_spec.rb
The primary goal here is to enable use of policyfile endpoints in local mode without requiring additional configuration on the user's part. Due to the various compatibility constraints around ChefFS (because of `knife download` being a backup/migration mechanism for many folks), this means we have to change the default behavior of Chef Zero to Chef 12 mode for Chef Client local mode operation.
We still default to single-org mode, which means that there's no way to serve user data via local mode with the default configuration, because Chef Zero will map a request for `/users` to `/organizations/chef/users`, but that can be fixed with additional config and is a suspect use case (e.g., `knife list users -z` and similar). This limitation is described in more detail in a comment in the tests. …
=> Enable policies in local mode by default

ci/verify-chef.sh
Some testers fail with
```
ci/verify-chef.sh: test: ] missing`
```
This regression was introduced by
https://github.com/chef/chef/commit/2bcb7d06dcb49c953b9e666b24c8bd3cb56da2c5
This patch should fix it, though I can't be 100% sure as the pipeline seems to pick up the ci folder from master.
=> Fix bug in sh script that runs test in jenkins

lib/chef/application.rb, lib/chef/config_fetcher.rb, lib/chef/run_lock.rb, spec/unit/application_spec.rb, spec/unit/config_fetcher_spec.rb
I attempted to fix this previously in https://github.com/chef/chef/pull/3963 but it regressed; I wasn't able to track down the commit that broke it, but in any case that fix wasn't very stable because quite a few config paths are evaluated relative to the config file path, which is expanded relative to cwd, and chef-client chdirs to root right after the config file is read.
=> Force config file setting to expanded path in chef-client

spec/spec_helper.rb, spec/unit/encrypted_data_bag_item_spec.rb
The logic here is inverted, and I think the `not_wpar` one is as well. We'll fix that in a different PR.
=> Fix inverted filter logic for not_fips rspec filter

.travis.yml
if we don't test this here, then when the jenkins ci cluster runs it
we may error in the Rakefile when it tries to require a gem which is
not in the bundle that is installed there --without several gems.
=> bundle install without maintenance and others

.travis.yml
Poise is currently having it's tests refactored and thus
not passing tests. We can revert this commit once that's
all fixed up.
cc @coderanger
=> Remove poise from the test matrix

acceptance/cookbook-git/.kitchen.ec2.yml
Minor change to comment out use of public IP for AWS instance.
@chef/client-maintainers @sersut @jkeiser
=> Don't use public IP for AWS

lib/chef/chef_fs/chef_fs_data_store.rb, lib/chef/chef_fs/file_system/repository/chef_repository_file_system_cookbook_artifact_dir.rb
Pedant tests were leading us astray, we don't want to remove entries for
empty cookbook segments.
This needs https://github.com/chef/chef-server/pull/714 in order for Chef Zero to pass pedant in CHEF_FS mode.
=> Remove incorrect cookbook artifact normalization

acceptance/.gitignore, acceptance/cookbook-git/.kitchen.ec2.yml, chef.gemspec, ci/verify-chef.sh
An acceptance test that works against EC2 on ubuntu and windows and checks that there is a single version of chef and ohai gems in Chef Client packages.
@tyler-ball this is the first task for making these run in EC2. @chefsalim and @patrick-wright has an incoming change which we will need to rebase on top of soon. Wanted to share this for initial review.
=> Run acceptance tests in Jenkins

chef.gemspec
We require 4.4+ to support policyfile APIs with ChefFS and local mode,
but we don't want to be pessimistic about minor versions, only major.
It looks like the minor version pessimism was accidentally introduced
here:
https://github.com/chef/chef/commit/6e4d70826d8ee6977348bd071d0ce543686b89f6
Now that Chef Zero 4.5 is released, this is breaking stuff where we load chef and chef zero from master.
=> Allow all Chef Zero 4.x after 4.4

spec/functional/resource/ohai_spec.rb
Running ohai is slow.
This is still not as fast as I hoped, but shaves more than 2/3's of the time off.
Still at 26 seconds on my machine
=> Don't rerun ohai for ohai_spec when not needed

omnibus/config/projects/chef.rb, omnibus/resources/chef/msi/source.wxs.erb
windows client SKUs default to giving more permissions than necessary
=> explicitly specify user permissions during msi install of chef directory

appveyor.yml, spec/functional/dsl/reboot_pending_spec.rb, spec/functional/dsl/registry_helper_spec.rb, spec/functional/knife/configure_spec.rb, spec/functional/resource/dsc_resource_spec.rb, spec/functional/resource/dsc_script_spec.rb, spec/functional/resource/windows_service_spec.rb, spec/functional/util/powershell/cmdlet_spec.rb, spec/functional/win32/crypto_spec.rb, spec/functional/win32/registry_spec.rb, spec/spec_helper.rb, spec/unit/dsl/regsitry_helper_spec.rb
Ohai on windows is really slow. While we should fix this, we should also make tests fast and not keep redoing work. This was caused by https://github.com/chef/ohai/issues/715
I've also marked the windows_service_spec as broken. It is extremely unreliable. It causes the entire process to die in the 64 bit tests. Still unclear why this has become so unstable lately.
=> Modified all windows paths to not reload anything from ohai

spec/functional/event_loggers/windows_eventlog_spec.rb
Using SecureRandom is slow if it is not initialized.
Random is good enough for this test.
=> Make windows event log tests faster

lib/chef/provider/osx_profile.rb, spec/unit/provider/osx_profile_spec.rb
Bad test lead to a provider coverage failure for brand new machines with no profiles installed. This fixes the test and ensures profiles will actually install on machines that currently have no profiles.
@jaymzh must do the merge as he is our designated CLA person. Thanks Phil!
=> Fix osx_profile coverage failure and update spec

chef-config/lib/chef-config/config.rb, lib/chef/application/knife.rb, lib/chef/knife.rb, lib/chef/knife/bootstrap.rb, lib/chef/knife/core/bootstrap_context.rb, spec/unit/application/knife_spec.rb, spec/unit/application_spec.rb, spec/unit/knife/bootstrap_spec.rb, spec/unit/knife/core/bootstrap_context_spec.rb
This somewhat worked before. However, it was just for knife bootstrap.
It also didn't support --no-fips in the case where it was in your
knife.rb and you decided that you didn't want to use fips for
that one call.
The assumption here is fips mode you run knife with is the fips
mode the node will get. This has the nice property that validatorless
bootstraps will talk to the chef server in fips mode if the node
is requested to be in fips mode.
=> Allow use of command line fips switch for knife

lib/chef/mixin/powershell_type_coercions.rb, lib/chef/provider/dsc_resource.rb, spec/unit/mixin/powershell_type_coercions_spec.rb, spec/unit/provider/dsc_resource_spec.rb
* Chef::Mixin::PowerShellTypeCoercions can translate a hash, but cannot translate an ImmutableMash which causes it to serialize it as a string.  This breaks DSC resources that are expecting a hash.
* Chef::Mixin::PowerShellTypeCoercions can translate a array, but cannot translate an ImmutableArray which causes it to serialize it as a string.  This breaks DSC resources that are expecting a array.
* `dsc_resource` does not append the verbose output from the set method when updating a resource that was not in the desired state.
=> Fix few dsc_resource bugs

chef-config/lib/chef-config/config.rb, lib/chef/chef_fs/file_pattern.rb, lib/chef/exceptions.rb, lib/chef/formatters/error_inspectors/cookbook_resolve_error_inspector.rb, lib/chef/formatters/error_inspectors/cookbook_sync_error_inspector.rb, lib/chef/formatters/error_inspectors/node_load_error_inspector.rb, lib/chef/knife/core/status_presenter.rb, lib/chef/knife/ssh.rb, lib/chef/provider/batch.rb, lib/chef/provider/powershell_script.rb, lib/chef/provider/user.rb, lib/chef/run_list/run_list_item.rb, spec/functional/event_loggers/windows_eventlog_spec.rb, spec/functional/resource/directory_spec.rb, spec/unit/application/knife_spec.rb, spec/unit/formatters/error_inspectors/cookbook_resolve_error_inspector_spec.rb, spec/unit/key_spec.rb, spec/unit/provider/service/debian_service_spec.rb
3 Performance/CaseWhenSplat: Place when conditions with a splat at the end of the when branches.
1 Style/ElseAlignment: Align else with if.
1 Style/EvenOdd: Replace with Fixnum#even?.
1 Style/MethodDefParentheses: Use def with parentheses when there are parameters.
3 Style/PercentQLiterals: Do not use %Q unless interpolation is needed.  Use %q.
3 Style/SpaceAfterColon: Space missing after colon.
2 Style/SpaceAfterMethodName: Do not put a space between a method name and the opening parenthesis.
2 Style/Tab: Tab detected.
1 Style/TrailingUnderscoreVariable: Do not use trailing _s in parallel assignment.
1 Style/UnneededCapitalW: Do not use %W unless interpolation is needed.  If not, use %w.
=> auto-fixing some easy cops

kitchen-tests/Berksfile
Seems we're hitting a molinillo bug that prevents us from solving
dependencies correctly.
cc @jaym
=> Lock php cookbook in kitchen tests to solvable version

.travis.yml
It seems something must have changed in travis and it's not merging the before scripts anymore
=> Trying to fix travis

omnibus/resources/chef/msi/localization-en-us.wxl.erb
Our PublisherName shows up in Add/Remove Control Panel as a quoted string - this looks ugly, and is not the standard way to represent the package in the ARP.  The reason is we are doing an XML escape of the Manufacturer property in the MSI.  This PR puts a cleaner version of the string in the loc erb - sans the maintainers email address (which also doesn't belong in the PublisherName property).
@chef/client-core @chef/omnibus-maintainers @adamedx
=> Update MSI ManufacturerName to be a cleaner string

lib/chef/application/client.rb, lib/chef/application/solo.rb, spec/unit/application/client_spec.rb, spec/unit/application/solo_spec.rb
- deprecates '-r' used for the recipe_url in chef-solo
- adds --delete-entire-chef-repo option for users who want the
old behavior back.
- cleans up some old code
closes #3802
closes #1515
closes #1751
=> removing rm -rf in chef-solo recipe_url

ci/verify-chef.bat, ci/verify-chef.sh, spec/functional/resource/aixinit_service_spec.rb, spec/functional/resource/bff_spec.rb, spec/functional/resource/rpm_spec.rb, spec/functional/run_lock_spec.rb, spec/scripts/ssl-serve.rb
Fixes the "disk space filling up" issue on chef testers.
=> Create special tempdir and destroy it on each ci run

acceptance/top-cookbooks/.acceptance/acceptance-cookbook/libraries/top_cookbooks.rb, acceptance/top-cookbooks/.kitchen.learn-the-basics-windows.yml
Add a Windows learn-chef test to the top cookbooks.
@chef/client-core @sersut @jkeiser @tyler-ball
=> Add learn-chef for Windows to top-cookbooks test

lib/chef/knife/ssh.rb
we don't use run_command anywhere and this can apparently cause uninitialized
constant issues when knife ssh is invoked via other knife commands (i.e.
bootstrap) where apparently the transitive lazy deps aren't getting
invoked correctly.  there's another bug there, but we do not have any
run_command statements in knife anymore so we should be able to drop
this as a much easier fix.
closes #4546
=> remove Chef::Mixin::Command use

lib/chef/provider/package/chocolatey.rb, spec/functional/resource/chocolatey_package_spec.rb
This covers 2 problems:
* Ensures we specify the internal source repo location on chocolatey functional tests
* Remove the `--source` parameter when calling `choco uninstall` since that is illegal. Note that the resource `:remove` action still needs the source for the idempotence check
I ran the tests with a wireshark trace running to ensure nothing was leaking to the public choco repo with the exception of the initial choco.exe install
=> do not include source parameter when removing a chocolatey package and ensure source is used on all functional tests

ci/verify-chef.bat, ci/verify-chef.sh
Travis/Appveyor already run the unit tests at the appropriate gate earlier in the build process. Running the tests on each platform we build a package for should give the same result and really just serves to slow the overall delivery process down.
This is per a meeting we had earlier to improve build speeds.
/cc @chef/engineering-services @chef/ship-it @chef/workflow @chef/ecosystem-team
=> Disable unit tests in later stages of CD pipeline

lib/chef/policy_builder/policyfile.rb, spec/unit/policy_builder/policyfile_spec.rb
The change from `Chef::REST` to `Chef::ServerAPI` ([here](https://github.com/chef/chef/commit/d99e306a41b1402209d320cb7119b12a3bbb962f)) seems to have broken the `policyfile_zero` test-kitchen provisioner (I'm not sure where else the Policyfile `compat_mode_manifest_for` method is used).
You can see the different here:
```
[3] pry(#<Chef::PolicyBuilder::Policyfile>)> rest_api = Chef::REST.new(config[:chef_server_url])
[4] pry(#<Chef::PolicyBuilder::Policyfile>)> rest_api.get("cookbooks/#{name}/#{lock_data['dotted_decimal_identifier']}")
[2016-02-12T07:45:10+00:00] WARN: Auto inflation of JSON data is deprecated. Please use Chef::CookbookVersion#from_hash at (pry):4:in `block in cookbooks_to_sync'
=> #<Chef::CookbookVersion:0x000000048fedd8
@attribute_filenames=[], …
```
=> Fix policyfile_zero provisioner in 12.7

lib/chef/provider/route.rb
When I was writing a cookbook that had both route deletions and additions, I noticed that the route-eth0 file written by chef had **all** the route information from **all** the route resources I had defined no matter the type of action. 
I added an additional check to only include the :add route resources.
=> Don't use routes with action :delete when writing config

ci/verify-chef.bat, ci/verify-chef.sh
@chef/ship-it 
The "good measure" cleanup logic overrides the script exit status.  Since we do a cleanup at the start of the script this should meet our immediate needs.
=> Remove final cleanup from ci verify scripts

lib/chef/provider/user/useradd.rb, spec/functional/resource/user/useradd_spec.rb, spec/support/shared/unit/provider/useradd_based_user_provider.rb
Disallow locked user to log in setting /bin/false as a shell value (without it user is still able to log in using ssh key + authorized keys, even with locked password). 
Reset shell for unlocked user.
=> Change shell for locked user.

spec/unit/provider/user/dscl_spec.rb, spec/unit/provider/user/solaris_spec.rb
This fixes the following error:
```ruby
/Users/juliandunn/devel/gh/juliandunn/chef/spec/unit/provider/user/solaris_spec.rb:23: warning: already initialized constant ShellCmdResult
/Users/juliandunn/devel/gh/juliandunn/chef/spec/unit/provider/user/dscl_spec.rb:19: warning: previous definition of ShellCmdResult was here
```
=> Refactor test to remove duplicate definition of ShellCmdResult

lib/chef/cookbook_loader.rb, lib/chef/knife/cookbook_upload.rb, spec/unit/cookbook_loader_spec.rb, spec/unit/knife/cookbook_upload_spec.rb
Since 2011 we've been warning that cookbooks shadowing was deprecated, but only in the 'knife cookbook upload' command.
See https://github.com/chef/chef/commit/5a9fee8edaede311ac03a15d52fbc66dad83b576
This inserts the warning directly into the CookbookLoader class which should cause it to be emitted every time the code in question is actually exercised.
=> Extend cookbook shadowing deprecation warnings more broadly

chef-config/lib/chef-config/path_helper.rb, chef-config/spec/unit/path_helper_spec.rb, lib/chef/data_bag.rb
Backslashes should not be passed to Dir, as it does not work
when globbing in many cases.
Created new function that can be used with dir on windows.
`escape_glob_dir` should be used when the result is going
to be passed into Dir.
Fixes #4194
Replaces #4195
=> Fix databag globbing issues for chef-solo on windows

lib/chef/provider/launchd.rb, lib/chef/providers.rb, lib/chef/resource/launchd.rb, lib/chef/resources.rb, spec/unit/provider/launchd_spec.rb, spec/unit/resource/launchd_spec.rb
@jaymzh will merge under his CCLA once it's passed review by @chef / @client-core
This resource installs/removes Launch Daemons and Agents
- :create
- :create_if_missing
- :delete
- `label` - This required key uniquely identifies the job to launchd.
- `path` - This is used as an override. By default the provider will generate a
path for you based on service_type. Default: /Library/LaunchDaemons/#{label}
- `hash` - key, value pairs to create launchd plist.
- `source` - Source path to launchd plist.
- `cookbook` - Cookbook which source file exists. Default: current cookbook
- `service_type` - is the type of launchd plist you would like to create.
Options are [system, user], System with create LaunchDaemon, and User will
create a LaunchAgent. Default: system
These parameters are Apples …
=> launchd for osx

distro/common/markdown/man8/chef-client.mkd, lib/chef/application/client.rb, lib/chef/cookbook/synchronizer.rb, lib/chef/shell.rb
Use with caution. Useful for patching a set of cookbooks on a machine
when iterating during development.
=> chef-client: add --[no]skip-cookbook-sync option

lib/chef/provider/package/zypper.rb
obvious fix to remember the results so we don't re-compute every single time on access
=> zypper multipackage performance fix

spec/functional/resource/user/useradd_spec.rb
Bug in AIX auto increments UIDs. So after 200 builds, this test fails.
=> skip uid check for aix in user add functional tests

acceptance/top-cookbooks/.kitchen.git.yml
\cc @mwrock @chef/client-maintainers 
We need to run apt becuase thats what the [cookbook also does](https://github.com/chef-cookbooks/git/blob/master/.kitchen.yml#L18-L21)
=> Need to run apt update on EC2 ubuntu images for acceptance tests

lib/chef/win32/api/error.rb, lib/chef/win32/error.rb
This fixes the build pipeline for Windows Server 2012 (R1)
This was a very weird one and I can only reproduce errors on Azure server 2012 images and not from ISOs via MSDN. (The build numbers are slightly different). On azure, when one attempts to get a formatted error message of a [Network Management Error Code](https://msdn.microsoft.com/en-us/library/aa370674(v=vs.85).aspx), such as `2220`, the following error is raised:
```
irb(main):001:0> require 'chef'
=> true
irb(main):002:0> Chef::ReservedNames::Win32::Error.format_message(2220)
Chef::Exceptions::Win32APIError: The resource loader failed to find MUI file.
---- Begin Win32 API output ----
System Error Code: 15100
System Error Message: The resource loader failed to find MUI file.
---- End Win32 API output ----
from …
```
=> fallback to netmsg.dll error table if error message is not found in system errors

spec/functional/resource/dsc_script_spec.rb
Azure 2012R2 slaves have been failing to run the dsc resource functional tests because the HTTP winrm listener is not present. This ensures it is enabled before the tests are run.
cc @chefsalim @schisamo
=> enable HTTP winrm listener for dsc functional tests

chef-config/lib/chef-config/config.rb, lib/chef/chef_fs/chef_fs_data_store.rb, lib/chef/chef_fs/config.rb, lib/chef/chef_fs/data_handler/client_key_data_handler.rb, lib/chef/chef_fs/file_system/repository/chef_repository_file_system_client_keys_dir.rb, lib/chef/chef_fs/file_system/repository/chef_repository_file_system_root_dir.rb
Supports work to bring chef-zero closer to parity with chef-server. See chef/chef-zero#199.
=> Add client keys handling to ChefFS

chef-config/lib/chef-config/path_helper.rb, lib/chef/mixin/path_sanity.rb, spec/unit/mixin/path_sanity_spec.rb
On windows (I'm assuming this is limited to windows) when using anon ascii encoding like (CP850) and with non ASCII characters (like like an umlaut `\x81`) in `ENV['PATH']` or `ENV['HOME']`, chef runs fail.
I have found 2 key areas that lead to this failure:
* `path_helper`
* `path_sanity`
`path_helper` fails because `Dir.home` has a `Windows-1252` encoding and when a character like `\x81` is present, checking the directory with `File.exists?` fails due to an invalid byte sequence.
`path_sanity` creates a path that is far from sane if a character like `\x81` is in the path. This results in creating a `ENV['PATH']` with a `Encoding:8BIT` that can wreak havoc in several possible places throughout a chef run.
Note that this can only be reproduced when the node has a non US langiage pack. I …
=> ensure paths maintain utf-8ness in non ascii encodings

bin/chef-shell
I have tested this on windows 10, 2012R2 and 2008R2 and all worked fine.
=> removing disabling of readline in chef-shell

lib/chef/provider/package/chocolatey.rb, spec/unit/provider/package/chocolatey_spec.rb
The previous implementation (in `define_resource_requirements`) failed acceptance testing because `choco.exe` gets called before that, in `load_current_resource`, so the detection needs to be a bit lower-level.
This includes a spec that replicates the acceptance test (by calling `load_current_resource`).
=> Fix the Chocolatey-missing error again

acceptance/.shared/kitchen_acceptance/.kitchen.vagrant.yml, acceptance/Gemfile, acceptance/fips/.acceptance/acceptance-cookbook/.gitignore, acceptance/fips/.acceptance/acceptance-cookbook/metadata.rb, acceptance/fips/.acceptance/acceptance-cookbook/recipes/destroy.rb, acceptance/fips/.acceptance/acceptance-cookbook/recipes/provision.rb, acceptance/fips/.acceptance/acceptance-cookbook/recipes/verify.rb, acceptance/fips/.kitchen.yml, acceptance/fips/test/integration/fips/serverspec/Gemfile, acceptance/fips/test/integration/fips/serverspec/fips_spec.rb, spec/functional/resource/deploy_revision_spec.rb, spec/functional/resource/git_spec.rb
Adding a test to the accepting framework for FIPS. When a package gets built, it will toggle FIPS mode for the platforms we care about and run the rspec tests. This keeps us from mucking around with the test matrix in jenkins.
=> Add acceptance tests for running chef-client with the FIPS mode

lib/chef/data_bag_item.rb, spec/unit/data_bag_item_spec.rb
Fixes issue #4614.
Make a copy of the raw_data (that is then mutated with "data_bag" and "chef_type" keys) to return, rather than the actual raw_data object.
=> Fix a bug that was causing DataBagItem.to_hash to mutate the data bag item

lib/chef/cookbook/cookbook_version_loader.rb, lib/chef/cookbook_version.rb, spec/unit/cookbook/cookbook_version_loader_spec.rb, spec/unit/cookbook/syntax_check_spec.rb, spec/unit/cookbook_site_streaming_uploader_spec.rb, spec/unit/cookbook_version_spec.rb
My tactical goal here is to restore some functionality that broke in ChefDK/policyfiles. Previously, ChefDK would do a simple file copy to copy cookbooks when doing `chef export` (which is what the test kitchen provisioner uses to get the cookbook code on the guest VM). That didn't honor chefignore, so in some cases folks could end up copying a VM into itself. Therefore, that behavior was changed to use `CookbookVersionLoader`. However, this had the side-effect of only copying files that belong to a "cookbook segment," so test files were not copied. So the goal here is to make it possible for ChefDK to get the list of all of a cookbook's files (there are some caveats to this which are documented in code comments), so that test/spec/etc. files will be copied.
@chef/client-core This is …
=> List all of the unignored files when loading a cookbook

lib/chef/cookbook/cookbook_version_loader.rb
Fixes build failures on windows comparing backslashed paths with forward slashed glob patterns using `::File.fnmatch?`. This now ensures that the paths being compared have forward slashes.
=> use Pathname#cleanpath instead of Chef::Util::PathHelper.cleanpath

lib/chef/provider/dsc_resource.rb, spec/functional/resource/dsc_resource_spec.rb, spec/unit/provider/dsc_resource_spec.rb
When converging a `dsc_resource`, we call `get-dscresource` to determine if the resource is present and if it belongs to a module. Some resources report no module associated but in these cases we should default to using `PSDesiredStateConfiguration` as the module to prevent some modules from failing.
This also allows functional tests to run on RTM wmf 5 with LCM enabled.
=> if no module name is found for a valid dsc resource default to PSDesiredStateConfiguration

lib/chef/http/validate_content_length.rb, spec/unit/http/validate_content_length_spec.rb
This is equivalent to not passing one, we can't check for bad downloads.
For an example, run `curl -ivs -o /dev/null "https://www.isc.org/downloads/file/dhcp-4-3-3-p1/?version=tar-gz"`
Curl displays `Negative content-length: -1, closing after transfer`. I can't find any standard for this behavior, but it seems to be shared by all the browsers I tried. ¯\_(ツ)_/¯
=> Handle negative content length headers too.

lib/chef/data_bag_item.rb, spec/unit/data_bag_item_spec.rb
So on one hand it would be nice if this raised the same exception for both client and solo modes, on the other hand that would be a compat break and this is better than nothing. On the client code path is ends up raising `Net::HTTPServerException` with a 404. Mostly this matters because of 
If we don't fail here, it blows up a few lines later when running `from_hash(nil)`. This gets used in https://github.com/chef/chef-vault/blob/master/lib/chef-vault/item_keys.rb#L114-L127, found via a [report on StackOverflow](https://stackoverflow.com/questions/35761065/knife-solo-and-vault-data-bag-item-rb129in-from-hash-undefined-method-d).
=> Clearer exception for loading non-existent data bag items in solo mode.

MAINTAINERS.md, MAINTAINERS.toml
\cc @chef/maintainers 
ChefDK should have been listed in here under Dev Tools - this just bring the doc in line with reality
=> ChefDK was mistakenly left out of the Chef maintenance policy

omnibus/config/projects/chef.rb
Add step for unused static lib cleanup at build time
@chef/client-core @lamont-granquist
=> Cleanup static libs at build time

lib/chef/data_bag_item.rb, spec/unit/data_bag_item_spec.rb
This PR resolves https://github.com/chef/chef/issues/4392
In cases where the data bag item is loaded with json that does not have the canonical knife format (with the user fields in "raw_data"), then the loading code was explicitly deleting the "name" key.  It is not clear whether the deletion of the "name" key actually served any purpose (in the case where the raw_data IS present, deleting "name" is a no-op), so removing it.
@chef/client-core @thommay @tas50 @lamont-granquist
=> Data bag item hash can have name key

spec/functional/resource/bash_spec.rb, spec/integration/knife/upload_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb, spec/support/shared/unit/execute_resource.rb, spec/support/shared/unit/script_resource.rb, spec/unit/cookbook/metadata_spec.rb, spec/unit/encrypted_data_bag_item/check_encrypted_spec.rb, spec/unit/encrypted_data_bag_item_spec.rb, spec/unit/node_spec.rb, spec/unit/policy_builder/expand_node_object_spec.rb, spec/unit/provider/execute_spec.rb, spec/unit/resource/chef_gem_spec.rb, spec/unit/run_list/versioned_recipe_list_spec.rb
lets us use Gem::Dependency constraints directly as rspec
constraints for matching Chef::Version and RUBY_VERSION.
copies some magic sauce from bundler that does something
similar
=> better chef+ruby rspec constraints

lib/chef/knife.rb, lib/chef/knife/core/hashed_command_loader.rb, lib/chef/knife/core/subcommand_loader.rb, lib/chef/knife/rehash.rb, spec/functional/knife/rehash_spec.rb, spec/unit/knife/core/hashed_command_loader_spec.rb, spec/unit/knife/core/subcommand_loader_spec.rb, spec/unit/knife_spec.rb
Fixes https://github.com/chef/chef-dk/issues/681
Whenever the user runs `knife rehash` we ignore the existing hash file (if there is one) and instead load all available plugins from disc in order to generate the new hash.  This avoids issues like upgrading the ChefDK and no longer having the `rehash` command in the manifest exist in the specified location.
If the hash file is incorrect we also no longer spit out a line per error - instead there is 1 error line stating that a rehash needs to be ran and then a listing of all affected files.
```
FATAL: Cannot find subcommand for: 'vault'
If this is a recently installed plugin, please run 'knife rehash' to update the subcommands cache.
Available vault subcommands: (for details, knife SUB-COMMAND --help)
ERROR: There are files specified in the …
```
=> Always rehash from gem source and not existing hash file

lib/chef/cookbook_version.rb, spec/unit/cookbook_version_file_specificity_spec.rb
The `preferred_manifest_record` function pretty prints the list of
existing files when the asked file can't be found. To do that, the root
path of the cookbook is removed from each existing file but the update
is done on the `existing_files` variable, not on a copy. When called
several times, this variable will eventually be equals to `[nil]`,
leading to a NoMethodError.
Without the fix, the new unit test fails with
> expected Chef::Exceptions::FileNotFound, got #<NoMethodError: undefined method `[]' for nil:NilClass> with backtrace:
>   # ./lib/chef/cookbook_version.rb:321:in `block in preferred_manifest_record'
>   # ./lib/chef/cookbook_version.rb:319:in `map!'
>   # ./lib/chef/cookbook_version.rb:319:in `preferred_manifest_record'
>   # …
=> preferred_manifest_record: fix pretty print.

lib/chef/provider/service.rb, lib/chef/provider/service/solaris.rb, lib/chef/provider/service/systemd.rb, lib/chef/resource/service.rb, spec/unit/provider/service/systemd_service_spec.rb
systemd support the concept of user services (https://wiki.archlinux.org/index.php/Systemd/User), which are like system services, but are run and supervised within a user session.
This patch adds support for managing user services within the `service` resource, e.g. by doing
```
service 'foo' do
user 'bar'
action [:enable, :start]
end
```
the  service `foo` will be enabled and started whenever the user `baz` logs in.
I'm a Facebook employee and @jaymzh will do the final merge.
=> Extend service resource to support systemd user services

lib/chef/mixin/properties.rb, lib/chef/property.rb
Because they were different and one in Chef::Mixin::Properties would result in duplicated values for string keys.
Very specifically not adding a new test for string keys on `property` because I think this is not part of our declared API (we only state support for symbol keys) and we probably shouldn't test formally undefined behavior.
=> Fix property coercion

omnibus/config/projects/chef.rb
This has passed through the build+test matrix. Windows upgrades from 2.0 to 2.1, and unix gets a patch bump from 2.1.6 to 2.1.8.
NOTE: we will not merge this until after 12.8 is released, to give us more time before the next release to sort out any issues that crop up.
=> Use ruby 2.1.8 on both windows and unix

MAINTAINERS.toml
We added Cisco to Tier 1 support, and it's already available. Just filling out the paperwork.
=> Adding myself as LT and Maintainer for Cisco platforms

acceptance/top-cookbooks/.acceptance/acceptance-cookbook/libraries/top_cookbooks.rb, acceptance/top-cookbooks/.kitchen.chocolatey.yml, acceptance/top-cookbooks/.kitchen.iis.yml, acceptance/top-cookbooks/.kitchen.powershell.yml, acceptance/top-cookbooks/.kitchen.sql_server.yml, acceptance/top-cookbooks/.kitchen.winbox.yml, acceptance/top-cookbooks/.kitchen.windows.yml
This PR adds some new cookbooks to chef-acceptance that exercise functionality deemed important to validate for the 64-bit Chef on Windows test-matrix - see:
https://docs.google.com/spreadsheets/d/1i_H8skdOLyhLDNfL4VWrOCSRbyBR5BE56vp48KZ1rR0/edit
@client-core @jkeiser @tyler-ball
=> Add cookbooks for 64-bit Windows test matrix

lib/chef/provider/mount/windows.rb, spec/unit/provider/mount/windows_spec.rb
Mounting a device was not idempotent on Windows, and would fail with an error:
Chef::Exceptions::UnsupportedAction
-----------------------------------
#<Chef::Provider::Mount::Windows:0x36abe70> does not implement #mount_options_unchanged?
The options check functionality was added by this change, but missed Windows: https://github.com/chef/chef/commit/43620a7e3d663ca83bc4394a5baaf724fecf06d8
Fix is to add the missing function.
@chef/client-core @mwrock
=> Make mount idempotent on Windows

chef-config/lib/chef-config/config.rb
people are actually doing this in order to work around issues with
writing /etc/hosts in docker containers.  they should seriously
stop doing it and fix this problem in the cookbooks.
=> Warn users not to tweak Chef::Config[:file_atomic_update] setting

lib/chef/dsl/declare_resource.rb
currently, Chef blows up under ruby 2.3 (e.g. [this travis build](https://travis-ci.org/nathwill/chef-hekad/builds/115222568)), this fixes that
closes #4359
=> remove deprecated Thread.exclusive

lib/chef/mixin/params_validate.rb, lib/chef/property.rb, spec/integration/recipes/lwrp_inline_resources_spec.rb
Because set(property, nil) gets turned into get(property), add a 'nil_set' parameter to get() to skip a spurious warning when that happens.
=> Fix issue 4334: eliminate spurious warnings.

lib/chef/chef_fs/file_system/chef_server/cookbook_dir.rb, lib/chef/cookbook/cookbook_version_loader.rb, lib/chef/run_context/cookbook_compiler.rb, spec/integration/knife/chef_repository_file_system_spec.rb
:construction: For Discussion :construction:
Some widely used chef-solo cookbooks, like edelight/chef-solo-search, have subdirectories in their libraries directory.
The libraries directory can also contain non-ruby files (in the chef-solo-search case, the treetop search parser from chef 10).
This PR adds support for this, and would be necessary for chef-zolo support.
=> Support libraries with sub directories

lib/chef/dsl/recipe.rb, lib/chef/provider.rb, lib/chef/recipe.rb, spec/unit/lwrp_spec.rb
this module was created out of a bit of excessive paranoia instead of
simply adding mixins that we always use with Chef::DSL::Recipe directly
to Chef::DSL::Recipe.  lets try and YAGNI this class and just add it
directly.  these modules are already injected into everyone's recipes
and providers, so I can't imagine a huge amount of backcompat breaks.
=> deprecate Chef::DSL::Recipe::FullDSL

chef-config/lib/chef-config/config.rb, chef-config/spec/unit/config_spec.rb, lib/chef/http/basic_client.rb, lib/chef/provider/remote_file/ftp.rb, spec/unit/http/basic_client_spec.rb, spec/unit/provider/remote_file/ftp_spec.rb, spec/unit/rest/auth_credentials_spec.rb
* Always use `*_proxy` environment variables.
* Make a `ChefConfig::Config.proxy_uri` method that gets used by
`Chef::Provider::RemoteFile::FTP` and `Chef::HTTP::BasicClient`.
* Remove `env` method from `Chef::HTTP::BasicClient` (using
`stub_const("ENV", ...)` in specs instead.)
* Remove `http_proxy_user` and `http_proxy_pass` methods from
`Chef::HTTP::BasicClient` (replaced by functionality in `ChefConfig`.)
=> Make handling of proxies more consistent

chef.gemspec
This matches the constraint in ohai, which will make Chef and ohai use the same version.
=> Allow any 3.x version of plist

lib/chef/dsl/core.rb, lib/chef/dsl/method_missing.rb, lib/chef/dsl/recipe.rb, lib/chef/provider.rb
- creates Chef::DSL::MethodMissing which will be nuked in Chef 13
- creates Chef::DSL::Core which is the mixins into core providers
- adds build_resource/define_resource to core providers
The intent here is to create Chef::DSL::Core which is intended to
become the DSL minus method_missing and things that are only intended
for recipes.  Right now I've only added build_resource/declare_resource
to core providers.  We should probably push more into the "Core" DSL
so that core providers could do things like use the search API.
I would have moved everything other than resources and definitions over
but the audit mode stuff is really only appropriate for recipes and not
provider code and probably should not be moved over.  We should probably
have an intermediate mixin which is the "Custom …
=> rearrange dsl mixins

spec/integration/recipes/resource_converge_if_changed_spec.rb, spec/integration/recipes/resource_load_spec.rb
You only see these test failures if you run the recipe integration tests before running the provider resolver tests. I can't say why these did not start failing until recently, since there didn't seem to be any related change in the test configuration that triggered the test failures.
=> Make example resource classes return strings for Class.to_s

chef-config/chef-config.gemspec, chef-config/lib/chef-config/config.rb, chef-config/lib/chef-config/mixin/fuzzy_hostname_matcher.rb, chef-config/lib/chef-config/package_task.rb, chef-config/spec/unit/config_spec.rb, chef.gemspec, lib/chef/http/basic_client.rb, lib/chef/knife/ssl_check.rb, lib/chef/mixin/proxified_socket.rb, spec/unit/mixin/proxified_socket_spec.rb, spec/unit/rest/auth_credentials_spec.rb
Update no_proxy usage in chef-config to conform to documentation:
https://docs.chef.io/proxies.html#no-proxy
http://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html
@chef/client-core @randomcamel @tyler-ball
=> Client option no_proxy does not work as advertised

RELEASE_NOTES.md, lib/chef/provider.rb, lib/chef/provider/apt_update.rb, lib/chef/resource.rb, lib/chef/resource/action_class.rb, spec/unit/lwrp_spec.rb, spec/unit/provider/apt_update_spec.rb
* removes the DSL from InlineResources class
* ActionClass is now responsible for mixing the DSL into
action classes
* apt_update provider converted over to use new syntax
- does not need to mixin DeclareResource DSL
- declares use_inline_resources
- uses declare_resource instead of build_resource
- converts def action_stuff to action :stuff
- uses an execute resource instead of shell_out!
- does not need the converge_by to update the action
=> allow use_inline_resources for core chef providers

appveyor.yml, lib/chef/monkey_patches/win32/registry.rb
\cc @randomcamel @chefsalim @btm @chef/client-windows
=> We still test Chef with versions that do not include our Registry monkeypatches, so better documenting when we can remove these

acceptance/.shared/kitchen_acceptance/.kitchen.ec2.yml
This will allow us to force `i386` when calling from chefdk build
=> Pass windows architecture to kitchen provisioner

lib/chef/provider/subversion.rb, spec/unit/provider/subversion_spec.rb
See issue at https://github.com/chef/chef/issues/4214
This change allows the subversion provider to respect proxy environment variables, by adding an appropriate proxy configuration to the svn command line.
@chef/client-core @randomcamel @tyler-ball
=> Subversion provider should respect proxies

MAINTAINERS.md, MAINTAINERS.toml
https://github.com/chef/ohai/pull/687 was opened to create a maintainers file in Ohai and it was mentioned that it really should go in chef/chef as its own team.  Here it is.
=> Break out Ohai in maintainers files and add myself

MAINTAINERS.md, MAINTAINERS.toml
We're opening [Chef Provisioning](https://github.com/chef/chef-provisioning) and its drivers up to open source maintenance, in line with other components of Chef.
I've added myself as a Lieutenant and @jkeiser as a Maintainer.  We'll go through the [election process](https://github.com/chef/chef-rfc/blob/master/rfc030-maintenance-policy.md#how-to-become-a) to find more maintainers.
I'm going to have this discussed at the next developer's meeting.  I will also start advertising this potential change so any interested maintainers can come to the developer's meeting.
=> Adding Chef Provisioning to the maintainers file.

lib/chef/platform/provider_mapping.rb
This prevents really weirdo behavior with relative constant lookups like `Chef::Provider.const_get('Resource')` == `ChefVaultCookbook::Resource` which causes all kinds of fun.
Ruby docs tells me this param should exist on all supported rubies so probably just an oversight that we didn't do this before. We should also possibly consider restricting this fallback check to classes under `Chef::Resource` if `class.name` is set (/cc @jkeiser @lamont-granquist for that bit?). Ping @chef/client-core for review.
=> Set inherit=false on the fallback provider constant lookup.

spec/unit/mixin/path_sanity_spec.rb, spec/unit/mixin/xml_escape_spec.rb, spec/unit/util/diff_spec.rb
see https://github.com/whitequark/parser/issues/283
if rubocop works around this bug then we can revert this patch.
=> supresses parser gem errors

chef.gemspec
Ruby 2.0.0 maintenance ended Feb. 24th, 2016.
=> ruby 2.0.0 is EOL

RELEASE_NOTES.md, lib/chef/application.rb, spec/unit/application_spec.rb
Adds `:syslog` and `:win_evt` as possible values for the `log_location` option for easier configuration via node attributes.
=> Add shorthand :syslog and :win_evt for log_location config

RELEASE_NOTES.md, lib/chef/application/client.rb, spec/unit/application/client_spec.rb
The `--daemonize` option takes an optional integer argument for the number of seconds to wait before the first daemonized run.
Closes #3305
=> Add optional integer argument for --daemonize option

lib/chef/knife/ssh.rb, spec/unit/knife/ssh_spec.rb
This adds a config to 'knife ssh' to allow a connection timeout to be specified.
This will prevent knife ssh from hanging if one of the hosts is down or not reachable.
@chef/client-core @tyler-ball
=> Add option to set knife ssh timeout

acceptance/omnitruck/.acceptance/acceptance-cookbook/.gitignore, acceptance/omnitruck/.acceptance/acceptance-cookbook/metadata.rb, acceptance/omnitruck/.acceptance/acceptance-cookbook/recipes/destroy.rb, acceptance/omnitruck/.acceptance/acceptance-cookbook/recipes/provision.rb, acceptance/omnitruck/.acceptance/acceptance-cookbook/recipes/verify.rb
These ensure it only returns 32-bit packages for Chef versions < 12.9
\cc @randomcamel @chefsalim @jrunning @btm 
This PR depends on https://github.com/chef/chef-acceptance/pull/33
=> Adding acceptance tests for Omnitruck

lib/chef/provider/package/homebrew.rb
According to #4715 we can unset TMPDIR to fix this issue
Closes #4715
=> fix for #4715 - unset TMPDIR in homebrew package provider

spec/support/chef_helpers.rb, spec/unit/knife/data_bag_from_file_spec.rb, spec/unit/provider/remote_directory_spec.rb
This issue only surfaces on Windows with Ruby 2.2 only when the user name is longer than 8 characters -- the Windows TEMP environment variable will be set to a path that includes the user's name since it's contained in the user's profile directory, but it will force the usage of an 8 character file name. This causes an issue in the test because while Ruby has always used TEMP when creating temp dirs. used by our tests, some Chef code that operates on it used to also return such (improperly) shortened names, but as of Ruby 2.2 which has been used for Chef only starting in the last week it does not, perhaps due to some improvement in other parts of Ruby.
This fixes the tests so that long file names are expected. However, there may be a need to investigate whether the new Ruby 2.2 behavior …
=> Spec break on Windows due to temp dir and short path names

lib/chef/provider/mount.rb, spec/unit/provider/mount/aix_spec.rb, spec/unit/provider/mount/mount_spec.rb, spec/unit/provider/mount/windows_spec.rb, spec/unit/provider/mount_spec.rb
Closes issue #4056, although as discussed in that issue, we still need followup design and
implementation work to make the mount resource behave in a safe and unsurprising way.
=> Revert PR #1796: make mount resource options-ignorant again.

Gemfile, appveyor.yml, omnibus/config/projects/chef.rb, spec/support/chef_helpers.rb, spec/unit/knife/data_bag_from_file_spec.rb, spec/unit/provider/remote_directory_spec.rb
This reverts commit 3cb10016d142c45d5b2409ecb337b1b7bc295046.
Going back to Ruby 2.1 until we can get chef-acceptance passing.
@adamedx @lamont-granquist @chef/client-core
=> Revert "bump to ruby 2.2.4"

omnibus/Gemfile
\cc @jkeiser @mwrock @randomcamel @chefsalim 
Reverts https://github.com/chef/chef/pull/4781 because https://github.com/jmespath/jmespath.rb/issues/20 was fixed
=> Revert https://github.com/chef/chef/pull/4781 because jmespath was relased with an update to prevent loading issues with json vs json_pure

.travis.yml, lib/chef/resource_builder.rb, lib/chef/resource_collection.rb, lib/chef/run_context.rb, lib/chef/runner.rb, spec/integration/recipes/notifies_spec.rb, spec/unit/resource_collection_spec.rb
This is similar to poise's approach but has a few differences.
Similarly to poise, the base behavior of notifications and find() and
lookup() on the resource collection is changed to be 'recursive' and
to search in outer contexts for resources and will return them by
default.
There are find_local() and lookup_local() methods added to allow for
bypassing the recursion and making sure to throw exceptions if the
current run_context does not have any matching resources.
The CHEF-3694 resource cloning code has been modified to call the
lookup_local() API and not to be recursive because we believe that
nobody in their right mind would want that behavior (and resource
cloning should eventually be removed).  So the behavior of resource
cloning should remain unchanged.
The behavior of delayed …
=> Notifications from LWRPS/sub-resources can trigger resources in outer run_context scopes

lib/chef/provider/service/redhat.rb, spec/unit/provider/service/redhat_spec.rb
Also remove `:enable` from that list because `enable_command` isn't a thing on the service resource. Not clear to me why `:enable` ever worked there.
Alternatively we could modify `custom_command_for_action?` to always return true if `init_command` is set, but that feels weirder to me.
Ping @chef/client-core @chef/client-enterprise-linux for review.
=> Setting init_command should be accepted instead of specific command overrides

chef.gemspec, lib/chef/provider/remote_file/fetcher.rb, lib/chef/provider/remote_file/sftp.rb, lib/chef/providers.rb, spec/unit/provider/remote_file/sftp_spec.rb
This is a PR to fulfill #4043 .  The sftp_provider cookbook has gotten at least one PR since creation and sftp usage is strictly required for my employer's security policy. I think there's enough community need to consider a PR into core now. Additionally the sftp_provider cookbook creates an awkward gem dependency race condition that is addressed if that dependency is delivered with the chef-client install. I structured the spec to be as similar to the ftp spec as possible where appropriate to ensure the interface is similar.
Notable gaps include:
* network proxy capability
* ssh key usage ( username and password in uri are enforced )
These might be addressable but I'm not sure at this time if they are inside the capability of the net-sftp gem.
=> Sftp remote file support

MAINTAINERS.toml
Because my role is changing with Chef, I need to replace myself
with Adam Leff for the lieutenant and maintainer of the Cisco
NX-OS and IOS-XR builds. He's already agreed with this.
/cc @adamleff @chef/client-maintainers
=> Replacing myself with Adam Leff for Cisco LT

lib/chef/knife/ssh.rb, spec/unit/knife/ssh_spec.rb
Adds a default timeout to the new knife ssh timeout option.
@tyler-ball @chef/client-core
=> Add default timeout

lib/chef/cookbook/gem_installer.rb
The gem command in the cookbook metadata uses the bundler API but needs to not leave the chef-client in a 'bundled' state.
Trying to do this in-process always results in a bundled state.  The result is that /other/ cookbooks that access other gems such as a cookbook with:
```ruby
chef_gem "mysql"
require "mysql"
```
Will fail.  Since we can't convert every cookbook from using chef_gem to get metadata (for backcompat reasons, practicality reasons, and because of native gems and build-essentials deps) we need a workaround.
Best workaround I can come up with is to simply fork off a process.  Since windows does not support fork, the easiest way to implement this is to shell_out to `bundle install`.  When the bundle install returns, we are guaranteed that the spawned process hasn't twiddled at …
=> MVP to fix gem metadata command

omnibus/config/projects/chef.rb
/cc: @tyler-ball 
So this path needs to be relative to the `project_root` which is the omnibus directory. So we need to point to the parent to pick up the LICENSE.
Sorry for the break.
=> Point to the right license file for chef.

lib/chef/provider/apt_repository.rb, lib/chef/providers.rb, lib/chef/resource/apt_repository.rb, lib/chef/resources.rb, spec/unit/provider/apt_repository_spec.rb, spec/unit/resource/apt_repository_spec.rb
:construction: needs more tests, but basic review appreciated :construction:
=> Add apt_repository resource

lib/chef/provider/group.rb, lib/chef/provider/group/windows.rb, spec/functional/resource/group_spec.rb, spec/unit/provider/group/windows_spec.rb
This resolves the following issue : https://chefio.atlassian.net/browse/TRI-96
Currently, if removing users from a group, where the user is malformed or does not exist, we error out and fail the recipe. The new behavior is to not fail in this case - we now just log a warning and keep going.
@chef/client-core @tyler-ball @jkeiser
=> Removing non-existent members from group should not fail

omnibus/omnibus.rb
This should be set in the make scripts and cookbooks for the
esoteric platforms that need it. Overriding this to 10 workers
on all platforms is slowing things down and causing massive
resource constrains and failures on smaller platforms (like ARM).
=> Remove override of number of workers to be used.

lib/chef/chef_fs/file_system/repository/chef_repository_file_system_acls_dir.rb, lib/chef/chef_fs/file_system/repository/chef_repository_file_system_entry.rb, lib/chef/chef_fs/file_system/repository/chef_repository_file_system_root_dir.rb, lib/chef/chef_fs/file_system/repository/clients_dir.rb, lib/chef/chef_fs/file_system/repository/containers_dir.rb, lib/chef/chef_fs/file_system/repository/directory.rb, lib/chef/chef_fs/file_system/repository/environments_dir.rb, lib/chef/chef_fs/file_system/repository/groups_dir.rb, lib/chef/chef_fs/file_system/repository/nodes_dir.rb, lib/chef/chef_fs/file_system/repository/policy_groups_dir.rb, lib/chef/chef_fs/file_system/repository/roles_dir.rb, lib/chef/chef_fs/file_system/repository/users_dir.rb, spec/unit/chef_fs/file_system/repository/directory_spec.rb
Internally, this is FLOW-252:
Currently path types in ChefFS are handled inconsistently. 
While some paths have their own type, other paths are implemented by injecting a variable into a generic class, which makes it hard to troubleshoot behavior with just one type of object. For example, if one API call is behaving unexpectedly, additional debug code will likely apply to many other API calls, which makes printf debug output overwhelming and pry debugging annoying. 
ChefFS' design can be improved to make the code clearer to read and modify, which we expect will make future improvements easier.
Some Caveats:
- i've not added tests for the subclasses yet. I'm not sure how much value tests there will be right now.
- The cookbook directories are special snowflakes currently.
=> Refactor ChefFS directories to be directories

lib/chef/property.rb, lib/chef/provider/apt_repository.rb, lib/chef/resource/apt_repository.rb, spec/unit/property/validation_spec.rb, spec/unit/provider/apt_repository_spec.rb, spec/unit/resource/apt_repository_spec.rb
in Chef-13 nillable will become 'true' by default and we'll have
to deprecate and remove all nillable properties, but for now
this lets us opt-in, which was can't currently do in Chef-12.
=> add nillable apt_repository and nillable properties

Rakefile
Just change the top level bundle.
I suspect this is the issue causing version bumper to fail.
=> Don't use berks when bumping version--can't possibly change.

omnibus/files/chef/build-chef.rb
We already install it frozen elsewhere; this makes Windows do the same as other platforms.
=> Refreeze windows

lib/chef/provider/package/rubygems.rb, spec/unit/provider/package/rubygems_spec.rb
```
➜  chef git:(ksubrama+praj/FLOW-298/local_gem) ✗ gem uninstall a
Successfully uninstalled a-0.1.1
##Disable internet before testing
➜  chef git:(ksubrama+praj/FLOW-298/local_gem) ✗ bundle exec sudo bin/chef-apply -e "gem_package '/Users/prajaktapurohit/Downloads/a-0.1.1.gem'"
Recipe: (chef-apply cookbook)::(chef-apply recipe)
* gem_package[/Users/prajaktapurohit/Downloads/a-0.1.1.gem] action install[2016-04-19T12:32:39-07:00] WARN:  gem package /Users/prajaktapurohit/Downloads/a-0.1.1.gem does not satisfy the requirements /Users/prajaktapurohit/Downloads/a-0.1.1.gem (>= 0)
- install version  of package /Users/prajaktapurohit/Downloads/a-0.1.1.gem
➜  chef git:(ksubrama+praj/FLOW-298/local_gem) ✗ gem list | grep "a ("
a (0.1.1)
aruba (0.14.1, 0.11.2, 0.10.2)
```
/cc #@chef/client-core …
=> Update rubygems provider to support local install of gems if so specified

lib/chef/provider/package/easy_install.rb, spec/unit/provider/package/easy_install_spec.rb
This is because easy_install itself is long-since deprecated by the Python community and has been de-facto unmaintained for around 5 years.
Ping @chef/client-core for review.
=> The easy_install provider and resource are deprecated and will be removed in Chef 13

lib/chef/mixin/shell_out.rb, spec/unit/mixin/shell_out_spec.rb
**options has worked ever since we've deprecated ruby 1.9.x
=> modernize shell_out method syntax

.travis.yml, tasks/bin/run_chef_tests
- the bundler args look entirely identical, it is very hard to detect that 'integration' is added to the --without args.
- chef_rewind is on the path to deprecation, we should focus on deprecating it, not fixing the test
- bin/run_chef_tests is removed
there's no additional code duplication with this (the run_chef_tests line gets replaced by the rake spec line everywhere) while the common code is moved back into the .travis.yml file.  IMO, this is good because then all the information is contained withing the .travis.yml file and there's no need for the additional context switch between .travis.yml to the run_chef_tests file when reading it -- removed an unnecessary layer of indirection
=> remove tasks/bin/run_chef_tests; remove commented chef_rewind test; document bundler args

lib/chef/knife/ssl_check.rb, spec/unit/knife/ssl_check_spec.rb
On windows when we `glob` the trusted certs directoty, we always return an empty list of files even if there are certs present because we don't properly delimit the path for `glob`
=> fixes knife ssl check on windows

lib/chef/provider/git.rb, spec/unit/provider/git_spec.rb
@lamont-granquist has been gracious enough to provide specific feedback around https://github.com/chef/chef/pull/4771  I’ll be breaking out changes into the smallest atomic PRs that can be created.  
This pull request is _just_ the changes specific to the consolidation of the git shell_out usage.
**Overview**
The git HWRP currently has a number of instances where git is called directly via ‘shell_out’.  This PR attempts to consolidate the number of code paths to shell_out.
As always feedback is much appreciated.
Thanks! :)
=> Consolidate shell_out usage when calling git within it's HWRP.

lib/chef/decorator.rb, lib/chef/decorator/lazy.rb, lib/chef/decorator/lazy_array.rb, lib/chef/provider/package.rb, lib/chef/provider/package/dpkg.rb, lib/chef/provider/package/rubygems.rb, spec/unit/decorator/lazy_array_spec.rb, spec/unit/decorator/lazy_spec.rb, spec/unit/decorator_spec.rb, spec/unit/provider/package/rubygems_spec.rb, spec/unit/provider/package_spec.rb
This does many things:
1.  Fixes a bug in handling `:update` actions where partial version matches in the new_resource.version like `~> 1.0` wouldn't update 1.1 to 1.2 when it came out.
2.  The rubygems provider was abusing the crap out of setting the candidate_version to nil and using side effects of lying about it to achieve its goals, which has been removed
3.  There's a lot of documentation added around the two badly-named subclass hooks now
4.  The candidate_version is now Lazy'd in the package provider so that we can walk all the arrays in parallel, while still not accessing the candidate_version and doing expensive operations even though we might wind up being completely idempotent.
5.  The LazyArray is necessary for getting multipackage's to be Lazied as well.
6.  The seeming …
=> Lazy'ing candidate_version in package provider

lib/chef/provider/package.rb, lib/chef/provider/package/apt.rb, spec/unit/provider/package/apt_spec.rb, spec/unit/provider/package_spec.rb
general modernization of apt_package
- removing/purging virtual packages works now ( at least a virtual package with only one option -- which is all that we support installing)
=> Make apt package provider use_multipackage_api aware

lib/chef/provider/package/chocolatey.rb, spec/unit/provider/package/chocolatey_spec.rb
Ahoy! I am an employee at Facebook, @jaymzh will be doing the actual merging of this code for the sake of legal thingies.
I was testing the new chocolatey_package provider and found that it was throwing this error when I used it
```
Recipe: my_cookbook::install_things
* chocolatey_package[something] action install
←[0m
Error executing action `install` on resource 'chocolatey_package[something]'
NoMethodError
-------------
undefined method `chomp' for nil:NilClass
```
Digging around I found that the expected output of the chocolatey command includes the program's header, which the `parse_list_output` method was not accounting for. …
=> Chocolatey Package Provider chomps nil object

lib/chef/monkey_patches/win32/registry.rb, spec/functional/win32/registry_spec.rb
This fixes #4897 and addresses a known bug documented [here](https://bugs.ruby-lang.org/issues/11410)
=> Encode registry enumerated values and keys to utf8 instead of the local codepage

lib/chef/provider/package/yum.rb
if you decorate/delegate =~ you can't update the capture variables
which are local to the calling context.
maybe something could be done to update the $~ in the binding of
the caller, but i don't want to do that today...
=> the =~ in ruby is awful

lib/chef/knife/cookbook_site_install.rb
tar.exe  bundled with chef-dk on windows don't support the --force-local option
> STDERR: tar: Option --force-local is not supported
- fixes : #4862
=> cookbook site install : tar error on windows

lib/chef/cookbook/gem_installer.rb
otherwise it'll crash on the first run and have to be re-run
=> gem metadata command needs Gem.clear_paths

acceptance/top-cookbooks/.kitchen.docker.yml
Acceptance tests for Docker are currently failing due to a problem starting a service. For now we'll disable this test and file an issue to track fixing the cookbook or Chef if it's a product issue, or otherwise fixing the test if it's a test issue (which seems more likely given that simply starting the service is failing).
=> Disable Docker cookbook acceptance tests until the cookbook or Chef is fixed

ci/verify-chef.sh
We output all data generated during a chef-acceptance run to the workspace
of the executing Jenkins job using chef-acceptance's `--data-path` option.
If the `chef-acceptance` commands are executed with elevated privileges
(using `sudo`) the generated files are owned by `root`:
https://gist.github.com/schisamo/7ce7262813f2bc81b7314d9eab53afa0
This is an issue as the generated data cannot be properly archived OR
cleaned up when the next job runs:
https://gist.github.com/schisamo/b7246987d49534b27b8a4ad72f9ad965
/cc @chef/engineering-services
=> Execute chef-acceptance without elevated privileges

lib/chef/provider/systemd_unit.rb, spec/unit/provider/systemd_unit_spec.rb
was thinking about this the other day, and wanted to send a PR to raise the subject:
currently, we pass the content string through as-is, which means it's possible to give bad input to systemd. this fixes it so that it will at least be enforced as a well-formed ini-formatted string, but it's not perfect...
pro: ensure well-formed ini content string by attempting to parse as ini before converting back to string
con: `IniParse.parse(str).to_s` reformats the string with spaces between the `=` and an empty line between headings, so it's possible that a valid ini string may not match the exact string as rendered on disk, thus breaking idempotency :frowning:...
maybe this is a case that should just be covered by integration testing, but i figured i'd raise the subject and see what Chef …
=> reject malformed ini content in systemd_unit resource

lib/chef/handler.rb, spec/unit/handler_spec.rb
smear just a little bit of minimal DSL wiring into the Chef::Report
class so that classes can wire themselves up automatically as
handlers.
this also extends the Chef::Config[*_handler] arrays to take classes
as well as instances.
in the case of passing a class that is not a singleton, a new instance
will be created when the report is run.  it will obviously be difficult
to pass any state into this instance.
if the class that is passed supports calling `#instance` we assume it
is a Singleton and get the instance and use that.  this is to support
other chef code grabbing/creating the singleton instance and poking
it with data (probably configuring where the reporter goes and what
creds it needs to publish and other stuff).
=> wire up chef handlers directly from libraries

chef-config/lib/chef-config/config.rb, lib/chef/application/apply.rb, lib/chef/application/solo.rb, lib/chef/client.rb, lib/chef/cookbook/synchronizer.rb, lib/chef/data_bag.rb, lib/chef/data_bag_item.rb, lib/chef/deprecation/provider/remote_file.rb, lib/chef/environment.rb, lib/chef/policy_builder/dynamic.rb, lib/chef/policy_builder/expand_node_object.rb, lib/chef/policy_builder/policyfile.rb, lib/chef/shell/shell_session.rb, spec/integration/solo/solo_spec.rb, spec/unit/application/apply_spec.rb, spec/unit/application/solo_spec.rb, spec/unit/client_spec.rb, spec/unit/cookbook/synchronizer_spec.rb, spec/unit/data_bag_item_spec.rb, spec/unit/data_bag_spec.rb, spec/unit/environment_spec.rb, spec/unit/policy_builder/dynamic_spec.rb, spec/unit/policy_builder/policyfile_spec.rb
This switches the default operation of chef-solo to be equivalent to `chef-client -z`, but allows for the old style chef-solo by uttering `chef-solo --legacy-mode`.
=> RFC 31 - Default solo to local mode

acceptance/Gemfile.lock, ci/verify-chef.sh
All chef-acceptance logs and generated data is now properly archived with the job:
http://manhattan.ci.chef.co/job/chefdk-test/183/architecture=x86_64,platform=acceptance,project=chefdk,role=tester/artifact/chef-acceptance-data/chef-dk/
These changes were tested in the following ad hoc build:
http://manhattan.ci.chef.co/job/chef-test/6/architecture=x86_64,platform=acceptance,project=chef,role=tester/console
There was one failure in the `top-cookbooks` suite which appears to be an acceptance failure (as opposed to an error in the code that executes the acceptance suites):
http://manhattan.ci.chef.co/job/chef-test/6/architecture=x86_64,platform=acceptance,project=chef,role=tester/artifact/chef-acceptance-data/logs/top-cookbooks/provision.log/*view*/
/cc @chef/engineering-services @adamedx …
=> Re-enable and fix acceptance tests

lib/chef/provider/git.rb, spec/unit/provider/git_spec.rb
The user property of the git resource fails when passing the user id instead of the user name. Similarly to what is described in #2860. The problem comes from the fact that the function used to retrieve the user's home only takes a String as input. The changes in this PR allows to retrieve the user's home when the user id is being used. 
Latest available RPM installed automatically via vagrant
Centos 6.5
```
git /tmp/mydir do
repository 'ssh://git@somehost.tld/myrepo.git'
revision 'master'
user <user id>
group <group id>
end
```
From memory (will update later with proper output I can't access now):
```
TypeError: no implicit conversion of Integer into String
```
Raised at this line: https://github.com/chef/chef/blob/master/lib/chef/provider/git.rb#L300
=> Handle numeric id for the user value in the git resource

lib/chef/application.rb, lib/chef/application/apply.rb, lib/chef/application/client.rb, lib/chef/application/exit_code.rb, lib/chef/application/solo.rb, lib/chef/application/windows_service.rb, lib/chef/config_fetcher.rb, lib/chef/exceptions.rb, lib/chef/platform/rebooter.rb, spec/integration/client/exit_code_spec.rb, spec/unit/application/apply_spec.rb, spec/unit/application/exit_code_spec.rb, spec/unit/config_fetcher_spec.rb
To test the behavior, 
```ruby
bundle exec rspec ./spec/integration/client/exit_code_spec.rb
```
There are two integration tests marked pending that should be safe but appear not to cancel the reboot on travis in time.
=> RFC062 exit status chef client

Gemfile, tasks/bin/bundle-platform, tasks/bundle_util.rb
As of bundler 1.12.0, running our rake bundler tasks wipes out the windows dependencies when run on mac/linux and wipes out the non-windows dependencies when run on windows. This change can be narrowed down to a change to the `gemspec` DSL in [this one line](https://github.com/bundler/bundler/blob/master/lib/bundler/dsl.rb#L71). v1.12.0.pre.1 added the `platform` parameter. Removing that parameter duplicates the behavior we see in 1.11.2. We can get this same behavior by not using `gemspec` and calling `gem` instead via `path: "."`.
I'm not crazy about this trickery but it appears to be the best way to support 1.12.4 and beyond.
=> fix bundle locking on bundler 1.12

lib/chef/provider/package/chocolatey.rb, spec/functional/resource/chocolatey_package_spec.rb, spec/unit/provider/package/chocolatey_spec.rb
This should fix retrieving the wrong package version when expecting the latest and should also significantly improve package query performance. It also supports some feeds that do not implement the all versions capability.
We now only query the chocolatey feed for the latest version and use that as the candidate version unless an explicit version is requested and then that is the candidate.
This does prevent us from validating valid versions and allows a resource with a bogus version. In these cases we will bubble up the error from choco.exe.
=> fixes #4968 and only retrieves the latest version of packages from chocolatey

lib/chef/provider/package/portage.rb, spec/unit/provider/package/portage_spec.rb
I ran into an issue where chef 12 installs openssl 1.0.2d even if it's already installed. It doesn't support the character on the version, `d`.
According to `man 5 ebuild`
> 
Versions  are  normally made up of two or three numbers separated by periods, such as 1.2 or 4.5.2.  This string may be followed by a character such as 1.2a or 4.5.2z.  Note that this letter is not meant to indicate alpha,  beta,  etc...  status.   For  that,  use  the  optional  suffix;  either  _alpha,  _beta,  _pre (pre-release),  _rc  (release candidate), or _p (patch).
I added a test which failed before I added the fix. `bundle exec rspec spec/unit/provider/package/portage_spec.rb ` shows passing tests.
This is my first PR on chef so let me know if I need to change anything.
=> Fix portage provider to support version with character

lib/chef/provider/systemd_unit.rb, lib/chef/resource/systemd_unit.rb, spec/unit/provider/systemd_unit_spec.rb
systemd has some fancy unit commands that do roughly the equivalent of the service resource's "supports" behavior for reloads, where you can say "reload-or-restart" and it'll issue a restart if the unit doesn't support reloading (as defined by the ExecReload directive);
they're defined as:
- try-restart: Restart one or more units if active
- reload-or-restart: Reload one or more units if possible, otherwise start or restart
- reload-or-try-restart: Reload one or more units if possible, otherwise restart if active
=> add systemd_unit try-restart, reload-or-restart, reload-or-try-restart actions

lib/chef/dsl/platform_introspection.rb, lib/chef/provider/file.rb, lib/chef/resource/file.rb
This commit fixes https://github.com/chef/chef/issues/4949 by adding
ohai-based docker detection code and statically checking for
/etc/hostname or /etc/resolv.conf.
cc @lamont-granquist
=> Fix #4949 and Avoid Errno::EBUSY on docker containers

lib/chef/provider/directory.rb, spec/unit/provider/directory_spec.rb
=> Don't mask directory deletion errors

lib/chef/data_collector.rb, lib/chef/data_collector/messages.rb, spec/unit/data_collector/messages_spec.rb, spec/unit/data_collector_spec.rb
After adding up-to-date and skipped resources to the DataCollector
resource list, the logic that computed the number of resources
updated needed to change accordingly. This change fixes that
bug and also eliminates an unnecessary counter that tracks
the total number of resources.
=> Bug fix: updated_resource_count should only include updated resources

kitchen-tests/.kitchen.travis.yml
This fixes the nokogiri compile failures on TK fedora
=> install zlib-devel and rpm-build on fedora kitchen docker

lib/chef/provider.rb, lib/chef/resource.rb
http://manhattan.ci.chef.co/job/chef-trigger-ad_hoc/28/downstreambuildview/
```
➜  test-custom-resource-bug kitchen converge original-chef-12-9-41
-----> Starting Kitchen (v1.7.3)
-----> Creating <original-chef-12-9-41>...
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'bento/ubuntu-14.04'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/ubuntu-14.04' is up to date...
==> default: A newer version of the box 'bento/ubuntu-14.04' is available! You currently
==> default: have version '2.2.5'. The latest is version '2.2.7'. Run
==> default: `vagrant box update` to update.
==> default: Setting the name of the VM: kitchen-test-custom-resource-bug-original-chef-12-9-41_default_1465241273190_44789
==> …
```
=> no more missing constants for LWRP class

lib/chef/data_collector/messages/helpers.rb, spec/unit/data_collector/messages/helpers_spec.rb
When we changed the messages from class instances to a module, the
reading of metadata into an instance variable was removed and
introduced a bug when updating metadata. This bug causes the
metadata to be properly read from disk, updated, but then the
metadata from disk is simply re-written to disk without the
intended updates.
=> bug fix: correctly write out data collector metadata file

lib/chef/provider/remote_directory.rb, spec/unit/provider/remote_directory_spec.rb
```
➜  remote_directory_example git:(master) ✗ sudo bundle exec chef-client -z -o remote_directory[2016-06-13T17:35:20-07:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.12.2
[2016-06-13T17:35:27-07:00] WARN: Run List override has been provided.
[2016-06-13T17:35:27-07:00] WARN: Original Run List: []
[2016-06-13T17:35:27-07:00] WARN: Overridden Run List: [recipe[remote_directory]]
resolving cookbooks for run list: ["remote_directory"]
Synchronizing Cookbooks:
- remote_directory (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: remote_directory::default
* remote_directory[/var/www/html] action create
- create new directory /var/www/html
- change mode from '' to '0755'
Recipe: …
```
=> Remote resource should respect sensitive flag

lib/chef/chef_fs/file_system/multiplexed_dir.rb
A previous change introduced what appears to be a copy/paste bug. A guard condition from the children
method was used in the make_child_entry incorrectly.
This removes the reference to the non-existent variable `seen`
=> Fix for #5027 - Remove bad variable reference

lib/chef/knife/cookbook_site_download.rb, lib/chef/knife/cookbook_site_install.rb, lib/chef/knife/cookbook_site_list.rb, lib/chef/knife/cookbook_site_search.rb, lib/chef/knife/cookbook_site_share.rb, lib/chef/knife/cookbook_site_show.rb, lib/chef/knife/cookbook_site_unshare.rb, lib/chef/knife/supermarket_download.rb, lib/chef/knife/supermarket_install.rb, lib/chef/knife/supermarket_list.rb, lib/chef/knife/supermarket_search.rb, lib/chef/knife/supermarket_share.rb, lib/chef/knife/supermarket_show.rb, lib/chef/knife/supermarket_unshare.rb, spec/unit/knife/cookbook_site_download_spec.rb
Include all knife supermarket sub commands here, and allow all knife
cookbook site commands to have a configurable supermarket URL.
cc @chef/client-dev-tools @robbkidd
=> Deprecate knife-supermarket gem

lib/chef/provider/package/windows/exe.rb, spec/unit/provider/package/windows/exe_spec.rb
Replaces PR #4831 largely keeping its implementation but quoting the string if it is a existing file. Researching this it looks like NullSoft often (but not always) does not quote the uninstall string. Most other installers do provide quotes unless they truly are not needed.
=> fixes some uninstall scenarios by calling uninstall string directly

lib/chef/knife/core/bootstrap_context.rb
We want client_d, not cliend_d
=> correct typo in knife bootstrap context

chef-config/lib/chef-config/config.rb, chef-config/spec/unit/config_spec.rb
This PR fixes build breaks in the chef-dk jenkins debian and redhat testers when they run chef unit tests. They currently fail due to a mocking expectationi error on `::File.read` because `ChefConfig` reads `/proc/sys/crypto/fips_enabled` early in the run. and the breaking tests expect a different path.
As an alternative to mocking the call to `read` on the fips path which would be irrelevant to the test and likely raise questions as to why that is being mocked, this PR allows the fips check to have a forced `false` value if the `FIPS_ENABLED` variable is present but empty and if so, the check of the fips file is avoided.
So the following `FIPS_ENABLED` values have the following impact:
value | impact
------- | ----------
`nil` | unknown and the systems settings are checked incurring a …
=> Turn off fips with an empty environment var

lib/chef/application/solo.rb, spec/unit/application/solo_spec.rb
Solo has always defaulted to `/var/chef` but local-mode uses the user's
home directory, so we need to ensure that we set the correct path before
entering local-mode.
Fixes: #5051
=> Ensure that chef-solo uses the expected repo dir

lib/chef/data_collector.rb, lib/chef/data_collector/messages.rb, lib/chef/data_collector/resource_report.rb, spec/unit/data_collector/messages_spec.rb, spec/unit/data_collector_spec.rb
Historically when a Chef run fails, the event handlers only report
on resources that have been processed during the run. This change
allows the Data Collector to report those resources in the resource
collection that have not yet been processed so users can better
ascertain how much of their run was completed, and specifically
what resources were not processed as a result of the Chef failure.
Instead of building up a list of resources as they are processed,
this change instead creates a resource report for each resource+action
in the resource collection and then modifies each of those reports
once the resource is processed.
=> Expand data_collector resource list to include all resources

lib/chef/http.rb
Similar to https://github.com/chef/chef/pull/4693 .
With ruby 2.3, chef-client run throws warnings like `Thread.exclusive is deprecated, use Mutex`.
This has been confirmed with chef version  `12.10.24`.
Removing Thread.exclusive based on [this comment](https://github.com/chef/chef/pull/4693#issuecomment-195597601) and [this comment](https://github.com/bundler/bundler/pull/4245#discussion_r51481284).
Please let me know if there is something else necessary.
=> Remove deprecated Thread.exclusive around require call.

acceptance/data-collector/test/integration/default/serverspec/default_spec.rb, lib/chef/data_collector.rb, lib/chef/data_collector/messages.rb, lib/chef/data_collector/resource_report.rb, spec/unit/data_collector/messages_spec.rb
Many use cases that involve consuming the run_converge messages and
displaying them to end users include needing additional data about
the node that generated the run_converge message. This change
consolidates the run_converge and node_update message into a single
message making it easier for users to filter run_converge messages
based on attributes and criteria of the node itself.
=> Adding node object to Data collector run_converge message

Gemfile, Gemfile.lock
Rack 2.0 was released today and it requires Ruby 2.2+ now, which is
breaking Travis runs on anything that depends on Chef. This should get
our builds running again.
=> Depend on rack < 2

lib/chef/property.rb, lib/chef/resource_builder.rb, spec/support/lib/chef/resource/zen_master.rb, spec/unit/recipe_spec.rb
- clean up "ZenMaster" resource
- clean up 3694 detection to use properties
- unlazy the resource_name in the trivial resource check
- fixes an issue with resources-as-definitions pattern emitting
3694 errors for trivial resources
=> tweak 3694 warnings

acceptance/.shared/kitchen_acceptance/libraries/kitchen.rb, acceptance/Gemfile.lock
Let me know if I should leave the updated Gemfile.lock in there.
locally:
```➜  acceptance git:(praj/FLOW-370/acceptance_logging) ✗ ls .acceptance_data/logs/kitchen/basics/logs/
chef-current-install-ubuntu-1404.log kitchen.log
```
on ci:
http://manhattan.ci.chef.co/job/chef-test/57/architecture=x86_64,platform=acceptance,project=chef,role=tester/artifact/chef-acceptance-data/logs/
=> The kitchen logs per instance per suite for acceptance are now in ci

lib/chef/data_collector.rb, lib/chef/data_collector/resource_report.rb, spec/unit/data_collector_spec.rb
If a user configured data_collector.server_url in their Chef config
as an empty string, we blissfully passed it along to Chef::HTTP
which would eventually raise a TypeError when trying to dup the
URI's host. This change validates the server_url when setting up
the Data Collector and gives helpful error messages to the user.
We also count Errno::EHOSTDOWN as an error worthy of disabling
the Data Collector reporter for a given run if the user so chooses.
=> Data Collector server URL validation, and disable on host down

lib/chef/provider/package/aix.rb, spec/unit/provider/package/aix_spec.rb
bff packages can include multiple "filesets" under a single "software product". The individual filesets are the actual installed artifact and nodes can cherry pick these filesets or just provide the product name thereby installing all filesets in the product.
As the bff/aix pacjkage provider stands today, it only treats package names that refer to individual filesets idempotently. I can install an entire product but when given the product name, it is not idempotent and will converge the resource on every run.
#5071 was an attempt to "fix" this but it was agreed that shoehorning a "group" concept into this provider was not the right path. So this PR basically extends an olive branch to users who wonder why their packages always converge. It warns them that the package is not an individual …
=> Warn if not installing an individual bff fileset

lib/chef/provider/package/zypper.rb, spec/unit/provider/package/zypper_spec.rb
This is backward compatible with zypper version 1.12.* (used by SLES11SP4).
=> Fixed regex for zypper version 1.13.*. 

lib/chef/dsl/cheffish.rb
This method is included in the docs: https://docs.chef.io/resource_chef_data_bag_item.html and Cheffish's README: https://github.com/chef/cheffish but was missed when we made chef-provisioning and cheffish lazy-load in 010392858c2a3a036578b681085704ed1971ab21
=> Add `chef_data_bag_item` to Cheffish DSL methods

lib/chef/resource.rb, lib/chef/run_context.rb
John K and I are 99% sure those branches have never been used outside of
unit tests. Fingers crossed!
=> Clean up subscribes internals and notification storage.

lib/chef/knife/bootstrap.rb, lib/chef/knife/core/bootstrap_context.rb
Using `knife bootstrap --bootstrap-proxy` it is not currently possible to provide proxy authentication credentials.  Including credentials in the URL does not seem to work, as apparently Chef requires explicit  `http_proxy_user` and `http_proxy_pass` entries in client.rb.
=> Add bootstrap proxy authentication support.

lib/chef/audit/audit_reporter.rb
This changes the log message to `debug` when running in local-mode as it's not an error that the audit-data could not be sent to the server.
I'm not very familiar with the internals of `chef/chef` so any feedback is appreciated.
Fixes https://github.com/chef/chef/issues/4728
=> Don't log error for reporting audit data in when in chef-zero

Gemfile.lock, acceptance/Gemfile.lock, kitchen-tests/Gemfile.lock, omnibus/Gemfile.lock
Replaces #5168
Manually added back ffi line in kitchen-tests/Gemfile.lock that was failing travis.
=> Bump dependencies to bring in Ohai 8.18

lib/chef/provider/apt_repository.rb, lib/chef/provider/apt_update.rb, spec/unit/resource/apt_repository_spec.rb, spec/unit/resource/apt_update_spec.rb
makes apt_update behave similarly to apt_repository when invoked on non-apt-using distros
=> noop apt_update similar to apt_repository

lib/chef/recipe.rb
these are all covered under chef/dsl/recipe now
=> remove requires in Chef::Recipe that are no longer necessary

omnibus/config/software/chef-complete.rb
From what I can tell by looking at jenkins build logs, Windows is the only platform where actual files are deleted by this build delendency defined [here](https://github.com/chef/omnibus-software/blob/master/config/software/clean-static-libs.rb). The files deleted on Windows are:
```
Deleting C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/libyajl2-1.2.0/ext/libyajl2/libyajldll.a
Deleting C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/lib/libyajldll.a
```
These files are each about 32k. Further, the `ffi-yajl` gem depends on these libraries. So if a user attempts to install a different version of lib-yajl or a gem that depends on it, they will receive compilation errors blocking the install.
=> Keeping static libraries previously deleted by jenkins builds

.rubocop.yml, lib/chef/cookbook/synchronizer.rb, lib/chef/http.rb, lib/chef/http/basic_client.rb, spec/unit/cookbook/synchronizer_spec.rb, spec/unit/http/basic_client_spec.rb, spec/unit/http_spec.rb
- leverages ruby 2.x so no need for net/http/persistent
- does not try to do everything and just solves the problem for clients that correctly reuse their Net::HTTP objects
- patches the cookbook synchronizer to reuse Net::HTTP objects which is probably 90% of the battle
closes #1617 
replaces #1792
=> HTTP 1.1 keepalives re-re-redux

spec/support/shared/functional/file_resource.rb
This is another fix for ensuring aborted functional tests do not corrupt subsequent runs. Here we make sure that the test directory is deleted in case it was not cleared out by the aborted run.
=> Clear test directory before file resource examples

lib/chef/cookbook/cookbook_version_loader.rb, spec/integration/knife/chef_repo_path_spec.rb
Windows Ruby 2.3 Dir.glob() translates pathnames like ADMINI~1 to Administrator, making the comparison fail.
=> Don't use relative_path_from on glob results

omnibus/Gemfile, omnibus/Gemfile.lock, omnibus/config/software/chef-appbundle.rb, omnibus/config/software/chef-complete.rb, omnibus/config/software/chef-gem-binding_of_caller.rb, omnibus/config/software/chef-gem-byebug.rb, omnibus/config/software/chef-gem-debug_inspector.rb, omnibus/config/software/chef-gem-ffi-yajl.rb, omnibus/config/software/chef-gem-ffi.rb, omnibus/config/software/chef-gem-json.rb, omnibus/config/software/chef-gem-libyajl2.rb, omnibus/config/software/chef-gem-mini_portile2.rb, omnibus/config/software/chef-gem-nokogiri.rb, omnibus/config/software/chef-gem-pkg-config.rb, omnibus/config/software/chef-gem-ruby-prof.rb, omnibus/config/software/chef-gem-ruby-shadow.rb, omnibus/config/software/chef-remove-docs.rb, omnibus/omnibus.rb
This PR goes with https://github.com/chef/omnibus/pull/705 and https://github.com/chef/omnibus-software/pull/714 and adds licensing information collection for the transitive dependencies of Chef Client. 
An ad_hoc build with all these branches are tested at:
http://manhattan.ci.chef.co/job/chef-trigger-ad_hoc/157/downstreambuildview/
Note that the PRs linked from here do not contain the msys2 changes that are currently sitting in the private branches of `omnibus` and `omnibus-software` pointed to by this project. Once they are merged we will need to rebase the private branches on top of master and re-test.
=> Transitive dependency licensing information for Chef Client

omnibus/Gemfile.lock
Pick up the license_scout version that overrides the license information for json gem on Ruby 2.3 correctly.
/cc: @jkeiser
=> Pick up the final license_scout version

spec/integration/solo/solo_spec.rb
removes the requirement that the second wait for the first, just that
one of them waits for the other, so if we ever somehow lose that race
and the second wins the run_lock as long as the first sleeps then its
all good...
this now removes all the sleeps and just uses the logfile for IPC so that the first
run only exits after the second run writes its logline that its waiting on the first.
on my mac this results in exactly zero calls to sleep now.
upper bound is still that it'll wait for 20 seconds for insanely slow hosts, but it now exits as soon as it can rather than taking 25 minutes no matter how slow the host is.
=> speed up solo test

lib/chef/provider/group/usermod.rb
Action is an array.  We need to check to see if create is in the action
array instead of checking to see if it's ";create" which it never will
be.
Fixed #3780
=> Fix specify members of group on suse/openbsd/solaris2/hpux

spec/functional/assets/testchefsubsys
This looks like a typo was introduced; we're seeing this in the logs on nodes.
=> Stop logging "SIGQUIT is not a command" in tests

.travis.yml, Gemfile, Gemfile.lock, chef.gemspec, kitchen-tests/.kitchen.travis.yml
=> remove ruby 2.1 support

spec/functional/http/simple_spec.rb, spec/functional/knife/cookbook_delete_spec.rb, spec/functional/knife/exec_spec.rb, spec/functional/knife/ssh_spec.rb, spec/functional/resource/remote_file_spec.rb, spec/functional/rest_spec.rb, spec/functional/tiny_server_spec.rb, spec/integration/client/client_spec.rb, spec/tiny_server.rb
1. Wait for the start callback rather than the do block, as it happens
later. This prevents us from getting into many conditions where the
start returns before the server is fully initialized, where if stop()
is called too soon after start returns, it would cause exceptions.
2. Wait for the thread to finish completely
3. Use Thread.current.abort_on_exception` to show the actual listen errors,
so that problems like this can be diagnosed.
4. Use :each to start and stop TinyServer so that race conditions like this
are exposed earlier and more often (this will let us rid ourselves of them
more quickly).
5. Use WEBrick::HTTPServer directly, which gets rid of the need for the
complicated trap workaround (rack is the one that traps).
=> Fix TinyServer races by waiting for stop() and start() callbacks

Gemfile.lock, chef-config/chef-config.gemspec, chef-config/lib/chef-config/config.rb, chef.gemspec, lib/chef/knife/search.rb, lib/chef/mixin/uris.rb, lib/chef/search/query.rb, spec/unit/provider/remote_file/local_file_spec.rb
We'll use `Addressable::URI` instead. See http://stackoverflow.com/questions/2824126/whats-the-difference-between-uri-escape-and-cgi-escape#answer-13059657 for details on why.
=> Fix "URI.escape is obsolete" warnings

lib/chef/provider/package/windows.rb
Hello,
The package providers is instantiating the remote_file resource manually, i.e. not using the DSL.
This means the cookbook_name attribute of the resource is not set; it's sometimes useful to have this information.
I patched the windows_package using the DSL (see chef-cookbooks/windows#318), but this time I decided to only forward the cookbook_name to the newly created resources.
That means maybe other attributes may be missing. I can change my PR if you want :)
Regards!
Cc: @aboten
=> Forward package cookbook_name to underlying remote_file

lib/chef/resource/conditional.rb, spec/unit/resource/conditional_spec.rb
This will hopefully catch errors like this:
```ruby
myresource 'name' do
not_if { 'some command' }
end
```
Anyone that doesn't want to see the warning can throw a `!!` in their block. I special cased empty strings as a gut feeling but I can't back that up so no argument on changing that behavior. Ping @chef/client-core for review.
=> Add a warning for guard blocks that return a non-empty string

lib/chef/provider/systemd_unit.rb
Fixes #5200 
I realise there are no tests for this feature. That is because I wasn't able to find any pre-existing tests relating to the internal file block on which to base any new ones.
=> Verify systemd_unit file during create

lib/chef/mixin/properties.rb, lib/chef/property.rb, lib/chef/resource.rb, spec/unit/resource_spec.rb
Some properties in custom resources may include sensitive data, such as a
password for a database server. When the Resource's state is built for use by
Data Collector or similar auditing tool, `Chef::Resource#state_for_resource_reporter`
builds a hash of all state properties for that resource and their values. This
leads to sensitive data being transmitted and potentially stored in the clear.
This change enhances properties with the ability to set an individual property
as sensitive and then have the value of that property suppressed when exporting
the Resource's state.
As a Visibility user,
I want to be able to view my Chef runs which include custom resources,
which may include custom resources whose property values may be sensitive,
and ensure that the sensitive values are not …
=> Allow flagging a resource property as sensitive

lib/chef/provider/service/systemd.rb, lib/chef/provider/systemd_unit.rb, spec/unit/provider/service/systemd_service_spec.rb, spec/unit/provider/systemd_unit_spec.rb
Using the user property of the service resource when using systemd (on omnibus chef-12.13.30-1 (possibly older versions as well)) causes:
TypeError: no implicit conversion of Hash into String
This appears to be stemming from https://bugs.ruby-lang.org/issues/10708 - the type of hash key used influences how args are handled when splat / doublesplat are in play - both of which are used in newer mixin/shell_out function definitions (older "def shell_out(*command_args)" versus newer "def shell_out(*args, **options)").  Changing the hash keys to symbols in get_systemctl_options_args addresses this.
Sample code to demonstrate problem:
https://gist.github.com/joshuamiller01/43f4ccc86d69d1e3ba8f5dc357b7062e
=> Use symbols instead of strings as keys for systemd user property

lib/chef/provider/user/linux.rb, spec/support/shared/unit/provider/useradd_based_user_provider.rb
this removes the kinda brittle kinda insane parsing of the installed
rpm version.  now we're just less strict about the exit 1 code and
fail on the output not being what is expected.
this also likely fixes a bug in rhel in why-run mode where shell_out!
would have failed on the user-not-found and raised an exception that
would have ended the run.  the code before certainly looks buggy.
=> rewrite linux_user provider check_lock

lib/chef/run_context.rb
this is to address some of the regressions in compat_resource -- when we run this as a monkeypatch over old run_context classes we need to be able to skip these checks or it blows up if we have cheffish or chef-provisioning installed due to $REASONS.
=> add a hook for compat_resource

spec/integration/solo/solo_spec.rb
- fix the 'last' statements (my perl brain occassionally crops up
in ruby code) and replace with a raise.  of course this just swaps
one exception for another, but this time its really intended to
work this way.
- swap the order of the expecations so that if we fails to see the
waiting on the other process statement, but we blow up in both
threads in the exception that was just added, we know we actually
have a legit run_lock race condition that this code just found.
does not fix this bug, just gets us a bit more information if it
reoccurs.
=> tweak chef-solo run_lock timing test

lib/chef/resource/launchd.rb
The launchd resource only allows True/False values for the keep_alive property. This allows you to pass hash values as well, which are valid values for LaunchDaemons/Agents.
=> Add Hash type to launchd:keep_alive

lib/chef/event_dispatch/base.rb, lib/chef/formatters/base.rb, lib/chef/run_context/cookbook_compiler.rb, spec/unit/event_dispatch/dispatcher_spec.rb, spec/unit/run_context/cookbook_compiler_spec.rb
This also extends two of the recipe events to get the recipe name in addition to the path because that's usually useful for display. These arguments are both added at the end so the auto-magic argument trimmer will keep backwards compat.
Ping @chef/client-core for review. We should probably do a general audit on all the events to see if any others were defined and never cabled.
=> Hook up the recipe_file_loaded event which was defined but not actually called

chef-config/lib/chef-config/config.rb, lib/chef/knife.rb
This deeply hurt my brain to figure out, and I don't want to have to research this twice.
There's a spec test in mixlib-config verifying that this is the actual behavior of mixlib-config:
https://github.com/chef/mixlib-config/pull/44
=> Document strange config_context :knife voodoo 

.travis.yml, Gemfile, Gemfile.lock, version_policy.rb
Because chef-zero is pinned, oc-chef-pedant must be pinned too (as its test suite). They must move forward together or not at all. This difference caused a Travis breakage the other day.
=> Pin oc-chef-pedant to prevent unintended test slippage

lib/chef/resource/yum_repository.rb
The :delete action wasn't working and this is the documented action so this is a pretty big break. Also we weren't allowing the legacy properties that a good chunk of people are still using.
=> Allow the :delete action for yum_repository + fix old property support

CHANGELOG.md, RELEASE_NOTES.md
We missed a few important things in the release notes and we needed to call out the yum_repository work in a way that it could be cmd-F'd in the changelog.
=> Update the changelog and release notes for 12.14.60/65

lib/chef/file_content_management/tempfile.rb, spec/unit/file_content_management/tempfile_spec.rb
helps out with verification steps where the tempfile may be passed to a program
which gets annoyed if the extension isn't correct.
closes https://github.com/chef/chef/issues/5324
=> preserve the extension of the file in the rendered tempfile in File providers

spec/unit/file_content_management/tempfile_spec.rb
thought this was green, but it was clearly red on appveyor/windows
code was correct, only tests were broken.
=> derp fix for master breakage

kitchen-tests/cookbooks/base/recipes/default.rb, kitchen-tests/cookbooks/base/recipes/tests.rb, lib/chef/file_content_management/tempfile.rb, lib/chef/resource/file.rb
it looks like we broke this awhile back with the docker specific check in the file provider (but only broke it in docker containers)
and the tempfile fix that went into master just broke this as well for everyone, but that version was never released.
adds a test (which conveniently runs in a docker container) so that hopefully we don't regress again.
=> fix non-utf8 filename issues in the file provider (again)

lib/chef/resource/yum_repository.rb
Our allowed action in the resource doesn't match the action name in the provider. 
makecache is the correct action not make_cache:
https://github.com/chef-cookbooks/yum/blob/master/providers/repository.rb#L100
Signed-off-by: Tim Smith tsmith@chef.io
=> Fix makecache action name in yum_repository

RELEASE_NOTES.md
Release notes are now aggregated for all minor releases, so changing the docs.chef.io location to reflect that change.
=> Updated location for latest release notes

spec/integration/solo/solo_spec.rb
caused by a race condition (not actually fixed) where the pid
can be read by the process which lost the race to lock it before the
pid has been written by the process which got the lock.
the result is a message like:
"WARN: Chef client  is running, will wait for it to finish and then run."
without any numerical pid.
i'm not super concerned with fixing the race, this will unbreak a lot
of red travis failures though.
=> fix chef-solo spec timeouts

lib/chef/provider/systemd_unit.rb
Reverts chef/chef#5210 since this appears to be a breaking change. See https://github.com/chef/chef/issues/5324
=> Revert "Verify systemd_unit file during create"

lib/chef/cookbook/metadata.rb, spec/unit/cookbook/metadata_spec.rb
if we're just using chef-zero there's no metadata.json file so
chef-client doesn't do json parsing (which ignores unknown metadata
fields already) but parses metadata.json which explodes.
i believe since TK goes through berks it renders the rb to json before
copying to the virt so we don't see this in TK or in running chef-client
from a real server.
this only affects the chef-client -z or chef-zolo mode of operation (and
probably legacy chef-solo)
=> ignore unknown metadata fields in metadata.rb

spec/functional/resource/ifconfig_spec.rb
Modified `ifconfig` resource's functional spec to handle `persistent stateless network interface names (deprecation of eth0)`, introduced in `Ubuntu 16.04` OS.
=> Fix for ifconfig resource's functional spec.

CONTRIBUTING.md
Make it a bit more generic to Chef projects.
Mention how to report security issues
Mention the feedback site
=> Improvements to the contributing doc

lib/chef/node/attribute.rb, lib/chef/node/attribute_collections.rb, spec/unit/node/attribute_spec.rb, spec/unit/node/vivid_mash_spec.rb, spec/unit/node_spec.rb
Chef-12 changes the behaviour of how attributes that are defined as literal arrays are handled, such as they do not longer work as they did in Chef-11
given an attributed defined as an array of hashes
```
node['foo'] = [ {'key' => 'value'} ]
```
in Chef-11 accessing using symbols or strings works seamlessly, while in Chef-12 yields different results, i.e.
```
node['foo'].first['key'] == node['foo'].first[:key]  
```
returns `true` in Chef-11 and `false` in Chef 12, as in the latter `node['foo'].first[:key]` is `nil`
I created [a gist with a really basic cookbook](https://gist.github.com/gbagnoli/7fc007c3f67869faf8081f9f584268b4) that shows the problem -- `result_unpatched.txt` is the rendered template using code from master and `result_patched.txt` contains the same template rendered with …
=> Chef 12 Attribute Regression

lib/chef/knife.rb
this was not supposed to be private
Fixes this:
```
/Users/lamont/.rvm/gems/ruby-2.3.1/gems/chef-12.14.77/lib/chef/application/knife.rb:212:in `print_help_and_exit': private method `list_commands' called for Chef::Knife:Class (NoMethodError)
Did you mean?  subcommands
from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/chef-12.14.77/lib/chef/application/knife.rb:176:in `validate_and_parse_options'
from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/chef-12.14.77/lib/chef/application/knife.rb:154:in `run'
from /Users/lamont/.rvm/gems/ruby-2.3.1/gems/chef-12.14.77/bin/knife:25:in `<top (required)>'
from /Users/lamont/.rvm/gems/ruby-2.3.1/bin/knife:23:in `load'
from /Users/lamont/.rvm/gems/ruby-2.3.1/bin/knife:23:in `<main>'
from /Users/lamont/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval' …
```
=> fix knife list_commands()

omnibus/Gemfile, omnibus/Gemfile.lock
This updates to a branch that was based on the lcg/ruby23 branch.
https://github.com/chef/omnibus-software/compare/lcg/ruby23...shain/ruby_windows_monster
=> Update to a 'newer' omnibus-software branch

lib/chef/provider/package/rubygems.rb, spec/unit/provider/package/rubygems_spec.rb
pr #5098 was intended tom revert #4847 however that revert left behind the addition of the `--local` argument when installing gems from a local path. So from what I can tell, the original bug reported in #4955 remains. If I try to install a gem locally that has remote dependencies, the converge fails.
This essentially completes the revert and allows remote dependencies to to be installed.
=> Revert --local filter for gems installed from  paths

lib/chef/provider/apt_update.rb
The `apt_update` resource generates a file at `/etc/apt/apt.conf.d/15update-stamp` that conflicts with the system-provided `update-notifier-common` package on Ubuntu. Because the file dropped by Chef differs from the system-provided file, `apt-get` requires user interaction to install `update-notifier-common`. This creates a problem if you're trying to install `update-notifier-common` via a Chef `package` resource... Adding a trailing newline makes the file identical to the one provided by `update-notifier-common`, and allows the package install to proceed without interaction.
A debatable shortcoming of my fix is that if someone installs `update-notifier-common` and then later removes it, `/etc/apt/apt.conf.d/15update-stamp` will be removed. However, within the `apt_update` update …
=> Add trailing newline to generated 15update-stamp

spec/functional/knife/cookbook_delete_spec.rb
This removes a little extra STDOUT spew from the tests:
```
Chef::Knife::CookbookDelete
when the cookbook doesn't exist
logs an error and exits
when there is only one version of a cookbook
asks for confirmation, then deletes the cookbook
asks for confirmation before purging
when there are several versions of a cookbook
Deleted cookbook[obsolete-cookbook][1.0.0]
Deleted cookbook[obsolete-cookbook][1.1.0]
Deleted cookbook[obsolete-cookbook][1.2.0]
deletes all versions of a cookbook when given the '-a' flag
Deleted cookbook[obsolete-cookbook][1.0.0]
asks which version to delete and deletes that when not given the -a flag
Deleted cookbook[obsolete-cookbook][1.0.0]
Deleted cookbook[obsolete-cookbook][1.1.0]
Deleted cookbook[obsolete-cookbook][1.2.0]
deletes all versions of the cookbook when …
```
=> Don't let knife cookbook delete tests print to stdout

lib/chef/provider/apt_repository.rb
We have multiple apt repositories that have key names similar enough so the cookbook treats them as the same when performs `remote_file` cache (due to regex below).
Related: https://github.com/chef-cookbooks/apt/pull/207
This PR makes sure that `remote_file` caches remote key with a unique name and thus avoids updating resources on every chef run.
=> Normalize full key name to avoid resource update on identical key names

acceptance/fips/.kitchen.yml
This "turns off" the FIPS acceptance tests on windows that are breaking with the latest winrm bug fix. A bit of history here:
* Early this year we turned off the windows fips acceptance tests because they were failing and it was not obvioous why and we needed to get the pipeline green for the other 99.9% of users.
* Early July of this year we started using winrm v2 for acceptance tests. This had a bug that would swallow some exit codes.
* Mid July - turned acceptance/fips/windows tests back on and everything seemed fine
* Last week fixed winrmv2 bug and now the error in fips is surfacing
We do need to root cause fips but not hold everything else up.
=> turn off fips unit-functional tests on windows acceptance

lib/chef/mixin/powershell_out.rb, spec/functional/mixin/powershell_out_spec.rb, spec/unit/mixin/powershell_out_spec.rb
Reverts chef/chef#5381
I had to revert this because its causing the chocolatey functional tests to fail on Jenkins 2008R2 testers. 
The above failure is partly the fault of something in the chocolatey tests which I will get to in a bit. The key problem with this PR is that it bubbles up exceptions from stderr in `powershell_out` but the bubbling of exceptions should only happen automatically from `powershell_out!`. Any error conditions are meant to be  suppressed in `powershell_out` so that the caller can examine them and act as it sees fit.
So it ends up that on 2008R2, the chocolatey installer fails and that failure causes `powershell_out` to raise an exception where it previously suppressed it. This was not a problem since chocolatey is already installed. We do need to investigate that …
=> Revert "Handling double quotes in powershell_out"

lib/chef/provider/user.rb, lib/chef/provider/user/dscl.rb, lib/chef/provider/user/linux.rb, lib/chef/provider/user/pw.rb, lib/chef/provider/user/useradd.rb
on freebsd and mac we're now telling people to use `manage_home` instead
of `supports[:manage_home]` but it doesn't actually work.  fixes that so
that it works now.
=> Fix manage_home provider inconsistency for Mac and FreeBSD User providers

lib/chef/application/exit_code.rb, lib/chef/exceptions.rb, spec/unit/application/exit_code_spec.rb
This adds support for the RFC062 exit code 213 "Chef has exited during a client upgrade"
One example implementation of a Chef Client upgrade is here: https://github.com/chef-cookbooks/omnibus_updater/pull/130
=> Adding support for rfc 62 exit code 213

Gemfile, Gemfile.lock
and its now officially deprecated in its README:
https://github.com/thommay/chef-rewind
=> chef-rewind:  remove from integration gems (it was not in the testing matrix) as it is deprecated

lib/chef/dsl/declare_resource.rb, spec/integration/recipes/accumulator_spec.rb
helps with scoping issues, best practice would be to always use
the |new_resource| argument to the block when using edit_resource
inside of resources
addresses part of https://github.com/chef/chef/issues/5438
=> Core: pass new_resource to edit_resource through instance_exec

lib/chef/resource.rb, spec/integration/recipes/accumulator_spec.rb
effectively creates a resource which sends itself a delayed notification
useful to create a resource which runs exactly once at the end of a run:
```ruby
with_run_context :root do
find_resource(:execute, "/bin/true") do
action :nothing
delayed_action :run
end
end
```
avoids using a log resource to force a resource to update and force a
delayed notification which avoids the extra output from the log
resource, and avoids the resource updated count always being updated.
=> Core: add delayed_action to the Chef::Resource API

lib/chef/provider/user.rb, spec/unit/provider/user_spec.rb
This fixes the `Chef::Provider::User#compare_user` method for comparing the home folder by ignoring trailing slashes.
Fixes #5444 
required
=> User Provider:  Fix home folder comparison

lib/chef/chef_class.rb
According to the documentation at https://docs.chef.io/dsl_handler.html you can use `Chef.event_handler` in a recipe. However, when you do so and run chefspec you get the following error:
```
Failure/Error: expect { chef_run }.not_to raise_error
expected no Exception, got #<NameError: uninitialized constant Chef::EventDispatch::DSL
Did you mean?  Chef::DSL> with backtrace:
```
We worked around the problem by requiring 'chef/event_dispatch/dsl' in our spec file but I believe the true fix is to require the class where it is being used. With this fix in place we can remove our workaround.
required
Signed-off-by: Thiago Oliveira <thiagoo@yahoo-inc.com>
=> require the event_dispatch dsl since it's used in chef_class

lib/chef/http.rb
Depending on how you configure your Chef client, it's possible that a
later retry would have an authentication timestamp header
(`X-OPS-TIMESTAMP`) that was more than 900 seconds old. Since the Chef
server treats timestamps older than this threshold as unauthorized
requests, you would potentially get seemingly spurious "401
Unauthorized" responses from the server.
A solution is to generate the headers on each retry so that we have a
new authentication timestamp for each retried request.
I'm not sure if this change of behavior requires additional thought. Hoping someone with more context can weigh in here.
- [Intermittent "401 Unauthorized" failures from Chef server using Chef client](https://github.com/chef/chef-server/issues/968)
=> Rebuild HTTP headers on each retried request

omnibus/Gemfile.lock
Bump omnibus Gemfile.lock deps to pull in openssl from `omnibus-software`.
Relates to internal issue COOL-595.
/cc @chef/client-core
=> Update omnibus Gemfile.lock

chef-config/lib/chef-config/config.rb, chef-config/lib/chef-config/exceptions.rb, chef-config/spec/unit/config_spec.rb, lib/chef/application.rb, lib/chef/knife.rb, spec/unit/knife_spec.rb
The `--config-option` CLI option allows setting any `Chef::Config`
setting on the command line, which allows applications to be used
without a configuration file even if a desired config option does not
have a corresponding CLI option. This CLI option was present in the help
output for knife but was not actually implemented. Moving the behavior
into chef-config allows us to use it for both `chef-client` and `knife`.
Internal issue for a Chef Software customer.
Signed-off-by: Daniel DeLeo <dan@chef.io>
=> Implement `--config-option` CLI opt for knife

lib/chef/dsl/declare_resource.rb, lib/chef/run_context.rb
introduce run_context.root_run_context that avoids global state
=> remove dependency on Chef.run_context global state

lib/chef/provider/cron.rb
#5127, which I admittedly advocated for via #4900, implemented the ability to set certain environment variables (`MAILTO`, `PATH`, `SHELL`, `HOME`) to an empty string. A side effect of that fix is that if a `cron` resource uses one of those variables (empty or not), the crontab file gets rewritten with every chef-client run. This is because the desired state of the resource uses unquoted strings for those variables, while the current state of the resource uses quoted strings.
This PR fixes the problem by stripping leading and trailing double quotes from those four variables when parsing the current crontab. There are definitely other ways this could be fixed (for example, by forcing all environment variables to be quoted) - I only chose this approach because it seems like the least …
=> Cron Provider: Eliminate crontab rewrite that happens with every chef-client run

lib/chef/resource/scm.rb
should always suppress the password output by default since typically nobody wants to see that in their logs when we crash.
=> convert svn_password to property + make sensitive

spec/unit/node_spec.rb
Tests for the issue that led up to
https://github.com/chef/chef/issues/5447
The Hash tests actually pass against 12.13.37 so it appears that we
only broke the ImmutableArray objects in 12.0.  This both explains
why we didn't have any existing tests that caught it, and why it went
uncaught for so long.  It also adds some ammunition to the argument
that fixing this in 12.14.x was not a major breaking change to users
that had been relying on the buggy 12.0 behavior, since Hash behavior
has been correct all along.
=> Attributes: add tests for regression in 12.0 fixed recently

lib/chef/resource/yum_repository.rb
We're using the legacy name instead of the new name here. The result is the same, but we should clean this up.
=> Use property vs. attribute in yum_repository

spec/unit/resource/apt_repository_spec.rb
This was copied and the name of the resource we're testing wasn't updated.
=> Fix a typo in the apt_repository spec

lib/chef/provider/group/suse.rb, spec/functional/resource/group_spec.rb
Fixes suse spec test. Using `all?` will return `false` when the array is empty, thus causing the resource to raise an error incorrectly.
COOL-597
=> Use `all?` instead of `any?` to check for SUSE users

lib/chef/node.rb, lib/chef/node/attribute.rb, lib/chef/node/attribute_collections.rb, lib/chef/node/common_api.rb, lib/chef/node/immutable_collections.rb, lib/chef/node/mixin/deep_merge_cache.rb, lib/chef/node/mixin/immutablize_array.rb, lib/chef/node/mixin/immutablize_hash.rb, lib/chef/node/mixin/path_tracking.rb, lib/chef/node/mixin/state_tracking.rb, spec/unit/node/vivid_mash_spec.rb, spec/unit/node_spec.rb
Fixes some long-standing horribleness introduced in Chef 12.0 with the top_level_breadcrumb state and confusion in the deep merge cache when that global state is whacked in the middle of an operation.
This modifies some APIs.  I would argue nobody should ever have been using them, they were undocumented, should not have been considered covered by SemVer.  Any affected consumer should modify their code.  Summary of changes:
- added the :__path accessor (can't use :path because of method_missing)
- removed the :root accessor and changed it to __root for consistency
- dropped the :top_level_breadcrumb accessor in favor of the :__path array (this is entirely an implementation detail of the deep merge cache, and its an API that is broken by design)
- changed the initializer of VividMash and …
=> Add Chef::Node __path tracking, change root to __root, drop top_level_breadcrumb hack, fix long-standing Chef 12.0 deep merge cache bugs

lib/chef/knife/core/generic_presenter.rb, lib/chef/knife/node_show.rb, lib/chef/knife/osc_user_show.rb, spec/integration/knife/environment_show_spec.rb, spec/integration/knife/node_environment_set_spec.rb, spec/support/shared/integration/knife_support.rb, spec/unit/knife/core/ui_spec.rb
For the commands that allow you to filter which attributes it shows you
using the `--attribute` flag, add the `--field-separator` flag to allow
the user to customize which character(s) they want to use to delineate the
attribute hierarchy.
``` shell
knife node show NODE -S: -a "packages:Chef Client v12.12.15"
```
- Internal ticket COOL-599
=> Add the `--field-separator` flag to knife show commands

lib/chef/provider/user/solaris.rb, spec/unit/provider/user/solaris_spec.rb
On Solaris, the 'shadow' database does not exist within `getent`, so the
checking for the username there won't return accurate results. As the
Solaris provider assumes user management via /etc/shadow, we can very
easily parse the contents of the file directly
``` shell
tduffield@chef-solaris-11-i86pc:~$ getent shadow tduffield
Unknown database: shadow
usage: getent database [ key ... ]
```
- Internal ticket COOL-413
=> Properly check lock status of user on solaris2

lib/chef/property.rb, spec/integration/recipes/resource_action_spec.rb
@tas50 here's a slightly improved error message for this case.
=> Core: improve readability of property-resource namespace collision exception message

lib/chef/rest.rb
The rest.rb [**add the deprecation warnings**](https://github.com/chef/chef/commit/0ef0ab07531ae78cb4052242037227b0fb5365dc), but the method log_deprecation is undefined, it need to require "chef/chef_class" first.
If user follow [**official document**](https://docs.chef.io/auth.html#ruby) to request Chef server API in ruby, there is exception showing ...
```
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/rest.rb:62:in `initialize': undefined method `log_deprecation' for Chef:Class (NoMethodError)
```
=> include chef/chef_class for method log_deprecation

lib/chef/data_collector.rb, lib/chef/data_collector/messages.rb, spec/unit/data_collector/messages_spec.rb
By adding deprecation warnings to Data Collector, receivers of
Data Collector messages can easily identify nodes that would need
attention to their versions/cookbooks before a major version Chef
upgrade would be successful.
=> Add deprecations to Data Collector competion message

lib/chef/chef_fs/file_system/chef_server/cookbook_file.rb
Fixes https://github.com/chef/chef/issues/5363
Signed-off-by: aliasgar16 aliasgar.batterywala@msystechnologies.com
=> Fixed knife download cookbooks issue which used to corrupt the certificate files each time the command was fired.

omnibus/resources/chef/ips/symlinks.erb
Create symlinks.erb template resource for chef IPS package so it will install the symbolic links for the commands. These are the links added by post install scripts for other package types. But since IPS does not use post install scripts they need to be added here.
Resolves: https://github.com/chef/chef/issues/5458 after successful merge for this PR and https://github.com/chef/omnibus/pull/728 
- [y] New functionality includes tests
- [y] All tests pass
Create symlinks.erb template to exists in local project directory structure
to enable IPS package to create required symlinks for installed commands
Signed-off-by: Jaymala Sinha jsinha@chef.io
=> [BEN-123] Fix IPS package must create symlinks to package commands

lib/chef/provider/user/dscl.rb
new_resource.gid.to_s will be empty if a recipe calls the user resource without gid and changes the home property. Will result in an exception and if chef is run by root, the home dir will end up being owned by root from the mv.
=> Add a default GID for user creation on MacOS

chef-config/lib/chef-config/config.rb, chef-config/spec/unit/config_spec.rb, lib/chef/data_collector.rb, spec/unit/data_collector_spec.rb
Third-party data collector implementations are supported and may not
require a token for authentication. Therefore we must allow the case
where the token is nil in Chef Solo mode. To reduce the chance that the
data collector is accidentally enabled, only set the data collector URL
to a default value in Chef Client mode.
Acceptance is failing in the pipeline because it tests this exact case
Signed-off-by: Daniel DeLeo <dan@chef.io>
=> Enable data collector w/o token for solo, but require explicit URL

HISTORY.md, tasks/changelog.rb
Configure the changelog generator to better fit our current pattern of
changelogs. By utilizing the HISTORY.md file, we can generate a combined
changelog of the latest version from HISTORY.md to now. Then, when we
cut a release we can simply move our current changelog into
HISTORY.md (using the appropriate rake task) and start the process over
again.
This might even be a first step to having the Chef Versioner generate
the changelog automatically for us each time it bumps the version, and
then we just need to groom it as we go along.
Some personal pain for those who have to artisanally craft the current CHANGELOG out of yack hair, toothpicks, bubble gum, and tears.
=> Update changelog generator to better fill our pattern

lib/chef/provider/yum_repository.rb
This fixes #5459: Purge the yum cache and metadata before deleting the yum repository config.
Fixes #5459. See also https://github.com/chef-cookbooks/yum/pull/166.
=> Fixed 5459 - Purge yum cache before deleting repo config

.travis.yml, kitchen-tests/.kitchen.travis.yml
Use the latest fedora to avoid having to bump things every X months
We need to make the cache afterwards. I ran into this same issue in the cron cookbook and I’ve updated the dnf_compat recipe in yum to do the same.
=> Test on the latest fedora and fix yum failures in testing

lib/chef/resource/apt_update.rb, spec/unit/resource/apt_update_spec.rb
Prevent apt_update failures on non-Linux platforms
We 1/2 wired up the noop functionality, but specifying that we only provided the resource on Linux caused that code to never run.
This prevents this sort of error on non-Linux platforms:
```
Cannot find a resource for apt_update on windows version 6.3.9600
```
=> Prevent apt_update failures on non-Linux platforms

lib/chef/resource/launchd.rb
The key `LimitLoadToSessionType` is actually an array and not a string. This causes chef to fail or create an incorrect launchd.
=> Mac: Ensure that launchd limit_load_to_session_type is properly handled

lib/chef/provider.rb
sensitive is the property of the resource, not the provider.
Fixes exceptions using converge_if_changed
=> Core: Ensure that the sensitive property is correctly accessed

README.md, tasks/changelog.rb
Add gem release badge to the readme / changelog header
When we update our changelog it’s a bit confusing since multiple days go by before we ship the new release. Adding a header and a readme gem release badge should help clear up what our current release is.
=> Add gem release badge to the readme / changelog header

chef-config/lib/chef-config/config.rb, chef-config/spec/unit/config_spec.rb
This change causes the platform_specific_path function to root its's path in the drive `__FILE__` is found in. This is arguably more accurate than $env:SystemDrive since in some security contexts a chef-client installation on a drive other than the OS is preferred. 
fixes #5477
=> Windows: search for config on same drive as executable location

ci/version_bump.sh
The Github Changelog Generator threw an error about invalid
encoding. This never happened locally, and indications are that its
because of this environment variable.
=> Add UTF-8 environment var to version bumper

CHANGELOG.md, HISTORY.md, RELEASE_NOTES.md
We forgot to mention a really cool contribution that made it into the last release! This must be corrected!
=> Update 12.16 release notes with package locking

lib/chef/node/mixin/state_tracking.rb, spec/unit/node/immutable_collections_spec.rb, spec/unit/node/vivid_mash_spec.rb
=> fix ImmutableArray slices

lib/chef/node/attribute.rb
Removes debug write introduced in previous commit: e57e29b96b75ff7fc04abb7f9db73920b2a5894a
Removes erroneous output during compilation phase, eg:
```
Compiling Cookbooks...
python
platform
python
platform
platform
```
Obvious fix.
=> Remove debug write

spec/functional/resource/msu_package_spec.rb
Sets the msu_package functional tests to only run on appveyor.
Unblocks chef-test in Jenkins where these tests fail
Choosing an MSU that works on a system but shouldn't be installed is hard / impossible.
These tests work on appveyor but break the build in Jenkins. For now, let them just run on
appveyor.
=> Only run msu_package functional tests on Appveyor

MAINTAINERS.md
This PR removes the Dev Tools component. All responsibilities of Dev
Tools would thus be handled by the Core Maintainers.  As part of this
change, I propose that
Steven Danna, and
Joshua Timberman
be added as Core Maintainers. All other members of Dev Tools are already
core maintainers. This move simplifies the MAINTAINER list and makes it
easier to find reviewers for the components previously handled by Dev
Tools.
To add the new core maintainers this PR requires approval from a
majority of @chef/client-core and @thommay.
No procedure is specified to remove a component. I recommend that we
require a super-majority of 80% (4/5ths) of existing Dev
Tools (@chef/client-dev-tools) maintainers to approve with no vetos.
Signed-off-by: Steven Danna <steve@chef.io>
=> Remove the Dev Tools component

Rakefile, tasks/announce.rb, tasks/templates/prerelease.md.erb, tasks/templates/release.md.erb
To ensure consistency, and to let users get the information they
want/need at a glance, we're introducing release announcement
templates. The Chef release team will use these tasks to generate the
release announcements before posting them to Discourse.
=> Add rake task for generator release annoucnements

lib/chef/data_collector.rb
After changing Data Collector to use Chef::ServerAPI or
Chef::HTTP::SimpleJSON, the message output in the debug log is a ruby
inspect of the message hash rather than the JSON output that will be
sent to the data collector. Having this as JSON makes it easier to debug
and reproduce Data Collector-related issues.
Signed-off-by: Adam Leff <adam@leff.co>
=> Data Collector debug log should output JSON

lib/chef/data_collector.rb, spec/unit/data_collector_spec.rb
In certain cases when using custom resources, we have seen evidence
of resource_updated and resource_failed events getting fired before
the DataCollector instance has a valid resource report created to
track such updates/failures.
This change ensures a resource report exists before attempting to
modify it, regardless of what order these events may fire.
=> Ensure Data Collector resource report exists before updating

lib/chef/provider/package/msu.rb, spec/functional/resource/msu_package_spec.rb, spec/unit/provider/package/msu_spec.rb
Functional specs for msu_package failed pipeline with error:
```
1) Chef::Resource::MsuPackage installing package installs the package successfully
Got 0 failures and 2 other errors:
1.1) Failure/Error: subject.run_action(:install)
Chef::Exceptions::Package:
msu_package[test msu package] (dynamically defined) had an error: Chef::Exceptions::Package: Corrupt MSU package: MSU package doesn't contain any xml file
1.2) Failure/Error: pkg_to_remove.run_action(:remove)
Chef::Exceptions::Package:
msu_package[Package_for_KB2959977] (dynamically defined) had an error: Chef::Exceptions::Package: Corrupt MSU package: MSU package doesn't contain any xml file
2) Chef::Resource::MsuPackage removing a package removes an installed package
Failure/Error: subject.run_action(:install) …
```
=> Use the full path to expand.exe for msu_package, raise exception if command fails

lib/chef/knife/core/bootstrap_context.rb, spec/unit/knife/core/bootstrap_context_spec.rb
Passing config_log_level and config_log_location from config.rb
https://github.com/chef/chef/issues/1452
=> Knife Bootstrap: Passing config_log_level and config_log_location from config.rb

Dockerfile
This Dockerfile will allow individuals, who wish to, to build Docker
images containing the latest Chef Client. Specifically, it can be used
inside testing frameworks like kitchen-dokken.
This Dockerfile will be used by internal Chef release engineering to
automatically post Docker images to the Docker Hub as part of our
standard artifact promotion pipeline.
=> Add Dockerfile to root

lib/chef/data_collector/messages.rb, lib/chef/data_collector/messages/helpers.rb
Data Collector uses the json gem to read/write the metadata file
in the file cache. Let's change that to use Chef::JSONCompat instead.
=> Update Data Collector to use Chef::JSONCompat

lib/chef/provider/package/cab.rb
Support for running cab_package on non-English system locales
When using cab_package on Windows with non-English system locales, such as Russian, chef-client throws up an error:
> undefined method `[]' for nil:NilClass
The reason is that dism.exe output is in russian language and therefore cannot be parsed.
This PR ensures that output of dism.exe will always be in English.
=> Support for running cab_package on non-English system locales

distro/common/markdown/man1/knife-configure.mkd, lib/chef/knife/configure.rb, spec/unit/knife/configure_spec.rb
This modifies the example given for `chef_server_url` in `knife configure`. A proper `chef_server_url` in `knife.rb` must contain a path to an organization.
=> Modify `knife configure` example `chef_server_url`

MAINTAINERS.md, MAINTAINERS.toml
Besides the platfrom ones, which require some touch up to the
maintenance policy.
Per the developers' meeting last week, the subsections are not really working, so let's get rid of them.
cc @adamhjk @chef/maintainers
=> Remove Maintainer subsections

RELEASE_NOTES.md, lib/chef/provider/mount.rb, lib/chef/resource/mount.rb, spec/unit/provider/mount_spec.rb, spec/unit/resource/mount_spec.rb
Allows the usage of `action :unmount` to `umount` a mount point
Closes https://github.com/chef/chef/issues/5595
Signed-off-by: Grant Ridder <shortdudey123@gmail.com>
=> Alias unmount to umount for mount resource

kitchen-tests/.kitchen.travis.yml
Since we use kitchen-dokken, we are downloading the chef Docker image. To avoid downloading the Chef binary from packages.chef.io as well, use the chef/chef:current image available on the Docker Hub instead. 
* Excess bandwidth spent downloading duplicate Chef packages
=> Use chef/chef image instead of downloading from packages.chef.io

lib/chef/provider/mount/mount.rb, spec/unit/provider/mount/mount_spec.rb
linux mount provider - skip device detection for zfs
#5597
=> linux mount provider - skip device detection for zfs

lib/chef/provider/ohai.rb, lib/chef/resource/ohai.rb, spec/unit/resource/ohai_spec.rb
If #5606 is approved, any resource that creates a property that is an
already-existing Ruby method on a Chef::Resource object will throw a
deprecation warning. The ohai resource currently creates a `name`
property which conflicts with the `name` property created in the base
Chef::Resource class.
This change updates the ohai resource and provider to the new style of
defining resources and stops overwriting the `name` method.
Signed-off-by: Adam Leff <adam@leff.co>
=> Update ohai resource to new style, stop overwriting name property

lib/chef/provider/package/yum.rb
this is a "nope, aint got time to test this one" PR.
this affects a code path that is only for localinstalls and doesn't have
any existing tests.
i've already exceeded my 5 minute timebox for fixing the problem.
i'm more likely to rewrite the yum provider from scratch and shitcan the
unit tests in their entirety than to reuse any work that i do here so
any time spent on carefully testing this is likely to end up wasted.
=> fix yum regexp similarly to rpm regexp in #3985

tasks/changelog.rb
Use the badge in the changelog so the current stable version is shown
regardless of when the CHANGELOG is viewed.
=> Use badge in CHANGELOG

lib/chef/provider/link.rb, spec/functional/resource/link_spec.rb
When a link resource needs to change its destination, there was a bug in
the logic flow that would cause the access controls on the resulting
symlink to revert to the default access controls. This commit closes
that hole by re-evaluating the current access controls after creating
the new symlink.
* COOL-614 (Internal Ticket)
=> Core: Fix bug where Access Controls on existing symlink resources would be ignored on first chef-client run

lib/chef/provider/package/chocolatey.rb, spec/unit/provider/package/chocolatey_spec.rb
Changes `choco install -version` to `choco install --version`
Resolves issue where would give error `Cannot bundle unregistered option '-e'`
Fixes issue #5256
=> change choco -version to choco --version

spec/unit/provider/subversion_spec.rb
So it doesn't alter generated subversion commands (and fail the spec)
=> Unset http[s]_proxy in the subversion spec

lib/chef/platform/rebooter.rb, spec/functional/rebooter_spec.rb
Use 'C:/Windows/System32/shutdown.exe...' instead of 'shutdown...' when rebooting.
https://github.com/chef/chef/issues/5594
- [N/A] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
=> Ensures correct version of shutdown is called when using the reboot resource on Windows

lib/chef/chef_fs/file_system/repository/chef_repository_file_system_root_dir.rb, lib/chef/chef_fs/file_system/repository/nodes_dir.rb, spec/integration/solo/solo_spec.rb
This commit ensures that the `nodes` dir and the node files within
it are created with the correct permissions by chef-solo.
Internal ticket
cc @chef/client-core @chef/client-windows
=> Core: Ensure chef-solo creates node files w/ correct permissions

lib/chef/provider_resolver.rb
no, we should not do this only in why-run mode, add more yapping to
make that clear.
=> fix provider_resolver comment to remove FIXME

distro/powershell/chef/chef.psm1
The PowerShell module functions, Load-Win32Bindings & Run-ExecutableAndWait, were modified to utilize an anonymous pipe for writing stdout and stderr of the spawned child process, which provides the parent PowerShell process the ability to read from the pipe and then pass through the output in the normal way.
This commit fixes [#4045](https://github.com/chef/chef/issues/4045) where the output from any of the chef executables wrapped by the module functions would not allow redirection or variable capture.
=> PowerShell module output pass through

lib/chef/deprecated.rb, lib/chef/platform/provider_mapping.rb, spec/functional/resource/dsc_script_spec.rb, spec/integration/recipes/recipe_dsl_spec.rb, spec/support/lib/chef/provider/snakeoil.rb, spec/support/lib/chef/resource/cat.rb, spec/support/lib/chef/resource/one_two_three_four.rb, spec/support/lib/chef/resource/openldap_includer.rb, spec/support/lib/chef/resource/with_state.rb, spec/support/lib/chef/resource/zen_master.rb, spec/unit/lwrp_spec.rb, spec/unit/platform_spec.rb, spec/unit/provider_resolver_spec.rb, spec/unit/resource/remote_file_spec.rb, spec/unit/resource_spec.rb, spec/unit/runner_spec.rb
These should have been deprecated formally in 12.5.1 after the
Dynamic Provider-Resolver'ing of the internal chef resources
was completed.
=> Properly deprecate old Chef::Platform methods

lib/chef/data_collector.rb, spec/unit/data_collector_spec.rb
In the Data Collector, when detecting unprocessed resources, a Set
was built up using the resource object itself as the Set element.
Internally, Set adds this to a Hash.
We allow users to create custom resources that could contain a property
named "hash" which in turn wires up a `#hash` instance method on the
Resource. Ruby expects object's `#hash` method to return a Fixnum that
it uses internally. So if a resource had a "hash" property that returned
a String, bad things happened.
With this change, we make our own Hash and use the resource's object ID
in the key so we don't have to worry about the resource's `#hash` method
getting called and throwing an exception. I will send up a separate
change that warns users when they choose a property name that is already
an existing method name. …
=> Use object ID when detected unprocessed Resources

README.md, Rakefile, ci/version_bump.sh, tasks/templates/prerelease.md.erb, tasks/templates/release.md.erb
* Update the release announcement templates to remove kitchen language.
* Make sure that the default version in the Dockerfile is kept up to date with the latest stable release.
* Update the download URL for chef in the README.
=> Update Release Announcements; Keep Dockerfile up-to-date

lib/chef/dsl/platform_introspection.rb
Ensures `node.docker?` return boolean instead of truthy
N/A
Trivial change to ensure node.docker? returns either true or false.
=> Ensure node.docker? returns boolean

ci/version_bump.sh
We don't want to fail the version bump if the changelog update fails.
=> Dont fail the version bump if changelog fails

.travis.yml
Rbx was failing as it wasn't a valid rbenv name. Ruby 2.4 comes out this month so we should add it to the test matrix.
=> Swap rbx testing in Travis for Ruby head

lib/chef/data_collector/messages/helpers.rb, spec/unit/data_collector/messages/helpers_spec.rb
The regex used to pluck the Chef Server Organization from the
chef_server_url config value did not permit hyphens in org names
even though they are allowed by Chef Server. This caused org names
to get incorrectly truncated when sending the payload to Data
Collector servers.
Re: Chef bug IPO-500
Signed-off-by: Adam Leff <adam@leff.co>
=> Fix Data Collector organization parsing regex

lib/chef/chef_fs/file_system/chef_server/rest_list_entry.rb
Previously, this code determined if an object existed by doing the
following:
parent.children.any? { |child| child.api_child_name == api_child_name }
For organizations and object types with a small number of total objects,
this wasn't problematic; however, it has very bad worst-case behavior.
For example, if a user was attempting to restore an organization with
30k client records to an empty organization, each client upload would do
the following:
1. Run GET /clients
2. Iterate the list returned in (1) normalizing the clients names along
the way.
3. Upload the client via POST when exist? returned false.
When the clients don't exist, this means step (2) will always iterate
over every member returned in step (1).  By the time you get into the
1000s of clients, this iteration dominates the …
=> [cheffs] Don't iterate parent object on exist? call

.bundle/config, .travis.yml, Gemfile, Gemfile.lock
=> remove chef-provisioning-aws from travis

omnibus/resources/chef/msi/source.wxs.erb
This will allow the MSI created task to be managed by the chef-client cookbook. See https://github.com/chef-cookbooks/chef-client/blob/master/recipes/task.rb#L41
cc @btm 
=> Use the same task name used by the chef-client cookbook so that the task can be managed by its task recipie

RELEASE_NOTES.md
I added a section for the deprecations. Let me know if that format makes
sense. This process was defined in RFC-082
=> Wipe the 12.17 release notes and start 12.18 release notes

RELEASE_NOTES.md, lib/chef/resource_reporter.rb, spec/unit/resource_reporter_spec.rb
Before this commit we were sending sensitive resource information to
Reporting and therefor you were able to see the sensitive data on the
Run History in the Chef Manage Console.
This commit is fixing this problem and now it is transforming any
sensitive resource to display the word `*sensitive*` instead of the
actual data. As we are inserting this values directly to the data base,
it means that this change will cascade all the way to the front-end.
Catch: Old data that was already reported and is displaying sensitive
data will contineu to be displayed. Apologize.
COOL-642/ZD 12936 - Chef Manage Run History compromises sensitive data
=> Report a dummy resource if sensitive is enabled

lib/chef/chef_fs/file_system/repository/chef_repository_file_system_root_dir.rb, lib/chef/chef_fs/file_system/repository/nodes_dir.rb
`Chef::ReservedNames::Win32::Security::SID.current_user` throws an error when `chef-solo` is being run as a `SYSTEM` user:
```
Chef encountered an error attempting to load the node data for "WIN-00P0BGAA4IV"
Unknown Server Error:
---------------------
The server had a fatal error attempting to load the node data.
Server Response:
----------------
Exception raised! #<Chef::Exceptions::Win32APIError: No mapping between account names and security IDs was done.
---- Begin Win32 API output ----
System Error Code: 1332
System Error Message: No mapping between account names and security IDs was done.
---- End Win32 API output ----
> …
```
=> Fix error thrown by solo when run on Windows as SYSTEM

RELEASE_NOTES.md
Pretty straight forward. This needs to go in prior to our release
=> Add run_command deprecation to the release notes

spec/functional/resource/user/useradd_spec.rb
usermod -U for user with blank password on Rhel6 zlinux systems
exits with error message.  Updating the test for this behavior
@chef/engineering-services 
=> Fix failing useradd test for rhel6 on s390x platform

lib/chef/provider/support/yum_repo.erb, lib/chef/resource/yum_repository.rb
Port two fixes that were made the yum cookbook yum_repository provider.
https://github.com/chef-cookbooks/yum/pull/165
https://github.com/chef-cookbooks/yum/pull/162
=> yum_repository: Allow baseurl to be an array & allow fastestmirror_enabled false

lib/chef/node/attribute.rb, spec/unit/node_spec.rb
closes #5556
corrects behavior to 12.11.x behavior which was lost in the refactor
may address #5715
=> Core: fix node attribute "unless" API methods

.travis.yml
since its green, we should probably keep it green.
=> enforce 2.4.0 failures

.bundle/config, .travis.yml, Gemfile.lock, chef.gemspec
Bump net-ssh to 4.0.0 and add dependencies for ed25519 support
https://github.com/chef/chef/issues/5461
=> Bump net-ssh to v4, add dependencies for ed25519

lib/chef/policy_builder/policyfile.rb
/cc @coderanger @danielsdeleo
We have been looking for an easy way to get this value into our error
reporting application and it surprised me that it isn't already
captured. If there's a better way to do this totally open for thoughts!
=> Add the policyfile revision_id as an automatic attribute.

lib/chef/provider/package/aix.rb, spec/unit/provider/package/aix_spec.rb
This fixes #4819 with the fix suggested by the original poster.
=> Don't blindly check source on candidate_version calls.

.gitignore, habitat/default.toml, habitat/hooks/run, habitat/plan.sh
This is a simple initial habitat plan. It creates a chef-client service,
which uses chef-solo to run cookbooks that are located in the default
cache location.
To build it yourself:
* Install habitat
* `hab studio build`
You'll wind up with a habitat artifact in `results`.
Signed-off-by: Adam Jacob <adam@chef.io>
This adds a habitat plan for the chef client, enabling chef to be run as a habitat service.
None.
=> Initial habitat plan

lib/chef/knife/ssh.rb, spec/unit/knife/ssh_spec.rb
Net-ssh 4.0 is incompatible with configration_for.
https://github.com/chef/chef/pull/5687#issuecomment-272775751
- add true to 2nd arg. It has not changed the behavior. 
- #5461
=> pass true as 2nd args for Net::SSH.configuration_for by default.

Gemfile.lock, lib/chef/chef_class.rb, lib/chef/deprecated.rb, lib/chef/property.rb, lib/chef/provider/launchd.rb, lib/chef/resource/apt_repository.rb, lib/chef/resource/launchd.rb, lib/chef/resource/yum_repository.rb, spec/unit/provider/launchd_spec.rb
When creating a resource, a user can create a property that is the same
name as an already-existing Ruby method, such as `#hash`. In the case of
the `#hash` method, this can cause issues when attempting to adding
resources to other data structures, such as Arrays or Hashes. In other
examples, this could cause unexpected behavior that is incredibly
difficult to troubleshoot.
This change adds a deprecation warning in the case where a user adds
a property to a resource that the resource instance already responds to.
If y'all are OK with this approach, I'll be happy to write up the
deprecation doc for this for docs.chef.io.
In addition, three resources were found to be redefining methods in this manner: `apt_repository`, `yum_repository`, and `launchd`.  `apt_repository` and `yum_repository` …
=> Deprecate creating properties whose names are already methods

lib/chef/provider/directory.rb, lib/chef/provider/file.rb, spec/support/shared/unit/provider/file.rb, spec/unit/provider/directory_spec.rb
The `File` provider's `action_create` method would modify the `new_resource` object during a
`why-run`. This was problematic when a `File` resource was configured with a `notifies :before`
because resources with `before` timers have their actions executed twice. [Once](https://github.com/chef/chef/blob/a2e1d1d4edb74a968b416517fdbdf35740686467/lib/chef/runner.rb#L54-L57) in `why-run` mode to
see if the other resources need to be notified, and then executed [once again](https://github.com/chef/chef/blob/a2e1d1d4edb74a968b416517fdbdf35740686467/lib/chef/runner.rb#L68-L69) after the `before`
notifications are resolved. This behavior would result in existing File resources not getting their
ownership and permissions updated properly during a converge.
Internal ticket
=> Do not modify File's new_resource during why-run

acceptance/Gemfile, acceptance/Gemfile.lock
The nio4r gem, which is a dep of celluloid, was having
some install problems. To avoid this we're just pinning it.
* COOL-661 (Internal Ticket)
=> Pin nio4r gem to avoid install error

lib/chef/exceptions.rb, lib/chef/provider/dsc_resource.rb, lib/chef/resource/dsc_resource.rb, spec/unit/provider/dsc_resource_spec.rb, spec/unit/resource/dsc_resource_spec.rb
Added `module_version` attribute support for `dsc_resource` resource to allow users to specify which version of a module (out of the multiple versions of a module installed) to use.
=> Added module_version attribute for dsc_resource.

omnibus/config/projects/chef.rb, omnibus/omnibus.rb
Use the new `fips_mode` variable added in https://github.com/chef/omnibus/commit/7fc5529b89327c7b1df457f3ac1f60cd2a9d8f64 to manage FIPS compilation. 
cc @tyler-ball 
Internal ticket COOL-663
=> Use new `fips_mode` variable to define whether to build with FIPS

habitat/hooks/run
This will resolve an error that appears if this Habitat package is built and run for development or personal use under a different origin.
Paired with @ubergeekgirl on this change.
No open issues related. This change was first posited on [a comment](https://github.com/chef/chef/pull/5677#discussion_r94259175) on the PR adding a Habitat plan to this repo.
Error that appears when the package is built with my origin is:
```
hab-sup(MN): Starting robbkidd/chef-client
hab-sup(MR): Butterfly Member ID f4f32fe7c7d14bd98dbf0f2788f43afe
chef-client.default(SR): Process will run as user=root, group=hab
hab-sup(MR): Starting butterfly on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
chef-client.default(SR): Initializing
chef-client.default(SV): Starting
chef-client.default(O): …
```
=> use pkg.path variable to reference path to self

lib/chef/cookbook/cookbook_version_loader.rb, spec/data/prefer_metadata_json/metadata.json, spec/data/prefer_metadata_json/metadata.rb, spec/integration/client/client_spec.rb, spec/unit/cookbook/cookbook_version_loader_spec.rb
=> favor metadata.json over metadata.rb

lib/chef/provider/route.rb, spec/unit/provider/route_spec.rb
Convert the netmask into it's CIDR block for the route-eth0 file.
Everything I've found in terms of documentation says that the CIDR block is perfectly acceptable in the route-eth0 file. Unless I missed something that's probably what we want to use as RHEL does not accept the netmask. 
* Internal ZD-12741
=> Use CIDR notation rather than netmask in route-eth0 file

lib/chef/cookbook/syntax_check.rb, spec/unit/cookbook/syntax_check_spec.rb
Fixed 'too short control escape' on knfie upload.
#5702
=> Core: Ensure paths are correctly escaped when syntax checking

lib/chef/provider/systemd_unit.rb, lib/chef/resource/file/verification/systemd_unit.rb, spec/unit/resource/file/verification/systemd_unit_spec.rb
Adds custom file verification class to work around file name requirements when running `systemd-analyze`.
This is a second attempt at adding this functionality after the first (#5210) had to be reverted. The problem lay in the fact that `systemd-analyze` checks that attributes within the unit match the name of the unit as determined by it's filename. Due to the way in which the Chef file provider manages temp files, the name would not match and `systemd-analyze` would fail the file.
This second approach addresses this problem by providing a custom file verification class which copies the temp file to a new temp directory under it's real name and verifies it there instead, before cleaning up the temp directory and by extension the second temp file.
- #5200 (original feature request)
- …
=> Verify systemd_unit file with custom verifier

lib/chef/provider/package/ips.rb, spec/unit/provider/package/ips_spec.rb
Other package providers will raise an error if the package installation returns an unaccepted response code. The `ips_package` provider should do the same. 
* #5132
* Internal Ticket (COOL-464)
=> Raise error if ips_package install returns non-zero

lib/chef/application/client.rb
Somewhat unintuitively, mixlib-cli needs both `boolean => true` as well as
`long => "--[no-]option"` for the boolean feature to work.
=> Fix --no-fips on chef-client

lib/chef/chef_fs/file_system/repository/chef_repository_file_system_root_dir.rb, lib/chef/chef_fs/file_system/repository/nodes_dir.rb
In addition to the creating user, grant the Administrators group permission to the nodes directory created when chef-solo executes. 
* Fixes #5768
=> Grant Administrators group permissions to nodes directory under chef-solo

lib/chef/mixin/which.rb, lib/chef/provider/package.rb, lib/chef/provider/package/dnf/dnf_helper.py, lib/chef/provider/package/dnf/python_helper.rb, spec/unit/mixin/which.rb, spec/unit/provider/package/dnf/python_helper_spec.rb, spec/unit/util/selinux_spec.rb
- fixes for dnf 2.0 / rhel7
- improved error messages from python helper (gives python stack
traces instead of just EPIPE all the time)
- improved which/where interface in the which mixin.
=> rhel7 / dnf 2.0 fixes / improved errors

spec/spec_helper.rb, spec/support/platform_helpers.rb, spec/support/shared/functional/execute_resource.rb, spec/support/shared/functional/windows_script.rb
On Windows you need the SeAssignPrimaryTokenPrivilege right to use
CreateProcessAsUser when running under a service, even if you're an
Administrator. This makes these functional tests not run under Jenkins if
the jenkins user does not have this right.
=> Fix functional tests for alternate user support

lib/chef/platform/provider_mapping.rb, spec/unit/platform_spec.rb
Deprecation warnings for Chef::Platform methods introduced in #5631 were
logged as e.g. `"Class.set is deprecated"` instead of `"Chef::Platform.set is
deprecated"`
This gets correct class name for message and adds unit specs to cover
the expected deprecation messages.
Unfortunately for these specs, some of these methods use each other,
resulting in multiple warnings. I have put an expectation for each of
these to avoid masking any other deprecations.
Signed-off-by: Bill Ruddock <bill.ruddock@gmail.com>
=> Fix chef_platform_methods deprecation class name

lib/chef/resource.rb, spec/unit/resource_spec.rb
When a property is marked sensitive, suppress it when printing a text representation of the resource for logging purposes. 
* ZD-13635 (internal ticket)
* COOL-680 (internal ticket)
* Fixes #5473
=> Suppress sensitive properties from resource log and reporting output

RELEASE_NOTES.md
We merged in notes for 12.19 with the old 12.18 notes. This removes the 12.18 notes and adds the notes from Thom’s PR. It also adds the 6 anticipated Ohai deprecations. Two of these deprecations have yet to be merged into master, but they’re planned for 13.0.
=> Update release notes for 12.19

chef.gemspec
Ruby 2.2 is still not compatible with the latest rack. We need to actually specify 2.2.2+ which is what rack and others now require. We dep on rack via chef-zero.
=> Bump minimum required ruby version to 2.2.2

lib/chef/http/api_versions.rb, lib/chef/mixin/versioned_api.rb, lib/chef/server_api.rb, lib/chef/server_api_versions.rb, spec/unit/http/api_versions_spec.rb, spec/unit/mixin/versioned_api_spec.rb, spec/unit/server_api_versions_spec.rb
When we make a request to a chef server, we capture the minimum and
maximum support API versions and allow them to be queried.
We then provide some infrastructure for making decisions on which class
should be used, in a middleware-ish mechanism.
=> Beginning of automatic API version detection

Gemfile.lock, omnibus/Gemfile.lock
This reverts commit bd45e8360cf233cbadba17c4ee9870d450a610f8.
Seems to have caused some chaos building omnibus in manhattan for reasons that I don't understand right now and the shortest path to getting back to green (and isolating the fact that the dep bumping broke the build) is just to revert this change.
=> Revert "updating dependencies"

RELEASE_NOTES.md
Chef Client will no longer be built or tested on Cisco platforms.
@chef/engineering-services 
=> Deprecate Cisco platforms

lib/chef/provider/package.rb, spec/unit/provider/package/apt_spec.rb
This correctly deals with quotes and so on in package options to apt_package.
#5836
=> Use shellsplit for apt_package options

lib/chef/knife/core/bootstrap_context.rb, spec/unit/knife/core/bootstrap_context_spec.rb
When a node is bootstrapped in FIPS mode and then tries to run a
chef-client run it gets the following error:
```
STDERR: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-config-12.18.31/lib/chef-config/workstation_config_loader.rb:163:in `rescue in apply_config': You have an error in your config file /var/opt/delivery/workspace/.chef/knife.rb (ChefConfig::ConfigurationError)
NameError: uninitialized constant Chef
/var/opt/delivery/workspace/.chef/knife.rb:2:in `eval'
/var/opt/delivery/workspace/.chef/knife.rb:2:in `eval'
/var/opt/delivery/workspace/.chef/knife.rb:2:in `from_string'
```
ER-478 in Jira
=> Require chef/version when trying to read it

MAINTAINERS.md, MAINTAINERS.toml
Chef is no longer built on the Cisco platforms, so there is no need
for lieutenants and maintainers any longer.
Signed-off-by: Adam Leff <adam@leff.co>
=> Removing Cisco from Maintainers files

lib/chef/http/json_output.rb
we should probably raise (?) but this at least helps us debug.
This is just a little bit of help for bugs like this one:  https://github.com/chef/chef-dk/issues/1184
=> HTTP: add debug long for non-JSON response

omnibus/Gemfile, omnibus/Gemfile.lock
the `github:` argument gets translated to git:// urls, which are
insecure and i have a .gitconfig which translates those to
https:// urls, and the effect of that is that when _I_ bump the
Gemfile.lock the urls don't match and `bundle install` with
the `--deployment` flag gets all pissy and I break the build, and
since i don't habitually `bundle install --deployment` locally I
never see the failures.
=> bump omnibus gems and change protocol to https

lib/chef/knife/data_bag_create.rb, spec/unit/knife/data_bag_create_spec.rb
[ZD-12613]
There are users who want to customize permissions to prevent a group of
users from creating new data bags but want to allow the group of users
to create data bag items within an existing data bag.
If the user doesn't have permission to create data bags then the current
API request sequence will prevent the user from creating a data bag item
even if the data bag already exists.
This commit fixes the above problem by verifying (not trying to create)
if the data bag exist through a GET request, if it doesn't the it tries
to generate it, then it proceeds to create the data bag item.
ZD-12613
=> Verify data bag exists before trying to create it

.bundle/config, chef-config/lib/chef-config/config.rb, lib/chef/knife/bootstrap.rb, lib/chef/knife/ssh.rb, spec/functional/knife/ssh_spec.rb, spec/unit/knife/bootstrap_spec.rb
Add an option for gateway_identity_file that will allow key-based authentication on the gateway.
Rebase of https://github.com/chef/chef/pull/1651
N/A
=> CHEF-4538 - add an option for gateway_identity_file that will allow key-based authentication on the gateway.

Gemfile, Rakefile, chef-config/lib/chef-config/package_task.rb, ci/bundle_install.sh, ci/version_bump.sh, tasks/version.rb
This PR shifts some of the logic around, making it so that all the version bumping logic is together. It also adds a special helper that allows the entire version bump task to be tolerant of failure.
=> Improve version bumping 

lib/chef/property.rb, spec/unit/property_spec.rb
This removes all the magic that attempts to allow users to write unsafe
properties - ie, ones that set a default but claim to be a name
property. This yielded different results depending on ordering. It's
better for our users to just suck up fixing this.
Closes: #5542, replaces: #5866
(Part of #3705)
=> Be a bit less keen to help properties

RELEASE_NOTES.md, lib/chef/resource.rb, lib/chef/resource/mount.rb, lib/chef/resource/service.rb, lib/chef/resource/user.rb, spec/unit/provider/user/linux_spec.rb, spec/unit/resource/mount_spec.rb, spec/unit/resource/service_spec.rb, spec/unit/resource_spec.rb
still there on service (where it makes some sense)
also still on mount (because i have no idea if that is actively being
used or if it makes any sense at all).
converts it to a property on mount + service as well.
bonus bug fix:  the old array-style code was mutating the default values, which it should not do now.
=> CHEF-13:  remove supports API from Chef::Resource

lib/chef/provider/package/windows/registry_uninstall_entry.rb, spec/unit/provider/package/windows/registry_uninstall_entry_spec.rb
#
Some Windows packages apparently create a separate uninstall string under the key QuietUninstallString. We should search for that and use it if it exists.
https://github.com/chef/chef/issues/5580
=> add support QuietUninstallString for windows packages

spec/functional/knife/ssh_spec.rb
this only affects tests running as root on old solaris because ENV['HOME'] for
root is "/" there and that causes a "/.ssh" vs "//.ssh" error if we don't
File.expand_path in both the code and the spec.
=> fix spec for solaris 10

acceptance/Gemfile, acceptance/Gemfile.lock
i guess this makes this also an integration test of
chef-config against berkshelf and ridley.
i considered going the other way and pinning to < 13 in order
to get the rubygems version, but decided to go this direction
since it feels like we get more 'coverage' this way.
=> use master of chef-config we're tesing in acceptance tests

acceptance/Gemfile, acceptance/Gemfile.lock
jenkins barfed pretty hard on the prior attempt to fix.  this
should work better.
can obviously be backed out once chef-13 is released.
=> pinning chef-config in acceptance to rubygems version

.travis.yml, Gemfile, Gemfile.lock
I'm not sure this is providing value. Should we decide to put resources in to sorting out cheffish/provisioning etc, we can easily re-add this.
=> Remove provisioning from the downstream tests

lib/chef/provider/apt_repository.rb, spec/unit/provider/apt_repository_spec.rb
Great description and solution of the problem made by @jeremiahsnapp in
the below issue!
Closes https://github.com/chef/chef/issues/5831
I have validated this works fine for the following os:
* Ubuntu 14.04
* Ubuntu 16.04
* Ubuntu 16.10 (latest)
* Debian-6.0.10
* Debian-8.7 (latest)
* COOL-685
* https://github.com/chef/chef/issues/5831
=> Fix apt_repository for latest os version 16.10

omnibus/Gemfile, omnibus/Gemfile.lock
This updates the branch pinnings to use the omnibus-toolchain enabled version of omnibus and omnibus-software and removes the no longer needed pinnings for the long-standing branches on omnibus and omnibus-software.
/cc @chef/engineering-services 
/cc @chef/maintainers
=> Use omnibus-toolchain on Windows platforms.

omnibus/config/projects/chef.rb
This gives considerable size benefits, at a cost of slightly slower decompression. xz compression has been available in dpkg and rpm since 2009 so we shouldn't see any platforms that don't support this.
=> Compress debs and rpms with xz

lib/chef/knife/bootstrap/templates/chef-full.erb, spec/unit/knife/bootstrap_spec.rb
[ZD-12489] This change fixes the content expansion of the
bootstrap command in the option `--json-attributes`.
Reference:
https://www.gnu.org/software/bash/manual/html_node/Redirections.html
It might be possible that some users are counting on this expansion
to occur.
* [ZD-12489]
=> Changed EOP to 'EOP' to avoid content expansion

Gemfile.lock, lib/chef/resource.rb, spec/data/lwrp/resources/buck_passer.rb, spec/data/lwrp/resources/buck_passer_2.rb, spec/data/lwrp/resources/embedded_resource_accesses_providers_scope.rb, spec/data/lwrp/resources/inline_compiler.rb, spec/data/lwrp/resources/monkey_name_printer.rb, spec/data/lwrp/resources/paint_drying_watcher.rb, spec/data/lwrp/resources/thumb_twiddler.rb, spec/unit/lwrp_spec.rb, spec/unit/resource/deploy_spec.rb, spec/unit/resource_spec.rb
most of this deletes useless old code.
the change to lookup_provider_constant changes to more strictly
stop using class name based lookups and to go through the resource
resolver and provider resolver.
as a result in order to find the provider class for a given dsl name
you have to go through the resource resolver to find the resource in
order to be able to pass a resource instance through the provider
resolver.  since the provider resolver api passes resources into blocks
passed into provides api you must construct a resource instance.
that means that providers need to be associated with resources in order
to be looked up (which makes sense in Real Life(tm) use of Chef, but
breaks quite a few lazy tests we had where we constructed providers
without doing the work of wrapping them in a …
=> Chef-13:  Chef::Resource cleanup

RELEASE_NOTES.md, lib/chef/node/attribute.rb, lib/chef/node/attribute_collections.rb, lib/chef/node/immutable_collections.rb, spec/unit/node/attribute_spec.rb, spec/unit/node_spec.rb
So again the reasons why we break this:
- node.class vs. node['class'] kinds of problems
- adding node#foo to Chef::Node as an extension to the API and
breaking node.foo meaning node["foo"] (we can't make exensions
to that class without possibly breaking someone)
- crazy things like the old CHEF-3799 issue in the old ticketing
system where IO#puts in ruby blindly calls #to_ary on stuff and
expects it to raise -- whereas we would potentially autovivify
a 'to_ary' hash key and return nil which breaks the world.
This also has caused issues with the hashie gem and they've gone to
spamming warnings by default to try to deal with it:
https://github.com/berkshelf/berkshelf/issues/1665
=> Chef-13: remove method_missing access to node object.

RELEASE_NOTES.md, lib/chef/dsl/declare_resource.rb, lib/chef/dsl/resources.rb, spec/unit/recipe_spec.rb
Likely nobody cares about this change, I added it and then a
release or two later introduced the better edit_resource style
of API.
I also changed "created_at" to be a proper named parameter, instead
of a positional parameter, which is a breaking change in an API that
has been around for quite some time -- makes the API consistent since
I added it as a named parameter to the new APIs when I wrote them.
(This one is very internal, though, so I suspect there's a shortlist of
things that muck about in chef internals that would be all that would break).
=> Chef-13:  Remove declare_resource create_if_missing API

lib/chef/node/immutable_collections.rb, spec/unit/node/attribute_spec.rb, spec/unit/node/immutable_collections_spec.rb
previously to_hash allowed mutating non-container elements, now
they get properly dup'd.
fixes a 2.5 year old pending spec test.
also fills out the API so that there is to_h/to_hash/to_a/to_array
instead of the weird mix-and-match we had before.
bonus-fix:  dup wasn't properly dup'ing as well
=> Chef-13:  properly deep dup Node#to_hash

RELEASE_NOTES.md, lib/chef/node/immutable_collections.rb, lib/chef/node/mixin/immutablize_array.rb, lib/chef/node/mixin/immutablize_hash.rb, spec/unit/node/attribute_spec.rb
Another oversight in creating ImmutableMash/Array but the strings were never dup'd and frozen.
I'm certain this will break bad code out there.  There's no way to issue deprecation warnings though (monkeypatching every mutator on every simple class like String and Fixnum so that you can mark a string as being deprecated-frozen so that they'll issue warnings, although dup will remove the flag and make it behave the same afterwards?  Nope...)
=> Chef-13: freeze merged node attribute

.gitignore, RELEASE_NOTES.md, lib/chef/shell.rb, lib/chef/shell/shell_session.rb, spec/data/shef-config.rb, spec/functional/shell_spec.rb, spec/unit/shell/shell_session_spec.rb
As a person who debugs chef cookbooks with chef-shell, I should be able to connect to a local chef-zero instance with chef-shell, so that I can more easily debug my cookbooks in server mode.
https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/8783605-chef-shell-with-chef-zero-local-client-mode-supp
=> Properly use chef-shell in SoloSession by deprecating old behavior into SoloLegacySession

lib/chef/shell.rb
There is a little mistake that we didn't catch. This will fix the option name and help message.
None
=> Fix chef-shell option name and help message

lib/chef/node_map.rb, spec/unit/node_map_spec.rb
removes old Chef-10 era APIs that were not widely used.
=> Chef-13: remove node_map back-compat

lib/chef/util/windows/net_user.rb, lib/chef/win32/security/sid.rb
Get Users group name based on SID
In some languages, windows translates the name of the Users group. This causes a group does not exist error. The SID is supposed to be the same across different languages, so getting the name based on the SID fixes the problem.
The only gotcha is that account_name returns something like BUILTIN\Users, and that also fails with a group does not exist error. Only the group name must be sent, and not the domain.
=> Fix for creating users in non english windows machines

lib/chef/client.rb
nothing uses these, nothing should use these, no tests, deprecated for ages, goodbye...
=> Chef-13: Remove deprecated Chef::Client attrs

RELEASE_NOTES.md, lib/chef/dsl/resources.rb, lib/chef/property.rb, lib/chef/provider.rb, spec/integration/recipes/recipe_dsl_spec.rb, spec/integration/recipes/resource_action_spec.rb, spec/unit/property_spec.rb
we did actually have tests around creating actions with spaces and
hyphens in their names.  we had fallback code for properties, but it
was broken and threw a "private method define_resource called" and then
it created a closure and didn't have the `name` in the binding so it
called itself and blew up the stack.
this change walks that back.  it does prove that we still support
UTF-8 in property names, actions and DSL names, which i'd argue is
more than enough.
=> Chef-13: Simplify DSL creation

Gemfile, Gemfile.lock
https://github.com/sparklemotion/nokogiri/issues/1615
This is required to pass the bundle-audit check in Travis CI
=> Bump nokogiri for CVE-2016-4658

RELEASE_NOTES.md, lib/chef/resource.rb, spec/unit/resource_spec.rb, spec/unit/runner_spec.rb
Without this, sending an interrupt signal (hitting Ctrl+C) during a
chef-client run that is currently executing a resources that has
`retries` set will not interrupt the run.
If the retryable resource is shelling out, the spawned process also gets
the INT signal and will stop -- however, the chef-run would go on,
merely noticing that the resource has failed and theres X-1 retries
left.
It is imaginable that users depend on some (whacky) Ruby script in a
retriable resource that raises SystemExit, and they want this to _not_
stop the chef-run. So it's up for debate if we just want to merge this
or make it configurable.
In general, I'd like Ctrl+C to _stop my chef-run_, but this expectation
could also be misled.
StackOverflow …
=> Don't `rescue Exception` in retryable resources

lib/chef/data_collector/resource_report.rb, spec/unit/data_collector/resource_report_spec.rb
Lets make the ResourceReporter smarter, we will try to get the identity
and state (after and before) of the resource but if we can't because of
an Exception, lets sends a message to the data collector containing a
static resource identity since we were unable to generate a proper one.
The problem is coming from the ResourceReporter, when it is trying to
report back the resource identity and state, it is using basic methods
from the Base class that should be secure to call from eny subscriber.
This is actually not a bug since Chef is doing the right thing, that is
to throw an error when the identity property is nil (or is not the right
kind that we configured for) so, rather than making identity properties
smarter for lazy evaluation we are going to make the ResourceReporter a
bit smarter …
=> Make ResourceReporter smarter to get resource identity and state

lib/chef/provider_resolver.rb, lib/chef/resource.rb, spec/integration/recipes/resource_action_spec.rb
The old action_class code was doing some magical stuff with the provider
accessor in order to determine if the class was supposed to be a custom
resource or not and have the action_class autovivifying accessor return nil
in cases when the resource wasn't a custom resource and implementing
inheritance by walking back up the tree in ways that were difficult to
grok.
This removes the magic from the provider so that there's no longer any
accessor that magically short-circuits to nil if the resource is not
supposed to be a custom resource.
There is now a simple inherited API for `Chef::Resource.custom_resource?`
which just defines if the class is a custom resource or not.  Since both
`action` and `action_class` call `define_action_class` they both wind up
setting this boolean on the class, …
=> Fix action class weirdness in Chef-13

lib/chef/http.rb, lib/chef/http/api_versions.rb, lib/chef/http/authenticator.rb, lib/chef/mixin/versioned_api.rb, lib/chef/server_api_versions.rb, spec/spec_helper.rb, spec/unit/http/api_versions_spec.rb, spec/unit/http/authenticator_spec.rb, spec/unit/mixin/versioned_api_spec.rb
If we've not made a request to the server previously, we start by
trying the best possible version we know about; this means that in the case of a fresh connection to an old server we in general should only make two requests at worst.
=> Retry API requests if using an unsupported version

Gemfile, Gemfile.lock, omnibus/config/software/chef.rb
nokogiri does not have a ruby-2.4 release for windows
this is slightly complicated because we still need nokogiri in the
Gemfile.lock for travis.
i'm starting to think we should have a Gemfile.travis and
Gemfile.travis.lock or something and stop using groups for that.
=> disable nokogiri on windows for now

lib/chef/provider.rb, lib/chef/resource.rb, lib/chef/resource/action_class.rb
since any ActionClass literally is-a Chef::Provider it should just
use inheritance and then we don't have to use the hacky hooks for
class methods in modules and it becomes more clear from the
ActionClass source what it is and what it does.
~~Bonus starts the deprecation of properties being injected into the
provider namespace.~~ Not yet.
=> Chef-13: Make ActionClass a class

spec/functional/resource/link_spec.rb
ruby-2.4 on solaris 11 behaves the same way here
i suspect linux is the buggy one and everyone else is posix
compliant...
=> fix ruby-2.4 func link tests on solaris 11

lib/chef/resource/powershell_script.rb
Signed-off-by: Tor Magnus Rakvåg <tm@intility.no>
Sets the default `guard_interpreter` of `powershell_script` back to `:powershell_script`
https://github.com/chef/chef/issues/5953
=> set default guard_interpreter to powershell_script

RELEASE_NOTES.md, lib/chef/dsl/resources.rb, lib/chef/resource.rb, lib/chef/resource/apt_update.rb, lib/chef/resource_builder.rb, lib/chef/resource_collection/resource_set.rb, spec/integration/recipes/notifies_spec.rb, spec/integration/recipes/recipe_dsl_spec.rb, spec/unit/dsl/resources_spec.rb, spec/unit/property_spec.rb, spec/unit/recipe_spec.rb, spec/unit/resource/conditional_spec.rb, spec/unit/resource_collection/resource_set_spec.rb, spec/unit/resource_spec.rb
This makes nameless resources work in the DSL:
```ruby
apt_update
```
It does it by giving it an empty-string name of ""
It also drops support for multi-arg resources, that has been deprecated
for some time:
```ruby
some_resource "foo", "bar", "baz"
```
Note that multipackage package resources do not use multiple args, but a
single argument which is an array:
```ruby
package [ "lsof", "strace", "tcpdump" ]
```
So this change does not affect that usage.  Multi-arg has been
deprecated for some time now and its not clear that it was ever used by
anyone.
=> Chef-13: Support nameless resources and remove deprecated multi-arg resources

lib/chef/decorator/unchain.rb, spec/unit/node_spec.rb
removes the `node.set_unless.foo.bar.baz` case
=> Chef-13: remove more deprecated method_missing access

RELEASE_NOTES.md, lib/chef/knife/search.rb, lib/chef/knife/ssh.rb, lib/chef/search/query.rb, spec/unit/search/query_spec.rb
extracts out a common 'fuzz' option to Chef::Search::Query so that anyone can
use it.
closes #3526
=> apply knife search node fuzzifier to knife ssh

lib/chef/resource_resolver.rb
Removes an alias to Chef::ResourceResolver.resource_name
=> Chef-13: Remove deprecated Chef::ResourceResolver.resource API

RELEASE_NOTES.md, omnibus/Gemfile.lock, omnibus/config/software/chef.rb, omnibus/files/chef-gem/build-chef-gem.rb
pulls in chef/omnibus-software#806 and removes iconv from both
nokogiri and ruby.
ruby hasn't needed iconv since 1.9.x and everyone should be using
the Encoding library by now.
nokogiri will lose support for things like Shift-JIS inside of XML
but UTF-8, UTF-16LE/BE, ISO-8851-1(Latin-1), ASCII and "HTML" encoding
are all supported by nokogiri natively.  if users need more they need
to be maintaining their own nokogiri installs and accept the
maintenance costs themselves.
=> Chef-13: remove iconv from the chef build

lib/chef/cookbook/gem_installer.rb, spec/unit/cookbook/gem_installer_spec.rb
Current gem installer does not work if multiple cookbook request the
same gem. The solution is to merge all the gem requirements for the same
gem.
If multiple cookbooks have conflicting constraints, the install will
fail anyway.
This bug affects Chef 12 too and make the feature almost unusable.
=> Fix cookbook gem installer

lib/chef/provider/package.rb, lib/chef/provider/package/windows/msi.rb, lib/chef/resource/chocolatey_package.rb, lib/chef/resource/package.rb, lib/chef/resource/windows_package.rb, spec/unit/provider/package/windows/msi_spec.rb, spec/unit/resource/package_spec.rb
Windows side we still can't support this kind of API, this
is for Unix-ey stuff.
closes #5763
=> Chef-13: coerce package options property to an Array

chef-config/lib/chef-config/config.rb, lib/chef/application.rb, lib/chef/provider/package/zypper.rb, lib/chef/resource/zypper_package.rb, spec/unit/provider/package/zypper_spec.rb
Adds a gpg_check property to the resource to turn them off on a
per-resource basis.  The global config is also preserved.  The
global config will warn once if you have it set to turn off
gpg checks.  The per-resource property will not warn (presumably
you know you're doing something bad when you turn it off).
closes #2339
=> Chef-13: turn on zypper gpg checks by default

lib/chef/formatters/error_description.rb, spec/unit/formatters/error_description_spec.rb
An example of the new block:
```
System Info:
------------
chef_version=13.0.0
platform=ubuntu
platform_version=16.04
ruby=ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
program_name=chef-client
executable=/opt/chef/bin/chef-client
```
The only odd ones that might need explanation are program_name which is the straight $0 and executable which is the un-symlinked path of the actual ruby-level program running.
=> Expand the system info displayed on error to give us some more data to work with when helping users
