chef/chef

- lib/chef/exceptions.rb
- lib/chef/knife/cookbook_site_install.rb
- spec/unit/knife/cookbook_site_install_spec.rb
Backport of PRs #2642 and #2345 to chef 11-stable
cc @btm @lamont-granquist @sethvargo @opscode/chef-employees
> Allow knife to install cookbooks with metadata.json

- lib/chef/exceptions.rb
- lib/chef/knife/cookbook_site_install.rb
- spec/unit/knife/cookbook_site_install_spec.rb
cc @danielsdeleo @sethvargo @opscode/client-engineers
> Provide more info when cookbook metadata is not found

- CHANGELOG.md
- lib/chef/version.rb
Its time
cc @opscode/client-engineers
> Prepare Chef 11.18.0 release

- CHANGELOG.md
- lib/chef/dsl/include_recipe.rb
- lib/chef/recipe.rb
- lib/chef/run_context.rb
- spec/unit/recipe_spec.rb
- spec/unit/run_context_spec.rb
fixes https://tickets.opscode.com/browse/CHEF-3599
> make include_recipe "::foo" use current cookbook

- CHANGELOG.md
@lamont-granquist 11.18.2 got tagged with an error in the CHANGELOG :disappointed:
> Prepare 11.18.4

- lib/chef/resource.rb
The biggest thing this does is order the methods into four main groups:
- Generic DSL (methods that are just there so words like "lazy" and "search" will work
- Resource DSL (methods the user will call when using the resource)
- Resource Definition DSL (methods a resource developer will call)
- Internal (stuff that seems like it's only for Chef)
> Add lots of comments to Resource, section methods by who uses them

- spec/unit/application/client_spec.rb
Fixes https://github.com/chef/chef/issues/2747.
Verified this on my local box with an unreadable /etc/chef/client.rb. @ranjib @lamont-granquist @tyler-ball
> Stub reading of /etc/chef/client.rb in spec

- CHANGELOG.md
> missing md file

- lib/chef/provider/dsc_script.rb
This is just a small fix for a typo that I found while digging through this code.
> Fix typo resouces to resources

- lib/chef/knife.rb
This is just a typo fix I found while looking through the code in this file.
> Fix typo cab to can

- CHANGELOG.md
- lib/chef/version.rb
Forgot to bump version in 11.18.4
> Prepare 11.18.6

- CHANGELOG.md
- lib/chef/data_bag_item.rb
- spec/unit/chef_fs/file_pattern_spec.rb
- spec/unit/data_bag_item_spec.rb
Merging https://github.com/chef/chef/pull/2707
> Merging https://github.com/chef/chef/pull/2707

- appveyor.yml
- spec/stress/win32/file_spec.rb
- spec/unit/application/client_spec.rb
testing to see if it passes, cherry-pick of #2655
> appveyor for 12-stable

- spec/functional/resource/user/useradd_spec.rb
See https://github.com/chef/chef/commit/f445869cfa26b17e22a4266c58907b3619b749ae#commitcomment-9471756
> Fixed typo in test from #2823.

- lib/chef/knife/ssl_fetch.rb
- require 'knife/chef'
- dont require self
> Fix require statement on knife ssl fetch

- CHANGELOG.md
- lib/chef/provider/package/rpm.rb
- spec/unit/provider/package/rpm_spec.rb
Merging https://github.com/chef/chef/pull/2698
> Merging https://github.com/chef/chef/pull/2698

- appveyor.yml
This will print a `.` instead of the full test name
\cc @jdmundrawala @chef/maintainers
> Changing Appveyor to use progress formatter

- RELEASE_NOTES.md
- kitchen-tests/.chef/client.rb
- kitchen-tests/cookbooks/audit_test/recipes/default.rb
- kitchen-tests/cookbooks/audit_test/recipes/error_duplicate_control_groups.rb
- kitchen-tests/cookbooks/audit_test/recipes/error_no_block.rb
- kitchen-tests/cookbooks/audit_test/recipes/error_orphan_control.rb
- kitchen-tests/cookbooks/audit_test/recipes/failed_specs.rb
- kitchen-tests/cookbooks/audit_test/recipes/serverspec_collision.rb
- kitchen-tests/cookbooks/audit_test/recipes/serverspec_support.rb
- kitchen-tests/cookbooks/audit_test/recipes/with_include_recipe.rb
- lib/chef/audit/audit_event_proxy.rb
- lib/chef/audit/runner.rb
- lib/chef/dsl/audit.rb
- lib/chef/event_dispatch/base.rb
- spec/functional/audit/runner_spec.rb
- spec/integration/client/client_spec.rb
- spec/unit/audit/audit_event_proxy_spec.rb
- spec/unit/audit/runner_spec.rb
- spec/unit/dsl/audit_spec.rb
- spec/unit/recipe_spec.rb
This addresses https://github.com/opscode/chef/issues/2755.
\cc @tyler-ball @opscode/client-engineers
> Change audit DSL method controls to control_group.

- spec/unit/knife/role_env_run_list_add_spec.rb
- spec/unit/knife/role_env_run_list_clear_spec.rb
- spec/unit/knife/role_env_run_list_remove_spec.rb
- spec/unit/knife/role_env_run_list_replace_spec.rb
- spec/unit/knife/role_env_run_list_set_spec.rb
- spec/unit/knife/role_run_list_add_spec.rb
- spec/unit/knife/role_run_list_clear_spec.rb
- spec/unit/knife/role_run_list_remove_spec.rb
- spec/unit/knife/role_run_list_replace_spec.rb
- spec/unit/knife/role_run_list_set_spec.rb
broke master with #stub! which got removed.  fixed mechanically
via using transpec gem
> rspec-3-ify all the env-run-list specs

- spec/unit/application/client_spec.rb
These were not passing on windows in jenkins or on my local machine. Still not clear on why they passed in appveyor
cc @mcquin @chef/client-engineers
> Fix broken tests in jenkins

- lib/chef/provider/dsc_script.rb
- lib/chef/util/dsc/local_configuration_manager.rb
- spec/unit/util/dsc/local_configuration_manager_spec.rb
Solves https://github.com/chef/chef/issues/2831
cc @btm @ksubrama @smurawski
> dsc_script passes timeout to lcm shellout

- MAINTAINERS.md
per https://github.com/chef/chef/pull/2710#issuecomment-73626709
I have a Fedora environment at work currently (fleet of about 250) so would considering putting myself forward for those if I end up maintaining a lot of Redhat-specific crap.
> Chef Core maintainers: ++fujin

- CHANGELOG.md
- DOC_CHANGES.md
- lib/chef/provider/package/yum.rb
- spec/unit/provider/package/yum_spec.rb
This is a squashed and rebased version of #2835.
> Updated version of #2125 to fix CHEF-2911

- lib/chef/knife/core/generic_presenter.rb
- spec/unit/knife/core/ui_spec.rb
These were super close to being done, so I'm just pushing them across the finish line.  Thanks to @justanshulsharma for the original work!
Fixes https://github.com/chef/chef/issues/1974
\cc @chef/client-core @adamedx
> Finishing tests for https://github.com/chef/chef/pull/2338

- lib/chef/node/attribute.rb
- spec/unit/node/attribute_spec.rb
Finishing the tests, again thanks to @justanshulsharma for the original work!
Fixes https://github.com/chef/chef/issues/1562
> Completing tests for https://github.com/chef/chef/pull/2310

- lib/chef/guard_interpreter/resource_guard_interpreter.rb
- spec/unit/guard_interpreter/resource_guard_interpreter_spec.rb
Completing the tests for https://github.com/chef/chef/pull/2688
Fixes https://github.com/chef/chef/issues/2683
> Adding tests for https://github.com/opscode/chef/pull/2688

- lib/chef/provider/package/rpm.rb
Dont raise exceptions in load_current_resource when checking current status
> Dont raise exceptions in load_current_resource when checking current status

- lib/chef/chef_fs/file_system/chef_repository_file_system_cookbook_entry.rb
- lib/chef/cookbook_site_streaming_uploader.rb
- lib/chef/knife/cookbook_site_share.rb
- lib/chef/knife/ssh.rb
- lib/chef/platform/provider_mapping.rb
- lib/chef/provider/env.rb
- lib/chef/provider/registry_key.rb
- lib/chef/role.rb
- lib/chef/util/path_helper.rb
- lib/chef/util/windows/net_use.rb
fixes some Linting cops:
* Lint/UnreachableCode
* Lint/Loop
* Lint/LiteralInCondition
* Lint/AmbiguousRegexpLiteral
* Lint/DefEndAlignment
* Lint/BlockAlignment
> remove unreachable code

- lib/chef/provider/group.rb
- lib/chef/provider/group/dscl.rb
- lib/chef/provider/ifconfig.rb
- lib/chef/provider/ifconfig/aix.rb
- lib/chef/provider/mount.rb
- lib/chef/provider/mount/mount.rb
- lib/chef/provider/package.rb
- lib/chef/provider/package/aix.rb
- lib/chef/provider/package/dpkg.rb
- lib/chef/provider/package/macports.rb
- lib/chef/provider/package/pacman.rb
- lib/chef/provider/package/portage.rb
- lib/chef/provider/package/rpm.rb
- lib/chef/provider/package/solaris.rb
- lib/chef/provider/package/yum.rb
- lib/chef/provider/package/zypper.rb
- spec/functional/resource/aix_service_spec.rb
- spec/functional/version_spec.rb
- spec/unit/provider/group/dscl_spec.rb
- spec/unit/provider/ifconfig/aix_spec.rb
- spec/unit/provider/ifconfig_spec.rb
- spec/unit/provider/mount/mount_spec.rb
- spec/unit/provider/package/aix_spec.rb
- spec/unit/provider/package/dpkg_spec.rb
- spec/unit/provider/package/macports_spec.rb
- spec/unit/provider/package/pacman_spec.rb
- spec/unit/provider/package/portage_spec.rb
- spec/unit/provider/package/rpm_spec.rb
- spec/unit/provider/package/solaris_spec.rb
- spec/unit/provider/package/zypper_spec.rb
> fix aix related providers to replace popen4 with mixlib shell_out

- lib/chef/knife/search.rb
Fixes #2980 
:construction: this passes unit tests but I haven't run it for real. Also, what's the risk of people w/ hardcoded workarounds getting broken, how much do we care (I presume they'll be happy about it in the long term)?
> Send search count to stderr

- lib/chef/knife/cookbook_site_share.rb
- spec/unit/knife/cookbook_site_share_spec.rb
cc @danielsdeleo @tyler-ball @fnichol
> Fix specs on OSX

- lib/chef/audit/runner.rb
- spec/unit/audit/runner_spec.rb
> Add /lib/chef/ to backtrace exclusion patterns for audit mode

- lib/chef/provider/package.rb
> Allow people to pass in a 'source' to package rules

- appveyor.yml
try it three times before giving up
> make appveyor retry bundle install

- MAINTAINERS.md
I'm proposing myself as LT for RHEL and Core - I've split the proposals into two commits so they can be handled separately if necessary.
> Proposing myself as LT for RHEL and Core

- lib/chef/provider/user/dscl.rb
- spec/functional/resource/user/dscl_spec.rb
- spec/functional/resource/user/useradd_spec.rb
- spec/spec_helper.rb
- spec/support/platform_helpers.rb
* Encoding issues
* Wrong specs being run
cc @jtimberman @tyler-ball @lamont-granquist @schisamo
> Fix dscl issues for osx

- lib/chef/node.rb
Should close [Issue 2863](https://github.com/chef/chef/issues/2863)
> Change inspect to string to be more human-readable.

- lib/chef/config.rb
- lib/chef/knife/bootstrap.rb
- lib/chef/knife/core/subcommand_loader.rb
- lib/chef/knife/exec.rb
- lib/chef/knife/ssh.rb
- lib/chef/provider/service/macosx.rb
- lib/chef/shell.rb
- lib/chef/util/path_helper.rb
- lib/chef/workstation_config_loader.rb
- spec/unit/config_spec.rb
- spec/unit/knife/bootstrap_spec.rb
- spec/unit/knife/core/subcommand_loader_spec.rb
- spec/unit/provider/service/macosx_spec.rb
- spec/unit/shell_spec.rb
- spec/unit/workstation_config_loader_spec.rb
> Change all accesses to ENV['HOME'] or ~ to PathHelper.home instead.

- RELEASE_NOTES.md
cc @chef/client-windows @adamedx @btm @smurawski
> DSC Resource release notes

- lib/chef/provider/package/rubygems.rb
A clearer error message here would have saved me significant time yesterday. See also #2963. Thanks, Peter
> Clarify warning

- lib/chef/provider/cron.rb
- lib/chef/provider/cron/unix.rb
Fixes #3136 
cc @lamont-granquist @scotthain
> Use unix specific provider for cron on solaris

- lib/chef/provider/dsc_resource.rb
> Fixed bug where module_name would return an object instead of string

- CHANGELOG.md
- lib/chef/mixin/params_validate.rb
- lib/chef/provider/deploy.rb
- lib/chef/provider/git.rb
- lib/chef/resource.rb
- lib/chef/resource/deploy.rb
- lib/chef/resource/git.rb
- lib/chef/resource/lwrp_base.rb
- spec/functional/resource/deploy_revision_spec.rb
- spec/unit/mixin/params_validate_spec.rb
- spec/unit/resource/deploy_spec.rb
This change had many unforeseen consequences. Reverting until we can figure out a way to do this that does not break people
cc @chef/client-engineers @chef/client-core
> Revert nillable resource attributes

- lib/chef/util/path_helper.rb
- spec/unit/util/path_helper_spec.rb
Fixes #3153 
cc @chef/client-core @chef/client-engineers
> Fix bug where unset HOME would cause chef to crash

- MAINTAINERS.md
Ping @chef/maintainers & @martinisoft
> Volunteer myself as FreeBSD maintainer.

- CHEF_MVPS.md
Awesome Community Chefs are listed in the MVPs file.
Blog URLs use the chef.io domain.
> Awesome Community Chefs

- spec/functional/resource/execute_spec.rb
> Fix failing specs

- lib/chef/exceptions.rb
- lib/chef/key.rb
- spec/unit/key_spec.rb
Implemented and added spec for the Key object corresponding to the key rotation API endpoint.
Blocked pending chef/oc_erchef#126 merge.
Ping @chef/lob
> Chef Key Object

- lib/chef/version.rb
> 12.4.0.dev.0 for master

- lib/chef/log.rb
- spec/unit/log_spec.rb
It's update for https://github.com/chef/chef/pull/3262 .
For now, it works well.
```
log_location Chef::Log::Syslog.new
```
```
$ chef-client -l debug -c client.rb
Apr 23 14:29:44 rundeck01 chef-client[3788]: [14:29:44.742957 ] [ WARN]: Node rundeck01.higan.works has an empty run list.
Apr 23 14:29:44 rundeck01 chef-client[3788]: [14:29:44.744007 ] [DEBUG]: Converging node rundeck01.higan.works
Apr 23 14:29:44 rundeck01 chef-client[3788]: [14:29:44.744843 ] [DEBUG]: Saving the current state of node rundeck01.higan.works
Apr 23 14:29:44 rundeck01 chef-client[3788]: [14:29:44.746246 ] [DEBUG]: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
Apr 23 14:29:44 rundeck01 chef-client[3788]: [14:29:44.750056 ] [DEBUG]: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_request
Apr 23 …
```
> send message with Severity to syslog

- MAINTAINERS.toml
> Fix syntax nits in Maintainers file

- lib/chef/provider/package/yum.rb
- spec/unit/provider/package/yum_spec.rb
We rely on a system python installation with the correct python
libraries.  To improve the chances that the python interpreter we call
has the yum libary available, we use the same interpreter as yum uses.
Fixes #3143
> Use the same python interpreter as yum when possible

- spec/functional/dsl/reboot_pending_spec.rb
> Cherry pick changes for reboot pending

- kitchen-tests/.kitchen.travis.yml
- kitchen-tests/.kitchen.yml
- kitchen-tests/Gemfile
Update kitchen tests to use latest official test-kitchen
cc @chef/client-core @schisamo @mcquin
> Update kitchen tests to use latest official test-kitchen

- lib/chef/knife/client_key_list.rb
- lib/chef/knife/key_list.rb
- lib/chef/knife/key_list_base.rb
- lib/chef/knife/user_key_list.rb
- spec/support/key_helpers.rb
- spec/unit/knife/key_create_spec.rb
- spec/unit/knife/key_helper.rb
- spec/unit/knife/key_list_spec.rb
Abstracted out a bunch of common tests with the key create code to reduce redundancy.
Ping @chef/lob
> Implemented `knife user key list` and `knife client key list`.

- CHANGELOG.md
- lib/chef/provider/package/yum.rb
- lib/chef/resource/yum_package.rb
- spec/unit/provider/package/yum_spec.rb
> Make multipackage and arch play nicely together

- lib/chef/knife/client_key_delete.rb
- lib/chef/knife/key_delete.rb
- lib/chef/knife/user_key_delete.rb
- spec/support/key_helpers.rb
- spec/unit/knife/key_create_spec.rb
- spec/unit/knife/key_delete_spec.rb
- spec/unit/knife/key_list_spec.rb
Ping @chef/lob 
@danielsdeleo @jdmundrawala @btm /cc client-core
> Implemented `knife user key delete` and `knife client key delete`.

- kitchen-tests/Gemfile
@jdmundrawala This is a follow up to #3260
> Updating to released test kitchen and kitchen vagrant

- .travis.yml
test latest 2.0.x, 2.1.x, 2.2.x
> let the ruby patchlevels float

- spec/functional/shell_spec.rb
also makes timing errors hard errors
> fixes the timing on the chef-shell specs

- ext/win32-eventlog/chef-log.man
- lib/chef/event_loggers/windows_eventlog.rb
- lib/chef/log.rb
- lib/chef/log/syslog.rb
- lib/chef/log/winevt.rb
- lib/chef/mixin/unformatter.rb
- lib/chef/win32/eventlog.rb
- spec/unit/log/winevt_spec.rb
- spec/unit/mixin/unformatter_spec.rb
> Added a logger for Windows Event Log

- CHANGELOG.md
- lib/chef/node.rb
- lib/chef/run_context.rb
- lib/chef/run_list/versioned_recipe_list.rb
- spec/unit/client_spec.rb
- spec/unit/policy_builder/policyfile_spec.rb
- spec/unit/run_context_spec.rb
* fix node[:recipes] 
* add node[:cookbooks]
* add node[:expanded_run_list]
> fix node recipes, add run_list_expansion and cookbooks

- .travis.yml
- appveyor.yml
- chef.gemspec
- spec/integration/client/client_spec.rb
- spec/integration/recipes/recipe_dsl_spec.rb
- spec/spec_helper.rb
- tasks/rspec.rb
* Fix IPv6 tests via Chef-Zero fix (TODO: merge that and use a released version of chef zero)
* Runs integration tests on travis
* Fix an issue where class "Foo" and module "Foo" were both defined.
Talking to John about the chef-zero thing https://github.com/chef/chef-zero/pull/133 Once that's done I'll redo the commit that pulls in the chef-zero fix.
> Integration tests fix ipv6

- CHANGELOG.md
- spec/unit/lwrp_spec.rb
> fix an lwrp default action test

- lib/chef/event_dispatch/base.rb
- lib/chef/formatters/doc.rb
- lib/chef/policy_builder/policyfile.rb
- spec/unit/formatters/doc_spec.rb
> Display Policyfile Name and Revision ID

- CHANGELOG.md
- lib/chef/resource.rb
- spec/unit/resource_spec.rb
allows for using shell_out! and friends in not_if/only_if blocks
> add shell_out to resources

- CHANGELOG.md
- lib/chef/mixin/windows_env_helper.rb
helps powershell pick up the env change settings.
> add unicode WM_SETTINGCHANGE broadcast

- lib/chef/audit/audit_reporter.rb
- lib/chef/audit/logger.rb
- lib/chef/audit/runner.rb
- lib/chef/client.rb
- lib/chef/event_dispatch/base.rb
- lib/chef/formatters/doc.rb
- spec/functional/audit/runner_spec.rb
- spec/support/shared/context/client.rb
- spec/unit/audit/audit_reporter_spec.rb
- spec/unit/audit/logger_spec.rb
- spec/unit/audit/runner_spec.rb
Fixes https://github.com/chef/chef/issues/2910
> Make sure the audit mode output is reflected both in the logs and in the formatter output.

- lib/chef/file_content_management/deploy/mv_windows.rb
- spec/unit/file_content_management/deploy/mv_windows_spec.rb
> Fix copying ntfs dacl and sacl when they are nil

- spec/unit/run_context_spec.rb
I found these when answering someone's questions.  Mo tests, mo better!
> These tests were accidently left out when I moved #2621 to master

- lib/chef/resource.rb
- lib/chef/resource/lwrp_base.rb
- spec/integration/recipes/recipe_dsl_spec.rb
- spec/unit/lwrp_spec.rb
> Ensure :nothing is in the list of allowed actions for an LWRP

- lib/chef/resource.rb
- spec/support/shared/shared_examples.rb
- spec/unit/api_client_spec.rb
- spec/unit/cookbook_version_spec.rb
- spec/unit/data_bag_item_spec.rb
- spec/unit/data_bag_spec.rb
- spec/unit/environment_spec.rb
- spec/unit/exceptions_spec.rb
- spec/unit/json_compat_spec.rb
- spec/unit/node_spec.rb
- spec/unit/osc_user_spec.rb
- spec/unit/recipe_spec.rb
- spec/unit/resource_collection_spec.rb
- spec/unit/resource_spec.rb
- spec/unit/role_spec.rb
- spec/unit/run_list_spec.rb
- spec/unit/user_spec.rb
not X = Class.new(Chef::Resource)
This fixes #3524
> Only automatically set resources that do class X < Chef::Resource

- lib/chef/resource_resolver.rb
- spec/unit/resource_resolver_spec.rb
> Add missing require statement in resource_resolver

- MAINTAINERS.md
- MAINTAINERS.toml
ref: https://github.com/chef/chef-rfc/pull/130
> add Joe Miller as LT for OpenBSD

- lib/chef/client.rb
- spec/unit/client_spec.rb
cc @jtimberman @sersut @mcquin
> Exceptions for audits should only get wrapped if audit mode is enabled

- lib/chef/platform/priority_map.rb
Possible fix for https://github.com/chef/chef/issues/3561.
> Re-add #priority.

- MAINTAINERS.md
- MAINTAINERS.toml
I'm back!
Also, I've been getting some PR review requests on Ohai lately. I'd like to be able to review and +1 them officially.
> Proposal to (re-)add myself as a core chef maintainer.

- lib/chef/node_map.rb
- spec/unit/node_map_spec.rb
> Fix issue where blocks were not considered in priority mapping

- lib/chef/knife/bootstrap/templates/chef-full.erb
> Fix some errant bashisms

- lib/chef/knife/bootstrap/templates/chef-full.erb
Added the word "the" and it now reads much better.
> The wording seemed odd.

- MAINTAINERS.toml
I would really rather we split the DSL and Resource machinery in to a component because I'm definitely not able to call myself a maintainer for the "and everything else" part, but waiting to get my patches merged is getting annoying.
> Add myself as a core maintainer.

- lib/chef/run_list/versioned_recipe_list.rb
- spec/unit/run_list/versioned_recipe_list_spec.rb
See #3618 for details. This needs to get back ported to 12.4.1
> 3618 run list mutation issue

- chef-windows.gemspec
> Revert "FFI 1.9.9 is causing segfaults"

- lib/chef/dsl/resources.rb
- spec/integration/recipes/recipe_dsl_spec.rb
> Don't accept multiple parameters in recipe DSL (just name)

- .travis.yml
- appveyor.yml
Removes 12-stable from travis.yml branch filter
Updates appveyor.yml for the 12.4-stable branch
Fixes 2/3 of #3640
> Decommission 12-stable

- lib/chef/http/http_request.rb
"opscode.com" was two domain name changes ago :laughing: 
> Update the URL in user agent string

- spec/functional/win32/service_manager_spec.rb
- spec/spec_helper.rb
> avoid windows service spec unless we're on appveyor

- CHANGELOG.md
- lib/chef/knife/ssl_check.rb
- spec/unit/knife/ssl_check_spec.rb
> Support SNI in 'knife ssl check'.

- MAINTAINERS.md
- MAINTAINERS.toml
> Adding omnibus-chef to core maintainer projects

- lib/chef/mixin/params_validate.rb
- spec/unit/property/validation_spec.rb
> Fix #3692: flatten regex validation array so nested arrays work

- lib/chef/exceptions.rb
- lib/chef/util/windows/net_group.rb
- lib/chef/win32/api.rb
- lib/chef/win32/api/net.rb
- lib/chef/win32/net.rb
- spec/functional/resource/group_spec.rb
This should now be less broken and works on both 32bit and 64 bit.
cc @adamedx @chefsalim @ksubrama @mcquin @smurawski
> Rewrite NetLocalGroup things to use FFI

- CHANGELOG.md
- lib/chef/provider/package/dpkg.rb
- spec/unit/provider/package/dpkg_spec.rb
This is based on @kwilczynski's work in #2434
> Use dpkg-deb directly rather than regex

- lib/chef/provider/ifconfig.rb
- spec/unit/provider/ifconfig_spec.rb
> Use target, not name, if it is specified.

- lib/chef/dsl/reboot_pending.rb
- spec/unit/dsl/reboot_pending_spec.rb
reboot_pending should look for CBS RebootPending instead of RebootRequired
Ref: https://gallery.technet.microsoft.com/scriptcenter/Get-PendingReboot-Query-bdb79542
> Make reboot_pending? look for CBS RebootPending

- CHANGELOG.md
- lib/chef/provider/service/debian.rb
- lib/chef/provider/service/insserv.rb
- lib/chef/provider/service/invokercd.rb
- lib/chef/provider/service/redhat.rb
- lib/chef/provider/service/systemd.rb
- lib/chef/provider/service/upstart.rb
the block to provides can handle this case
> remove use of self.provides?

- CHANGELOG.md
- lib/chef/mixin/params_validate.rb
> Validating is comparing to true instead of ruby truthiness

- lib/chef/util/windows/volume.rb
- lib/chef/win32/api/file.rb
- lib/chef/win32/file.rb
This will let us rip out the windows-pr gem from chef
cc @adamedx @chefsalim @ksubrama @mcquin
> Rewriting volume code to use FFI

- lib/chef/win32/api/net.rb
> Make win32/api/net.rb look nicer

- lib/chef/win32/api/registry.rb
- lib/chef/win32/registry.rb
Enable Registry to use FFI ; convert delete_key_ex to use FFI version of RegDeleteKeyEx API.
> Prep for Registry FFI; Convert RegDeleteKeyEx to FFI

- lib/chef/win32/unicode.rb
> Monkeypatch Win32::Registry#write

- Gemfile
- MAINTAINERS.md
- MAINTAINERS.toml
- tasks/maintainers.rb
> sync maintainers with github

- appveyor.yml
> Add 64 bit testers

- lib/chef/formatters/error_inspectors/compile_error_inspector.rb
Per the discussion at the bottom of https://github.com/chef/chef/pull/3757, doing some further refinement of compile_error_inspector's message regarding frozen objects. Helps further address the original issue https://github.com/chef/chef/issues/3734.
> Further revision for compile errors due to frozen

- lib/chef/config.rb
- lib/chef/platform/query_helpers.rb
- spec/unit/platform/query_helpers_spec.rb
> Don't add win_evt logger when on nano.

- lib/chef/knife/ssh.rb
- spec/functional/knife/cookbook_delete_spec.rb
- spec/functional/knife/ssh_spec.rb
This allows most config options to work with the SSH gateway too. The most important of these is the identity file stuffs.
> Refactor knife ssh options stuff

- lib/chef/policy_builder/policyfile.rb
Also, improve the language around unsupported features/options.
> Remove experimental feature warning for policyfiles

- lib/chef/chef_class.rb
- lib/chef/cookbook_version.rb
- lib/chef/deprecation/provider/remote_directory.rb
- lib/chef/deprecation/warnings.rb
- lib/chef/formatters/base.rb
- lib/chef/property.rb
- lib/chef/resource/file/verification.rb
- spec/unit/property_spec.rb
> Do not prefer default: nil over name_attribute: nil

- lib/chef/formatters/base.rb
https://github.com/chef/chef/issues/3969 has the debugging stream of thought for this.
Ping @chef/client-core (and @jkeiser in particular) for review, but going to merge this ASAP so builds aren't broken over the weekend.
> I think this was a bad search-and-replace, causes an infinite loop.

- CHANGELOG.md
- lib/chef/provider/package/rpm.rb
- spec/unit/provider/package/rpm_spec.rb
See #3671 for discussion
cc: @lamont-granquist
> Use much simpler regex for determining the rpm version

- CONTRIBUTING.md
I accidentally nuked this one in git before it was merged here:
https://github.com/chef/chef/pull/3889
> Fix awkward wording in the contributing doc

- lib/chef/knife/bootstrap/templates/README.md
The other scripts are gone.  Also update the URLs
> Bootstrap doc doesnt match reality

- distro/common/html/knife_cookbook_site.html
- distro/common/man/man1/knife-cookbook-site.1
- lib/chef/cookbook_site_streaming_uploader.rb
- lib/chef/knife/cookbook_create.rb
- lib/chef/knife/cookbook_site_download.rb
- lib/chef/knife/cookbook_site_install.rb
- lib/chef/knife/cookbook_site_share.rb
- lib/chef/knife/search.rb
- lib/chef/knife/ssh.rb
- spec/unit/knife/cookbook_site_share_spec.rb
Also a few tense fixes and some sentences that needed to be capitalized
> Community site -> Supermarket in knife

- lib/chef/property.rb
- spec/unit/property_spec.rb
cc @coderanger (thanks for noticing the default thing!)
> Add ability for default to override name_property

- lib/chef/provider/powershell_script.rb
- spec/functional/resource/powershell_script_spec.rb
- spec/spec_helper.rb
- spec/support/platform_helpers.rb
- spec/support/shared/functional/windows_script.rb
- spec/unit/provider/powershell_script_spec.rb
Nano only supports the `-Command` flag.
> Use -Command flag on Nano

- lib/chef/event_dispatch/dispatcher.rb
- spec/unit/event_dispatch/dispatcher_spec.rb
with different numbers of arguments.
Fixes https://github.com/chef/chef-dk/issues/546
> Fix dispatch when there are different receivers

- lib/chef/knife/ssh.rb
This PR is part of #3959 
I want to recover regression of master to rescue integration testing my plugin. https://circleci.com/gh/higanworks/knife-zero/tree/integration_testedge
> pass ssh_password to session

- lib/chef/knife/cookbook_site_unshare.rb
Hopefully this prevents people from unsharing when they just want to remove the last version.
> Better warning for unsharing

- lib/chef/search/query.rb
- spec/unit/search/query_spec.rb
The start and rows parameter that are passed as part of the search
request are passed directly to Solr on the backend. Results from Solr
may contain deleted nodes no longer in the erchef database.  Erchef will
filter such nodes from the results. Thus, a user may receive fewer rows
than they asked for. Incrementing 'start' only by the number of rows
received will then result in the next Solr response overlapping the
first, which can lead to duplicate results. In the case of a Solr
results page that was completely filtered, it would lead to an infinite
loop.
This commit changes the code to always increment by the requested page
size (args[:rows]) when it is non-nil. Incrementing by the length of the
response set is still wrong in the case when the args[:rows] is nil, but
the server doesn't …
> Fix search result pagination

- Gemfile
- chef-config/chef-config.gemspec
- chef.gemspec
/cc @jkeiser @chef/client-core
> Add gemspec files to allow bundler to run from the gem

- lib/chef/event_dispatch/base.rb
- lib/chef/json_compat.rb
- lib/chef/policy_builder/expand_node_object.rb
- lib/chef/resource_reporter.rb
- lib/chef/run_list/run_list_expansion.rb
- spec/unit/resource_reporter_spec.rb
- spec/unit/run_list/run_list_expansion_spec.rb
Added run list expansion json conversion. Creates a json tree from the run list expansion trace.
Added event to report expanded run list
TODO: Unclear how to test the new event.
> Report expanded run list json tree to reporting

- CHANGELOG.md
- lib/chef/provider/service/solaris.rb
- spec/unit/provider/service/solaris_smf_service_spec.rb
rebase and md files for #3187
closes #3187
> overhaul solaris SMF service provider

- CHANGELOG.md
- lib/chef/provider/user/dscl.rb
- spec/unit/provider/user/dscl_spec.rb
rebase and md files for #3192 
closes #3192
> provider/user/dscl: Set default gid to 20

- CHANGELOG.md
- lib/chef/provider/user/dscl.rb
- spec/unit/provider/user/dscl_spec.rb
rebase and md files for #3193 
closes #3193
> provider/user/dscl: Set "comment" default value

- CHANGELOG.md
- lib/chef/dsl/platform_introspection.rb
- spec/support/shared/unit/platform_introspector.rb
rebase and md files for #3263 
closes #3263
> value_for_platform should use Chef::VersionConstraint::Platform

- CHANGELOG.md
- lib/chef/cookbook_version.rb
rebase and md files for #3450 
closes #3450
> Fix 'knife cookbook show' to work on root files

- MAINTAINERS.md
- MAINTAINERS.toml
I'm requesting to be made a maintainer on the FreeBSD team. Cheers!
> bryant-lippert-maintainer

- lib/chef/knife/ssh.rb
> Fix typo in comment

- CHANGELOG.md
- lib/chef/dsl/declare_resource.rb
- lib/chef/dsl/recipe.rb
- lib/chef/resource_builder.rb
- spec/unit/recipe_spec.rb
- extract to its own mixin so it can be included without
method_missing and the rest of the resources DSL
- add ability to inject different run_context
- add ability to create_if_missing into the resource_collection
> extract declare_resource to a mixin and extend API

- .travis.yml
- spec/functional/resource/ifconfig_spec.rb
- spec/functional/resource/mount_spec.rb
- spec/spec_helper.rb
We have enough travis capacity now to have longer running tasks
> A lot of our tests require sudo

- lib/chef/provider.rb
- spec/integration/recipes/lwrp_inline_resources_spec.rb
> Converge actions all together instead of in action :x (fixes #4124)

- spec/integration/recipes/lwrp_inline_resources_spec.rb
- spec/spec_helper.rb
this reverts the focus and allows all the tests to run again
> focus snuck into a PR

- .travis.yml
\cc @jkeiser @smith @chef/client-maintainers
> Updating the proxy tests config in .travis.yml to export a new env variable we need

- RELEASE_NOTES.md
Add note for OpenSSL 1.0.1q
@chef/client-core @jaym
> Add note for OpenSSL update

- spec/functional/resource/dpkg_package_spec.rb
The exit codes on debian 6 do not match what was expected.
Purging seems to behave differently... metadata is not purged.
We now check the contents of the output to see if the output
has been removed or purged. There are also places where we
dont care if it should be purged or removed... either would
suffice. This case is also represented, and all checks
go through `should_be_purged_or_removed`.
> Fix dpkg specs to run on debian 6

- RELEASE_NOTES.md
- lib/chef/resource.rb
- lib/chef/run_context.rb
- lib/chef/runner.rb
- spec/functional/notifications_spec.rb
- spec/support/shared/integration/integration_helper.rb
Implements https://github.com/chef/chef-rfc/pull/154
> Add immediately_before notification

- lib/chef/http.rb
- spec/unit/api_client/registration_spec.rb
and use it in registration client specs
> expose HTTP options

- RELEASE_NOTES.md
Minor fix - add CHANGELOG link
> Add CHANGELOG link

- DOC_CHANGES.md
Add a note for dsc_resource doc change
@jaym @smurawski @jamescott
> Doc change for dsc_resource

- CHANGELOG.md
- lib/chef/provider/file.rb
- lib/chef/resource/file.rb
- spec/support/shared/unit/provider/file.rb
- spec/unit/resource/cookbook_file_spec.rb
> make file resource use properties

- spec/functional/resource/mount_spec.rb
Use the NameFS filesystem type for the test which works inside both LPARs and WPARs.
@scotthain
> Re-enable AIX mount functional test

- lib/chef/provider/package/windows.rb
- spec/functional/file_content_management/deploy_strategies_spec.rb
- spec/functional/resource/aixinit_service_spec.rb
- spec/functional/resource/dsc_script_spec.rb
- spec/integration/knife/diff_spec.rb
- spec/unit/cookbook/metadata_spec.rb
- spec/unit/cookbook_loader_spec.rb
- spec/unit/encrypted_data_bag_item_spec.rb
- spec/unit/mixin/command_spec.rb
- spec/unit/provider/group/pw_spec.rb
- spec/unit/provider/ifconfig_spec.rb
- spec/unit/provider/mdadm_spec.rb
- spec/unit/provider/mount/mount_spec.rb
- spec/unit/provider/package/yum_spec.rb
- spec/unit/provider/service/gentoo_service_spec.rb
- spec/unit/provider/service/openbsd_service_spec.rb
- spec/unit/resource_reporter_spec.rb
- spec/unit/resource_spec.rb
fixes the following offenses:
46   Lint/EndAlignment
21   Lint/BlockAlignment
3    Lint/SpaceBeforeFirstArg
1    Lint/DefEndAlignment
> fix some lint cops

- lib/chef/provider/package/chocolatey.rb
- spec/unit/provider/package/chocolatey_spec.rb
when putting together functional tests for #4377 I noticed a couple problems:
* bogus packages were allowed to be installed when using an alternate source
* bogus versions were allowed to be installed regardless of source
This ensures that candidate versions only include pinned versions when pinning to a specific version and that we assert candidates exist when using an alternate source.
> assert candidates exist for alternate sources and when pinning versions

- lib/chef/node.rb
fixes loading brand new node objects from json
> don't blow up when json object has no recipes

- chef-config/lib/chef-config/package_task.rb
- lib/chef/chef_fs/file_system/chef_repository_file_system_cookbook_dir.rb
- lib/chef/provider/package/windows.rb
Style/SignalException - 3
@chef/client-maintainers
> Correct uses of fail to raise

- lib/chef/user_v1.rb
- lib/chef/win32/registry.rb
- spec/unit/mixin/securable_spec.rb
fixes:
Lint/AmbiguousOperator
Lint/DuplicateMethods
> yet more lint cops

- omnibus/Gemfile.lock
/cc @chef/engineering-services
> Bump omnibus

- .travis.yml
- Gemfile
- lib/chef/provider/package/chocolatey.rb
- spec/functional/resource/chocolatey_package_spec.rb
- spec/unit/provider/package/chocolatey_spec.rb
autocorrects some merges that will be broken when the next
chefstyle is released.
also runs chefstyle after the travis tests, because i'd rather know
how the code is broken rather than how its not pretty.
> fix chefstyle failures

- kitchen-tests/Gemfile
i'm a bit surprised this still even works at all..
> let kitchen-appbundle-updater float

- Gemfile
- lib/chef/chef_fs/chef_fs_data_store.rb
- lib/chef/chef_fs/file_system/chef_server/cookbook_artifact_dir.rb
- lib/chef/chef_fs/file_system/chef_server/cookbook_artifacts_dir.rb
- lib/chef/chef_fs/file_system/repository/chef_repository_file_system_cookbook_artifact_dir.rb
- lib/chef/chef_fs/file_system/repository/chef_repository_file_system_root_dir.rb
- spec/integration/knife/download_spec.rb
- spec/integration/knife/upload_spec.rb
bunch of merges over the weekend need re-fixing again.
seems like pointing at master of chefstyle is probably a good idea to
start making people fix their code before merging.
> another chefstyle catchup + pull master

- lib/chef/exceptions.rb
this is almost always a real networking issue and there is no bug in
chef-client.
> add a comment on exception triggers

- omnibus/Gemfile.lock
- omnibus/config/projects/chef.rb
implements first part of https://github.com/chef/chef-rfc/blob/master/rfc063-omnibus-chef-native-gems.md
> add nokogiri to omnibus-chef

- lib/chef/server_api.rb
and note in rspec that we want these gone in 13
> add get_rest etc calls to ServerAPI

- spec/functional/resource/chocolatey_package_spec.rb
Add choco to the path if it isn't already there.
\cc @mwrock @jaym
> Sometimes chocolately doesn't appear on the path

- Gemfile
- omnibus/Gemfile
- omnibus/Gemfile.lock
- spec/functional/resource/group_spec.rb
- spec/functional/resource/user/useradd_spec.rb
It cannot have uppercase users.
> Test failures for the Cisco Nexus 7 & Solaris platform in Manhattan

- CBGB.md
- CBGB.toml
- Rakefile
- tasks/cbgb.rb
Includes rake task to generate markdown from toml
> Add CBGB to the repository

- CBGB.md
- tasks/cbgb.rb
> Governers -> Governors

- acceptance/cookbook-git/.kitchen.ec2.yml
t1.micros are also beyond terrible for performance.
> debian-6 is EOL next month

- lib/chef/formatters/error_inspectors/api_error_formatting.rb
- lib/chef/formatters/error_inspectors/cookbook_resolve_error_inspector.rb
- lib/chef/formatters/error_inspectors/cookbook_sync_error_inspector.rb
- lib/chef/formatters/error_inspectors/node_load_error_inspector.rb
- lib/chef/formatters/error_inspectors/registration_error_inspector.rb
- lib/chef/formatters/error_inspectors/run_list_expansion_error_inspector.rb
- spec/unit/formatters/base_spec.rb
i think this still misses the biggest EOFError culprit which is the
node.save at the end, but we don't seem to have a node_save_failed
event to hook.
> adds EOFError message to handlers

- ci/verify-chef.sh
The if statement was always being evaluated to true.
> Fix sh spacing issues

- .gitignore
- omnibus/.gitignore
- omnibus/.kitchen.yml
- omnibus/Gemfile.lock
- omnibus/config/projects/chef-fips.rb
- omnibus/config/projects/chef.rb
- tasks/cbgb.rb
This allows master to build at https://github.com/chef/omnibus-software/pull/556
> Allow recent omnibus-software ruby version convention.

- omnibus/Gemfile.lock
> Bump omnibus to try harder to see if netfetcher is breaking

- spec/functional/shell_spec.rb
tests won't run in isolation with it.
> add spec helper

- .travis.yml
Reverts chef/chef#4477
My test systems are upgraded and good to go!
> Revert "Remove poise from the test matrix"

- acceptance/Gemfile
Fix chef acceptance failure
@chef/client-core @jkeiser @btm @sersut
> Remove local chef

- lib-backcompat/chef/chef_fs/file_system/acl_entry.rb
- spec/unit/lib_backcompat_spec.rb
Fixes https://github.com/chef/chef-server/issues/724
> Add missing acl_entry backwards compatibility "require"

- chef.gemspec
- omnibus/Gemfile.lock
- omnibus/config/projects/chef.rb
removes pry as a dep of chef directly because it was never a dep of
chef.
> add pry, pry-byebug, pry-remote to omnibus-chef

- lib/chef/mixin/params_validate.rb
- spec/unit/property_spec.rb
Right now, this is failing:
```
class X < Chef::Resource
resource_name :x
AB = property_type(is: [:a, :b])
property :abc, [AB, :c]
end
x 'hi' do
abc :c
end
```
This makes it succeed. Also tests interaction with `nil` warnings.
> Allow multiple property_types in `is`

- CHANGELOG.md
- RELEASE_NOTES.md
- omnibus/Gemfile
- omnibus/config/projects/chef.rb
@chef/maintainers Calling on all maintainers to update the `RELEASE_NOTES.md` and `DOC_CHANGES.md` in this branch with any explanations or expansions on features going out in this release.
> 12.7 Release Preperations

- spec/unit/provider/package/rubygems_spec.rb
These tests used to take 390ish seconds to run in appveyor
> make rubygems unit specs unit like

- omnibus/config/projects/chef.rb
these versions pass in manhattan
> bump bunder + rubygems

- lib/chef/application/client.rb
- lib/chef/application/solo.rb
- lib/chef/chef_fs/data_handler/data_handler_base.rb
- lib/chef/monkey_patches/webrick-utils.rb
- lib/chef/node/attribute.rb
- spec/unit/provider/deploy_spec.rb
- spec/unit/resource/dsc_resource_spec.rb
second round of autofixing for some reason...
> autofixing some missed cops

- acceptance/basics/test/integration/chef-current-install/serverspec/chef_client_spec.rb
- acceptance/basics/test/integration/chef-current-install/serverspec/spec_helper.rb
@chefsalim think these came in through your PR
> autofixing busted cops on master

- lib/chef/cookbook/remote_file_vendor.rb
- lib/chef/knife/cookbook_show.rb
- lib/chef/knife/cookbook_site_download.rb
- spec/unit/knife/cookbook_show_spec.rb
- spec/unit/knife/cookbook_site_download_spec.rb
> Use a streaming request to download cookbook

- acceptance/README.md
Update the README for chef acceptance
> Update README to reflect more config options

- lib/chef/knife.rb
- lib/chef/knife/client_create.rb
- lib/chef/knife/client_edit.rb
- lib/chef/knife/core/node_editor.rb
- lib/chef/knife/core/ui.rb
- lib/chef/knife/data_bag_edit.rb
- lib/chef/knife/environment_create.rb
- lib/chef/knife/key_create.rb
- lib/chef/knife/key_edit.rb
- lib/chef/knife/node_create.rb
- lib/chef/knife/osc_user_create.rb
- lib/chef/knife/osc_user_edit.rb
- lib/chef/knife/role_create.rb
- lib/chef/knife/user_create.rb
- lib/chef/knife/user_edit.rb
- spec/unit/knife/client_create_spec.rb
- spec/unit/knife/client_edit_spec.rb
- spec/unit/knife/core/node_editor_spec.rb
- spec/unit/knife/core/ui_spec.rb
- spec/unit/knife/data_bag_edit_spec.rb
- spec/unit/knife/environment_create_spec.rb
- spec/unit/knife/environment_edit_spec.rb
- spec/unit/knife/key_create_spec.rb
- spec/unit/knife/key_edit_spec.rb
- spec/unit/knife/osc_user_create_spec.rb
- spec/unit/knife/osc_user_edit_spec.rb
- spec/unit/knife/role_create_spec.rb
- spec/unit/knife/role_edit_spec.rb
- spec/unit/knife/user_create_spec.rb
- spec/unit/knife/user_edit_spec.rb
rather than guessing through json autoinflation
> tell knife's edit_data what the object is

- lib/chef/resource/group.rb
- spec/unit/resource/group_spec.rb
Fixes #4294, fixes #4322 cc @chef/client-core
Replaces #4322
> Split group members on commas

- lib/chef/knife/cookbook_upload.rb
fixes #4350, cc @chef/client-core
> remove bogus recalculation of cookbook upload failures

- lib/chef/http.rb
- spec/unit/http_spec.rb
This is a fix up of #2752 with added tests.
Fixes #2752, fixes #2171 cc @chef/client-core
> Make sure we have a valid object before calling close!

- lib/chef/knife/core/bootstrap_context.rb
fixes failing tests and cleans up the logic a little.
fixes #2865 fixes #3866
> bugfix #2865 check for validation_key

- lib/chef/knife/data_bag_show.rb
- spec/unit/knife/data_bag_show_spec.rb
https://github.com/chef/chef/issues/4154 resolution as per comments
> Update to Log Level when showing unencrypted databag

- lib/chef/file_content_management/tempfile.rb
- spec/unit/file_content_management/tempfile_spec.rb
Fixes #4376 cc @chef/client-core
> Prepend chef to tempfile name

- lib/chef/provider/package/windows.rb
- spec/unit/provider/package/windows_spec.rb
A regression introduced [here](https://github.com/chef/chef/commit/09df8eea8bdbca4b7f1f0db43033d8d473860131) has caused `exe` based windows packages to fail when pulling from a remote source. This is because of the added `define_resource_requirements` method which ensures that a `source` is included for `exe` packages. 
This is called before converging and therefore also before any remote source is downloaded. If the source is remote, we do not download it (and rightly so) until we determine that the package is elligible to be installed. However, in order to determine the type of package (in this case if the package is not an `msi`), we must beable to read the package installer file. If we do not have that locally, this fails with an error stating that the file cannot be found.
However, …
> fixes exe package downloads

- lib/chef/provider/user/useradd.rb
- spec/functional/resource/user/useradd_spec.rb
- spec/support/shared/unit/provider/useradd_based_user_provider.rb
This reverts commit 94494e761763b877c3ef3b52eee9ac9df2186340, reversing
changes made to a95a87d50c9e5af2fbd583afcf972880656d1a4b.
> Revert "Merge pull request #4465 from artursitarski/change-shell-for-locked-user"

- Rakefile
> guard against changelog generator not being installed

- .travis.yml
- chef-config/lib/chef-config/config.rb
- chef.gemspec
- kitchen-tests/.kitchen.travis.yml
- lib/chef/cookbook/cookbook_collection.rb
- lib/chef/cookbook/gem_installer.rb
- lib/chef/cookbook/metadata.rb
- lib/chef/event_dispatch/base.rb
- lib/chef/formatters/doc.rb
- lib/chef/policy_builder/expand_node_object.rb
- lib/chef/policy_builder/policyfile.rb
- lib/chef/provider/package/rubygems.rb
- spec/integration/client/client_spec.rb
- spec/unit/cookbook/metadata_spec.rb
- spec/unit/policy_builder/policyfile_spec.rb
Implements RFC-60 'gem' keyword in metadata.rb
> RFC-060 gem metadata MVP

- chef-config/lib/chef-config/path_helper.rb
- lib/chef/application/apply.rb
- lib/chef/application/windows_service.rb
- lib/chef/client.rb
- lib/chef/config_fetcher.rb
- lib/chef/cookbook_loader.rb
- lib/chef/cookbook_site_streaming_uploader.rb
- lib/chef/deprecation/warnings.rb
- lib/chef/file_access_control/windows.rb
- lib/chef/http/validate_content_length.rb
- lib/chef/knife/cookbook_bulk_delete.rb
- lib/chef/knife/cookbook_metadata.rb
- lib/chef/knife/cookbook_site_download.rb
- lib/chef/knife/core/custom_manifest_loader.rb
some UselessAssignments identified by chefstyle
> fix some UselessAssignment cases

- Gemfile
cc @danielsdeleo @chef/client-core
> ensure we always can rake

- lib/chef/provider/group/suse.rb
rework the set_members method so duplicates are avoided ( #4689)
> fix for https://github.com/chef/chef/issues/4689

- omnibus/config/projects/chef.rb
> use rb-readlin on unix as well as windows

- acceptance/.shared/kitchen_acceptance/.kitchen.ec2.yml
@sersut @adamedx this look right?
> Change acceptance test tag so old instances will be reaped

- Gemfile
- appveyor.yml
- lib/chef/win32/registry.rb
- omnibus/config/projects/chef.rb
> Bump omnibus ruby to ruby 2.2.4

- MAINTAINERS.md
- MAINTAINERS.toml
- Added JJ as a maintainer for c-p, specificly c-p-fog.
> Added JJ as maintainer for c-p

- lib/chef/knife/cookbook_create.rb
- spec/unit/knife/cookbook_create_spec.rb
Better markdown
Better requirements section
> Improve the docs generated by knife cookbook create

- DOC_CHANGES.md
> Update DOC_CHANGES for chef 12.9

- lib/chef/knife/ssh.rb
Missed case when merging https://github.com/chef/chef/pull/4767
@tyler-ball @chef/client-core
> Convert timeout config to integer

- omnibus/config/projects/chef.rb
Related PR: https://github.com/chef/omnibus-software/pull/646
@sersut  @chef/engineering-services
> add omnibus license metadata

- omnibus/.gitignore
- omnibus/.kitchen.yml
Similar to changes in https://github.com/chef/chef-dk/pull/797
/cc @jkeiser @chef/workflow @chef/client-windows @chef/engineering-services
> Omnibus Build Lab fixes/improvements

- lib/chef/dsl/declare_resource.rb
- lib/chef/provider.rb
- lib/chef/recipe.rb
- lib/chef/resource_collection.rb
- lib/chef/resource_collection/resource_list.rb
- lib/chef/resource_collection/resource_set.rb
- spec/unit/dsl/declare_resource_spec.rb
- spec/unit/recipe_spec.rb
- spec/unit/resource_collection_spec.rb
deprecates chef_rewind functionality completely and adds a few
more features
> add better resource manipulation API

- Gemfile
- Gemfile.lock
- version_policy.rb
(we have a lockfile now, so we are protected against inadvertent updates)
> Update changelog generator to latest

- lib/chef/http/json_input.rb
- lib/chef/knife.rb
- lib/chef/provider/env/windows.rb
- lib/chef/provider/package/windows.rb
- spec/functional/resource/group_spec.rb
- spec/unit/provider/powershell_script_spec.rb
> update to latest chefstyle - fix casecmp

- omnibus/config/projects/chef.rb
- pkg.rb
@chef/client-core @chef/engineering-services
> Update override path

- .travis.yml
- tasks/bin/run_chef_tests
make it easier to see if we have style errors or code errors
> run chefstyle in parallel, once

- spec/unit/chef_fs/config_spec.rb
> add tests for ChefFS path formatting

- Gemfile.lock
- chef-config/lib/chef-config/config.rb
- chef-config/lib/chef-config/fips.rb
- chef-config/spec/unit/config_spec.rb
- chef-config/spec/unit/fips_spec.rb
This essentially refactors code from #4841 and https://github.com/chef/ohai/pull/803 into `ChefConfig` the next step will be to refactor ohai code out of ohai and consume this instead.
> Adds a system check for fips enablement and runs in fips mode if enabled

- omnibus/config/software/chef-complete.rb
merge after https://github.com/chef/omnibus-software/pull/663 is merged
> Updating chef-complete to include gem-permissions update dependency in omnibus-software

- tasks/changelog.rb
> remove issues from changelog generator

- lib/chef/provider/osx_profile.rb
Note: I am a Facebook employee and PhilD will do the final merge.
Checks for nil on the os x profile provider.
> fix os x profile provider for nil

- lib/chef/knife/cookbook_show.rb
- spec/unit/knife/cookbook_show_spec.rb
> Load cookbook versions correctly for knife

- CHANGELOG.md
Adding the changelog here for posterity.
> Update changelog for 12.10.24 release

- ci/verify-chef.sh
A temporary disabling of jenkins acceptance tests
> exit 0 -- its how acceptance works

- lib/chef/dsl/core.rb
- lib/chef/dsl/recipe.rb
- lib/chef/dsl/universal.rb
- lib/chef/node.rb
- lib/chef/provider/lwrp_base.rb
- lib/chef/resource.rb
this is for DSL methods that get mixed in everywhere.
> create 'universal' DSL

- NOTICE
- ROADMAP.md
It's not a roadmap if you did it already.
> Opscode -> Chef and remove old roadmap items

- .travis.yml
> Remove old webhooks from Travis

- .travis.yml
- kitchen-tests/.kitchen.travis.yml
- kitchen-tests/cookbooks/base/attributes/default.rb
- kitchen-tests/cookbooks/base/recipes/default.rb
- kitchen-tests/test/integration/webapp/default_spec.rb
adds debian, centos-7 and fedora-23
> add a few more distros to kitchen testing

- lib/chef/application/solo.rb
- spec/unit/application/solo_spec.rb
> Ensure recipe-url works right in solo

- spec/unit/resource/dsc_script_spec.rb
just the functional one.
pending <> skip :)  
Learned something today.
> Did not need to pend dsc_script ps_credential unit test

- ci/bundle_install.sh
- ci/dependency_update.sh
- ci/version_bump.sh
- ci/version_show.sh
when bumping version and updating dependencies
> Install fewer binary dependencies and dependencies in general

- MAINTAINERS.toml
Spoke with Nathen Harvey about being added as a maintainer.
> Adding myself as a Chef Provisioning Maintainer

- lib/chef/knife/cookbook_create.rb
- spec/unit/knife/cookbook_create_spec.rb
> Deprecate `knife cookbook create` in favor of `chef generate cookbook`.

- lib/chef/provider/package/rubygems.rb
> correctly select current gem version

- chef-config/lib/chef-config/config.rb
> Fix #5078 using cwd parameter instead of Dir.pwd

- lib/chef/node/common_api.rb
- spec/unit/node/vivid_mash_spec.rb
- spec/unit/node_spec.rb
> Fix #5094 node.default_unless issue in 12.12.13

- lib/chef/decorator/unchain.rb
- lib/chef/node/attribute.rb
- spec/unit/node_spec.rb
> add back method_missing support to set_unless

- acceptance/.shared/kitchen_acceptance/libraries/kitchen.rb
- ci/verify-chef.sh
Modified:  I'm turning off all acceptance tests for now because they fail intermittently.
> Save acceptance test logs when failing

- lib/chef/knife/bootstrap.rb
This fixes https://github.com/chef/chef/issues/5113
> Ensure that the valid option is given back to the option parser

- lib/chef/knife/cookbook_site_share.rb
- spec/unit/knife/cookbook_site_share_spec.rb
Bonus fix for a hardcoded URL.
Fixes: #5088, #5092, #5095
> The user must specify a category for a new cookbook

- Gemfile
- Gemfile.lock
- chef.gemspec
See https://github.com/chef/chef-dk/pull/937
and https://github.com/chef/chef/issues/5116
> Install nokogiri and pin mixlib-cli

- lib/chef/application.rb
- lib/chef/provider/file.rb
- spec/spec_helper.rb
- spec/support/platform_helpers.rb
- spec/support/shared/unit/provider/file.rb
also wires up file providers to reload /etc/resolv.conf when it changes.
> replace glibc resolver with ruby resolver

- lib/chef/dsl/declare_resource.rb
- spec/unit/dsl/declare_resource_spec.rb
/cc @lamont-granquist @jkeiser @thommay 
This implements https://github.com/thommay/chef-rewind/commit/b69c9a510f1e7a85132dff0ee26fd883192ea12d for the new fancy API.
> Also clear notifications when deleting a resource.

- lib/chef/chef_fs/file_system/repository/acls_dir.rb
Ensure that we correctly write to them and manage them.
> Root ACLs are a top level json file not a sub-directory

- lib/chef/chef_fs/chef_fs_data_store.rb
- lib/chef/chef_fs/file_system/repository/base_file.rb
- lib/chef/chef_fs/file_system/repository/chef_repository_file_system_cookbook_entry.rb
- lib/chef/chef_fs/file_system/repository/directory.rb
- lib/chef/chef_fs/file_system_cache.rb
- spec/unit/chef_fs/file_system/repository/directory_spec.rb
> Invalidate the file system cache on deletion

- lib/chef/provider/cron.rb
- spec/functional/resource/cron_spec.rb
- spec/unit/provider/cron_spec.rb
> Support setting an empty string for cron attrs

- tasks/bundle.rb
> Change recommended by @jkeiser to make single gem updates work correctly.

- lib/chef/application.rb
> Log cause chain for exceptions

- Gemfile.lock
- acceptance/Gemfile.lock
- kitchen-tests/Gemfile.lock
- omnibus/Gemfile.lock
> Bump dependencies to bring in Ohai 8.18

- omnibus/Gemfile.lock
Force push last night took away the commit we were locked to
> Bump omnibus-software/ksubrama/ruby23

- lib/chef/application.rb
- lib/chef/provider/file.rb
- spec/spec_helper.rb
- spec/support/platform_helpers.rb
- spec/support/shared/unit/provider/file.rb
Fixes #5141. This reverts commit e8877cd363642ed6757c48d1ed5ab35509d87e22, reversing
changes made to 162d988d3bcfce2773ef2831fa33e416f53731f6.
> Revert "Merge pull request #5123 from chef/lcg/resolv-replace"

- acceptance/basics/test/integration/helpers/serverspec/Gemfile
- acceptance/data-collector/test/integration/helpers/serverspec/Gemfile
- acceptance/fips/test/integration/fips-integration/serverspec/Gemfile
- spec/support/chef_helpers.rb
- spec/unit/knife/data_bag_from_file_spec.rb
- spec/unit/provider/remote_directory_spec.rb
I want to commit these separately in an attempt to minimize the differences in the Ruby 2.3 branch.
> Changes that get Jenkins running against Ruby 2.3

- spec/tiny_server.rb
Sometimes when a jenkins slave aborts a build during functional tests when we are using the rack based `TinyServer`, future builds die on that slave during http server based tests. The aborted run has not completed its shutdown and therefore is still listening for HTTP requests on the expected port. So in this state the subsequent run thinks its `TinyServer` is ready but tests fail due to 500 errors returned from the server (probably because it is shutting down) and then the subsequent run crashes when it tries to shutdown its own unstarted server.
This PR grabs the `Webrick::HTTPServlet` yielded by Rack's `run` call which would fail if run fails and checks for that to see if its server has started rather than the parent `Rack::Server` which is likely to be present even in a failed `run` …
> Wait until inner webrick http server is confirmed running

- spec/integration/client/client_spec.rb
> omit this chef-provisioning test

- lib/chef/cookbook/cookbook_version_loader.rb
In Ruby 2.3 on Windows, `Find.find("x/")` will not traverse `x` if it is a symlink (while it does on other platforms). This fixes that to be consistent across platforms.
> Fix cookbook upload of symlinked cookbooks in Ruby 2.3 on Windows

- CONTRIBUTING.md
- MAINTAINERS.md
- MAINTAINERS.toml
- README.md
The docs were getting a bit dated
> Update docs for Slack and our new release cycle

- spec/functional/resource/group_spec.rb
- spec/functional/resource/user/dscl_spec.rb
- spec/functional/resource/user/useradd_spec.rb
- spec/functional/resource/windows_service_spec.rb
> fix omnibus test breaks

- tasks/bin/bundle-platform
- tasks/bin/bundler_patch.rb
This is a temporary fix until bundler 1.14 releases see https://github.com/bundler/bundler/issues/4896
> Add monkey patch to fix bundle locks for platforms

- spec/functional/resource/user/useradd_spec.rb
> fixed CHEF-2205 so fix the func test

- spec/functional/resource/user/useradd_spec.rb
try to document it a bit better so i don't accidentally delete it
again.
> fix the useradd test filters

- lib/chef/mixin/shell_out.rb
- lib/chef/provider/package.rb
- lib/chef/provider/user.rb
- lib/chef/provider/user/linux.rb
- lib/chef/resource/user/linux_user.rb
- spec/functional/resource/user/useradd_spec.rb
- spec/support/shared/unit/provider/useradd_based_user_provider.rb
- spec/unit/provider/user/linux_spec.rb
> Rewrite linux useradd provider

- lib/chef/provider/service/upstart.rb
- spec/unit/provider/service/upstart_service_spec.rb
> Use upstart goal state as service status

- Gemfile
- Gemfile.lock
- acceptance/Gemfile.lock
> Chefspec 5.0 is out. Remove fetching from git master

- lib/chef/resource/yum_package.rb
> Fix flush_cache issues in yum_package

- lib/chef/provider/osx_profile.rb
- spec/unit/provider/osx_profile_spec.rb
Adds support for profiles with spaces in the identifiers. Not great to use spaces, but Apple supports it, so we must as well.
> Added fix for spaces in profile identifiers

- kitchen-tests/cookbooks/base/recipes/packages.rb
- lib/chef/provider/package/rubygems.rb
> fix gem_package regression in master

- lib/chef/provider/package/windows/exe.rb
- spec/unit/provider/package/windows/exe_spec.rb
Fix for issue https://github.com/chef/chef/issues/4361
> Added timeout during removing of windows package

- spec/integration/solo/solo_spec.rb
there's a WONTFIX closed bug in ruby-lang.org on this bug:
https://bugs.ruby-lang.org/issues/10583
they seem to be favoring speed over usability with the result
that if you're doing I/O synchronization (like our run_lock?)
inside of a Process.spawn chain like this that you have to
wrap the spawn calls inside of threads.
probably a best practice to wrap every spawn call with a
Thread.
this probably also explains why we had the silly-long 20
second timeout?
> use threads to workaround Process.spawn buginess in chef-solo unit test

- lib/chef/knife.rb
> readability improvements to options parsing code

- lib/chef/provider/link.rb
- spec/functional/resource/link_spec.rb
- spec/unit/provider/link_spec.rb
> Added code to handle deletion of directories on Windows that are symlinks.

- lib/chef/provider/package/rubygems.rb
- spec/unit/provider/package/rubygems_spec.rb
Hi all. This should fix #4955.
> Fixes GH-4955, allowing local gems with remote dependencies

- lib/chef/provider/user/linux.rb
- lib/chef/resource/user.rb
- lib/chef/resource/user/linux_user.rb
- spec/unit/provider/user/dscl_spec.rb
- spec/unit/provider/user/linux_spec.rb
- spec/unit/provider/user/pw_spec.rb
even though i violently disagree that this is correct behavior and we're
just going to break everyone in one massive go when we hit Chef 13.
> revert supports[:manage_home] behavior

- lib/chef/provider/registry_key.rb
- spec/functional/resource/registry_spec.rb
- spec/unit/provider/registry_key_spec.rb
Fix for issue https://github.com/chef/chef/issues/5104, similiar issue occurs for additional registry types, fixed those also.
> Fix for idempotent issue for some registry types in registry_key resource

- .gitignore
- acceptance/README.md
Format the markdown and expand on some things I ran into while going through the process
> Update acceptance docs

- lib/chef/mixin/checksum.rb
- lib/chef/provider/file.rb
- lib/chef/provider/package/windows.rb
- spec/unit/mixin/checksum_spec.rb
- spec/unit/provider/package/windows_spec.rb
> Fixed undefined short_cksum method issue and checksum in uppercase issue for windows_package resource.

- lib/chef/knife/core/generic_presenter.rb
- spec/unit/knife/core/ui_spec.rb
> fix method_access and array handling in node presenter

- .travis.yml
We're not going to be building this again
> Remove 10_stable from the branches to build

- Gemfile.lock
- acceptance/Gemfile.lock
- kitchen-tests/Gemfile.lock
- omnibus/Gemfile.lock
necessary to get travis green again
> update deps, pull in chefspec

- lib/chef/provider/remote_file/content.rb
- spec/unit/provider/remote_file/content_spec.rb
w.r.t. https://github.com/chef/chef/issues/5286
> Handling Errno::ETIMEDOUT

- lib/chef/util/dsc/local_configuration_manager.rb
- spec/unit/util/dsc/local_configuration_manager_spec.rb
w.r.t https://github.com/chef/chef/issues/4534
> Invalid `dsc_scripts` should fail the run

- lib/chef/exceptions.rb
- lib/chef/provider/registry_key.rb
- lib/chef/resource/registry_key.rb
- spec/functional/resource/registry_spec.rb
- spec/unit/exceptions_spec.rb
- spec/unit/provider/registry_key_spec.rb
- spec/unit/resource/registry_key_spec.rb
> Allow deletion of registry_key without the need for users to pass data key in values hash.

- CONTRIBUTING.md
Paired with @tas50 to update the contributing process document for clarity.
> Updates to the Contributing process document

- lib/chef/resource/yum_repository.rb
Fixes https://github.com/chef/chef/issues/5397
> Set yum_repository gpgcheck default to true

- CONTRIBUTING.md
- README.md
Swap out the CLA text for DCO text plus a few other minor fixes and updates links for the readme while I'm doing copy stuff.
> Update contributing docs for the DCO

- lib/chef/server_api.rb
- spec/unit/server_api_spec.rb
> Allow raw_key to override the configured signing_key

- spec/unit/resource/apt_update_spec.rb
Make sure on non-linux without running which we still end up with a no-op
> Test apt_update on non-linux behavior

- lib/chef/provider/user/solaris.rb
- spec/unit/provider/user/solaris_spec.rb
Fixes #5403.
Ping @chef/client-solaris for review.
> Fix solaris handling for useradd -m/-M behavior

- kitchen-tests/.kitchen.travis.yml
- kitchen-tests/Berksfile.lock
> Fix centos 6 kitchen tests with chef-client cookbook 6.0.0

- omnibus/Gemfile.lock
> Update omnibus pinning to pull in Solaris 11 pkg fix

- lib/chef/cookbook/file_system_file_vendor.rb
- spec/unit/cookbook/file_vendor_spec.rb
> Fix for "Chefspec template rendering fails when cookbook_name != directory name"

- Rakefile
> small change to test bump bot

- lib/chef/knife/ssh.rb
> kinfe ssh: use the command line prompt for sudo if set

- RELEASE_NOTES.md
> Updated release notes for cab_package resource and provider

- CHANGELOG.md
Update changelog for upcoming release.
/cc @mwrock
> Rhass/changelog 12.15

- lib/chef/resource.rb
see https://github.com/chef/chef/pull/5443#issuecomment-253279021
> Core: make delayed_action argument mandatory, remove misleading ivar introduced in PR that added delayed_action

- omnibus/Gemfile.lock
@mwrock pending success of http://manhattan.ci.chef.co/job/angrychef-build/6/
> Cherry pick omnibus commit

- lib/chef/mixin/powershell_out.rb
- spec/unit/mixin/powershell_out_spec.rb
Fix for https://github.com/chef/chef/issues/5049
Re-worked changes as suggested by @mwrock : https://github.com/chef/chef/pull/5420
> Fixed double quotes issue in powershell_out

- omnibus/Gemfile.lock
Bump omnibus deps to include cherry-picked changes from omnbus for s390x support.
/cc @chef/client-core
> Bump omnibus deps once more.

- lib/chef/knife.rb
- spec/integration/knife/data_bag_create_spec.rb
> [Knife] Fix deprecation warning when creating data bag items

- acceptance/.shared/kitchen_acceptance/.kitchen.ec2.yml
Update tags created in EC2 by the  Chef Acceptance suite for compliance with Chef internal tagging standards.
Internal issue COOL-541
> Update EC2 tags for internal standards compliance.

- lib/chef/application/client.rb
- lib/chef/application/solo.rb
- lib/chef/provider/package/windows/exe.rb
- lib/chef/provider/package/windows/msi.rb
- spec/spec_helper.rb
- spec/unit/provider/deploy_spec.rb
these should also pass on the current engine as well
> fixes for rubocop 0.44.1 engine

- lib/chef/provider/group/suse.rb
- spec/functional/resource/user/useradd_spec.rb
- spec/unit/provider/group/suse_spec.rb
With the recent addition of SLES 11.4 and SLES 12.1 builders/testers to our internal build matrix, we have uncovered some bugs / false assumptions about the behavior of these two systems. This change updates our code base to address those issues.
Internal issue COOL-597
> Address test failures in SUSE 11.4 and 12.1

- CHANGELOG.md
- chef-config/lib/chef-config/config.rb
- distro/common/html/knife_bootstrap.html
- distro/common/man/man1/README.md
- distro/common/man/man1/knife-client.1
- lib/chef/chef_fs/file_system/chef_server/versioned_cookbook_dir.rb
- lib/chef/dsl/core.rb
- lib/chef/dsl/declare_resource.rb
- lib/chef/dsl/method_missing.rb
- lib/chef/dsl/recipe.rb
- lib/chef/dsl/universal.rb
- lib/chef/http.rb
- lib/chef/mixin/shell_out.rb
- lib/chef/provider/ruby_block.rb
- lib/chef/resource/file.rb
- omnibus/README.md
- spec/support/shared/integration/app_server_support.rb
- spec/unit/http_spec.rb
- spec/unit/knife/core/gem_glob_loader_spec.rb
- spec/unit/node_spec.rb
- spec/unit/provider/remote_file/content_spec.rb
Fix copyrights and update a few more Opscode references to Chef
> Fix copyrights and update a few more Opscode references to Chef

- lib/chef/provider/package.rb
- spec/unit/provider/package/windows_spec.rb
allows subclasses to use_inline_resources (hab_package
will most likely want this)
> Core: set use_inline_resources in package superclass

- MAINTAINERS.md
- MAINTAINERS.toml
> Add myself as a Maintainer on debian, ubuntu, suse, test tools and core

- lib/chef/provider/package.rb
- lib/chef/provider/package/apt.rb
- lib/chef/provider/package/yum.rb
- lib/chef/provider/package/zypper.rb
- lib/chef/resource/package.rb
- spec/unit/provider/package/apt_spec.rb
- spec/unit/provider/package/yum_spec.rb
- spec/unit/provider/package/zypper_spec.rb
- spec/unit/provider/package_spec.rb
This introduces package locking for the apt, yum and zypper package providers.
> package locking for apt, yum and zypper

- DOC_CHANGES.md
- RELEASE_NOTES.md
add release notes for attribute_changed, also deletes the doc_changes since we're not doing that any more.
> update docs for attribute_changed

- RELEASE_NOTES.md
- chef-config/lib/chef-config/config.rb
- chef-config/spec/unit/config_spec.rb
- lib/chef/data_collector.rb
- spec/support/shared/context/client.rb
- spec/unit/data_collector_spec.rb
- Allow the Chef Automate data collector to authenticate using signed headers with the client key.
- Attempt to automatically configure the data collector when running in client-server mode
- Token auth still available for either mode if configured
- Check for the presence of both the data collector URL and token to enable the collector in solo mode.
Internal Chef Ticket
> Enable Signed Header Auth for Data Collector, and Configure the Data Collector Automatically

- acceptance/data-collector/test/integration/default/serverspec/default_spec.rb
- lib/chef/data_collector.rb
- spec/unit/data_collector_spec.rb
Fixes more issues with data collector:
* messages were double JSON encoded for run complete events
* acceptance tests were not updated for new `deprecations` field
* acceptance tests were overly strict given the purpose of the tests and the difficulty of debugging them.
Failures of chef-test (acceptance) in the pipeline.
> Fix data collector acceptance

- .gitignore
Similar to the issue uncovered in chef/chef-server#997 which breaks
Bundler.
/cc @danielsdeleo @rhass
> Remove vendored git submodules

- spec/functional/resource/rpm_spec.rb
scientific linux, oracle, etc, etc...
> run the func tests on fedora, suseleap and others

- omnibus/Gemfile.lock
Cherry Pick omnibus commits
https://github.com/chef/chef/issues/5458
- [x ] All tests pass
- [x ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
> Cherry Pick omnibus commits

- lib/chef/provider/launchd.rb
- lib/chef/resource/launchd.rb
- spec/unit/provider/launchd_spec.rb
This work is @ErebusBat's, I'm simply finishing it off so we can get it merged.
Closes: #5115
> Mac: ensure launchd's start_calendar_interval gets valid settings

- lib/chef/shell/ext.rb
> Output https links in chef-shell

- RELEASE_NOTES.md
We merged in a 12.17 change into the 12.16 notes.
> Wipe the 12.16 release notes out

- lib/chef/application/exit_code.rb
- lib/chef/mixin/powershell_type_coercions.rb
- lib/chef/node/common_api.rb
- lib/chef/resource/launchd.rb
- lib/chef/resource/reboot.rb
believe this becomes necessary for ruby 2.4/3.0
> Core: fix Lint/UnifiedInteger cop

- lib/chef/knife/client_delete.rb
- lib/chef/knife/node_delete.rb
- spec/spec_helper.rb
- spec/unit/knife/client_delete_spec.rb
- spec/unit/knife/node_delete_spec.rb
Addresses https://github.com/chef/chef/issues/5436
> Add ability to pass multiple nodes to knife node/client delete

- lib/chef/resource/user.rb
- spec/unit/provider/user/linux_spec.rb
Fix the suggested fix to actually compile
> The suggested fix for the manage_home deprecation is incorrect

- lib/chef/cookbook/metadata.rb
- spec/unit/knife/cookbook_metadata_spec.rb
rewrite of the specs on top of @andy-dufour's patch
closes #4428 
closes #3888
> Knife: cookbook site share doesn't work with some json metadata

- tasks/templates/prerelease.md.erb
- tasks/templates/release.md.erb
The product download pages now leverage predictable URLS, so our
generators can leverage those to improve the download experience.
> Use new downloads.chef.io URLs for announcements

- spec/unit/provider/package/msu_spec.rb
suspect this will fix breakage on appveyor
> fix derpage on master

- omnibus/resources/chef/msi/source.wxs.erb
> Fixed minor UI issues with Chef's MSI.

- RELEASE_NOTES.md
> Add multiple client/nodes knife delete to release notes

- lib/chef/deprecated.rb
- lib/chef/mixin/command.rb
- lib/chef/mixin/shell_out.rb
- lib/chef/provider/group/groupadd.rb
- spec/unit/provider/group/groupadd_spec.rb
closes #3014
also improves the groupadd provider a bit
> formally deprecate run_command

- .travis.yml
> bump ruby versions in travis

- lib/chef/provider/service/macosx.rb
> fix master breakage

- lib/chef/mixin/shell_out.rb
- lib/chef/provider/group.rb
- lib/chef/provider/group/aix.rb
- lib/chef/provider/group/dscl.rb
- lib/chef/provider/group/gpasswd.rb
- lib/chef/provider/group/groupadd.rb
- lib/chef/provider/group/groupmod.rb
- lib/chef/provider/group/pw.rb
- lib/chef/provider/group/suse.rb
- lib/chef/provider/group/usermod.rb
- lib/chef/provider/group/windows.rb
- spec/unit/provider/group/dscl_spec.rb
- spec/unit/provider/group/gpasswd_spec.rb
- spec/unit/provider/group/groupadd_spec.rb
- spec/unit/provider/group/groupmod_spec.rb
- spec/unit/provider/group/pw_spec.rb
- spec/unit/provider/group/suse_spec.rb
- spec/unit/provider/group/usermod_spec.rb
- consistent use of shell_out_compact!
- remove more uses of run_command
- some other code cleanup
> cleanup of group provider

- lib/chef/provider/user.rb
- lib/chef/provider/user/aix.rb
- lib/chef/provider/user/dscl.rb
- lib/chef/provider/user/linux.rb
- lib/chef/provider/user/pw.rb
- lib/chef/provider/user/solaris.rb
- lib/chef/provider/user/useradd.rb
- lib/chef/provider/user/windows.rb
- spec/unit/provider/user/dscl_spec.rb
- spec/unit/provider/user/linux_spec.rb
- spec/unit/provider/user/pw_spec.rb
- spec/unit/provider/user/windows_spec.rb
- spec/unit/provider/user_spec.rb
needed to be built on top of #5673 so it might be easier to review and merge that one first.
> user provider cleanup

- lib/chef/provider/ifconfig.rb
- lib/chef/provider/ifconfig/aix.rb
- lib/chef/provider/ifconfig/debian.rb
- lib/chef/provider/ifconfig/redhat.rb
- lib/chef/provider/route.rb
- spec/unit/provider/ifconfig/aix_spec.rb
- spec/unit/provider/ifconfig/debian_spec.rb
- spec/unit/provider/ifconfig/redhat_spec.rb
- spec/unit/provider/ifconfig_spec.rb
- spec/unit/provider/route_spec.rb
built on top of #5673 and #5674 so easier to review after those get merged.
> cleanup of ifconfig and route providers

- lib/chef/provider/group/aix.rb
#5673 passed travis but broke func tests on AIX in internal jenkins
> fix aix breakage from #5673

- lib/chef/provider/group/dscl.rb
- spec/unit/provider/group/dscl_spec.rb
i didn't fully grok the way the dscl providers were written and
only half fixed the group dscl provider, but later did a better
job fixing the user one.
fixes the breakage caught in the dscl group func tests.
> fix dscl group provider func breakage from #5673

- distro/common/html/knife_environment.html
- distro/common/man/man1/knife-environment.1
Obvious fix.
Signed-off-by: Ronald Gundlach-Chmara <ronabop@gmail.com>
Removes outdated documentation verbiage,
> Remove non-working documention statements/arguments.

- lib/chef/provider/package/chocolatey.rb
- lib/chef/resource/chocolatey_package.rb
- spec/unit/provider/package/chocolatey_spec.rb
- spec/unit/resource/chocolatey_package_spec.rb
Added 'returns' property to chocolatey_package
#5030
> Adding returns property to chocolatey_package resource

- RELEASE_NOTES.md
> Fix release note links

- RELEASE_NOTES.md
w.r.t. https://github.com/chef/chef/pull/5688
> Release notes for returns property in chocolatey_package

- .travis.yml
just updating the matrix
bonus fix:  commenting out fedora-latest so that the builds at least look green again.
> ruby-2.4 got released

- spec/unit/provider/remote_file/sftp_spec.rb
Corrects URI in remote_file sftp test
Initial #4750 merge incorrectly tested 'ftp' scheme.
> Correct SFTP remote_file tests

- .github/ISSUE_TEMPLATE.md
> make it a trifle clearer that server issues don't belong here

- MAINTAINERS.md
- MAINTAINERS.toml
Add myself as core maintainer (per discussion with @thommay at Rally)
> Add myself as core maintainer

- lib/chef/win32/security.rb
- spec/unit/win32/error_spec.rb
- spec/unit/win32/security_spec.rb
Done.
Cherry-picked required commits from the [PR](https://github.com/chef/chef/pull/3808). I have added RSpecs for the functionality implemented in the [PR](https://github.com/chef/chef/pull/3808).
> Raise NamedSecurityInfo related exception using HR result.

- lib/chef/knife/ssh.rb
- spec/functional/knife/ssh_spec.rb
- spec/unit/knife/ssh_spec.rb
Also use partial search for much small on-the-wire sizes
https://discourse.chef.io/t/maximum-knife-ssh-nodes/10259/12 for reference.
> Ensure ssh search paginates correctly

- habitat/plan.sh
git archive + standard unpack untar is faster than rsync and prevents picking up a dirty working directory.
Also fixes an empty `GEM_HOME` set during `do_build` and trims some trailing whitespace.
Paired with @ubergeekgirl on this change.
No open issues related. This change was first posited on [a comment](https://github.com/chef/chef/pull/5677#discussion_r94259484) on the PR adding a Habitat plan to this repo.
> use git archive to speed up putting source in place

- .github/ISSUE_TEMPLATE.md
To avoid product suggestions getting lost in the github issues, add a link to the issue template to direct users to propose new feature requests to feedback.chef.io
> Direct feature requests to feedback.chef.io

- .bundle/config
- Gemfile.lock
- chef.gemspec
> Bump mixlib-archive version to 0.4

- tasks/changelog.rb
> ignore things properly

- lib/chef/provider/package.rb
- lib/chef/provider/package/yum.rb
- spec/unit/provider/package/yum_spec.rb
An initial refactor to add multipackage_api support to the yum_package
provider. There probably needs to be an additional refactor to make
this provider look a little bit more like the DNF provider, but this
should buy us some time and address some bugs.
* COOL-612 (internal ticket)
* ZD-3574 (internal ticket)
* ZD-13572 (interna ticket)
* Fixes #3476
* Fixes #4266
* Fixes #5112 
* Fixes #5163 
* Fixes #5254
> Add mutlipackage_api support to yum_package provider

- lib/chef/provider/package/dnf.rb
- lib/chef/resource/dnf_package.rb
> do not support dnf_package on dnf 0.x

- RELEASE_NOTES.md
Replaces https://github.com/chef/chef/pull/5784
> Be more specific about using the alternate user feature

- spec/support/platform_helpers.rb
looks someone fixed an edge condition in rubocop
> fix for rubocop 0.47.1

- lib/chef/data_collector.rb
- spec/support/shared/context/client.rb
new data collector re-introduced the same kinds of bugs that e.g. #3320 fixed
> Sanitize UTF-8 data sent to Data Collector

- ci/bundle_install.sh
> Bundle with changelog group for version bump

- README.md
Fix 2 typos and simplify the list markdown
> Fix readme typos and improve list markdown

- tasks/changelog.rb
We need them to sort the pull requests by type.
> Don't ignore issues when generating the changelog

- lib/chef/resource/package.rb
- lib/chef/resource/yum_package.rb
- spec/unit/resource/yum_package_spec.rb
as noted in comments this works around bugginess in the yum
provider that require a major refactor to fix.
closes #5812
> coerce immutable arrays to normal arrays in the yum_package resource

- appveyor.yml
so we can roll back when we need to
looks like we need to
> appveyor: uninstall bundler first

- Gemfile.lock
- chef-config/lib/chef-config/config.rb
- lib/chef/deprecated.rb
- lib/chef/resource_builder.rb
- spec/unit/recipe_spec.rb
> Chef-13 remove resource cloning and 3694 warnings

- omnibus/Gemfile.lock
now the build should be fixed.
> forgot to run the rake task to update deps

- Gemfile.lock
- omnibus/config/software/chef-gem-ohai.rb
- omnibus/config/software/chef.rb
- omnibus/files/chef-gem/build-chef-gem/gem-install-software-def.rb
converts ohai over to a "chef_gem" omnibus definition and builds out the ability of those definitions to pull from git
> build ohai from git

- .travis.yml
- appveyor.yml
- ci/bundle_install.sh
- version_policy.rb
* Replace final few occurrences of changelog bundle group with CI group
* Broken Builds
> Replace changelog group with ci group

- lib/chef/resource.rb
- lib/chef/resource/execute.rb
- spec/support/shared/unit/execute_resource.rb
- spec/unit/resource_spec.rb
converts sensitive, retries, retry_delay and ignore_failure to
properties
> convert additional resource methods to properties

- lib/chef/deprecation/mixin/template.rb
- lib/chef/deprecation/provider/cookbook_file.rb
- lib/chef/deprecation/provider/file.rb
- lib/chef/deprecation/provider/remote_directory.rb
- lib/chef/deprecation/provider/remote_file.rb
- lib/chef/deprecation/provider/template.rb
- lib/chef/provider/cookbook_file.rb
- lib/chef/provider/file.rb
- lib/chef/provider/remote_directory.rb
- lib/chef/provider/remote_file.rb
- lib/chef/provider/template.rb
- spec/unit/deprecation_spec.rb
This reverts commit f312ab8b2f46f6211fc0b732890c69e4dae46c77.
> Revert "Remove all 11 era deprecations"

- lib/chef/resource/file/verification.rb
- spec/unit/resource/file/verification_spec.rb
> Remove %{file} from verify interpolation

- Gemfile.lock
- chef-config/lib/chef-config/config.rb
- spec/unit/encrypted_data_bag_item_spec.rb
> Use v3 data bag encryption

- lib/chef/search/query.rb
- spec/unit/search/query_spec.rb
> remove partial_search

- spec/functional/knife/ssh_spec.rb
This is a continuation of #5873, using a blunter instrument. @chef/maintainers I think I will just merge this.
> Ensure that there are no pesky // in our paths

- README.md
> Add release policy badge to README

- RELEASE_NOTES.md
> [ci skip] add missing relnotes for Node deep-duping

- lib/chef/node/attribute.rb
- spec/unit/node/attribute_spec.rb
nod to @jaymzh for finding this one.
> fix node#debug_value access through arrays

- RELEASE_NOTES.md
- lib/chef/property.rb
- lib/chef/resource.rb
- spec/unit/property_spec.rb
- spec/unit/resource/cookbook_file_spec.rb
- spec/unit/resource/cron_spec.rb
- spec/unit/resource/deploy_spec.rb
- spec/unit/resource/directory_spec.rb
- spec/unit/resource/env_spec.rb
- spec/unit/resource/file_spec.rb
- spec/unit/resource/group_spec.rb
- spec/unit/resource/ifconfig_spec.rb
- spec/unit/resource/link_spec.rb
- spec/unit/resource/mdadm_spec.rb
- spec/unit/resource/mount_spec.rb
- spec/unit/resource/ohai_spec.rb
- spec/unit/resource/package_spec.rb
- spec/unit/resource/registry_key_spec.rb
- spec/unit/resource/remote_directory_spec.rb
- spec/unit/resource/remote_file_spec.rb
- spec/unit/resource/route_spec.rb
- spec/unit/resource/scm_spec.rb
- spec/unit/resource/service_spec.rb
- spec/unit/resource/systemd_unit_spec.rb
- spec/unit/resource/template_spec.rb
- spec/unit/resource/user_spec.rb
- spec/unit/resource_reporter_spec.rb
- spec/unit/resource_spec.rb
flips the deprecation warning over to a raise
> Chef-13:  raise on properties redefining inherited methods

- omnibus/Gemfile.lock
We need to ensure that libgcc.dll gets copied in to the right place
> Bump to current master of omnibus

- acceptance/basics/test/integration/chef-current-install/serverspec/chef_client_spec.rb
- acceptance/top-cookbooks/.acceptance/acceptance-cookbook/libraries/top_cookbooks.rb
> Disable some tests for now

- omnibus/Gemfile.lock
- omnibus/files/chef-gem/build-chef-gem.rb
> bump _XOPEN_SOURCE to 600 for ruby 2.4 on Solaris

- omnibus/Gemfile.lock
necessary for a solaris build fix
> bumping omnibus lockfile

- acceptance/Gemfile.lock
mostly picks up chef/chef-acceptance#45
> bumping acceptance gems

- lib/chef/resource/launchd.rb
> Chef-13: remove deprecated launchd resource hash property

- lib/chef/resource.rb
i don't even think there were any tests?
> Chef-13:  remove Chef::Resource.updated=

- lib/chef/knife/search.rb
- spec/integration/knife/search_node_spec.rb
- spec/support/shared/integration/knife_support.rb
> Chef-13 knife search exit 1 when no results

- .travis.yml
- Gemfile.lock
- lib/chef/provider/ifconfig/redhat.rb
- lib/chef/provider/package/dnf.rb
- lib/chef/provider/package/yum.rb
- lib/chef/provider/service.rb
- lib/chef/provider/service/insserv.rb
- lib/chef/provider/service/redhat.rb
- lib/chef/resource/dnf_package.rb
- lib/chef/resource/yum_package.rb
expecting this to go red and need code/spec changes in chef
> bumping Gemfile.lock to pick up ohai amazon change

- acceptance/data-collector/test/integration/default/serverspec/default_spec.rb
> Ensure we check all required fields

- lib/chef/knife/ssh.rb
`knife ssh --exit-on-error` exit when the command launch by ssh fail.
https://github.com/chef/chef/issues/5399
> fix knife ssh --exit-on-error

- lib/chef/resource/execute.rb
> Very minor follow up to https://github.com/chef/chef/commit/81db0e0cfc218169a70a8178f83c567b467d2e6c

- lib/chef/provider/user/linux.rb
> fix build break on master in linux user provider

- MAINTAINERS.md
- MAINTAINERS.toml
Signed-off-by: Josh Hudson <jhudson@chef.io>
Add myself as a core maintainer.
> Add myself as a core maintainer

- omnibus/Gemfile.lock
Picking up chef/omnibus#771 to correct an issue with the BFF
packager, currently causing issues on the chef-test job for AIX
testers. Thanks for nothing, braces-in-filenames!
> Update omnibus Gemfile.lock

- Gemfile
- Gemfile.lock
- RELEASE_NOTES.md
First pass, review and updates appreciated @chef/maintainers.
I used https://github.com/search?l=&o=asc&p=1&q=type%3Apr+merged%3A%222017-02-23+..+%2A%22+repo%3Achef%2Fchef&ref=advsearch&s=updated&type=Issues&utf8=%E2%9C%93 as a query for all the PRs we merged since 12.19.36 .
> Write release notes for Chef 13

- lib/chef/cookbook/manifest_v0.rb
- spec/unit/cookbook/manifest_v0_spec.rb
- spec/unit/cookbook/manifest_v2_spec.rb
Refs https://github.com/chef/chef/issues/6044
> Fix for Chef 13 upload reversion.

- Gemfile.lock
> Bump ohai dependency

- lib/chef/knife/client_key_create.rb
- lib/chef/knife/client_key_delete.rb
- lib/chef/knife/client_key_edit.rb
- lib/chef/knife/client_key_list.rb
- lib/chef/knife/client_key_show.rb
- lib/chef/knife/user_key_create.rb
- lib/chef/knife/user_key_delete.rb
- lib/chef/knife/user_key_edit.rb
- lib/chef/knife/user_key_list.rb
- lib/chef/knife/user_key_show.rb
> The two key list commands didn’t actually require the helper object they both use.

- spec/functional/resource/user/useradd_spec.rb
> Looks like this is broken on SLES 12.0/x64 too

- lib/chef/provider/execute.rb
Sorry to bug you guys with this PR, it's just a typo I ran into it and decided to fix it.
None
None
> Fixing small typo

- lib/chef/cookbook/remote_file_vendor.rb
- lib/chef/cookbook/synchronizer.rb
- lib/chef/cookbook_manifest.rb
- spec/integration/client/client_spec.rb
- spec/unit/cookbook/synchronizer_spec.rb
- spec/unit/cookbook_manifest_spec.rb
Fixes: #6051 and supercedes: #6070
> lazy load cookbook files

- Gemfile
- Gemfile.lock
pretty sure i solved this some other way and this was debugging
i forgot to remove...
> actually i don't think appveyor needs this

- lib/chef/provider/user/aix.rb
- spec/unit/provider/user/aix_spec.rb
> Fix manage_home on AIX

- .travis.yml
- ci/dependency_update.sh
- ci/version_bump.sh
> Don't futz with bundle config

- lib/chef/provider/apt_repository.rb
Signed-off-by: Matt Whiteley <mattwhiteley@gmail.com>
https://github.com/chef/chef/pull/5874 caused keys to be retrieved from keyserver and installed on every chef run. The regex in `extract_fingerprints_from_cmd` was changed but it's called in both `install_key_from_uri` and `install_key_from_keyserver` and it will never match the command output in `apt-key finger`.
I'm not sure this is the desired way to do this, happy to change up if it's not.
> apt-key finger no longer matches extract fingerprints regex

- kitchen-tests/.kitchen.travis.yml
i like the reliability of omnitruck over the docker installs better.
> go back to using omnitruck to install

- lib/chef/provider/user/windows.rb
wrt issue  https://github.com/chef/chef/issues/5521
> User on Windows with group incorrectly warns about passing GID

- lib/chef/resource/windows_task.rb
- spec/functional/resource/windows_task_spec.rb
> Adding functional specs for windows_task resource

- spec/functional/resource/windows_task_spec.rb
> Fixing broken functional test in windows_task resource

- appveyor.yml
back port of just these fixes for chef-13
> fix appveyor on chef-12

- spec/functional/resource/chocolatey_package_spec.rb
> Completely ignore the chocolatey tests

- spec/functional/resource/chocolatey_package_spec.rb
> Run choco tests just on 2012r2 for now

- Gemfile.lock
please to be whacking merge if its green
> bump deps in Gemfile.lock

- RELEASE_NOTES.md
Just add the single ohai deprecation
> Update release notes for 13.1

- lib/chef/application/solo.rb
#This is technically a compat break but I think it's probably okay `¯\_(ツ)_/¯`. Slightly safer for my inner paranoid security engineer.
> Make non-legacy solo use socketless mode

- chef-config/lib/chef-config/config.rb
> Missed this which makes some smoke tests for chef-shell fail.

- spec/functional/resource/windows_task_spec.rb
> mark windows task :end test as volatile

- acceptance/basics/test/integration/chef-current-install/serverspec/chef_client_spec.rb
The minitest gem is shipped by ruby itself.
> whitelist minitest

- spec/integration/knife/common_options_spec.rb
Yet more "I should have actually run all the tests locally" stuff. Not sure how this got by Travis though but should be happier now. Bit awkward to test for stuff that is deprecated but it's complex enough that it seemed like a good idea to leave.
> Fix up tests for the no-listen swapover.

- README.md
> bump ruby version in README [ci skip]

- lib/chef/version.rb
- omnibus/Gemfile.lock
Provided by chef/omnibus-software#836
> Copy chef gems in place

- RELEASE_NOTES.md
For https://github.com/chef/chef/pull/6122
> Add release notes related to SIGHUP changes [ci skip]

- .travis.yml
> Update the chefspec URL for Travis

- lib/chef/resource/breakpoint.rb
> Fix a typo in the breakpoint resource name

- Gemfile.lock
mostly want this for new chefstyle, nothing surprising here.
> bump Gemfile.lock

- lib/chef/provider/package/chocolatey.rb
wrt https://github.com/chef/chef/issues/6165
> Fix chomp error for nil class

- .expeditor/update_version.sh
> Don't error out if .bundle/config doesn't exist (as it might)

- spec/functional/mixin/powershell_out_spec.rb
- spec/functional/resource/group_spec.rb
- spec/spec_helper.rb
- spec/support/platform_helpers.rb
> Fixing build failures of Windows Server 2016

- Gemfile.lock
- lib/chef/provider/group/aix.rb
- lib/chef/provider/group/groupadd.rb
- lib/chef/provider/user/pw.rb
- lib/chef/provider/user/windows.rb
- spec/integration/knife/cookbook_bulk_delete_spec.rb
- spec/integration/knife/cookbook_show_spec.rb
- spec/integration/knife/environment_compare_spec.rb
- spec/integration/knife/environment_show_spec.rb
- spec/integration/knife/role_show_spec.rb
- spec/support/shared/unit/provider/useradd_based_user_provider.rb
- spec/unit/provider/group/groupadd_spec.rb
- spec/unit/provider/user/pw_spec.rb
> bump rubocop to 0.49.1

- .rubocop.yml
- .travis.yml
- Gemfile
- Gemfile.lock
> lock chefstyle at 0.5

- lib/chef/policy_builder/policyfile.rb
- spec/unit/policy_builder/policyfile_spec.rb
Backport #6229 from master for use in ACC pipeline.
> Properly send run_list_expanded event in policy node case

- lib/chef/knife/cookbook_test.rb
Update message to recommend Cookstyle not Rubocop
> Update deprecation message for Cookstyle

- Gemfile.lock
- RELEASE_NOTES.md
Add RELEASE_NOTES for 13.2 release
> Prepare release notes for 13.2

- lib/chef/provider/mount/aix.rb
- spec/unit/provider/mount/aix_spec.rb
Signed-off-by: NAshwini <ashwini.nehate@msystechnologies.com>
[Make mount idempotent on Aix]
> [MSYS-590]Make mount idempotent on Aix

- Gemfile
- Gemfile.lock
> Add nokogiri to the installer again

- lib/chef/deprecation/warnings.rb
It's the next major version not Chef 13.
> Auto increment the chef version for deprecations

- acceptance/data-collector/.acceptance/data-collector-test/recipes/default.rb
allow them to continue to abuse it, but contain it.
> acceptance tests are (ab)using our internal ruby

- Gemfile.lock
For #6261
its still early for me, need more coffee
> Except I forgot to bundle update of course

- .gitignore
Add Rubymine project files to .gitignore list
n/a
> Add Rubymine project files to .gitignore list

- acceptance/data-collector/.acceptance/data-collector-test/files/default/api.rb
- acceptance/data-collector/.acceptance/data-collector-test/recipes/default.rb
should hopefully get our tests back to green
> More acceptance test fixing.

- appveyor.yml
Signed-off-by: MSys <harikesh.kolekar@msystechnologies.com>
Investigate length of package functional tests in Appveyor for chef/chef
> change image appveyor

- omnibus/Gemfile.lock
The actual fix is chef/omnibus-software#864
> Fix solaris/x86 builds

- MAINTAINERS.md
- MAINTAINERS.toml
> Removing myself as a maintainer

- lib/chef/resource/execute.rb
- spec/unit/resource/execute_spec.rb
> [MSYS-629] Added username/password validation for elevated option

- appveyor.yml
> bump appveyor to ruby 2.4

- lib/chef/data_collector/resource_report.rb
- spec/unit/data_collector/resource_report_spec.rb
Backport to Chef 12 of https://github.com/chef/chef/pull/5941.
> made changes to work file and remote_file resource work for lazy

- omnibus/Gemfile.lock
> Bump omnibus-software version

- RELEASE_NOTES.md
> Add release notes for 13.3

- Gemfile.lock
> Pull in Ohai 13.3

- lib/chef/provider/apt_preference.rb
- spec/unit/provider/apt_preference_spec.rb
> Fix the apt_preference action to be remove

- RELEASE_NOTES.md
> Add more items to the 13.3 release notes

- RELEASE_NOTES.md
> Fix bad examples in the release notes

- .expeditor/config.yml
- .expeditor/update_version.sh
Add proper Expeditor support to the chef-12 branch
> Add Expeditor to chef-12 branch

- .expeditor/update_version.sh
Work around https://github.com/bundler/bundler/issues/5644 in the same way we did for ChefDK.
> Fix up update_version to work around bundler bug

- CHANGELOG.md
Are there links? Nope. Is it a changelog? Yes
> Add Chef 13.0.113 and 13.0.118 to the changelog

- .rubocop.yml
- spec/unit/knife/client_delete_spec.rb
discussion in chef/chefstyle#54
> add more rubocop.yml config to disable some Lint and the Security/Eval cop for now

- .github/CODEOWNERS
> add codeowners for reviews

- RELEASE_NOTES.md
w.r.t. https://github.com/chef/chef/pull/6295
> [MSYS-645] Updated release_notes for windows_path

- lib/chef/node/immutable_collections.rb
- spec/unit/node/immutable_collections_spec.rb
> backport 6355 to Chef-12

- lib/chef/node/attribute.rb
> Chef-12: backport 6356

- lib/chef/provider/git.rb
- spec/unit/provider/git_spec.rb
This resolves issue chef issue 6350
https://github.com/chef/chef/issues/6350
> handle apple git

- lib/chef/provider/package/dnf.rb
> Backport #6351 to Chef-12

- RELEASE_NOTES.md
w.r.t https://github.com/chef/chef/pull/5832
> [MSYS-439] Updated Release notes for alternate user support in remote_file resource

- .expeditor/config.yml
- .github/CODEOWNERS
- CHANGELOG.md
Update the Expeditor configuration to match 0.5.0 requirements. 
For more info, you can see the new docs site: http://expeditor-docs.es.chef.io
> Update Expeditor config for 0.5.0

- CHANGELOG.md
Remove release note / changelog fixes, improve a few descriptions. Move
bugs into the bug section
> Cleanup the current changelog

- lib/chef/util/dsc/local_configuration_manager.rb
- spec/unit/util/dsc/local_configuration_manager_spec.rb
Fixes https://github.com/chef/chef/issues/5588
Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>
[fixed dsc_script for WMF5]
[dsc_script idempotence not working?]
> MSYS-656 - fixed dsc_script for WMF5

- .expeditor/config.yml
Update the Expeditor configuration
> Update Expeditor config to meet new standards

- CHANGELOG.md
We need to merge a PR to trigger Expeditor
> Typo fix to trigger a build

- .expeditor/config.yml
Add `docker_images` config to Expeditor config on chef-12 branch
> Fully configure Docker image in Expeditor

- .expeditor/config.yml
> [Expeditor] Use new glob-style version matching

- lib/chef/provider/route.rb
- spec/unit/provider/route_spec.rb
This should make us more robust in the face of the enemy
> [Route unit tests]: Ensure we go down the new file path

- lib/chef/provider/package/zypper.rb
- lib/chef/resource/zypper_package.rb
- spec/unit/provider/package/zypper_spec.rb
Add allow_downgrade to zypper_package resource 
none
> Add allow_downgrade to zypper_package resource 

- lib/chef/client.rb
- spec/unit/client_spec.rb
We should not stack-trace, we should exit with a clean error
> Support new CriticalOhaiPlugins

- CHANGELOG.md
Remove some items that don't matter. Remove internal Chef ticket
numbers.
> A bit of changelog cleanup

- lib/chef/provider/package/dnf.rb
- lib/chef/resource/dnf_package.rb
we have to worry about amazon being in the rhel platform_family
in Chef-12.
> backport of #6490

- lib/chef/platform/rebooter.rb
- spec/functional/rebooter_spec.rb
> fix rebooter for solaris and background reboots

- omnibus/files/chef-appbundle/build-chef-appbundle.rb
> Add environment/cwd to bundle freeze script

- lib/chef/provider/dsc_script.rb
- lib/chef/util/dsc/lcm_output_parser.rb
- lib/chef/util/dsc/local_configuration_manager.rb
- spec/unit/util/dsc/lcm_output_parser_spec.rb
- spec/unit/util/dsc/local_configuration_manager_spec.rb
Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>
> MSYS-684: Added parser for DSC configuration

- lib/chef/provider/package/chocolatey.rb
- spec/unit/provider/package/chocolatey_spec.rb
chocolatey_package installs packages in array for Artifactory server as source repo
Fixes https://github.com/chef/chef/issues/6303
> [MSYS-647] array support for choco pkg from artifactory

- Rakefile
trying to get a chef-12 build into -current
> bump a copyright date to kick off a build

- Gemfile.lock
- omnibus/Gemfile.lock
> Pull in Ohai 8.25

- RELEASE_NOTES.md
- lib/chef/deprecated.rb
- lib/chef/resource/deploy.rb
@tas50 has volunteered (really, I have witnesses) to make the migration cookbook.
> Deprecate the deploy resource and family

- README.md
Really I just need to kick off a build, but this should also get fixed
> Update ruby version required in readme

- CHANGELOG.md
This doesn't mean anything to an external user
> Remove msys ticket numbers from changelog

- omnibus/Gemfile.lock
- version_policy.rb
Bump all omnibus deps to pull in security and bug fixes
> Update liblzma, libxml2, libxslt, libyaml, zlib, and openssl

- RELEASE_NOTES.md
> Update the Ohai 13.6 release notes

- .mailmap
> Add mailmap entries for Tim Smith

- RELEASE_NOTES.md
> Add 13.6.4 release notes

- chef-config/lib/chef-config/path_helper.rb
- spec/support/shared/functional/execute_resource.rb
Removes deprecated method warning.
> replace deprecated Dir.exists? with Dir.exist?

- lib/chef/knife/ssh.rb
- spec/unit/knife/ssh_spec.rb
> Filter out periods from tmux session name

- lib/chef/provider/windows_task.rb
- spec/unit/provider/windows_task_spec.rb
Fixes https://github.com/chef/chef/issues/6480 and https://github.com/chef/chef/pull/6312#issuecomment-337533074
> [MSYS-688] Fixed invalid date and Invalid starttime error

- lib/chef/knife/data_bag_show.rb
- spec/integration/knife/data_bag_show_spec.rb
- spec/unit/knife/data_bag_show_spec.rb
> Only warn if a secret was actually given

- lib/chef/provider/systemd_unit.rb
- lib/chef/resource/systemd_unit.rb
adds unit_name identity attribute to systemd_unit resource
#6542
> add unit_name name_property to systemd_unit (fixes #6542)

- Gemfile.lock
- RELEASE_NOTES.md
> Update InSpec to 1.47 and Ohai to 13.7

- lib/chef/resource/windows_task.rb
- spec/functional/resource/windows_task_spec.rb
- spec/unit/resource/windows_task_spec.rb
Round 2 of logging improvements to the windows_task resource.
> Additional logging improvements to windows_task

- .travis.yml
> Remove the allowed_failures in Travis

- lib/chef/node_map.rb
- spec/unit/node_map_spec.rb
this is the flip side of what was making the old tests so slow and this
change will actually speedup customer runs by short-circuiting some
operations.
> speedup node_map get and set operations

- spec/unit/knife/data_bag_create_spec.rb
> Fix sneaky chefstyle violations

- lib/chef/api_client.rb
- lib/chef/api_client_v1.rb
- lib/chef/chef_class.rb
- lib/chef/chef_fs/data_handler/data_handler_base.rb
- lib/chef/cookbook/chefignore.rb
- lib/chef/cookbook/cookbook_collection.rb
- lib/chef/cookbook/metadata.rb
- lib/chef/knife.rb
- lib/chef/knife/data_bag_secret_options.rb
- lib/chef/mixin/powershell_out.rb
- lib/chef/provider/package/dnf.rb
- lib/chef/provider/remote_directory.rb
- lib/chef/resource/chef_gem.rb
- lib/chef/resource/file.rb
- lib/chef/resource/freebsd_package.rb
- lib/chef/resource/resource_notification.rb
- lib/chef/run_context.rb
Added them as I was reading through some resources
> Add a few more YARD comments to resources

- lib/chef/resource/cab_package.rb
- lib/chef/resource/chocolatey_package.rb
- lib/chef/resource/dsc_script.rb
- lib/chef/resource/env.rb
- lib/chef/resource/msu_package.rb
- lib/chef/resource/windows_task.rb
- spec/unit/resource/msu_package_spec.rb
- spec/unit/resource/windows_task_spec.rb
Tip of the iceberg here, but it's the low hanging fruit
> Avoid a few initializers in resources by using the DSL we have

- lib/chef/provider/reboot.rb
- lib/chef/resource/reboot.rb
- spec/unit/resource/reboot_spec.rb
> Modernize reboot resource and add spec

- Gemfile.lock
- chef-config/chef-config.gemspec
- chef-config/lib/chef-config/config.rb
- chef-config/lib/chef-config/mixin/credentials.rb
- chef-config/lib/chef-config/workstation_config_loader.rb
- chef-config/spec/unit/workstation_config_loader_spec.rb
- lib/chef/application/knife.rb
- lib/chef/knife.rb
- lib/chef/knife/configure.rb
- lib/chef/server_api.rb
- spec/unit/knife/configure_spec.rb
- spec/unit/knife_spec.rb
> implement credential management

- lib/chef/resource/osx_profile.rb
> Modernize osx_profile resource

- lib/chef/provider/file.rb
- lib/chef/resource/file/verification.rb
- spec/support/shared/unit/provider/file.rb
- spec/unit/resource/file/verification_spec.rb
This is a rescue of #4795 with chefstyle and a rebase.
Fixes #4795
> Slight improvements to validation failures

- lib/chef/provider/ifconfig.rb
- lib/chef/resource/ifconfig.rb
> Modernize the ifconfig resource

- lib/chef/resource/directory.rb
> Modernize directory resource

- lib/chef/resource/yum_repository.rb
- spec/unit/resource/yum_repository_spec.rb
priority should be 0-99. Simple fix to the regex to check that. I also removed all the .* regexes from the Strings. Speak up if you know why we had those.
> Fix yum_repository allowing priority of 0 and remove string regexes

- lib/chef/knife/cookbook_upload.rb
Uploaded 0 cookbook. -> Uploaded 0 cookbooks.
Obvious fix.
> Add an 's' for quantity of 0 cookbooks.

- lib/chef/provider/launchd.rb
- lib/chef/resource/launchd.rb
> Modernize launchd resource

- .travis.yml
- tasks/rspec.rb
This should make it easier to read through failures and should greatly speed things up.
> Break out unit tests into their own jobs in Travis to speed things up

- lib/chef/property.rb
- spec/integration/recipes/resource_action_spec.rb
- spec/unit/property_spec.rb
Give more details on why people are seeing these problems so they can fix them.
> Improve property warnings in resources

- lib/chef/deprecated.rb
- lib/chef/resource/erl_call.rb
This implements RFC 98 from https://github.com/chef/chef-rfc
> Deprecate erl_call resource

- lib/chef/knife/core/ui.rb
- lib/chef/knife/edit.rb
I updated the structure of the knife documentation a while back and we have a dedicated doc for setting up knife now.
> Update the knife editor error message to point to the correct document

- lib/chef/node_map.rb
flattens out the internal data structure and removes some excessive
defensive coding.
> simplify node_map logic

- spec/functional/assets/chefinittest
- spec/functional/resource/bff_spec.rb
lets TMPDIR be something other than /tmp
> use TMPDIR correctly in initscript

- .travis.yml
- spec/unit/chef_fs/file_system/repository/directory_spec.rb
- spec/unit/deprecated_spec.rb
> Add Ruby 2.5 testing to Travis

- spec/support/shared/integration/knife_support.rb
> Ensure we don't use credentials during integration tests

- distro/common/html/knife_search.html
- distro/common/man/man1/knife-search.1
- distro/common/markdown/man1/knife-search.mkd
Fixing missing and/or inconsistent quoting in knife search documentation
No pre-existing issue(s)
> Fixing missing and/or inconsistent quoting in knife search documentation

- lib/chef/node.rb
- lib/chef/node/attribute.rb
- spec/unit/node_spec.rb
been deprecated since late-12.
closes #6610
> Remove node.set and node.set_unless attribute levels

- lib/chef/application/client.rb
- lib/chef/application/solo.rb
- spec/unit/application/client_spec.rb
- spec/unit/application/solo_spec.rb
> Fail on interval runs on windows

- CHANGELOG.md
This failed to automatically happen
> Fix the changelog for the 13.7 release

- lib/chef/application/client.rb
- lib/chef/application/solo.rb
- spec/unit/application/client_spec.rb
- spec/unit/application/solo_spec.rb
> Revert "Fail on interval runs on windows"

- spec/functional/resource/windows_task_spec.rb
Signed-off-by: NAshwini <ashwini.nehate@msystechnologies.com>
Added idempotent checks to windows_task_spec
> Added idempotent checks to windows_task_spec

- lib/chef/api_client_v1.rb
- lib/chef/handler.rb
- lib/chef/mixin/api_version_request_handling.rb
- lib/chef/mixin/deprecation.rb
- lib/chef/mixin/homebrew_user.rb
- lib/chef/mixin/openssl_helper.rb
- lib/chef/mixin/provides.rb
- lib/chef/mixin/securable.rb
- lib/chef/mixin/shell_out.rb
- lib/chef/mixin/template.rb
- lib/chef/mixin/why_run.rb
Mostly remove some warnings when running yard on the CLI
> Cleanup a bit of YARD and add a few things

- lib/chef/resource/apt_repository.rb
- spec/unit/resource/apt_repository_spec.rb
> Nillable properties are the default now

- lib/chef/resource.rb
We have a count. Just add the s if it's more than 1 left.
> Use attempt or attempts in the retries logging

- spec/unit/resource_spec.rb
> Remove the spec for epic_fail

- omnibus/README.md
Trigger a new build since we saw failures in the previous build.
> Format omnibus readme markdown

- spec/functional/assets/chefinittest
- spec/functional/resource/bff_spec.rb
> Fix tests on AIX

- lib/chef/provider/package/powershell.rb
- spec/unit/provider/package/powershell_spec.rb
- spec/unit/resource/powershell_package_spec.rb
This PR simplifies and optimizes some of the `powershell_out` calls in `powershell_package`.
> Simplify powershell_out calls in powershell_package

- lib/chef/mixin/params_validate.rb
- lib/chef/mixin/properties.rb
- lib/chef/property.rb
- lib/chef/provider.rb
- lib/chef/resource.rb
- spec/unit/mixin/params_validate_spec.rb
- spec/unit/mixin/properties_spec.rb
- spec/unit/property/validation_spec.rb
- spec/unit/resource_spec.rb
> Implement resource enhancement RFCs

- Gemfile.lock
- omnibus/Gemfile.lock
> Use the updated inspec gem - 1.51.18

- lib/chef/provider/package/powershell.rb
- lib/chef/resource/powershell_package.rb
- spec/unit/provider/package/powershell_spec.rb
- spec/unit/resource/powershell_package_spec.rb
This PR enhances `powershell_package` with a `source` parameter.
> Add powershell_package source param

- ci/verify-chef.sh
> Kill any orphaned tests

- lib/chef/resource/apt_package.rb
- lib/chef/resource/apt_preference.rb
- lib/chef/resource/apt_repository.rb
- lib/chef/resource/apt_update.rb
- lib/chef/resource/bash.rb
- lib/chef/resource/batch.rb
- lib/chef/resource/bff_package.rb
- lib/chef/resource/breakpoint.rb
- lib/chef/resource/cab_package.rb
- lib/chef/resource/chocolatey_package.rb
- lib/chef/resource/cookbook_file.rb
- lib/chef/resource/cron.rb
- lib/chef/resource/csh.rb
- lib/chef/resource/directory.rb
- lib/chef/resource/dnf_package.rb
- lib/chef/resource/dpkg_package.rb
- lib/chef/resource/dsc_resource.rb
- lib/chef/resource/dsc_script.rb
- lib/chef/resource/execute.rb
- lib/chef/resource/file.rb
- lib/chef/resource/freebsd_package.rb
- lib/chef/resource/gem_package.rb
- lib/chef/resource/git.rb
- lib/chef/resource/group.rb
- lib/chef/resource/homebrew_package.rb
- lib/chef/resource/http_request.rb
- lib/chef/resource/ifconfig.rb
- lib/chef/resource/ips_package.rb
- lib/chef/resource/ksh.rb
- lib/chef/resource/launchd.rb
Not all of them, but a good chunk. Also at some point we should figure out if this is the text we want to eventually show on the docs site.
> Add new introduced and description resource properties to many resources

- lib/chef/resource/mdadm.rb
> Modernize mdadm

- lib/chef/resource/powershell_package.rb
> Simplify how we define the powershell_package resource_name

- spec/unit/mixin/powershell_type_coercions_spec.rb
Accidentally reverted this in #6898 but i has nothing directly to do with the attribute rewrite and is useful to keep.
> Revert "Revert "fixup some unit tests""

- lib/chef/resource/cron.rb
> Convert parts of cron resource to use properties

- lib/chef/knife/environment_compare.rb
- lib/chef/knife/list.rb
> fix for master of chefstyle

- Gemfile.lock
- omnibus/Gemfile.lock
- spec/spec_helper.rb
- spec/unit/daemon_spec.rb
Mostly just to force a new build, but why not.
> One last Chef 12 dependency bump

- Gemfile
- Gemfile.lock
- omnibus_overrides.rb
already working for kitchen-appbundle-updater in travis
> use appbundler 0.11.1 for omnibus builds

- Gemfile.lock
hopefully one last time with feeling...
> bump appbundler again, again

- lib/chef/provider/route.rb
- lib/chef/resource/route.rb
This change allows you to specify a comment in route resources
N/A
> Allow specifying a comment for routes

- lib/chef/resource/git.rb
Modernize how we define this resource
> Set properties in git resource using our resource DSL

- lib/chef/provider/package/portage.rb
- lib/chef/resource/portage_package.rb
- spec/unit/resource/portage_package_spec.rb
> Modernize provides in the portage_package resource

- lib/chef/resource/windows_service.rb
> windows_service: Set identity on the properly not using identity_attr

- lib/chef/provider.rb
- spec/integration/recipes/resource_action_spec.rb
require writing `new_resource.my_property` instead of just
`my_property` in provider code.
a surprise in this code was that methods directly on the
resource are all injected into the provider, and we never
deprecated that, because we didn't know about it.
that makes `action_class {}` helpers unnecessary, but causes
additional namespace pollution, but at least the methods declared
in the resource will lose to DSL methods (i.e. `def execute`
will not work).
but that also means that resources which are injected into the DSL
which overwrite resource methods in other cookbooks may break
their use in that cookbooks providers/action_classes.
we should probably deprecate that as well, but we didn't and
people probably found this behavior and used it.
i cleaned it up a bit and removed the methods …
> remove deprecated property namespace collisions

- lib/chef/mixin/params_validate.rb
- lib/chef/mixin/properties.rb
- lib/chef/property.rb
- lib/chef/provider.rb
- lib/chef/resource.rb
- spec/unit/mixin/params_validate_spec.rb
- spec/unit/mixin/properties_spec.rb
- spec/unit/property/validation_spec.rb
- spec/unit/resource_spec.rb
Ensure we can use `description` and friends on later chef 13s.
> Backport RFC-101/RFC-104 resource enhancements

- lib/chef/api_client.rb
- lib/chef/chef_fs/data_handler/policy_data_handler.rb
- lib/chef/chef_fs/data_handler/policy_group_data_handler.rb
- lib/chef/cookbook/chefignore.rb
- lib/chef/data_collector/messages/helpers.rb
- lib/chef/provider/apt_repository.rb
- lib/chef/provider/zypper_repository.rb
- lib/chef/resource/resource_notification.rb
- lib/chef/run_context.rb
> Fix some yard warnings

- RELEASE_NOTES.md
- lib/chef/mixin/powershell_exec.rb
Adding further explanation and documentation as requested by #6941
> powershell_exec mixin - adding docs and examples

- lib/chef/provider/mount.rb
- lib/chef/provider/mount/aix.rb
- lib/chef/provider/mount/mount.rb
- lib/chef/provider/mount/solaris.rb
- lib/chef/resource/mount.rb
- spec/unit/provider/mount/mount_spec.rb
- spec/unit/provider/mount/solaris_spec.rb
- spec/unit/resource/mount_spec.rb
> update mount to use properties and fix 6851

- lib/chef/win32/security.rb
LsaFreeMemory takes a pointer to the struct in memory created by LsaEnumerateAccountRights.
We have to pass it the actual pointer, not the FFI::MemoryPointer object.
This fixes masked access violations which occasionally lead to a heap corruption which
presents itself as silent termination of chef-client/ruby with a return code of -1073740940
or STATUS_HEAP_CORRUPTION / 0xc0000374.
Fixes #6589, Backport of #6980
> Pass pointer to LsaFreeMemory, not FFI::MemoryPointer

- Gemfile.lock
- omnibus/Gemfile.lock
This already ran through Jenkins w/o issue and gives us a build with libarchive on all platforms (even AIX!)
> Use Chef omnibus def that includes libarchive

- lib/chef/resource/apt_package.rb
- lib/chef/resource/apt_preference.rb
- lib/chef/resource/build_essential.rb
- lib/chef/resource/openssl_rsa_private_key.rb
- lib/chef/resource/powershell_package.rb
- lib/chef/resource/python.rb
- lib/chef/resource/reboot.rb
- lib/chef/resource/remote_directory.rb
- lib/chef/resource/remote_file.rb
- lib/chef/resource/ruby.rb
- lib/chef/resource/ruby_block.rb
- lib/chef/resource/scm.rb
- lib/chef/resource/script.rb
- lib/chef/resource/subversion.rb
- lib/chef/resource/template.rb
- lib/chef/resource/windows_env.rb
- lib/chef/resource/yum_package.rb
More general resource cleanup. Add more resource descriptions and convert resources to use properties
> Add more resource descriptions and convert resources to use properties

- lib/chef/provider/mount.rb
- lib/chef/provider/mount/aix.rb
- lib/chef/provider/mount/mount.rb
- lib/chef/provider/mount/solaris.rb
- lib/chef/resource/mount.rb
- spec/unit/provider/mount/mount_spec.rb
- spec/unit/provider/mount/solaris_spec.rb
- spec/unit/resource/mount_spec.rb
Move to properties, ensure that mount points only appear once.
> Backport mount provider fixes to 13

- lib/chef/resource/link.rb
- lib/chef/resource/log.rb
- lib/chef/resource/ohai.rb
- lib/chef/resource/ohai_hint.rb
- lib/chef/resource/package.rb
- lib/chef/resource/perl.rb
- lib/chef/resource/remote_file.rb
- lib/chef/resource/sudo.rb
> Add more resource descriptions and convert more resources to use properties

- lib/chef/provider/package.rb
This is a 10% perf gain for lightweight use of package resources like `build_resource(:yum_package, 'lsof').current_value.version`
> memoize some work in the package class

- lib/chef/resource/mount.rb
> [chef-13] support nils because of course

- lib/chef/resource/windows_feature_dism.rb
This issue was reported on the cookbook after refactoring the resource. The issue is that we have a method to determine the features to install given a list of features we want to install. It wasn't taking into account that a removed feature can be installed if the user specifies a source. Now it properly takes that into account and should build the correct array of features to install. It also builds the install command in a cleaner way that avoids funky extra spaces at the end of the command.
> Support installing removed windows features from source

- lib/chef/chef_fs/command_line.rb
- lib/chef/config_fetcher.rb
- lib/chef/data_collector.rb
- lib/chef/dsl/platform_introspection.rb
- lib/chef/file_access_control/unix.rb
- lib/chef/knife/deps.rb
- lib/chef/monkey_patches/net_http.rb
- lib/chef/provider/package/rpm.rb
- lib/chef/util/windows/net_user.rb
- spec/unit/knife/osc_user_reregister_spec.rb
- spec/unit/knife/osc_user_show_spec.rb
- spec/unit/user_spec.rb
some cops got a little stricter.
> rubocop fixes from engine bump to 0.54.0

- lib/chef/application.rb
- lib/chef/provider/execute.rb
This is a rescue of @thelunaticscripter's PR, which Fixes: #6203
> Suppress nested causes for sensitive exceptions

- lib/chef/provider/mount/solaris.rb
- lib/chef/resource/mount.rb
> partially revert 61e3d4bb: do not use properties for mount

- CHANGELOG.md
> Add missing Chef 13.8 release to the notes

- README.md
> Update information on updating gems / Expeditor

- lib/chef/resource/apt_update.rb
- lib/chef/resource/dmg_package.rb
- lib/chef/resource/powershell_script.rb
- lib/chef/resource/rhsm_errata.rb
- lib/chef/resource/rhsm_errata_level.rb
- lib/chef/resource/rhsm_register.rb
- lib/chef/resource/rhsm_repo.rb
- lib/chef/resource/rhsm_subscription.rb
Use the same format that the docs team approved throughout and make a
few minor changes
> Add / update resource descriptions

- lib/chef/resource/sudo.rb
Adds ruby type for `visudo_binary` property
> Sudo resource: specify ruby type for visudo_binary

- RELEASE_NOTES.md
Sorry I didn't catch this before.
> [Release Notes] s/systctl/sysctl

- lib/chef/resource/windows_ad_join.rb
> [windows_ad_join] add description for :join action

- lib/chef/resource/windows_font.rb
> [windows_font] get rid of "remove" in description

- lib/chef/resource/dmg_package.rb
I'll get this fixed in the cookbook as well.
> Fix method missing error in dmg_package

- lib/chef/application.rb
Edge case but nice to have and shouldn't hurt anything.
> Address possible gem installs between interval runs that are then used in the config

- lib/chef/resource/windows_printer_port.rb
> [windows_printer_port] fix typo + add action descriptions

- RELEASE_NOTES.md
Add all the knife deprecations
Add the chef solo -r deprecation
Add a note about the changes to the windows_feature resources
Add the node.set / node.set_unless deprecation
> Update Chef 14 release notes

- lib/chef/resource/rhsm_register.rb
This fix came into the cookbook repo at https://github.com/chef-partners/redhat-subscription-manager-cookbook/pull/41
> Fix RHSM registration using passwords

- .expeditor/config.yml
> Expeditor docs are available over http

- lib/chef/provider/package/yum/python_helper.rb
- lib/chef/provider/package/yum/yum_helper.py
- spec/functional/resource/yum_package_spec.rb
use one array, shove them in the array in order, read them out
and apply them...
close #7118
> fix for enable/disable repo ordering

- lib/chef/knife.rb
- lib/chef/knife/core/bootstrap_context.rb
- lib/chef/knife/ssh.rb
ensure that trace level is selectable if necessary via -VVV
Pass the correct object to net/ssh
> Fix up knife logging

- .github/lock.yml
https://github.com/dessant/lock-threads
> add support for lock bot

- lib/chef/provider/package/yum/yum_helper.py
Catch json.load exceptions causing syslog errors 
https://github.com/chef/chef/issues/7153
>  Catch json.load exceptions causing syslog errors 

- RELEASE_NOTES.md
> Add 14.0.202 release notes

- lib/chef/provider/package/yum/yum_helper.py
apply the magic in the redhat bugzilla bug report
closes #7126
> fix for Red Hat Satellite yum_package bug

- lib/chef/resource_inspector.rb
@tas50 is there anything else that jumps out as being a useful addition?
> add name_property to resource inspector

- .travis.yml
Not sure how this got in there, but we certainly don't need it.
> Remove duplicate knife-windows travis testing

- lib/chef/provider/ifconfig/debian.rb
- spec/functional/resource/apt_package_spec.rb
- spec/functional/resource/ifconfig_spec.rb
> Ubuntu 1804 - passing tests and fixed ifconfig provider

- lib/chef/provider/service/debian.rb
- spec/unit/provider/service/debian_service_spec.rb
Debian removed the no-op flag from update-rc.d, and so we're now
unlinking services rather than just querying them. Just parsing the
scripts ourselves is much safer.
Fixes: #7119
> [Debian/Ubuntu] Detect init script service levels

- README.md
trying to sort out weirdness from this morning
> whitespace fix to make expeditor run
