chef/chef

lib/chef/provider/systemd_unit.rb, lib/chef/resource/systemd_unit.rb
systemd's pretty strict with the verification rules. it's usually possible to make it work, but this adds an escape hatch for if the verifier is too strict, or for use in debugging, since verifier output isn't surfaced right now.
permits users to opt out of resource verification
helps with situations like #5931 and #5909. a full fix for #5931 that actually surfaces err output is incoming, but as a separate PR (#5972) since it touches more than just the systemd_unit resource.
=> systemd_unit verifier escape hatch

lib/chef/chef_fs/chef_fs_data_store.rb, spec/integration/knife/serve_spec.rb
Add real support for rb files (at least roles) in knife-serve
chef/chef-zero#107 claims knife-serve supports rb files.
It wasn't the case before this patch:
`knife serve & (sleep 5knife raw -s http://localhost:8889 /role)` shows truncated      names for rb roles.
This was due to the way filenames are transformed to object names.
This patch only tests behavior for roles.
=> Add real support for rb files (at least roles) in knife-serve

lib/chef/provider/user/linux.rb
Signed-off-by: Maxime “pep” Buquet <pep@collabora.com>
`-u` (uid) parameter is required by usermod when using `-o` (non_unique). This patch adds the parameter if needed.
I don't have tests for it as apparently there is no test yet for usermod in the linux_spec. I can try to come up with some tests if somebody quickly guides me through it.
=> Add -u param to usermod in linux_user resource when using non_unique

RELEASE_NOTES.md, chef-config/lib/chef-config/config.rb, lib/chef/cookbook/gem_installer.rb, lib/chef/provider/package/rubygems.rb, lib/chef/resource/gem_package.rb, spec/unit/cookbook/gem_installer_spec.rb, spec/unit/provider/package/rubygems_spec.rb
By default now we don't pass any --source option or set the
`Chef::Config[:rubygems_url]` to anything.  This is so that
if there is external config for rubygems sources we will simply
have rubygems pick it up and use it (the resource acts like
the command line).
There is also no more magic around `--clear-sources` and if you
set the property it sets the flag.
If the `Chef::Config[:rubygems_url]` setting is set then that
becomes the default `--source` flag sent to the command.  This
also supports Arrays now.
If the `source` option is set to a URI (it can also be set to a
filesystem path for poorly-designed-API reasons) then we do not
use the default values at all.  This may be an API break but this
much more clearly allows users to override individual resources
and is more declarative. …
=> Chef-13:  tweaks to rubygems source option for urls

lib/chef/application/exit_code.rb, lib/chef/application/windows_service.rb, lib/chef/config_fetcher.rb, lib/chef/exceptions.rb, lib/chef/platform/rebooter.rb, spec/functional/rebooter_spec.rb, spec/integration/client/exit_code_spec.rb, spec/unit/application/exit_code_spec.rb, spec/unit/application_spec.rb, spec/unit/config_fetcher_spec.rb
Sets a default in Chef::Config for `exit_status` to `:enabled`.
Removes uses of deprecated exit codes from the Chef code base.
Changed the deprecation warning/error to a warning message when attempting to exit with a non-standard exit code while standard exit codes are enforced.
=> Make Standardized Exit Codes The Default Behavior

Gemfile, Gemfile.lock, omnibus/config/software/chef-gem-inspec.rb, omnibus/config/software/chef.rb
This change adds InSpec as a dependency of Chef, making it easier
for our community to use InSpec for testing without requiring
them to `chef_gem` install it prior to use.
This also helps our users who wish to use InSpec but are in an
air-gapped environment. Including our preferred testing library
in our Omnibus builds will make it much easier for those users
to use InSpec.
=> Add InSpec to chef omnibus builds

lib/chef/data_bag_item.rb, spec/unit/data_bag_item_spec.rb
=> Ensure DataBagItems are a Mash

RELEASE_NOTES.md, lib/chef/cookbook_version.rb, lib/chef/run_context/cookbook_compiler.rb, spec/data/cookbooks/aliased/attributes.rb, spec/data/cookbooks/aliased/metadata.rb, spec/data/cookbooks/aliased/recipe.rb, spec/functional/root_alias_spec.rb, spec/unit/cookbook_loader_spec.rb
https://github.com/chef/chef-rfc/blob/master/rfc033-root-aliases.md
tl;dr this makes it so you can use `mycookbook/attributes.rb` and `mycookbook/recipe.rb` instead of folders. For attributes this should probably be the dominant use case since having multiple attribute files is almost always more confusing than anything else. For recipes, this is nice for simple use cases, though there are plenty of good reasons to have many recipes so for those cases they should continue to use the folder.
=> Implement RFC033: Root aliases

acceptance/data-collector/.acceptance/data-collector-test/metadata.rb, lib/chef/knife/cookbook_create.rb
We’re trying to get everything to use these so we can have standardized values in Supermarket. All Rights Reserved is clearly not a standard license and that’s just life.
=> Have knife cookbook generate use SPDX standard license strings

Gemfile.lock, chef-config/lib/chef-config/config.rb, lib/chef/event_dispatch/base.rb, lib/chef/node.rb, lib/chef/run_context/cookbook_compiler.rb, spec/integration/client/client_spec.rb
RFC 59 - Load ohai plugins, take 2. This just uses a new ohai system context to run all the plugins.
replaces #6007
=> RFC 59 - Load ohai plugins

RELEASE_NOTES.md, chef-config/lib/chef-config/config.rb, lib/chef/provider/package/rubygems.rb, lib/chef/resource/gem_package.rb, spec/unit/provider/package/rubygems_spec.rb
I think this is better
- Chef::Config[:rubygems_uri] is nearly always applied (but
could be set to nil if someone really wanted to opt-out)
- the per-resources sources are additive on top of the
global config (lets cookbooks be additive to global config
rather than override it by default).
- there's a new flag for if you want to opt-out of the global
config completely on a per-resource basis.
So I think this gets the most commmon and the next most common
use cases correct, while still allow people with arbitrarily
crazy needs to write resources that do it.
The RELEASE_NOTES also have somewhat better user stories in them,
which I think suggests that I'm on the right track here.
=> Chef-13: better solution to gem_package source issues

RELEASE_NOTES.md, lib/chef/application.rb, lib/chef/application/windows_service.rb, lib/chef/client.rb, lib/chef/knife/configure.rb, lib/chef/knife/configure_client.rb, spec/integration/client/client_spec.rb, spec/unit/application_spec.rb, spec/unit/client_spec.rb, spec/unit/knife/configure_client_spec.rb
This should remove all of the magic.
This makes `chef-client > /tmp/client.out` log with the formatter.
It also makes the default log format the formatter.
It also eliminates the magical addition of a STDOUT formatter when a log formatter is configured in client.rb
closes #2514
There may be a little bit of overrreach here in that someone might be using the magic additional logger to capture logs of all command line invocations of chef-client, which will now be removed.  I tend to feel like that's a better use case for event handlers, the data collector, etc.  Its a very poor-mans solution and i think it had fairly poor features since i think it would switch log formats based on how you invoked it.  At any rate, if people show up who really want that kind of behavior back, I'd say we …
=> Chef-13:  remove magic from the logger/formatter settings

lib/chef/client.rb, spec/integration/client/client_spec.rb, spec/support/shared/context/client.rb, spec/unit/client_spec.rb
when the chef-server is configured to serve a requried recipe,
chef-client shall load the recipe into the run context and
execute it as part of the converge phase.
if the chef-server is NOT configured, it will return a 404 and
chef-client will continue normally.
Signed-off-by: Stephen Delano <stephen@chef.io>
See above.
See also:
* https://github.com/chef/chef-rfc/pull/258
* https://github.com/chef/chef-server/pull/1214
* https://github.com/chef/chef-rfc/pull/258
=> server enforced required recipe

RELEASE_NOTES.md, lib/chef/application.rb, lib/chef/application/windows_service.rb, spec/unit/application_spec.rb
This backs out a bit of #5851 that was probably too aggressive.
=> Chef-13: restore log_location in client.rb

lib/chef/provider/package.rb, spec/unit/provider/package/apt_spec.rb
#5838 was a bug fix that we need in chef 12 but got missed when we branched, so make sure we keep it.
=> Ensure the apt package fix gets on chef-12 branch

lib/chef/client.rb, spec/unit/client_spec.rb
The previous log message didn't have enough context and could sound
"scary" to users unfamiliar with the feature.
Signed-off-by: Daniel DeLeo <dan@chef.io>
Adds more context to the log message that's emitted when the 'required recipe' feature isn't enabled, to make it sound less scary.
Before: `[timestamp] INFO: Required Recipe not found`
Now: `[timestamp] DEBUG: Required Recipe not configured on the server, skipping it`
The message was also moved to debug as it unlikely to be useful information most of the time.
Additionally, an info message was added for the case that the required recipe is configured.
Issue was reported in Chef's slack channel, no ticket.
=> Clarify log messaging for required recipe feature

lib/chef/client.rb, spec/support/shared/context/client.rb, spec/unit/client_spec.rb
Backport #6032 -- we want folks to be able to use this without upgrading to 13.
n/a
=> Backport #6032 (required recipe) to Chef 12

lib/chef/provider/package.rb, lib/chef/provider/package/yum.rb, spec/unit/provider/package/yum_spec.rb
We should probably audit the tests for more of this pattern of using rspec-mocks on the resource object, might be other resource-y changes that we've missed for the same reason. This should make `options` work again on Yum-y platforms.
Ping @chef/client-core and @chef/client-enterprise-linux for review, should probably get hotfix'd.
Fixes https://github.com/chef/chef/issues/6046.
=> Fix some fallout from the options converstion to an array

acceptance/fips/.acceptance/acceptance-cookbook/recipes/destroy.rb, acceptance/fips/.acceptance/acceptance-cookbook/recipes/provision.rb, acceptance/fips/.acceptance/acceptance-cookbook/recipes/verify.rb, omnibus/Gemfile, omnibus/Gemfile.lock
`gem` has mysteriously disappeared on Windows. Our hero is venturing on to the dark paths to hunt down the missing command, and coax it lovingly in to returning to the light of a chef release.
Bug #6049 has the gory details
=> Ensure the gem binary is installed on windows

.expeditor/config.yml, .expeditor/update_version.sh
Expeditor is the next-generation utility that we'll use for version bumping. It will include additional features that we don't currently have like the ability to not bump a version on a specific PR.
=> Add expeditor

lib/chef/knife/client_key_create.rb
Signed-off-by: Daniel DeLeo <dan@chef.io>
The command didn't have a banner so `knife` showed the default one:
```
$ bundle exec bin/knife client key create -h
Usage: bin/knife (options)
...
```
I'm not aware of a bug ticket.
=> Add usage banner for knife client key create

lib/chef/run_context.rb, lib/chef/runner.rb, spec/unit/runner_spec.rb
because surfing through ObjectSpace makes kittens cry
=> add a pointer from the run_context back to the runner

tasks/changelog.rb
Allow running specs offline. Done fetch latest version information unless required
Changelog related rake task always attempt to obtain latest version information.
=> (chore)fetch latest stable version only if its required

chef.gemspec
There is no such directory, no need to require it.
=> Remove lib-backcompat dir from require_path

lib/chef/resource/env.rb, lib/chef/resource/route.rb, lib/chef/resource/service.rb, lib/chef/resource/user.rb, spec/functional/resource/registry_spec.rb, spec/support/shared/unit/provider/useradd_based_user_provider.rb, spec/unit/provider/env_spec.rb, spec/unit/provider/group/dscl_spec.rb, spec/unit/provider/group/pw_spec.rb, spec/unit/provider/group/usermod_spec.rb, spec/unit/provider/group/windows_spec.rb, spec/unit/provider/group_spec.rb, spec/unit/provider/http_request_spec.rb, spec/unit/provider/package/aix_spec.rb, spec/unit/provider/package/apt_spec.rb, spec/unit/provider/package/ips_spec.rb, spec/unit/provider/package/macports_spec.rb, spec/unit/provider/package/pacman_spec.rb, spec/unit/provider/package/yum_spec.rb, spec/unit/provider/route_spec.rb, spec/unit/provider/service/arch_service_spec.rb, spec/unit/provider/service/init_service_spec.rb, spec/unit/provider/service/invokercd_service_spec.rb, spec/unit/provider/service/simple_service_spec.rb, spec/unit/provider/service/upstart_service_spec.rb, spec/unit/provider/service_spec.rb, spec/unit/provider/user/pw_spec.rb, spec/unit/provider/user_spec.rb
This kind of got away from me as it turns out a whole bunch of tests were assuming nillable properties. I converted the two easy ones (`env` and `route`) so that's just done, for the others I could either revert the test changes or we can live with annoying hacks for nillable stuff for the few cases where it was breaking tests.
=> Clean up more stubbed properties in tests

omnibus/Gemfile.lock
This updates the Gemfile.lock so that Chef 12 can build successfully.
Fixes building since the version of omnibus which was previously pinned was broken.
/cc @sdelano
=> Update omnibus/Gemfile.lock for Chef 12.

.travis.yml
the travis precise openssl libs appears to hate rubygems and we should
do this anyway.
=> switch to using trusty on travis

MAINTAINERS.md, MAINTAINERS.toml
Volunteering to be a core maintainer if additional maintainers
are desired.
=> Adding Adam Leff as maintainer

lib/chef/resource/windows_task.rb, spec/unit/resource/windows_task_spec.rb
Signed-off-by: Corey Hemminger <corey.hemminger@nativex.com>
allows day option for windows_task with monthly frequency. 
This should fix issue #6104
=> Updated to fix day validation with monthly frequency

lib/chef/cookbook/synchronizer.rb, spec/unit/cookbook/synchronizer_spec.rb
cookbook_segment returns nil if the cache is not found in the manifest.
This can happen when chef client 12 runs on a node where chef client 13
generated cookbook cache files.
Currently, chef client fails in this case. This patch fixes it.
It should be safe to remove those cache files because they are not
cached in Chef 12, after all.
https://github.com/chef/chef/issues/6128
=> Discard caches for files not in the manifest

lib/chef/provider/package/cab.rb, lib/chef/provider/package/msu.rb
Updates the `cab_package` resource (which supports the `msu_package` resource) to validate the name and the version, not just the name.
Fixes #6091
=> cab_package should comare package name and version, not just name

lib/chef/platform/service_helpers.rb, spec/unit/provider_resolver_spec.rb
Signed-off-by: Grant Ridder <shortdudey123@gmail.com>
On newer Debian based systems that use systemd to have a package install a SysV init and Upstart script.  Systemd can use systemd service files or SysV init scripts.  However, on the Chef serivce provider side, this is not reflected.  So in this case, Upstart will be prefered even if Upstart itself is not installed on the system.
Service resource failing to modify a service on a systemd based host that has SysV init and Upstart scripts.
closes #6076
=> Prefer Systemd with sysvinit script over Upstart for service provider

lib/chef/mixin/which.rb, lib/chef/provider/package/rubygems.rb, spec/unit/provider/package/rubygems_spec.rb
Previously we injected our expected paths in to ENV['PATH'] but we
stopped doing that in Chef 13; for gem_package, we need to ensure that
if all else fails we'll use the Omnibus provided gem binary, but we
should never pick that if we can find a different one.
Closes: #6103
cc @lamont-granquist @chef/maintainers
=> Ensure that we check the embedded gem binary last

RELEASE_NOTES.md
The wrong link was put into the release notes
=> Fix ohai deprecation link in the release notes

spec/functional/resource/chocolatey_package_spec.rb
This is a bit of a workaround for now. We need to get Chocolatey back on the windows jenkins builders so we can get green tests. This gets us green for the 13.1 release though.
=> Only run the Chocolatey tests if Chocolatey is installed

RELEASE_NOTES.md, lib/chef/application/client.rb, lib/chef/application/knife.rb, lib/chef/deprecated.rb, lib/chef/local_mode.rb
Fixes https://github.com/chef/chef/issues/6088, docs in https://github.com/chef/chef-web-docs/pull/687.
The only case where this is likely to matter is the chef-provisioning stuff mentioned in #6088, which is few enough people that I'm calling this a security fix.
=> Use socketless local mode by default

lib/chef/formatters/error_description.rb, spec/unit/formatters/error_description_spec.rb
Backporting #5987 for the next Chef 12 release. Will maybe make support a little easier for people that end up stuck on 12 forever.
=> Backport error info for Chef 12

lib/chef/application.rb, lib/chef/application/client.rb, spec/unit/application/client_spec.rb
We can't reconfigure in a trap context because we might open files or another activity that could cause a deadlock. Ruby 2.0+ now prevents this by raising a ThreadError.
Fixes #4578, Replaces #6119.
=> reconfigure between runs when running in a loop

CLA_ARCHIVE.md
Now that Chef has moved to DCO, update the CLA archive to include companies and individuals from Supermarket's time as the CCLA/ICLA system of record.
=> update CLA archive

chef-config/lib/chef-config/package_task.rb, lib/chef/deprecated.rb, lib/chef/dsl/declare_resource.rb, lib/chef/provider.rb, lib/chef/version.rb, spec/integration/recipes/accumulator_spec.rb, spec/integration/recipes/resource_action_spec.rb, spec/integration/recipes/resource_load_spec.rb
This forces everyone to starting using new_resource.property_name
instead of just property_name.
closes #5974
=> Deprecate property namespace magic

lib/chef/property.rb
We could (and probably should) fix this in each cookbook but this has been the cause of enough issue spam that a special case seems warranted, especially since it is only needed on the 12.x branch and won't live on in 13.
=> Special case for the supports pseudo-property for Chef 12.

lib/chef/policy_builder/policyfile.rb, spec/unit/policy_builder/policyfile_spec.rb
This fixes a bug where the `expanded_run_list` was not being sent to `data_collector` for policy nodes.
=> Properly send run_list_expanded event in policy node case

acceptance/top-cookbooks/.kitchen.docker.yml
the port 80 keyservers pool is really unreliable
=> use the HA pool for the docker acceptance test

lib/chef/provider/execute.rb, spec/functional/resource/execute_spec.rb, spec/unit/provider/apt_update_spec.rb, spec/unit/provider/execute_spec.rb, spec/unit/provider/script_spec.rb
This may be a breaking change for some users coming from 13.0/13.1
but this was the intended way that this API would function in Chef 13.0.
With this change we stop inserting environment variables into
execute resources.  That means that whatever users type into the
execute resource should much more exactly agree with the response
on the command line, which will close a shedload of bugs and is how
Chef 13.0 was intended to operate.  We no longer globally mangle the
PATH or the LANG/LC_ locale environment variables.
The way that it worked in Chef 13.0/13.1 resulted in the internal
chef embedded/bin directory being prepended to the PATH environment
variable in the `execute` resource, which was never intended.
closes #6239
=> fix execute resource to use shell_out_with_systems_locale

lib/chef/http/api_versions.rb, lib/chef/server_api_versions.rb, spec/unit/server_api_versions_spec.rb
If we don't see a version header, we should default to only supporting
API version 0, and if we can't support that, then we should die as usual
=> Have a sensible default for old chef servers

lib/chef/provider/package/zypper.rb, spec/unit/provider/package/zypper_spec.rb
the `options` property was ignored on the `zypper` package resource. This adds it.
@chef/engineering-services 
resolves https://github.com/chef/chef/issues/6011
=> Enable zypper package options

Gemfile, omnibus/config/projects/chef.rb, omnibus_overrides.rb
this hand-builds it with the software dep, and its not a direct dep of
chef itself and shouldn't be in the Gemfile.lock anyway, plus we need
to pin via omnibus_overrides.rb and double-pinning in the Gemfile.lock
is just added fussiness
=> move nokogiri config to omnibus

lib/chef/provider/service/systemd.rb, lib/chef/provider/systemd_unit.rb, spec/unit/provider/service/systemd_service_spec.rb, spec/unit/provider/systemd_unit_spec.rb
Chef currently passes the string representing the name of a service (i.e. of the unit in systemd land) directly on the `systemctl` command line when shelling out. This causes issues for units containing escape sequences (e.g. autogenerated units like `dev-dm\x2d1.swap`), which will result in Chef calling `systemctl start dev-dm\x2d1.swap`, which doesn't work as the shell reads the `\` as a control character. This PR fixes the problem by always calling `.shellescape` when using the service name in a command line for the systemd `service` provider and the `systemd_unit` provider.
N/A
=> Ensure the service_name is always escaped when using systemd

lib/chef/knife/core/bootstrap_context.rb, spec/unit/knife/bootstrap_spec.rb
This should help bootstrapping with policies
Fixes: #5353
=> If we don't have a run_list, don't send it

omnibus/Gemfile.lock
I ran `bundle update omnibus` - if that isn't the current way of updating, please fix as appropriate.
=> Update omnibus pinning to enable automated s3 omnibus cache population

.expeditor/config.yml
Update the `.expeditor/config.yml` to use the new-style merge-action declaration syntax.
cc @schisamo @thommay @lamont-granquist
=> Use new Expeditor config format

omnibus/config/projects/chef.rb
The cert has been updated as the old one expires on 2017-07-25. The new cert has also been deployed to our build infrastructure. 
=> Update SHA1 fingerprint for MSI signing cert

appveyor.yml, lib/chef/provider/windows_task.rb, spec/unit/provider/windows_task_spec.rb
Signed-off-by: MSys <harikesh.kolekar@msystechnologies.com>
Since `windows_task` moved into core, the expectation is that the `:create` action can take the place of the old `:change` action (since it has the same attributes).  In fact, the plan sounds like that `:change` action can just be aliased to `:create` to prevent legacy breakage.  However, the `:create` action will break if the `command` attribute is not specified (like it would be in a preexisting `:change` action): ` undefined method `tr' for nil:NilClass`
*Expected Results*:  The windows_task resource can be modified by resource name without having to specify the command
=> [MSYS-586] Allow windows_task create action to update tasks.

appveyor.yml
@harikesh-kolekar believes we'll have better luck on the 'Previous' 2015 image rather than 2013.
=> Use the previous VS 2015 image in appveyor instead of 2013

lib/chef/knife/core/status_presenter.rb, spec/unit/knife/status_spec.rb
Fixes https://github.com/chef/chef/issues/6277
Added `node['platform']` and `node['platform_version']` attributes in
the unit test to trigger the "can't modify frozen String" error which wasn't
being thrown in the unit tests before.
Fixed by doing shallow copy of `node['platform']` on assignment.
Signed-off-by: Jeremy J. Miller <jm@chef.io>
https://github.com/chef/chef/issues/6277
=> avoid mutation attempt of node['platform']

Gemfile.lock
#6271 requires mixlib-shellout 2.3 for elevated functionality merged in https://github.com/chef/mixlib-shellout/pull/149.
=> Bump mixlib-shellout for #6271

appveyor.yml, lib/chef/provider/execute.rb, lib/chef/resource/execute.rb, spec/unit/resource/powershell_script_spec.rb
Added :elevated option for powershell_script resource. This should be merged after https://github.com/chef/mixlib-shellout/pull/148
fixes https://github.com/chef/chef/issues/6086
=> Added :elevated option for powershell_script resource

Gemfile, Gemfile.lock, lib/chef/http.rb, spec/spec_helper.rb, spec/unit/http/api_versions_spec.rb, spec/unit/server_api_spec.rb
on the first pass through the JSON middleware it encodes the
body.  if there's a retry, it re-encodes the body as a string
with all its metacharacters escaped.
this is a particular issue when doing a first request that is
a POST that requires negotiating the API version.  when doing a
GET it isn't a problem because there's no body payload -- but a
POST or a PUT which requires a retry will get garbled and will
cause a 500.
this happens on hosted right now if trying to POST with a v2
API since hosted is only v1, so there's a retry to downgrade.
i also made the same kind of changes to the streaming download
requests, but since they're GETs its unclear to me if there was
any impact there -- but middleware could have been double-mangling
headers on a retry.
=> fix retries on JSON POST requests

lib/chef/cookbook/metadata.rb, spec/unit/cookbook/metadata_spec.rb, spec/unit/knife/cookbook_show_spec.rb
chef server returns a 400.  we could prune nil values out of the
JSON but then it'd be difficult to specify a "null" JSON value if we
really needed one.  seems better to follow the pattern of using
empty string here (which i tested against Hosted and works).
=> chef server rejects metadata with nil maintainer

appveyor.yml
@FeodorFitsner reports that https://github.com/appveyor/ci/issues/1657 has been fixed for the VS 2015 images.
=> Switch to current VS 2015 Appveyor Image

lib/chef/http/http_request.rb, lib/chef/provider/http_request.rb, lib/chef/resource/http_request.rb
Add support for HTTP PATCH requests 
http_request cannot send PATCH requests - limiting usefulness when working with APIs which require them
=> Add support for HTTP PATCH requests

lib/chef/provider/package/windows/registry_uninstall_entry.rb
Closes #6217.
The reason why we do `to_s.rstrip` is to handle the (potentially weird case of) `display_name` being `nil`, in which case we will otherwise get an unfriendly Ruby error message.
=> Handle display names with trailing spaces

lib/chef/knife/ssh.rb, spec/unit/knife/ssh_spec.rb
Depending on the setting of the server, the session times out when we run a long-time task with `knife ssh`.
This PR makes if ssh_config has ServerAliveInterval setting, change it so that it can be used.
- https://forums.aws.amazon.com/thread.jspa?threadID=228154
- http://qiita.com/kackytw/items/49e2d10512b197089502
=> use ServerAliveInterval option if exists in ssh_config by `knife ssh`.

lib/chef/provider/apt_preference.rb, lib/chef/providers.rb, lib/chef/resource/apt_preference.rb, lib/chef/resources.rb, spec/unit/provider/apt_preference_spec.rb, spec/unit/resource/apt_preference_spec.rb
Pull in the apt_preference provider from the apt cookbook. This fully deprecates the apt cookbook.
N/A
Specs are a placeholder on the provider side
=> Apt: Add apt_preference resource from apt cookbooks

lib/chef/search/query.rb, spec/functional/knife/ssh_spec.rb, spec/unit/search/query_spec.rb
The previous code would advance the search start parameter by either
the user-provided rows parameter or (as a fallback) the number of rows
returned in that page.  Most code that calls the search() function
does not set rows, so the fallback is used often.
Since the search index may have stale results, it is possible to get
responses with a completely empty page. For example:
{
"start": 0,
"total": 1,
"rows": []
}
In this case, if no rows parameter was passed, the search function
would infinitely recurse (eventually running out of stack).
To avoid this, we set rows to 1000 if no user-provided value was set.
This is the default page size of Chef Server so for most users it will
not be changing the default behavior.
Signed-off-by: Steven Danna <steve@chef.io>
Fixes #4329
Fixes #5783
=> Set explicit page size for every search request

.dockerignore
Our container image does not require any files from the local path. This PR adds a `.dockerignore` file that will ensure none of the local system files get copied over to the container image when it is built. This should reduce the size of the resulting container image.
=> Add .dockerignore to reduce size of resulting images

CONTRIBUTING.md
Previously the first dash in `--amend` was a unicode en dash (U+2013) rather than a hyphen, which results in the confusing:
```
$ git commit –-amend -s
error: pathspec '–-amend' did not match any file(s) known to git.
```
=> Fix git command in DCO sign-off example

spec/unit/provider/package/windows/registry_uninstall_entry_spec.rb, spec/unit/provider/package/windows_spec.rb
This adds missing test coverage for https://github.com/chef/chef/pull/6280.
=> MSYS-631 Added tests for Chef::Provider::Package::Windows::RegistryUninstallEntry.find_entries

lib/chef/exceptions.rb, spec/unit/provider/dsc_resource_spec.rb
Signed-off-by: Tor Magnus Rakvåg <tm@intility.no>
Currently, MultipleDscResourcesFound errors are unreadable due to the (usually) large object which is returned. This change adresses this by printing only the name and discovered versions of the dsc resources.
Talked to @thommay in the chef community slack #chef-dev channel.
=> throw readable errors if multiple dsc resources are found

lib/chef/resource/zypper_repository.rb, spec/unit/resource/zypper_repository_spec.rb
=> Maintain compat with old zypper_repo resource used in cookbooks

README.md
Since I am a new user of Chef, I was confused about how to start Chef development.
It is better to divide User and Developer instructions clearly in README.md.
For example,
- Add "Getting Started" section for User
- Change "Installing From Git" section to "Installing From Git for Developers"
It is easy to understand to add the following link to "Getting Started" as the reference for User.
https://docs.chef.io/quick_start.html
README.md improvement.
=> README improvement for Chef beginner.

CHANGELOG.md
We're obviously missing a chunk of Chef 13, but this gets us several releases closer
=> Catch Chef 12 changelog up to current 12 release

.bundle/config, .expeditor/update_version.sh
Fix the auto-bumping by removing the bundle lock that was preventing us from updating the Gemfile.lock.
=> Update Gemfile.lock without attempting to install Gems

lib/chef/resource.rb, spec/unit/resource_spec.rb
Fixes #6320, which can cause all kinds of fun cascade errors since we invoke to_text as part of the error display.
=> Ignore validation errors in Resource#to_text

lib/chef/mixin/deep_merge.rb, spec/unit/node_spec.rb
Fix an issue where DeepMerge overwrites nil values when run against a VividMash.
Call .key? instead of [] when checking if a key exists for a VividMash
Otherwise the VividMash will return an empty object instead of nil for
that key.
Fixes https://github.com/chef/chef/issues/6302
=> Fix an issue where DeepMerge overwrites nil values

lib/chef/shell.rb, lib/chef/shell/shell_session.rb, spec/unit/shell/shell_session_spec.rb
Fixes an issue in chef-shell whereby runlists passed in via a json file using the -j flag would not be loaded when running chef-shell in client mode using the -z flag.
Adds unit tests on top of #6313
=> Pass json configuration to ShellSession class

CHANGELOG.md
A more perm solution to this problem would be nice, but until then we're forward porting changelog entries.
=> Add v12.21.4 to master's changelog

lib/chef/provider/zypper_repository.rb, lib/chef/resource/zypper_repository.rb
Without this anything that's gpg signed will fail waiting for the user to accept or deny the key. If users don't want this I've provided a new property to disable it.
=> Auto import gpg keys in zypper_repository

omnibus_overrides.rb
Bumps Bundler version to 1.15.4
https://github.com/bundler/bundler/issues/5781 was included in Bundler 1.15.2 that fixes `no_proxy` environment variable support. Without it, we are unable to contact an internally hosted Artifactory instance proxying RubyGems when utilizing `http_proxy`,  `https_proxy`, and `no_proxy` as `no_proxy` was not being respected and it was attempting to send the traffic through the proxy.
=> Bumps Bundler version to 1.15.4

lib/chef/provider/package/dnf.rb
It is really bad to have Chef all of a sudden start using a different provider
on the same OS because you happen to install DNF to play with it.
For RHEL, we know 8 will default to DNF, and 7 defaults to yum, so we specify
that.
Unexpectedly switching package managers
=> dnf_provider: be more specific when we provide `package`

lib/chef/node/immutable_collections.rb, spec/unit/node/immutable_collections_spec.rb
since we only inject Mash/VividMashes do not convert
=> speed up immutabilization

lib/chef/node/attribute.rb
since immutablize now does dup + freeze of everything this
is definitively unnecessary, and appears to have been
unnecessary even in Chef-12 (at last does not break any
specs there either).
=> node attributes: remove useless dup in merge_all

lib/chef/knife/core/ui.rb
We're already doing this same thing in the other location where we throw the editor error.
=> Link to the knife docs in both places where we error on editor

omnibus_overrides.rb
has security fixes:   http://blog.rubygems.org/2017/08/27/2.6.13-released.html
=> bump rubygems to 2.6.13

Gemfile, Gemfile.lock
Sufficient folk use Chef Vault that I think it's reasonable that we just include it by default. There are zero additional dependencies from this.
=> Ship chef-vault in the omnibus package

lib/chef/provider/apt_repository.rb, lib/chef/resource/apt_repository.rb
Amends `apt_repository` key property to accept an array of keys to install, in the case of authenticating packages from repos signed by multiple keys.
Fix #6369
=> Support an array of keys for apt_repository

lib/chef/mash.rb, lib/chef/node/attribute.rb, lib/chef/node/immutable_collections.rb
removes a lot of excess dup'ing that was going on in deep merge
this forks our deep merge implementation since people were using deep merge as an external API, internally we no longer use the old deep merge class.
the attribute version of deep merging is about to mutate into unrecognizability though, and is no longer an external api.
=> immutablize properly as we deep merge

lib/chef/mash.rb, lib/chef/node/attribute.rb, lib/chef/node/immutable_collections.rb
backport of already merged #6362 
test failures are the familiar ones on the chef-12 branch.
=> backport of 6362

lib/chef/provider/launchd.rb, lib/chef/provider/service/macosx.rb, spec/unit/provider/service/macosx_spec.rb
The Launchd resource will load launchagents as root when the mac is
sitting on the login window. This is never a desired outcome and is hard
to recover from. This change now will now check to see if a user is
logged in before loading launchagents.
Signed-off-by: Mike Dodge <mikedodge04@gmail.com>
=> Launchd should not load launchagents as root.

lib/chef/provider/ifconfig/redhat.rb, spec/unit/provider/ifconfig/redhat_spec.rb
Quote ETHTOOL_OPTS and BONDING_OPTS so ifcfg-if changes from
BONDING_OPTS=mode=active-backup miimon=100 # invalid
to
BONDING_OPTS="mode=active-backup miimon=100" # valid
N/A
=> Ensure we quote ETHTOOL/BONDING_OPTS

lib/chef/provider/route.rb, spec/unit/provider/route_spec.rb
Allow specifying default gateway on RHEL/Centos
https://github.com/chef/chef/issues/2243
=> Allow specifying default gateway on RHEL/Centos

.expeditor/config.yml
=> Provide release_branch as an array instead of a hash

lib/chef/util/dsc/local_configuration_manager.rb, spec/unit/util/dsc/local_configuration_manager_spec.rb
Backport #6383 to Chef 12, which adds support for using `dsc_script` on Powershell 5.
=> backport #6383 to 12

lib/chef/provider/apt_preference.rb, lib/chef/provider/apt_repository.rb, lib/chef/provider/apt_update.rb, lib/chef/resource/apt_package.rb, lib/chef/resource/apt_preference.rb, lib/chef/resource/apt_repository.rb, lib/chef/resource/apt_update.rb, spec/unit/provider/apt_repository_spec.rb, spec/unit/resource/apt_preference_spec.rb, spec/unit/resource/apt_repository_spec.rb, spec/unit/resource/apt_update_spec.rb
apt-get is a link to yast2 in suse so these resources fire there when someone wouldn't expect them to. Looking back we probably should have skipped the whole platform based no-op thing, but that ship sailed. This makes it behave the way a user would expect it to. What happens if you have apt compiled on your gentoo box? Well it's going to break. We'll just have to live with fixing it for 99.99% of users instead of the current 95%. Also: This is faster.
=> Replace which apt-get check with simple debian check in apt resources

lib/chef/provider/zypper_repository.rb
This is probably the sane set of options for an automated refresh approach.
=> Quiet the output of the zypper refresh and add force

lib/chef/provider/yum_repository.rb
We're not using http simple or shellout here.
=> Remove unused requires in yum_repository

lib/chef/resource/apt_preference.rb, lib/chef/resource/apt_repository.rb, lib/chef/resource/apt_update.rb
If we want these to throw a no ops vs. a hard failure we need them to be
wide open. Since a lot of people (including all of chef-cookbooks) have
coded as if these will gracefully skip this would have been a breaking
change.
=> Open apt resources up to prevent breaking change

lib/chef/provider/package/dnf/dnf_helper.py
dnf_helper.py was configured to catch the SIGCHLD signal and quit if it
was received.  In Fedora26 I have found that the fill_sack call in the
dnf python package may shell out causing a SIHCHLD call.  This results
in no information as the helper just exits before finding a package.
This removes the helper restoring the default handling of SIGCHLD which
is to ingore it.
Obvious fix.
Signed-off-by: Brandon Bennett <bbennett@fb.com>
Fixes #6393
- [N/A] New functionality includes tests
- [N/A] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
=> Don't catch SIGCHLD from dnf_helper.py

.expeditor/config.yml
Allows us to ignore all the things for minor updates
=> Wire up the expeditor: skip all label

lib/chef/provider/apt_repository.rb
Signed-off-by: Matt Whiteley <mattwhiteley@gmail.com>
Backport #6094 to Chef 12
This is just a cherry pick of the commit there and then I cleaned up the small conflict
#6094
=> Backport 6094 to Chef 12: apt-key finger no longer matches extract fingerprints regex

lib/chef/provider/support/yum_repo.erb, lib/chef/resource/yum_repository.rb
These two config options were missing. You can pass them via options, but they should be supported out the box just like the other options.
=> Add throttle and metalink options to yum_repository

lib/chef/knife/search.rb
Signed-off-by: Dmitry Shestoperov <dmitry@shestoperov.info>
Prevents knife -i to pull whole object for post-fitering on client-side
#5192
=> Fix Knife search ID only option to actually filter result set

lib/chef/provider/windows_task.rb, spec/functional/resource/windows_task_spec.rb, spec/unit/provider/windows_task_spec.rb
DateTime.parse is not really that well defined. It accepts a lot
of different dates, however not `MM/DD/YYYY`. It does `DD/MM/YYYY`.
We should be very specific in the format we accept, and continue
to support `MM/DD/YYYY` as it was in the cookbook
Fixes https://github.com/chef-cookbooks/chef-client/issues/523
=> Only accept MM/DD/YYYY for windows_task start_day

.expeditor/config.yml
Use new `docker_images` syntax. 
Failing to build Docker Images
=> Use new 'docker_images' Expeditor syntax

lib/chef/cookbook/synchronizer.rb, spec/unit/cookbook/synchronizer_spec.rb
Signed-off-by: Tor Magnus Rakvåg <tm@intility.no>
Does not modify the functionality of CookbookSynchronizer, but moves the warning out of the loop so it only warns once.
https://github.com/chef/chef/issues/6402
=> only warn about skipping sync once

bin/chef-shell
Currently on some distros where the default isn't UTF (SUSE/omnios/probably others) chef-shell fails to launch with a nasty rb-readline error. It's not the best user experience. Lifting this line from Berkshelf fixes it and makes it easier to troubleshoot on those platforms.
Closes #6446 
=> Force encoding to UTF_8 in chef-shell to prevent failures

lib/chef/provider/zypper_repository.rb, lib/chef/resource/zypper_repository.rb, spec/unit/provider/zypper_repository_spec.rb, spec/unit/resource/zypper_repository_spec.rb
This prevents failures when the key is unknown.
This way is *simple*, but I'm not a fan of the way the :before notification results in double template logging. I'm open to a better way that provides some idempotency to the key import.
=> Import the zypper GPG key before templating the repo

lib/chef/provider/package.rb, lib/chef/provider/package/apt.rb, lib/chef/provider/package/chocolatey.rb, lib/chef/provider/package/dnf.rb, lib/chef/provider/package/dnf/dnf_helper.py, lib/chef/provider/package/dnf/python_helper.rb, lib/chef/provider/package/rpm.rb, lib/chef/provider/package/windows.rb, lib/chef/provider/package/yum.rb, spec/unit/provider/package/rubygems_spec.rb
This pull request introduces fixes to the behaviour of the various providers of the "package" resource (and subtypes like dnf_package etc) when a more recent version of the package has been installed than that present in an available repository or file source and "action :upgrade" is called against the package.
Currently, a number of package providers will attempt to *downgrade* a package under this scenario, where the desired action should be to recognise that a more up to date version is already installed and do nothing.
The PR introduces a ```version_compare``` method to the package superclass which by default uses ```Gem::Version``` comparison with spaceship-operator semantics to ensure that an upgrade is attempted only when the candidate version is *not* older than the current …
=> Fixes to package upgrade behaviour

lib/chef/knife/client_delete.rb, lib/chef/knife/node_delete.rb, lib/chef/knife/node_run_list_add.rb, lib/chef/knife/node_run_list_remove.rb, lib/chef/knife/role_env_run_list_add.rb, lib/chef/knife/role_run_list_add.rb
We don't actually use commas in command lines.
Fixes #6465.
=> Tweak the knife banners for multi-arg commands.

lib/chef/resource/dnf_package.rb, spec/unit/provider_resolver_spec.rb
With #6351 and #6377, the DNF package provider was fixed to use yum by
default on RHEL 7, but the resource was still calling the DNF provider
if it happened to be installed.
We want to use the default of yum for RHEL 7, and only use DNF if we
call `set_priority_map` directly.
Signed-off-by: Naomi Reeves <naomi.c.reeves@gmail.com>
Unexpectedly switching package managers
=> dnf_resource: be more specific for rhel packages

lib/chef/resource/dnf_package.rb, spec/unit/provider_resolver_spec.rb
Backport #6435 to Chef 12
Signed-off-by: Naomi Reeves <naomi.c.reeves@gmail.com>
Unexpectedly switching package managers
=> Backport #6435 to Chef-12: dnf_resource

lib/chef/chef_fs/data_handler/data_bag_item_data_handler.rb, lib/chef/data_bag.rb, spec/unit/chef_fs/data_handler/data_bag_item_data_handler.rb, spec/unit/knife/data_bag_create_spec.rb
…ment.
Signed-off-by: Sandra Tiffin <sandi.tiffin@gmail.com>
Prevent creation of data bags named node, role, client or environment, using knife.
https://github.com/chef/chef/issues/3058
=> Prevent creation of data bags named node, role, client or environment

lib/chef/chef_fs/config.rb
Signed-off-by: Josh Hudson <jhudson@chef.io>
Fixes an issue where newer versions of ChefFS cannot be used with Chef 11 servers because policyfiles did not exist then. I believe this was a mistaken addition (it is included in `CHEF_12_OBJECTS` properly) that only affected Chef 11 servers.
=> Remove cookbook_artifacts from CHEF_11_OSS_STATIC_OBJECTS

distro/powershell/chef/chef.psm1, omnibus/.kitchen.yml
Signed-off-by: Kartik Null Cating-Subramanian <ksubramanian@chef.io>
Fixes an issue where on a single CPU machine, the powershell wrapper module using a lots of CPU and spin-waits until the chef process it is waiting on produces the first byte of output on STDOUT/STDERR.
This was a weird edge case issue introduced in https://github.com/chef/chef/pull/5549 that none of us noticed.
I added some improvements to the omnibus kitchen files in order to simplify launching windows 10 builders.
=> [SUSTAIN-731] Don't spin in powershell module that launches chef processes

lib/chef/application/client.rb
Signed-off-by: Giedrius Rekasius <giedrius.rekasius@gmail.com>
This change resolves a bug of chef-client service going into infinite sleep after handling SIGHUP. The logic is to sleep for another interval after handling SIGHUP.
chef-client service going to infinite sleep after handling SIGHUP (Issue: [6411](https://github.com/chef/chef/issues/6411))
=> Sleep for another interval after handling SIGHUP

lib/chef/client.rb, spec/unit/client_spec.rb
We should not stack-trace, we should exit with a clean error
=> Support new CriticalOhaiPlugins (backport #6486 to chef-12)

lib/chef/provider/package/dnf.rb, lib/chef/resource/dnf_package.rb
the shell_out approach to parse the version string from rpm is a bit of
a failed experiment.
the shell_out that gets incurred on every package provider is a bit
terrible for performance.
DNF < 1.00 has also never formally landed in any distribution and its
very difficult at this point to deploy it.
when amazon deploys DNF we should add a version comparison for that.
If this patch causes issues we can go back to adding some form of
`provides :package ... { which("dnf" }`
That will be much faster than having the shell_out().
=> only rhel >= 8 and fedora >= 22 get dnf

lib/chef/provider/windows_task.rb, lib/chef/resource/windows_task.rb, spec/functional/resource/windows_task_spec.rb, spec/unit/provider/windows_task_spec.rb, spec/unit/resource/windows_task_spec.rb
Updated code to add `none` frequency option to windows task resource.
Fixes #6200
=> Windows: Added :none frequency to windows_task resource

lib/chef/util/dsc/lcm_output_parser.rb
This was backported from Chef 13 where we require Ruby 2.3. This won't work in Ruby 2.2.
=> Don't use the safe navigation operator which requires Ruby 2.3

lib/chef/mixin/user_context.rb, spec/unit/mixin/user_context_spec.rb, spec/unit/provider/remote_file/network_file_spec.rb
Our check here to see if we're on Windows uses node data that's not
available in this context. Use the same Chef::Platform.windows? check we
use above. Without this you get the following error:
[2017-10-02T21:40:42+00:00] DEBUG: Re-raising exception: NameError - remote_file[c:/foo/bar] (foo::default line 14) had an error: NameError: undefined local variable or method `node' for #<Chef::Provider::RemoteFile::NetworkFile:0x00000000064c0148>
=> Fix remote_file with UNC paths failing

Gemfile.lock, RELEASE_NOTES.md
Ohai Release Notes 13.6
- Critical Plugins
Users can now specify a list of plugins which are `critical`. Critical plugins will cause Ohai to fail if they do not run successfully (and thus cause a Chef run using Ohai to fail). The syntax for this is:
```
ohai.critical_plugins << :Filesystem
```
- Filesystem now has a `allow_partial_data` configuration option
The Filesystem plugin now has a `allow_partial_data` configuration option. If set, the filesystem will return whatever data it can even if some commands it ran failed.
- Rackspace detection on Windows
Windows nodes running on Rackspace will now properly detect themselves as running on Rackspace without a hint file.
- Package data on Amazon Linux
The Packages plugin now supports gathering packages data on Amazon Linux
=> Include Ohai 13.6

spec/functional/win32/security_spec.rb
Signed-off-by: MSys <harikesh.kolekar@msystechnologies.com>
https://github.com/chef/chef/blob/master/spec/functional/win32/security_spec.rb#L33
I'm fairly certain that the mixlib-shellout user code works now, we were just talking about using it with powershell_out. If so, we create the necessary functional tests here.
=> [MSYS-492]Add missing functional tests for users

lib/chef/provider/package.rb, lib/chef/provider/package/apt.rb, lib/chef/provider/package/dpkg.rb, spec/unit/provider/package/apt_spec.rb
This is builds on the work that @komazarari did in https://github.com/chef/chef/pull/6554 to fix comparison of version strings that Gem can't handle.
If we don't have a version installed yet we shouldn't go do a version
comparison with nil. No matter what that's a waste of time and in
dpkg/apt it's going to require shelling out now. Instead just do the
install.
This also adds the same version comparison method to the dpkg resource.
At the moment it doesn't look like this is going to get called since our
upgrade action there is a bit broken (doesn't actually compare
versions), but that's going to get fixed next.
This also cleans up the version comparison to make sure we're
always dealing with strings
=> Fix the invalid version comparison in apt/dpkg providers

lib/chef/provider/package/apt.rb
The strings of dpkg versions are more complex than the Gem::Version
and not compatible with it.
Using Gem::Version to compare versions of dpkg packages will cause
mistakes or raise the exeption of 'Malformed version number..'.
please see a simple example:
https://gist.github.com/komazarari/c6b33b29a0e31e9c62bbc2f0b2091647
Prefer to use the dpkg cli.
https://debian-handbook.info/browse/en-US/stable/sect.manipulating-packages-with-dpkg.html
none
=> Fix the invalid version comparison of apt packages.

omnibus/Gemfile.lock, omnibus_overrides.rb
openssl:
CVE-2017-3736 (OpenSSL advisory)  [Moderate severity] 2nd November 2017:
There is a carry propagating bug in the x86_64 Montgomery squaring procedure. No EC algorithms are affected. Analysis suggests that attacks against RSA and DSA as a result of this defect would be very difficult to perform and are not believed likely. Attacks against DH are considered just feasible (although very difficult) because most of the work necessary to deduce information about a private key may be performed offline. The amount of resources required for such an attack would be very significant and likely only accessible to a limited number of attackers. An attacker would additionally need online access to an unpatched system using the target private key in a scenario with persistent DH parameters and …
=> Bump openssl and rubygems to latest

lib/chef/client.rb, spec/unit/client_spec.rb
We need ohai_time to get the 'Last Check-In' time on the Chef Server.
There is really no risk to including it.
=> Add ohai_time to minimal_ohai filter

spec/functional/resource/user/useradd_spec.rb
RHEL >= 7.3 ships with a fixed `usermod` command.
Reference: https://access.redhat.com/errata/RHBA-2016:2322
=> Change a useradd_spec test for RHEL >= 6.8 and >= 7.3

spec/functional/resource/user/useradd_spec.rb
This fixes the version constraint check used in one of the useradd_spec tests.
=> Use Chef::VersionConstraint in useradd_spec test

spec/functional/win32/security_spec.rb
testing to see if appveyor goes green or not.
so somewhere between v13.5.28 and v13.6.7 we broke appveyor.
looks like it was fa6e4e89b586bb8eaee767d5602b13cb75f6c073
=> Revert "add missing functional tests for users"

lib/chef/provider/service/solaris.rb
Without setting "maintenance" to false service restart
fails with error "service is not in a maintenance or degraded state"
on solaris nodes
Fix typo 
=> Fix variable name in solaris service provider

.travis.yml
If `sudo` is `false`, then Travis CI will use a container for testing. If
`sudo` is `required, then it will use a GCE VM. We've recently been
seeing permission errors that appeared related to the Travis CI infrastructure.
Switching to the VM resolves those errors. The downside is that it takes 50s
instead of 5s to start up the tester, but given that our tests take 18 minutes
that is okay.
https://docs.travis-ci.com/user/reference/trusty/
=> Switch from the Travis container to the VM

lib/chef/util/selinux.rb, spec/unit/util/selinux_spec.rb
Fixes a bug with interactions with SELinux and filenames with special characters when using `remote_directory`.
(Do the merge commits need to be signed-off?)
Closes #6346.
=> Selinux shellout fix (#6346)

lib/chef/client.rb, lib/chef/event_dispatch/base.rb
Added at the end to comply with our magic compat code rules (i.e. new arguments at the end are allowed because we auto-trip to match the arity of older event sinks).
=> Makes life easier for hook authors switching from the older report handler syntax

lib/chef/node_map.rb, spec/unit/node_map_spec.rb
Chef::Version and VersionConstraint are for x.y/x.y.z cookbook
versions, and are always wrong for anything other than
cookbooks.
=> fix NodeMap to not throw exceptions on platform_versions

lib/chef/provider/windows_path.rb, spec/unit/resource/windows_path_spec.rb
Fixes https://github.com/chef/chef/issues/6526
=> Fix windows_path converging on every run

lib/chef/provider.rb, spec/integration/recipes/resource_converge_if_changed_spec.rb
Hides value of resource properties marked as sensitive in the output of converge_if_changed.
Closes #6571
=> Hide sensitive properties in converge_if_changed.

lib/chef/knife/ssh.rb, spec/functional/knife/ssh_spec.rb, spec/unit/knife/ssh_spec.rb
```sh
$ knife ssh 'name:app-server' 'echo hello' 
ec2-10-0-0-1.compute-1.amazonaws.com hello
$ knife ssh --prefix-attribute name 'name:app-server' 'echo hello'
app-server hello
```
Allows an attribute to be specified which will determine how a node is identified in the output of `knife ssh` commands. It uses the long flag `--prefix-attribute` ~~and the short flag `-b`. The short flag was picked as a placeholder, chosen because `-p` is already in use for `--port`, this can be changed prior to merging to align with any sort of option/flag guidelines that may exist.~~ The config setting `Chef::Config[:knife][:prefix_attribute]` is also supported.
This feature makes use of the session properties assignment functionality documented [here](https://github.com/jamis/net-ssh-multi/blob/c0b0a0b9a84d …
=> Knife SSH prefix option

lib/chef/provider/windows_task.rb
Improve debug logging to improve troubleshooting data. Also use converge_by since why not
=> Improved windows_task logging

lib/chef/node/attribute.rb, lib/chef/node/attribute_collections.rb, lib/chef/node/common_api.rb, lib/chef/node/immutable_collections.rb, lib/chef/node/mixin/state_tracking.rb, spec/unit/mixin/powershell_type_coercions_spec.rb, spec/unit/node/attribute_spec.rb, spec/unit/node/immutable_collections_spec.rb, spec/unit/node/vivid_mash_spec.rb
This is per-container lazy deep-merge-caching.
The @deep_merge_cache ivar hanging off of Node::Attribute is the hash structure of the deep merge cache that uses ImmutableArray/Mash objects.
Those objects are lazy so that they autovivify their contents only when they're hit.
Right now there is no per-key autovivification so any access to the object causes the contents to get completely populated (testing has not shown that we really need per-key autovivification).  That means that when the top level is hit, all the top-level keys are walked through and populated (but they're assigned to lazy/empty ImmutableMash/Array objects).
The cache inside the Mash/Array is just the normal internal state of the Array/Hash and the normal setter functions are used to set the values (there's a lot of …
=> Node attributes per-container lazy deep merge and deep merge performance improvements

spec/integration/recipes/noop_resource_spec.rb, spec/integration/recipes/recipe_dsl_spec.rb, spec/integration/recipes/resource_action_spec.rb, spec/spec_helper.rb, spec/unit/lwrp_spec.rb
reset the global resource and provider handler maps before each and
every test.
note that mutation through the top-level keys will get preserved so
this is not perfect, but deep-duping through every single test we run
becomes expensive.
this is sufficient to flush out the global state of all the test lwrp fixtures
that we setup.
it discovered several usage bugs where we either relied on this feature
or where we were testing different fixtures from the ones we thought we
were.
=> speedup lwrp tests

lib/chef/provider/service/solaris.rb, spec/unit/provider/service/solaris_smf_service_spec.rb
Signed-off-by: Patrick Wright <patrick@chef.io>
=> Solaris: Fix svcadm clear to only run in maintenance state

lib/chef/resource/windows_task.rb, spec/functional/resource/windows_task_spec.rb, spec/unit/resource/windows_task_spec.rb
windows_task is rather particular on the data it takes, especially dates and time values. We need to make sure to properly validate user input so we can fail and warn.
Changes in this PR:
- execution_time_limit now sets the default value in the property definition instead of injecting it via a validation method later on
- random_delay and execution_time_limit now accept Integers in addition to Strings. The value here is an Integer and this is the safest way to pass it
- random_delay and execution_time_limit validation has been improved to make sure the values are in fact numeric
- start_time is now properly validated to make sure it's a time value
- start_date is now properly validated to make sure it's a date value
- Generation of ISO8601 duration can now accept 0 seconds as a valid …
=> windows_task: Add additional input validation to properties

lib/chef/data_bag.rb, spec/unit/knife/data_bag_create_spec.rb
I think there was a bug introduced by #3058 where any data bag *containing* reserved words are seen as invalid
#3058
=> Ensure data bags names can contain reserved words

lib/chef/provider/windows_task.rb, spec/unit/provider/windows_task_spec.rb
`start_time` and `start_day` are set as `N/A` for `frequency :on_logon`, which results into `invalid date` and `invalid time` error.
Fixes https://github.com/chef/chef/issues/6615
=> Invalid date error on windows_task with frequency :on_logon

lib/chef/provider/windows_task.rb, spec/unit/provider/windows_task_spec.rb
While executing following recipe its been observed that the windows_task resource is not idempotent 
```
windows_task 'chef-client' do
command 'chef-client -L C:\\tmp\\'
frequency :on_logon
action :create     
end
```
The command that gets set in the task XML is: chef-client -L C:\\tmp\" /RU SYSTEM. So current_resource.command and new_resource.command don't match.
This fix resolved the above issue.
=> windows_task: Fix resource isn't fully idempotent due to command property

.github/ISSUE_TEMPLATE.md
This way we don't see the end users notes when they submit it. This should make it easier to read the issues.
=> Use comments in the github issue template

lib/chef/resource/windows_task.rb
Added a todo to fix this when Ruby 2.3 support goes away since it's 3x
faster
=> Don't use .match? which is Ruby 2.4+ only in windows_task

kitchen-tests/Berksfile.lock, kitchen-tests/cookbooks/base/attributes/default.rb
fedora-latest just went to Fedora 27 and blowfish / cast have been removed with the inclusion of openSSH 7.6. The cookbook is fine, but we set this here.
=> Remove the ciphers that openSSH 7.6 doesn't support

lib/chef/resource/cab_package.rb, lib/chef/resource/msu_package.rb, spec/unit/resource/cab_package_spec.rb, spec/unit/resource/msu_package_spec.rb
The two issues fixed here:
1) cab_package did not require source, but didn't set it from the resource name so cab_package 'xyz.cab' would just fail since source was nil
2) msu_package would coerce the resource name and not package_name so if you overwrote the package name you would also have to set the source, although you wouldn't realize that until it failed oddly
So the solution here is to set the source value to package_name by default and that gets coerced into a path as was previously done. This adds tests for this behavior and the coerce behavior itself to both resources.
This fixes issue #6674
=> Fix bugs in handling 'source'  in msu_package and cab_package

lib/chef/resource/cookbook_file.rb, spec/unit/resource/cookbook_file_spec.rb
Don't hardcode the provider since the provider already has a provides line
Test the source logic default properly by creating the resource name as a absolute path, which is how the user would use it
=> Modernize cookbook_file resource and expand specs

lib/chef/chef_fs/data_handler/data_bag_item_data_handler.rb, spec/unit/chef_fs/data_handler/data_bag_item_data_handler.rb, spec/unit/knife/data_bag_create_spec.rb
Allow data bag names containing, but not equal to, the search reserved words node, role, environment and client.
(Also fixes a couple of grammatical errors in text for other data bag tests).
[#3058](https://github.com/chef/chef/issues/3058)
=> fix for data bag names partially matching search reserved words

lib/chef/http.rb, lib/chef/provider/remote_file/http.rb, spec/unit/http_spec.rb, spec/unit/provider/remote_file/http_spec.rb
Necessary to fix remote_file not obeying the same options that the rest of the file providers take.
Also necessary for berkshelf to inject a Tempfile and control the binmode.
The default in Chef::HTTP should probably be to set binmode to true, but that seems invasive.
closes #2401
=> Allow injecting tempfiles into Chef::HTTP

lib/chef/knife/core/bootstrap_context.rb, spec/data/client.d_00/02-strings.rb, spec/support/shared/unit/application_dot_d.rb, spec/unit/knife/bootstrap_spec.rb
Fixes #6680
Signed-off-by: Allan Espinosa <aespinosa33@bloomberg.net>
`knife bootstrap` runs eveyrhint in `sh -c ' XXX '`.  As such single quotes gets removed. Details about the issue are in #6680 
#6680
=> Escape single-quoted strings from the context in knife bootstrap

appveyor.yml
Start by shuffling around the config to not do a build. This makes it easier to follow and matches their Ruby guide. Then enable bundler caching per their docs.
=> Speed up Appveyor testing with bundler caching

distro/powershell/chef/chef.psm1
Signed-off-by: John Snow <thelunaticscripter@outlook.com>
Submitted with contributions also from @btm 
When a command, like knife, is run using the chef.psm1 function the output of the command was buffered until the command completed so that an object could be created and passed through a pipe. This prevents UI elements from being visible to the user as well as stdout during the running of the ruby command. By instead passing the output of the ruby command direct instead of storing it in a string buffer this helps with both piping commands and allow for UI elements to be visible.
Note: If a UI element is piped such as `knife client delete fake-node > output.txt` the UI element will be in the text file not in the console.
https://github.com/chef/chef-dk/issues/1236
Sustaining Eng MSYS-692 …
=> [MSYS-692] Fix issue with PowerShell function buffer

lib/chef/resource/zypper_repository.rb
Pretty sure I mistakenly copied this from yum_repository. There's no real point and it's just going to slow things down.
=> Remove a useless regex in zypper_repository resource

lib/chef/provider/apt_preference.rb, lib/chef/provider/apt_repository.rb, lib/chef/provider/apt_update.rb, lib/chef/provider/package/smartos.rb
We're already going specific enough here to identify the platform_family. Debian is always going to be on Linux and SmartOS on Solaris2. Don't both checking both.
=> Don't check both platform_family / os in provides when platform_family will do

lib/chef/provider/windows_path.rb, lib/chef/resource/windows_path.rb, spec/unit/resource/windows_path_spec.rb
=> Modernize windows_path resource

lib/chef/resource/execute.rb, spec/support/shared/unit/execute_resource.rb
Allows forcing sensitive to false on execute and batch resource if password is set.
Resolves #6073 
=> [MSYS-725] [chef#6073] allow forcing sensitive to false on execute and batch resource if password is set.

.travis.yml
We already specify sudo where we need it. Enabling it everywhere just
means we have to run full boxes that take longer to spin up.
=> Don't run sudo on every travis job

lib/chef/provider/user/dscl.rb, spec/unit/provider/user/dscl_spec.rb
Signed-off-by: Sean Karlage <skarlage@fb.com>
This is a re-do of https://github.com/chef/chef/pull/6225. This still currently blocks some user operations on chef > 12.17.44 for macOS.
#5777
=> DSCL: Check for set home property before file existence (fixes #5777)

lib/chef/provider/windows_task.rb, lib/chef/resource/windows_task.rb, spec/unit/provider/windows_task_spec.rb, spec/unit/resource/windows_task_spec.rb
windows_task resource is not idempotent for random_delay and execution_time_limit property
```
windows_task 'chef-client 5' do
command 'chef-client'
run_level :highest
frequency :weekly
frequency_modifier 3
random_delay '60'
day 'Mon'
end
```
```
windows_task 'chef-client 5' do
command 'chef-client'
run_level :highest
frequency :weekly
frequency_modifier 3
execution_time_limit '60'
day 'Mon'
end
```
#6638 partially fixed because if day is not set the resource is still not idempotent for day. We will address this issue in different PR.
=> Fix windows_task resource not being idempotent for random_delay and execution_time_limit

lib/chef/provider/group/dscl.rb, spec/unit/provider/group/dscl_spec.rb
To check whether a requested gid is used by the system already, the macOS dscl group provider lists all gids on the system and parses the output. There's a bug wherein the parsing looks for the number and a newline, but this yields false positives, e.g. if `dscl . list /Groups gid` returns:
```
group1          100
group2          148
```
and the code `gid_used?(48)` is run currently, it will return `true` even though gid 48 isn't present.
None
=> Fix dscl group provider gid_used?

lib/chef/provider.rb, spec/unit/provider_spec.rb
Toss in some yard while I'm in here as well
=> Enable the deprecation for use_inline_resource

acceptance/Gemfile
There's no reason to exclude chef 13 at this point.
=> Update the acceptance chef-config pin for chef 14

lib/chef/knife/core/status_presenter.rb
When a node.save operation is executed and a "knife status" is
immediately executed I get "xx minutes" instead of "xx seconds".
The code behind 'knife status' isn't designed to have the ability to
format the time difference in seconds.
To remediate issue, make sure there is a condition in place to format
the time difference in seconds when appropriate.
Signed-off-by: Chibuikem Amaechi <cramaechi@me.com>
No pre-existing issue(s).
=> Fix knife status to show seconds when needed #5055

ci/verify-chef.sh
This makes sure we don't fail on the very slim chance that an OS generated file (lookin' at you, AIX) ends up in this directory and blocks deletion.
=> Force deletion of tmpdir with sudo

lib/chef/application.rb
We are ignoring this setting in non-daemonized (--no-fork) runs.
=> fix non-daemonized umask

Dockerfile
RHEL5 has been EOL and builds are no longer being produced. Move the
Dockerfile to use RHEL6.
Failing Docker builds
=> Update Dockerfile to use RHEL6 build

lib/chef/resource/windows_task.rb, spec/unit/resource/windows_task_spec.rb
Validate if  `idle_time` is not provided or provided outside range `1-999` for `frequency :on_idle`
=> [MSYS-735]fix validation for idle_time

lib/chef/provider/yum_repository.rb
Without this you cannot install a package that is in that repository. We already did this for the yum cache, but not  for the DNF cache.
=> Fix yum_repository to properly reload chef's package cache post repo setup

lib/chef/knife/user_create.rb, lib/chef/knife/user_delete.rb, lib/chef/knife/user_edit.rb, lib/chef/knife/user_reregister.rb, lib/chef/knife/user_show.rb
We're currently shipping 2 of each of these plugins and rewriting the user input when we think they actually meant to support Chef 11 server. It's code that really needs to go away at this point.
=> Add a warning that Chef 11 server support in knife user is deprecated

lib/chef/application/solo.rb, spec/unit/application/solo_spec.rb
We claimed we were going to remove this in Chef 13. Let's stop rewriting
ARGs now.
=> Remove deprecated -r option for Solo mode

lib/chef/knife/ssh.rb
This was replaced with knife ssh cssh
=> Chef 14: Remove deprecated knife ssh csshx command

lib/chef/knife/ssh.rb
This was replaced with --ssh_identity_file
=> Remove deprecated knife ssh --identity-file option

lib/chef/mixin/openssl_helper.rb, lib/chef/resource/openssl_dhparam.rb, lib/chef/resource/openssl_rsa_private_key.rb, lib/chef/resource/openssl_rsa_public_key.rb, spec/unit/mixin/openssl_helper_spec.rb
This way people don't have to refactor their code from OpenSSL::Whatever to ::OpenSSL::Whatever
=> Rename the OpenSSL mixin to avoid name conflicts

lib/chef/node_map.rb, lib/chef/resource/file.rb, lib/chef/resource/link.rb, spec/integration/recipes/recipe_dsl_spec.rb, spec/unit/data_collector/resource_report_spec.rb, spec/unit/node_map_spec.rb, spec/unit/recipe_spec.rb
We still bind preferentially by specificity, but for ties with
specificity we now prefer last-writer-wins instead of the alphabetic
by class name method we had before (that was never documented and I'm
pretty certain nobody understood).
So now `provides(:whatever) { true }` in a cookbook should always win
over core.
=> Convert node map to last-writer-wins for ties

lib/chef/knife/node_policy_set.rb, spec/unit/knife/node_policy_set_spec.rb
Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>
Added support for setting node policy name and group from knife.
knife node policy set  NODE --policy-name POLICY_NAME --policy-group POLICY_GROUP
=> [MSYS-727] Added support for setting node policy name and group from knife

lib/chef/http.rb, spec/functional/http/simple_spec.rb, spec/functional/resource/remote_file_spec.rb
For the truncated downloads the tiny server needs to hit its
RequestTimeout in order to terminate the truncated request, so that
is set to 1 second.  Then also drop down the retries and the
rest_timeout on the client side (but keep the rest_timeout to 2 to
keep it above the tiny_server timeout)
=> speed up http func tests

lib/chef/resource/log.rb
In chef 13.6 this was the case. In the cleanup this one was missed and
this breaks chefspec behavior
=> Fix regression where message isn't an identity property in log resource

lib/chef/mixin/user_context.rb, lib/chef/provider/remote_file/network_file.rb, lib/chef/resource/remote_file.rb, lib/chef/util/windows/logon_session.rb, lib/chef/win32/api/security.rb, lib/chef/win32/security.rb, spec/functional/win32/security_spec.rb, spec/unit/util/windows/logon_session_spec.rb, spec/unit/win32/security_spec.rb
While finishing https://github.com/chef/chef/pull/5832,  we changed the logon type in `Chef::Util::Windows::LogonSession` from `LOGON32_LOGON_NETWORK` to `LOGON32_LOGON_NEW_CREDENTIALS` to facilitate passing credentials to a remote system without logging in locally using those credentials, to handle a use case where those credentials were valid on the remote system but not on the local system.
However, this means that `Chef::Mixin::UserContext.with_user_context` might log on to the local system as a new user but continue using the old users token and thus the old/original users privileges.
`Chef::ReservedNames::Win32::Security.has_admin_privileges?` is really looking to see if we're elevated, not 'admin' per se. We should print some debug information about the token like if it is …
=> [MSYS-724] Chef::Util::Windows::LogonSession should allow having only the prescribed users permissions

.travis.yml
same thing we did to ohai https://github.com/chef/ohai/pull/1086/files but for some reason never appear to have done to this repo.
=> allow uninstall of bundler to fail

lib/chef/node/attribute_collections.rb, lib/chef/node/mixin/state_tracking.rb, spec/unit/node/attribute_spec.rb
node.default['foo'] = node['bar'] need to have node['bar'] have its
cache vivified otherwise we potentially get an empty hash or array.
in the case of hashes, the assignment must have been walking though
the values with #each or something which poked the cache on the target
hash which caused it to vivify, so this bug only affected Arrays
where the AttrArray initializer likely did a quick-n-dirty copy of
the internal structure of the ImmutableArray which was empty.
close #6784
=> fix node assignment of ImmutableArrays to VividMashes/AttrArrays

lib/chef/node/attribute_collections.rb, lib/chef/node/mixin/state_tracking.rb, spec/unit/node/attribute_spec.rb
node.default['foo'] = node['bar'] need to have node['bar'] have its
cache vivified otherwise we potentially get an empty hash or array.
in the case of hashes, the assignment must have been walking though
the values with #each or something which poked the cache on the target
hash which caused it to vivify, so this bug only affected Arrays
where the AttrArray initializer likely did a quick-n-dirty copy of
the internal structure of the ImmutableArray which was empty.
=> fix node assignment of ImmutableArrays to VividMashes/AttrArrays (Chef-13 backport)

omnibus/Gemfile.lock
(let's hold off on merging this until the master build is verified)
=> Ensure that we create a docker compatible ca-certs symlink

lib/chef/resource.rb
We deprecated this in 13.7 and we have a Foodcritic rule to identify it.
There's only 1 person using it on the entire Supermarket since we
haven't documented it since Chef docs were on the wiki.
=> Remove epic_fail alias to ignore_failure

omnibus/Gemfile.lock, omnibus/resources/chef/msi/source.wxs.erb
This change adds an MSIFASTINSTALL property to the Windows Installer set with a value that skips most of the costings, when used on a system that supports Windows Installer 5.0 (i.e. Windows 2008 R2 upwards) [ref](https://msdn.microsoft.com/en-us/library/windows/desktop/aa372856(v=vs.85).aspx).  It should result in a slight speed improvement on install/upgrade.
=> Add MSIFASTINSTALL property, supported by Windows Installer 5.0

lib/chef/knife/core/status_presenter.rb
If a node object's ohai_time value is "nil" then the calculated
time-since-last-run value is incorrect because the "nil" gets converted
to integer "0".
"knife status" should signal an error when a node's ohai_time value
is nil.
Signed-off-by: Chibuikem Amaechi <cramaechi@me.com>
No preexisting issue(s)
=> Update error handling for "knife status" #3287

lib/chef/knife/bootstrap.rb, lib/chef/knife/ssh.rb
This is required due to config[:on_error] being set here: https://github.com/chef/chef/blob/93fe1aca2beff64b30910daa2aac615bc623d259/lib/chef/knife/ssh.rb#L134. This conditional will allow ssh_commands that return non-zero status to be executed on entire pool of servers returned by the knife query when --exit-on-error is NOT specified. 
https://github.com/chef/chef/issues/6581
=> use a stricter comparison so knife ssh only fails if --exit-on-error

lib/chef/provider/package.rb, lib/chef/provider/package/apt.rb, lib/chef/provider/package/yum.rb, lib/chef/provider/package/zypper.rb, spec/unit/provider/package/apt_spec.rb, spec/unit/provider/package_spec.rb
Due to the nature of the comparison done, the `package_locked` methods
will always return false as they presume the package name is a string,
when it is in fact always coerced into an array.
Additionally in situations where the package_name is set rather than
being inherited from the package resource's name, it will always return
false.
Resolves #6361
Resolves #6493
=> Ensure package (un)locking is idempotent

spec/functional/mixin/powershell_out_spec.rb
we don't need to test the exact output of this powershell command, just
get literally anything that looks like it ran successfully.
=> Fix Appveyor testing:  the format of this flametest doesn't matter

lib/chef/provider/mount/mount.rb, spec/unit/provider/mount/mount_spec.rb
/etc/fstab contains: /source /destination nullfs defaults 0 0
This does not mount after reboot. It should be:
/source /destination nullfs rw 0 0
So "defaults" does not work on FreeBSD and must be replaced.
Signed-off-by: Chibuikem Amaechi <cramaechi@me.com>
No preexisting issue(s).
=> Update /etc/fstab on FreeBSD #4959

.travis.yml, Dockerfile, spec/functional/mixin/powershell_out_spec.rb
The Dockerfile was causing failures in Jenkins. EL5 is EOL and we're not publishing these anymore so we'd get a 404 trying to pull the EL5 artifact. I also updated the default stable release to a current release. Not sure why that wasn't getting done. I doubt anyone uses this like this, but why not.
This also pulls in the same Fixes we made on the Chef 14 branch for Powershell on Appveyor and it splits out testing on Travis so we can hit reload over and over again until we don't land on the 1 & 2 builders (the broken ones).
=> Fix Dockerfile & Travis/Appveyor failures

spec/functional/mixin/powershell_out_spec.rb
we don't need to test the exact output of this powershell command, just
get literally anything that looks like it ran successfully.
=> Backport the powershell spec fix to get Appveyor green again

lib/chef/provider/package/apt.rb, lib/chef/resource/apt_package.rb, spec/unit/provider/package/apt_spec.rb, spec/unit/resource/apt_package_spec.rb
This is finishing the great work of @ccope in #5698 which we've rather let languish.
Fixes: #6245, Fixes: #5698
=> Avoid dpkg prompts for modified config files

.travis.yml, acceptance/.shared/kitchen_acceptance/.kitchen.ec2.yml, acceptance/.shared/kitchen_acceptance/.kitchen.vagrant.yml, kitchen-tests/.kitchen.travis.yml, kitchen-tests/.kitchen.yml, kitchen-tests/cookbooks/base/recipes/default.rb, omnibus/.kitchen.yml
Debian 7 goes EOL 31st May 2018. We should merge this around that time.
=> Remove testing of Debian 7 as it's going EOL

lib/chef/resource/windows_task.rb, spec/unit/resource/windows_task_spec.rb
Two improvements on the idle_time validation function for the windows_task resource:
- Compare frequency to :idle_time instead of comparing to an incomplete list of other frequencies.
- Keep all the validation logic in the function instead of splitting it between the function and where the function is called.
I din't create an issue since it seemed like an easy fix, but the previous PR [#6714](https://github.com/chef/chef/pull/6714) on the matter had some of my windows_task resources fail when using the :onstart frequency.
=> Fix windows_task idle_time validation

lib/chef/provider/windows_task.rb
Signed-off-by: Tor Magnus Rakvåg <tm@intility.no>
Fixes some minor grammar nits in windows_task
=> Grammar fixes in windows_task

appveyor.yml
This PR removes 32-bit testing on Windows, now that we no longer support any 32-bit operating systems on Windows.
=> No longer test against 32-bit Ruby on Appveyor

chef-config/lib/chef-config/config.rb, lib/chef/knife.rb, spec/integration/knife/deps_spec.rb
This is a pretty common first error message to experience with Chef. Let's point the users to a helpful location so they can quickly get up and running.
=> Link to the knife docs when the knife config file is missing

omnibus/Gemfile, omnibus/Gemfile.lock
LicenseScout is being refactored. We have released a 1.x version that is pinned within the Omnibus gem.
=> Use the version of LicenseScout that comes with the Omnibus gem.

omnibus/Gemfile, omnibus/Gemfile.lock
LicenseScout is being refactored. We have released a 1.x version that is pinned within the Omnibus gem.
=> Use the license_scout that comes with Omnibus gem

lib/chef/provider/systemd_unit.rb, lib/chef/resource/systemd_unit.rb, spec/unit/provider/systemd_unit_spec.rb, spec/unit/resource/systemd_unit_spec.rb
MOAR ACTIONS FOR THE ACTION GOD
adds support for additional systemd_unit actions supported by systemctl:
- [preset](https://www.freedesktop.org/software/systemd/man/systemctl.html#preset%20NAME…): restore enable/disable status based on preset files
- [revert](https://www.freedesktop.org/software/systemd/man/systemctl.html#revert%20NAME…): remove any non-vendor overrides (drop-ins, same-name user-provided units, etc)
- [reenable](https://www.freedesktop.org/software/systemd/man/systemctl.html#reenable%20NAME…): disable then enable (alias regenerator)
https://github.com/chef/chef/issues/6823
=> add additional systemd_unit actions

lib/chef/chef_fs/data_handler/organization_invites_data_handler.rb
Sort threw an error trying to compare nil with a string while running
knife ec backup.  This change deletes the nil entries before sorting.
knife ec backup failed trying to compare nil with a string while running a backup.
New issue
- [x ] New functionality includes tests
- [ x] RELEASE\_NOTES.md, has been updated if required (not required for bugfixes, required for API changes)
- [ x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
=> invites_sort_fail: Clean the invites array before sorting it

lib/chef/provider/remote_file/http.rb, spec/unit/provider/remote_file/http_spec.rb
We can get back a nil tempfile from the streaming downloader which means
that we need to clean up our own tempfile since the base file provider
will not do it for us.
closes #6821
=> RemoteFile: unlink tempfile when using cache control shows unchanged

lib/chef/provider/remote_file/http.rb, spec/unit/provider/remote_file/http_spec.rb
=> RemoteFile: unlink tempfile when using cache control shows unchanged (Chef-13 backport)

CHEF_MVPS.md
Updating the Awesome Community Chefs list to include 2016 and 2017 awardees.  This should probably be moved out of the repo but at least now it's up to date.
=> Adding Awesome Community Chefs from 2016 and 2017

lib/chef/knife/ssh.rb
Affects at least knife 12.5.1
When a user uses knife ssh in "password, not key" mode, it fails.
Signed-off-by: Chibuikem Amaechi <cramaechi@me.com>
closes #4342
=> Fix "knife ssh" authentication scheme #4342

lib/chef/node_map.rb, spec/unit/node_map_spec.rb
halite needs this public API in order to not be so brittle.
also eventually we likely need halite's helper that uses this, or something similarish to it in core because its addressing this issue:
https://github.com/chef/chef/blob/master/spec/spec_helper.rb#L242-L254
this does not make poise/halite go green on its own, but will prevent this problem in the future.
https://github.com/poise/halite/pull/14
will fix the poise/halite redness.
=> add Chef::NodeMap#delete_class API

lib/chef/node_map.rb, spec/unit/node_map_spec.rb
Backport of #6846 will be useful to retire the somewhat janky code in halite sooner rather than later.
=> add Chef::NodeMap#delete_class API (Chef 13 backport)

lib/chef/provider/registry_key.rb
This PR adds the `sensitive` property to `registry_key` but needs some help before it's ready to be merged.
I'm not sure if the `sensitive: true` sets the `values` property to default to sensitive or if when `sensitive` is true on the resource, `values` will be masked.
Re tests, looking at the `execute` resource it looks like I should be copying across something like below, but not sure where it should sit.
```
context "when sensitive is set true" do
it "should honor sensitive attribute" do
new_resource.sensitive true
opts.delete(:live_stream)
expect(provider).to receive(:shell_out_with_systems_locale!).with(new_resource.name, opts)
expect(provider).to receive(:converge_by).with("registry_key sensitive resource").and_call_original
expect(Chef::Log).not_to receive(:warn) …
```
=> registry_key: Add sensitive property support for suppressing output (fixes #5695)

lib/chef/chef_fs/chef_fs_data_store.rb
#6471 includes regression. We will not be able to find a cookbook based on identifier saved by chef export.
Not in this repository. External thing, integration test of my plugin now fails.
- https://github.com/higanworks/knife-zero/issues/118
Signed-off-by: SAWANOBORI Yukihiko <sawanoboriyu@higanworks.com>
=> check identifier to resolve exported cookbooks by chef export

chef-config/spec/unit/config_spec.rb
This came up in circle - they have capitalized environment
variables which our tests were choking on.
=> make sure all proxy settings are dealt with

.travis.yml
Seems to be somewhat more stable in travis, and we do have coverage in jenkins (and the func and integ tests still run with sudo)
=> Disable sudo on unit tests

lib/chef/provider/ifconfig/debian.rb, lib/chef/resource/ifconfig.rb
This PR allows customization of the network family option in Debian/Ubuntu platforms, defaulting to the currently used 'inet' family. It will open the door to IPv6 networking eventually, but I didn't want to overload the scope of this change with adding IPv6 support.
None
=> Add support for network family in ifconfig for Debian platforms

.gitignore
During development, users `bundle exec chef-client` (amongst other commands) in order to test their changes.  On a system without any overridden configuration specified in client.rb or at the command line this leads to the creation of a `nodes/` folder containing data relating to the development node.  This PR simply excludes this folder from accidentally being committed.
=> Git ignore any node json generated during development

lib/chef/application/client.rb
If we find a config file in the exported tarball, load it up. This way
we can use --recipe-url with the direct results of `chef export -a`
=> Allow tarballs generated by chef export to be used

.travis.yml, spec/spec_helper.rb, spec/unit/daemon_spec.rb
The only line here which is actually a bugfix is this one:
https://github.com/chef/chef/pull/6888/files#diff-1c826d5d40b34ba0095996a6453ca135R76
Which stubs and no-ops `:_change_privilege`.  Most of the rest of the specs in this describe block setup expectations on that method, but the first test does not, which means that it really calls that function and really changes privs.
Also added some defensive checking which will blow up if this ever happens again (and has an edge case where it throws out a false positive which is responsible for the other couple lines of spec fixes).
=> The end of our long travis unit testing nightmare

lib/chef/knife/search.rb
This fixes the formatting of knife search --id-only output to restore the behavior prior to chef v13.4.32.
#6438 caused the output of this command to change from displaying each id on its own line to displaying each id followed by a colon and an empty line.
See the related issue and comments for more details.
https://github.com/chef/chef-dk/issues/1475
=>  Prevent knife search --id-only from outputting IDs in the same format as an empty hash

lib/chef/node/attribute.rb, lib/chef/node/attribute_collections.rb, lib/chef/node/common_api.rb, lib/chef/node/immutable_collections.rb, lib/chef/node/mixin/state_tracking.rb, spec/unit/mixin/powershell_type_coercions_spec.rb, spec/unit/node/attribute_spec.rb, spec/unit/node/immutable_collections_spec.rb, spec/unit/node/vivid_mash_spec.rb
Reverts #6424 and #6790 
That experiment failed badly.  The problem is that the actual Hash and Array classes poke directly into anything that inherits directly from Hash or Array.  With lazy per-container caches `Hash#merge(ImmutableMash)` just directly grabs the empty Hash from the ImmutableMash and never pokes a method on the ImmutableMash which could be hooked in order to create the cache first.  This could be solved by going with a pure decorator approach which broke the inheritance from Hash/Array (in which case `Hash#merge` would call `#to_h` on the decorated object which could then be hooked to populate the cache.  That ran into difficulties with other operators when I tried going down that road and I abandoned it though. 
Going down the road of trying to have per-container caches …
=> Chef-13 revert lazy attributes

lib/chef/resource/macosx_service.rb
Use properties throughout instead of set_or_return
=> Modernize macosx_service

lib/chef/node/attribute.rb, lib/chef/node/attribute_collections.rb, lib/chef/node/common_api.rb, lib/chef/node/immutable_collections.rb, lib/chef/node/mixin/state_tracking.rb, spec/unit/node/attribute_spec.rb, spec/unit/node/immutable_collections_spec.rb, spec/unit/node/vivid_mash_spec.rb
Reverts #6424 and #6790
That experiment failed badly. The problem is that the actual Hash and Array classes poke directly into anything that inherits directly from Hash or Array. With lazy per-container caches Hash#merge(ImmutableMash) just directly grabs the empty Hash from the ImmutableMash and never pokes a method on the ImmutableMash which could be hooked in order to create the cache first. This could be solved by going with a pure decorator approach which broke the inheritance from Hash/Array (in which case Hash#merge would call #to_h on the decorated object which could then be hooked to populate the cache. That ran into difficulties with other operators when I tried going down that road and I abandoned it though.
Going down the road of trying to have per-container caches which were …
=> revert lazy attributes

chef-config/lib/chef-config/config.rb, lib/chef/knife.rb, spec/integration/knife/deps_spec.rb
This is a pretty common first error message to experience with Chef. Let's point the users to a helpful location so they can quickly get up and running. Add some YARD comments while I was in the config class
=> Link to the knife.rb docs when the knife.rb file is missing

lib/chef/resource/mount.rb, lib/chef/resource/msu_package.rb, lib/chef/resource/openbsd_package.rb, lib/chef/resource/osx_profile.rb, lib/chef/resource/pacman_package.rb, lib/chef/resource/paludis_package.rb, lib/chef/resource/portage_package.rb, lib/chef/resource/powershell_package.rb, lib/chef/resource/reboot.rb, lib/chef/resource/route.rb, lib/chef/resource/rpm_package.rb, lib/chef/resource/service.rb, lib/chef/resource/smartos_package.rb, lib/chef/resource/solaris_package.rb, lib/chef/resource/subversion.rb, lib/chef/resource/systemd_unit.rb, lib/chef/resource/windows_env.rb, lib/chef/resource/windows_package.rb, lib/chef/resource/windows_path.rb, lib/chef/resource/windows_service.rb, lib/chef/resource/windows_task.rb, lib/chef/resource/yum_repository.rb, lib/chef/resource/zypper_package.rb, lib/chef/resource/zypper_repository.rb
There's still more, but this adds the fields to a good chunk of additional resources
=> Add more introduced and description fields to resources

lib/chef/guard_interpreter/default_guard_interpreter.rb
surface command stderr when guard interpreter command is unsuccessful. helps with showing why file/systemd_unit verify commands may fail.
surfacing the error in the converge output is important for debugging since the temporary files used during verification are not available for inspection after the verification command is run.
aids in debugging when guard interpreter fails
#5931
=> surface default guard interpreter errors

lib/chef/resource/openssl_dhparam.rb, lib/chef/resource/openssl_rsa_private_key.rb, lib/chef/resource/openssl_rsa_public_key.rb
Get these updated for the latest and greatest before we ship Chef 14
=> Add description, validation_message, and introduced fields into openssl resources

lib/chef/knife/ssh.rb
Signed-off-by: Erik <Erik.Parra4@gmail.com>
When using option --ssh-gateway-identity and -ssh-identity, both with be utilized by the session_options definition.
[Issue #6210 ](https://github.com/chef/chef/issues/6210) Resolves the issue of --ssh-gateway-identity being used for both gateway and target node.
=> Added Flag to distinguish between gateway and host key to fix issue #6210

lib/chef/provider/mount/aix.rb
eql? doesn't make sense for string comparison and it's just 20% slower
than ==
=> Don't use .eql? in the aix mount provider

lib/chef/knife/cookbook_site_download.rb
When installing the postgres cookbook, the following error was reported "TypeError: no implicit conversion of nil into String". Debugging the code, I found that the issue was caused by a missing "replacement" attribute on the cookbook while "deprecated"=>true. This commit is my proposed change to fix this issue. The updated code produces the following warning as opposed to an error: WARNING: DEPRECATION: This cookbook has been deprecated. No replacement has been defined.
Below is the error that I came across as I was trying to install the postgresql cookbook.
```
$ knife cookbook site install postgresql
Installing postgresql to /home/rlyders/chef-repo/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-postgresql) exists, switching to it.
Downloading postgresql …
```
=> [knife] Don't crash when a deprecated cookbook has no replacement

distro/common/html/knife_bootstrap.html, lib/chef/knife/bootstrap.rb, lib/chef/knife/bootstrap/templates/chef-full.erb, spec/unit/knife/bootstrap_spec.rb
Signed-off-by: S. Cavallo <smcavallo@hotmail.com>
Add support for knife bootstrap-preinstall-command
Allows custom pre-install commands to be inserted into the bootstrap template.
A common use case is waiting for cloud-init to complete or any existing package manager locks to be released.  It is possible to do this by customizing the install command or using custom bootstrap templates.  Maintaining custom bootstrap templates can be difficult to keep up to date.
Allowing a custom pre-install bootstrap command would allow us to use the built-in templates without having to fork or customize the templates.
=> Add support for knife bootstrap-preinstall-command

lib/chef/knife/ssh.rb, spec/unit/knife/ssh_spec.rb
If fqdn is duplicated, it raises fatal error. Because it sometimes does not notice that it is duplicated.
=> Raise fatal error If FQDN duplicated

lib/chef/application.rb, lib/chef/knife.rb, spec/unit/application/client_spec.rb, spec/unit/application_spec.rb
The pre-14 precedence level is:
1. mixlib-cli setting
2. mixlib-cli default
3. mixlib-config setting
4. mixlib-config default
This means that if an option has a mixlib-cli default that it cannot ever be set in the config file.
This PR swaps 2+3 around:
1. mixlib-cli setting
2. mixlib-config setting
3. mixlib-cli default
4. mixlib-config default
Now the mixlib-cli defaults still take precedence over mixlib-config
defaults, but it is possible to set a value in config.rb if there's
a mixlib-cli default setting (which creeps into the settings in hidden
ways if you just use `boolean: true` in mixlib-cli).
=> Stop mixlib-cli default clobbering mixlib-config settings

Gemfile, Gemfile.lock
Seems pointless when we pin the version in Gemfile.lock and
I'm not even sure we need this now with GH's alerts.
=> Remove git ref on bundler-audit

lib/chef/provider/package/chocolatey.rb, lib/chef/resource/chocolatey_package.rb, spec/unit/provider/package/chocolatey_spec.rb
Remove the previously deprecated :uninstall action for
chocolatey_package. This is noted in CHEF-21 (https://docs.chef.io/deprecations_chocolatey_uninstall.html)
=> Remove the :uninstall action from chocolatey_package - CHEF-21

Gemfile, Gemfile.lock, kitchen-tests/Gemfile, omnibus/Gemfile.lock
This new Ohai fixes fetching Softlayer Metadata
=> Bump depenencies to pull in Ohai 13.8 / InSpec 1.51.21

kitchen-tests/cookbooks/base/metadata.rb, kitchen-tests/cookbooks/base/recipes/default.rb
apt cookbook wasn't being used anywhere and build_essential resource is
built in now
=> Update our tests based on new resources we ship

.travis.yml, kitchen-tests/.kitchen.travis.yml
We have a dokken image for 18.04 based off the beta and rebuilding on a schedule in Docker Cloud.
=> Add Ubuntu 18.04 Testing in Travis

lib/chef/provider/apt_repository.rb, spec/unit/provider/apt_repository_spec.rb
So this all started when @coderanger pointed out that we didn't need to use the run_command on the shell_out helper method since it does that internally already. I fixed that here and realized the logic could be broken out to ease readability and expand testing. I added yard comments, broke out some logic into smaller methods, added more unit tests, and added a bit more debug logging.
=> Apt repo cleanup and testing expansion

lib/chef/knife/cookbook_site_download.rb
When installing the postgres cookbook, the following error was reported "TypeError: no implicit conversion of nil into String". Debugging the code, I found that the issue was caused by a missing "replacement" attribute on the cookbook while "deprecated"=>true. This commit is my proposed change to fix this issue. The updated code produces the following warning as opposed to an error: WARNING: DEPRECATION: This cookbook has been deprecated. No replacement has been defined.
Below is the error that I came across as I was trying to install the postgresql cookbook.
```
$ knife cookbook site install postgresql
Installing postgresql to /home/rlyders/chef-repo/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-postgresql) exists, switching to it.
Downloading postgresql …
```
=> [knife] Don't crash when a deprecated cookbook has no replacement (#6853)

lib/chef/resource/apt_package.rb
No reason for OS and platform_family.
=> Check the platform family only in the apt_package provides

lib/chef/provider/package.rb
The helper method is further down in the class, just checks `respond_to?`. Related: we should probably add this to `Chef::Resource::Package` so its supported by all the systems unless there is some reason not to.
=> Use the existing helper method for package resource classes that don't support allow_downgrade

lib/chef/provider/package/macports.rb
Fixed minor typo in macports.rb: status.insect -> status.inspect
=> fix typo in macports error handling

lib/chef/resource/registry_key.rb, spec/unit/resource/registry_key_spec.rb
Partially modernize registry_key resource. The main fix here is that we limit what symbols can be passed to the architecture property now where as before it was wide open. This will probably help a bit since the docs are a bit confusing and also enormous.
=> registry_key: Properly limit allowed values for architecture

lib/chef/resource/osx_profile.rb
Use the modern method not identity_attr
=> osx_profile: set identity on the property not using identity_attr

chef-config/lib/chef-config/config.rb, lib/chef/application/client.rb, lib/chef/application/solo.rb, spec/integration/client/client_spec.rb, spec/unit/application/client_spec.rb
without --interval we default to --no-fork, with --interval we default
to running --fork.  --once and --daemonize are handled before this code
so they will also DTRT.
closes #6712
=>  Don't use supervisor process for one-shot / command-line runs

lib/chef/config.rb, lib/chef/dsl/reboot_pending.rb, lib/chef/platform/query_helpers.rb, lib/chef/win32/eventlog.rb, lib/chef/win32/security.rb, lib/chef/win32/security/sid.rb, lib/chef/win32/version.rb, spec/functional/event_loggers/windows_eventlog_spec.rb, spec/functional/resource/link_spec.rb, spec/functional/resource/powershell_script_spec.rb, spec/functional/win32/security_spec.rb, spec/functional/win32/versions_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb, spec/support/shared/functional/file_resource.rb, spec/unit/dsl/reboot_pending_spec.rb, spec/unit/platform/query_helpers_spec.rb, spec/unit/provider/link_spec.rb, spec/unit/provider/remote_directory_spec.rb, spec/unit/win32/security_spec.rb
Windows 2003 is fully end of life at this point and hasn't been supported by Chef for quite a while. EXTENDED support for Windows 2003 ended July 14, 2015. We avoid a good number of WMI queries by removing this support entirely.
=> Remove support for Windows 2003

lib/chef/provider/apt_repository.rb, spec/unit/provider/apt_repository_spec.rb
My previous PR to apt_repository introduced a bug where gpg keys couldn't validate. This converts a raise to an execute so it all happens during converge.
=> Avoid compile time error in apt_repository

lib/chef/mixin/from_file.rb, spec/data/mixin/invalid_data.rb, spec/data/mixin/real_data.rb, spec/functional/mixin/from_file_spec.rb
This adds a new field `source_file` to the `FromFile` mixin that contains the source file used to load the object.
This is useful if you want to trace back a Role/Cookbook::Metadata to the file it was generated from.
We have some scripts that do some custom validation on Role/Cookbook::Metadata objects and currently monkeypatch the FromFile class to contain this attribute, but it'd be nice to have upstream and get rid of the monkeypatch. They mostly use this information to provide meaningful error messages to users in the event that this custom validation fails.
I double-checked that none of the classes using FromFile were already using the name `source_file` for something else, so this won't conflict with any of the code in the chef repo. Happy to rename if desired.
I didn't update …
=> Added source_file to FromFile

lib/chef/resource/remote_file.rb, spec/unit/resource/remote_file_spec.rb
Remove `remote_file` explicit setting of `@provider` in favor of `Chef::ProviderResolver` way of being.
N/A
=> Remove explicit setting of @provider and depend on ProviderResolver

lib/chef/resource/cron.rb, lib/chef/resource/dsc_resource.rb, lib/chef/resource/dsc_script.rb, lib/chef/resource/execute.rb, lib/chef/resource/group.rb, lib/chef/resource/http_request.rb, lib/chef/resource/link.rb, lib/chef/resource/ruby_block.rb, lib/chef/resource/scm.rb, spec/unit/resource_reporter_spec.rb
Just modernizing our resources so we can start to add descriptions to them for the documentation
=> Convert more set_or_returns to proper properties

kitchen-tests/cookbooks/base/recipes/packages.rb
aws-sdk is 132 gems now. It takes *forever* to install on some platforms
like CentOS 6. Use a simple gem.
=> Switch to a smaller gem to install in kitchen runs

.gitignore, acceptance/.gitignore, chef-config/.gitignore, chef-config/README.md, chef-config/chef-config.gemspec
Squash down to a single gitignore file and remove the readme from chef-config that dates back to when it was its own repo
=> Remove duplicate files from acceptance / chef-config

lib/chef/node.rb, lib/chef/policy_builder/policyfile.rb, spec/unit/knife/core/node_editor_spec.rb, spec/unit/knife/node_edit_spec.rb, spec/unit/node_spec.rb, spec/unit/policy_builder/policyfile_spec.rb
We also now set chef_environment the same as policy group when that's
appropriate
=> RFC 106: expose name and chef_environment as attrs

lib/chef/resource/windows_feature_dism.rb
This fix was released in the windows 4.0.1 cookbook
=> Use node.override not node.normal in the windows_feature_dism resource

lib/chef/provider/package/rubygems.rb, spec/unit/provider/package/rubygems_spec.rb
Fixes #6954, #3363. Not sure how best to test this other than the poise-ruby test suite. I put in a monkeypatch version of this and it seems to fix my suite.
=> Rework installed_versions for newer Rubygems

lib/chef/resource/dsc_resource.rb
Check the passed value to see if it's one of the values we support instead of failing hard later when the user passes the wrong thing.
=> Properly validate reboot_action in dsc_resource

lib/chef/provider/cron.rb
This is another Rubocop performance cop. Here's their description:
```
In Ruby 2.3 or later, use unary plus operator to unfreeze a string literal instead of String#dup and String.new. Unary plus operator is faster than String#dup.
Note: String.new (without operator) is not exactly the same as +''. These differ in encoding. String.new.encoding is always ASCII-8BIT. However, (+'').encoding is the same as script encoding(e.g. UTF-8). So, if you expect ASCII-8BIT encoding, disable this cop.
```
=> Don't use String.new in the cron provider

README.md, chef.gemspec
We're removed testing on 2.3 so at this point we wouldn't know if we
introduced some Ruby 2.4+ code.
=> Require Ruby 2.4+

lib/chef/win32/security.rb
LsaFreeMemory takes a pointer to the struct in memory created by LsaEnumerateAccountRights.
We have to pass it the actual pointer, not the FFI::MemoryPointer object.
This fixes masked access violations which occasionally lead to a heap corruption which
presents itself as silent termination of chef-client/ruby with a return code of -1073740940
or STATUS_HEAP_CORRUPTION / 0xc0000374.
Fixes #6589
=> Pass pointer to LsaFreeMemory, not FFI::MemoryPointer

lib/chef/http.rb
In http, strips `Authorization` header on 302 redirects, just like curl does it.
- https://github.com/chef/chef/issues/6984
=> Stripping out Authorization header on redirect to a different host

lib/chef/http.rb
This introduced a failure when using the http_request resource that we experienced internally using Chef 14 builds. 
```
Error executing action `delete` on resource 'http_request[delete-indicies]'
FrozenError
-----------
can't modify frozen Hash
Resource Declaration:
---------------------
313:   http_request 'delete-indicies' do
314:     url 'http://localhost:9200/_all'
315:     action :delete
316:   end
317:
```
=> Revert "Stripping out Authorization header on redirect to a different host

lib/chef/resource/apt_repository.rb, lib/chef/resource/chef_handler.rb, lib/chef/resource/cron.rb, lib/chef/resource/git.rb, lib/chef/resource/http_request.rb, lib/chef/resource/mdadm.rb, lib/chef/resource/sudo.rb
Lamont pointed out that without a lazy eval we're freezing these and then if we try to append them later chef fails.
=> Lazy eval empty Hash/Array resource properties.

lib/chef/resource/scm.rb, lib/chef/resource/subversion.rb, spec/unit/resource/scm_spec.rb, spec/unit/resource/subversion_spec.rb
We actually set the defaults for these in the subversion property, but the actual properties are in scm. Move them to subversion since they are subversion specific.
=> Move subversion specific properties from scm to subversion

lib/chef/win32/security.rb, spec/functional/win32/security_spec.rb
The logging refactor in #6980 should have been a class variable. This fixes that.
Also adds functional tests that would catch that and the original #6980 bug.
=> Fix regression in #6980, add functional tests

lib/chef/provider/package/zypper.rb, spec/unit/provider/package/zypper_spec.rb
This resolves issue #6836 which explains the issue in great detail.
TLDR: Packages that are installed as deps on another package have a
different string when you get info on them now. This updates the regex
to detect both. Based on the zypper changelog I believe this was
introduced in 1.13.17.
=> Detect new "automatically" installed string in Zypper

.travis.yml, Gemfile, Gemfile.lock
With GitHub's built in security checking service this has increasingly limited value, and with travis getting slower and slower removing a test has real value.
=> Remove Bundle Audit

.travis.yml, kitchen-tests/.kitchen.travis.yml, lib/chef/resource/build_essential.rb
This worked until Amazon released 2.0
=> Don't try to install old GCC packages on Amazon Linux 2

lib/chef/resource/apt_repository.rb, lib/chef/resource/yum_repository.rb, lib/chef/resource/zypper_repository.rb, spec/unit/resource/apt_repository_spec.rb, spec/unit/resource/yum_repository_spec.rb, spec/unit/resource/zypper_repository_spec.rb
We can't write out a filename like foo/bar.repo so we should properly warn the user if they try to give us that. There's probably other things, but this one makes particular sense for apt since people want to use the slash in PPA repo names.
Fixes #6564 
=> Fail with a warning if users specify apt/yum/zypper repos with slashes

lib/chef/resource/apt_repository.rb, spec/unit/resource/apt_repository_spec.rb
We set a lot of nil defaults and did coercions here that are no longer necessary. Since we did accept nil in a lot of these properties at one point we need to keep it so I wrote a note to future me about that. I also added some specs for the remaining coercion and the defaults.
=> Remove Chef 12-isms from the apt_repository resource

lib/chef/resource/build_essential.rb
Add the missing installed? check that makes this fast. Also use tail
instead of head in the execute so we install the latest not the oldest
xcode release if more than 1 is available on the system (upgrades).
=> Add missing installed logic for macos in build_essential

lib/chef/resource/windows_pagefile.rb
@s1mark reported this in the Windows cookbook
=> Pagefile sizes are in megabytes not bytes

chef-config/lib/chef-config/config.rb, lib/chef/client.rb, lib/chef/data_collector/messages/helpers.rb, lib/chef/node.rb, spec/support/shared/context/client.rb, spec/support/shared/examples/client.rb, spec/unit/client_spec.rb, spec/unit/data_collector/messages/helpers_spec.rb, spec/unit/node_spec.rb
We generate the UUID as part of the data collector report, but we didn't
make that available to the node or the chef server otherwise.
cc @jquick
=> Save the node's UUID as an attribute

lib/chef/property.rb
this is effectively dead because of forcing new_resource.thingy
i stuck a hard `raise` in here and we have no tests around this any
more.
the conditional also just makes my head hurt looking at it.
=> remove dead code from property declaration

lib/chef/resource/sudo.rb, spec/unit/resource/sudo_spec.rb
I guess they use .d directory structures in sudo, but that's about it.
=> sudo: Don't fail on FreeBSD. Turns out there's a .d directory

Gemfile.lock, omnibus/Gemfile.lock
This gets us bz2 support in libarchive
=> Use the latest libarchive/bzip2 defs in omnibus

lib/chef/resource/sudo.rb, lib/chef/resource/support/sudoer.erb
1) if use env_keep you'd get incorrect sudo templates written out. Updating to the latest template that was already pushed out in the cookbook is the fix
2) Make sure the visudo_present? method actually returns true
3) Rename visudo_path -> visudo_binary and raise if the old one is used. Release engineering ran into this since they were using the undocumented (not even in a changelog) option that was introduced in Nov.
=> Fix a few bugs in the sudo resource

lib/chef/resource/windows_pagefile.rb, spec/unit/resource/windows_pagefile_spec.rb
I backported locate_sysnative_cmd initially, but after chatting with Stuart this isn't something we need anymore. This removes it and instead uses wmic.exe directly, which in testing works just fine. This also removes the windows friendly path helper which is really just a gsub on the slashes. Instead I changed the coerce to get us what we need in terms of path formats. I copied this to a Windows 2016 box and it works fine with both formats of paths. I'm making this same change to the windows cookbook.
=> Remove path helpers from window_pagefile

RELEASE_NOTES.md, lib/chef/resource/dmg_package.rb, lib/chef/resource/hostname.rb, lib/chef/resource/macos_userdefaults.rb, lib/chef/resource/rhsm_subscription.rb, lib/chef/resource/sudo.rb, lib/chef/resource/swap_file.rb, lib/chef/resource/windows_feature.rb, lib/chef/resource/windows_font.rb
First stab at Chef 14 release notes. Let me know if I got it all. I'm sure there's plenty of typos.
Yes it's really big. That's ok. It's a big release with a lot of things we want people to know about.
=> Add Chef 13.8 and 14.0 release notes

lib/chef/resource/windows_feature_dism.rb, lib/chef/resource/windows_feature_powershell.rb, spec/unit/resource/windows_feature_dism.rb, spec/unit/resource/windows_feature_powershell.rb
This fixes how we parse out the arrays and adds testing to make sure it's doing what we want.
Plus it properly continues on when the user has removed all local feature but specified an external source of those via the registry. That was a reported issue that came in on the cookbook after the rewrite.
Lastly this also fixes a bad method call to the dism method that came over when diffing from the cookbook.
=> Fix array parsing in windows_feature_dism / windows_feature_powershell

lib/chef/resource/windows_feature_dism.rb, spec/unit/resource/windows_feature_dism.rb
We took what they user gave us and compared it to the list of available
packages from dism.exe. In doing so we were case sensitive, but the CLI
doesn't actually care. This just downcases what the user gives us and
what dism gives us so it doesn't matter.
This same change is in windows cookbook 4.1.2
=> windows_feature_dism: Be case insensitive with feature names

lib/chef/resource/hostname.rb, spec/unit/resource/hostname_spec.rb
alphanumeric, -, . or _
Starts with an alphanumeric
We could get a lot more complex here and that might not be a bad idea, but this is probably a step in the right direction.
=> Add basic hostname validation on Windows

lib/chef/provider/service/windows.rb, spec/unit/provider/service/windows_spec.rb
LocalSystem is a special account for the service subsystem, and the security
subsystem doesn't know about it. It inherits rights from BUILTIN\Administrators
so we don't need to check it for SeServiceLogonRight. Even if we look up System
it wouldn't show up as it gets that right from hidden membership in
BUILTIN\Administrators.
=> Avoid lookups for rights of 'LocalSystem' in windows service

lib/chef/resource/homebrew_cask.rb, lib/chef/resource/homebrew_tap.rb
Turns out I was doing this entirely wrong. I've confirmed this fixes the issue I introduced by trying to fix another issue with the usage of the mixin.
Thanks @coderanger for the pointer
=> homebrew_tap / homebrew_cask: Fix compile time errors with the user mixin

.travis.yml, lib/chef/file_content_management/tempfile.rb
this keeps Tempfile.open from internally barfing on ruby-2.5.1
also bumps the ruby version in the travis matrix for testing.
closes #7100
=> scrub tempfile names

lib/chef/resource/windows_feature_dism.rb, lib/chef/resource/windows_feature_powershell.rb
We want to do this better with the singleton, but at the moment this is the exact same method we landed in the dism resource. It's also 3.5x faster than the old method and has behavior changes that landed in the major release of the windows cookbook. We need to make sure those are consistent.
Does it need to be rewritten to not use the node? Yep.
=> Bring in the windows_feature_powershell improvements from the cookbook

chef-config/lib/chef-config/config.rb, lib/chef/http.rb
Signed-off-by: Noam Lerner <noamler@fb.com>
This is another attempt of https://github.com/chef/chef/pull/6985. This makes it so that chef won't sent the `Authorization` header on `GET` or `POST` redirects.
- https://github.com/chef/chef/issues/6984
As a previous PR broke the `:delete` action and got reverted (https://github.com/chef/chef/pull/6996), I'd like to be extra careful here. Please let me know how if you'd like me to test this further. Here's what I did.
- Ran a similar test script using `chef-apply`: https://gist.github.com/bugok/53add64fbb7b2c605068bc648cdb3ccd
- Added the following snippet to one of my cookbooks, and ran chef (successfully): 
```
http_request 'dummy' do
action :get
url 'https://httpbin.org/redirect-to?url=https://www.google.com'
headers({'Authorization' => …
```
=> Stripping Authorization header upon redirects (second try)

lib/chef/provider/package/portage.rb, spec/unit/provider/package/portage_spec.rb
Rewrite portage package provider candidate_version determination and fix tests.
Please see https://github.com/chef/chef/issues/7026 for details.
https://github.com/chef/chef/issues/7026
- [N/A] New functionality includes tests
=> [CHEF-7026] Rewrite portage package provider candidate_version determination and fix tests

lib/chef/resource/hostname.rb
Look for periods instead of the regex value .
Discovered with BFT tests
=> Don't fail on every hostname with windows

RELEASE_NOTES.md
This is an obvious fix so no DCO
=> Remove "unreleased" from the Chef 14 release notes

lib/chef/resource/macos_userdefaults.rb, spec/unit/resource/macos_user_defaults_spec.rb
This is a fix for the improper boolean to int conversion occuring on macos_userdefaults
Fix for https://github.com/chef/chef/issues/7127
=> macos_userdefaults - fix improper boolean to int conversion

lib/chef/chef_fs/chef_fs_data_store.rb, spec/integration/knife/chef_fs_data_store_spec.rb
Fixes a perf bug introduced by #6471 where we were taking O(n^2)
with the number of cookbook versions in the cookbook synch phase.
This is a minimum viable fix that changes the algorithm so that
it does the old, fast method of looking up the CBV first.  Only
if it doesn't find it does it then go searching for cookbooks
that are in a differently named directory but which match by
the name in the metadata.
There may be edge conditions here if people mix-and-match and
have cookbooks which have both named-directory and
name-in-metadata versions.  Please try not to do that.  Don't
cross the streams.
=> fix Chef-14 chef_fs/chef-zero perf regression

.expeditor/config.yml
We no longer care about angrychef for Chef 12
=> Remove 'angrychef' from chef-12 build concerns

.expeditor/config.yml
We no longer care about angrychef for Chef 13
=> Remove angrychef from 'chef-13'

lib/chef/provider/route.rb, lib/chef/resource/route.rb
This allows specifying route metric. metric are already supported by the ifconfig resource so add here also
N/A
=> Add support for route metric

lib/chef/dsl/declare_resource.rb, lib/chef/recipe.rb, lib/chef/resource.rb, spec/unit/dsl/declare_resource_spec.rb
Custom resource actions were picking this up via delegation to
the wrapping resource, and that wiring was removed in 14, so that
API then got dropped accidentally.  This should fix that back
up.  It also consistently injects the resource APIs into resources
and providers both now (and consistently across core resources
and custom resources).
=> add the resources() dsl method back to providers

omnibus/resources/chef/msi/source.wxs.erb
This change allows the Windows Installer (MSI) to attempt to unzip files during repair mode.  This allows for am attempted repair of the Chef Client in case the local install has become damaged.  This change will also be applied to the Chef 13 branch.
Related #7103
=> Windows MSI: files are now re-unzipped during repair mode

lib/chef/provider/route.rb
On RHEL/CentOS, we must specify dev when using metric at least
N/A
=> Some options, i.e. metric, require specifying dev

lib/chef/provider/package/powershell.rb, spec/unit/provider/package/powershell_spec.rb
`powershell_out` wraps the command to run via calling a method `build_powershell_command`.  This method was also implemented with the same name in the `powershell_package` provider but for a different purpose and hence calling `powershell_out` from the provider resulted in incorrect parameters being passed to PowerShell for execution.
Renamed the method in the provider and associated references, and made a small optimization to the PowerShell version detection logic to use an ohai automatic attribute instead of attempting to execute PowerShell to retrieve the version.
Fixes #7166
=> Avoid conflict with build_powershell_command from powershell_out mixin

lib/chef/resource/sudo.rb
This was just a typo that came in from the sudo cookbook
=> Remove duplicate source property in the sudo resource

RELEASE_NOTES.md
OSX 10.10 is deprecated and has been for a while.
=> We no longer build or test on OSX 10.10

.travis.yml
Disable this pending a Chef 14 compatible version of poise
=> Disable testing of poise in travis for now

.travis.yml
it doesn't depend on chef/chef so this test seems quite pointless.
=> removing foodcritic from travis

.travis.yml, lib/chef/chef_fs/chef_fs_data_store.rb, spec/integration/knife/chef_fs_data_store_spec.rb, tasks/bin/run_external_test
- revert the changes to try to lookup chef-zero cookbook using name property.  even after the perf fixes, it caused chef-zero to fail lots of pedant tests, which were masked by the fact that this repo was testing the released version of chef, and pulling master of chef-zero which was still pinned to chef 13.
- test chef-zero and cheffish correctly against PRs and against master.
this reverts the changes in #7143 and #6471
=> actually test against cheffs

ci/verify-chef.sh
Previously, we ran only integration tests. But many of our unit tests
are constrained by rootyness and platform, and this means the first time
they get run is during the ChefDK verification stage, which uses the
released Chef build. So we have no way of fixing test failures short of
a new Chef release.
For those that can see this, http://manhattan.cd.chef.co/job/chefdk-test/architecture=x86_64,platform=el-7,project=chefdk,role=tester/25//console is a perfect example.
=> Run all tests in CI

lib/chef/provider/package/apt.rb, lib/chef/provider/package/zypper.rb, spec/unit/provider/package/apt_spec.rb, spec/unit/provider/package/zypper_spec.rb
Signed-off-by: Jonathan Hartman <j@hartman.io>
These resources don't coerce `package_name` to an array so would raise an
exception when trying to call `name.all?` when `package_name`, and thus `name`,
was a string.
Before applying the provider changes:
```shell
✗ bundle exec rspec spec/unit/provider/package/apt_spec.rb
...
Failures:
1) Chef::Provider::Package::Apt after loading the current resource when locking a package should not lock if the package is already locked
Failure/Error: name.all? { |n| locked_packages.include? n }
NoMethodError:
undefined method `all?' for "irssi":String
2) Chef::Provider::Package::Apt after loading the current resource when unlocking a package should not unlock if the package is already unlocked
Failure/Error: name.all? { |n| locked_packages.include? n } …
```
=> Fix NoMethodError when (un)locking single packages in apt and zypper

.expeditor/config.yml
Enable expire cache enabled release builds for chef-13
=> Enable expire cache enabled builds for chef-13

lib/chef/provider/git.rb, spec/unit/provider/git_spec.rb
high branch/tag churn requires pruning or it will break once a branch name gets re-used. This is very common in feature branch-workflows.
solves #3929
- [X ] New functionality includes tests
- [ X] All tests pass
- [X ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
=> prune remotes with git fetch, fixes #3929

lib/chef/resource/sysctl.rb
This came into the sysctl cookbook https://github.com/sous-chefs/sysctl/pull/127
=> sysctl: Fix ignore_error being ignored

kitchen-tests/cookbooks/base/recipes/default.rb, lib/chef/resource/build_essential.rb, spec/unit/resource/build_essential_spec.rb
This is the same as apt_update. It seems odd to use this resource with a name like this:
```ruby
build_essential "build-essential"
```
=> Allow build_essential resource to be used without setting a name

lib/chef/resource/link.rb
This was accidentally renamed from owner to user. While I'm here add all the descriptions.
=> Fix regression where owner was removed from link resource

lib/chef/resource/launchd.rb, lib/chef/resource/ohai_hint.rb, lib/chef/resource/openssl_rsa_private_key.rb, lib/chef/resource/rhsm_register.rb, lib/chef/resource/scm.rb
These are not state attributes, but we're treating them like state attributes.
=> Set desired_state: false on several properties

lib/chef/resource/registry_key.rb, spec/unit/resource/registry_key_spec.rb
Convert this to a true property. It required updating the specs a tiny bit since key gets returned as a state value now (as it should).
=> Convert :key property in registry_key to use property

lib/chef/resource/subversion.rb
Retained the False = nil behavior which is actually tested in the specs already.
=> Convert properties in subversion to use property

lib/chef/cookbook/remote_file_vendor.rb
Testing with a single remote directory of 100 3 byte files, this drops a chef run from 40 secs to 5 secs when the files are already in the cache (identical to lazy load being disabled).
=> Don't always request lazy files

lib/chef/formatters/base.rb, lib/chef/resource.rb, spec/unit/formatters/base_spec.rb, spec/unit/resource_spec.rb
Directly inspired by https://github.com/sous-chefs/sysctl/pull/127 but more generally people have been asking for this forever so why not?
=> Allow specifying `ignore_failure :quiet` to disable the error spew

omnibus/resources/chef/msi/source.wxs.erb
(Backport of #7111 to Chef 13)
This change allows the Windows Installer (MSI) to attempt to unzip files during repair mode. This allows for am attempted repair of the Chef Client in case the local install has become damaged.
Fixes #7103
=> Windows MSI: files are now re-unzipped during repair mode (Backport to Chef 13)

lib/chef/application/client.rb, spec/integration/client/client_spec.rb
Trying to use --recipe-url on Windows with local file fails, but succeeds on Linux. I'm guessing open-uri doesn't handle local file paths well with `open`? Either way this fixes the issue.
Signed-off-by: tyler-ball <tyleraball@gmail.com>
=> Trying to use --recipe-url on Windows with local file fails

lib/chef/knife/configure.rb
This is already provided by `def confirmation_instructions` in `chef/lib/chef/knife/core/ui.rb`, currently this results in 
```
Overwrite /Users/alexymik/.chef/credentials?? (Y/N)
```
Fixes typo
=> Remove redundant "?" in knife configure

lib/chef/node.rb, spec/unit/node_spec.rb
This means it understands nested roles, avoiding a common footgun. It's technically a behavior change, so perhaps it needs to wait for 15. But I would say that it errs towards what most users expect so maybe we should do it now. Discuss :)
=> Switch Node#role? to use the attributes expansion instead of the run list

lib/chef/provider/git.rb, spec/unit/provider/git_spec.rb
Fix git provider which currently breaks when used with an old git version.
`--prune-tags` was introduced by a very recent git version ([2.17.0](https://github.com/git/git/blob/master/Documentation/RelNotes/2.17.0.txt#L32)) but most supported distros come with rather old git versions which do not have this option and break the git resource.
This PR removes the pruning of tags. Pruning of branches works even with older git versions and should be the most common use case (e.g. when using feature branches) anyway.
This issue is related to the merged PR #7129
- [X ] New functionality includes tests
=> fix git provider: -prune-tags is not available with old git versions, fixes #7233

lib/chef/resource/rhsm_repo.rb
Signed-off-by: Thomas Anderson <thomas@tjanderson.net>
Makes rhsm_repo resource work in a chef converge
#7251
=> repo_name property should be part of new_resource object

chef-config/lib/chef-config/workstation_config_loader.rb, chef-config/spec/unit/workstation_config_loader_spec.rb
Support for toml knife config settings
Enable defining additional (knife) config settings via chef .credentials file.
The goal is that no conditional custom ruby code needs to exist in the client.rb or knife.rb files to support multiple chef organizations.
The new .credentials file has been fantastic and a huge improvement for maintaining one config file which can support multiple chef orgs.  See - https://chef.github.io/chef-rfc/rfc099-authentication-config-file.html
This new feature is limited in that it only currently supports setting the following config values:
node_name, chef_server_url, validation_client_name, validation_key, validator_key, client_key
There are other settings, namely the encrypted data bag secret file, which aren't yet supported.
This adds support for setting any …
=> Support for toml knife config settings

lib/chef/resource/remote_directory.rb, spec/unit/resource/remote_directory_spec.rb
`remote_directory` used to overwrite files by default. When converting to properties, the default was changed to false in PR #7204 probably unintentionally. This PR restores the default and also provides a test case.
=> remote_directory: restore overwrite default

lib/chef/provider/apt_repository.rb
We'll continue to use the resource name to name the apt_update resource, but all the other actions will use the name property as the user would expect.
Fixes #7231 
=> apt_repository: Use the repo_name name property

Gemfile.lock
Previously this would throw a nomapping error.
=> Update win32-taskscheduler gem to fix creating tasks as the SYSTEM user

spec/functional/resource/windows_task_spec.rb
The 2008r2 tester has been failing with an error like:
```
1) Chef::Resource::WindowsTask action :enable enables the disabled task
Failure/Error: expect(current_resource.task.status).to eq("not scheduled")
expected: "not scheduled"
got: "running"
(compared using ==)
```
This has only been happening on the enable and disable tests and appears to be a timing issue. This change gives thoses tests unique names and changes the default name to not be 'chef-client' which is more likely to collide with another test.
This change has passed chef-test on jenkins in an ad-hoc test.
=> Use some unique task names for windows_task functional tests

.expeditor/config.yml, lib/chef/property.rb
This sucks for folk upgrading where a cookbook uses a property called state, like https://github.com/chef-cookbooks/openssl/pull/70
=> we removed the state default property in 13

lib/chef/provider/windows_task.rb, spec/functional/resource/windows_task_spec.rb
Fix for
The new windows_task in chef client v14 does not correctly parse backslashes in the command property- they end up being erased in the task on the node.
#7277 
verified running with following recipes
```
windows_task 'chef-client-test' do
task_name 'chef-client-test1'
command 'chef-client -W -L "C:\\chef\\chef-ad-join.log"'
user 'Administrator'
password 'master#123'
run_level :highest
frequency :daily
end
windows_task 'chef-client-test' do
task_name 'chef-client-test2'
command 'chef-client -W'
run_level :highest
frequency :daily
end
windows_task 'chef-client-test' do
task_name 'chef-client-test3'
command 'chef-client'
run_level :highest
frequency :daily
end
windows_task 'chef-client-test' do
task_name 'chef-client-test4' 
command '"C:\\Program Files\\Git\\git-bash.exe"'
run_level …
```
=> [MSYS-817] fix for windows_task does not parse backslashes in the commad property

lib/chef/cookbook/manifest_v0.rb, lib/chef/cookbook_manifest.rb, lib/chef/cookbook_version.rb, lib/chef/run_context/cookbook_compiler.rb, spec/unit/cookbook/manifest_v0_spec.rb, spec/unit/cookbook_manifest_spec.rb
We weren't consistently naming root files; in some places in the spec
the names contained the `root_files` segment and in other places they
didn't. This now always uses `root_files`.
=> Fix manifest entries for root files

lib/chef/provider/service/systemd.rb, lib/chef/provider/systemd_unit.rb, spec/unit/provider/service/systemd_service_spec.rb, spec/unit/provider/systemd_unit_spec.rb
- Switches out `Etc.getpwuid` for `Etc.getpwnam` in `systemd_unit` provider and `systemd` provider for `service` resource in order to correctly handle usernames set on the resources.
- Fixes issue where `daemon-reload` would be called at the system level for user level unit changes which would leave the updated user units in an incomplete state.
https://github.com/chef/chef/issues/7269
=> Fix systemd_unit user context

lib/chef/cookbook_version.rb
=> Cookbook Version:  add host-<fqdn> to the error message for templates and files specificity

.rubocop.yml, lib/chef/mixin/shell_out.rb, lib/chef/provider/execute.rb, lib/chef/resource/execute.rb, lib/chef/resource/sysctl.rb, spec/functional/resource/execute_spec.rb, spec/unit/mixin/shell_out_spec.rb, spec/unit/provider/apt_update_spec.rb, spec/unit/provider/execute_spec.rb, spec/unit/provider/script_spec.rb
this will wind up replacing shell_out_with_systems_locale.
also fixes an issue in the sysctl provider.
closes #7181
=> add default_env flag to shell_out and execute resource

lib/chef/knife/configure.rb
config[:config_file] is the knife.rb path so we'd either make it look like we were writing to a knife.rb file or it was nil and we'd print a blank file path. Toss in some yard and shuffle things around while I'm in here.
=> Properly print path to config file to the screen in knife configure

lib/chef/guard_interpreter/default_guard_interpreter.rb, lib/chef/provider/service/freebsd.rb, lib/chef/provider/service/init.rb, lib/chef/provider/service/macosx.rb, lib/chef/provider/service/simple.rb, lib/chef/provider/service/systemd.rb, lib/chef/provider/service/upstart.rb, lib/chef/provider/systemd_unit.rb, spec/functional/mixin/shell_out_spec.rb, spec/unit/dsl/recipe_spec.rb, spec/unit/mixin/shell_out_spec.rb, spec/unit/provider/service/arch_service_spec.rb, spec/unit/provider/service/freebsd_service_spec.rb, spec/unit/provider/service/init_service_spec.rb, spec/unit/provider/service/invokercd_service_spec.rb, spec/unit/provider/service/macosx_spec.rb, spec/unit/provider/service/openbsd_service_spec.rb, spec/unit/provider/service/simple_service_spec.rb, spec/unit/provider/service/systemd_service_spec.rb, spec/unit/provider/service/upstart_service_spec.rb, spec/unit/provider/systemd_unit_spec.rb, spec/unit/provider/zypper_repository_spec.rb, spec/unit/provider_spec.rb, spec/unit/resource/conditional_spec.rb, spec/unit/resource_spec.rb
Somewhat mechanically converts old `shell_out_with_systems_locale` to the new API.
=> Convert shell_out_with_systems_locale to `default_env: true` API

lib/chef/provider/package/dnf.rb, lib/chef/provider/package/yum.rb
work towards finishing deprecating the a_to_s api.
=> convert a_to_s to shell_out_compact in DNF/yum

lib/chef/provider/package/windows.rb, spec/unit/provider/package/windows_spec.rb
This raises an error if a local file does not exist when attempting to install a `windows_package`
#7290
=> Check local file exists before installing a windows package

spec/support/shared/functional/securable_resource.rb
This change allows users of Windows 10 machines connected to an Azure Active Directory (AAD) to execute our securable resource tests.  In this scenario, USERDOMAIN is set to the NetBIOS domain name for the AAD (e.g. OPSCODECORP),  but no domain controller is reachable so commands that use USERDOMAIN generally fail.
In non-domain-connected machines (such as Appveyor) USERDOMAIN and COMPUTERNAME should be identical so this change should only have a positive effect of allowing Windows 10 users to run the tests successfully.
=> Allow securable resource tests to work on Windows 10 machines connected to an Azure Active Directory

kitchen-tests/.kitchen.travis.yml, kitchen-tests/.kitchen.yml
stop pulling down ohai master / chef-14 current / ruby-2.5
=> pin kitchen tests to chef-13 on chef-13 branch

CONTRIBUTING.md
GitHub has a capital H.
We don't use the ready for merge label anymore
Mention Expeditor bot actions
Add the projects vs. corporate website links
=> Minor updates to the contributing doc.

lib/chef/provider/package/powershell.rb, lib/chef/resource/powershell_package.rb, spec/unit/provider/package/powershell_spec.rb, spec/unit/resource/powershell_package_spec.rb
Adds a `skip_publisher_check` property and fixes a bug where catalog signing errors would cause the install to fail silently.
https://github.com/chef/chef/issues/7212
=> Add skip_publisher_check property to powershell_package

lib/chef/platform/query_helpers.rb, lib/chef/resource/windows_feature_dism.rb, lib/chef/resource/windows_feature_powershell.rb, spec/unit/resource/windows_feature_dism.rb, spec/unit/resource/windows_feature_powershell.rb
So this one was a few layers deep:
1) We didn't actually need to import the ServerManager module. This was a powershell 2.0 thing, but since we use ConvertTo-Json  we require Powershell 3.0 where this module is autoloaded.
2) Features are only case insensitive on Windows 8 / 2012+. That means we can't lowercase the features on these platforms. We still want to lowercase the features everywhere else because case shouldn't matter and that would be a breaking change.
3) Windows 2008 R2 doesn't have a concept of a removed feature (where the source is gone) so they don't return data the same way when you request features. They just return: Installed: true/false. This means we need to coerce the returned data from 2008 R2 to look like a later Windows release.
Signed-off-by: Tim Smith …
=> Support windows_feature_powershell on Windows 2008 R2

lib/chef/deprecated.rb, lib/chef/resource/freebsd_package.rb, spec/unit/resource/freebsd_package_spec.rb
FreeBSD 10 and later have pkgng and Chef will use that instead. This Oct even FreeBSD 10 goes fully EOL so we'll be supporting multiple EOL versions back come April. We should speed up this resource and simplify things by removing the unnecessary provider and the logic that decides which one to use.
=> Deprecated the Chef::Provider::Package::Freebsd::Pkg provider

lib/chef/mixin/shell_out.rb, lib/chef/provider/package.rb, lib/chef/provider/package/apt.rb, lib/chef/provider/package/bff.rb, lib/chef/provider/package/dnf.rb, lib/chef/provider/package/dpkg.rb, lib/chef/provider/package/freebsd/base.rb, lib/chef/provider/package/freebsd/pkg.rb, lib/chef/provider/package/freebsd/pkgng.rb, lib/chef/provider/package/freebsd/port.rb, lib/chef/provider/package/homebrew.rb, lib/chef/provider/package/ips.rb, lib/chef/provider/package/macports.rb, lib/chef/provider/package/openbsd.rb, lib/chef/provider/package/pacman.rb, lib/chef/provider/package/paludis.rb, lib/chef/provider/package/portage.rb, lib/chef/provider/package/rpm.rb, lib/chef/provider/package/smartos.rb, lib/chef/provider/package/solaris.rb, lib/chef/provider/package/yum.rb, lib/chef/provider/package/zypper.rb, lib/chef/resource/paludis_package.rb, lib/chef/resource/portage_package.rb, spec/unit/provider/package/apt_spec.rb, spec/unit/provider/package/dpkg_spec.rb, spec/unit/provider/package/paludis_spec.rb, spec/unit/provider/package/portage_spec.rb, spec/unit/provider/package/zypper_spec.rb
Collapses down the API a bit better.
I've got some possibly overly paranoid gating to make sure this wouldn't affect anyone's cookbooks, but at the same time this only affects shell_out_compact(), not shell_out() itself.
It found and fixed at least one reported bug:  #6288
Since portage is a compile-from-source I bumped the default timeout up to 3600 on that one and it now should obey user-set timeouts.
Code timeouts always take precedence now, then the new_resource.timeout, then it applies the 900 timeout if that is nil.
closes #6288
=> Make shell_out_compact automatically pull timeouts off the resource + remove uses of shell_out_compact_timeout

lib/chef/provider/package/windows.rb, spec/unit/provider/package/windows_spec.rb
Adds whyrun message on `windows_package` when installing a local file.
Resolves #7348
=> Add whyrun message when installing a local file on Windows

lib/chef/client.rb, lib/chef/node_map.rb, lib/chef/resource.rb, lib/chef/resource_inspector.rb, spec/unit/node_map_spec.rb, spec/unit/resource_spec.rb
Implementation of https://github.com/chef/chef-rfc/pull/305 based on current discussion. May need more changes if that RFC is changed before acceptance.
Probably needs some tweaks to the language of the warning, but this is a start and I think implements the right behavior.
=> Implement rfc107: NodeMap locking for resource and provider handlers

lib/chef/provider/mount/windows.rb, spec/unit/resource/mount_spec.rb
According to mount resource documentation for mount_type, "The directory (or path) in which the device is to be mounted. Default value: the name of the resource block. A customer had tried this and was getting errors when the name was anything but the mount_point. Looking at lib/chef/provider/mount/windows.rb, it shows that net_use is hard-wired to use only the resource name, which conflicts with the documentation. If we change it from name to mount_point, then it will work according to how the documentation specifies.
Windows mount uses `new_resource.name` instead of `new_resource.mount_point` when connecting to a CIFS share
https://getchef.zendesk.com/agent/tickets/18684
=> Mount: Fix errors on Windows when using the mount_point property

lib/chef/resource/chef_handler.rb, lib/chef/resource/dsc_script.rb, lib/chef/resource/hostname.rb, lib/chef/resource/ohai.rb, lib/chef/resource/ohai_hint.rb
These were getting included since we load the world, but we should still probably require what we dep on.
=> Add missing chef/resource requires in resource

lib/chef/provider/package/bff.rb, lib/chef/provider/package/ips.rb, lib/chef/provider/package/macports.rb, lib/chef/provider/package/openbsd.rb, lib/chef/provider/package/rpm.rb, lib/chef/provider/package/solaris.rb, lib/chef/provider/package/windows.rb
We have a package_name name_property in package resources, but we weren't using it everywhere which makes for some super confusing errors / why-run messages
=> package: Make sure to use the package_name name properties

lib/chef/resource/windows_feature_dism.rb
Make sure we dupe the immutable array of the node attribute so we can
concat the additional array values into it later on.
=> windows_feature_dism: Fix errors when specifying the source

Gemfile.lock, chef-universal-mingw32.gemspec, omnibus/Gemfile.lock
- Fixes tasks gets created when wrong username and password is provided and then it throws error for invalid username password.
- Fixes windows_task not idempotent when task_name includes parent folder
=> Pull in win32-taskscheduler 1.0.2

lib/chef/provider/windows_task.rb
When wrong username and password provided in the windows_task recipe it creates the windows_task and raises the exception afterwards. It should not create task when username and password is incorrect.
Updated win32-taskscheduler to set user information at the time of creation of task so that it will validate the user at that time and updated the method defination in windows_task provider.
=> windows_task: Don't allow bad username/password to be provided to a task which will fail later

lib/chef/provider/windows_task.rb, spec/functional/resource/windows_task_spec.rb
The windows_task not idempotent when task_name includes parent folder. The resource will converge every time as a result, even when properties have not changed.
```
windows_task 'MyTask Under MyOrg' do
task_name '\MyOrg\MyTask'
command 'powershell -NoLogo -NonInteractive -ExecutionPolicy Bypass "Write-EventLog -LogName 
Application -EventID 10000 -Source Chef -EntryType Information -Message MyTask_Under_MyOrg"'
run_level :highest
frequency :daily
start_time '03:00'
action :create
end
```
Fixes #7291
Tested with following recipes
```
windows_task 'MyTask Under MyOrg' do
task_name '\MyOrg\MyTask'
command 'powershell -NoLogo -NonInteractive -ExecutionPolicy Bypass "Write-EventLog -LogName Application -EventID 10000 -Source Chef -EntryType Information -Message MyTask_Under_MyOrg"'
run_level …
```
=> windows_task: Fix for task is not idempotent when task name includes parent folder

RELEASE_NOTES.md, chef-config/lib/chef-config/config.rb, lib/chef/chef_class.rb, lib/chef/deprecated.rb, lib/chef/formatters/base.rb, lib/chef/formatters/doc.rb, lib/chef/log.rb, lib/chef/node_map.rb, spec/integration/knife/common_options_spec.rb, spec/unit/chef_class_spec.rb, spec/unit/deprecated_spec.rb, spec/unit/node_map_spec.rb
Also includes a minor overhaul of the deprecation system because it was kind of all over the place.
=> Silence deprecation warnings

chef-config/lib/chef-config/workstation_config_loader.rb, chef-config/spec/unit/workstation_config_loader_spec.rb
This won't work with 100% of Chef config options, but it should cover the majority and avoids situations where we forget to add important options in here in the future.
=> Rework the credentials file system to support any config keys.

RELEASE_NOTES.md, lib/chef/deprecated.rb, lib/chef/mixin/shell_out.rb, lib/chef/provider/package.rb, spec/functional/mixin/shell_out_spec.rb, spec/unit/mixin/shell_out_spec.rb, spec/unit/provider/package_spec.rb
note that this restores the behavior of shell_out_with_timeout()
which downstream consumers may be using, and correctly treats
custom resources and LWRPs the same, along with setting up
removing all this backcompat weirdness in Chef-15.
=> deprecate old shell_out APIs

lib/chef/mixin/wide_string.rb
been a long, long time since we've needed to use iconv.
this does not address the rest of dubiousness of this mixin, but just
cleans out the old codepaths.
=> remove some ruby 1.8.7-isms

spec/unit/cookbook_loader_spec.rb
We keep forgetting to remove this, lets not continue to forget.
=> add spec to force really remove cookbook merging

lib/chef/knife/environment_from_file.rb
This should be in all the plugins and it is except for this one.
=> Add missing require knife

spec/unit/data_collector_spec.rb
Our unit tests keep creating this file that dirties the repo
=> Suppress data_collector.json spec turd file

.travis.yml
Temporarily disables Amazon Linux 2 from Travis pending updates to Omnitruck. This will allow all the GitHub requirements to be satisfied for merge without an admin being involved.
This may not be required if the mixlib-install/omnitruck fixes make it through the pipe first, but preparing just in case.
Related: https://github.com/chef/mixlib-install/pull/259 
Related: https://github.com/chef/omnitruck/pull/364
=> Temporary disable of Amazon Linux 2 from Travis CI

Gemfile
Reduce the amount of verbose logging for bundler on Windows. CI was skipped as this is a dev-only change.
=> Quiet down bundle install/bundle exec messages on Windows [skip ci]

lib/chef/resource/windows_feature_powershell.rb
It should fail on less than 3.0, but not 3.0
This same change was made in the cookbook with the 4.3.3 release
=> windows_feature_powershell: Don't error on PowerShell 3.0

bin/chef-apply, bin/chef-client, bin/chef-service-manager, bin/chef-shell, bin/chef-solo, bin/chef-windows-service, bin/knife
Rubygems is built in Ruby now.
=> Don't require rubygems in our binaries

Gemfile.lock, chef-config/chef-config.gemspec, lib/chef/application.rb
I _think_ this resolves issue #7184
Basically reverting back to the previous logic of
`want_additional_logger?`. It was mentioned in the issue comments that
the comparison against `STDOUT` wasn't working, but it seems to work for
me currently on Centos7.
Signed-off-by: Nolan Davidson <ndavidson@chef.io>
Prevents duplicate stdout_loggers from being created when STDOUT is redirected.
```
#
log_level :info
log_location STDOUT
```
```
chef-client -z -c /tmp/client.rb | head -100
[2018-06-28T15:50:22+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /src/chef.
[2018-06-28T15:50:22+00:00] INFO: Started chef-zero at chefzero://localhost:1 with repository at /src/chef
One version per cookbook
Starting Chef Client, version 14.1.24
[2018-06-28T15:50:22+00:00] INFO: …
```
=> Fix dupe stdout_logger

lib/chef/dsl/platform_introspection.rb, lib/chef/platform/query_helpers.rb, lib/chef/resource/windows_feature_dism.rb, lib/chef/resource/windows_feature_powershell.rb
Move older_than_win_2012_or_8? to platform_introspection and pass in node automatically.
=> Prevent failures using windows_feature due to the platform helper

.travis.yml
Keep CI green by temporarily disabling Amazon Linux 2 on chef-13 branch whilst issues with Omnitruck/Mixlib-install are ironed out.
Related: https://github.com/chef/mixlib-install/pull/259 
Related: https://github.com/chef/omnitruck/pull/364
=> chef-13: Temporarily disable testing on Amazon Linux 2 in Travis

.travis.yml
We've deployed a new omnitruck release which should correct the version
identification bug we had before.
=> Enable Amazon Linux 2.0 tests again

lib/chef/resource/dsc_script.rb, lib/chef/resource/windows_service.rb
Make sure we're calling these properties so we don't further confuse
users.
=> Attributes -> Properties in a few more resources

lib/chef/win32/api/security.rb, lib/chef/win32/security.rb, spec/functional/win32/security_spec.rb
- Added functionality 'remove_account_right' to remove the type of logon that a user account can perform.
- Added functional test case
Signed-off-by: [Nimesh](nimesh.patni@msystechnologies.com)
PR includes addition of a method `remove_account_right` by which we can remove a privilege of a user
#[6716](https://github.com/chef/chef/issues/6716)
=> [MSYS-843] - Add remove_account_right function to win32/security

lib/chef/provider/user/dscl.rb, spec/unit/provider/service/windows_spec.rb, spec/unit/provider/user/aix_spec.rb, spec/unit/provider/user/dscl_spec.rb, spec/unit/provider/user/solaris_spec.rb
the dscl user provider uses mixin/shell_out instead and the specs don't seem to use mixlib/shellout or actually need the require.
=> Remove require mixlib/shellouts where not necessary

lib/chef/knife/core/hashed_command_loader.rb, spec/unit/knife/core/hashed_command_loader_spec.rb
No one outside chef developers knows what the manifest is and we don't actually tell them what command to run. Leave the details out. Just tell them how to fix it.
=> Provide a better error when knife plugins are missing from the cache

.expeditor/config.yml
Remove labels that we don't use in chef/chef. Also remove Chef 12 branch setup.
=> Expeditor: Remove labels that don't exist / chef 12 config

RELEASE_NOTES.md, chef-config/lib/chef-config/mixin/credentials.rb, lib/chef/knife.rb, lib/chef/knife/config_get_profile.rb, lib/chef/knife/config_list_profiles.rb, lib/chef/knife/config_use_profile.rb, lib/chef/knife/core/subcommand_loader.rb, spec/integration/knife/config_get_profile_spec.rb, spec/integration/knife/config_list_profiles_spec.rb, spec/integration/knife/config_use_profile_spec.rb
Mostly because explaining the `.chef/context` file to people is hard, so hide it behind a command. These should probably grow up to be `chef` CLI commands some day but I'm not doing that until we have a better idea of the plan there.
=> Add knife config get/use-profile commands

lib/chef/http/http_request.rb, spec/unit/http/http_request_spec.rb
rubocop rule led to us mutating the argument to the constructor here
and continuously appending query params.
closes #7461
=> Fix duplicated query parameters to resolve Chef::HTTP::Simple regression

lib/chef/knife/cookbook_site_download.rb, lib/chef/knife/cookbook_site_install.rb, lib/chef/knife/cookbook_site_list.rb, lib/chef/knife/cookbook_site_search.rb, lib/chef/knife/cookbook_site_share.rb, lib/chef/knife/cookbook_site_show.rb, lib/chef/knife/cookbook_site_unshare.rb, lib/chef/knife/supermarket_download.rb, lib/chef/knife/supermarket_install.rb, lib/chef/knife/supermarket_list.rb, lib/chef/knife/supermarket_search.rb, lib/chef/knife/supermarket_share.rb, lib/chef/knife/supermarket_show.rb, lib/chef/knife/supermarket_unshare.rb, spec/unit/knife/supermarket_download_spec.rb, spec/unit/knife/supermarket_install_spec.rb, spec/unit/knife/supermarket_share_spec.rb, spec/unit/knife/supermarket_unshare_spec.rb
We want to deprecate knife cookbook site. This moves all the logic into
the knife supermarket plugins and has the legacy knife cookbook site
plugins inherit from that.
=> Move all knife cookbook site plugin logic into knife supermarket

lib/chef/knife/bootstrap.rb
If the user really wanted to run knife boostrap windows then the "hostname" bit here doesn't make sense.
=> Improve the error message when knife bootstrap windows isn't installed 

lib/chef/knife/client_bulk_delete.rb, lib/chef/knife/client_create.rb, lib/chef/knife/client_delete.rb, lib/chef/knife/client_edit.rb, lib/chef/knife/client_list.rb, lib/chef/knife/client_reregister.rb, lib/chef/knife/client_show.rb, lib/chef/knife/data_bag_from_file.rb, lib/chef/knife/environment_create.rb, lib/chef/knife/environment_delete.rb, lib/chef/knife/environment_edit.rb, lib/chef/knife/environment_list.rb, lib/chef/knife/environment_show.rb, lib/chef/knife/role_run_list_remove.rb, lib/chef/knife/role_run_list_set.rb, lib/chef/knife/role_show.rb, lib/chef/knife/user_create.rb, lib/chef/knife/user_delete.rb, lib/chef/knife/user_edit.rb, lib/chef/knife/user_list.rb, lib/chef/knife/user_reregister.rb, lib/chef/knife/user_show.rb
We're not directly manipulating json in these knife plugins. We're using mostly using the  API class or environment/role classes directly.
=> Remove require json_compat where not used

lib/chef/cookbook/gem_installer.rb, lib/chef/exceptions.rb, spec/unit/cookbook/gem_installer_spec.rb
When multiple cookbooks in the run list require the same gem from the gem_installer, and these gem declarations include keyword arguments (e.g. to install the gem from a git repository), the gem_installer will generate an invalid Gemfile.
This should fix this by handling keyword arguments separately and merging them together when necessary. This may still result in unwanted behaviour, if the cookbooks specify different arguments that do not play well together, but at least we will have a valid Gemfile in all cases.
None?
=> Make gem_installer generate a valid Gemfile

lib/chef/mixin/shell_out.rb
broke public API that habitat package cookbook was using, so add
this back but make it deprecated.
=> add back clean_array API

lib/chef/provider/ifconfig/redhat.rb, lib/chef/resource/ifconfig.rb, spec/unit/provider/ifconfig/redhat_spec.rb, spec/unit/provider/route_spec.rb
=> ifconfig: Allow specifying VLAN on RHEL/Centos

omnibus/config/projects/chef.rb
We don't build on RHEL 5 anymore so there's no need to gate this.
=> Remove the platform check from RPM compression in Omnibus

MAINTAINERS.md, MAINTAINERS.toml
@mcquin recently asked that we remove her from the maintainer list.
I also removed the person field for Seth Vargo since he's not on the list anymore
=> Remove mcquin as a maintainer

lib/chef/resource/group.rb, spec/functional/resource/group_spec.rb, spec/unit/resource/group_spec.rb
This converts another resource to use properties and gives each property
a description from the docs site.
It also  makes the string parsing a bit more user spacing proof.
accepted before:
- 1,2,3
accepted now:
- 1,2,3
- 1, 2, 3
- 1 ,2 ,3
- any combo of the above 3
=> group: convert to properties with descriptions and improve comma separated parsing

.travis.yml, appveyor.yml
chef-14 branch doesn't exist yet, but this way we won't have to update
things when we fork
=> Swap chef-12 for chef-14 branches in CI

spec/functional/resource/dnf_package_spec.rb, spec/functional/resource/group_spec.rb, spec/functional/resource/rpm_spec.rb, spec/functional/resource/user/dscl_spec.rb, spec/functional/resource/yum_package_spec.rb, spec/spec_helper.rb
Remove rhel 5 and macos 10.6 exclusions, make groups random characters to match other tests, and add amazon in a few places for if/when we get an amazon tester.
=> Misc cleanup to our functional tests

lib/chef/provider/ifconfig/debian.rb, lib/chef/provider/ifconfig/redhat.rb, lib/chef/resource/ifconfig.rb
This reimplements #6279 after our conversion of this resource to use properties. It also adds support for RHEL since that's documented here:
https://www.centos.org/docs/5/html/Deployment_Guide-en-US/s1-networkscripts-interfaces.html
=> ifconfig: Add gateway property on RHEL/Debian based systems

chef-config/lib/chef-config/path_helper.rb, lib/chef/provider/windows_task.rb, spec/functional/resource/windows_task_spec.rb
- Added a method to split the command and its arguments
- Checked the beaviour when they are inclusive of single/double quotes
- Added specs to test the functionality. Covered a [test](https://github.com/chef/chef/compare/sp/7413)
Fixes: MSYS-855
Signed-off-by: nimesh-msys <nimesh.patni@msystechnologies.com>
Using a custom method to split command and arguments instead of `shellwords`
#7413 
Working fine with
```
command "powershell.exe -file \"C:\\Program Files\\app\\script.ps1\""
```
also supports similar syntax
```
command 'powershell.exe -file "C:\\Program Files\\app\\script.ps1"'
```
=> Handling Quotes in Windows Task Commands and Arguments

spec/functional/win32/security_spec.rb
This resolves the functional test failures so they work on an Azure AD-connected Windows 10 or Windows 2016 machine.  Our tests always create a "local" user however the domain name on an AAD connected machine is the NetBIOS name of the domain (e.g. OPSCODECORP).
Fixes #7440
=> Functional tests: Ensure we logon with the local security_user account

Gemfile.lock, omnibus/Gemfile.lock
Bumped win32-taskscheduler version to 1.0.10 to get latest fix and which resolves breaking functional test in windows_task resource as mentioned in #7502 .
=> Bump dependencies to fix failing functional test for windows_task

MAINTAINERS.md, MAINTAINERS.toml
Adding Stuart Preston as a maintainer, in the Core and Windows components.
=> Adding @stuartpreston as a Chef maintainer [ci skip]

lib/chef/deprecated.rb, spec/unit/chef_class_spec.rb
When the location string during a deprecation check looks like
`/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/spec/unit/chef_class_spec.rb:141:in
'block (4 levels) in <top (required)>'` then trying to silence
deprecation warnings using only an index number (EG,
`Chef::Config[:silence_deprecation_warnings] = [0]`) can end up matching
part of that location string incorrectly. In this case it matched the 0
in the ruby version.
SHACK-304
Signed-off-by: tyler-ball <tball@chef.io>
=> [SHACK-304] Deprecation checking turns up false positive

lib/chef/resource/registry_key.rb, spec/unit/resource/registry_key_spec.rb
The registry_key resource doesn't recognise the keys in the option values hash when passed as an attribute.
Fixes #7367
=> Fix for registry_key resource doesn't recognise keys when passed as attribute.

MAINTAINERS.md, MAINTAINERS.toml
Adding cheeseplus as maintainer
=> Adding cheeseplus as maintainer

lib/chef/application/client.rb
Original error: https://github.com/chef/chef-apply/pull/9
I thought I fixed this in https://github.com/chef/chef/pull/7223 but it
turns out relative or absolute paths continue to match the URI regular
expression. This means that Windows continues to fail to unpack
policyfile tarballs.
Reversing the order of these checks ensures that real paths do not fall
prey to the URI error.
SHACK-290
Signed-off-by: tyler-ball <tball@chef.io>
=> [SHACK-290] Unpacking tarball paths suffer from URI error

lib/chef/resource/rhsm_errata.rb, lib/chef/resource/rhsm_errata_level.rb, lib/chef/resource/rhsm_register.rb, lib/chef/resource/rhsm_repo.rb, lib/chef/resource/rhsm_subscription.rb
These started failing due to changes in how we manage paths when we
shell out.  Instead of messing with paths further this just uses the
absolute paths to the binaries.
=> Prevent failures RHSM resources by using default_env in execute resources

lib/chef/provider/service/debian.rb
Signed-off-by: Guido Schoening <guido.schoeing@gmail.com>
Spring Boot Webapps cat contain an init script as a header of the jar.
By stopping to parse the init script at the marker the binary part of the file is no longer parsed which avoids errors trying to parse binary data as a string. Furthermore to iterate over lines after the marker is unnecessary
=> stop parsing init script at the "### END INIT INFO" marker.

.travis.yml, kitchen-tests/cookbooks/base/recipes/packages.rb, lib/chef/file_content_management/tempfile.rb
To fix travis
Also removing the `aws-sdk` gem from the set of integration tests which install gems to ensure `chef-client` can do what it advertises. This gem takes over 10 minutes to install on centos 6 for some reason, and we no longer install it in Chef master. We shouldn't use this gem to validate that chef can do what it says (with `chef_gem`) because its so massive.
Backporting https://github.com/chef/chef/pull/7104 to Chef 13
SHACK-290
Signed-off-by: tyler-ball <tball@chef.io>
=> Backport for 13: scrub tempfile names

.expeditor/config.yml, .expeditor/update_dep.sh
This uses expeditor subscriptions to automatically cut a PR to update gems when a dependent Chef managed gem is pushed to rubygems.
=> Automatically open PRs on dep gem updates

lib/chef/provider/osx_profile.rb, spec/unit/provider/osx_profile_spec.rb
This prevents an app named profiles being later in the path, which was reported by a user.
=> osx_profile: Use the full path to /usr/bin/profiles

lib/chef/provider/user/windows.rb, spec/unit/provider/user/windows_spec.rb
Currently, User resource on windows applies `comment` as `full_name`, does not allow for setting `description`. Now able to set `comment` as `description` and not as `fullname`. Done testing with below output:
```
PS C:\Users\ashuser> $dom = $env:userdomain
PS C:\Users\ashuser> $usr = $env:username
PS C:\Users\ashuser> ([adsi]"WinNT://$dom/$usr,user").fullname
PS C:\Users\ashuser> ([adsi]"WinNT://$dom/$usr,user").description
the comment
```
Issue fixed : https://github.com/chef/chef/issues/7356
Signed-off-by: NAshwini <ashwini.nehate@msystechnologies.com>
=> Fix issue of setting comment for windows user

Gemfile.lock, chef.gemspec, omnibus/Gemfile.lock
We need this to merge in https://github.com/chef/chef/pull/7353
=> Require mixlib-shellout 2.4 or later

lib/chef/provider/package/yum.rb
We've been relying on the yum libraries to throw away the version
information that we supply here and return the version that is
installed that matches the name + arch.
On el6 32-bit we've hit a bug in the yum libraries where it appears
to not do this.  The simple solution here is to just throw away the
version information ourselves.
I think at one point early in the development of the new yum provider
that there was more of a point to supplying the version here, but as
it evolved that went away, but this argument was still kept around
vestigially.
=> Fix failed RHEL6 32-bit functional tests

lib/chef/provider/package/yum/python_helper.rb
This restarts the yum Python helper before each repo enable/disable in order to work around a bug in the yum API that occurs on CentOS 6.
#7540
=> Restart Python yum helper before each repo enable/disable

lib/chef/provider/windows_task.rb, lib/chef/resource/windows_task.rb, spec/functional/resource/windows_task_spec.rb, spec/unit/resource/windows_task_spec.rb
Support for running tasks when on battery. Properties `disallow_start_on_battery` and `stop_on_battery` is being added.
Fixes https://github.com/chef/chef/issues/6403
=> Support for battery power options in windows_task resource

lib/chef/resource/systemd_unit.rb, spec/unit/resource/systemd_unit_spec.rb
Fixes partial support for systemd unit files by allowing options to be specified multiple times.
Fixes #7559
=> support repeated options in systemd_unit

spec/support/shared/functional/file_resource.rb
not failing here hides issues caused by e.g. mknod not working properly.
=> switch shell_out to shell_out! in func tests

lib/chef/resource/lwrp_base.rb
only set it if the resource doesn't set one.
this means that we don't call resource_name or provides before parsing
the file so that the chef_version_for_provides API in #7524 can work
(otherwise we throw the deprecation warning before we ever parse the
file).
=> lazy the default resource_name until after parsing

Rakefile, chef-config/chef-config.gemspec
Make sure we build our Windows gemspec when on Windows. Previously we handled this via the omnibus-software def, but it made it so the Rake task never worked on Windows.
=> Fix rake task to build the correct gemspec on Chef

.expeditor/update_dep.sh
See if waiting 2 minutes gives rubygems time to catch up.
=> Add a 120 second sleep to the dependency bumping

Rakefile, lib/chef/http.rb, spec/tiny_server.rb
We were trying to parse out a readme file that doesn't exist and the license file which produced errors
We namespaced the task in a way we don't do anywhere else. This matches our other gems now
Tell people to use bundler in the errors instead of gem installing things
We required rubygems which is not necessary
=> Simplify / fix our yard doc Rake task

lib/chef/resource/cron_d.rb
new_resource.cookbook needed to be cookbook inside after_created
=> Resolve new_resource error with cron_d resource

lib/chef/resource/openssl_dhparam.rb, lib/chef/resource/openssl_ec_private_key.rb, lib/chef/resource/openssl_ec_public_key.rb, lib/chef/resource/openssl_x509_certificate.rb, lib/chef/resource/openssl_x509_crl.rb, lib/chef/resource/openssl_x509_request.rb
Update the descriptions, add copyrights, add authors, make sure the cookbook wins until Chef 15 for the legacy openssl_x509 name.
=> openssl resources: Improve descriptions and fix provides for Chef 14.X

lib/chef/resource/openssl_x509_certificate.rb
Make it clear that we want this to be "true" with Chef 15, but right now
the cookbook needs to win for backwards compatibility reasons.
=> Be more explicit in disabling provides for openssl_x509

omnibus/README.md, omnibus/kitchen.hyperv.yml, omnibus/kitchen.yml
Updates omnibus to build using Hyper-V with the `kitchen-vagrant` driver if required.
N/A
=> Updating omnibus kitchen builder to work on Windows 10/Hyper-V

tasks/templates/prerelease.md.erb, tasks/templates/release.md.erb
mixlib-install has been out long enough at this point we don't need to
call it new or mention what version of DK originally shipped with it.
=> Update release announcement templates

.expeditor/update_dep.sh, ci/dependency_update.sh, tasks/dependencies.rb
we're calling scripts to call rake tasks to call scripts to call rake
tasks to mostly execute shellcodes.  this gets rid of at least 2 levels
of indirection.
=> Simplify the rake task to updating gem dependencies

lib/chef/resource/windows_auto_run.rb
This is a custom resource. Removing this just increases readability for anyone used to writing resources in cookbooks.
=> windows_auto_run: Avoid declare_resource where it's not needed

lib/chef/resource_inspector.rb
Previously the inspect method wrote out to stdout which makes it
impossible to use as a library. Now it returns data which the start
method will write to stdout. This allowed me to use this as a library
for auto-generating docs.
=> Allow resource_inspector be used outside the binary

lib/chef/resource/gem_package.rb, lib/chef/resource/openssl_dhparam.rb, lib/chef/resource/openssl_ec_private_key.rb, lib/chef/resource/openssl_ec_public_key.rb, lib/chef/resource/openssl_rsa_private_key.rb, lib/chef/resource/openssl_rsa_public_key.rb, lib/chef/resource/openssl_x509_certificate.rb, lib/chef/resource/openssl_x509_crl.rb, lib/chef/resource/openssl_x509_request.rb, lib/chef/resource/sudo.rb, lib/chef/resource/swap_file.rb, lib/chef/resource/windows_ad_join.rb, lib/chef/resource/windows_auto_run.rb, lib/chef/resource/windows_env.rb, lib/chef/resource/windows_feature_dism.rb, lib/chef/resource/windows_font.rb, lib/chef/resource/windows_package.rb, lib/chef/resource/windows_printer.rb, lib/chef/resource/windows_printer_port.rb, lib/chef/resource/windows_service.rb, lib/chef/resource/windows_task.rb, lib/chef/resource/zypper_package.rb
We allowed String, nil, which is a legacy thing that's not longer necessary. Just make these String.
This syncs all the properties with what I just pushed up to the docs site. It cleans up some wording around owner/group properties and fixes typos.
Signed-off-by: Tim Smith <tsmith@chef.io>d
=> Update property descriptions and remove extra nil types

lib/chef/resource/build_essential.rb
This is a custom resource so we don't need this.
=> Remove unnecessary declare_resource usage in build_essential

lib/chef/cookbook_version.rb, spec/unit/cookbook_version_file_specificity_spec.rb
I noticed that i was not able to use the `remote_directory` resource when the **source** is within the root of the cookbooks /files directory. I would always get a `FileNotFound` exception. 
e.g. with `example_cookbook/files/tmp/test/test_file.txt`
```
files/host-testvbox/tmp/test 	<= works
files/ubuntu-18.04/tmp/test 	<= works
files/ubuntu-18/tmp/test 	<= works
files/ubuntu/tmp/test 		<= works
files/default/tmp/test 		<= works	
files/tmp/test 			<= fails
```
this issue comes from a regex within `lib/chef/cookbook_version.rb` and `preferences_for_path`. It fails to match the last item so i updated the regex to fix and added a unit test that if run without the fix will illustrate the error.
I tested using:
```
Chef Development Kit Version: 3.1.0
chef-client version: 14.2.0
delivery …
```
=> Fix remote_directory does not obey removal of file specificity

lib/chef/resource/paludis_package.rb
This is meant to be an integer, but we didn't specify.
=> paludis_package: Make sure timeout property is an Integer

lib/chef/resource/windows_ad_join.rb
Signed-off-by: Derek Groh <derekgroh@github.io>
Adds the NewName parameter for the Add-Computer command
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/add-computer?view=powershell-5.1#optional-parameters
Stack Overflow request to be able to rename a computer when joining the domain.
=> windows_ad_join resource - add newname property

lib/chef/resource/windows_ad_join.rb
newname matches powershell, but isn't entirely apparent to
non-PowerShell users. We should give it a name that requires no
knowledge outside of Chef. This also adds the introduced field, which we
use to generate docs.
=> Rename windows_ad_join's newname to be new_hostname

MAINTAINERS.md, MAINTAINERS.toml
opensuse should have a lieutenant and I've been working on the overall support in Chef client. I've also been working on the windows/macos side of things.
=> Add @tas50 as the opensuse lieutenant and maintainer for macos / windows

omnibus/Gemfile.lock
This avoids installing yard and related gems with ohai.
=> Pull in updated omnibus-software

.expeditor/config.yml
You can now use `{{version_constraint}}` to reference the version
constraint for your release branch.
https://expeditor.chef.io/docs/getting-started/subscriptions/#subscription-template-variables
=> [Expeditor] Use new template variables in .expeditor/config.yml

MAINTAINERS.md, MAINTAINERS.toml
His github is a 404 and this causes our maintainer scripts to fail since he can't be added to the group.
=> Remove Bryant Lippert as a FreeBSD maintainer

lib/chef/resource/openssl_x509_certificate.rb
I originally left this uncommented, but this actually broke backwards
compatibility more than the potential for Chef winning over the
cookbook. I think we have to just bite the bullet here and let Chef win
in the name of backwards compatibility with the name.
=> Wire up openssl_x509

lib/chef/provider/service/windows.rb
Removes the logging of potentially sensitive information in the log when a Windows service is configured or reconfigured.
#7634
=> windows_service: Remove potentially sensitive info from the log

.github/CODEOWNERS
Since the release notes end up on the docs site we should involve the
docs team as early in the process as possible.
=> Add docs team as owners on readme / release notes

lib/chef/resource/windows_feature_dism.rb, lib/chef/resource/windows_feature_powershell.rb
Removing incorrect grammar, now that the exception message is aware of package quantity.
=> windows_feature: Fix exception message grammar

lib/chef/resource/ohai.rb
This isn't actually used anywhere in the resource and there's no point. It reload's plugins based on the plugin property. We should kill this thing off and reduce the complexity a tiny bit.
=> Deprecate ohai resource's ohai_name property

omnibus/Gemfile.lock
This should properly generate the gems so we have something in artifactory to push when we promote to stable.
=> Update to the latest omnibus-software for builds

lib/chef/resource/ohai_hint.rb
These aren't necessary here and make it harder to read the resource.
=> Remove declare_resource usage in ohai_hint

.expeditor/config.yml, Gemfile.lock, omnibus/Gemfile.lock
Fix the rubyzip CVE and also bring in the mixlib-archive fixes on windows.
=> Update rubyzip to 1.2.2 and mixlib-archive to 0.4.16

lib/chef/resource/user/windows_user.rb, lib/chef/resource/zypper_package.rb
Fixed wrong version description in introduced for newly added properties in zypper_pacakge and windows_user resource.
=> Fixed introduced version to 14.6 for newly added properties in zypper_package and windows_user resource as it got released in 14.6.

lib/chef/provider/package.rb, spec/unit/provider/package/rpm_spec.rb, spec/unit/provider/package_spec.rb
package providers that don't know anything about allow_downgrade should
get true by default.
=> Change the allow_downgrade pseudo-default in the package provider superclass to true

lib/chef/provider/package.rb
combined with the other PRs this will make most of the
subclasses never even call version_compare now.
the subclasses that need allow_downgrade as a feature
should implement both the property and implement
version_compare now.
=> short circuit before the version_compare call

lib/chef/resource/rhsm_errata_level.rb
Signed-off-by: Joshua Colson <joshua.colson@gmail.com>
There is a misspelling in the 'description' property of the rhsm_errata_level resource. The problem causes chef-client to throw an exception when attempting to call the :install action.
I did not create an issue for this as it is such a simple bug.
=> fixed typo in description property of rhsm_errata_level resource

omnibus/Berksfile, omnibus/README.md, omnibus/kitchen.hyperv.yml, omnibus/kitchen.vmware.yml, omnibus/kitchen.yml
Unpin cookbook deps
Remove platforms we don't support anymore
Add new platforms
Update instructions for getting setup in Vagrant Cloud
Fold the kitchen files into a single file
=> Cleanup the Test Kitchen setup in omnibus

chef-universal-mingw32.gemspec, chef.gemspec
We don't actually need these powershell scripts and DLLs on non-Windows platforms. This shaves 300k from our gem size on non-Windows platforms.
I skipped the contributing.md file as well which is useless in a Ruby install.
=> Only include the Windows distro files on Windows

.expeditor/config.yml
This PR enables Habitat package builds of chef-client for the x86_64-linux-kernel2 PackageTarget
Signed-off-by: Scott Macfarlane <smacfarlane@chef.io>
=> Enable x86_64-linux-kernel2 habitat builds for chef-client

appveyor.yml
The Chef repo has Expeditor subscriptions to other repos which
automatically create a PR to bump versions of those dependencies in Chef
when they're released. We were skipping all commits in Appveyor by 'Chef
Expeditor' to avoid testing the automatic version bump commits that
happen on every merge to master.
This change will only skip the version bumps.
=> Tune appveyor skip to only version bumps

Gemfile.lock, chef-universal-mingw32.gemspec
We refactored a number of the helper methods to more safely namespace
them. Nothing should be using those methods outside of
win32-taskscheduler, but we bumped the major version because of the
change.
=> Bump win32-taskscheduler to 2.0

lib/chef/file_content_management/deploy/mv_unix.rb, spec/unit/file_content_management/deploy/mv_unix_spec.rb
Looks to be an at least 5 year old bug here dealing with how POSIX
strips sticky bits off of files on a chown/chgrp.
closes #7711
=> File provider:  fix sticky bits management / preservation

.travis.yml
There's no reason to keep executing our TK tests against ruby 2.4.
=> Run more Travis tests on Ruby 2.5.1

lib/chef/provider/windows_task.rb, lib/chef/resource/windows_task.rb, lib/chef/win32/security/sid.rb, spec/functional/resource/windows_task_spec.rb, spec/unit/provider/windows_task_spec.rb, spec/unit/resource/windows_task_spec.rb
Signed-off-by: Anton Kvashenkin <anton.jugatsu@gmail.com>
This PR adds full support (idempotent) for using localized system account in `windows_task` resource.
I think it would be better to remove hard-coded system accounts and use `Chef::ReservedNames::Win32::Security::SID` to determine if account is actually system or not. This can help us to support all localized versions of Windows.
Closes https://github.com/chef/chef/issues/7629
=> Add support for localized system account to windows_task resource

lib/chef/application.rb, lib/chef/config.rb
This fixes the duplicate logs for `log_location` 
fixes https://github.com/chef/chef/issues/7184
Manual testing completed : 
1. With chef-client
a) when :log_location is set STDOUT
```
[azure@dh-rhel chef]$ bundle exec chef-client -z -o starter -c ../chef-repo/client.rb
[2018-09-27T05:31:18-04:00] INFO: Started chef-zero at chefzero://localhost:1 with repository at /home/azure/chef-repo
One version per cookbook
Starting Chef Client, version 14.5.24
[2018-09-27T05:31:18-04:00] INFO: *** Chef 14.5.24 ***
[2018-09-27T05:31:18-04:00] INFO: Platform: x86_64-linux
[2018-09-27T05:31:18-04:00] INFO: Chef-client pid: 120873
[2018-09-27T05:31:18-04:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping... …
```
=> [chef/chef]Fix duplicate logs

lib/chef/mixin/params_validate.rb
Right now if a user enters an incorrect action they get a message like
this that doesn't print the actions as being symbols. That's super
confusing to new users and results in random cookbook bugs from time to
time.
[2018-10-07T13:26:39-07:00] FATAL: Chef::Exceptions::ValidationFailed: Option action must be equal to one of: nothing, create, remove, modify, manage, lock, unlock!  You passed :whatever.
With this change we properly print out symbols as symbols so it's clear
what the available values are.
[2018-10-07T13:24:09-07:00] FATAL: Chef::Exceptions::ValidationFailed: Option action must be equal to one of: :nothing, :create, :remove, :modify, :manage, :lock, :unlock!  You passed :whatever.
It's a small thing, but I think this will have a pretty big impact on
first time users. This one …
=> Throw better error on invalid resources actions

chef.gemspec
Neither of these are needed in the gem. Gets us back 16k on disk.
=> Don't ship contributing.md and VERSION file in the gem

lib/chef/provider/registry_key.rb, spec/unit/provider/registry_key_spec.rb
Fixes bug with `registry_key` resource when sensitive is true
Tested against Chef 14.5.33 on Windows 2012r2 & 2016
The following example results in `*sensitive value suppressed*` being written to the registry value, instead of `some value`
```ruby
registry_key "HKEY_LOCAL_MACHINE\\path-to-key\\Policies\\System\Demo" do
values [{
name: 'example',
type: :string,
data: 'some value'
}]
sensitive true
action :create
end
```
=> Fix registry key bug when sensitive is true

Gemfile, Gemfile.lock, omnibus/Gemfile.lock
Turns out if we switch to non-git chefstyle we just end up with 2 copies and that's not smaller. Keep it as git since everything else pulls it from git. This does pull in the updated definition that should slim our install by about 400k.
=> Switch back to chefstyle from git and use the updated chef omnibus def

lib/chef/resource/locale.rb
There was a double source in the command, which would fail.
=> Fix locale on RHEL 6 / Amazon Linux

chef-config/lib/chef-config/config.rb, lib/chef/knife/bootstrap.rb
I missed a few of these in Chef 14. This removes the remainder.
=> Remove the deprecated knife bootstrap --identity-file flag

lib/chef/mixin/shell_out.rb, lib/chef/provider/package.rb, spec/functional/mixin/shell_out_spec.rb, spec/unit/mixin/shell_out_spec.rb, spec/unit/provider/package_spec.rb
Whoever wrote the what-to-do-in-Chef-15 notes did a pretty decent job of it, but
the specs for the timeouts could have used a pointer into the code where
the TODOs were located, I got lost there for a few minutes...
=> Do the shell_out deprecations for Chef-15.

lib/chef/dsl/include_recipe.rb
We've been warning on this one for YEARS and we have a Foodcritic rule
for it as well, which has been around since before I was at Chef.
=> Remove legacy require_recipe DSL method

lib/chef/cookbook_loader.rb, lib/chef/exceptions.rb, lib/chef/knife/cookbook_upload.rb, spec/unit/cookbook_loader_spec.rb, spec/unit/knife/cookbook_upload_spec.rb
This has been deprecated since forever.
=> Remove cookbook merging/shadowing from the cookbooker loader

lib/chef/mixin/shell_out.rb
fixes rspec tests with a `let(:new_resource)` from blowing up
still have to do the janky string thing because descendents tracker needs to get nuked...
=> shell_out auto-timeout still needs to be restricted to only providers

lib/chef/platform/rebooter.rb
We're extending this in a few places where we didn't actually require
it. We should probably just require it here.
=> Require mixin::shellout where we use it

appveyor.yml
Currently our rspec run in Appveyor takes 35 minutes. Even with the non-cached first run this dropped it down to 19 minutes, which is about how long our longest Travis run takes.
=> Break out appveyor tests

lib/chef/resource/timezone.rb
Moving towards a world where we properly load the current state. Adds a method that grabs the current timezone and properly fails with a warning message if we don't have the privs we need. Using converge_by and shell_out to set the timezone so we get a nice clean converge messaging vs. execute resources. Also improves the description to give a link to where users can find all the TZ options.
=> Add macOS support to the timezone resource

lib/chef/property.rb, lib/chef/resource.rb, lib/chef/resource/apt_repository.rb, lib/chef/resource/macos_userdefaults.rb, lib/chef/resource_inspector.rb
skip_docs is used to specify a property that we don't want to include in the documentation. We have several of these.
default_description is used to describe the default in a way we'd want to put on the docs site. This is particularly useful for describing all our lazy / computed values.
I've used both of these in resources to show how I think we'll use them. I'm sure I'm missing a few more things that need to be done to get this wired up so let me know what else I need @lamont-granquist 
=> Add skip_docs and default_description to resource properties

lib/chef/resource/mount.rb
We try to coerce the array into a Hash, but we don't allow the Array
value. This makes this actually work as we documented it.
Fixes https://github.com/chef/chef/issues/7620
=> Allow passing array to supports in mount again

lib/chef/resource/dmg_package.rb
1) Remove the "installed" property that was being used to track state and instead properly load the current_value
2) Set desired_state false on several properties that aren't part of the desired state
3) Add missing periods to a few descriptions
4) Remove declare_resource where it's not necessary
5) Fix dmg_name to properly take on app as the default value
6) Move some of the logic into helper methods that can be tested at some point
7) Move some values into default values instead of variables we set later that contained the same logic
8) Improved the error message you get if your package requires setting the EULA
9) Don't use grep to find the string that indicates the EULA is required
10) Use the full path to hdiutil so we're not depending on the PATH variable being correct
11) Accepting …
=> Multiple fixes to dmg_package

lib/chef/cookbook_loader.rb, spec/unit/cookbook_loader_spec.rb
this can be cleaned up by the removal of the multiple loaders per
cookbook (since shadowing / merging is gone) and just because the
logic was getting really weird.
=> Refactor Cookbook loader logic now that we don't support merging

Gemfile, Gemfile.lock
12.0 comes from our ruby 2.4 install already. This same change was made
for chef 14 where Ruby 2.5 shipped with rake 12.3.
=> Pin rake to 12.0 to prevent shipping 2 copies

lib/chef/resource_inspector.rb
We need to .inspect these so the default value is a symbol not the
string version of the symbol.
=> Fix inspector to properly handle defaults that are symbols

kitchen-tests/Gemfile
=> Pull ohai from the 14-stable branch in kitchen tests

Gemfile.lock, omnibus/Gemfile.lock
The previous release did not ship a license file and was failing license validation in Jenkins.
=> Update win32-certstore to include a license

omnibus/package-scripts/angrychef/postrm, omnibus/package-scripts/chef-fips/postrm, omnibus/package-scripts/chef/postrm, spec/support/platform_helpers.rb
Make sure we identify SLES 15 as suse for our zypper tests
Make sure we don't remove the symlinks on SLES when doing an upgrade or the new release will be broken
=> Fix testing / installing on SLES 15

Gemfile.lock
=> Bump win32-certstore to 0.1.11

lib/chef/resource/windows_certificate.rb, lib/chef/resource/windows_share.rb
The initial PR was for the backport, but we don't want these to be
previews in Chef 15
=> Remove preview resource from windows_certificate & windows_share

lib/chef/application/apply.rb
Per issue when we use the reboot resource with chef-apply then it crashes and returns `UncaughtThrowError`. So updated code handles the `UncaughtThrowError` and also reboot the machine.
Fixes https://github.com/chef/chef/issues/4088
```
PS C:\Users\azure\chef> bundle exec chef-apply C:\reboot.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
* reboot[foo] action reboot_now[2018-10-04T12:03:38+00:00] WARN: Rebooting system immediately, requested by 'foo'
[2018-10-04T12:03:38+00:00] WARN: Rebooting system immediately, requested by 'foo'
[2018-10-04T12:03:38+00:00] WARN: Rebooting server at a recipe's request. Details: {:delay_mins=>2, :reason=>"Reboot by
Chef", :timestamp=>2018-10-04 12:03:38 +0000, :requested_by=>"foo"} …
```
=> Fix chef-apply crash for reboot

lib/chef/provider/windows_task.rb
- Minor bug fix to handle `interactive_enabled` property on windows_task resource
- These changes will work once [win32-taskscheduler changes](https://github.com/chef/win32-taskscheduler/pull/75) will be merged
- As of now, this property is only significant for non-system users. For system users, if we need to set `interactive_enabled` we need to do some workarounds on these validations:
1. System users does not require password
2. interactive_enabled requires a password
- Will add test cases
#7801
Signed-off-by: Nimesh <nimesh.patni@msystechnologies.com>
=> Handle `interactive_enabled` property in windows_task resource

lib/chef/resource/mount.rb
Backport from Chef 15:
We try to coerce the array into a Hash, but we don't allow the Array
value. This makes this actually work as we documented it.
=> Allow passing array to supports in mount resource again

lib/chef/property.rb, lib/chef/resource.rb, lib/chef/resource/apt_repository.rb, lib/chef/resource/dmg_package.rb, lib/chef/resource/group.rb, lib/chef/resource/homebrew_cask.rb, lib/chef/resource/homebrew_tap.rb, lib/chef/resource/hostname.rb, lib/chef/resource/macos_userdefaults.rb, lib/chef/resource/openssl_ec_public_key.rb, lib/chef/resource/openssl_rsa_public_key.rb, lib/chef/resource_inspector.rb
Backport from Chef 15 master:
Add new DSL for resource properties:
- skip_docs: don't document a particular property
- default_description: describe a default value since many are calculated
This also syncs some copy edits from the docs site.
=> Automated resource documentation improvements

lib/chef/resource_inspector.rb
We need to .inspect these so the default value is a symbol not the
string version of the symbol.
=> Backport: Fix inspector to properly handle defaults that are symbols

omnibus/package-scripts/angrychef/postrm, omnibus/package-scripts/chef-fips/postrm, omnibus/package-scripts/chef/postrm, spec/support/platform_helpers.rb
Make sure we properly identify SLES 15 as being SLES so we don't remove symlinks. Also make sure we run the tests on our SLES 15 tester node.
=> Backport: Don't remove package symlinks when upgrading Chef on SLES 15

Gemfile.lock, omnibus/Gemfile.lock
=> Update win32-taskscheduler to 2.0.1

lib/chef/mixin/params_validate.rb
Improve the error message when actions are wrong. This is a super confusing error message to get during cookbook development.
=> Backport:  Throw better error on invalid resources actions 

ci/verify-chef.sh
Our tests hammer YUM pretty hard and the EL6 testers get corrupted after some period of time. Rebuilding the RPM database clears up the underlying corruption. We'll do this each test run just to be safe.
=> Automatically rebuild RPM database on EL6 testers

lib/chef/resource/ohai.rb, spec/unit/resource/ohai_spec.rb
This did nothing and we deprecated it already.
=> Remove the deprecated ohai_name property from the ohai resource

lib/chef/provider/windows_task.rb, lib/chef/resource/windows_task.rb, spec/functional/resource/windows_task_spec.rb
- Added a property `description` to allow user to add a description of a task on windows task scheduler
Signed-off-by: kapil chouhan <kapil.chouhan@msystechnologies.com>
- Added a property `description` (String) in windows_task resource
- Consuming the method `comment` of win32-taskscheduler in provider to achieve the functionality
- Ensured the idempotency 
Fixes MSYS-913: windows_task resource should support a 'description' property
Will send another PR on [chef-web-docs](https://github.com/chef/chef-web-docs/blob/master/chef_master/source/resource_windows_task.rst) to update the property once this PR will be merged.
=> Added property `description` on windows_task resource

ci/verify-chef.sh
Bring some stability to our build system
=> Backport: Avoid rhel 6 DB corruption in jenkins RHEL 6 boxes

lib/chef/provider/script.rb
new_resource.code comes from the execute resource and it's a required property there. This can never fire.
=> Remove the check for nil code property in the script provider

lib/chef/node/attribute_collections.rb, lib/chef/node/mixin/immutablize_array.rb, lib/chef/node/mixin/mashy_array.rb, spec/unit/node/immutable_collections_spec.rb, spec/unit/node/vivid_mash_spec.rb
Doing something like:
```
node.default["foo"] = []
node.default["foo"] << { "bar" => "baz }
```
Would result in a Hash instead of a VividMash inserted into the
AttrArray, so that:
```
node.default["foo"][0]["bar"] # gives the correct result
node.default["foo"][0][:bar]  # does not work due to the sub-Hash not
```
This fixes that behavior, but is likely a breaking change to someone
who expects to ingest hashes with symbol keys and get back out symbol
keys, they will now get converted to strings.  This breaking change
is fully 100% intentional.  This makes the node attribute structure
more consistent and predictable.
=> Chef 15 node attribute array fixes

lib/chef/resource/apt_update.rb, lib/chef/resource/build_essential.rb, lib/chef/resource/cab_package.rb, lib/chef/resource/chef_gem.rb, lib/chef/resource/cookbook_file.rb, lib/chef/resource/cron_d.rb, lib/chef/resource/dmg_package.rb, lib/chef/resource/execute.rb, lib/chef/resource/file.rb, lib/chef/resource/hostname.rb, lib/chef/resource/locale.rb, lib/chef/resource/mdadm.rb, lib/chef/resource/mount.rb, lib/chef/resource/powershell_package.rb, lib/chef/resource/remote_directory.rb, lib/chef/resource/sudo.rb, lib/chef/resource/swap_file.rb, lib/chef/resource/sysctl.rb, lib/chef/resource/systemd_unit.rb, lib/chef/resource/windows_ad_join.rb, lib/chef/resource/windows_printer.rb, lib/chef/resource/windows_printer_port.rb, lib/chef/resource/windows_workgroup.rb, lib/chef/resource/zypper_repository.rb
Properly deprecate visudo_path in sudo resource
Add better descriptions, skip some properties, and add default descriptions to others
=> Improve resource descriptions for resource documentation automation

lib/chef/resource/kernel_module.rb
Defer running initramfs_command until end of run. Updating initramfs is expensive and only needs to be performed once
https://github.com/chef/chef/issues/7471
=> Defer running initramfs_command until end of run

RELEASE_NOTES.md, lib/chef/resource/sudo.rb, lib/chef/resource/sysctl.rb, lib/chef/resource/systemd_unit.rb, lib/chef/resource/windows_auto_run.rb, lib/chef/resource/windows_env.rb, lib/chef/resource/windows_feature.rb, lib/chef/resource/windows_feature_dism.rb, lib/chef/resource/windows_feature_powershell.rb, lib/chef/resource/windows_path.rb, lib/chef/resource/windows_share.rb
Update descriptions to match the edits that were done to the docs site. Also fix windows_share to lazily eval the arrays, which is a bugfix + a docs fix the way we generate docs right now.
=> Add additional descriptions to resource and update others

lib/chef/resource_inspector.rb
Only inspec the value if it isn't nil.
=> resource inspector: don't convert nil to "nil" in default values

lib/chef/resource/windows_firewall_rule.rb, spec/unit/resource/windows_firewall_rule_spec.rb
Allow ports to be an integer
Allow ports to be a comma separated list or an array
Workaround a bug in PowerShell where arrays that are converted to json turn into hashes with the count and the value
The quotes around the port are removed because you can't pass '80,8080' in the cmdlet. It has to be a bare 80,8080
=> Allow passing multiple ports in windows_firewall

lib/chef/resource/mdadm.rb, lib/chef/resource/openssl_dhparam.rb, lib/chef/resource/openssl_ec_private_key.rb, lib/chef/resource/openssl_ec_public_key.rb, lib/chef/resource/openssl_rsa_private_key.rb, lib/chef/resource/openssl_rsa_public_key.rb, lib/chef/resource/openssl_x509_certificate.rb, lib/chef/resource/openssl_x509_crl.rb, lib/chef/resource/openssl_x509_request.rb, lib/chef/resource/package.rb, lib/chef/resource/rhsm_errata.rb, lib/chef/resource/rhsm_errata_level.rb, lib/chef/resource/rhsm_register.rb, lib/chef/resource/rhsm_repo.rb, lib/chef/resource/rhsm_subscription.rb, lib/chef/resource/windows_feature.rb, lib/chef/resource/windows_feature_dism.rb, lib/chef/resource/windows_feature_powershell.rb, lib/chef/resource/windows_printer.rb, lib/chef/resource/windows_printer_port.rb, lib/chef/resource/yum_repository.rb, lib/chef/resource/zypper_package.rb, lib/chef/resource_inspector.rb
Better descriptions for many name properties and copy edits from the docs site.
Tweaked default handling again in the resource inspector. We were quoting a lot of odd things like empty arrays or empty strings. The original intent was to quote symbols. Let's just stick to that.
=> Update more descriptions and tweak default handling in chef-resource-inspector

lib/chef/resource/kernel_module.rb
This backports @tomdoherty's fix in #7871
=> Backport: Defer running initramfs_command until end of run

spec/functional/resource/yum_package_spec.rb
Turns out there's no bug here.  We're doing the right thing now, but prior versions of chef were ignoring epochs in versions.  That bug got fixed, so now epochs are compared correctly and leaving the epoch off has an implicit value of '0' so it fails the check if the package has an epoch.
Merging this because it is additional test coverage over useful cases.
See #7552 for background.
=> add tests for yum version with package_source bug

spec/integration/knife/raw_spec.rb, spec/integration/knife/redirection_spec.rb, spec/support/shared/integration/app_server_support.rb
rely on killing the thread to terminate the server, and rely on
thread#join to correctly signal to the main thread that the
server thread is dead, don't leak the server object out of the
helper.
=> Fix the knife integration spec timeouts

spec/integration/knife/raw_spec.rb, spec/integration/knife/redirection_spec.rb, spec/support/shared/integration/app_server_support.rb
rely on killing the thread to terminate the server, and rely on
thread#join to correctly signal to the main thread that the
server thread is dead, don't leak the server object out of the
helper.
=> Chef 14 Backport: fix the knife integration spec timeouts

lib/chef/resource/windows_task.rb
Move the if windows statement from the entire resource to the actual
place where we used Windows specific code. This makes it so we can use
chefspec and the chef-resource-inspector for this resource.
Line 46 is where the check is now. This is the updated version of #7902. Thanks for noticing this @jjustice6
=> Make sure we define windows_task resource on *nix systems

lib/chef/resource/windows_ad_join.rb
Solves an issue where the domain name is required to build the PSCredential object that is required as input to the AD cmdlets behind our windows_ad_join resource. After discussion with the community, it was decided that the UPN format would be valid in more cases, rather than the NetBIOS style (domain\username) approach, plus we require the domain name to be provided in FQDN format anyway.
Fixes #7715
=> windows_ad_join: Switch to UPN format usernames for use with AD cmdlets

lib/chef/resource/windows_ad_join.rb
Backport of #7895 to Chef 14
Fixes #7715
=> Chef 14 Backport: windows_ad_join: Switch to UPN format usernames for use with AD cmdlets

lib/chef/resource/windows_task.rb
Move the if windows statement from the entire resource to the actual
place where we used Windows specific code. This makes it so we can use
chefspec and the chef-resource-inspector for this resource.
(cherry picked from commit 8757bab03081dcbcec159614b67969a9387900bf)
=> Chef 14 Backport: Make sure we define windows_task resource on *nix systems

RELEASE_NOTES.md
Since we branch the main release notes doc was missing a ton of stuff.
We'll probably use this doc for the release notes when we switch the
docs site to markdown so it needs to include the missing releases.
=> Add release notes for missing 14,13,12 versions

lib/chef/resource/windows_feature.rb, spec/unit/resource/windows_feature.rb
This eliminates the need for setting the subresource variable and also allows us to auto-generate docs that are aware of the default.
=> windows_feature: Move provider logic into the default of the install_method property

lib/chef/resource/windows_feature.rb, spec/unit/resource/windows_feature.rb
This eliminates the need for setting the subresource variable and also allows us to auto-generate docs that are aware of the default.
=> Backport: windows_feature: Move provider logic into the default of the install_method property

lib/chef/resource/windows_certificate.rb
This is a helper from the windows cookbook that doesn't exist in core
Chef.
=> Replace usage of win_friendly_path helper in windows_certificate

Gemfile.lock, omnibus/Gemfile.lock
The cheffish bump fixes a bug in the private_key resource which was failing tests in appveyor due to a openssl / ruby bump that occurred there.
=> Update Cheffish to 14.0.4

lib/chef/resource/windows_feature_dism.rb
- Remove `fail_if_removed` condition to allow user to install removed features on windows_feature_dism.
- we have catch error 50 and raise an error like `Error 50 returned by DISM related to parent features, try setting the 'all' property to 'true' on the 'windows_feature_dism' resource.`
Fixes MSYS-873: windows_feature_dism refuses to install removed features
=> windows_feature_dism: support installed deleted features

spec/unit/resource/chef_gem_spec.rb
We removed this config in Chef 13. There's no need to set it in the spec
anymore.
=> Don't set chef_gem_compile_time config in the chef_gem spec

lib/chef/provider/execute.rb, lib/chef/provider/osx_profile.rb, lib/chef/provider/package/apt.rb, lib/chef/provider/package/chocolatey.rb, lib/chef/provider/package/openbsd.rb, lib/chef/resource/directory.rb, lib/chef/resource/execute.rb, lib/chef/resource/yum_repository.rb
We were still calling things attributes when they're actually properties. This fixes some documentation and error messages.
=> Replace several uses of attribute with property in resources

lib/chef/resource/windows_workgroup.rb, spec/unit/resource/windows_workgroup_spec.rb
Instead of converting the passed in reboot property when we use it coerce it when it's passed in. This allows us to easily test the conversion and it makes it so the docs don't include the legacy values.
I also added moved command generation into a method and added tests for that.
=> windows_workgroup: Coerce the provided reboot property and add more tests

chef-config/lib/chef-config/config.rb
These haven't been used since we refactored the yum provider
=> Remove unused yum_timeout and yum_lock_timeout configs

lib/chef/run_context/cookbook_compiler.rb, spec/unit/run_context/cookbook_compiler_spec.rb
This reverts a change which was working around problems caused by
unforked interval runs.  Fixes issues with chefspec, should make
it faster and reduce warning spam.
closes #6450
=> Chef-15:  require instead of load libraries

RELEASE_NOTES.md, lib/chef/provider/package/yum.rb, lib/chef/provider/package/yum/version.rb, lib/chef/resource/package.rb, lib/chef/resource/rpm_package.rb, lib/chef/resource/yum_package.rb, lib/chef/resource/zypper_package.rb, spec/functional/resource/yum_package_spec.rb, spec/unit/provider/package/rpm_spec.rb, spec/unit/provider/package/zypper_spec.rb
The fact that this:
```
package "foo" do
version "1.2.3"
end
```
Does not allow downgrades from version "2.3.4" is surprising non-declarative magic.  The meaning of that block should be to pin that package to that version.  Instead we currently make people realize there's an edge condition and then go hunting for `allow_downgrade true` to fix this behavior.  Instead we can reverse that and now the semantics of that block is exactly what it looks like it says and people who want to do "foo > 1.2.3" will need to use `allow_downgrade false` explicitly.
closes #6484
=> Chef-15: switch default of allow_downgrade to true

lib/chef/resource/windows_share.rb
Solves an issue where if multiple accounts need to be revoked from the share access list, the input is not in a format that can be parsed as a PowerShell string array.
Ref #7956
=> windows_share: Accounts to be revoked should be provided as an individually quoted string array

lib/chef/provider/execute.rb, lib/chef/provider/osx_profile.rb, lib/chef/provider/package/apt.rb, lib/chef/provider/package/chocolatey.rb, lib/chef/provider/package/openbsd.rb, lib/chef/resource/directory.rb, lib/chef/resource/execute.rb, lib/chef/resource/yum_repository.rb
We were still calling things attributes when they're actually properties. This fixes some documentation and error messages.
=> Chef 14: Replace several uses of attribute with property in resources

spec/unit/resource/windows_certificate.rb
These should have been tested when I merged this in. It's easy stuff to verify with unit tests.
=> Chef 14: windows_certificate: Add testing of the defaults and allowed properties

lib/chef/resource/windows_workgroup.rb, spec/unit/resource/windows_workgroup_spec.rb
Instead of converting the passed in reboot property when we use it coerce it when it's passed in. This allows us to easily test the conversion and it makes it so the docs don't include the legacy values.
I also added moved command generation into a method and added tests for that.
=> Chef 14: windows_workgroup: Coerce the provided reboot property and add more t ests

lib/chef/resource/windows_share.rb
=> Chef 14: windows_share: Properly split the users to be revoked using quotes

lib/chef/provider/apt_repository.rb, spec/unit/provider/apt_repository_spec.rb
use --no-tty during apt-keys for gpg
=> Chef 14: apt_repository: prevent gpg key import on newer Debian releases

lib/chef/resource/windows_share.rb
This resource uses powershell under the hood and calls new-smbshare,
which defaults to adding read only access to the everyone group. With
this change when we create the share we'll remove that permission. Once
that's done we'll go about adding our desired permissions. This only
runs once so the overhead is pretty low and fixes idempotency.
=> Chef 14: windows_share: Fix idempotency by removing the "everyone" access

lib/chef/provider/package/apt.rb, spec/unit/provider/package/apt_spec.rb
Includes support for older apt-get (pre-1.1) that does not have this flag as well.
closes #6095
=> Support apt-get --allow-downgrades

lib/chef/provider/package/cab.rb, spec/functional/resource/msu_package_spec.rb
- We have use `shell_out()` instead of directly hitting Mixlib::Shellout `shellout = Mixlib::ShellOut.new("dism.exe /Online /English #{command} /NoRestart", { :timeout => @new_resource.timeout })`
- Then we are using exitstatus rather than raising an error directly
- After that We are maching `Error: 0x800f081e` and raise an error like `The specified package is not applicable to this image.`
Fixes MSYS-918: ZD 20361 - tecRacer GmbH & Co. KG - msu_package / cab_package should check return code of call to dism.exe
=> cab_package: Chef should fail when specified package is not applicable to the image

lib/chef/provider/package/rubygems.rb, spec/unit/provider/package/rubygems_spec.rb
should still maintain backcompat for rubygems < 2.0 for RHEL6 and
other old platforms.
=> gem_package provider supports --no-document and rubygems 3.x

kitchen-tests/kitchen.travis.yml
should fix issues with kitchen tests breaking in travis
after we merge to ohai
=> pull the ohai version from the bundle not from master

lib/chef/provider/package/rubygems.rb, spec/unit/provider/package/rubygems_spec.rb
should still maintain backcompat for rubygems < 2.0 for RHEL6 and
other old platforms.
=> gem_package: support the --no-document flag needed for Ruby 2.6 / rubygems 3

lib/chef/mixin/which.rb
It uses path_to which is in chef_class
=> Make sure which mixin requires chef_class

kitchen-tests/kitchen.travis.yml
since it turns out kitchen-tests/Gemfile.lock isn't actually checked in
the prior change was still just effectively floating on master, this
now makes us parse the ohai version out of the root Gemfile.lock and
use that to install ohai from git in our virt.
=> better kithen ohai pinning

lib/chef/provider/package/dnf/python_helper.rb
Signed-off-by: pixdrift <support@pixeldrift.net>
Bug fix for package resource under RHEL 8 using DNF when no python binary is installed.
RHEL 8 by default does not ship a selected python version, with the preference of python2/python3 left to the user. If a Cookbook was executed on a default system without python installed the install would fail. RHEL 8 does ship a `platform-python` python binary that is used by system tools (including DNF) and is installed on the system. This commit updates the DNF python binary search to look for the `platform-python` binary in its default location `/usr/libexec`. `platform-python` is prioritised in the search as it should be the preferred binary for system tools such as DNF.
#7988
=> package resource: Add RHEL 8 support to DNF package installer

omnibus_overrides.rb
Without this we end up with chef-client's definition using the version
of ohai in the gemfile.lock and the ohai defintion using whatever is in
master. This is bad for two reasons:
1. we're shipping an unreleased master version even when we ship chef 13
or chef 14
2. we ship the ohai gem twice which takes up space on disk
=> Pin the ohai definition to use the ohai version from Gemfile.lock

.travis.yml, chef.gemspec
We haven't fully added 2.6 support, but Chef 15 will continue or RFC defined Ruby support process of supporting N and N-1. Now that the latest Ohai 15 is in the Gemfile.lock the unit tests on Ruby 2.4 fail. This bumps the required version to 2.5 and removes the 2.4 tests.
=> Require Ruby 2.5 or later

spec/functional/resource/group_spec.rb, spec/functional/resource/user/dscl_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb
Rename the macos helpers. Remove unused helpers to check for RHEL 5 and < Windows 2008 R2.
=> Cleanup some functional helpers

lib/chef/dsl/universal.rb, lib/chef/recipe.rb, spec/unit/resource_spec.rb
- I have added a new module `CommonHelpers` for using common methods on both `recipe.rb` and `resource.rb`
- In this module has added `tagged?(tags)` method and included this module on both `recipe.rb` and `resource.rb`
Fixes ZD 20517 
Fixed #7449
=> Allow the use of tagged?(tags) method in both only_if and not_if blocks

lib/chef/win32/version.rb
This change adds a `windows_server_2019?` helper available on an instance of the `Chef::ReservedNames::Win32::Version` class. This will return true on a Windows Server 2019-based machine.
####Usage (Windows Server 2019):
```ruby
> win_version = Chef::ReservedNames::Win32::Version.new
> win_version.windows_server_2019?
=> true
```
=> Chef 15: Windows Server 2019 version detection

lib/chef/win32/version.rb
Backport of #8031 - adding `windows_server_2019?` method to Chef::ReservedNames::Win32::Version class instance.
Closes #8032
=> Chef 14: Windows Server 2019 version detection

lib/chef/client.rb, spec/unit/client_spec.rb
This is a pretty critical bit of data and we're using it for decisions
in the timezone resource now.
=> minimal_ohai: Add init_package plugin as a required plugin

lib/chef/provider/group/windows.rb, lib/chef/resource/group.rb, lib/chef/util/windows/net_group.rb, lib/chef/win32/api/net.rb, lib/chef/win32/net.rb, spec/unit/provider/group/windows_spec.rb, spec/unit/resource/group_spec.rb
- Added a property `comment` to allow user to add a comment of a windows group
- Added a method `net_local_group_set_info` for set a comment of windows group by using `NetLocalGroupSetInfo`
Fixes MSYS-897: Allow setting the comment/description on a Windows group
=> Added property `comment` on Windows group.

omnibus/Gemfile.lock
This will allow the new inspec deps to pass
=> Bump license_scout to 1.0.20 for licensing tests

lib/chef/resource/windows_certificate.rb
Currently  certificate delete action fails if certificate doesn't exist as mentioned here https://github.com/chef-cookbooks/windows/issues/578. This fix handles this. I will be adding same fix on the windows cookbook side too.
We need to merge https://github.com/chef/win32-certstore/pull/45 before merging this.
https://github.com/chef-cookbooks/windows/issues/578
=> windows_certificate: Fix failures in delete action fails if certificate doesn't exist

CHANGELOG.md, RELEASE_NOTES.md
This makes it so people can see 14.X work when you hit the github repo.
=> Add 14.7 and 14.8 release notes and changelog

lib/chef/resource/windows_certificate.rb, spec/unit/resource/windows_certificate.rb
This change will fix  the error `ArgumentError: invalid byte sequence in UTF-8`.
Fixes [chef-cookbooks/windows#582](https://github.com/chef-cookbooks/windows/issues/582)
=> chef 14: windows_certificate: Fix invalid byte sequence errors with pfx certicates

lib/chef/client.rb, spec/unit/client_spec.rb
This is a pretty critical bit of data and we're using it for decisions
in the timezone resource now.
=> chef 14: minimal_ohai: Add init_package plugin as a required plugin

.travis.yml
=> Remove the travis apt proxy for the Ruby 2.4 functional tests

omnibus/omnibus.rb
This has caused a ton of random issues where builders start pulling in
cache from other branches. Every time we get in this state we just
rebuild without the cache and all is fine again. It seems like we should
just disable it at this point since we run builds on 2 branches at the
same time now.
=> Disable s3 omnibus cache

Gemfile.lock, omnibus/Gemfile.lock
=> Update train-core to 1.6.3 for smaller size and new winrm options

omnibus_overrides.rb
These are the last versions of these stable releases. We may want to go
bundler 2.0 / rubygems 3.0, but this is a solid first step.
=> Update rubygems to 2.7.7 and bundler to 1.17.3

MAINTAINERS.md, MAINTAINERS.toml
Remove unsupported platforms Arch, Gentoo, Omnios, and openBSD where we've had just about zero action.
Collapse the opensuse and SLES groups into one since the code is now the same
Remove Chef Provisioning
Fixup the TOML for the change in FreeBSD maintainers
=> Simplify the sub-systems in the Chef maintainers file

Gemfile.lock, lib/chef/provider/windows_task.rb, lib/chef/resource/windows_task.rb, spec/functional/resource/windows_task_spec.rb, spec/unit/resource/windows_task_spec.rb
- Minor changes in validations under `validate_user_and_password` to handle this feature
- `validate_interactive_setting` would no longer be needed
- Simple changes in error verbiage
- Fixes MSYS-924
Signed-off-by: Nimesh <nimesh.patni@msystechnologies.com>
- Non-System users would only need to provide a password for Non-Interactive tasks
- For interactive tasks, they may or may not provide a password
- System users always creates non-interactive tasks and password should not be sent
#7834 
[win32-taskscheduler](https://github.com/chef/win32-taskscheduler/pull/76) needs to be merged and updated for these changes.
=> windows_task resource: Allow non-system users without password

lib/chef/client.rb, spec/unit/client_spec.rb
When critical ohai plugins fail, they currently cause the chef run to `exit(false)`, which makes the chef run_exception "SystemExit: exit", which isn't very clear as to what actually went wrong.
By removing the rescue block the run fails with Ohai::Exceptions::CriticalPluginFailure, with a run_exception akin to ""Ohai::Exceptions::CriticalPluginFailure: The following Ohai plugins marked as critical failed: [:BlockDevice]. Failing Chef run."
=> Don't system exit on ohai CriticalPluginFailure

Gemfile.lock, lib/chef/provider/windows_task.rb, lib/chef/resource/windows_task.rb, spec/functional/resource/windows_task_spec.rb, spec/unit/resource/windows_task_spec.rb
- Minor changes in `validate_user_and_password` to support this feature
- `validate_interactive_setting` would no longer be needed
- Added support to latest version of win32-taskscheduler gem (2.0.4)
- Fixes MSYS-924
Signed-off-by: Nimesh <nimesh.patni@msystechnologies.com>
=> windows_task resource: allow non-system users without password for interactive tasks

.expeditor/update_dep.sh
Pulls in the logic that tyler wrote in DK that performs retries and
validates that the gem was actually updated. This preventts empty PRs
from being opened and shortens the time the job takes to run.
=> Pull in the gem update retry logic from DK

lib/chef/resource/timezone.rb, spec/functional/resource/timezone_spec.rb
This backports the work that @username-is-already-taken2 and @Stromweld did here. We missed bringing this into Chef 14.
=> Chef 14: A windows support to the timezone resource

omnibus/Gemfile.lock
This unbreaks license checks for jaro_winkler gem in Jenkins.
=> Update license_scout to 1.0.22

lib/chef/resource/ssh_known_hosts_entry.rb
You'd get the resource name not the host property in the logging.
=> ssh_known_host_entry: Use the host name_property in debug logging

lib/chef/resource/openssl_ec_private_key.rb, lib/chef/resource/openssl_x509_request.rb
We have a name_property, but we're not using it everywhere here.
Fixes #8105
=> openssl_ec_private_key / openssl_x509_request.rb: properly use the path properties when specified

lib/chef/resource/windows_printer.rb
We have a name_property of device_id for this resource but we weren't using it in the delete_printer method so if you used the name property the deletion would fail.
=> windows_printer: prevent failures when deleting printers and using device_id property

lib/chef/resource/homebrew_cask.rb, lib/chef/resource/homebrew_tap.rb, lib/chef/resource/openssl_ec_private_key.rb, lib/chef/resource/openssl_x509_request.rb, lib/chef/resource/ssh_known_hosts_entry.rb, lib/chef/resource/windows_printer.rb
This backports:
https://github.com/chef/chef/pull/8125
https://github.com/chef/chef/pull/8124
https://github.com/chef/chef/pull/8123
https://github.com/chef/chef/pull/8122
It fixes homebrew_cask, homebrew_tap, windows_printer, openssl_ec_private_key, openssl_x509_request, and ssh_known_host_entry resources to correctly honor name properties that are passed by the user.
=> Backport various name_property fixes in resources from Chef 15

.expeditor/config.yml
This change ensures we are promoting our Hab packages to `current` and
`stable` at the same time we execute said promotions for the Omnibus
packages.
=> Promote Hab package alongside Omnibus package

lib/chef/resource/homebrew_cask.rb
Homebrew cask was merged into homebrew some time ago: https://github.com/Homebrew/homebrew-cask/issues/14384#issuecomment-242328541.
Afterwards the homebrew-cask repositories were also moved to the Homebrew organization.
Also see https://github.com/chef-cookbooks/homebrew/pull/134
Because of that move on Chef 13 and older with this cookbook installing a cask would try to tap `caskroom/cask` every time. If you execute that manually you'll notice that it actually taps `homebrew/cask`.
=> Updates homebrew_cask tap name

lib/chef/resource/homebrew_cask.rb
This fixes an issue where casks would be installed during each chef-client run because the `casked?` check failed.
Interpolation was not taken into account correctly in the `casked?` check.
---
@tas50 Should the changes from the [homebrew](https://github.com/chef-cookbooks/homebrew) cookbook all be backported into Chef? (in case this and #8139 don't cover everything yet)
=> Fix cask resource running each chef-client run

kitchen-tests/cookbooks/end_to_end/recipes/tests.rb, kitchen-tests/kitchen.yml, lib/chef/resource/sysctl.rb
This change will allow user to pass slash separated key/name in `sysctl` resource.
As per the functionality, sysctl resource creates a file in `sysctl.d` directory with the file name as the key/name passed in resource. (`"99-chef-<key>"`). Due to this reason, even if we want to pass slashes in key, then while creating a file it was being considered as a directory and raised an error.
But as per sysctl's syntax, in case an interface name contains dot in it, then other properties must be separated by slash.
```
eg: Interface: ens256.401
valid sysctl key: net/ipv4/conf/ens256.401/rp_filter
```
We should be able to take care of this necessity.
With these changes: 
- Name of the File which is created by chef will always be dot separated
- This would avoid any of it's consideration to a …
=> Sysctl: Allow slashes in key or block name

lib/chef/resource/homebrew_cask.rb
Backports 2 different homebrew_cask fixes from @jeroenj 
#8140 Fix cask resource running each chef-client run
#8139 Updates homebrew_cask tap name
=> homebrew_cask: Ensure the resource is fully idempotent

Gemfile, Gemfile.lock
As Chef 14 goes into stable this avoids the need to keep up with changes in chefstyle. We can chase that on master.
=> Pin Chefstyle to 0.11.2 in chef-14 branch

.travis.yml, lib/chef/cookbook/metadata.rb, spec/data/cookbooks/openldap/metadata.rb, spec/data/metadata/quick_start/metadata.rb, spec/integration/knife/cookbook_show_spec.rb, spec/unit/cookbook/metadata_spec.rb, spec/unit/knife/cookbook_show_spec.rb
We have a foodcritic rule to tell people not to do this
It's not being used anywhere and is just a pile of code we run for no reason
We should start warning that it's an unknown attribute when cookbooks contain these as it's wasted effort on the part of cookbook authors
=> Remove 'attributes'  attribute from cookbook metadata

Gemfile.lock, omnibus/Gemfile.lock
This brings in multiple misc deps that we don't have expeditor setup to subscribe to.
=> Bump all deps to the latest versions

spec/functional/resource/cron_spec.rb, spec/unit/provider_resolver_spec.rb
We have a solaris2 platform, but not a solaris platform.
=> Remove bogus "solaris" platform from specs

lib/chef/deprecated.rb
- In chef-13 whenever we were using the `deprecated:` option in a property on a custom resource, we were facing `subclasses of Chef::Deprecated::Base should define #target` exception at the time of `chef-client` run, so we have added `target` method in `Property` class, now it's working fine.
Fixes #7762
=> Fix for Property deprecations are broken in Chef 13

lib/chef/provider/group/usermod.rb, spec/unit/provider_resolver_spec.rb
We removed hpux support from other parts of ohai / chef. This appears to be the last of it.
=> Remove hpux support from group's usermod provider

omnibus/Gemfile.lock, omnibus_overrides.rb
The new omnibus-software includes a patch I added to fix compilation
failures on non C99 compatible compilers with 2.6.0.
The omnibus release that gets pulled in is also necessary for Ruby 2.6 on macOS
The new nokogiri supports windows on Ruby 2.6, which the previous
version did not.
=> Use the latest omnibus-software and nokogiri

lib/chef/knife/cookbook_site_download.rb, lib/chef/knife/cookbook_site_install.rb, lib/chef/knife/cookbook_site_list.rb, lib/chef/knife/cookbook_site_search.rb, lib/chef/knife/cookbook_site_share.rb, lib/chef/knife/cookbook_site_show.rb, lib/chef/knife/cookbook_site_unshare.rb
Our docs already list this is deprecated. We should make sure users running the command know now.
=> Add a deprecation warning to knife cookbook site

kitchen-tests/cookbooks/end_to_end/metadata.rb, lib/chef/provider/group/groupadd.rb, lib/chef/provider/group/suse.rb, lib/chef/provider/group/usermod.rb, lib/chef/providers.rb, spec/unit/provider/group/usermod_spec.rb, spec/unit/provider_resolver_spec.rb
We had a few places where we checked for legacy opensuse platforms. Chef 15 doesn't support this platform and you won't be able to find binaries via omnitruck. We might as well yank out a bit of provider logic.
Also for some reason usermod has logic in a method for suse, but the provider didn't support that.
=> Remove support for unsupported opensuse < 42 from group provider

.expeditor/config.yml
This means we can run:
/expeditor promote chef-15 15.0.31337
instead of:
/expeditor promote chef/chef:master 15.0.31337
=> Add a project alias in expeditor

lib/chef/knife/supermarket_install.rb, lib/chef/knife/supermarket_share.rb
1) Move everything into the deps blocks
2) don't require shell_out in install since we're not using it. We use mixlib_archive now
=> Cleanup requires / includes in knife supermarket

lib/chef/application/client.rb, lib/chef/cookbook_loader.rb, lib/chef/deprecated.rb, spec/integration/client/client_spec.rb, spec/integration/client/exit_code_spec.rb
These will throw full stop deprecations now.
=> Officially deprecate cookbook shadowing and audit mode

lib/chef/knife/bootstrap/templates/chef-full.erb
omnitruck-direct.chef.io is a legacy URL that now points to the same
place as omnitruck.chef.io, and was originally in place to support
clients with older SSL libraries. However, the backward compatible
behavior of omnitruck-direct hasn't been the case for a while now. This
change just corrects the URL in the bootstrap template also.
https://github.com/chef/chef/pull/4312 was where the omnitruck-direct URL was originally set up.
=> Update knife bootstrap template to use up to date omnitruck URL

lib/chef/provider/execute.rb, lib/chef/resource/execute.rb, lib/chef/resource/script.rb
The execute resource has not been fully converted to using property to set properties. We should convert this to setup properties via the property resource DSL.
Fixes #7063
=> Convert execute_resource remaining properties to use properties 

Gemfile.lock, chef-universal-mingw32.gemspec, lib/chef/resource/windows_certificate.rb, spec/functional/resource/windows_certificate_spec.rb
- Using `add_pfx` of Win32::Certstore to import a PFX certificate with its private key
- Using required version of the `win32-certstore` gem 
- Added Test cases
- Minor cleanup and optimization
We created a method `add_pfx` in `win32-certstore` which uses purely Crypt APIs and without any conversion to other formats or data loss, imports a PFX certificate into the certstore.
Using the same here to import a PFX certificate with its private key.
#8180 
[windows#580](https://github.com/chef-cookbooks/windows/issues/580)
[windows#575](https://github.com/chef-cookbooks/windows/issues/575 )
=> windows_certificate: Import PFX certificates with their private keys

lib/chef/provider/windows_task.rb, spec/functional/resource/windows_task_spec.rb
There was an overhead check before splitting a command and its arguments which was restricting chef to consider empty commands.
#8197
=> windows_task: Properly set command / argumentts so resource updates behave as expected

.travis.yml, omnibus/Gemfile.lock, omnibus_overrides.rb, spec/unit/knife/bootstrap_spec.rb
Both of these have a long list of bugfixes and are the last versions
before major bumps were made. We should get these new versions pulled in
since we're shipping them in DK.
=> Update rubygems to 2.7.8 and bundler to 1.17.3

lib/chef/provider/powershell_script.rb, lib/chef/resource/powershell_script.rb, spec/functional/resource/powershell_script_spec.rb, spec/support/shared/unit/script_resource.rb, spec/unit/provider/powershell_script_spec.rb, spec/unit/resource/powershell_script_spec.rb
- Handling `flags` property at resource level instead of provider
- Fixed the order of concatenating user defined and default flags
- Chef-style maintained
The order of concatenating user input flag and the default flag was incorrect.
`Powershell` would favor the flag value which is happening at last mentioned. Thus, to give priority to user input flag, we should append them at latter place.
#3057 
=> powershell_script: Prefer user provided flags over the defaults

lib/chef/provider/windows_task.rb, spec/functional/resource/windows_task_spec.rb
Backport #8201 
There was an overhead check before splitting a command and its arguments which was restricting chef to consider empty commands.
#8197
=> windows_task: Properly set command / arguments so resource updates behave as expected

lib/chef/chef_fs/file_system/repository/chef_repository_file_system_root_dir.rb
Backport #8202 
- Create directory recursively instead to assume that parent dir should exist.
=> chef-solo: Fixes for extra cookbook_path with parent dir that doesn't exist causes crash

Gemfile, Gemfile.lock, omnibus/Gemfile.lock
fixes #8170
gems do not ship on solaris because they do not compile
=> add ed25519 gemset and update omnibus-software

Gemfile.lock
This properly pins mixlib-cli and provides an ohai user agent when talking to GCE
=> Update Ohai to 13.12.6

lib/chef/provider/group/solaris.rb, spec/functional/resource/group_spec.rb, spec/unit/provider/group/solaris_spec.rb
Now that the functionality matches between solaris and other providers just remove the solaris only / excluded on solaris bits of testing. Then modify the normal tests to not reuse a GID, use high numbered values, and keep the name less than 9 characters.
Based off #8217,  but changes the GID testing floor to work on additional platforms.
=> Alter how we set set group members in solaris / unify group testing

chef-config/lib/chef-config/config.rb, chef-config/spec/unit/config_spec.rb
- Config dir is extracted from the `config_file` if provided otherwise it is set to the `user_home` path and based on the environments (windows or Linux) we provide canonical path but when we set `user_home` it returns as it is, So In order to make it uniform we are returning environments based uniform path for `user_home` dir as well.
#4909
=> Chef::Config: Uniform config dir path separator

RELEASE_NOTES.md
This is a good breaking change, but still a breaking change.
The Chef 14 stuff is just copied here from the Chef 14 branch. No need to review that.
=> Add a breaking change for powershell_script to the release notes

lib/chef/provider/package/chocolatey.rb, spec/unit/provider/package/chocolatey_spec.rb
- Added options parameter while fetching the list of choco packages as is required if the source is private.
-  Minor fixes required in existing specs.
- Added specs for the private source.
Completed: https://github.com/chef/chef/pull/6196
=> chocolatey_package: use provided options when determing available options to allow using private sources

lib/chef/dsl/universal.rb
somehow this was missed in #4942 which makes this DSL much less
useful as a target.
=> add LazyModuleInclude to Universal DSL

Gemfile, Gemfile.lock
rbnacl 6.x no longer supports rbnacl-libsodium
=> pin rbnacl to 5.x

lib/chef/resource/openssl_dhparam.rb, spec/unit/resource/openssl_dhparam_spec.rb
=> allow setting mode for openssl_dhparam after creation

lib/chef/resource/windows_share.rb
Fixes issue where updating a share will cause the share to be deleted
but not re-created until chef is next run, and for chef to fail the run
Signed-off-by: Jason Field <jason@avon-lea.co.uk>
Share cannot update a path without delete and recreate, however logic will only delete and not recreate currently
=> windows_share: Improve path comparison to prevent convering on each run

Gemfile, Gemfile.lock
we need to get onto net-ssh 5.x and the ed25519 gem instead, but that
is more involved
=> rollback rbnacl

Gemfile, Gemfile.lock
we need to get onto net-ssh 5.x and the ed25519 gem instead, but that
is more involved
=> Chef-14: rollback rbnacl

omnibus/.gitignore, omnibus/Gemfile, omnibus/Gemfile.lock
Allow for test-kitchen 2 and remove pry which we don't need here and can be easily added with a local gemfile if need be later.
=> Update omnibus gemfile deps to remove pry

lib/chef/local_mode.rb, lib/chef/monkey_patches/win32/registry.rb, spec/integration/knife/chef_fs_data_store_spec.rb, spec/integration/knife/diff_spec.rb, spec/integration/knife/raw_spec.rb, spec/integration/knife/show_spec.rb, spec/unit/chef_fs/parallelizer.rb, spec/unit/node/attribute_spec.rb
Some of this supports older versions of Ruby 2.1/2.2 and others support Ruby 1.8
=> Remove checks / patches for old versions of Ruby

omnibus_overrides.rb
This resolves a minor CVE that doesn't impact Chef, but should get fixed anyways.
=> Update openssl to 1.0.2r

chef-config/lib/chef-config/config.rb, chef-config/spec/unit/config_spec.rb
Use the appropriate platform path separators on WIndows
Backports #8219
=> Use proper paths on Windows in chef-config

omnibus/Gemfile.lock
Adds these new roots:
GTS Root R1
GTS Root R2
GTS Root R3
GTS Root R4
UCA Global G2 Root
UCA Extended Validation Root
Certigna Root CA
=> Update cacerts to 2019-01-22 file

lib/chef/provider/mount/aix.rb, spec/unit/provider/mount/aix_spec.rb
This PR supersedes #8101. Adds a new blank line `\n\n` when appending a new mount point for AIX, adds a spec and is rebased on master.
Without a newline separating entries, AIX will not allow the entry preceding the one managed by Chef to be mounted anymore - this appears not to be an issue for already-mounted filesystems.
See Zendesk ticket 20952 for more details.
Closes #8101
=> mount: Add proper new lines when on AIX to prevent failures

lib/chef/provider/mount/aix.rb, spec/unit/provider/mount/aix_spec.rb
AIX requires double new lines between mounts in fstab. This backports #8271
=> mount: Add proper new lines when on AIX to prevent failures 

spec/support/chef_helpers.rb
This was an undocumented method that was removed from Ruby 2.5. It's ours now.
ruby/ruby@25d56ea
=> Note that this helper method is no longer a backport

.travis.yml
Move all the generic tests to Ruby 2.6.1 not 2.5.3
Switch from 2.6 to 2.6.1 due to travis breakage
=> Switch tests to Ruby 2.6

lib/chef/provider/service/windows.rb, spec/unit/provider/service/windows_spec.rb
Use idempotent `#action_configure` instead of using older code path that isn't actually idempotent.
- #8080
=> windows_service: Fix action :start to not resets credentials on service

lib/chef/application/client.rb, spec/unit/application/client_spec.rb
Signed-off-by: Adam Bewsher <adam.bewsher@neos.co.uk>
Allows the use of `--delete-entire-chef-repo` in chef-client when also using `--local-mode` with `--recipe-url`
Previously when using these options, chef-client exited with `undefined local variable or method  'recipes_path'`.  This was due to a copy/paste error in https://github.com/chef/chef/pull/4545 and no tests.
=> Allow the use of `--delete-entire-chef-repo`

lib/chef/client.rb, lib/chef/data_bag.rb, lib/chef/policy_builder/expand_node_object.rb, lib/chef/policy_builder/policyfile.rb, lib/chef/run_context.rb, spec/unit/client_spec.rb, spec/unit/run_context_spec.rb
Allow for allocation of the Chef::RunContext without its arguments and
use that to allocate it early.  The APIs are kept backcompatible since
otherwise this has a decent chance of blowing up something like
chefspec.
=> Early allocation of the Chef::RunContext

.expeditor/update_dep.sh, Gemfile.lock, omnibus/Gemfile.lock
Expeditor keeps incorrectly bumping addressable to 2.5.2, which seems like some sort of ruby/bundler bug, which is breaking builds. We're attempting to switch back to ruby 2.5.3. in expeditor to see if that resolves the bumping issues.
=> Pin expeditor to ruby 2.5.3 and bump train to 1.7.6

.expeditor/update_dep.sh, .expeditor/update_version.sh
This should keep out other deps.
=> Attempt a convervative bundle update when bumping chef versions

Gemfile, Gemfile.lock
It doesn't look like we're using this anymore.
=> Remove the travis gem from our gemfile

Gemfile.lock, chef-universal-mingw32.gemspec
Bring in the updated win32-certstore gem and allow bringing in the updated service gem later on.
=> Loosen the win32-cerstore and win32-service dependencies

.github/lock.yml
Old PRs and Issues fall off our radar much faster than 2 months, and in
the case where someone does make a comment and it is missed, then
waiting 2 months to autolock it just makes it worse by having it sit in
limbo.
Any activity on the closed PR/Issue does reset the timer to zero.
=> Lower the lock timeout

.travis.yml, kitchen-tests/kitchen.travis.yml, kitchen-tests/kitchen.yml, omnibus/kitchen.yml
This goes EOL at the end of April and we won't be supporting it in Chef 15 officially although support in code will continue.
=> Remove Ubuntu 14.04 testing

.expeditor/config.yml, .travis.yml, appveyor.yml
This is no longer a supported release and we won't be building or
testing it at this point.
This can be merged April 30th, 2019.
=> Remove chef-13 branch from expeditor/travis/appveyor

.bldr.toml, .expeditor/build.habitat.yml, .expeditor/config.yml
_This is a release engineering change only._
Migrate to using the Buildkite-based Habitat build pipelines.
=> Move to using the v2 Habitat Build functionality

lib/chef/data_collector.rb, spec/unit/data_collector_spec.rb
forces output to UTF-8 so it doesn't throw.
closes #8326
=> fix data collector non-utf8 file output

lib/chef/deprecated.rb, lib/chef/resource/locale.rb, spec/functional/resource/locale_spec.rb, spec/spec_helper.rb, spec/unit/resource/locale_spec.rb
- Deprecated `lc_all` property.
- Provided other features such as if locale is not available, generate that
- Bug fixes and system dependency removed
- Fixes: MSYS-988
Refactored changes as per the discussions on #8100 
#7904
=> locale: Add support to set all LC ENV variables and deprecate LC_ALL

appveyor.yml
They have a ruby26 environment now. We should test with it.
=> Add Ruby 2.6 testing Appveyor

.travis.yml, kitchen-tests/kitchen.travis.yml
We have a dokken box for Debian 10 now. We should integration test PRs against it.
=> Add Debian 10 testing to Travis

spec/functional/resource/group_spec.rb
Some platforms have groups in odd ranges, make sure the gid we select is
not in use.
=> Avoid occasionally randomly reusing a gid in tests

spec/functional/resource/dsc_script_spec.rb
New Windows platforms like 2016 have Powershell 5.
=> Don't force DSC functional tests to PS4

lib/chef/application.rb, lib/chef/node.rb, lib/chef/policy_builder/expand_node_object.rb, spec/integration/client/client_spec.rb, spec/unit/policy_builder/expand_node_object_spec.rb
Previously this was not possible.  Now you can do this:
```
chef-client -o "" ./foo.rb
```
And it will only run foo.rb and not any of the recipes in your
run_list at all.  Node will not be saved at the end.
Useful to one-shot something like keyrotation (which still needs
keys and needs to talk to the chef server API, so this is a
different use case from simple chef-apply).
=> Allow empty strings in -o to result in empty override run list

kitchen-tests/cookbooks/end_to_end/recipes/default.rb, lib/chef/resource/locale.rb, spec/functional/resource/locale_spec.rb
Platforms that don't use /etc/locale.conf aren't supported
Replaces #8358. Also fixes an intermittent failure on MacOS.
=> Limit locale resource to Linux

lib/chef/provider/service/windows.rb, spec/unit/provider/service/windows_spec.rb
As I refactored the `windows_service` resource there are a couple of assumptions that I made originally that turn out to be more harmful than good. i.e. Assuming that when a user removes the `run_as_user` or `delayed_start` properties that they want those property defaults to be enforced. More verbosely stated:
If a user originally has a resource defined as such:
```ruby
windows_service 'MyApp' do
run_as_user 'MyAppsUser'
run_as_password 'MyAppsUserPassword'
startup_type :automatic
delayed_start true
action [:configure, :start]
end
```
And then the user updates the resource to:
```ruby
windows_service 'MyApp' do
startup_type :automatic
action [:configure, :start]
end
```
I think it's more harmful to assume the user wants to configure the service using `LocalSystem` as the `run_as_user` …
=> Prevent accidentally configuring windows_service properties

lib/chef/knife/data_bag_edit.rb, spec/integration/knife/data_bag_create_spec.rb, spec/integration/knife/data_bag_edit_spec.rb, spec/integration/knife/data_bag_show_spec.rb, spec/unit/knife/data_bag_edit_spec.rb
After creating an unencrypted data bag, and trying to edit/encrypt, It was raising exception as shown below.
There was a minor miss while editing. If data is not encrypted, we should be returning data only instead of returning the entire item.
```
// Creating an unencrypted Data Bag
> knife data bag create test box 
Data bag test already exists
Created data_bag_item[box]
// Edit and add encryption
> knife data bag edit test box  --secret 'ab'
Encrypting data bag using provided secret.
Saved data_bag_item[box]
// Raises Exception:
> knife data bag show test box 
ERROR: Chef::Exceptions::ValidationFailed: Property data_bag's value {"encrypted_data"=>"zuDd2Da3eyZiuPehburpE3DD+oJt2TA=\n", "iv"=>"jPNhkdghdNd+IsEP\n", "auth_tag"=>"V772V241NSkUwy+102R6Dg==\n", "version"=>3, …
```
=> Allow encrypting a previously unencrypted data bag

spec/functional/dsl/reboot_pending_spec.rb
The 'Component Based Servicing' registry key is limited by permissions
to Trusted Installer, so we can't easily create/delete it. We do cover
this key in the unit tests, and the other functional tests cover the
code paths already, so we can remove this rather than leaving it
'pending' forever.
Closes #3085
=> Remove a functional test for the reboot_pending DSL

lib/chef/application.rb, lib/chef/application/windows_service.rb, spec/unit/application_spec.rb, spec/unit/log/syslog_spec.rb, spec/unit/log/winevt_spec.rb
You could interpret this error message in 2 different ways. This makes it super clear we're skipping the config file since we couldn't find it.
=> Improve the error message when no config can be loaded

lib/chef/application/solo.rb
This matches our behavior in all our other commands since Chef 12.5.
=> Use color in chef-solo by default on Windows

lib/chef/application/solo.rb
We've updated the descriptions in chef-client over the years and we never copied stuff over to solo.
=> Sync the CLI option descriptions between chef-client and chef-solo

Gemfile.lock, chef.gemspec, lib/chef/knife/list.rb
One step closer to killing off highline. We're just getting the terminal width here, which is super overkill for highline. We're still using it in quite a few other places, but this gets us one step closer to moving over to tty entirely.
=> Replace highline with tty-screen in knife list
