chef/chef

- lib/chef/resource/rhsm_register.rb
Thanks @donwlewis for pointing this out here: https://github.com/chef-partners/redhat-subscription-manager-cookbook/pull/43
> rhsm_register: skip the registration check if force is specified

- lib/chef/resource/apt_preference.rb
- lib/chef/resource/apt_repository.rb
- lib/chef/resource/apt_update.rb
- lib/chef/resource/bash.rb
- lib/chef/resource/batch.rb
- lib/chef/resource/bff_package.rb
- lib/chef/resource/breakpoint.rb
- lib/chef/resource/build_essential.rb
- lib/chef/resource/cab_package.rb
- lib/chef/resource/chocolatey_package.rb
- lib/chef/resource/cookbook_file.rb
- lib/chef/resource/cron.rb
> Add descriptions to more resources

- spec/support/shared/examples/client.rb
- spec/unit/application/client_spec.rb
- spec/unit/application_spec.rb
> fix application tests on linux

- lib/chef/resource/remote_directory.rb
- spec/unit/resource/remote_directory_spec.rb
This isn't all of it, but it's a start
> Convert some of remote_directory to use properties

- CHANGELOG.md
I nuked out 2 items that didn't need to be in there while I was in the file
> Update changelog due to expeditor missing PRs

- ci/verify-chef.sh
> Revert "Run all tests in CI"

- spec/integration/client/client_spec.rb
- spec/integration/client/ipv6_spec.rb
- spec/integration/solo/solo_spec.rb
- spec/spec_helper.rb
- spec/unit/provider/mount/mount_spec.rb
Our more esoteric unices need some more careful hand holding
> Ensure we don't run tests on unsupported platforms

- .expeditor/config.yml
* Add Ubuntu 18.04 testers
* Enable auto deletion of PR branch after merge
> Enable Expeditor PR branch deletion feature

- spec/functional/resource/group_spec.rb
- spec/unit/provider/powershell_script_spec.rb
These should have been caught before.
> Fix two new Chefstyle warnings with Rubocop 0.55

- RELEASE_NOTES.md
Update release notes with Ubuntu-18.04 and Debian-9 platform support
> Update release notes with new supported platforms

- .rubocop.yml
- habitat/config/client.rb
- habitat/config/data_collector_metadata.json
- habitat/default.toml
- habitat/hooks/init
- habitat/hooks/run
- habitat/plan.sh
Updates habitat plan to build chef 13 correctly. Also adds config settings for data-collector
***There are no integration tests to validate this***
> Update Habitat plan to correctly build

- lib/chef/provider/windows_task.rb
- lib/chef/resource/windows_task.rb
- spec/functional/resource/windows_task_spec.rb
- spec/unit/provider/windows_task_spec.rb
> Fix windows_task resource not handling commands with arguments

- lib/chef/resource/hostname.rb
fix regex pattern 
https://github.com/chef/chef/issues/7260
- [x ] All tests pass
> improved regex accuracy lib/chef/resource/hostname.rb

- spec/unit/resource/windows_ad_join.rb
- spec/unit/resource/windows_auto_run_spec.rb
- spec/unit/resource/windows_env_spec.rb
- spec/unit/resource/windows_feature.rb
- spec/unit/resource/windows_feature_dism.rb
- spec/unit/resource/windows_feature_powershell.rb
- spec/unit/resource/windows_font_spec.rb
- spec/unit/resource/windows_pagefile_spec.rb
- spec/unit/resource/windows_path_spec.rb
- spec/unit/resource/windows_printer_port_spec.rb
- spec/unit/resource/windows_printer_spec.rb
- spec/unit/resource/yum_repository_spec.rb
- spec/unit/resource/zypper_repository_spec.rb
Fill in some missing coverage here so we can refactor with confidence.
> Add additional unit tests for resource actions/properties

- lib/chef/resource_inspector.rb
This is a very useful thing to know about a resource.
> Add default_action to the resource inspector

- lib/chef/provider/ifconfig/debian.rb
- spec/functional/resource/ifconfig_spec.rb
- spec/functional/resource/package_spec.rb
> Backport Ubuntu 1804 fixes

- lib/chef/knife.rb
Remove the mention of Chef .10
Remove terremark and bluebox
Add more modern plugins
Avoid some extra work we didn't need to do
> Better errors with uninstalled official knife plugins

- lib/chef/resource_inspector.rb
> resource_inspector: Add default values for properties

- lib/chef/provider/service/windows.rb
- spec/unit/provider/service/windows_spec.rb
Fixes configuration of delayed start when using the `:configure_startup` action.
- #7257
> Fix :configure_startup action to configure delayed start

- lib/chef/provider/git.rb
- spec/unit/provider/git_spec.rb
This pulls in PR #6249 and fixes a chefstyle warning.
> Quote git remote_url property (PR 6249 + chefstyle fix)

- RELEASE_NOTES.md
> Add release notes for Chef 14.2

- RELEASE_NOTES.md
We have more to add here so don't worry about the lack of final version number.
> Add 13.9.X release notes

- omnibus/resources/chef/msi/source.wxs.erb
This is an update to the Support/Help URL that is exposed in Add/Remove Programs on Windows.
> Update help link in Add/Remove Programs on Windows

- lib/chef/resource/homebrew_package.rb
- lib/chef/resource/http_request.rb
- lib/chef/resource/ifconfig.rb
- lib/chef/resource/ips_package.rb
- lib/chef/resource/launchd.rb
- lib/chef/resource/log.rb
- lib/chef/resource/mdadm.rb
> Add more property descriptions to resources

- lib/chef/knife/cookbook_metadata.rb
- lib/chef/knife/cookbook_metadata_from_file.rb
- lib/chef/knife/cookbook_site_download.rb
- lib/chef/knife/cookbook_site_search.rb
- lib/chef/knife/cookbook_site_share.rb
- lib/chef/knife/cookbook_site_show.rb
- lib/chef/knife/cookbook_test.rb
- lib/chef/knife/delete.rb
- lib/chef/knife/deps.rb
- lib/chef/knife/diff.rb
- lib/chef/knife/download.rb
- lib/chef/knife/edit.rb
- lib/chef/knife/list.rb
- lib/chef/knife/raw.rb
- lib/chef/knife/role_env_run_list_add.rb
- lib/chef/knife/role_env_run_list_replace.rb
- lib/chef/knife/role_run_list_add.rb
- lib/chef/knife/role_run_list_replace.rb
- lib/chef/knife/serve.rb
- lib/chef/knife/show.rb
- lib/chef/knife/upload.rb
- lib/chef/knife/xargs.rb
> Add missing knife license headers

- lib/chef/application/client.rb
- spec/integration/client/client_spec.rb
Backporting https://github.com/chef/chef/pull/7223 to Chef 13
N/A
Signed-off-by: tyler-ball <tball@chef.io>
> Trying to use --recipe-url on Windows with local file fails

- chef-config/lib/chef-config/config.rb
- chef-config/lib/chef-config/workstation_config_loader.rb
> fix some chefstyle offenses

- Gemfile.lock
> Bump Ohai to 14.3.0

- Gemfile.lock
- chef-config/chef-config.gemspec
- lib/chef/application.rb
Backports https://github.com/chef/chef/pull/7401
> Backport duplicate logger fix

- lib/chef/guard_interpreter/resource_guard_interpreter.rb
- lib/chef/provider/windows_task.rb
- lib/chef/resource/chocolatey_config.rb
- lib/chef/resource/chocolatey_source.rb
- lib/chef/resource/homebrew_tap.rb
- lib/chef/resource/hostname.rb
- lib/chef/resource/ifconfig.rb
- lib/chef/resource/kernel_module.rb
- lib/chef/resource/ohai_hint.rb
- lib/chef/resource/openssl_dhparam.rb
- lib/chef/resource/openssl_rsa_private_key.rb
- lib/chef/resource/powershell_package.rb
- lib/chef/resource/powershell_package_source.rb
- lib/chef/resource/rhsm_errata.rb
- lib/chef/resource/rhsm_errata_level.rb
- lib/chef/resource/rhsm_register.rb
- lib/chef/resource/rhsm_repo.rb
- lib/chef/resource/rhsm_subscription.rb
- lib/chef/resource/script.rb
- lib/chef/resource/service.rb
- lib/chef/resource/sudo.rb
- lib/chef/resource/sysctl.rb
- spec/functional/resource/bash_spec.rb
- spec/unit/provider/execute_spec.rb
- spec/unit/resource/dsc_script_spec.rb
Just some misc cleanup of resource descriptions.
> Add missing descriptions and add periods after resource the descriptions

- RELEASE_NOTES.md
- lib/chef/resource/ssh_known_hosts_entry.rb
> Add release notes for 14.3

- .expeditor/config.yml
Nuke the Chef 12 config and old labels while I'm in here as well.
> Update Expeditor to cleanup merged PRs

- RELEASE_NOTES.md
> Add CVE we fixed to the 14.2 release notes

- chef-config/lib/chef-config/path_helper.rb
- lib/chef/http/http_request.rb
> Add proper yard deprecated tags on methods

- lib/chef/provider/apt_repository.rb
- lib/chef/provider/apt_update.rb
- lib/chef/provider/cron/unix.rb
- lib/chef/provider/ifconfig.rb
- lib/chef/provider/mdadm.rb
- lib/chef/provider/mount/aix.rb
- lib/chef/provider/mount/mount.rb
- lib/chef/provider/mount/solaris.rb
- lib/chef/provider/osx_profile.rb
- lib/chef/provider/route.rb
- lib/chef/provider/systemd_unit.rb
- spec/unit/provider/apt_repository_spec.rb
- spec/unit/provider/apt_update_spec.rb
- spec/unit/provider/cron/unix_spec.rb
- spec/unit/provider/ifconfig_spec.rb
- spec/unit/provider/mdadm_spec.rb
- spec/unit/provider/mount/aix_spec.rb
- spec/unit/provider/mount/mount_spec.rb
- spec/unit/provider/mount/solaris_spec.rb
- spec/unit/provider/osx_profile_spec.rb
- spec/unit/provider/systemd_unit_spec.rb
- apt_repository
- apt_update
- cron/unix
- ifconfig
- mdadm
- mount (aix, solaris, linux)
- osx_profile
- route
- systemd_unit
> Fixing array args in some unix providers

- lib/chef/provider/ifconfig/redhat.rb
- lib/chef/provider/route.rb
- lib/chef/resource/ifconfig.rb
- spec/unit/provider/ifconfig/redhat_spec.rb
- spec/unit/provider/route_spec.rb
Allow specifying VLAN on RHEL/Centos
N/A
> Allow specifying VLAN & Gateway on RHEL/Centos

- .expeditor/config.yml
> Fix Expeditor action set ordering

- chef-config/lib/chef-config/path_helper.rb
> Fix comment typo

- .expeditor/config.yml
Label aligns with other Expeditor labels.
> Add minor version bumping to Expeditor config

- Gemfile.lock
- chef.gemspec
- lib/chef/resource/windows_task.rb
- Verified the dependencies and test cases: No Threats
Fixes- MSYS-868
Signed-off-by: Nimesh<nimesh.patni@msystechnologies.com>
#7492
> Bump version of ISO8601 to latest (0.11.0)

- lib/chef/provider/windows_task.rb
- lib/chef/resource/windows_task.rb
- spec/functional/resource/windows_task_spec.rb
- spec/unit/resource/windows_task_spec.rb
Add a property to windows_task in core for setting task priority.
Fixes [#6629]
> Add support for setting task priority

- lib/chef/resource/apt_repository.rb
- lib/chef/resource/chocolatey_package.rb
- lib/chef/resource/dpkg_package.rb
- lib/chef/resource/dsc_resource.rb
- lib/chef/resource/dsc_script.rb
- lib/chef/resource/execute.rb
- lib/chef/resource/file.rb
- lib/chef/resource/link.rb
- lib/chef/resource/template.rb
These are straight from our docs when available.
> Add additional resource descriptions

- lib/chef/provider/package.rb
- spec/unit/provider/package/windows_spec.rb
- spec/unit/provider/package_spec.rb
Signed-off-by: piyushawasthi <piyush.awasthi@msystechnologies.com>
added warning if allow_downgrade set to be false and tried to install older version
Fixes https://github.com/chef/chef/issues/7403
> MSYS-858 : added warning if allow_downgrade set to be false and tried to install older version

- lib/chef/node_map.rb
- lib/chef/resource.rb
- spec/unit/resource_spec.rb
also adds the chef_version_for_provides helper method
> add chef_version API to provides lines

- .expeditor/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
> Fix expeditor to fire the right script on gem releases

- Gemfile.lock
> Bump Ohai to 14.4

- .expeditor/update_dep.sh
Don't confuse gem and bundler flags.
> Fix bundle update syntax in update_dep.sh

- omnibus/Gemfile.lock
Let chef-sugar and other deps float
> Update omnibus to 5.6.15

- lib/chef/provider/package/windows.rb
- lib/chef/provider/package/windows/exe.rb
- lib/chef/resource/windows_package.rb
Package resource doesn't suppress all sensitive resource output even if suppress property is used
https://getchef.zendesk.com/agent/#/tickets/18893
> windows_package: Fix package sensitive error

- RELEASE_NOTES.md
- lib/chef/resource/cron_access.rb
Document the new resources and the improvements to existing resources.
> Start work on the 14.4 release notes

- chef-config/lib/chef-config/workstation_config_loader.rb
- lib/chef/knife/core/bootstrap_context.rb
Fixes #7561 in two different ways for maximum fixage.
> Validatorless bootstrap fix

- .expeditor/update_dep.sh
Update this to the same script we use in DK
> Fix how dep bumping works

- .expeditor/update_dep.sh
Without this our version bump PRs fail our DCO check.
> DCO sign off the version bump

- Gemfile.lock
- omnibus/Gemfile.lock
> Update to Ohai 14.4.2

- README.md
- Rakefile
- omnibus_overrides.rb
Update the readme with the correct rake tasks to build chef
Fix a typo in the rake comments
Add a comment we have in DK to remind folks that they need to update the deps after changing the overrides.
> Update some build / updating instructions for development

- lib/chef/resource/windows_feature_powershell.rb
This was left empty by mistake.
> Add missing description to windows_feature_powershell

- RELEASE_NOTES.md
Link to the docs site so we don't have enormous release notes
Thank everyone that contributed
Add the openssl security update
Add all the openssl resources we added
Add the battery properties for windows_task
Add the improvement to systemd_unit
> Finalize the 14.4 release notes

- lib/chef/resource/openssl_dhparam.rb
- lib/chef/resource/openssl_ec_private_key.rb
- lib/chef/resource/openssl_ec_public_key.rb
- lib/chef/resource/openssl_rsa_private_key.rb
- lib/chef/resource/openssl_rsa_public_key.rb
- lib/chef/resource/openssl_x509_certificate.rb
- lib/chef/resource/openssl_x509_crl.rb
- lib/chef/resource/openssl_x509_request.rb
- lib/chef/resource/package.rb
- lib/chef/resource/sysctl.rb
- lib/chef/resource/windows_shortcut.rb
- lib/chef/resource/windows_task.rb
- lib/chef/resource/yum_repository.rb
- lib/chef/resource/zypper_package.rb
- lib/chef/resource/zypper_repository.rb
Gets us closer to being able to generate docs from the Chef sourcecode. This adds missing documentation fields and update many that weren't synced with the docs site.
> Add additional property docs + update existing docs

- RELEASE_NOTES.md
Signed-off-by: Kimberly Garmoe <kgarmoe@chef.io>
Syncs the release notes with the docs release notes.
> Edits to RELEASE_NOTES.md

- lib/chef/resource/apt_package.rb
- lib/chef/resource/apt_repository.rb
- lib/chef/resource/build_essential.rb
- lib/chef/resource/chocolatey_package.rb
- lib/chef/resource/ohai.rb
- lib/chef/resource/route.rb
- lib/chef/resource/systemd_unit.rb
- lib/chef/resource/windows_font.rb
- lib/chef/resource/yum_package.rb
- lib/chef/resource/zypper_package.rb
Getting the auto generated docs ready 1 fix at a time.
> Add introduced versions for properties and more descriptions

- RELEASE_NOTES.md
- lib/chef/mixin/powershell_out.rb
- lib/chef/provider/dsc_resource.rb
- lib/chef/provider/dsc_script.rb
- lib/chef/provider/package/powershell.rb
- lib/chef/provider/powershell_script.rb
- lib/chef/resource/dsc_resource.rb
- lib/chef/resource/powershell_package.rb
- lib/chef/resource/powershell_package_source.rb
- lib/chef/util/powershell/cmdlet.rb
- spec/functional/resource/dsc_resource_spec.rb
- spec/functional/resource/powershell_script_spec.rb
- spec/functional/win32/crypto_spec.rb
- spec/unit/platform/query_helpers_spec.rb
- spec/unit/provider/dsc_resource_spec.rb
- spec/unit/provider/dsc_script_spec.rb
- spec/unit/resource/dsc_resource_spec.rb
- tasks/templates/prerelease.md.erb
It's PowerShell not Powershell. Our docs site had already been updated.
> Properly capitalize PowerShell in descriptions and errors

- lib/chef/resource_inspector.rb
We need this to autogenerate documentation.
> Add required properties to the resource inspector output

- .expeditor/config.yml
- .expeditor/update_dep.sh
> Update expeditor config to use subscriptions

- omnibus/Gemfile.lock
This includes several bugfixes and is now up in omnibus-software repo.
> Update libarchive to 3.3.3

- lib/chef/resource/ohai_hint.rb
- lib/chef/resource/rhsm_errata_level.rb
Update these to match copy fixes we made on the docs site.
> Fix resource descriptions for ohai_hint and rhsm_errata_level

- lib/chef/resource/homebrew_cask.rb
- lib/chef/resource/homebrew_tap.rb
- lib/chef/resource/hostname.rb
- lib/chef/resource/locale.rb
More syncing of wording from the docs site so we can generate the content on the docs site.
> More Resource doc fixes

- RELEASE_NOTES.md
- lib/chef/resource/ifconfig.rb
- lib/chef/resource/windows_workgroup.rb
> Add Chef 14.5 release notes

- lib/chef/resource/action_class.rb
- lib/chef/resource/mount.rb
Bump when we're going to kill this off so we can search for Chef-15 in the codebase.
> Add a tiny bit more yard

- MAINTAINERS.toml
As discussed with @tas50, add myself as a maintainer for chef-provisioning since we end up keeping it running a lot!
Signed-off-by: Jaymz Julian <jjulian@limepoint.com>
> Add @jjlimepoint as a maintainer for chef-provisioning

- lib/chef/resource/windows_ad_join.rb
I 1/2 renamed this property name.
> Fix failures in windows_ad_join in 14.5.27

- RELEASE_NOTES.md
Small regression release to get the windows_ad_join fix out.
> Add Chef 14.5.33 Release Notes

- lib/chef/provider/user/windows.rb
- lib/chef/resource/user/windows_user.rb
- spec/functional/resource/user/windows_spec.rb
- spec/unit/provider/user/windows_spec.rb
Adds full_name property to user resource for Windows.
#7542
> Adds full_name property to user resource for Windows.

- RELEASE_NOTES.md
> Add Chef 13.11 release notes

- lib/chef/provider/package/windows.rb
the windows package provider is doing some very strange, and very likely
very buggy things.
i don't have the time or the knowledge right now to unwind these though.
> add some big FIXMEs

- omnibus/Gemfile.lock
- omnibus/config/projects/chef.rb
reduces the size of the installed omnibus package from 191 MB to 132 MB
> Add chef-cleanup omnibus-software defn

- lib/chef/knife/bootstrap.rb
This PR add some documentation for method
Chef::Knife::Bootstrap#validate_options!.
> better docs for Chef::Knife::Bootstrap#validate_options!

- appveyor.yml
- Avoid running on Expeditor changes
- Avoid running on CHANGELOG/RELEASE_NOTES changes
https://ci.appveyor.com/project/chef/chef/history
https://www.appveyor.com/docs/build-configuration/#skip-matrix-jobs-conditionally
https://www.appveyor.com/docs/how-to/filtering-commits/
> Configure Appveyor to skip some commits

- omnibus/Gemfile.lock
> Update omnibus deps

- omnibus/Gemfile.lock
- omnibus/config/projects/chef.rb
> Update omnibus to use ruby-cleanup definition

- Gemfile
- Gemfile.lock
This gets us some nice new functionality in InSpec.
> Update InSpec to 3.0

- Gemfile.lock
- omnibus/Gemfile.lock
Each of these trims the included files a bit.
> Update chef-vault and serverspec to the latest

- .travis.yml
Get the latest bugfix release in Travis
> Test on Ruby 2.4.5 in Travis not 2.4.4

- RELEASE_NOTES.md
> Add release notes for Chef 14.6

- lib/chef/resource/chocolatey_config.rb
- lib/chef/resource/chocolatey_source.rb
- lib/chef/resource/cron_access.rb
- lib/chef/resource/cron_d.rb
- lib/chef/resource/kernel_module.rb
- lib/chef/resource/locale.rb
- lib/chef/resource/openssl_ec_private_key.rb
- lib/chef/resource/openssl_ec_public_key.rb
- lib/chef/resource/openssl_x509_certificate.rb
- lib/chef/resource/openssl_x509_crl.rb
- lib/chef/resource/openssl_x509_request.rb
- lib/chef/resource/powershell_package_source.rb
- lib/chef/resource/ssh_known_hosts_entry.rb
- lib/chef/resource/timezone.rb
- spec/unit/resource/chocolatey_config_spec.rb
- spec/unit/resource/chocolatey_source_spec.rb
- spec/unit/resource/kernel_module_spec.rb
- spec/unit/resource/ssh_known_hosts_entry_spec.rb
These will now load and cookbook resources will not.
> Make all Chef 14 preview resources into full resources

- lib/chef/resource/dmg_package.rb
- lib/chef/resource/group.rb
- lib/chef/resource/homebrew_cask.rb
- lib/chef/resource/homebrew_tap.rb
- lib/chef/resource/hostname.rb
- lib/chef/resource/macos_userdefaults.rb
- lib/chef/resource/openssl_ec_public_key.rb
- lib/chef/resource/openssl_rsa_public_key.rb
Minor syncs from the docs site.
> Update description fields from the docs site

- lib/chef/provider/route.rb
- lib/chef/resource/route.rb
- spec/unit/resource/route_spec.rb
Add descriptions and remove unused properties.
> Remove unused route resource properties

- Gemfile.lock
- RELEASE_NOTES.md
- omnibus/Gemfile.lock
> Update Ohai to 13.12.4

- .expeditor/config.yml
> Setup expeditor for chef-14 branch

- appveyor.yml
> Backport: Break out appveyor tests

- lib/chef/resource/timezone.rb
Moving towards a world where we properly load the current state. Adds a method that grabs the current timezone and properly fails with a warning message if we don't have the privs we need. Using converge_by and shell_out to set the timezone so we get a nice clean converge messaging vs. execute resources. Also improves the description to give a link to where users can find all the TZ options.
> Backport: Add macOS support to the timezone resource

- omnibus/package-scripts/angrychef/postrm
- omnibus/package-scripts/chef-fips/postrm
- omnibus/package-scripts/chef/postrm
- spec/support/platform_helpers.rb
Fix SLES 15 to not remove symlinks in the upgrade scripts and fix testing
> Backport: Fix SLES 15 upgrades removing the symlinks

- lib/chef/provider/windows_task.rb
Signed-off-by: Nimesh <nimesh.patni@msystechnologies.com>
> Backport: Handle `interactive_enabled` property in windows_task resource

- lib/chef/resource/dmg_package.rb
A large number of fixes to the dmg_package resource including a fix for EULA acceptance not working.
> Backport: Multiple fixes to dmg_package including functional EULA acceptance

- lib/chef/application/apply.rb
> Backport: Fix chef-apply crash for reboot

- chef-config/lib/chef-config/path_helper.rb
- lib/chef/client.rb
- lib/chef/provider/script.rb
> Backport: Update script resource deprecation warning

- appveyor.yml
> Break out appveyor

- Gemfile.lock
- omnibus/Gemfile.lock
> Update win32-taskscheduler to 2.0.1

- ci/verify-chef.sh
> Add some additonal RPM db cleanup steps missed in #7845

- lib/chef/knife/status.rb
We've been telling people this was going away in Chef 15
> Remove deprecated knife status --hide-healthy flag

- lib/chef/provider/windows_task.rb
- lib/chef/resource/windows_task.rb
- spec/functional/resource/windows_task_spec.rb
> Backport: Added `description` property on windows_task resource

- chef-config/lib/chef-config/config.rb
The plan outlined in https://github.com/chef/chef/pull/7006 was to set this to true in Chef 15.
> Set http_disable_auth_on_redirect to true

- lib/chef/resource/powershell_package.rb
Signed-off-by: Tor Magnus Rakvåg <tor.magnus@outlook.com>
Docs update to powershell_package. Replaces reference to `Register-PackageSource` with `powershell_package_source`.
> powershell_package doc update

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/BUG_TEMPLATE.md
- .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST_TEMPLATE.md
- .github/ISSUE_TEMPLATE/RESOURCE_REQUEST.md
- .github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
This way when you click new you get a choice between the three.
> Add additional github issue templates

- lib/chef/knife/config_list_profiles.rb
- lib/chef/knife/list.rb
- lib/chef/knife/raw.rb
- lib/chef/knife/role_env_run_list_clear.rb
- lib/chef/knife/role_env_run_list_remove.rb
- lib/chef/knife/role_env_run_list_replace.rb
- lib/chef/knife/role_env_run_list_set.rb
- lib/chef/knife/role_run_list_clear.rb
- lib/chef/knife/role_run_list_remove.rb
- lib/chef/knife/role_run_list_replace.rb
- lib/chef/knife/role_run_list_set.rb
- lib/chef/knife/show.rb
- lib/chef/knife/upload.rb
- lib/chef/knife/xargs.rb
Add (options) everywhere you can pass in options.
> Make knife command banners consistent

- lib/chef/resource/apt_update.rb
- lib/chef/resource/build_essential.rb
- lib/chef/resource/cab_package.rb
- lib/chef/resource/chef_gem.rb
- lib/chef/resource/cookbook_file.rb
- lib/chef/resource/cron_d.rb
- lib/chef/resource/dmg_package.rb
- lib/chef/resource/execute.rb
- lib/chef/resource/file.rb
- lib/chef/resource/hostname.rb
- lib/chef/resource/locale.rb
- lib/chef/resource/mdadm.rb
- lib/chef/resource/mount.rb
- lib/chef/resource/powershell_package.rb
- lib/chef/resource/remote_directory.rb
- lib/chef/resource/sudo.rb
- lib/chef/resource/swap_file.rb
- lib/chef/resource/sysctl.rb
- lib/chef/resource/systemd_unit.rb
- lib/chef/resource/windows_ad_join.rb
- lib/chef/resource/windows_printer.rb
- lib/chef/resource/windows_printer_port.rb
- lib/chef/resource/windows_workgroup.rb
- lib/chef/resource/zypper_repository.rb
Improve resource documentation when using the chef-resource-inspector.
> Backport: Add default_descriptions to properties

- lib/chef/knife/config_list_profiles.rb
- lib/chef/knife/list.rb
- lib/chef/knife/raw.rb
- lib/chef/knife/role_env_run_list_clear.rb
- lib/chef/knife/role_env_run_list_remove.rb
- lib/chef/knife/role_env_run_list_replace.rb
- lib/chef/knife/role_env_run_list_set.rb
- lib/chef/knife/role_run_list_clear.rb
- lib/chef/knife/role_run_list_remove.rb
- lib/chef/knife/role_run_list_replace.rb
- lib/chef/knife/role_run_list_set.rb
- lib/chef/knife/show.rb
- lib/chef/knife/upload.rb
- lib/chef/knife/xargs.rb
Add (options) everywhere you can pass in options.
> Backport: Make knife command banners consistent

- RELEASE_NOTES.md
This is a *very* rough draft of the notes we'll ship in April. I wanted
to get what we've done so far written down so we don't have to dig
through 4 months of git history later on.
> Document our breaking changes in Chef 15

- lib/chef/resource/windows_firewall_rule.rb
- spec/unit/resource/windows_firewall_rule_spec.rb
> Backport: Allow multiple local and remote ports in the windows_firewall_rule resource

- lib/chef/node/attribute.rb
no idea how this ever passed chefstyle, but the multi-line array loop was confusing everything
> fix whitespace in node attributes [ci skip]

- RELEASE_NOTES.md
> Add Chef 14.7 release notes

- chef-config/lib/chef-config/config.rb
- lib/chef/policy_builder/dynamic.rb
- spec/unit/policy_builder/dynamic_spec.rb
Remove the config to turn it off
> Always run policy_file if a policy_file or policy_group exists

- CODE_OF_CONDUCT.md
This will be displayed on GitHub now
> Add a link to our code of conduct page

- .expeditor/update_dep.sh
> Make sure to open PRs against the chef-14 branch

- lib/chef/resource/cron.rb
- lib/chef/resource/cron_d.rb
- lib/chef/resource/dmg_package.rb
- lib/chef/resource/execute.rb
- lib/chef/resource/hostname.rb
- lib/chef/resource/scm.rb
- lib/chef/resource/swap_file.rb
- lib/chef/resource/sysctl.rb
- lib/chef/resource/systemd_unit.rb
- lib/chef/resource/template.rb
- lib/chef/resource/windows_auto_run.rb
- lib/chef/resource/windows_feature.rb
- lib/chef/resource/windows_feature_powershell.rb
> Add additional resource description fields

- .expeditor/update_dep.sh
The into part was working, but we were trying to open the PR from
master, which obviously doesn't work.
> Make sure we open PRs from chef-14 and into chef-14

- lib/chef/resource/remote_directory.rb
- spec/unit/resource/remote_directory_spec.rb
Also add descriptions, default_descriptions, and expand the tests a bit.
> Fully convert remote_directory to use properties

- lib/chef/resource/macosx_service.rb
- lib/chef/resource/service.rb
- lib/chef/resource/windows_service.rb
- spec/unit/resource/macosx_service.rb
- spec/unit/resource/service_spec.rb
- spec/unit/resource/windows_service_spec.rb
Also expand the testing a bit while I'm here.
> Convert service resource to use properties

- RELEASE_NOTES.md
Signed-off-by: Mary Jinglewski <mjinglewski@chef.io>
Clarifying language from release notes in https://github.com/chef/chef/pull/7953
> Edits to Release Notes

- omnibus/package-scripts/angrychef/preinst
- omnibus/package-scripts/chef-fips/preinst
- omnibus/package-scripts/chef/preinst
> need -rf to remove dirs

- lib/chef/resource/apt_package.rb
- lib/chef/resource/apt_preference.rb
- lib/chef/resource/apt_repository.rb
- lib/chef/resource/chocolatey_config.rb
- lib/chef/resource/chocolatey_source.rb
- lib/chef/resource/cron.rb
- lib/chef/resource/cron_access.rb
- lib/chef/resource/cron_d.rb
- lib/chef/resource/dmg_package.rb
- lib/chef/resource/execute.rb
- lib/chef/resource/homebrew_cask.rb
- lib/chef/resource/homebrew_tap.rb
- lib/chef/resource/hostname.rb
- lib/chef/resource/kernel_module.rb
- lib/chef/resource/link.rb
- lib/chef/resource/ohai_hint.rb
- lib/chef/resource/package.rb
- lib/chef/resource/scm.rb
- lib/chef/resource/swap_file.rb
- lib/chef/resource/sysctl.rb
- lib/chef/resource/systemd_unit.rb
- lib/chef/resource/template.rb
- lib/chef/resource/windows_auto_run.rb
- lib/chef/resource/windows_feature.rb
- lib/chef/resource/windows_feature_powershell.rb
Add additional description fields and improve the copy of the existing descriptions.
> Chef 14: Improve resource descriptions

- lib/chef/resource/windows_feature_dism.rb
> Chef 14: removed features are also available for installation in windows_feature_dism

- Gemfile.lock
- omnibus/Gemfile.lock
> Update inspec to 3.0.52

- Gemfile.lock
- lib/chef/mixin/which.rb
- omnibus/Gemfile.lock
It uses path_to which is in chef_class
> Make sure which mixin requires chef_class

- lib/chef/provider/package/cab.rb
- spec/functional/resource/msu_package_spec.rb
> cab_package: Fail if the cab does not apply to the current windows image

- lib/chef/provider/package/apt.rb
- spec/unit/provider/package/apt_spec.rb
> apt_package: Support downgrades for apt packages

- RELEASE_NOTES.md
this is certainly worth documenting.
> add a RELEASE_NOTE on /opt/chef wiping

- RELEASE_NOTES.md
This gets down what we have so far.
> Add initial Chef 14.8 release notes

- RELEASE_NOTES.md
Add 2 more breaking changes for Chef 15.
> Add new items from the Ohai release notes

- lib/chef/provider/package/yum/python_helper.rb
> RHEL8 yum_package fix.

- lib/chef/provider/package/dnf/python_helper.rb
Backport from master
Signed-off-by: pixdrift <support@pixeldrift.net>
> dnf_package: Add RHEL 8 support

- omnibus_overrides.rb
> Fix locking ohai to to the value in the Gemfile.lock

- Gemfile.lock
- omnibus/Gemfile.lock
> Update InSpec to 3.0.61 and Ohai to 15.0.20

- lib/chef/resource/powershell_package_source.rb
- spec/unit/resource/powershell_package_source_spec.rb
Supresses warnings which pollute the state fetching script and resolves the name/source_name idempotency issue
https://github.com/chef/chef/issues/7628
https://github.com/chef/chef/issues/7883
> Bugfixes to powershell_package_source

- omnibus/package-scripts/angrychef/preinst
- omnibus/package-scripts/chef-fips/preinst
- omnibus/package-scripts/chef/preinst
I think this works, its somewhat difficult to test, I couldn't find the magic that creates the EBUSY errors.
It certainly doesn't error out on me, we'll have to see if it fixes travis
> fix EBUSY errors in preinst script

- lib/chef/resource/windows_ad_join.rb
Suppresses stderr when sensitive is true.
https://github.com/chef/chef/issues/8053
> windows_ad_join: suppress sensitive stderr

- .travis.yml
- lib/chef/resource/powershell_package_source.rb
- spec/unit/resource/powershell_package_source_spec.rb
Cherry-picked from 23d806d (#8025) and includes the apt-get proxy fix from (#8040)
> Backport: Bugfixes to powershell_package_source

- lib/chef/provider/group/windows.rb
- lib/chef/resource/group.rb
- lib/chef/util/windows/net_group.rb
- lib/chef/win32/api/net.rb
- lib/chef/win32/net.rb
- spec/unit/provider/group/windows_spec.rb
- spec/unit/resource/group_spec.rb
Cherry pick of 4dfc7f4 (#8038)
> Backport: Allow setting the comment on a Windows group

- lib/chef/resource/windows_ad_join.rb
Backport of #8054 to chef-14 branch
> Backport: windows_ad_join: suppress sensitive stderr

- Gemfile.lock
- omnibus/Gemfile.lock
This slims down a few of our deps
> Bump multiple deps to the latest

- MAINTAINERS.md
I have decided to hang up my Chef coat and promote @onlyhavecans up to Lieutenant of the FreeBSD Client team.
None
> Remove myself as maintainer and promote Amy as FreeBSD Lieutenant

- .expeditor/config.yml
> Update expeditor config for the new labels

- .expeditor/update_dep.sh
Pulls in the logic that tyler wrote in DK that performs retries and
validates that the gem was actually updated. This preventts empty PRs
from being opened and shortens the time the job takes to run.
> Chef 14: Pull in the gem update retry logic from DK

- chef-config/lib/chef-config/config.rb
Adding it as I read through the classes.
> Add a bit more yard to chef-config/config

- omnibus/Gemfile.lock
This fixes license enforcement errors
> Update license scout 1.0.21

- lib/chef/resource/homebrew_cask.rb
- lib/chef/resource/homebrew_tap.rb
If the name properties for these resources we used we'd entirely ignore them.
> homebrew_cask / homebrew_tap:  Properly use the cask_name and tap_name properties

- kitchen-tests/cookbooks/end_to_end/recipes/tests.rb
- kitchen-tests/kitchen.yml
- lib/chef/resource/sysctl.rb
This backports #8136 to Chef 14
> systctl: Allow slashes in key or block name

- lib/chef/knife/cookbook_site_download.rb
- lib/chef/knife/cookbook_site_install.rb
- lib/chef/knife/cookbook_site_list.rb
- lib/chef/knife/cookbook_site_search.rb
- lib/chef/knife/cookbook_site_share.rb
- lib/chef/knife/cookbook_site_show.rb
- lib/chef/knife/cookbook_site_unshare.rb
We'll want to backport this to Chef 14 as well.
> Add a deprecation warning to knife cookbook site

- Gemfile.lock
- omnibus/Gemfile.lock
Brings in Chef 14.9 in omnibus and a bunch of misc deps that have changed in the last month or so.
> Bump misc deps the latest

- RELEASE_NOTES.md
> Add release notes for 14.9

- omnibus_overrides.rb
This includes a large number of bugfixes and improvements over 1.8.5.
> Update nokogiri to 1.10.1

- lib/chef/formatters/indentable_output_stream.rb
- lib/chef/knife/core/bootstrap_context.rb
- lib/chef/knife/core/generic_presenter.rb
- lib/chef/knife/core/node_presenter.rb
- lib/chef/knife/core/status_presenter.rb
- lib/chef/knife/core/ui.rb
Some YARD fixes as I was reading through knife bits.
> Misc YARD updates for knife

- Gemfile.lock
- omnibus/Gemfile.lock
Bring in the new omnibus and omnibus-software as well as the updated addressable.
> Bump all deps to current

- lib/chef/provider/apt_repository.rb
> apt_repository: Don't create gpg temporary files owned by root in the running user's home directory

- .travis.yml
- omnibus_overrides.rb
- spec/unit/knife/bootstrap_spec.rb
Bump Chef 15 to the latest and greatest rubygems.
> Update Rubygems to 3.0.2

- Gemfile.lock
- lib/chef/provider/git.rb
- omnibus/Gemfile.lock
Backports #8179 and also updates win32_certstore so it will import private keys.
> Backport git resource fix in #8179 and update win32-certstore

- RELEASE_NOTES.md
> Add 14.10 release notes

- Gemfile.lock
- RELEASE_NOTES.md
> Bump InSpec to 3.4.1

- lib/chef/resource/windows_uac.rb
- lib/chef/resources.rb
- spec/unit/resource/windows_uac_spec.rb
This comes from the windows_uac cookbook.
https://supermarket.chef.io/cookbooks/windows_uac
> Add windows_uac resource

- lib/chef/resource/dmg_package.rb
- lib/chef/resource/sudo.rb
- lib/chef/resource/swap_file.rb
- lib/chef/resource/sysctl.rb
- lib/chef/resource/timezone.rb
- lib/chef/resource/windows_ad_join.rb
- lib/chef/resource/windows_auto_run.rb
- lib/chef/resource/windows_certificate.rb
- lib/chef/resource/windows_dfs_folder.rb
- lib/chef/resource/windows_dfs_namespace.rb
- lib/chef/resource/windows_dns_record.rb
- lib/chef/resource/windows_dns_zone.rb
- lib/chef/resource/windows_env.rb
- lib/chef/resource/windows_feature.rb
- lib/chef/resource/windows_feature_dism.rb
- lib/chef/resource/windows_feature_powershell.rb
- lib/chef/resource/windows_firewall_rule.rb
- lib/chef/resource/windows_font.rb
- lib/chef/resource/windows_pagefile.rb
- lib/chef/resource/windows_path.rb
- lib/chef/resource/windows_printer.rb
- lib/chef/resource/windows_share.rb
- lib/chef/resource/windows_shortcut.rb
- lib/chef/resource/windows_task.rb
- lib/chef/resource/windows_workgroup.rb
- lib/chef/resource/yum_repository.rb
- lib/chef/resource/zypper_repository.rb
This better describes how a name property works.
> More consist descriptions for resource name properties

- Gemfile
- Gemfile.lock
- omnibus/Gemfile.lock
> Chef-14: add ed25519 gemset and update omnibus-software

- .expeditor/update_dep.sh
- .expeditor/update_dockerfile.sh
Use the new prefixed environment variables.
> Update scripts to use new EXPEDITOR_ environment variables

- .expeditor/update_dep.sh
This allows us to easily re-use this script as is on other release branches of this repository. 
> Open the PR against the appropriate release branch

- lib/chef/dsl/universal.rb
> Chef-14: add lazy module include to universal DSL

- lib/chef/dsl/universal.rb
> Chef-13: add lazy module include to universal DSL

- lib/chef/resource/windows_share.rb
> windows_share: Improve path comparison to prevent convering on each run

- lib/chef/provider/package/chocolatey.rb
- spec/unit/provider/package/chocolatey_spec.rb
> ﻿﻿chocolatey_package: use provided options when determing available options to allow using private sources

- lib/chef/resource/openssl_dhparam.rb
- spec/unit/resource/openssl_dhparam.rb
> openssl_dhparam: allow changing file mode on subsequent runs

- RELEASE_NOTES.md
- omnibus_overrides.rb
There may be more to add here, but this is 90% complete at least.
> Update Rubygems to 2.7.9 + Add release notes for Chef 14.11

- omnibus_overrides.rb
This resolves several CVEs as well as a few bugs.
> Update rubygems to 3.0.3

- spec/unit/provider/service/windows_spec.rb
Refactoring the `windows_service` provider tests.
N/A
> Refactor windows_service unit tests

- .travis.yml
These don't do anything at this point.
> Nuke the old sudo configs from .travis.yml

- lib/chef/knife/bootstrap.rb
- lib/chef/provider.rb
- lib/chef/resource/build_essential.rb
- lib/chef/resource/chef_gem.rb
- lib/chef/resource/chef_handler.rb
- lib/chef/resource/execute.rb
- lib/chef/resource/homebrew_cask.rb
- lib/chef/resource/homebrew_tap.rb
- lib/chef/resource/hostname.rb
- lib/chef/resource/link.rb
- lib/chef/resource/ohai_hint.rb
A pile of misc yard I added as I was reading things.
> Add misc YARD comments

- Gemfile.lock
> fix unsolvable Gemfile.lock

- lib/chef/provider/service/windows.rb
- spec/unit/provider/service/windows_spec.rb
Backport fix for #8080 to Chef 14.
- #8080
> Backport fix for #8080

- Gemfile.lock
- omnibus/Gemfile.lock
This should resolve build issues on Solaris
> Update inspec to 3.9.0

- omnibus_overrides.rb
> Update nokogiri to 1.10.2

- omnibus/omnibus-test.ps1
- omnibus/omnibus-test.sh
> Add PROJECT_NAME to omnibus-test scripts

- lib/chef/mixin/properties.rb
- spec/unit/property_spec.rb
Kept in the properties mixin since it is tightly coupled.
closes #7046
> Implement Chef::Resource#copy_properties_from

- spec/functional/resource/dsc_script_spec.rb
- spec/functional/resource/group_spec.rb
> Backport two test fixes/changes to chef-14

- .expeditor/config.yml
- .expeditor/verify.pipeline.yml
- scripts/bk_tests/bk_install.sh
Add verification tests to Buildkite public pipeline
Speeds up verification testing
> Add Verification tests in Buildkite

- lib/chef/application/solo.rb
> Drop privileges before creating files in solo mode

- .expeditor/verify.pipeline.yml
- kitchen-tests/Gemfile
- kitchen-tests/kitchen.bk.yml
- scripts/bk_tests/bk_install.sh
StackOverflow discussions that are relevant]
> Add more verification tests

- lib/chef/knife/data_bag_edit.rb
- spec/integration/knife/data_bag_create_spec.rb
- spec/integration/knife/data_bag_edit_spec.rb
- spec/integration/knife/data_bag_show_spec.rb
- spec/unit/knife/data_bag_edit_spec.rb
> Backport #8077 to Chef 14

- README.md
This change will trigger an expeditor version bump and release to current.
> Triggering expeditor version bump

- lib/chef/resource/snap_package.rb
Our docs site is generated with this field.
> Add the introduced field to snap_package

- .expeditor/config.yml
we decided to ship this to rubygems.
> missing gem publish.

- lib/chef/resource/archive_file.rb
- lib/chef/resource/windows_dfs_namespace.rb
- lib/chef/resource/windows_dns_zone.rb
The docs team performed copy editing on these on the docs site. This
backports those changes.
> Update property descriptions for new resources

- omnibus/Gemfile.lock
pull in the fixes to appbundling chef+chef-bin
> bump omnibus-software

- Gemfile.lock
- omnibus/Gemfile.lock
Update lock files to pull latest gems
Update lock files to pull latest gems
> Update InSpec to 4.3.2

- lib/chef/data_collector.rb
- lib/chef/formatters/error_inspectors/api_error_formatting.rb
- lib/chef/formatters/error_inspectors/registration_error_inspector.rb
- lib/chef/formatters/error_inspectors/run_list_expansion_error_inspector.rb
- lib/chef/knife/core/windows_bootstrap_context.rb
Update Chef Client and Chef Server brand names to current.
> Update more brand names to current

- lib/chef/chef_fs/command_line.rb
> Resolve exceptions when running knife diff

- lib/chef/provider/cron.rb
- spec/unit/provider/cron_spec.rb
> Fix for cron resource get confused by environment/property mismatch

- lib/chef/knife/bootstrap/train_connector.rb
Windows Powershell command to create temp dir has a minor bug.
https://github.com/chef/chef/issues/8475
> Chef 15: Unable to create temp dir on windows system

- Rakefile
chefstyle is failing in master right now
> quote fix for chefstyle

- spec/unit/knife/bootstrap_spec.rb
> Remove purposefully failing test - no longer want to gate releases

- lib/chef/knife.rb
- lib/chef/knife/config_list_profiles.rb
- lib/chef/shell.rb
Most of the knife.rb mentions have been updated and the docs have been updated already. Mention both since every existing user is only familiar with knfie.rb.
> Update a few more knife.rb references to include config.rb

- omnibus/package-scripts/angrychef/postinst
- omnibus/package-scripts/chef-fips/postinst
- omnibus/package-scripts/chef/postinst
Point brand new users in the right direction.
> Point people to Learn Chef in the post install message

- lib/chef/resource/windows_feature_powershell.rb
- Fixed minor bug
Fixes: 
https://getchef.zendesk.com/agent/tickets/22056
https://chefio.atlassian.net/browse/MSYS-1006
> windows_feature: Fix failures on windows 2008r2

- .travis.yml
- RELEASE_NOTES.md
- appveyor.yml
- kitchen-tests/cookbooks/rspec/templates/run-chef-rspec
- spec/unit/knife/core/windows_bootstrap_context_spec.rb
Some shells interpret the '-' character in 'accept-no-persist'
N/A
> CHEF_LICENSE environment variables should be quoted

- lib/chef/knife/bootstrap.rb
- In order to fix Parse `--max-wait` options string to an integer.
- It would be good it we can provide the fixes on https://github.com/inspec/train side as well at location https://github.com/inspec/train/blob/ec41c1f1e6f38f6ab1c335955651064eaeb7028f/lib/train/transports/ssh_connection.rb#L138 or https://github.com/inspec/train/blob/ec41c1f1e6f38f6ab1c335955651064eaeb7028f/lib/train/transports/ssh_connection.rb#L44
https://github.com/chef/chef/issues/8488
> Chef 15: bootstrap options --max-wait raises NoMethodError: undefined method /

- Dockerfile
Help outsiders understand how we push things up.
> Add comments to the Dockerfile explaining how it all works

- lib/chef/chef_fs/file_system/repository/chef_repository_file_system_root_dir.rb
- lib/chef/chef_fs/file_system/repository/nodes_dir.rb
- lib/chef/dsl/declare_resource.rb
- lib/chef/local_mode.rb
- lib/chef/log.rb
- lib/chef/mixin/user_context.rb
- lib/chef/mixin/windows_architecture_helper.rb
- lib/chef/mixin/windows_env_helper.rb
- lib/chef/provider/package/windows/msi.rb
- lib/chef/provider/script.rb
- lib/chef/provider/user/windows.rb
- lib/chef/provider/windows_path.rb
- lib/chef/resource/cron.rb
- lib/chef/resource/lwrp_base.rb
- lib/chef/resource/windows_package.rb
- lib/chef/resource/windows_task.rb
- lib/chef/util/powershell/ps_credential.rb
- lib/chef/util/windows/logon_session.rb
> Change some more require to require_relative

- lib/chef/knife/bootstrap.rb
- Replace `connection_protocol == "winrm"` check with existing `winrm?` method. 
> Chef 15: Minor winrm check code refactor

- ext/win32-eventlog/chef-log.man
- omnibus/config/projects/chef.rb
- omnibus/resources/chef/msi/localization-en-us.wxl.erb
Make sure we're Chef Infra Client where the user sees it.
> Update to Chef Infra Client in Add/Remove Programs & Event Log

- RELEASE_NOTES.md
Signed-off-by: Mary Jinglewski <mjinglewski@chef.io>
> Chef Infra Client 15 Release Notes copyedits

- Gemfile.lock
Bump license-acceptance to 1.0.11 to resolve failures on Windows 2016
#8548
> Bump license-acceptance to 1.0.11 to resolve failures on Windows 2016

- lib/chef/knife/bootstrap.rb
- spec/unit/knife/bootstrap_spec.rb
This includes a few fixes:
1. properly handle the default value for session_timeout in cases where
merge_config is not called (plugins) to populate defaults.
2. verify that we're using the ssh protoocl before referencing ssh
constants.
3. capture and compare the higher-level Train::Error for the check
to see if we've gotten a missing fingerprint error, instead of using
Train::Transports::SSHFailed which may not be loaded when exception
is being evaluated.
4. Add tests for missing fingerprint behavior
5. do not save session_timeout to Chef::Config[:knife], it was not
referenced as knife config in any location and we're trying to move away
from pushing CLI values into knife config.
6. Map ca_trust_file to ca_trust_path on the train side. Train was incorrectly accepting and passing along …
> Multiple Bootstrap bug fixes

- RELEASE_NOTES.md
Signed-off-by: Mary Jinglewski <mjinglewski@chef.io>
> Chef Infra Client 15 Release Notes Additional edits

- .expeditor/config.yml
- .expeditor/verify.pipeline.yml
- .travis.yml
- kitchen-tests/kitchen.travis.yml
- kitchen-tests/kitchen.yml
- scripts/bk_tests/bk_install.sh
> Add BK public verify pipeline

- .travis.yml
- kitchen-tests/Gemfile
- kitchen-tests/README.md
- kitchen-tests/kitchen.travis.yml
- kitchen-tests/kitchen.yml
- lib/chef/win32/security.rb
- spec/unit/win32/security_spec.rb
> Chef 14: Fix for Chef::Exceptions::Win32APIError: The operation completed successfully

- RELEASE_NOTES.md
Somehow I nuked all @mjingle's edits. 🤷‍♂
> Add back release note edits that were accidently deleted

- .expeditor/config.yml
- .expeditor/update_version.sh
> Add chef-14 update_version script

- lib/chef/provider/service/insserv.rb
- spec/functional/assets/inittest
- spec/functional/resource/insserv_spec.rb
- spec/spec_helper.rb
- spec/support/platform_helpers.rb
- spec/unit/provider/service/insserv_service_spec.rb
* fix service enable idempotency in sles11
Backport of #8256
> Fix service enable idempotency in sles11 (#8256)

- lib/chef/chef_fs/knife.rb
- lib/chef/knife.rb
- lib/chef/knife/cookbook_site_download.rb
- lib/chef/knife/cookbook_site_install.rb
- lib/chef/knife/cookbook_site_list.rb
- lib/chef/knife/cookbook_site_search.rb
- lib/chef/knife/cookbook_site_share.rb
- lib/chef/knife/cookbook_site_show.rb
- lib/chef/knife/cookbook_site_unshare.rb
This fixes the issue of inheritance of option with knife plugins as discussed in issue #8583
Fixes #8583
> Fix for knife bootstrap inheritance issue with knife plugins

- lib/chef/resource/launchd.rb
> Add introduced field to launch_events in launchd

- lib/chef/resource_collection.rb
- spec/unit/resource_collection_spec.rb
with multiple providers
Fixes: https://github.com/chef/chef/issues/6158
Signed-off-by: Artem Sidorenko <artem.sidorenko@t-systems.com>
> Fix delete_resource for resources

- .expeditor/verify.pipeline.yml
- .travis.yml
- Gemfile
- Gemfile.lock
- appveyor.yml
Remove these deps from our gemfile.lock since we're not using them anymore.
>  Remove old maintainer gems from the Gemfile

- lib/chef/knife/core/status_presenter.rb
Signed-off-by: Vijay Mali <vijay.mali@msystechnologies.com>
> Fixed empty value for knife status long output

- lib/chef/chef_fs/command_line.rb
> fix knife diff exceptions

- lib/chef/knife.rb
- lib/chef/knife/bootstrap.rb
- spec/unit/knife_spec.rb
> 14: backport knife fixes

- RELEASE_NOTES.md
> Add 14.13 release notes

- lib/chef/knife/bootstrap.rb
- spec/unit/knife/bootstrap_spec.rb
- Handles "-x" that was used to set "winrm-user" and is now Deprecated.
- Fixes #8566 
> Chef-15: Added deprecation check for short arguments

- .expeditor/verify.pipeline.yml
- kitchen-tests/kitchen.yml
- scripts/bk_tests/bk_dokken_install.sh
- scripts/bk_tests/bk_install.sh
- scripts/bk_tests/bk_linux_exec.sh
- spec/functional/resource/ifconfig_spec.rb
> Enable more BK verification tests

- lib/chef/knife/bootstrap.rb
- lib/chef/knife/bootstrap/train_connector.rb
- lib/chef/knife/core/gem_glob_loader.rb
Chef has gotten quite loud with warnings. This quiets things back down a
bit.
> Avoid constant warnings

- RELEASE_NOTES.md
- docs/dev/design_documents/how_chef_is_tested_and_built.md
- docs/dev/how_to/releasing_chef_infra.md
> Document how to release Chef

- docs/dev/how_to/updating_chef12.md
Forgot some stuff from recent discussions.  Added a purpose line so its hopefully more clear what I'm trying to capture here.
> More upgrading from Chef 12 docs

- omnibus/omnibus-test.sh
This is a release engineering change only.
Make omnibus-test.sh use appropriate toolchain.
> Make omnibus-test.sh use appropriate toolchain

- RELEASE_NOTES.md
> Add Chef 14.12.9 release notes

- appveyor.yml
Specify retries and the number of jobs directly in the bundler command.
> Improve how we bundler install in appveyor

- lib/chef/resource/chocolatey_source.rb
This way we get the proper docs for Chef 15.1.
> Add introduced fields for chocolatey_source

- RELEASE_NOTES.md
Add the release notes for Chef 15.1
> Add Chef 15.1 release notes

- .expeditor/release.omnibus.yml
- omnibus/README.md
Deprecate Ubuntu-14
Deprecate Ubuntu-14
> Deprecate Ubuntu-14

- tasks/docs.rb
1) Fix the indentation
2) Avoid extra new lines
3) Show example data if we have it
4) Chef Infra Client vs. the Chef Infra Client
> Improve generation of docs site resource pages

- spec/functional/resource/ifconfig_spec.rb
- spec/functional/resource/mount_spec.rb
- spec/spec_helper.rb
We're running this all in buildkite w/o issues.
> Remove rspec config for Travis

- omnibus/Gemfile.lock
https://github.com/chef/omnibus-software/pull/1076
> Pull in latest omnibus-software to fix Windows builds

- .travis.yml
Remove some leftovers from rspec testing
Remove the notifications
Use Ruby 2.6 not 2.5 for our kitchen tests
> Cleanup the Travis config

- .expeditor/verify.pipeline.yml
Let's further verify our changes before merging.
> Add rspec testing on Fedora in Buildkite

- Gemfile.lock
- omnibus/Gemfile.lock
> Bump InSpec, Ohai, and appbundler to the latest

- omnibus/omnibus-test.sh
Cloud testers have  as many as 10 zypper repos configured and enabled, so the zypper searches from specs take longer to run on our testers as too many repos with most of them enabled were slowing down the zypper process, locking it during the test runs and failing the zypper package functional tests.  Since we do not use these repos in our testing we delete them.
Resolves failing zypper package test on our infra testers
> Fix zypper test failures

- .expeditor/verify.pipeline.yml
> Enable Kitchen dockken tests with BK linux executor

- lib/chef/provider/package/zypper.rb
- spec/unit/provider/package/zypper_spec.rb
> Chef-14: fix zypper_package upgrade provider and unit tests to verify

- lib/chef/knife/core/generic_presenter.rb
- lib/chef/knife/node_environment_set.rb
- spec/unit/knife/node_environment_set_spec.rb
-  Correctly show the output of command `knife node environment set NODE ENVIRONMENT`  
-  According to issue it was not showing correctly despite being set properly and could be seen in `knife node show` output
Fixes https://github.com/chef/chef/issues/8453
```
PS E:\Backup\Project\Chef_Repo\chef> knife node environment set dh-ubu-14 development_environment -c 'E:\Backup\Project\chef-starter\chef-repo\.chef\knife.rb'
dh-ubu-14:
chef_environment: _default
PS E:\Backup\Project\Chef_Repo\chef> knife node show dh-ubu-14 -c 'E:\Backup\Project\chef-starter\chef-repo\.chef\knife.rb'
Node Name:   dh-ubu-14
Environment: development_environment
FQDN:        ip-172-31-22-126.us-west-2.compute.internal
IP:          34.219.31.214
Run …
```
> fix knife node environment set output

- .expeditor/verify.pipeline.yml
We keep seeing random failures on our PRs.  This resolves that.
> Add retries to the GitHub PRs in Buildkite

- RELEASE_NOTES.md
> Add Chef Infra Client 15.2 release notes

- README.md
Don't link to a boneyard repo anymore
> Update the link to our release cadence information

- omnibus/config/projects/chef.rb
> Begin signing MSI's with renewed Windows Signing Cert

- omnibus/Gemfile.lock
Pull in the latest omnibus and omnibus-software updates.
> Update omnibus build deps to the latest

- .expeditor/release.omnibus.yml
> Add AIX 7.2 platform

- chef-config/lib/chef-config/config.rb
- lib/chef/exceptions.rb
- lib/chef/provider.rb
- lib/chef/resource.rb
- lib/chef/resource/resource_notification.rb
- lib/chef/resource_collection.rb
- lib/chef/run_context.rb
- lib/chef/runner.rb
- spec/integration/recipes/unified_mode_spec.rb
backport of #8668
this will make it easier to start using unified mode in community cookbooks without cutting off large numbers of users.
> unified mode backport to Chef-14

- .expeditor/release.omnibus.yml
> Deprecate macOS 10.12 and add macOS 10.15 support

- chef-config/lib/chef-config/config.rb
> Remove duplicate policy_path config

- RELEASE_NOTES.md
Add release notes for our upcoming release.
> Add Chef 15.3 release notes

- CHANGELOG.md
> Fix simple typo: acceptannce -> acceptance

- lib/chef/provider/user/mac.rb
- lib/chef/resource/user/dscl_user.rb
- lib/chef/resource/user/mac_user.rb
- spec/functional/resource/user/mac_user_spec.rb
https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/120#ed3f7f98-4aa1-4c08-bed5-6407df1467a4
> [macos] fix mac_user platform constraints

- RELEASE_NOTES.md
> Add release notes for new user changes in 15.3

- lib/chef/application/solo.rb
Can't do this, regression in #8386
closes #8386
> Revert "Drop privileges before creating files in solo mode"

- lib/chef/resource/apt_repository.rb
- lib/chef/resource/apt_update.rb
- lib/chef/resource/archive_file.rb
- lib/chef/resource/build_essential.rb
- lib/chef/resource/chocolatey_config.rb
- lib/chef/resource/chocolatey_feature.rb
- lib/chef/resource/chocolatey_package.rb
- lib/chef/resource/chocolatey_source.rb
- lib/chef/resource/cron_access.rb
- lib/chef/resource/cron_d.rb
- lib/chef/resource/dmg_package.rb
- tasks/docs.rb
I'm also adding these same examples to the docs.
> Add more resource examples to the codebase

- lib/chef/provider/package/dnf/dnf_helper.py
- lib/chef/resource/dnf_package.rb
- spec/functional/resource/dnf_package_spec.rb
- spec/spec_helper.rb
- spec/support/platform_helpers.rb
> dnf_package fixes for RHEL8 backport to chef-14

- lib/chef/provider.rb
- spec/integration/recipes/resource_converge_if_changed_spec.rb
Fixes #6300.
This may be a breaking change.
> fix converge_if_changed to compare default values

- lib/chef/node/attribute.rb
- lib/chef/node/attribute_collections.rb
- lib/chef/node/immutable_collections.rb
- lib/chef/node/mixin/immutablize_array.rb
- lib/chef/node/mixin/immutablize_hash.rb
- spec/unit/node/attribute_spec.rb
- spec/unit/node/immutable_collections_spec.rb
 - Psych module to_yaml not working as expected for ImmutableMash & ImmutableArray.
 - So parse first to Hash/Array then convert it to YAML formatted string.
eg.
1. If hash is assgined to node attribute it is returning ImmutableMash
```
> node.default['test'] = {'bar' => ['baz'], 'bing' => 'boo'}
> node['test'].class # ImmutableMash
```
2. If Array is assigned to node attribute it is returning ImmutableArray
```
> node.default['test'] = [{'bar' => ['baz']}, {'bing' => 'boo'}]
> node['test'].class # ImmutableArray
```
3. If any other value is assigned to node `to_yaml` working as expected.
https://github.com/chef/chef/issues/8820
> Add #to_yaml method for ImmutableMash & ImmutableArray

- .expeditor/verify.pipeline.yml
- scripts/bk_tests/bk_run_choco.ps1
- scripts/bk_tests/bk_win_functional.ps1
- scripts/bk_tests/bk_win_integration.ps1
- spec/integration/knife/chef_repo_path_spec.rb
- spec/spec_helper.rb
* Use default windows 2019 image
* Skip 8dot3name tests as default disabled on 2019
* Use windows privileged executor for functional tests
* Use windows docker image for chocolatey tests
> Fix Windows Integration and Functional tests for BK

- omnibus_overrides.rb
> Update nokogiri to 1.10.4 and openssl to 1.0.2t

- RELEASE_NOTES.md
> Add Chef 14.14 release notes

- spec/functional/util/powershell/cmdlet_spec.rb
> fixup some bad rspec to greenify master

- spec/functional/util/powershell/cmdlet_spec.rb
> fixup some bad rspec to greenify chef-14  branch

- lib/chef/knife/ssh.rb
> Fix knife ssh interactive mode exit error

- lib/chef/knife/cookbook_metadata_from_file.rb
- Added file in banner
backport https://github.com/chef/chef/pull/8812 from master
> Fix knife cookbook metadata from file command banner

- lib/chef/provider/windows_task.rb
- spec/unit/provider/windows_task_spec.rb
> windows_task: Fix for :day option is not accepting integer value

- RELEASE_NOTES.md
Adding release notes for 14.14.22 prior to promotion.
> Add release notes for 14.14.22

- .expeditor/config.yml
- .expeditor/habitat-test.pipeline.yml
> Create habitat test pipeline

- lib/chef/knife/bootstrap/templates/chef-full.erb
Wrapped up file creation and chmod into single command and using umask instead of chmod before creating the file.
#3872
> Using umask to avoid race conditions in bootstrap

- .bldr.toml
- .expeditor/build.habitat.yml
- .expeditor/config.yml
This PR  addresses the issues with habitat artifact creation described in #8966 
> Fix habitat build in expeditor config

- RELEASE_NOTES.md
> Add initial Chef 15.4 release notes

- lib/chef/knife.rb
https://github.com/chef/chef/blob/f6d445c28467b5ea5741d05aed2bd1f657c4a1dd/lib/chef/knife.rb#L237
- knife plugins list variable `vsphere`, `acl` , `opc`, `tidy` are missing.
- Add these as well and sorted the list.
https://github.com/chef/chef/issues/8898
> knife: Improve messaging for installing official plugins into DK / Workstationn

- lib/chef/knife/core/generic_presenter.rb
It seems while extracting the attribute from non-array object currently, it's trying to access using the `key?` method.
But it would be possible that the object itself does not respond to the `key?` method. So added `respond_to?` before access.
Before Fix: 
```
=> knife node show node1-centos -a sdfjkhdsafkadksfkdsa
node1-centos:
sdfjkhdsafkadksfkdsa: 
=> knife node show node1-centos -a os.sdfjkhdsafkadksfkdsa
ERROR: knife encountered an unexpected error
This may be a bug in the 'node show' knife command or plugin
Please collect the output of this command with the `-VVV` option before filing a bug report.
Exception: NoMethodError: undefined method `key?' for "linux":String
```
After Fix: 
```
=> knife node show node1-centos -a sdfjkhdsafkadksfkdsa
node1-centos:
sdfjkhdsafkadksfkdsa: 
=> …
```
> Fix knife node show non-existent attributes

- lib/chef/knife/cookbook_metadata_from_file.rb
- spec/unit/knife/cookbook_metadata_from_file_spec.rb
Add name args validation check and show the proper error message.
Fixes https://github.com/chef/chef/issues/9031
> Fix knife cookbook metadata from file name args

- omnibus/Gemfile.lock
Pull in fix https://github.com/chef/omnibus/pull/910
> Bump omnibus to 6.1.10

- lib/chef/data_collector.rb
- lib/chef/knife/configure.rb
- lib/chef/knife/core/status_presenter.rb
- lib/chef/node/attribute.rb
- lib/chef/provider/file.rb
- spec/unit/knife/status_spec.rb
- spec/unit/provider/package/openbsd_spec.rb
- spec/unit/provider/package/smartos_spec.rb
This update found a few things that should have been triggering before.
> Updates for Chefstyle with Rubocop 0.75.1

- lib/chef/provider/systemd_unit.rb
Backport of #9046
closes #9045
> systemd_unit needs to log (chef 14 backport)

- lib/chef/knife/config_get.rb
- spec/integration/knife/config_get_spec.rb
> [chef-14] backport #9049

- Gemfile.lock
- omnibus/Gemfile.lock
- omnibus_overrides.rb
> Update nokogiri, libxml2, and libxslt to latest

- RELEASE_NOTES.md
> Add 14.14.29 release notes

- habitat/plan.sh
i broke the builds (kind of expected really)
> missed adding chef-utils to hab plan here

- lib/chef/resource_reporter.rb
> Fix action collection nilclass error early in runs

- lib/chef/knife/list.rb
- spec/integration/knife/list_spec.rb
- Raised an error if no argument provided.
```
FATAL: You must specify at least one argument. If you want to list everything in this directory, run "knife list ."
```
- Added required specs.
Fixes https://github.com/chef/chef/issues/9052
> [knife list] Validate name argument & raise error if no args provided

- lib/chef/knife/list.rb
- spec/integration/knife/list_spec.rb
This reverts commit c29b8da2b0353bb5d6e499b5d7cc79c0fadab9b3.  It was causing failures in CI.
> Revert "Validate name argument for knife list"

- chef-utils/README.md
I'm going to use most of this for the release notes so I updated it to
match the experience level we generally assume in those release notes.
> Reorder the helper docs and expand platforms and descriptions

- RELEASE_NOTES.md
> Add Chef Infra Client 15.5. release notes

- docs/dev/README.md
> Remove bonus `.md` to fix link

- lib/chef/client.rb
Obvious bug.  Prioritizing fixing this for now over figuring out where to add testing.
> fix enforce_path_sanity being set to true

- RELEASE_NOTES.md
> Add 15.5.15 release notes

- omnibus/Gemfile.lock
> Bump Omnibus to the latest

- Gemfile
- Gemfile.lock
> Update ruby_prof to 1.0

- chef-config/lib/chef-config/config.rb
- chef-config/spec/unit/config_spec.rb
- Expand paths provided in `--config-option` setting to allow for relative paths
Fixes: #5842 #3890
> Fix for ChefConfig should expand relative paths

- lib/chef/provider/apt_repository.rb
- spec/unit/provider/apt_repository_spec.rb
As apt repository resource appended double/single quotes and this be problematic. also seems we are adding extra spaces.
Here some example of the apt source list
```
deb http://deb.debian.org/debian buster main
deb-src http://deb.debian.org/debian buster main
deb http://deb.debian.org/debian-security/ buster/updates main
deb-src http://deb.debian.org/debian-security/ buster/updates main
deb http://deb.debian.org/debian buster-updates main
deb-src http://deb.debian.org/debian buster-updates main
```
Fixes https://github.com/chef/chef/issues/6524
> Fix apt_repository uri single/double quotes and spaces

- lib/chef/guard_interpreter/default_guard_interpreter.rb
- lib/chef/provider/file.rb
- lib/chef/resource/file/verification.rb
- spec/spec_helper.rb
- spec/support/shared/unit/provider/file.rb
> Add output for the file provider verification

- RELEASE_NOTES.md
> Add Chef Infra Client 15.6 release notes

- omnibus/omnibus-test.ps1
- omnibus/omnibus-test.sh
> omnibus tests need to accept the license

- omnibus/omnibus-test.ps1
- omnibus/omnibus-test.sh
integration tests have license-acceptance issues that i wasn't able
to figure out last night
> try unit + functional tests

- omnibus/omnibus-test.sh
we seem to sadly have some tight coupling.
> run functional tests before units

- omnibus/Gemfile.lock
> Update all omnibus deps to the latest

- Gemfile.lock
- omnibus/Gemfile.lock
Pull in the latest omnibus to slim the build down further.
> Update all deps to the latest

- Gemfile.lock
- omnibus/Gemfile.lock
> Update libarchive to 1.0

- Gemfile.lock
- omnibus/Gemfile.lock
Runtime and omnibus to current
> Update all deps to current

- lib/chef/resource/sudo.rb
In commit https://github.com/chef/chef/pull/8928/commits/6e69823a8843008965de5b5171e0e0435a19cf1c we have verified the overall sudoers content but on 2nd converge seems that we are duplicating the file content which cases the issue.
So, if the file already exists split the verification command and verify the content.
Fixes https://github.com/chef/chef/issues/9001
> Fixes for sudo resource fails on 2nd converge when Cmnd_Alias is used

- .expeditor/config.yml
This has been added to the notes for next time
> Fix the project alias in expeditor

- Gemfile.lock
- omnibus/Gemfile.lock
> Update to Ohai 16.0.2

- docs/dev/how_to/building_and_installing.md
- docs/dev/how_to/bumping_minor_or_major_versions.md
- docs/dev/how_to/bumping_the_major_version.md
- docs/dev/how_to/releasing_chef_infra.md
We need to document this so that releng and others can perform the bump
in the future.
> Document the process for bumping the major version

- lib/chef/cookbook/cookbook_version_loader.rb
- lib/chef/cookbook_loader.rb
- lib/chef/cookbook_uploader.rb
- lib/chef/knife/cookbook_upload.rb
- spec/integration/knife/chef_fs_data_store_spec.rb
- spec/integration/knife/deps_spec.rb
- spec/integration/knife/upload_spec.rb
- spec/unit/cookbook/cookbook_version_loader_spec.rb
Backport of https://github.com/chef/chef/pull/9011
> Raises error if there is empty cookbook directory at the time of upload

- RELEASE_NOTES.md
> Add Chef 15.7 release notes

- lib/chef/cookbook/cookbook_version_loader.rb
- spec/integration/knife/chef_fs_data_store_spec.rb
- spec/integration/knife/deps_spec.rb
- spec/integration/knife/upload_spec.rb
- spec/unit/cookbook/cookbook_version_loader_spec.rb
When this shows up in logs it's impossible to figure out what actually
needs to be updated
> Provider a better error message in Chef::Cookbook::CookbookVersionLoader

- spec/integration/knife/chef_fs_data_store_spec.rb
- spec/integration/knife/deps_spec.rb
- spec/unit/cookbook/cookbook_version_loader_spec.rb
> Cleanup the specs for the load_cookbooks warnings

- lib/chef/cookbook/cookbook_version_loader.rb
- spec/unit/cookbook/cookbook_version_loader_spec.rb
use a proper deprecation instead of a warning and don't raise
in the load method.
> switch the load method back to not raising + deprecation

- .gitignore
add byebug command history file `.byebug_history` in `.gitignore`
> [minor] ignore byebug command history file

- lib/chef/cookbook/cookbook_version_loader.rb
- lib/chef/cookbook_uploader.rb
- spec/unit/cookbook/cookbook_version_loader_spec.rb
> Chef 15 backport of #9281 and #9274

- lib/chef/provider/ifconfig.rb
- spec/unit/provider/ifconfig_spec.rb
debian 10 version of net-tools switches its --version output to
stdout from stderr.
> debian 10 ifconfig fix

- .expeditor/verify.pipeline.yml
- Gemfile.lock
- omnibus_overrides.rb
- scripts/bk_tests/bk_run_choco.ps1
- scripts/bk_tests/bk_win_functional.ps1
- scripts/bk_tests/bk_win_integration.ps1
- scripts/bk_tests/bk_win_unit.ps1
Add ruby 2.7 testing
bumps to bundler 2.1.2 and rubygems 3.1.2 because ruby 2.7 comes with those
> Add ruby 2.7 expeditor testing

- .buildkite/hooks/pre-command
mostly copied from https://github.com/chef/automate/blob/master/.buildkite/hooks/pre-command
> add bk testing against merge commit

- chef-utils/README.md
- chef-utils/lib/chef-utils.rb
- chef-utils/lib/chef-utils/dsl/cloud.rb
- chef-utils/spec/spec_helper.rb
- chef-utils/spec/unit/dsl/cloud_spec.rb
Porting these straight over from chef-sugar
> Add cloud helpers from chef-sugar

- chef-utils/lib/chef-utils.rb
> chef-utils: add which/train_helpers/path_sanity to the DSL

- chef-config/lib/chef-config/config.rb
> Revert Dist value for chef-zero default org

- chef-utils/README.md
- chef-utils/lib/chef-utils.rb
- chef-utils/lib/chef-utils/dsl/cloud.rb
- chef-utils/spec/spec_helper.rb
- chef-utils/spec/unit/dsl/cloud_spec.rb
> Add chef-sugar cloud helpers to chef-utils

- chef-utils/README.md
- chef-utils/lib/chef-utils/dsl/introspection.rb
- chef-utils/spec/unit/dsl/introspection_spec.rb
> Add chef-sugar include_recipe? helper

- omnibus/Gemfile.lock
- omnibus/resources/chef/pkg/entitlements.plist
ffi loads c code into memory in an unsigned way and this allows workstation
to work with the hardened runtime.
Signed-off-by: Jon Morrow <jmorrow@chef.io>
https://github.com/chef/omnibus/pull/928
> Adding entitlement for unsigned memory execution

- RELEASE_NOTES.md
- lib/chef/resource/sysctl.rb
- spec/unit/resource/sysctl_spec.rb
Break the content generation out into its own method so we can test it.
> Add an introduced field to sysctl and expand testing

- lib/chef/resource/user/mac_user.rb
Make sure we expose this come docs
> Document the new hidden field in mac_user ships in 15.8

- lib/chef/provider/user/mac.rb
- lib/chef/resource/user/mac_user.rb
Backport https://github.com/chef/chef/pull/9275 and https://github.com/chef/chef/pull/9322
> mac_user: fixing gid and system properties, and adding hidden property

- RELEASE_NOTES.md
- lib/chef/resource/sysctl.rb
- spec/unit/resource/sysctl_spec.rb
Backport https://github.com/chef/chef/pull/8409 and https://github.com/chef/chef/pull/9321
> sysctl: Add new comments property for adding comments to configs

- .expeditor/release.omnibus.yml
This PR is just adding Debian 10 testing to the omnibus builds for Chef 15
> Add Debian 10 Tester to Chef 15

- .expeditor/release.omnibus.yml
This PR is just adding Debian 10 testing to the omnibus builds for Chef 14
> Add Debian 10 (Buster) Tester

- RELEASE_NOTES.md
> Add Chef Infra Client 15.8 release notes

- chef-utils/lib/chef-utils/dsl/windows.rb
> Add missing require_relative in chef-utils

- lib/chef/resource/hostname.rb
- lib/chef/resource/notify_group.rb
- lib/chef/resource/openssl_dhparam.rb
- lib/chef/resource/openssl_ec_private_key.rb
- lib/chef/resource/openssl_ec_public_key.rb
- lib/chef/resource/openssl_rsa_private_key.rb
- lib/chef/resource/openssl_rsa_public_key.rb
- lib/chef/resource/openssl_x509_certificate.rb
- lib/chef/resource/openssl_x509_crl.rb
- lib/chef/resource/openssl_x509_request.rb
This lets us get these onto the docs site as well.
> Add examples to various resources

- omnibus/Gemfile.lock
- omnibus_overrides.rb
> Update libarchive to 3.4.2 and nokogiri to 1.10.8

- Gemfile
It is internal, so let it float.
> Relax the cheffish constraint

- lib/chef/application/knife.rb
> Fix our verbosity help

- lib/chef/resource/dsc_resource.rb
- lib/chef/resource/homebrew_cask.rb
- lib/chef/resource/homebrew_package.rb
- lib/chef/resource/homebrew_tap.rb
- lib/chef/resource/hostname.rb
- lib/chef/resource/ips_package.rb
- lib/chef/resource/kernel_module.rb
- lib/chef/resource/locale.rb
- lib/chef/resource/macos_userdefaults.rb
- lib/chef/resource/macosx_service.rb
- lib/chef/resource/route.rb
- lib/chef/resource/rpm_package.rb
- lib/chef/resource/sudo.rb
- lib/chef/resource/sysctl.rb
- lib/chef/resource/timezone.rb
- lib/chef/resource/yum_package.rb
- lib/chef/resource/zypper_package.rb
> Convert more resources to unified_mode

- lib/chef/provider/package/dnf/dnf_helper.py
I can't imagine we wouldn't run into needing this.
> Add assumeyes to dnf helper

- lib/chef/provider/mount/mount.rb
- lib/chef/provider/remote_file.rb
- lib/chef/provider/route.rb
- lib/chef/resource/execute.rb
- lib/chef/resource/hostname.rb
- lib/chef/resource/remote_file.rb
- spec/unit/resource/execute_spec.rb
> Use the chef-utils helpers in our resources 

- Gemfile.lock
- omnibus/Gemfile.lock
This includes a fix for Openstack detection
> Update Ohai to 16.0.7

- CONTRIBUTING.md
> Update how approvals / builds happen

- spec/support/shared/unit/script_resource.rb
- spec/unit/cookbook/metadata_spec.rb
- spec/unit/encrypted_data_bag_item/check_encrypted_spec.rb
- spec/unit/encrypted_data_bag_item_spec.rb
- spec/unit/mixin/shell_out_spec.rb
> Remove constraints on specs

- lib/chef/resource/windows_feature_powershell.rb
https://github.com/chef/chef/pull/9205 did the initial bit, but I failed to remove the #powershell_version method that was called by #raise_on_old_powershell. Also remove a platform check around the registry key checks.
> More removal of Windows 2008 R2 support from windows_feature_powershell

- kitchen-tests/kitchen.yml
- lib/chef/provider/ifconfig.rb
- Backport https://github.com/chef/chef/pull/8756 to Chef 14
Fixes https://github.com/chef/chef/issues/9392
> [Backport]ifconfig: fix regex matching interface name with hyphen

- lib/chef/provider.rb
- lib/chef/provider/batch.rb
- lib/chef/provider/powershell_script.rb
- lib/chef/provider/windows_script.rb
Broke some stuff because I assumed the func tests were just having typical breakages.
> fixing some windows func test breaks

- lib/chef/resource/timezone.rb
We don't support Debian / Ubuntu systems that need this logic anymore.
> timezone: Remove support for ubuntu < 16.04 / Debian < 8

- .expeditor/verify.pipeline.yml
- kitchen-tests/kitchen.yml
This is a pre-release container, but it'll get updated as they release
newer versions so we'll continue to test on the latest versions of
20.04 until it's released.
> Test on Ubuntu 20.04 in Buildkite

- Gemfile.lock
- omnibus/Gemfile.lock
This adds the improvements to Azure metadata fetching
> Update Ohai to 16.0.9

- .expeditor/verify.pipeline.yml
- scripts/bk_tests/bk_container_prep.sh
- scripts/bk_tests/bk_linux_exec.sh
We have these baked into the containers now
> Stop installing packages on our constainers that are already there

- Gemfile
- Gemfile.lock
> Pin to Rake 13.0.1 to prevent double rake

- Gemfile.lock
- omnibus/Gemfile.lock
> Update Fauxhai to 8.0

- spec/unit/cookbook/gem_installer_spec.rb
Fix broken require in test.
This require line does not work, but since the tests only run when run with bundler this was probably never a problem.
This is not something unique to these tests, requiring this file like this does not work in a very simple reproduction:
```
Petes-MBP:chef pete$ ruby -rbundler/dsl -e "p Bundler::Dsl"
Traceback (most recent call last):
4: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
3: from /usr/local/Cellar/ruby/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/dsl.rb:6:in `<top (required)>'
1: from /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/dsl.rb:7:in `<module:Bundler>' …
```
> Fix require breaking windows functional tests in BK

- scripts/bk_tests/bk_win_functional.ps1
Make this easier to debug in the future
> Add more folding to the windows functional tests

- lib/chef/property.rb
- lib/chef/resource_inspector.rb
We need this information so we can generator documentation that includes these values.
> Expose equal_to values in property / chef-resource-inspector

- kitchen-tests/cookbooks/end_to_end/recipes/alternatives.rb
- kitchen-tests/cookbooks/end_to_end/recipes/default.rb
- lib/chef/resource/alternatives.rb
- lib/chef/resources.rb
- spec/unit/resource/alternatives_spec.rb
This comes from https://github.com/vkhatri/chef-alternatives
> Add alternatives resource for Linux

- omnibus/config/software/more-ruby-cleanup.rb
Let's see if this gets the tests passing again.
> Remove some of the ruby cleanup to fix builds

- Gemfile.lock
> Update Ohai to 16.0.12

- omnibus/config/software/more-ruby-cleanup.rb
> Remove additional files from the gems in our builds

- lib/chef/provider/mount/mount.rb
- lib/chef/provider/remote_file.rb
- lib/chef/provider/route.rb
- lib/chef/resource/execute.rb
- lib/chef/resource/hostname.rb
- lib/chef/resource/remote_file.rb
- spec/unit/resource/execute_spec.rb
> Use the chef-utils helpers in our resources

- lib/chef/resource/rhsm_errata.rb
- lib/chef/resource/rhsm_errata_level.rb
- lib/chef/resource/rhsm_register.rb
Backport https://github.com/chef/chef/pull/9409
> Update the rhsm_erata* and rhsm_register resources for RHEL 8

- kitchen-tests/cookbooks/end_to_end/recipes/default.rb
- lib/chef/resource/user_ulimit.rb
Also test it in the kitchen tests.
> Fix loading the template file in the user_ulimit resource

- lib/chef/resource/rhsm_register.rb
- spec/unit/resource/rhsm_register_spec.rb
Backporting #9525 to Chef Infra Client 15
> Backport rhsm_register resource :https_for_ca_consumer property

- lib/chef/resource/rhsm_register.rb
I realized we needed this right after the merge
> Add missing introduced value to the new property in rhsm_register

- .expeditor/config.yml
- .expeditor/verify.pipeline.yml
- chef-utils/lib/chef-utils/dsl/architecture.rb
- chef-utils/lib/chef-utils/dsl/cloud.rb
- chef-utils/lib/chef-utils/dsl/introspection.rb
- chef-utils/lib/chef-utils/dsl/os.rb
- chef-utils/lib/chef-utils/dsl/path_sanity.rb
- chef-utils/lib/chef-utils/dsl/platform.rb
- chef-utils/lib/chef-utils/dsl/platform_family.rb
- chef-utils/lib/chef-utils/dsl/service.rb
- chef-utils/lib/chef-utils/dsl/train_helpers.rb
- chef-utils/lib/chef-utils/dsl/windows.rb
Fix some tests and backport some yard comments we use for generating vscode plugin data.
> backport chef-utils comment fixes

- lib/chef/resource/build_essential.rb
I read the GitHub review history wrong on this and totally missed this
suggestion.
> Simplify the matching code per code review

- README.md
- RELEASE_NOTES.md
- docs/dev/design_documents/resource_guard_interpreters.md
- docs/dev/how_to/upgrading_from_chef_12.md
- habitat/default.toml
- lib/chef/cookbook/metadata.rb
- lib/chef/cookbook_loader.rb
- lib/chef/deprecated.rb
- lib/chef/dsl/reboot_pending.rb
- lib/chef/knife.rb
- lib/chef/knife/bootstrap/templates/README.md
- lib/chef/knife/core/ui.rb
- lib/chef/knife/edit.rb
- lib/chef/mixin/api_version_request_handling.rb
- lib/chef/provider/package/rubygems.rb
- lib/chef/resource/cron.rb
- lib/chef/resource/cron_d.rb
- lib/chef/shell/ext.rb
- omnibus/README.md
- omnibus/resources/chef/msi/localization-en-us.wxl.erb
- spec/data/cookbooks/starter/recipes/default.rb
- spec/integration/knife/deps_spec.rb
- spec/unit/data_collector_spec.rb
- spec/unit/deprecated_spec.rb
Backports #9445 to Chef Infra Client 15.X
> Update all our links to use the new docs site format / cleanup descriptions

- lib/chef/resource/windows_share.rb
- spec/unit/resource/windows_share_spec.rb
> Fixed windows share cannot modify frozen string bug 

- spec/functional/run_lock_spec.rb
Backport https://github.com/chef/chef/pull/9449
> Fix file descriptor leak in our tests

- .expeditor/release.omnibus.yml
> Add Windows 10 Tester

- habitat/plan.ps1
> Fix Habitat builds

- .expeditor/release.omnibus.yml
We will not be supporting these platforms for Chef 16
> Stop building S390x packages

- RELEASE_NOTES.md
> Add Chef Infra Client 15.9 release notes

- RELEASE_NOTES.md
> Update the 15.9 release notes

- RELEASE_NOTES.md
> Add security notes for 15.9

- .expeditor/release.omnibus.yml
> Add Ubuntu 20.04 validation / package creation

- .expeditor/release.omnibus.yml
> Add Ubuntu 20.04 x86_64 and Ubuntu 18.04 aarch64 testers

- lib/chef/provider/windows_task.rb
- lib/chef/resource/windows_task.rb
- spec/functional/resource/windows_task_spec.rb
- spec/unit/resource/windows_task_spec.rb
Backport #8420 and #9223 to Chef-14
> Backport windows_task PR #8420 and #9223

- lib/chef/resource/windows_task.rb
> Updated introduced version for start_when_available option

- scripts/bk_tests/bk_win_functional.ps1
This should reduce or remove race conditions while downloading the same
file on multiple container instances.
This cherry-picks 36d254fe1e2c2d0a274854ce627add1f622459b7 from https://github.com/chef/chef/pull/9604 to master.
> Download and verify the Ruby installer, then move into place

- spec/functional/dsl/reboot_pending_spec.rb
This looks like it never worked but we happened to never run into it until we added a desktop platform to the pipeline.
> Really skip the reboot pending func test if a reboot is pending

- spec/functional/dsl/reboot_pending_spec.rb
This looks like it never worked but we happened to never run into it until we added a desktop platform to the pipeline.
> 14: Really skip the reboot pending func test if a reboot is pending

- spec/functional/dsl/reboot_pending_spec.rb
This looks like it never worked but we happened to never run into it until we added a desktop platform to the pipeline.
> 15: Really skip the reboot pending func test if a reboot is pending

- .expeditor/verify.pipeline.yml
- scripts/bk_tests/bk_container_prep.sh
- scripts/bk_tests/bk_linux_exec.sh
This should give us a nice speed bump since we have a ton of gems that need to be compiled
> Cache gems in the verify pipeline to speed up tests

- RELEASE_NOTES.md
> Add 14.15 release notes [skip-ci]

- Gemfile.lock
- omnibus/Gemfile.lock
- spec/functional/dsl/reboot_pending_spec.rb
> Update Ohai to 14.15

- omnibus/Gemfile.lock
This gets us working bundler hopefully
> Update to the latest commits in omnibus-software legacy_ruby branch

- chef-utils/README.md
- chef-utils/lib/chef-utils/dsl/architecture.rb
- chef-utils/spec/unit/dsl/architecture_spec.rb
It's tagged as first shipping in chef 15.10 since I plan to backport this and that'll make sense in the docs.
> Add arm? helper to chef-utils

- lib/chef/knife/bootstrap.rb
- lib/chef/knife/core/bootstrap_context.rb
- spec/unit/knife/core/bootstrap_context_spec.rb
closes #8834
@ccrebolder this should be all that is necessary to fix your issue.
> Fix knife bootstrap_version CLI option overriding config option

- lib/chef/knife/bootstrap.rb
I have given a quick try to fix these potential issues. catch the Sudo related exception and retry with password prompts.
Note: This required a train side fixes as well going to create PR soon
After fixes:
Without --connection-password option:
```
bundle exec knife bootstrap node2.test -N node2.test -U lubos --yes --sudo --use-sudo-password
Connecting to node2.test
Connecting to node2.test
WARN: [SSH] connection failed, terminating (#<Net::SSH::AuthenticationFailed: Authentication failed for user lubos@node2.test>)
WARNING: Failed to authenticate lubos to node2.test - trying password auth
Enter password for lubos@node2.test:
Connecting to node2.test
WARNING: Failed to authenticate lubos to node2.test - Sudo failed: Sudo requires a password, please configure it. 
sudo: 1 incorrect password …
```
> Fixes for sudo password prompt

- lib/chef/mixin/securable.rb
- lib/chef/resource/windows_dfs_server.rb
I think we may finally have them all now.
> Replace a few uses of attributes / parameters in messaging with properties

- .expeditor/release.omnibus.yml
Fix to use the correct Amazon Linux 2 queues.
An adhoc can be found here:
https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/240
> Fix to use correct Amazon Linux 2 queues

- .expeditor/verify.pipeline.yml
- scripts/bk_tests/bk_container_prep.sh
- scripts/bk_tests/bk_linux_exec.sh
Also improve the output. This is all work synced from master.
> Cache gems in Buildkite testing

- .expeditor/release.omnibus.yml
We're already doing this on master
> Produce aarch64 Amazon Linux 2 packages

- lib/chef/node.rb
The consumption of ohai attributes by the ohai segment plugin code
was breaking this feature.
> Fix platform_version Chef::VersionString API

- Gemfile.lock
- omnibus/Gemfile.lock
Also bump all the other stuff while we're at it.
> Update Ohai to 16.0.18 for Windows DMI plugin

- omnibus/omnibus-test.ps1
- tasks/bin/run_external_test
- tasks/dependencies.rb
- tasks/rspec.rb
clean_env is now unbundled in bundler
None
> [CHORE] with_clean_env is deprecated

- omnibus/config/software/more-ruby-cleanup.rb
Remove another 20 files and ~100k from the build size
> Remove a few additional files from our builds

- lib/chef/provider/git.rb
- spec/unit/provider/git_spec.rb
- Exception raised in `define_resource_requirements`
Fixes: #2860
> git resource: Fix for exceptions raised in why-run mode

- lib/chef/provider/package/pacman.rb
- spec/unit/provider/package/pacman_spec.rb
This is a rebase of https://github.com/chef/chef/pull/7984
> Add multipackage support to pacman package resource

- omnibus/Gemfile.lock
Let's see if this fixes it for realz this time.
> Update omnibus-software again to bring in double pry fixes

- RELEASE_NOTES.md
> Add 15.10 release notes

- omnibus/Gemfile.lock
Pull in the latest and greatest
> Update our omnibus software def to fix bundler on windows

- lib/chef/resource/windows_firewall_rule.rb
> Backport #9511 to Chef 15

- .expeditor/verify.pipeline.yml
The previous failures should be resolved with the update to Expeditor
> Enable caching of all our buildkite jobs again

- lib/chef/resource/rpm_package.rb
- lib/chef/resource/script.rb
- lib/chef/resource/service.rb
- lib/chef/resource/windows_firewall_rule.rb
Update things so we spit out better docs.
> Minor improvements to the resource descriptions

- habitat/plan.sh
Signed-off-by: John Snow <thelunaticscripter@outlook.com>
Fix the linux plan to build with ruby 2.7
> Fix linux plan to use ruby 2.7

- lib/chef/resource/locale.rb
- spec/functional/resource/locale_spec.rb
- spec/unit/resource/locale_spec.rb
- Now users can set the system locale on Windows with the help of locale resource.
Fixes: #9450
> locale: Support setting locale on Windows

- docs/dev/how_to/building_and_installing.md
- scripts/bk_tests/bk_linux_exec.sh
Also asdf is already installed
> Run Test Kitchen tests on Ruby 2.7

- kitchen-tests/cookbooks/end_to_end/recipes/default.rb
- lib/chef/resource/locale.rb
Expand the docs a bit for the docs site.
> Test and better document the locale resource

- lib/chef/resource/apt_preference.rb
- lib/chef/resource/apt_repository.rb
- lib/chef/resource/chef_client_cron.rb
- lib/chef/resource/chef_client_scheduled_task.rb
- lib/chef/resource/chef_client_systemd_timer.rb
- lib/chef/resource/windows_firewall_rule.rb
- lib/chef/resource/windows_service.rb
- tasks/docs.rb
A PR against the work that @phiggins did as a PR so we can review the changes.
> Additions to the auto generate resource docs code

- lib/chef/resource/apt_preference.rb
- lib/chef/resource/apt_repository.rb
- lib/chef/resource/chef_client_cron.rb
- lib/chef/resource/chef_client_scheduled_task.rb
- lib/chef/resource/chef_client_systemd_timer.rb
- lib/chef/resource/windows_firewall_rule.rb
- lib/chef/resource/windows_service.rb
- tasks/docs.rb
Work to make generating the docs less of a manual process.
For #9412. Includes code from  #9727 and https://github.com/chef/chef/tree/auto_generate.
> Updates for auto generated docs

- RELEASE_NOTES.md
> Adding YAML description to release notes.

- .expeditor/verify.pipeline.yml
Emojis are compact and easier to skim visually?
> add a ridiculous amount of emoji to buildkite test names

- spec/unit/mixin/powershell_exec_spec.rb
> Fix the powershell spec to use the right method

- RELEASE_NOTES.md
> Add Chef Infra Client 16 release notes

- RELEASE_NOTES.md
- lib/chef/resource/alternatives.rb
- lib/chef/resource/chef_client_cron.rb
- lib/chef/resource/chef_client_scheduled_task.rb
- lib/chef/resource/chef_client_systemd_timer.rb
- lib/chef/resource/zypper_package.rb
- lib/chef/resource/zypper_repository.rb
- tasks/docs.rb
Add some missing docs we'll use to generate docs on the docs site. Fix
an incorrect resource name. Fix a bad link in the release notes.
> Improve resource docs

- RELEASE_NOTES.md
- lib/chef/resource/windows_task.rb
- lib/chef/resource/windows_workgroup.rb
- lib/chef/resource/yum_package.rb
- lib/chef/resource/yum_repository.rb
- tasks/docs.rb
Make sure we don't document the deprecated properties and generally fix the formatting so we can auto generate the docs for the docs site properly.
> More resource documentation improvements

- RELEASE_NOTES.md
* filesystem2 is only now being introduced on windows
* log-* is additive
> Some fixes for Chef 16 release notes.

- lib/chef/resource/apt_package.rb
- lib/chef/resource/apt_preference.rb
- lib/chef/resource/apt_repository.rb
- lib/chef/resource/apt_update.rb
- lib/chef/resource/archive_file.rb
- lib/chef/resource/chef_client_cron.rb
- lib/chef/resource/chef_client_systemd_timer.rb
- lib/chef/resource/chocolatey_package.rb
- lib/chef/resource/cron.rb
- lib/chef/resource/cron_d.rb
- lib/chef/resource/dmg_package.rb
- lib/chef/resource/file.rb
- lib/chef/resource/gem_package.rb
- lib/chef/resource/ifconfig.rb
- lib/chef/resource/user.rb
- lib/chef/resource/windows_auto_run.rb
- lib/chef/resource/windows_feature.rb
- lib/chef/resource/windows_feature_dism.rb
- lib/chef/resource/windows_feature_powershell.rb
- lib/chef/resource/windows_package.rb
- lib/chef/resource/windows_pagefile.rb
- lib/chef/resource/windows_task.rb
- lib/chef/resource/yum_repository.rb
- tasks/docs.rb
Keeping this open to add resource updates to over time
> More improvements to the docs generation

- spec/support/platform_helpers.rb
The code this was used with is long gone
> Remove an unused spec helper

- lib/chef/resource/apt_preference.rb
- lib/chef/resource/bff_package.rb
- lib/chef/resource/cron.rb
- lib/chef/resource/cron_d.rb
- lib/chef/resource/dmg_package.rb
- lib/chef/resource/dpkg_package.rb
- lib/chef/resource/windows_env.rb
- lib/chef/resource/windows_feature.rb
- lib/chef/resource/windows_feature_dism.rb
- lib/chef/resource/windows_feature_powershell.rb
- lib/chef/resource/windows_font.rb
- lib/chef/resource/windows_package.rb
- lib/chef/resource/windows_pagefile.rb
- lib/chef/resource/windows_path.rb
- lib/chef/resource/windows_printer.rb
- lib/chef/resource/windows_printer_port.rb
- lib/chef/resource/windows_task.rb
- lib/chef/resource/yum_repository.rb
- lib/chef/resource/zypper_repository.rb
- lib/chef/resource_inspector.rb
- tasks/docs.rb
> Add more examples to resources

- lib/chef/resource/apt_package.rb
- lib/chef/resource/chef_gem.rb
- lib/chef/resource/chocolatey_package.rb
- lib/chef/resource/cookbook_file.rb
- lib/chef/resource/cron_access.rb
- lib/chef/resource/file.rb
- lib/chef/resource/gem_package.rb
- lib/chef/resource/rpm_package.rb
- lib/chef/resource/scm/_scm.rb
- lib/chef/resource/scm/subversion.rb
- lib/chef/resource/solaris_package.rb
- lib/chef/resource/sudo.rb
- lib/chef/resource/swap_file.rb
- lib/chef/resource/systemd_unit.rb
- lib/chef/resource/windows_dfs_folder.rb
- lib/chef/resource/windows_dfs_namespace.rb
- lib/chef/resource/windows_dfs_server.rb
- lib/chef/resource/yum_package.rb
- tasks/docs.rb
> Another round of description updates && Docs generator tweaks

- .expeditor/verify.pipeline.yml
- chef.gemspec
- kitchen-tests/kitchen.yml
> Fix failing RHEL 6 kitchen tests

- kitchen-tests/cookbooks/end_to_end/recipes/_cron.rb
- kitchen-tests/cookbooks/end_to_end/recipes/default.rb
- lib/chef/resource/cron_d.rb
Add kitchen testing for the cron resources
> Fix failures in the cron_d resource :remove action

- RELEASE_NOTES.md
> Add release notes for 16.0.275 [skip-ci]

- omnibus/config/software/more-ruby-cleanup.rb
This shave about ~200k and 74 files from our install.
> More cleanup of our installed gems

- omnibus/Gemfile.lock
Update omnibus-software for new msys2 path
> Update omnibus-software for new msys2 path

- lib/chef/provider/package/chocolatey.rb
- lib/chef/win32/api/command_line_helper.rb
- spec/functional/resource/chocolatey_package_spec.rb
- spec/unit/provider/package/chocolatey_spec.rb
backport #9509 to chef-15 which fixes #9413 and was escalated via https://github.com/chef/customer-bugs/issues/142
> Fix for Chocolate_resource options causing extra quotes

- omnibus/Gemfile.lock
https://github.com/chef/omnibus-software/pull/1196
https://github.com/chef/customer-bugs/issues/91
> Update omnibus-software for Windows lalr1.java removal

- kitchen-tests/cookbooks/end_to_end/recipes/_apt.rb
- kitchen-tests/cookbooks/end_to_end/recipes/_sudo.rb
- kitchen-tests/cookbooks/end_to_end/recipes/_sysctl.rb
- kitchen-tests/cookbooks/end_to_end/recipes/_yum.rb
- kitchen-tests/cookbooks/end_to_end/recipes/default.rb
- scripts/bk_tests/bk_linux_exec.sh
> Expand our sudo, sysctl, execute, apt_update and apt_preference testing

- scripts/bk_tests/bk_linux_exec.sh
We need to cache them in the project root not the TK root
> Cache the gems during the Test Kitchen tests

- scripts/bk_tests/bk_linux_exec.sh
> Don't update rubygems / bundler in the kitchen tests

- omnibus/Gemfile.lock
- openssl 1.0.2v
> Changes between 1.0.2u and 1.0.2v [5 May 2020]
>
> *) Implemented coordinate blinding for the generic implementations of both
> binary and prime elliptic curves to avoid leaking bits of the scalar and,
> potentially, bug attacks. A group of security researchers and
> cryptographers from academia and industry, listed below, reported a
> successful cache timing attack in OpenSSL 1.0.2u against specific prime and
> binary curves whose order or field length is close to a word boundary. They
> also provided the fix. This attack does not fit the OpenSSL threat model
> and so no CVE is assigned, but a fix is implemented nonetheless.
> [Diego F. Aranha, Akira Takahashi, Mehdi Tibouchi, Yuval Yarom]
- removes lalr1.java on windows
https://github.com/chef/customer-bugs/issues/91 …
> 15: Update omnibus-software to 74e9d0

- lib/chef/knife/user_invite_rescind.rb
> Fix a misspelling in knife subcommand.

- .expeditor/verify.pipeline.yml
- scripts/bk_tests/bk_linux_exec.sh
It seems odd that we install ruby over ruby
> Try removing asdf entirely and just use omnibus-toolchain

- lib/chef/formatters/error_inspectors/node_load_error_inspector.rb
- lib/chef/formatters/error_inspectors/registration_error_inspector.rb
Improves the branding here and makes sure this displays correctly for
cinc
> Use the dist values in server error messages

- .expeditor/release.omnibus.yml
> Add Debian 10 aarch64 support

- .expeditor/verify.pipeline.yml
> Add Ubuntu 20.04 testing to our pipeline

- .expeditor/verify_public.pipeline.yml
Most of these emojis I can't remember so I spend longer waiting for the
mouse-overs that I did before when some were too long. :older_man:
Removed a duplicate Amazon Linux TK test
Shortened some text where I thought it made sense too
This is obviously a bikeshed but I really do find the emoji's difficult
> Remove most of the emojis from the buildkite tests

- .expeditor/verify_public.pipeline.yml
- scripts/bk_tests/bk_win_functional.ps1
> Switch Ruby functional test on Windows to Ruby 2.7

- RELEASE_NOTES.md
> Add 16.1 release notes

- lib/chef/resource_inspector.rb
The chef-resource-inspector with zero args inspects chef, but you can also pass it an argument to inspect cookbooks or files. The current logic for inspecting a cookbook is broken. It incorrectly tries to load cookbooks and it results in failures after several minutes of spinning.
> Fix failures inspecting a single cookbook

- lib/chef/mixin/checksum.rb
- lib/chef/provider/file.rb
- lib/chef/provider/package/windows.rb
- lib/chef/resource/file.rb
A few small things I noticed while reading code.
> Small cleanups to checksum logic in file/windows_package/chef::mixin::checksum

- chef-utils/spec/unit/dsl/architecture_spec.rb
https://github.com/chef/chef/pull/9887#pullrequestreview-415569069
@phiggins noticed the broken tests after the merge, this fixes the test.
Signed-off-by: Matt Ray <github@mattray.dev>
> Fixed armv6l and armv7l tests.

- chef-utils/README.md
Signed-off-by: Michel Salim <michel@fb.com>
Slightly reword the introduction paragraph, and fix the mention of Devuan (the systemd-less Debian derivative).
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chef/chef/9895)
> [chef-utils] fix typos

- cspell.json
- lib/chef/resource/macos_userdefaults.rb
> macos_userdefaults: Fix ruby 2.7 keyword args warning and refactor a bit

- chef-utils/README.md
- chef-utils/lib/chef-utils/dsl/architecture.rb
- chef-utils/spec/unit/dsl/architecture_spec.rb
- lib/chef/formatters/error_inspectors/node_load_error_inspector.rb
- lib/chef/formatters/error_inspectors/registration_error_inspector.rb
- lib/chef/knife/bootstrap/templates/windows-chef-client-msi.erb
- lib/chef/knife/core/windows_bootstrap_context.rb
- lib/chef/resource_inspector.rb
- spec/unit/knife/core/windows_bootstrap_context_spec.rb
https://github.com/chef/chef/pull/9895
https://github.com/chef/chef/pull/9892
https://github.com/chef/chef/pull/9889
https://github.com/chef/chef/pull/9887
https://github.com/chef/chef/pull/9882
https://github.com/chef/chef/pull/9878
https://github.com/chef/chef/pull/9830
> Multiple backports from Chef 16

- .expeditor/verify_public.pipeline.yml
> Windows functional test should be single-use

- RELEASE_NOTES.md
> Add 15.11 Release Notes

- .expeditor/verify.pipeline.yml
> Windows functional tests should be single-use

- RELEASE_NOTES.md
> Add 16.1.16 release notes

- RELEASE_NOTES.md
- docs/dev/design_documents/resource_load_and_converge_methods.md
- docs/dev/how_to/bumping_the_major_version.md
- lib/chef/resource/homebrew_package.rb
- lib/chef/resource/kernel_module.rb
- lib/chef/resource/plist.rb
- lib/chef/resource/template.rb
- tasks/docs.rb
Add more descriptions and examples
Remove some smart quotes
Make sure homebrew_package gets tagged as supporting multi-package
> Improve auto-generated docs

- lib/chef/resource/cron_access.rb
Noticed this failing CI when reviewing another PR.
> Fix chefstyle violations.

- lib/chef/resource/cron_access.rb
This was hitting the file resource not the file ruby class.
> Make sure file is properly scoped in cron_access

- lib/chef/resource/hostname.rb
> hostname: Improve the windows reboot message

- spec/unit/provider/apt_repository_spec.rb
- spec/unit/provider/zypper_repository_spec.rb
We've already done this on master
> Avoid some constant warnings in specs

- spec/spec_helper.rb
- spec/support/chef_helpers.rb
- spec/unit/data_collector_spec.rb
- spec/unit/file_access_control_spec.rb
- spec/unit/json_compat_spec.rb
- spec/unit/resource_reporter_spec.rb
- spec/unit/run_lock_spec.rb
- spec/unit/scan_access_control_spec.rb
- tasks/rspec.rb
> Pull in spec task / helper from master

- lib/chef/resource/archive_file.rb
This way it always gets called in the action, but we can still avoid
spec failures on systems that don't have ffi-libarchive
> archive_file: move ffi-libarchive into a simple helper method

- .expeditor/config.yml
Subscribe to the more specific gem so we avoid double bumps
> Prevent double inspec dep bump PRs

- lib/chef/resource/windows_ad_join.rb
- lib/chef/resource/windows_auto_run.rb
- lib/chef/resource/windows_certificate.rb
- tasks/docs.rb
Skip defaults that are empty strings. There's a few of these floating around.
> Add more resource docs + improve yaml generation

- .expeditor/release.omnibus.yml
This PR just adds Windows 8 support, an adhoc build showing it working as expected can be found here:
https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/258
> Add Windows 8 Tester

- .expeditor/verify_public.pipeline.yml
- Rakefile
> Nicer error for misconfigured spellcheck in CI

- CHEF_MVPS.md
Updated with the MVPs listed for this year
Moved the contents around so newest are first.
> Update with 2020 MVPs

- lib/chef/provider/script.rb
- lib/chef/provider/windows_script.rb
- lib/chef/resource/bash.rb
- lib/chef/resource/batch.rb
- lib/chef/resource/csh.rb
- lib/chef/resource/perl.rb
- lib/chef/resource/powershell_script.rb
- lib/chef/resource/python.rb
- lib/chef/resource/ruby.rb
- lib/chef/resource/windows_script.rb
- spec/support/shared/unit/execute_resource.rb
- spec/unit/resource/timezone_spec.rb
Some small things salvaged from a larger refactoring I'm abandoning.
> Small code cleanups in script/windows_script

- kitchen-tests/cookbooks/end_to_end/recipes/_snap.rb
- kitchen-tests/cookbooks/end_to_end/recipes/linux.rb
- lib/chef/provider/package/snap.rb
> Disable snap dokken tests for now

- lib/chef/resource/windows_audit_policy.rb
- lib/chef/resource/windows_auto_run.rb
- lib/chef/resource/windows_certificate.rb
> Improve resource documentation

- lib/chef/resource/cron/_cron_shared.rb
> Change a variable name causing a spelling violation.

- RELEASE_NOTES.md
- cspell.json
> Add release notes for Infra Client 16.2

- azure-pipelines.yml
- lib/chef/provider/user/dscl.rb
- lib/chef/resource/homebrew_update.rb
- lib/chef/util/diff.rb
> Minor docs updates and MacOS -> macOS

- lib/chef/resource/chef_gem.rb
- lib/chef/resource/gem_package.rb
- tasks/docs.rb
This started from wanting to fix the busted examples section for chef_gem and grew from there:
> Resource doc updates

- lib/chef/resource/cron_access.rb
> Support for AIX and Solaris in cron_allow resource 

- spec/unit/util/threaded_job_queue_spec.rb
> Silence exception output in threaded test.

- Gemfile.lock
> Bump Ohai to 15.12 to support macOS Big Sur

- lib/chef/knife/bootstrap/templates/chef-full.erb
> Use /etc/chef for bootstrapping instead of ChefConfig

- spec/unit/chef_fs/diff_spec.rb
https://rubular.com/r/5JdtZDqWnZhB9J
> Fix broken tests after updating diff-lcs dep

- spec/unit/role_spec.rb
- spec/unit/util/selinux_spec.rb
There's like 18 different bugs that need fixing in these one by one, no single cause.
> Fix some windows unit tests

- Gemfile.lock
This fixes some errors I was seeing, but I'm getting different errors locally.
> Bump diff-lcs to get bugfix.

- lib/chef/provider/package/cab.rb
- lib/chef/provider/package/msu.rb
- lib/chef/resource/msu_package.rb
- spec/functional/resource/msu_package_spec.rb
- spec/unit/resource/msu_package_spec.rb
Backport the msu_package fixes that went into 16.0
> fix msu_package installation and extend the timeout to 60 minutes with a new property

- lib/chef/application/apply.rb
Hi, I found a load error when using `chef-apply` with json attribs.
That causes a `NameError: uninitialized constant Chef::ConfigFetcher`.
Signed-off-by: Takuto Komazaki <komazarari@gmail.com>
Add a require to` apply.rb` to solve following problem.
```
$ bundle exec chef-apply /tmp/recipe.rb -j /tmp/dummy.json
bundler: failed to load command: chef-apply (/home/takuto-komazaki/src/github.com/chef/chef/vendor/bundle/ruby/2.7.0/bin/chef-apply)
NameError: uninitialized constant Chef::ConfigFetcher
/home/takuto-komazaki/src/github.com/chef/chef/lib/chef/application/apply.rb:149:in `parse_json'
/home/takuto-komazaki/src/github.com/chef/chef/lib/chef/application/apply.rb:144:in `reconfigure'
/home/takuto-komazaki/src/github.com/chef/chef/lib/chef/application/apply.rb:238:in `run' …
```
> Fixed broken chef-apply with -j

- spec/functional/resource/aix_service_spec.rb
- spec/functional/resource/aixinit_service_spec.rb
- spec/functional/resource/bff_spec.rb
- spec/functional/resource/cron_spec.rb
- spec/functional/resource/ifconfig_spec.rb
- spec/functional/resource/link_spec.rb
- spec/functional/resource/mount_spec.rb
- spec/functional/resource/msu_package_spec.rb
An attempt to fix the tests that are failing in the release build.
https://buildkite.com/chef/chef-chef-master-omnibus-release/builds/613#_
> Fix release build tests

- spec/functional/resource/cron_spec.rb
A small thing I missed in #10088.
> Fix release build tests, part 2

- RELEASE_NOTES.md
> Add release notes for 16.2.72

- lib/chef/deprecated.rb
> Reserve deprecation ID that was used in Chef-15

- lib/chef/deprecated.rb
- lib/chef/resource/lwrp_base.rb
The deprecation docs are being added in https://github.com/chef/chef-web-docs/pull/2564
> Add resource_name_without_provides deprecation

- lib/chef/resource/windows_security_policy.rb
Switch to the powershell_out command instead of the powershell_exec so that testing on 32bit Windows succeeds.
Functional tests were failing due to powershell_exec not yet working wtih 32bit Windows versions.
> update to powershell_out to be compatible with 32 bit windows

- .expeditor/config.yml
With Chef 14 EOL we have deleted the Buildkite pipelines and this PR prevents them from being recreated.
> Remove Buildkite Pipelines

- lib/chef/chef_fs/data_handler/organization_data_handler.rb
- lib/chef/cookbook/remote_file_vendor.rb
- lib/chef/cookbook/syntax_check.rb
- lib/chef/data_bag.rb
- lib/chef/environment.rb
- lib/chef/knife/core/windows_bootstrap_context.rb
- lib/chef/mixin/openssl_helper.rb
- lib/chef/provider/package/snap.rb
- lib/chef/resource/chocolatey_feature.rb
- lib/chef/resource/openssl_x509_certificate.rb
- lib/chef/resource/openssl_x509_crl.rb
- lib/chef/role.rb
- lib/chef/win32/registry.rb
These seemed pretty straight forward. There's a new Rubocop cop for these.
> Avoid assigning variables before returning if we don't have to

- spec/unit/provider/package/windows_spec.rb
- spec/unit/resource/windows_package_spec.rb
Fixes some of the tests for the Windows package provider. There are other failing tests in this file that are beyond me at the moment.
> Fix some windows package tests

- lib/chef/resource/windows_dns_record.rb
This will make sure the docs generate correctly
> Add introduced field to new propertyin windows_dns_record

- lib/chef/provider/git.rb
- spec/functional/resource/git_spec.rb
Signed-off-by: Matthieu Serrepuy <lotooo@gmail.com>
This PR tried to fix the git resource when a `:sync` action is triggerred.
The `git` resouce is currently failing in chef-client 16 (tested with 16.1.16) when a new commit needs to be synced because you can't do a `git branch -f branch_name branch_name` if you are already on the  branch  `branch`.
https://github.com/chef/chef/issues/9872
> Fix git sync if the local branch already exist

- .expeditor/verify.pipeline.yml
- cspell.json
- tasks/spellcheck.rb
> Fix spellcheck CI task

- tasks/spellcheck.rb
> Minor chefstyle fixes in the spellcheck task

- lib/chef/http/authenticator.rb
see https://github.com/chef/chef-cli/issues/111 for related bug.
🚧 need to ponder the blast radius of this one 🚧 
although i think we clearly need to do this.
> Bump the server api version to 2

- spec/spec_helper.rb
- spec/unit/chef_fs/file_system/operation_failed_error_spec.rb
- spec/unit/cookbook/gem_installer_spec.rb
> Don't allow setting expectations on nil.

- Gemfile.lock
- chef-bin/chef-bin.gemspec
- chef-config/chef-config.gemspec
- chef-utils/chef-utils.gemspec
- lib/chef/provider/mount/solaris.rb
- lib/chef/provider/package/zypper.rb
- lib/chef/resource/execute.rb
- omnibus/Gemfile.lock
- spec/functional/resource/aix_service_spec.rb
- spec/functional/resource/aixinit_service_spec.rb
- spec/functional/resource/apt_package_spec.rb
- spec/functional/resource/cron_spec.rb
- spec/functional/resource/insserv_spec.rb
- spec/unit/mixin/securable_spec.rb
> Update to Chefstyle 1.2 + some fixes

- spec/unit/provider/package/rubygems_spec.rb
This is gross but I couldn't figure out a different way to get this test to pass.
> Workaround rubygems ssl test failure

- omnibus/Gemfile.lock
This adds a new cert to our bundle
> Bump omnibus-software to pull in the new cacerts

- lib/chef/mixin/openssl_helper.rb
- spec/spec_helper.rb
- spec/support/shared/integration/knife_support.rb
- spec/unit/chef_fs/file_system/operation_failed_error_spec.rb
- spec/unit/cookbook/gem_installer_spec.rb
- spec/unit/knife/cookbook_upload_spec.rb
- spec/unit/provider/package/dnf/python_helper_spec.rb
- spec/unit/provider/package/rubygems_spec.rb
- spec/unit/provider/package/windows_spec.rb
- spec/unit/provider/service/windows_spec.rb
- spec/unit/provider/systemd_unit_spec.rb
- spec/unit/resource/windows_package_spec.rb
- spec/unit/win32/security_spec.rb
These fix most of the failing windows unit tests:
https://github.com/chef/chef/pull/10129
https://github.com/chef/chef/pull/10127
https://github.com/chef/chef/pull/10136
https://github.com/chef/chef/pull/10138
https://github.com/chef/chef/pull/10144
https://github.com/chef/chef/pull/10149
https://github.com/chef/chef/pull/10150
https://github.com/chef/chef/pull/10155
https://github.com/chef/chef/pull/10154
https://github.com/chef/chef/pull/10160
> Backport various testing fixes from Infra Client 16

- lib/chef/resource/chef_client_scheduled_task.rb
Fixes https://github.com/chef/chef/issues/10175
This originated with @tiobagio
Signed-off-by: Matt Ray <github@mattray.dev>
> Replace single quotes with double

- lib/chef/knife/config_list_profiles.rb
- spec/integration/knife/config_list_profiles_spec.rb
Per https://github.com/chef/chef/issues/9686#issuecomment-647845732 we need not to check for list-profiles if we have already selected a bad profile.
So with this change we achieve this that if we have selected any bad profile then it won't affect for `knife config list-profiles` command.
Fixes https://github.com/chef/chef/issues/10065
```
bundle exec knife config get-profile -c ~/Downloads/chef-repo/.chef/knife.rb
manage
bundle exec knife config list-profiles -c ~/Downloads/chef-repo/.chef/knife.rb
Profile     Client   Key                                       Server
-------------------------------------------------------------------------------------------------------
management  dheerajd-msys …
```
> don't check list-profiles for already selected bad profile

- lib/chef/provider/package/windows.rb
I didn't realize that the source_package was being used to
collect the merged state off of the property.
> fix windows package for Chef-16 regression

- omnibus/Gemfile.lock
Pull in a potential fix for the current failure
> Update the ruby-cleanup omnibus-software configs

- omnibus/Gemfile.lock
Remove another duplicate entry causing failures
> Update ruby cleanup omnibus software again

- chef-config/lib/chef-config/path_helper.rb
- chef-config/spec/unit/path_helper_spec.rb
Eliminates a very large number of allocation in this routine simply
by moving code which never changes to a static method + constant.
before:
```
sourcefile                                            sourceline  count
----------------------------------------------------------------------------------------------  ----------  -----
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-config-16.2.74/lib/chef-config/path_helper.rb          59    629
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-config-16.2.74/lib/chef-config/path_helper.rb         144   1292
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-config-16.2.74/lib/chef-config/path_helper.rb         323      3
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-config-16.2.74/lib/chef-config/path_helper.rb          70    839 …
```
> Reduce path_helper allocations

- lib/chef/mixin/default_paths.rb
- lib/chef/mixin/which.rb
Fixing a few things that may have broken selinux on EL6 through 'which'
support.
> Fix default_paths patch

- Gemfile.lock
- omnibus/Gemfile.lock
> Bump Ohai to 16.3.0

- spec/functional/resource/git_spec.rb
> Remove bad filter from git spec tests

- lib/chef/handler.rb
Make sure this stays out of docs
> Mark a private method as private with yard

- lib/chef/http.rb
- spec/unit/server_api_spec.rb
> Fix NoMethodError when server returns a 406.

- Gemfile.lock
- omnibus/Gemfile.lock
> Update mixlib-shellout to 3.1.2

- Gemfile.lock
- omnibus/Gemfile.lock
- omnibus_overrides.rb
> Update libarchive, liblzma, and nokogiri to the latest

- omnibus/Gemfile.lock
> Bump omnibus-software to the latest

- RELEASE_NOTES.md
> Release 15.13

- RELEASE_NOTES.md
> Add 16.3.45 release notes

- omnibus/Gemfile.lock
This shaves 200k off the builds
> Remove debug code from libxml2

- omnibus/Gemfile.lock
> Further slim down libxml2

- lib/chef/resource/windows_firewall_rule.rb
Use cover? instead of include? with ranges
> Resolve Performance/RangeInclude warnings

- lib/chef/resource/apt_repository.rb
> apt_repository: Small code refactor in key_is_valid? method

- lib/chef/provider/package/rubygems.rb
Avoid creating an object only to select the first
> Use find instead of select.first

- Gemfile.lock
- omnibus/Gemfile.lock
This includes some significant perf improvements
> Pull Ohai 16.4.2 into Chef Infra Client

- chef-config/lib/chef-config/dist.rb
This is a continuation of https://github.com/chef/chef/issues/8376 adding support for chef-server
Example use-cases
https://github.com/tehlers320/chef-server/commit/21f9db8d8e18e3b7b64b199df2bfe67883645a59#diff-985e82b77141fc1a597fa9eb1e98180e
examples of what/where can use these constants
https://github.com/chef/chef-server/pull/2031/files
> added configuration options for chef-server

- lib/chef/provider/zypper_repository.rb
- lib/chef/resource.rb
- lib/chef/resource/windows_share.rb
- lib/chef/resource/windows_workgroup.rb
- spec/functional/resource/dsc_script_spec.rb
- spec/functional/resource/windows_security_policy_spec.rb
The universal DSL includes all this stuff. In Resource we include the universal DSL, but we also include several of the things it includes.
> Remove more requires that come for free

- lib/chef/resource/windows_ad_join.rb
- lib/chef/resource/windows_audit_policy.rb
- lib/chef/resource/windows_auto_run.rb
- lib/chef/resource/windows_certificate.rb
- lib/chef/resource/windows_dfs_folder.rb
- lib/chef/resource/windows_dfs_namespace.rb
- lib/chef/resource/windows_dfs_server.rb
- lib/chef/resource/windows_dns_record.rb
- lib/chef/resource/windows_dns_zone.rb
- lib/chef/resource/windows_feature.rb
- lib/chef/resource/windows_feature_dism.rb
- lib/chef/resource/windows_feature_powershell.rb
- lib/chef/resource/windows_firewall_profile.rb
- lib/chef/resource/windows_firewall_rule.rb
- lib/chef/resource/windows_font.rb
- lib/chef/resource/windows_pagefile.rb
- lib/chef/resource/windows_printer.rb
- lib/chef/resource/windows_printer_port.rb
- lib/chef/resource/windows_security_policy.rb
- lib/chef/resource/windows_share.rb
- lib/chef/resource/windows_shortcut.rb
- lib/chef/resource/windows_uac.rb
- lib/chef/resource/windows_user_privilege.rb
- lib/chef/resource/windows_workgroup.rb
Tiny bit of code rage included to wipe out a completely unnecessary
nodoc property I found in two of these.
I also renamed the "do_it" method in two of these.
Plus added the sensitive flag to a password property.
And a comment yelling about #10240 
There are 7 other non-custom-resource-style windows resources that
need converting that are all that is left.
> Convert windows custom resources to unified_mode

- chef-config/lib/chef-config/dist.rb
This is a continuation of https://github.com/chef/chef/issues/8376 adding support for chef-server
Example use-cases
https://github.com/tehlers320/chef-server/commit/21f9db8d8e18e3b7b64b199df2bfe67883645a59#diff-985e82b77141fc1a597fa9eb1e98180e
examples of what/where can use these constants
https://github.com/chef/chef-server/pull/2031/files
> Backport dist configuration to chef15

- lib/chef/run_status.rb
Resolves Style/BisectedAttrAccessor
> Combine attr_reader / attr_writer into attr_accessor

- chef-config/lib/chef-config/workstation_config_loader.rb
- lib/chef/node/attribute.rb
- lib/chef/resource_collection/stepable_iterator.rb
Avoid assigning when we don't need to
> Resolve Style/RedundantAssignment warnings

- lib/chef/mixin/deep_merge.rb
It ain't quite private, but if people find it useful but not quite what
they want they need to maintain their own implementation.
Seems to come up every year or two, I think this makes it clear.
Closes #10275
> Mark deep_merge as private

- spec/unit/provider/powershell_script_spec.rb
#10274 broke one of the tests on Windows.
> Fix broken powershell_script test.

- Gemfile.lock
- omnibus/Gemfile.lock
> Bump Ohai / Cheffish to the latest

- lib/chef/chef_class.rb
New RuboCop rule detected this dupe
> Remove a duplicate require

- Gemfile.lock
- omnibus/Gemfile.lock
> Update chef-telemetry and ohai to the latest

- Gemfile.lock
- omnibus/Gemfile.lock
> Bump deps for require perf optimizations

- omnibus/kitchen.yml
Get this closer to actually working as a test environment.
> Update Omnibus kitchen config with public boxes

- spec/functional/resource/link_spec.rb
> Convert the functional tests over to macos? as well

- chef-config/lib/chef-config/config.rb
- chef-config/lib/chef-config/path_helper.rb
- chef-config/spec/unit/config_spec.rb
- chef-config/spec/unit/path_helper_spec.rb
- lib/chef/knife/core/windows_bootstrap_context.rb
- spec/unit/knife/core/windows_bootstrap_context_spec.rb
> Fix bootstrapping windows-from-linux

- RELEASE_NOTES.md
> Add 16.4 release notes

- Gemfile.lock
- omnibus/Gemfile.lock
> Update train to 3.3.16

- lib/chef/resource/windows_feature_powershell.rb
- spec/unit/resource/windows_feature_powershell_spec.rb
windows features were not getting installed when it's InstallState was `Removed`
- This change handles installing features when state is removed or disabled(available)
- Works for single as well as multi-feature installation
- Earlier intersection of the features returned nil when state was `Removed` so feature was not getting installed.
- Ensured `Idempotent`  for the `windows_feature_powershell`
- Redundant test removed
Fixes https://github.com/chef/chef/issues/9536
```
PS C:\Users\Administrator\chef> Get-WindowsFeature -Name NET-Framework-Core
Display Name                                            Name                       Install State
------------                                            ---- …
```
> Fix install windows features when install state is removed 

- kitchen-tests/cookbooks/end_to_end/recipes/macos.rb
- lib/chef/resource/osx_profile.rb
Make sure we can execute the resource in a Test Kitchen run.
> Further improve osx_profile error message and add a test

- kitchen-tests/cookbooks/end_to_end/recipes/macos.rb
> Fix chefstyle in the Test Kitchen test

- lib/chef/knife/configure.rb
This command failed w/o these requires
> Add missing requires for knife configure command

- omnibus/omnibus-test.ps1
- omnibus/omnibus-test.sh
Get timing data so we know what we're doing.
> Enable rspec --profile in the omnibus tests

- spec/spec_helper.rb
- spec/support/platform_helpers.rb
> Simplify macos detection in specs to include big sur

- docs/dev/design_documents/client_exit_codes.md
This wasn't added to the design doc
> Document Exit code 43

- lib/chef/knife/config_get.rb
- lib/chef/knife/config_get_profile.rb
- lib/chef/knife/config_list.rb
- lib/chef/knife/config_list_profiles.rb
- lib/chef/knife/config_show.rb
- lib/chef/knife/config_use.rb
- lib/chef/knife/config_use_profile.rb
Walkthrough knife config found this improvement would add value so modified current knife config subcommand.
```
bundle exec knife config -h
** CONFIG COMMANDS **
knife config list (options)
knife config show [OPTION...] (options)
Displays the value of Chef::Config[OPTION] (or all config values)
knife config use [PROFILE]
```
Fixes: #9888
> make 'knife config' options shorter/easier

- Gemfile.lock
- chef.gemspec
- lib/chef/knife/config_list_profiles.rb
- spec/integration/knife/config_list_profiles_spec.rb
Found a place where we can use `tty-table` gem to display the items. The table was manually defined and print output to screen. As we are searching possible replacement of `ui.list` highline with tty-table.
- **There is a minor difference(trailing space) added & two chars "-" got removed with the _provided_ solution.** 
- If the content size is greater than the screen width table got rotated to vertical.
Before Fix:
After Fix:
Somewhat related to https://github.com/chef/chef/issues/9359 & https://github.com/chef/chef/issues/10208
> knife config list-profiles UI with tty-table

- Gemfile
We can invoke bundler from other directories
> Fix dll copying in Gemfile to remove Dir.pwd

- Gemfile.lock
- lib/chef/cookbook/cookbook_version_loader.rb
- lib/chef/encrypted_data_bag_item.rb
- lib/chef/encrypted_data_bag_item/decryptor.rb
- lib/chef/encrypted_data_bag_item/encryptor.rb
- lib/chef/http/decompressor.rb
- lib/chef/provider/package/rubygems.rb
- lib/chef/resource/chef_client_cron.rb
- lib/chef/win32/crypto.rb
- omnibus/Gemfile.lock
> Bump deps and resolve new Chefstyle warnings

- lib/chef/resource/launchd.rb
- spec/unit/resource/launchd_spec.rb
Make sure people give us proper nice values. Also the upper value is 19 not 20.
> Validate nice values in the launchd resource

- lib/chef/resource/chef_client_cron.rb
- lib/chef/resource/chef_client_launchd.rb
- lib/chef/resource/chef_client_scheduled_task.rb
- spec/unit/resource/chef_client_cron_spec.rb
- spec/unit/resource/chef_client_launchd_spec.rb
Unify method names, spec order, and add splay functionality to chef_client_launchd.
> More updates to the chef_client_* resources

- lib/chef/provider.rb
We're requiring these already at the top of the file
> Remove duplicate requires in the Provider class

- Gemfile
- Gemfile.lock
- omnibus/Gemfile.lock
Pull in the latest InSpec + mixlib gems
> Pin Chefstyle + bump all other deps

- lib/chef/knife/ssh.rb
- spec/unit/knife/ssh_spec.rb
Backport of https://github.com/chef/chef/pull/9482
- The knife ssh subcommand “freezes” after printing the name of a remote Windows 2016 host.
Fixes: https://github.com/chef/chef/issues/9447
> Avoid knife ssh freeze on windows

- .expeditor/release.omnibus.yml
- spec/functional/resource/link_spec.rb
- spec/functional/resource/user/dscl_spec.rb
- spec/functional/resource/user/mac_user_spec.rb
- spec/spec_helper.rb
- spec/support/platform_helpers.rb
This backports 3 different changes we made in master to add Big Sur packages.
> Simplify macos platform detection in the specs + add macOS Big Sur testers

- chef-config/spec/unit/config_spec.rb
- lib/chef/application.rb
- lib/chef/deprecated.rb
- lib/chef/knife/core/bootstrap_context.rb
- lib/chef/log/syslog.rb
- lib/chef/resource/chef_client_launchd.rb
- lib/chef/resource/chef_client_systemd_timer.rb
- lib/chef/resource/homebrew_update.rb
- spec/unit/node/immutable_collections_spec.rb
- spec/unit/provider/package/chocolatey_spec.rb
Resolve the issues that pete pointed out plus a few others
> Resolve RuboCop Style/RedundantInterpolation warnings

- lib/chef/provider/user/dscl.rb
- spec/support/platform_helpers.rb
There's no need for match? with regex here.
> Use include? to example strings when we don't need a regex

- spec/unit/data_collector/config_validation_spec.rb
Windows test cases are failing in PR https://github.com/chef/chef/pull/10393
> Mock File.expand_path to fix window C:/ dir appended in absolute path

- Gemfile.lock
- omnibus/Gemfile.lock
Gives us package info on macOS
> Update Ohai to 16.5

- lib/chef/application/knife.rb
- lib/chef/dist.rb
- lib/chef/formatters/doc.rb
- lib/chef/formatters/minimal.rb
- Add dist constants `PATENTS` & `KNIFE_DOCS`
- Add patent info link to chef-client & solo commands.
- Pending to add links to help command.
Fixes: https://github.com/chef/chef/issues/10397
> Add Patents link to chef infra & solo client

- .expeditor/release.omnibus.yml
> Add SLES 15 S390x builds

- RELEASE_NOTES.md
> Add Chef Infra Client 15.14 release notes

- lib/chef/file_access_control/windows.rb
- spec/support/shared/functional/securable_resource.rb
> allow the use of SIDs in windows securable resources

- lib/chef/application.rb
The line of code this comment was describing is gone, but the comment is still here.
https://github.com/chef/chef/commit/3abc3b6625dfca142a5e66c92ab531cc70bad2f9
> Remove an outdated comment.
