lib/chef/node.rb, lib/chef/whitelist.rb, spec/unit/node_spec.rb
looks like these have been broken for some time, the tests were only
testing automatic level (which has no "combined" hash version) and
the specs were injecting a plain old hash, so were failing to catch
this error on multiple different levels.
since the automatic level worked and since mostly people use automatic
blacklisting to remove junk from ohai it was very uncommon to hit
this bug.
closes #6120
=> fix default/override attribute blacklists and whitelists

lib/chef/application/apply.rb, lib/chef/application/client.rb, lib/chef/application/solo.rb, lib/chef/knife/bootstrap.rb
This provides forwards compatibility with the flags we're shipping in
Chef 15 so that someone can upgrade to a new Chef 14 release, add the
flags, then upgrade to Chef 15.
=> Add placeholder license acceptance flags

Gemfile, Gemfile.lock, chef.gemspec, omnibus/Gemfile.lock
Highline 1.7 is out and seems reasonable for our minimal highline usage
Pulling inspec from git for now allows us to use the latest train which allows for the new net-ssh
New net-ssh allows for new key formats
=> Add ed25519 deps, bump highline and net-ssh pins and pull inspec from git

kitchen-tests/Gemfile
=> Use inspec from git in the kitchen CI tests

lib/chef/application.rb, lib/chef/application/windows_service.rb, spec/unit/application_spec.rb, spec/unit/log/syslog_spec.rb, spec/unit/log/winevt_spec.rb
You could interpret this error message in 2 different ways. This makes it super clear we're skipping the config file since we couldn't find it.
=> Improve the error message when no config can be loaded 

kitchen-tests/Gemfile, kitchen-tests/kitchen.travis.yml
update of kitchen end-to-end testing for the modern world
=> Replace kitchen-appbundle-updater in Travis tests with Test Kitchen lifecycle hooks

Gemfile, Gemfile.lock, omnibus/Gemfile, omnibus/Gemfile.lock
We now have a preview of inspec 4 out so we can switch back to gems and kill off the full train gem and all its deps.
=> Switch to inspec/train from gems

lib/chef/application/apply.rb, lib/chef/application/client.rb, lib/chef/application/knife.rb, lib/chef/application/solo.rb, lib/chef/application/windows_service.rb, lib/chef/client.rb, lib/chef/dist.rb, lib/chef/http/http_request.rb, lib/chef/knife.rb, lib/chef/knife/bootstrap/templates/chef-full.erb, lib/chef/run_lock.rb, lib/chef/shell.rb, spec/functional/version_spec.rb, spec/integration/solo/solo_spec.rb, spec/unit/application/client_spec.rb, spec/unit/application/solo_spec.rb, spec/unit/knife_spec.rb
This PR replaces https://github.com/chef/chef/pull/8341 , same stuff, updated with latest information regarding Chef's trademark policy, and moved to a new github org to make collaboration easier.
first steps towards allowing multiple distros of Chef in compliance with the Trademark policy
first steps towards https://github.com/chef/chef/issues/8376
Presented as a user story, it could be defined as "As a Chef community member, I would like to create an OSS `chef-client` distribution in compliance with Chef (the company)'s Trademark policy in a simple, automatable and manageable way. The distribution should be a drop-in replacement for `chef-client`"
=> Add Chef::Dist to abstract branding details to a single location

Gemfile, Gemfile.lock, omnibus/Gemfile.lock
We had to move this out of train as they were causing installation failures for inspec. This change makes sure we get them into our omnibus package.
=>  Move ed25519 gems into omnibus

lib/chef/provider/windows_task.rb, lib/chef/resource/windows_task.rb, spec/functional/resource/windows_task_spec.rb, spec/unit/resource/windows_task_spec.rb
- Add `start_when_available` option in `windows_task` resource. 
-  `start_when_available` is already avaibale in https://github.com/chef/win32-taskscheduler.
- Add Unit/Functional test cases.
https://github.com/chef/chef/issues/8377
=> windows_task: Add start_when_available support

Gemfile.lock, chef.gemspec, lib/chef.rb, lib/chef/knife/bootstrap.rb, lib/chef/knife/bootstrap/train_connector.rb, spec/support/shared/integration/integration_helper.rb, spec/unit/knife/bootstrap/train_connector_spec.rb, spec/unit/knife/bootstrap_spec.rb
This removes chef-core from bootstrap and replaces it with direct usage of train.
=> Implement bootstrap directly with train

lib/chef/knife/core/bootstrap_context.rb, lib/chef/knife/core/windows_bootstrap_context.rb, spec/unit/knife/core/bootstrap_context_spec.rb, spec/unit/knife/core/windows_bootstrap_context_spec.rb
When performing the initial `chef-client` converge
on a bootstrapped host, ensure that we set the license
environment variable that indicates the license was accepted.
This will allow the run to continue under Chef 15, which requires
license acceptance.
I used the environment variable instead of the CLI flag
because older versions of Chef do not support the CLI flag.
=> Enable license acceptance during bootstrap 

chef-universal-mingw32.gemspec
these are moved to chef-bin now.
it looks like these were always duplicated in the chef.gemspec and
probably unnecessary anyway?
=> remove windows executables from windows gemspec

lib/chef/knife/core/windows_bootstrap_context.rb
This change fixes the error coming while using knife bootstrap winrm with --msi-url opition. 
Ref https://github.com/chef/knife-windows/blob/master/lib/chef/knife/core/windows_bootstrap_context.rb#L304
#8434
=> Fixed bootstrap error while using --msi-url option with knife bootstrap winrm

Gemfile
this file winds up in the embedded lib at:
/opt/chef/embedded/lib/ruby/gems/x.y.0/gems/chef-X.Y.Z/Gemfile
It needs to find the chef-bin gem from the same library, rather than
simply omitting it.
The chef-config gem comes in through the chef.gemspec so the lines are
different.
=> fix chef-bin bundling in omnibus

lib/chef/provider/file.rb, lib/chef/win32/file.rb, spec/support/shared/unit/provider/file.rb
In the event you are managing a file `/etc/file` with a `file` resource,
but it turns out to be a link to `/etc/passwd` and you are trying to figure
out what overwrite `/etc/passwd`, there is no indication in the logs. Let's add
one.
=> file: Tell people what file a link is pointing at in warning messages

lib/chef/knife/bootstrap.rb, spec/unit/knife/bootstrap_spec.rb
Fixed incorrect option mapping where deprecated flags
would have a 'long' taken from the replacement flag. This caused 
mixlib-cli to duplicate the `long` flag - which caused lots of 
assignment confusion, including warning the operator about using flags they never used. 
This also updates the behavior in case of conflicting flags
(for example --ssh-user and --connection-user) to raise an error 
instead of choosing which one to use.This seems less likely to surprise.
Renamed deprecation variables and methods for readability/consistency.
Fixes #8422
=> [CHEF-8422] Fix incorrect deprecation warnings

.expeditor/verify.pipeline.yml, .travis.yml, Gemfile, Gemfile.lock, appveyor.yml, omnibus/Gemfile.lock
These were used by our maintainer rake tasks. These are all gone now so there's no need for these gems.
=> Remove old maintainer gems from the Gemfile

.travis.yml
We're not going to see a release of halite that works with modern Chef
releases. We're just consuming a slot of Travis for this to fail each
run.
=> Remove poise halite testing from Travis

ci/verify-chef.bat, ci/verify-chef.sh
we need to bundle install now in both places (ChefDK style of
appbundling means there is no Gemfile.lock here and we do the
install against the somewhat novel-looking Gemfile that kinda
looks like Gemfile.lock).
and on windows side since there is no Gemfile.lock any more we need
to avoid that test.
=> update the ci verify tasks for chef-15

lib/chef/dist.rb, lib/chef/formatters/doc.rb, lib/chef/formatters/error_inspectors/api_error_formatting.rb, lib/chef/formatters/minimal.rb, lib/chef/knife.rb, lib/chef/knife/bootstrap.rb, lib/chef/run_lock.rb, spec/integration/solo/solo_spec.rb, spec/unit/knife_spec.rb
Signed-off-by: Tensibai <tensibai@iabis.net>
Replace products reference by its constant in chef/dist.rb. 
Makes replacing the brand for other distribution easier by replacing hard coded string by corresponding constant in the file chef/dist.rb.
Voluntarily not changing the unit tests not documentation at this point.
In line with #8376
=> Replace Chef Client by its constant in Chef::Dist

lib/chef/knife/bootstrap.rb, lib/chef/knife/bootstrap/train_connector.rb, spec/unit/knife/bootstrap/train_connector_spec.rb, spec/unit/knife/bootstrap_spec.rb
This PR corrects two problems found in #8432: 
1. when protocol was not given in the URL (winrm://hostname) set the default protoocol - even if '-o' was given - because it was lost in incorrect order of operations. 
2. when a `TrainConnector#connect!` failed, if protocol was not `ssh` we would  would receive undefined constant `Net::SSH` - we check for a specific `Net::SSH` exception, but if we don't hit ssh path in train `net/ssh` is not loaded. 
3. In addition, it cleans up TrainConnector a bit: 
* remove `#test_instance` -- we can do the same setup in tests
* finish moving config setup to a lazy load 
* Naming was made more consistent within the module 
* Removed a couple helper methods that didn't make sense anymore
* add yard doc
#8432
=> [CHEF-8432] Ensure default protocol is used properly. Use correct 'require' before accessing Net::SSH constants.

lib/chef/knife/core/status_presenter.rb
Signed-off-by: Vijay Mali <vijay.mali@msystechnologies.com>
Fixed blank output for knife status with long output option
It displays the output in following format.
```
$ knife status -l --run-list
vm-1, ubuntu, 192.168.102.190, [], ubuntu 16.04.
vm-1, ubuntu, 192.168.102.190, ["recipe[apt]"], ubuntu 16.04.
vm-1, ubuntu, 192.168.102.190, ["recipe[apt]", "recipe[nginx]"], ubuntu 16.04.
```
https://github.com/chef/chef/issues/7764
=> Fixed empty value for knife status long output

lib/chef/run_context/cookbook_compiler.rb, spec/data/run_context/cookbooks/dependency1/attributes/unparsed_file, spec/data/run_context/cookbooks/dependency1/definitions/unparsed_file, spec/data/run_context/cookbooks/dependency1/libraries/unparsed_file, spec/data/run_context/cookbooks/dependency1/providers/unparsed_file, spec/data/run_context/cookbooks/dependency1/recipes/unparsed_file, spec/data/run_context/cookbooks/dependency1/resources/unparsed_file, spec/unit/run_context/cookbook_compiler_spec.rb
Fixes #6281 which is a frequently reported issue where md files and swap
files and other junk causes the cookbook compiler to barf.
=> Chef-15: cookbook compiler should parse only .rb files

RELEASE_NOTES.md, lib/chef/knife.rb, lib/chef/knife/bootstrap.rb, lib/chef/knife/bootstrap/templates/chef-full.erb, lib/chef/knife/core/bootstrap_context.rb, lib/chef/knife/core/windows_bootstrap_context.rb, spec/unit/knife/bootstrap_spec.rb, spec/unit/knife/core/bootstrap_context_spec.rb, spec/unit/knife/core/windows_bootstrap_context_spec.rb, spec/unit/knife_spec.rb
Bootstrap prerelease support was originally removed after
discussion in community slack, but it turns out to have a little more 
utility than we thought at the time. When enabled, it will cause the 
package to be downloaded from the `current` channel - the latest by default,
but otherwise the specified `--bootstrap-version`.
`Knife#config_source` has been updated to not use a separate hash to store config sources,
and now knows about `:cli_default` value source, which maps to defaulted CLI options that are not in config or used on the CLI by the operator.  This was necessary to prevent `knife bootstrap` from thinking that `--channel` had been set by the operator when it only had a default value.
The CLI flag is now `--channel CHANNEL`; `--prerelease` has been deprecated. If use, will set …
=> Restore bootstrap pre-release support

lib/chef/dsl/data_query.rb, lib/chef/dsl/recipe.rb, lib/chef/dsl/universal.rb
Move the data_query, powershell and registry_helper DSLs up to universal.
Move the `tagged?` helper into data_query for organizational purposes.
closes #8356
=> Move more DSL helpers into universal so they're available everywhere

Gemfile.lock
This corrects CHEF-4823 by upgrading train-core to a version
with support for detecting windows over ssh.
[chef/8423](https://github.com/chef/chef/issues/8423)
[train/416](https://github.com/inspec/train/pull/416)
=> [CHEF-8423] Upgrade train-core to 2.1.0 for windows detection over ssh

Rakefile
We should probably push all the travis tests through the rakefile at
some point and centralize this, and make rake the entrypoint which
sets the env var, but we'd need rake tasks for the external and
kitchen tests.
=> Accept-no-persist the license in the Rakefile

lib/chef/knife/client_create.rb, spec/unit/knife/client_create_spec.rb
We've already removed the other support for setting up users on a Chef 11 server. This just further drops support for old Server installs.
=> Remove the Chef 11 admin flag from knife client create

lib/chef/provider/package.rb, lib/chef/provider/package/apt.rb, lib/chef/provider/package/deb.rb, lib/chef/provider/package/dpkg.rb, lib/chef/resource/apt_package.rb, lib/chef/resource/dpkg_package.rb, lib/chef/resource/package.rb, spec/data/cookbooks/irssi/files/default/irssi.response, spec/data/cookbooks/wget/files/default/wget.response, spec/support/shared/unit/provider/package/package_shared.rb, spec/unit/cookbook_loader_spec.rb, spec/unit/provider/package/apt_spec.rb, spec/unit/provider/package/deb_spec.rb, spec/unit/provider/package/dpkg_spec.rb, spec/unit/provider/package_spec.rb, spec/unit/resource/apt_package_spec.rb, spec/unit/resource/dpkg_package_spec.rb, spec/unit/resource/package_spec.rb
- Moved `response_file` and `response_file_variables` properties from `package` resource to `apt_package` and `dpkg_package` resources
- Created a `Chef::Provider::Package::Deb` module for `apt` and `dpkg` providers and included it into Apt and Dpkg classes which are the sub-classes of the Package class, and also moved common methods of `apt` and `dpkg` providers in `Chef::Provider::Package::Deb`
Fixes #7599 MSYS-986
=> package: move response_file and response_file_variables out of base package resource

lib/chef/deprecated.rb, lib/chef/node_map.rb, lib/chef/resource.rb, spec/unit/node_map_spec.rb, spec/unit/resource_spec.rb
Switch to only doing warnings.  Remove the features in the node_map that
we never used.
=> Remove resource collision deprecations

lib/chef/knife/bootstrap/templates/windows-chef-client-msi.erb
Under Chef 14 bootstrap, creation of directories
that already existed in Windows would log an error,
but not raise an error.
With the Chef 15 bootstrap change to run the bootstrap
script under powershell, any error in the script now causes
an error to be raised up. Even though the bootstrap complets
successfully - the script execution does not halt on error -
it presents a confusing error to the human that makes it look like
bootstrap failed.
Fixes #8469 
=> Check for directories on Windows before creating

lib/chef/dsl/universal.rb, lib/chef/guard_interpreter/default_guard_interpreter.rb, lib/chef/mixin/train_or_shell.rb
The train_or_shell mixin should mixin its dependent mixins and
require them, which removes the need to do that in the calling classes.
Include TrainOrShell correctly in the Universal DSL.
Few more code tweaks ("protected" is largely worthless in ruby and was
always being misused here).
=> Target mode code tweaks

lib/chef/knife/core/bootstrap_context.rb, lib/chef/knife/core/windows_bootstrap_context.rb
- Fix syntax error raised due to while adding `chef_license` acceptance in client.rb new line is missing. 
https://github.com/chef/chef/issues/8495
=> Chef 15: FATAL: Configuration error SyntaxError in client.rb during bootstrap

omnibus/config/projects/chef.rb
The resulting distribuions are licensed under the Chef EULA.
=> Update the omnibus build license to the Chef EULA

.expeditor/config.yml, .expeditor/update_dep.sh
This should still get us an update without removing the lockfile first which resulted in the new file being written out as a Bundler 2.x file.
=> Switch expeditor gem updating to use bundle lock

lib/chef/win32/security.rb, spec/unit/win32/security_spec.rb
- In `lookup_account_name` method, whenever `FFI::LastError.error` returns 0, on that time we are geting an exception like ` Chef::Exceptions::Win32APIError: The operation completed successfully.`
- Added a private method `error_insufficient_buffer` in `Chef::ReservedNames::Win32::Security` for handling this exception
- Added unit test cases for this
Fixes:
https://chefio.atlassian.net/browse/MSYS-996
https://getchef.zendesk.com/agent/tickets/21641
=> Fix for Chef::Exceptions::Win32APIError: The operation completed successfully.

lib/chef/knife/bootstrap/templates/chef-full.erb, spec/unit/knife/bootstrap_spec.rb
The bootstrap script is explicitly using /bin/sh.
On some solaris servers the version of /bin/sh exporting environment variables
using "export id=value" fails. The form "id=value export id" does work.
Bootstrap fails when the wrong form is used.
knife bootstrap fails. The shell command creates uses a form of the export command that isn't supported by old /bin/sh programs.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have run the pre-merge tests locally and they pass.
- [x ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.
- [x ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-o …
=> Use exports compatibile with /bin/sh in the bootstrap script

kitchen-tests/kitchen.yml
This way we know what version we started with and confirm we end up with
the right version
=> Add chef version debug info in the kitchen tests

lib/chef/knife.rb, spec/unit/knife_spec.rb
This moves initialization of @original_config out of
merge_configs and into the constructor.
A common access pattern running knife commands directly in code is:
cmd = KnifeCommand.new
cmd.config[:something] = value
cmd.run
This bypasses the `Knife.run` class method, which does extra config
initialization - including `merge_configs`.
With this change,  `config_source` will now return `nil` as the
source instead of exploding when `merge_configs` is bypassed. 
* Fixes https://github.com/chef/knife-ec2/issues/567
* Fixes https://github.com/chef/knife-google/issues/145
* Replaces https://github.com/chef/chef/pull/8494
=> [knife-ec2-547] Update config_source to support using knife classes without requiring merge_config

Gemfile.lock, omnibus/Gemfile.lock, omnibus_overrides.rb
This prevents us installing 1.17.3 in addition to 1.17.2. This *should* reduce the overall size of the install and prevent double gems. I'm waiting on an adhoc to see how this works out.
=> Pin bundler to 1.17.2 which is included in Ruby 2.6

RELEASE_NOTES.md, lib/chef/knife/bootstrap.rb, spec/unit/knife/bootstrap_spec.rb
Fixes #8482 by prompting to continue if the host key is not recognized.
This attempts to tell Net:SSH to accept and write the key but it is only
temporarily accepting.
This changes the parameters of --ssh-verify-host-key (which is new) to
take the Net::SSH values, which get passed through by train. This allows
the user more options than only verifying or not.
=> Use new Net:SSH host key verify values

lib/chef/knife/bootstrap.rb, spec/unit/knife/bootstrap_spec.rb
- Added bootstrap option `--session-timeout`.
- Added `--winrm-session-timeout` to deprecations.
- Default --session-timeout value is 60 secs(same was added for `--winrm-session-timeout`).
- Modified existing specs related to old `--winrm-session-timeout` key and add specs for `--session-timeout`.
- To fix `ERROR: TypeError: can't convert String into time interval` parse it to `to_i`. (Float not supported on terminal `ssh user@host -o 'ConnectTimeoit=14.5'` raise error `invalid time value`  )
https://github.com/chef/chef/issues/8491
=> Chef 15: Add --session-timeout bootstrap option for both ssh & winrm

lib/chef/resource/windows_dfs_folder.rb, lib/chef/resource/windows_dfs_namespace.rb, spec/unit/resource/windows_dfs_folder_spec.rb, spec/unit/resource/windows_dfs_namespace_spec.rb
We're creating these dfs shares so it makes a lot more sense to make the action create. This is probably what people using Chef would expect.
=> Rename the windows_dfs :install actions to :create

.expeditor/config.yml
Angrychef 15.0.293 never built so we can't properly promote chef right
now and we're in a half released state. This hopefully gets us out of
it.
=> Take angrychef out of the expeditor config

.expeditor/config.yml
These aren't working at the moment on N-1 branches.
=> Turn off version bump subscriptions

.expeditor/config.yml
Hab builds failing prevents rubygems from promoting right now.
=> Enable angrychef again, but disable hab builds

.expeditor/config.yml
Releng has decided it's best to stop building/promoting AngryChef right
alongside Chef for a number of reasons:
* Increases the fragility of the pipeline and requires a Chef build to
pass on the already large platform matrix times 2.
* AngryChef builds will not be required in our new Buildkite based
pipeline as Chef is not used to manage the underlying instances in the
elastic queues.
We just built/promoted AngryChef 15.0.293 out of band and will continue
to do this if future AngryChef builds are required.
=> Disable AngryChef builds and promotions

habitat/plan.sh
This updates the dependencies to explicitly use `core/ruby26`, rather than `core/ruby.` At the time of this PR `core/ruby` is still tracking 2.5 and _may_ move ahead before chef-client is ready to consume new releases of Ruby. 
I've also included `chef-bin` in the copied directories in order to get the `bundle install` to function. 
Closes #8542
=> Update habitat/plan.sh to allow building of Chef Infra Client 15

lib/chef/application/apply.rb, lib/chef/application/solo.rb
You could accept the license interactively but you could not do it via
the CLI flag
=> Add license CLI options to chef-apply command

lib/chef/knife/bootstrap.rb, spec/unit/knife/bootstrap_spec.rb
This will allow bootstrap to work with systems
that have `requiretty` configured, and is consistent
with the behavior of Chef 14 bootstrap
=> Enable pty for bootstrap ssh

lib/chef/knife/bootstrap.rb, spec/unit/knife/bootstrap_spec.rb
We should only set bootstrap_context.client_pem if we're a validatorless
bootstrap.
Fixes #8534
=> Only set client_pem in bootstrap_context when validatorless

chef-config/lib/chef-config/config.rb, chef-config/lib/chef-config/exceptions.rb, chef-config/lib/chef-config/fips.rb, chef-config/lib/chef-config/mixin/credentials.rb, chef-config/lib/chef-config/mixin/dot_d.rb, chef-config/lib/chef-config/path_helper.rb, chef-config/lib/chef-config/workstation_config_loader.rb
does the same fixing of require_relative and manual idempotency checking
that has been applied to the chef gem
=> Fix chef-config requires lines

lib/chef/train_transport.rb, spec/unit/train_transport_spec.rb
Changes the target mode error in the case of no creds at all to:
```
FATAL: ArgumentError: Credentials file specified for target mode does not exist: '/Users/lamont/.chef/credentials'
```
From:
```
[2019-05-20T17:30:41-07:00] FATAL: NoMethodError: undefined method `[]' for nil:NilClass
```
=> Better target mode no-creds errors

lib/chef/resource_collection.rb, spec/unit/resource_collection_spec.rb
with multiple providers
Fixes: https://github.com/chef/chef/issues/6158
Then a resource with multiple providers (e.g. package) is used, delete_resource doesn't work.
https://github.com/chef/chef/issues/6158
=> Fix delete_resource for resources

lib/chef/provider/service/insserv.rb, spec/functional/assets/inittest, spec/functional/resource/insserv_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb, spec/unit/provider/service/insserv_service_spec.rb
For service resource `action: enable` is not idempotent in case of `SLES v11` because it uses `insserv` for system initialization. Service runlevels in SLES resides inside `rc.d` directory which was missing in conditional.
With this change `action :enable` is idempotent so there is no deviation to enable the service for each chef-client run. 
fixes https://github.com/chef/chef/issues/6870 and https://getchef.zendesk.com/agent/tickets/21373
```
package 'ntp'
service 'ntp' do
action [:enable, :start]
end
```
In kitchen test I've used : 
```
multiple_converge: 2
enforce_idempotency: true
```
to ensure idempotency.
```
PS E:\Backup\Project\Chef_Repo\sap_ntp> kitchen converge
-----> Starting Kitchen (v1.24.0)
WARN: Unresolved …
```
=> Fix service enable idempotency in sles11

lib/chef/run_context.rb
We need to save the train connection object as that represents the ssh
connection that we want to reuse.
Fixes #8579
=> Preserve train connection in target mode to prevent running duplicate OS detection commands

lib/chef/mixin/which.rb
bit hacky since we're only testing the global execute-bit but doing this right will require porting File.executable? to work correctly in train and more or less copying
the logic in ruby's file.c to work across a train connection (which requires figuring out geteuid()/getegid()/getuid()/getgid() across a train connection which is "lolno" right now).
=> make which/where be target-mode aware

lib/chef/provider/launchd.rb, lib/chef/resource/launchd.rb
Adding support for the LaunchEvents key in launchd. From `man launchd.plist`:
```
LaunchEvents <dictionary of dictionaries of dictionaries>
Specifies higher-level event types to be used as launch-on-demand event sources.  Each sub-dictionary defines events for a particular event subsystem, such as "com.apple.iokit.match-ing", which can be used to launch jobs based on the appearance of nodes in the IORegistry. Each dictionary within the sub-dictionary specifies an event descriptor that is specified to each event subsystem. With this key, the job promises to use the xpc_set_event_stream_handler(3) API to consume events. See xpc_events(3) for more details on event sources.
``` 
Allows for having a LaunchDaemon with something like the following
```
<key>LaunchEvents</key>
<dict> …
```
=> launchd: add launch_events property

lib/chef/knife/bootstrap.rb, spec/unit/knife/bootstrap_spec.rb
Correct the order of `connection` before `registration`
Updates order of `connection`  before `registration` for any node, Ensures the `connection` object to be live.
Fixes https://github.com/chef/knife-ec2/issues/579
=> Chef 15: Fix order of connection before registering node

lib/chef/knife/bootstrap.rb
As per the release note, we have following deprecated options:
| Flag        | New option |
| ------------- |:-------------:|
| --forward-agent | --ssh-forward-agent
| --ssh-port | --connection-port 
| --winrm-ssl-verify-mode MODE | --winrm-no-verify-cert 
| --winrm-transport TRANSPORT | --winrm-ssl 
These options must be properly added to deprecated flags.
https://github.com/chef/chef/issues/8572
=> Chef-15: Add missing deprecated options

lib/chef/mixin/shell_out.rb
be a bit less lazy.
but ultimately train's run_command should take *args
=> Use Shellwords.join in target-mode shell_out

Gemfile.lock, chef-config/lib/chef-config/config.rb, lib/chef/knife/ssh.rb, lib/chef/mixin/shell_out.rb, lib/chef/util/powershell/cmdlet.rb
something is declaring an empty class somewhere and trolling me hard
but ruby makes that near impossible to figure out, so be slightly more
specific by looking for a mixlib-shellout constant
also bumps the gems
=> fix shellout require idempotency and bump gems

lib/chef/provider/log.rb, lib/chef/provider/ruby_block.rb, lib/chef/resource/breakpoint.rb, lib/chef/resource/log.rb, lib/chef/resource/ruby_block.rb
breakpoint and log have to be executed locally so they're safe to run unmodified in target_mode.
ruby_block is superficially debatable since there's the obvious question as to "should it run remotely?"
however there is a simple answer which is "hell no".
we'd have to ship the variable binding to the remote server and then ship it back.
consider:
```ruby
filename = "/etc/passwd"
ruby_block "nuke /etc/passwd because I hate logging into my box" do
block do
FileUtils.rm_rf(filename)
end
end
```
That block can't be eval'd by the local ruby interpreter or you'll nuke /etc/passwd on the local machine you're running on.  If you ship it up to the target host then it'll fail with a NoMethodError on filename.  You'd have to ship the full binding up to a remote instance (even just setting aside the …
=> Enable target mode on ruby_block, log and breakpoint

lib/chef/knife/bootstrap.rb, spec/unit/knife/bootstrap_spec.rb
This fixes the `ssh_user` setting if we provide from CLI rather than on `knife.rb`
-- `config_value` now returns the `ssh_user` value too if set in CLI.
Fixes https://github.com/chef/knife-ec2/issues/574
=> Chef 15: Fix ssh user set from cli

lib/chef/mixin/template.rb, spec/data/templates/failed.erb, spec/unit/mixin/template_spec.rb
While Chef already implements a nice amount of information
in `TemplateError#to_s`, when using ChefSpec with RSpec, the `#to_s`
is not called, leaving us with no source information for template
errors.
By adding the filename to `Erubis::Eruby` initialization, we can get
a better backtrace that will show up in RSpec output.
#8561
=> Improving error handling for template render

lib/chef/provider/file.rb, lib/chef/win32/file.rb, spec/support/shared/unit/provider/file.rb
In the event you are managing a file `/etc/file` with a `file` resource,
but it turns out to be a link to `/etc/passwd` and you are trying to figure
out what overwrite `/etc/passwd`, there is no indication in the logs. Let's add
one.
=> Tell people what file a link is pointing at.

lib/chef/dsl/data_query.rb, lib/chef/dsl/recipe.rb, lib/chef/dsl/universal.rb
Move the data_query, powershell and registry_helper DSLs up to universal.
Move the `tagged?` helper into data_query for organizational purposes.
=> Move the data_query, powershell and registry_helper DSLs up to universal

Gemfile, Gemfile.lock
The gem isn't loading correctly on the windows hosts.
=> Pin ruby_prof to < 0.18 to prevent appveyor failures

lib/chef/provider/cron.rb, spec/unit/provider/cron_spec.rb
- Added unit test cases
- Ensured chefstyle
- Added a warning in case user is using a `environment` for an entry that can also be specified as a `property`
- Revert changes in order to pass chefstyle
- Added a warning in case user is using a `environment` for an entry that can also be specified as a `property`
- Added these changes in cron_different? method
- Added unit test cases
- Added some changes in cron.rb
- It now throws error if user passes both environment with the {:SHELL, :HOME, :PATH, :MAILTO} and these properties itself.
- It maintains idempotency.
- Added Rspecs for this case.
- Ensured chef-style.
Signed-off-by: vijaymmali1990 <vijay.mali@msystechnologies.com>
=> Fix for cron resource get confused by environment/property mismatch

lib/chef/knife/bootstrap.rb
We're currently logging the directory we found the bootstrap template
in, but not actually the name of the file that we've chose. Minor change
to fix that.
=> Trace output the actual bootstrap template filename

lib/chef/knife.rb, spec/unit/knife_spec.rb
Fixes #8433
When we added trace this check wasn't changed, which means you only saw
the stacktrace for 2 (-VV) but not for 3 (-VVV)
=> Raise knife exceptions when verbosity is 3 (-VVV)

lib/chef/knife/bootstrap.rb
Most cloud plugins override #run today because they have additional
steps, such as being able to create an instance in the cloud before we
bootstrap it. This means it's easy for them to get out of sync.
This is a proposal for some hooks that enable better code reuse.
=> Add hooks for plugins in knife bootstrap

lib/chef/knife/bootstrap/train_connector.rb, spec/unit/knife/bootstrap/train_connector_spec.rb
Tempfile will create a file with CRLF on Windows, which when we upload to a
linux system then cannot be executed because of the line endings. Setting to
binmode prevents this.
Fixes chef/knife-ec2#580
=> Create bootstrap template in binmode to fix line endings

lib/chef/application.rb, lib/chef/application/client.rb, lib/chef/application/solo.rb, lib/chef/dist.rb, lib/chef/encrypted_data_bag_item.rb, lib/chef/knife/bootstrap/templates/chef-full.erb, lib/chef/knife/configure.rb, lib/chef/knife/core/bootstrap_context.rb, lib/chef/resource/breakpoint.rb, lib/chef/shell.rb, lib/chef/shell/ext.rb, lib/chef/shell/shell_session.rb, lib/chef/train_transport.rb, spec/integration/client/exit_code_spec.rb
Signed-off-by: Marc Chamberland <mchamberland@pbsc.com>
Another batch of distro constant changes. Mostly `chef-shell` and `/etc/chef` related, plus a few missed references of other wordmarks.
This brings us a bit closer to easily configurable distribution names.
=> more distro constants

.expeditor/verify.pipeline.yml
Use the minimal container for the chefstyle tests
Remove extra env vars that were for travis
Exclude gem groups we don't care about
Parallelize the bundler commands
=> Speed up buildkite tests

.expeditor/verify.pipeline.yml, tasks/bin/run_external_test
Switch more things over to the ruby containers which pull a minute faster
Remove more env vars that we used for naming in Travis
Simplify our bundler commands
Remove the Ruby version from the dokken commands since this will change any time the default ruby changes.
=> More speedups to the Buildkite PR verification tests

Gemfile.lock, chef.gemspec, lib/chef/knife/bootstrap.rb, spec/unit/knife/bootstrap_spec.rb
Deprecation logic is now available in `mixlib-cli`
via `deprecated_option`.  Let's use that instead
of keeping our custom deprecation behavior.
=> use mixlib-cli's deprecation mechanism

.expeditor/config.yml
Released to stable is what we care about not Rubygems
=> Update the changelog to not mention Rubygems

Gemfile, Gemfile.lock
We need to add the inspec-core-bin now that the binaries aren't part of
the inspec-core gem.
Fixes https://github.com/chef/chef/issues/8652
=> Make sure to ship the inspec binary

habitat/config/client.rb, habitat/default.toml, habitat/hooks/run
* Add in License Acceptance for Chef 15.
* Make package more flexible for running chef-client in alternative models.
Signed-off-by: Nathan Cerny <ncerny@gmail.com>
Adds in license acceptance by creating a config value in habitat, that passes the acceptance in to the command line in the run hook.
Adds in flexibility to the habitat build:
* Calls chef-client (with local_mode defined as a configurable) instead of chef-solo
* Allows overriding of the configuration file, to allow running in "hybrid" models, giving customers a migration path to fully effortless.
=> Update Habitat Build

lib/chef/mixin/shell_out.rb, lib/chef/mixin/train_helpers.rb, lib/chef/node_map.rb, lib/chef/platform/service_helpers.rb, lib/chef/provider/service/systemd.rb, lib/chef/resource/service.rb
Makes it so that local cookbook can bounce a remote service over
train/ssh/whatever.  Works at least for ubuntu.
Introduces a fairly rudimentary TrainHelpers class, using some
inspiration from ohbye.
=> Target mode for systemd service helper

Gemfile.lock, omnibus/Gemfile.lock
We need the updated appbundler definition with the correct license file.
=> Update omnibus-software to unbreak chef builds

docs/dev/how_to/updating_chef12.md
My vision for this is that it is the actual in-the-trenches guide to process and gotchas and the questions that everyone hits.  Not necessarily a wall of words on every last deprecation message no matter how small.
Also punting entirely on the question of what about chef-13 and now chef-14.  Chef-12 is the big pain point, so I don't care about upgrading from 13 and 14 right now.  We need people off 12.  We can reorganize the docs later when focus shifts.
=> Add Chef 12 updating docs

lib/chef/data_collector.rb, lib/chef/data_collector/config_validation.rb, spec/unit/data_collector_spec.rb
This works better as part of the module that handles all the config
wrangling.  It isn't central to the data_collector operation itself.
=> Move the data collector should_be_enabled? check

.expeditor/release.omnibus.yml, omnibus/omnibus-test.ps1, omnibus/omnibus-test.sh
This PR does NOT migrate omnibus builds to buildkite. That will be done in a subsequent PR after final tests of the buildkite pipeline are completed.
This PR enables all platforms in omnibus buildkite pipeline and ports appropriate functionality from `ci/verify-chef.*` scripts to the new `omnibus/omnibus-test.*` scripts.
=> Improvements to omnibus buildkite pipeline

.bldr.toml, habitat-packages/.bldr.toml
Signed-off-by: echohack <echohack@users.noreply.github.com>
I think this works? I used https://expeditor.chef.io/docs/integrations/habitat/ as a reference.
=> [chef-client] [scaffolding-chef] add new build configuration for scaffolding-chef

omnibus_overrides.rb
This is a really small release with just a few minor bugfixes and a
giant pile of fixes to their test / ci setup.
=> Update Rubygems to 3.0.4

Gemfile, Gemfile.lock, omnibus/Gemfile.lock
ruby-prof 0.18 fails to load on Windows. See https://github.com/ruby-prof/ruby-prof/issues/255
=> Pin to ruby-prof 0.17

lib/chef/knife/bootstrap/train_connector.rb, spec/unit/knife/bootstrap/train_connector_spec.rb
Signed-off-by: sawanoboly <sawanoboriyu@higanworks.com>
When using the sudo option, bootstrap may fail. Since pty is enabled in the SSH connection, the path acquisition of temp_dir does not work well when stderr contains unnecessary output.
for example
```
$ sudo mktemp -d
sudo: unable to resolve host hostnamelocalhost  # << this message outs on stderr but merged into stdin due to pty is true
/tmp/tmp.FgLKVeE87G
```
This PR is changed to use only the last line to ignore such output.
none.
=> Ignore noisy outputs at create temp_dir during bootstrap

lib/chef/resource/chocolatey_source.rb, spec/unit/resource/chocolatey_source_spec.rb
This provides the ability to set additional properties for a Chocolatey
source with properties `admin_only` and `allow_self_service`.  As well
as the ability to enable/disable a source.
https://github.com/chef/chef/issues/8634
=> chocolatey_source: Add additional actions and propereties for configuring sources

lib/chef/provider/package/yum/yum_helper.py
Add more careful exception handling around always closing the rpm database.
Convert some of the hard exits to just raise and then use a finally block to close the rpm database if it is open.
Tested this manually through exercising some of the exceptions (bad json and bad command).
Very difficult to create a test case which exercises this code in CI.
Closes #8515
=> yum_package: Better handle yum exceptions in our helper so we always close the rpmdb

.expeditor/config.yml
We have a working habitat build.
=> Enable Habitat build promotion in Expeditor again

lib/chef/resource/hostname.rb
Fix this so we can fix the docs site
=> Fix a typo in the hostname resource property descriptions

lib/chef/provider/package/yum.rb
When working with custom repo that are disabled by default, we need to enable them on-demand. The python helper handles that properly but the yum package provider does not pass user's options in all cases.
Most of the time there is no issue because in normal cases you should not need to enable any repository to work with "installed" packages.
However in some rare cases, you may have multiple installed versions of a given package. In that situation, python libraries used by the helper will do some extra work that may (will) requires to enable the repo.
See call to _compare_providers in http://yum.baseurl.org/download/docs/yum-api/3.2.27/yum-pysrc.html#YumBase._bestPackageFromList
Not passing the options in that case, will result in an unclear error:
> ' * No candidate version available for …
=> Pass yum_package options to underlying python helper

lib/chef/provider/windows_task.rb, spec/unit/provider/windows_task_spec.rb
As per the docs https://docs.chef.io/resource_windows_task.html. `day` can be an integer as well as a string value. But while setting `day: 1` as an integer it raises an error NoMethodError: undefined method `split' for 1:Integer.
To fixed this parse `day` value `to_s` first and then call `split`.
Fixed https://github.com/chef/chef/issues/8431
=> windows_task: Fix for :day option is not accepting integer value

.bldr.toml
The table name in `.bldr.toml` apparently needs to match the package name being built. 
This should fix package promotion from unstable->current in expeditor, too.
- ~Bug fix (non-breaking change which fixes an issue)~
- ~New feature (non-breaking change which adds functionality)~
- ~Breaking change (fix or feature that would cause existing functionality to change)~
=> update bldr config with new hab package name

.expeditor/config.yml
Need to get debug level output from the actual omnibus builds so that we can grep and see e.g. which step is installing which gems...
=> expeditor/buildkite: turn on debug level for builds

lib/chef/resource/apt_repository.rb, lib/chef/resource/chef_handler.rb, tasks/docs.rb
Add examples in markdown to the resources. We'll be using this on the
docs site in the future and if we need to display it we can use
tty-markdown which does a really nice job of displaying markdown in the
terminal
=> Add examples to the apt_repository resource

omnibus_overrides.rb
This is a bugfix only release.
=> Bump openSSL to 1.0.2s

lib/chef/mixin/params_validate.rb
The RDoc for `Chef::Mixin::ParamsValidate#validate` appears to have inadvertently copied the (helpful) inline pseudocode of the `:is` option to the `:equal_to` option (in commit 28f17b36a9d041be8ed50e20ae06fa5f5ea1fb38):
https://github.com/chef/chef/blob/6bbf42b0ff11eabdb72067e78e4101ad93820b71/lib/chef/mixin/params_validate.rb#L43-L45
Quick edit for obvious fix of documentation typo :)
=> Fix RDoc copy-pasta in Chef::Mixin::ParamsValidate#validate

omnibus/omnibus-test.sh
we've never wired up the symlinks, they should be owned by the
inspec package instead.  we require these to exist though and this
catches if inspec-core-bin slips out of the installed gemfile.
=> only check for the embedded/bin/inspec file being there

lib/chef/resource/kernel_module.rb, spec/unit/resource/kernel_module_spec.rb
This allows inspec kernel_module be_disabled to work
Add's disable method which matches inspec test
N/A
=> Implement disable for disabling kernel_modules

omnibus/Gemfile.lock
* bzip2recover: Fix use after free issue with outFile (CVE-2016-3189)
* Make sure nSelectors is not out of range (CVE-2019-12900)
=> Update bzip2 from 1.0.6 -> 1.0.8 to resolve CVEs

lib/chef/resource_reporter.rb, spec/unit/resource_reporter_spec.rb
Somehow this got converted to a bare integer in Chef-15 refactoring
which causes the server-side to reject it, so reverting back to the
old format.
Closes #8532
=> Duration field in resource report needs to be String

lib/chef/data_collector.rb, spec/unit/data_collector_spec.rb
This isn't Java and Net::HTTP can throw a billion things, so just rescue
(nearly) everything.  I have a hard time imagining that there's a
failure here that we wouldn't want to ignore, other than the ones like
OOM thrown by Exception that indicate internal failures.
Also only throw the "this is normal" info message on 404s, other
responses like 500s should be warns even if it is set to ignore
failures (people with data collectors correctly setup need to know about
500s even if we keep going, since that is abnormal).
This also fixes a bug in handling exceptions like Timeout::Error which
do not have a response.code at all which would throw NoMethodError.
closes #8749
=> Tweak data collector exception handling

.expeditor/release.omnibus.yml, omnibus/Gemfile, omnibus/Gemfile.lock
This change only affects CI. A new version of omnibus is required and the artifactory gem is required for the publish part of the build stage. Platform names in `release.omnibus.yml` are also fixed to conform with what the new package publishing code in the omnibus gem expects.
https://github.com/chef/omnibus-buildkite-plugin/issues/22
=> [ci] Fix omnibus pipeline

.expeditor/release.omnibus.yml
As of March 31st 2019, SLES 11 is no longer generally supported. Per our
support process we will no longer officially support SLES 11.
See https://docs.chef.io/platforms.html#platform-end-of-life-policy
=> Stop building Chef Infra Client on SLES 11

lib/chef/provider/package/zypper.rb, spec/unit/provider/package/zypper_spec.rb
Signed-off-by: Jeremy Chalfant <jchalfan@us.ibm.com>
As discussed in https://github.com/chef/chef/issues/4863, `zypper_package` is not upgrading some (or all?) packages in SUSE based systems.
Adding an `out_of_date`  boolean, similar to the `is_installed` variable in the zypper package provider allows the provider to properly detect whether the currently installed package is out of date.
Here's an example of a SuSe 12.3 system before any changes to the zypper package provider:
```
cms3xcfgsles123:~/cheftests # chef-client -v
Chef: 14.12.9
cms3xcfgsles123:~/cheftests # cat /etc/SuSE-release
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 3
cms3xcfgsles123:~/cheftests # cat upgrade.rb
%w(tar krb5).each do |p|
zypper_package p do
action :upgrade
end
end …
```
=> zypper_package upgrade action not working

lib/chef/resource/rhsm_repo.rb, spec/unit/resource/rhsm_repo_spec.rb
- Whenever the user passes `repo_name` as wildcards `*` in the `rhsm_repo` resource, so it didn't work at that time due to the `not_if` block. So we have fixed it.
Fixes #8323
=> Fix for rhsm_repo disable does not support wildcard

lib/chef/knife/bootstrap/train_connector.rb, spec/unit/knife/bootstrap/train_connector_spec.rb
- In order to get rid of `mktemp` use `mkdir` for Linux and Unix host.
- `mktemp` does not exist for AIX host.
- `mkdir` does not return the created path so return the dir itself.
Note: working on to fix `chown: /tmp/chef_Xr0QpL: Operation not permitted.` 
seems run_command! created dir with `root:system` user privileges 
but when ssh login on AIX host and run the same command to created dir it get created with `user:staff` permission.
```
drwxr-xr-x    2 vsingh   staff           256 Aug 06 08:36 chef_Xr0Q
drwxr-xr-x    2 root     system          256 Aug 06 08:35 chef_Xr0QpL
```
Any suggestions would be helpful?
Thanks!
https://github.com/chef/chef/issues/8764
Issue found while creating temp dir https://github.com/chef/chef/blob/3284e9067aacbe42f96afc78b06e523b46b98d2f/lib/chef/knife/boots …
=> Chef-15: Make temp dir using mkdir instead of mktemp

lib/chef/property.rb
The original comparison `value == NOT_PASSED` ends up calling `.<=>` on
`value` under the hood. This relies on the implementation of `<=>`/`cmp`
not being broken in that class.
Unfortunately, some classes like OpenSSL::X509::Name have broken
implementations of `<=>` that raise TypeError instead of returning nil
for mismatched types. https://github.com/ruby/openssl/pull/264
As a result, currently, if you attempt to set a resource property to an
OpenSSL::X509::Name object, the result is a TypeError.
```ruby
>> require 'openssl'
>> require './lib/chef/constants.rb'
>> name = OpenSSL::X509::Name.new
>> name == Chef::NOT_PASSED
TypeError: wrong argument type Object (expected OpenSSL/X509/NAME)
>> Chef::NOT_PASSED == name
=> false
```
With this change, we use the implementation of comparison …
=> Property: Reorder comparison with NOT_PASSED.

lib/chef.rb, lib/chef/decorator.rb, lib/chef/exceptions.rb, lib/chef/nil_argument.rb, lib/chef/node.rb, lib/chef/node/attribute.rb
We have four different versions of this now, and this converts to
just using the one convention in `lib/chef/constants.rb`
Interestingly `Chef::NIL_ARGUMENT` is used nowhere in the codebase, that
probably got refactored out in 12.5.1.
Node objects still use `NIL` but that is a different kind of `Object.new`
which really is semantically private to the implementation of
attributes.
=> Consistently use NOT_PASSED over alternatives

omnibus/omnibus-test.sh
We don't need this fix in `omnibus-test.sh` anymore. We updated the systems we use to run the test and that resolved the issue.
=> [ci] Revert the zypper test failures fix

.expeditor/config.yml
The omnibus pipelines now default to "internal" log level so setting this here is no longer necessary.
=> [ci] Remove explicit debug log level from omnibus pipelines

.expeditor/release.omnibus.yml
As of October 31st 2018, FreeBSD 10 is no longer generally supported. Per our
support process we will no longer officially support FreeBSD 10.
See https://docs.chef.io/platforms.html#platform-end-of-life-policy
It also adds support for FreeBSD 12.
=> Stop building Chef Infra Client on FreeBSD 10

.expeditor/release.omnibus.yml
As of October 31st 2018, FreeBSD 10 is no longer generally supported. Per our
support process we will no longer officially support FreeBSD 10.
See https://docs.chef.io/platforms.html#platform-end-of-life-policy
It also adds support for FreeBSD 12.
=> Stop building Chef Infra Client 14.x on FreeBSD 10

lib/chef/knife/cookbook_metadata_from_file.rb
`file` was missing in `knife cookbook metadata from file FILE` command banner.
- Added `file` in `knife cookbook metadata from file FILE` command banner.
- #8798
=> Updated knife cookbook metadata from file command banner

lib/chef/knife/bootstrap.rb, spec/unit/knife/bootstrap_spec.rb
- Validate only if chef version is less than 15.
- If the chef version is 14 or lower add validation based on bootstrap_version & prerelease.
- PR against chef-14 only.
Referenced PR: https://github.com/chef/chef/pull/8777
https://github.com/chef/chef/issues/8623
=> Chef-14: Raise an error on Chef 14 when trying to bootstrap Chef 15

.expeditor/release.omnibus.yml, omnibus/Gemfile.lock, omnibus/README.md, omnibus/config/projects/chef.rb, omnibus/omnibus-test.sh, omnibus_overrides.rb
Deprecate Ubuntu 14 + SLES 11 in the Chef-14 branch
This PR includes additional changes to fix broken builds on the new queues
https://github.com/chef/release-engineering/issues/607
=> Deprecate Ubuntu 14 + SLES 11

chef-config/lib/chef-config/config.rb, lib/chef/exceptions.rb, lib/chef/provider.rb, lib/chef/resource.rb, lib/chef/resource/resource_notification.rb, lib/chef/resource_collection.rb, lib/chef/run_context.rb, lib/chef/runner.rb, spec/integration/recipes/unified_mode_spec.rb
This is inspired by "use_inline_resources".
Setting `unified_mode false` in a resource would be the existing
behavior with separate compile/converge phases.  This remains the
default.
Setting `unified_mode true` in a resource will eliminate the converge
phase.  Reverse notifications and delayed notifications will still
fire.  The resource action will behave like all resources are executing
at compile time.
As a aside, notifications have never worked for resources firing at
compile time.  This implementation gets that behavior correct so
that notifications will work.
Of course forward notifications to resources not yet declared will not
be possible.
Setting `resource_unified_mode_default true` in `Chef::Config` would
turn off unified mode and turn off the split compile/converge mode for …
=> Add unified_mode for resources

chef-config/lib/chef-config/mixin/credentials.rb
Before:
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-config-15.1.36/lib/chef-config/mixin/credentials.rb:92:in `load_credentials': undefined local variable or method `credentials_file' for #<ChefConfig::WorkstationConfigLoader:0x00007fe01c8321e8> (NameError)
After:
ERROR: CONFIGURATION ERROR:Profile xyz doesn't exist. Please add it to /Users/developer/.chef/credentials.
It looks like this was missed as part of the refactoring in
d730505bb0d53d14c7b005c756ed4993b95fdf94.
Signed-off-by: Andrew Neitsch <andrew@neitsch.ca>
=> Fix crash when showing error about missing profile

lib/chef/provider/ifconfig.rb, spec/unit/provider/ifconfig_spec.rb
- Updated regex to match the interface name with hyphen 
- Updated regex will match with the output of `ifconfig` having device name `-` after any word character
e.g. `br-1234`
- Ensured `chefstyle`
- Added test case.
- After regex update, data which is accommodated in array has shifted from index 2 to 3. Incorporated this change in commit https://github.com/chef/chef/pull/8756/commits/8e295ba6e3397add1ad26d92d97d66b58659424e 
Fixes https://getchef.zendesk.com/agent/tickets/22294
`RHEL7: ifconfig provider fails with "undefined method [] for nil:NilClas`
```
[root@ip-172-31-26-90 chef]# cat ../recipe-ifconfig.rb
ifconfig("52.34.83.20") do
action :add
device "br-1234"
onboot "yes"
mask "255.255.255.255"
target "52.34.83.20" …
```
=> ifconfig: fix regex matching interface name with hyphen

lib/chef/node.rb, lib/chef/policy_builder/expand_node_object.rb, lib/chef/policy_builder/policyfile.rb, lib/chef/run_context.rb, spec/integration/client/client_spec.rb
closes #8817
Note that if any calling code winds up seeing this error message:
```
NoMethodError: undefined method `set_cookbook_attribute' for nil:NilClass
```
That means that the cookbook_collection was set before the node was
set on the run_context.  That wouldn't be a bug in core chef, that must
be fixed in the caller to reverse the order of operations.
Since I only made the positional arguments to the run_context constructor
optional in Chef-15.0 though I don't expect this breaks any existing code
written in the past month or two, but if anything crops up in the future,
consider this a definitive statement that the caller must reverse the
order of their operations and this error being thrown is a feature not
a bug to be fixed.
(The fact that we silently aborted rather than threw a …
=> Fix node[:cookbooks] attribute

lib/chef/knife/bootstrap/train_connector.rb, spec/unit/knife/bootstrap/train_connector_spec.rb
- Add check to append `sudo` only if require `sudo` privilege.
- Work fine with Ubuntu, CentOS, AIX nodes.
- Add test case to ensure it requires sudo only if option `--sudo` provided.
https://github.com/chef/chef/issues/8814
=> Bootstrap: Only use sudo when changing ownership if --sudo is passed

Gemfile.lock, omnibus/Gemfile.lock
This also gets us the public_suffix update which we've been blocked on for a long time due to the pin in addressable
=> Update InSpec to 4.16 and addressable to 2.7.0

Gemfile.lock, chef.gemspec, lib/chef/provider/package/chocolatey.rb, lib/chef/resource/chocolatey_package.rb, spec/functional/resource/chocolatey_package_spec.rb, spec/unit/provider/package/chocolatey_spec.rb
This improves command line argument handling on windows.  Should correctly deal with arguments-with-spaces issus along with any windows metacharacters in any command line arguments.  I don't see any open issues surrounding those, but we definitely have some questionable handling here.  If this is successful we can more broadly apply this across the codebase as a standard (finally).
=> convert chocolatey resource to use shell_out splat args

lib/chef/knife/bootstrap.rb, spec/unit/knife/bootstrap_spec.rb
- `rescue` the exception and retry with pty: true if host configured with `requiretty`.
- Remove the default pty: true for all node that causes the error in the window and other hosts while detecting the system.
- Earlier we provided `pty: true` for all node to bootstrap. But seems issue noticed for `Windows`, `AIX` or other `Unix` system.
- First tried without pty params.
- If fails with exception "_Sudo requires a TTY. Please see the README on how to configure_ "
https://github.com/inspec/train/blob/3ab9ad867972106f419a28ffd44d4291747dd360/lib/train/extras/command_wrapper.rb#L68 retry with `pty: true`.
- Add begin..rescue in `do_connect` seems unable to catch inside the `connect!` method.
- Warn message about pty request
```
WARNING: Sudo failed: Sudo requires a TTY. Please see the …
```
=> Bootstrap: Set pty true only if required

lib/chef/cookbook/gem_installer.rb, spec/unit/cookbook/gem_installer_spec.rb
Added support to provide options to gem installer.
When cookbook is running in airgapped environment, even if all gem are already installed, the chef-client tries to connect `https://rubygems.org/`. Adding `--local` option will resolve dependency from local cache.
- Added `gem_installer_bundler_options`, set `--local` to install from local cache or any other option can be added to modify the behavior ex. ["--local", "--clean"]
- Added `skip_gem_metadata_installation`, set `true` to skip gem metadata installation in case if all gems are already installed and installing again have performance issues. 
The above-mentioned options can be added to `config.rb`.
=> Support to provide --local flag to gem installer.

lib/chef/provider/user.rb, spec/unit/provider/user_spec.rb
- Handled a `gid` specified as a string
Fixes: https://github.com/chef/chef/issues/7158
=> Fix for user resource does not handle a gid specified as a string

lib/chef/knife/bootstrap/templates/chef-full.erb
The knife bootstrap is always installing chef-client due to a typo in
the test that checks for the existance of the executable.
=> Bootstrap: Fix typo when checking for existing chef-client

Gemfile.lock, omnibus/Gemfile.lock
Fixed a padding oracle in PKCS7_dataDecode and CMS_decrypt_set1_pkey (CVE-2019-1563)
For built-in EC curves, ensure an EC_GROUP built from the curve name is used even when parsing explicit parameters
Compute ECC cofactors if not provided during EC_GROUP construction (CVE-2019-1547)
Document issue with installation paths in diverse Windows builds (CVE-2019-1552)
=> Update openssl to 1.0.2t

lib/chef/resource/kernel_module.rb
This adds a new parameter called ``options`` which allows users to set module
specific parameters and settings. This option file needs to be run before
loading the module so that the settings get loaded properly.
=> kernel_module: Add new options property

omnibus_overrides.rb, spec/functional/resource/ifconfig_spec.rb, spec/functional/resource/mount_spec.rb
I removed the travis skips, but the comments were still there.
=> Remove some references to Travis from code comments

lib/chef/provider/package/chocolatey.rb, lib/chef/resource/chocolatey_package.rb, spec/unit/provider/package/chocolatey_spec.rb, spec/unit/resource/chocolatey_package_spec.rb
- Added method `common_options(include_source: true)` and three properties `list_options`, `user` and `password`
- In the chocolatey package if we have the feature `useEnhancedExitCodes` turned on, at that time choco will provide enhanced exit codes:
```
0: operation was successful, no issues detected
–1 or 1: an error has occurred
2: no results (enhanced)
```
- If the feature is not enabled its provide normally Exit codes:
```
0: operation was successful, no issues detected
–1 or 1: an error has occurred
```
- So we have handled the exception( 2: no results (enhanced) ) by setting the default value of property `returns` as [0, 2] instead of [0].
Fixes #8437
=> Fix for chocolatey_package fails using extra options

lib/chef/cookbook/gem_installer.rb, spec/unit/cookbook/gem_installer_spec.rb
- Added option to skip gem metadata installation
- Added test cases for gem installer
Cherrypick in the commit from #8847
We're backporting this in hopes it can help us work around #8753
=> Backport #8847 into Chef 14: Added support to provide additional options to bundle install

chef-config/lib/chef-config/config.rb
I have added an empty config_context for chefcli similar to chefdk so that commands do not fail with chefcli parameters in the knife.rb file. I have done the fix on my local machine and I no longer get errors when trying to do commands with `chefcli[:generator_cookbook] = "/path/to/generator"` in it. I specifically ran into this issue when trying to use test kitchen with this value in my knife.rb file.
=> Add empty chefcli config_context to fix commands with chefcli in knife.rb

Gemfile.lock, chef.gemspec, omnibus/Gemfile.lock
0.2.4 and before are entirely broken for bootstrapping.
Closes #8903
=> Require train-winrm >= 0.2.5

lib/chef/knife/ssh.rb
- Added nil check of `exit_status` before comparing with non zero exit condition.
https://github.com/chef/chef/issues/8849
=> [knife ssh] Fix interactive mode exit error

omnibus/resources/chef/msi/assets/LICENSE.rtf, omnibus/resources/chef/pkg/license.html.erb
When the Chef package is installed on OS X or windows, it should display [this](https://github.com/chef/chef/blob/master/omnibus/CHEF-EULA.md) file, but it was displaying the Apache 2.0 license.
=> Updated package license for macos and windows.

kitchen-tests/cookbooks/end_to_end/recipes/packages.rb
fpm has some deps that are failing to compile now on centos 6 and
opensuse 42
=> Swap test gem install of fpm for chef-ruby-lvm

.expeditor/verify.pipeline.yml, kitchen-tests/kitchen.yml
Expand our PR testing to include Oracle Linux.
=> Add testing in Buildkite for Oracle Linux 6/7/8

omnibus/Gemfile.lock
should pull in the appbundling of inspec along with whatever else is queued up.
=> bump omnibus gems

.expeditor/verify.pipeline.yml, kitchen-tests/cookbooks/end_to_end/attributes/default.rb, kitchen-tests/kitchen.yml
Use the latest opensuse leap 42 image instead of the one we stopped pushing 6 months ago
Add openSUSE leap 15 testing
=> Update openSUSE testing in Buildkite

lib/chef/knife/bootstrap/templates/chef-full.erb
Avoids leaking of the secret key on console output while bootstrapping
- Train handles it and they are no more required here
- Tested manually found no impacts
- Ensured the test cases
#8859 
#3887
=> Removing sh -c wrapper around the bootstrapper command string

lib/chef/formatters/doc.rb, spec/unit/formatters/doc_spec.rb
- Add check to avoid total if zero or nil.
- Set @progress[resource] default value to -1 so that it can start with 0%.
=> Fix show_progress in remote_file is causing FloatDomainError: Infinity

omnibus/Gemfile.lock
This takes out the appbundling of inspec which required 4.x
=> Update omnibus-software to fix build failures

Gemfile.lock, RELEASE_NOTES.md, omnibus/Gemfile.lock, omnibus_overrides.rb, scripts/bk_tests/bk_linux_exec.sh
Ruby 2.5.7 is out with fixes for:
- [CVE-2019-16201](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-15845).
- [CVE-2019-15845](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-9251).
- [CVE-2019-16254](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-16254).
- [CVE-2019-16255](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-16255).
=> Bump Ruby to 2.5.7 to address CVEs

Gemfile.lock
Expeditor bumped this to 2.0.2 for some reason.
=> Revert Gemfile.lock to Bundler 1.17.3

.expeditor/verify.pipeline.yml, kitchen-tests/kitchen.yml
openSUSE Leap 42 went EOL July 1st, 2019.
=> Remove EOL openSUSE Leap 42 testing

.expeditor/verify.pipeline.yml, kitchen-tests/kitchen.yml
Validate each PR against a Test Kitchen run on CentOS 8
=> Add CentOS 8 kitchen testing to buildkite

lib/chef/resource/windows_share.rb, spec/unit/resource/windows_share_spec.rb
Signed-off-by: Tor Magnus Rakvåg <tor.magnus@outlook.com>
The cmdlet doesn't care about the path separator format, but it should be the same everywhere for idempotency purposes.
https://github.com/chef/chef/issues/8879
=> windows_share: make path idempotent by coercing to backwhacks

lib/chef/resource/sudo.rb
`visudo` was only checking the individual file which is being generated using sudo resource, but it was not checking overall state of sudoers.
- Added overall state verification with `visudo`
Fixes #8763 #7042
=> sudo: perform config validation on the overall sudoers state

lib/chef/knife.rb
Fix for knife subcommand --help don't work as intended. If we run knife acl --help, knife group --help or knife opc --help command it does not list the commands even though this plugins are shipped with ChefDK. The reason behind this is the category under which these are listed does not 
match with the arguments passed by user. for e.g. acl commands are grouped under the category "OPSCODE_HOSTED_CHEF_ACCESS_CONTROL" and since acl as an argument doesn't match with this category as string, this does not gives valid output.
This methods groups the sub-command by category here https://github.com/chef/chef/blob/master/lib/chef/knife.rb#L165 and it fetches the category from the class for e.g. it has key and value like this in …
=> Fix for knife subcommand --help don't work as intended. 

lib/chef/knife/bootstrap.rb, spec/unit/knife/bootstrap_spec.rb
Bootstrap command was not prompting for the password when --connection-password option is not passed.
Bootstrap command was throwing error `ERROR: RuntimeError: password is a required option` when --connection-password option is not passed. The exception was not getting raised because of an incorrect method call.
- Done correct exception handling
- Fixed test case
=> Fix Bootstrap password prompt

lib/chef/knife.rb
If we run knife acl --help, knife group --help, knife opc --help command it does not list the commands even though this plugins are shipped with chefdk. The reason behand this is the category under which these are listed does match with the arguments passed by user. for e.g. acl commands are groued under the category OPSCODE_HOSTED_CHEF_ACCESS_CONTROL and since acl doesn't match with this category as string this does not gives valid output added a fix for this.
Backport https://github.com/chef/chef/pull/8915
=> Fix for knife subcommand --help doesn't work as intended.

lib/chef/provider/ifconfig.rb, spec/unit/provider/ifconfig_spec.rb
- Updated regex to match the interface name with hyphen 
- Updated regex will match with the output of `ifconfig` having device name `-` after any word character
e.g. `br-1234`
- Ensured `chefstyle`
- Added test case.
- After regex update, data which is accommodated in array has shifted from index 2 to 3. Incorporated this change in commit https://github.com/chef/chef/pull/8756/commits/8e295ba6e3397add1ad26d92d97d66b58659424e 
Fixes https://getchef.zendesk.com/agent/tickets/22294
`RHEL7: ifconfig provider fails with "undefined method [] for nil:NilClas`
```
[root@ip-172-31-26-90 chef]# cat ../recipe-ifconfig.rb
ifconfig("52.34.83.20") do
action :add
device "br-1234"
onboot "yes"
mask "255.255.255.255"
target "52.34.83.20" …
```
=> ifconfig: fix regex matching interface name with hyphen 

lib/chef/provider/user.rb, spec/unit/provider/user_spec.rb
=> Fix for MSYS-1094 user resource does not handle a gid specified as a string

lib/chef/provider/package/dnf/python_helper.rb, lib/chef/provider/package/yum/python_helper.rb
If shell out of python yum & dnf helper is exited with nonzero status then raise an error with stderr message
Now it showing 
```
------
FATAL: RuntimeError: yum_package[yum-utils] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: RuntimeError: Traceback (most recent call last):
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'yum'
```
Instead of `"undefined method `+' for false:FalseClass"`
Fixes https://github.com/chef/chef/issues/8965
=> Fix yum & dnf shellout if exit with nonzero status

lib/chef/event_dispatch/dispatcher.rb
Validated that it works:
"I rebuilt the chef/chef docker volume and the kube-jenkins builds have been passing 24 hours. Prior to the patch, 3 of the 8 builds in 24 hours would have failed."
Closes #8825
=> Event dispatcher thread local storage

lib/chef/knife/exec.rb
- Fix `undefined method 'each' for #<String:> (NoMethodError) ` while providing script path as follow
```
knife[:script_path] = "/home/myself/work/scripts"
```
- Better UI when no args provided for knife exec.
Fixes https://github.com/chef/chef/issues/5148
=> Fix undefined method `each' for String

lib/chef/provider/package/windows/exe.rb, lib/chef/provider/package/windows/msi.rb, spec/unit/provider/package/windows/exe_spec.rb
Avoid a PATH environment variable update before a windows package install
During a windows package install we need the PATH environment variable to be preserved. By default, shell_out updates the PATH by putting the Chef bin directory at the first place. It could break an install if a system command with the same name as a binary file embedded in Chef is used (like find.exe for example). 
Setting default_env to false into shell_out options in windows_package resource fix this issue. 
By default shell_out also updates the env vars LC_ALL, LANGUAGE and LANG which are not windows related variables.
=> Avoid a PATH environment variable update before a windows package install

.bldr.toml
This PR is related to issue #8966 and reverts the Chef-14 habitat package to the original artifact name `chef-client` from the new branding of `chef-infra-client`.
=> Revert habitat builder artifact to chef-client

lib/chef/knife/supermarket_list.rb, lib/chef/knife/supermarket_search.rb, spec/unit/knife/supermarket_list_spec.rb, spec/unit/knife/supermarket_search_spec.rb
- Increase items count 10 to 1000.  
- Remove #sort from cookbook collection because data is already sorted.
- Add `--sort-by` & `--owned-by` options
- Update the `new_start` count if total records are less so that it can prevent an infinite loop.
**Note:** Removing the limit from the cookbooks supermarket API is not possible because it always returns with default limit 10.
eg:  `https://supermarket.chef.io/api/v1/cookbooks` 
```
{"start":0,"total":3863,"items":[ 10 records...]}
```
We can bypass it by providing items limit something  `999999` or `9999999` but it's not feasible solution. 
Fixes https://github.com/chef/chef/issues/8958
=> Enhance knife supermarket list & search

lib/chef/knife/download.rb
Found this typo while working with knife download commands. knife download --[no]-diff and --[no-]force option should mention have download word in description.
=> Fix typo for knife download --[no]diff and --[-no]force options.

RELEASE_NOTES.md
Now that habitat packaging is working again we are promoting `14.14.25` rather than `14.14.22`
=> Modify release notes for 14.14.25 promotion

lib/chef/knife/data_bag_secret_options.rb
For `knife data bag` subcommands `-s` have different behavior for different subcommands.
1. `-s` refers  to as `--secret SECRET` for the following:
- knife data bag create 
- knife data bag edit
- knife data bag show
- knife data bag from file
2. `-s` refers to as `--chef-server-rul URL` for the following:
- knife data bag delete
- knife data bag list
Seems both `--server-url` and `--secret` has short option `-s` and mixlib-cli override the first one.
https://github.com/chef/chef/blob/cc6c31616126c38d93dafd1f0475ac3ae5815a65/lib/chef/application/knife.rb#L95-L98
https://github.com/chef/chef/blob/cc6c31616126c38d93dafd1f0475ac3ae5815a65/lib/chef/knife/data_bag_secret_options.rb#L37-L43
Also, some other subcommands like `knife bootstrap` included both helpers so `-s` refers to as …
=> [knife] Deprecate data bag secret (-s) short option due to conflict with --server-url option

.expeditor/config.yml, .expeditor/habitat-test.pipeline.yml
This improves on the existing pipeline by specifying which version of chef-infra-client's habitat package to install and test. The package ident environment variables will be populated automatically by expeditor when expeditor triggers the `habitat/test` pipeline which will be an action subscribed to the `buildkite_hab_build_group_published` workload.
The following subscription will need to be added to the expeditor config.yml once we are ready to start using the `habitat/test` pipeline.
```
subscriptions:
- workload: buildkite_hab_build_group_published:{{agent_id}}:*
actions:
- trigger_pipeline:habitat/test
```
=> Improve habitat test pipeline

.expeditor/config.yml
We can't use a name that starts with "habitat/" because
that causes it to be treated like a habitat build pipeline.
=> Fix habitat test pipeline name

CONTRIBUTING.md
As per the Chef OSS practics info https://github.com/chef/chef-oss-practices/blob/master/project-membership.md#maintainer we have removed maintainer and divided into explicit roles. 
So updated maintainers link in CONTRIBUTING.md
Any other links suggestion would be helpful thanks!
Fixes https://github.com/chef/chef/issues/8421
=> Update maintainers link in CONTRIBUTING.md

lib/chef/resource/locale.rb, spec/unit/knife/cookbook_show_spec.rb
This PR contains two minor orthography fixes to license notices and tags.
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
FWIW, I ran a license scan on the tip of chef following a bug report in https://github.com/nexB/scancode-toolkit/issues/1777 and found these two oddities fixed here that were not detected exactly because of some typos on your side.
=> correct typos in license headers

.expeditor/config.yml
Any pipeline name starting with "habitat" will be treated as
a habitat build pipeline. The simplest way to override this is
to explicitly set the trigger value to "default".
=> Fix habitat test pipeline name for real this time

lib/chef/application/knife.rb, spec/unit/application/knife_spec.rb
As we have supported `:summary`, `:text`, `:json`, `:yaml` and `:pp` format values but other than these values it raises error eg. `ERROR: ArgumentError: Unknown output format raw`.
After this fix it also does not allows any string starts with `s`, `t`, `y`, `j` and `p`
As per the code
https://github.com/chef/chef/blob/340ceac008bee94c053fd791175534a0b2a87ec2/lib/chef/knife/core/generic_presenter.rb#L112-L127
so previously it also taking following values as a valid format
```
=> knife cookbook list -F jjjjjjjjjjjjjjjjjj
=> knife cookbook list -F text_format_invalid
=> knife cookbook list -F p_but_not_exit
```
But after fixes, these raise an error?
Fixes https://github.com/chef/chef/issues/2979
=> Validate format option values using `in` attribute

lib/chef/knife/ssh.rb, spec/unit/knife/ssh_spec.rb
As per signature `knife ssh QUERY COMMAND (options)` seems QUERY argument is required 
so raises proper message to the user if no argument provided.
```
USAGE: knife ssh QUERY COMMAND (options)
-s, --server-url URL             Chef Infra Server URL.
--chef-zero-host HOST        Host to start Chef Infra Zero on.
--chef-zero-port PORT        Port (or port range) to start Chef Infra Zero on. Port ranges like 1000,1010 or 8889-9999 will try all given ports until one works.
-----
FATAL: You must specify the SEARCH QUERY.
```
Fixes #9027 
=> knife ssh: Fix Exception: NoMethodError: undefined method join for nil:NilClass

lib/chef/data_collector/run_end_message.rb, spec/unit/data_collector_spec.rb
Chef Automate node run history not showing cookbook version if it already converges.
In every chef-client run, we have all cookbooks with the version in node object which synced to perform the operation.
So added "expanded_cookbooks" in run_end_message API to send the data to Chef collector.
The data format of the expanded_coobooks attribute
```
eg.
{"starter"=>{"version"=>"1.0.1"}, "learn_chef_apache2"=>{"version"=>"0.1.0"}}
```
Added screenshot for reference.
=> [Data-collector] Add cookbooks attribute to run_end_message

omnibus/kitchen.yml
This PR adds an explicit license acceptance in `omnibus/kitchen.yml` reported in #9029 
=> Fix license acceptance in `omnibus/kitchen.yml`

Gemfile.lock, chef.gemspec, omnibus/Gemfile.lock
This gem is 70k smaller than the 2.x gem since it doesn't ship extra
files
=> Allow for the mixlib-authentication 3.x gem

.bldr.toml, .expeditor/config.yml, .expeditor/habitat-test.pipeline.yml, .expeditor/verify.habitat.pipeline.yml, habitat/plan.ps1, habitat/tests/spec.ps1, habitat/tests/test.pester.ps1, habitat/tests/test.ps1, omnibus/omnibus-test.ps1, scripts/ci/verify-plan.ps1, spec/functional/version_spec.rb
A Windows Habitat plan to produce Windows-flavored `chef/chef-infra-client`.
#8731 
- **within a supervised process**: The `PATH` set by the thing that starts the hab-supervisor might already [be included in the execution environment](https://github.com/habitat-sh/habitat/blob/5d4fc16c7abce0a2ffda505ba6518d042d8f889b/components/common/src/util/path.rs#L148-L151). I think.
- **when executed via hab-generated binlink**: Works as of 0.85.0
- **when executed via hab pkg exec**: Might not be needed? See https://github.com/habitat-sh/habitat/issues/6657#issuecomment-530106046
- ~Judicious testing with the effortless scaffolding~
=> a Windows Habitat plan

.expeditor/habitat-test.pipeline.yml
Gotta include the target platform or else it won't work when there are multiple platform targets for a
package.
We saw the pipeline attempt to promote without it:
```
hab pkg promote "chef/chef-infra-client/15.4.59/20191101204957" current'
--
  | Updating 'ci-studio-common'
  | ci-studio-common is up-to-date
  | Updating 'hab'
  | Chef Habitat is already up-to-date
  | » Promoting chef/chef-infra-client/15.4.59/20191101204957 (x86_64-linux) to channel 'current'
  | Failed to promote 'chef/chef-infra-client/15.4.59/20191101204957': APIError(NotFound, "")
  | You may need to specify a platform target argument
  | ✗✗✗
  | ✗✗✗ [404 Not Found]
  | ✗✗✗
```
Confirmed that the update to the command in this PR is correct.
```
> hab pkg promote chef/chef-infra-client/15.4.59/20191101204957 current …
```
=> [ci] include the platform target in the hab package promotion command

lib/chef/knife/config_get.rb, spec/integration/knife/config_get_spec.rb
- If `wcl.config_location` returns `nil` then it raises an error because of no nil checks before accessing `wcl.config_location`. Also for conf_dot_d we were passing `wcl.config_location` which is wrong so change it to `path` iteration attribute.
- After fixes showing relevant logs for config.d configuration files.
Before fix:
```
Loading from configuration file /.chef/config.rb
Loading from .d/ configuration file /.chef/config.rb
````
After fix:
```
Loading from configuration file /.chef/config.rb
Loading from .d/ configuration file /.chef/config.d/abc.rb
````
Fixes https://github.com/chef/chef/issues/9009
=> [knife config get] Fix TypeError: no implicit conversion of nil into String

lib/chef/provider/systemd_unit.rb
Unlike other resources, `systemd` doesn't log when it does work breaking the standard Chef logging model. This fixes that. See #9045 for details.
Ccloses #9045
=> systemd_unit needs to log

lib/chef/provider/service/systemd.rb, lib/chef/provider/systemd_unit.rb, lib/chef/resource/service.rb, lib/chef/resource/systemd_unit.rb, spec/unit/provider/service/systemd_service_spec.rb, spec/unit/provider/systemd_unit_spec.rb
`systemd_unit` and `service` both try to disable `indirect` units on every run.
Closes #9041
=> service/systemd_unit: Don't try to reenable services in an indirect status

.gitignore, ext/win32-eventlog/Rakefile, ext/win32-eventlog/chef-log.man.erb
Adding distro constants to windows event logs.
Templating the .man event description file as ERB and editing the corresponding Rake job to allow windows events to display alternate distribution names.
- [NA] I have updated the documentation accordingly.
- [NA] I have added tests to cover my changes.
=> dist constants in win logs

lib/chef/search/query.rb
This doesn't actually do anything and repetitively confuses me every
6 months when I look at it.
Array#pop(0) does nothing at all (in python it removes the first element
from the list):
```
[2] pry(main)> a = [ 1, 2, 3 ]
=> [1, 2, 3]
[3] pry(main)> a.pop(0)
=> []
[4] pry(main)> a
=> [1, 2, 3]
```
=> Remove useless search arg mangling

.expeditor/habitat-test.pipeline.yml, habitat/tests/spec.ps1, habitat/tests/test.ps1, scripts/ci/ensure-minimum-viable-hab.ps1, scripts/ci/verify-plan.ps1
We had a few problems with the `habitat/test` pipeline. 
* The PowerShell scripts calling PowerShell scripts was apparently swallowing the errors being thrown from inner layers. Check the error level of those scripts and throw another error if need be.
* Test hosts haven't necessarily had "hab setup" run for \hab\bin to be on the system PATH. For the purposes on this test, we would like that to be the case. So, put Hab's bin directory at the start of the PATH and carry on.
* Move the minimum hab check/install to a reusable script.
- `verify/habitat` needs hab >= 0.85 to both [build with environment variables that don't include the studio path](https://github.com/habitat-sh/habitat/pull/6850) and to [binlink the runtime
with stubs that include the package and system …
=> fix the habitat package promotion tests

.expeditor/verify.pipeline.yml, kitchen-tests/kitchen.yml
The oraclelinux:8 image has had many of the files laid down by the systemd package removed from its filesystem. The package must be reinstalled because the system thinks it already has been.
```
> docker run -it --rm --name oracle8 oraclelinux:8 bash
[root@a86be7dd7120 /]# ls -l /sbin/init
lrwxrwxrwx 1 root root 22 Jul  6 00:43 /sbin/init -> ../lib/systemd/systemd
[root@a86be7dd7120 /]# /sbin/init
bash: /sbin/init: No such file or directory
[root@a86be7dd7120 /]# ls -l /sbin/../lib/systemd/systemd
ls: cannot access '/sbin/../lib/systemd/systemd': No such file or directory
```
This seems to be new in v8. The filesystems used for each of the v7 images—on the [dist-amd64 branch of oracle/container-images](https://github.com/oracle/container-images/tree/dist-amd64)—have a systemd executable …
=> 🚧 WIP: remove Oracle 8 from TK tests run in CI

chef-utils/README.md, chef-utils/lib/chef-utils/dsl/platform_family.rb, chef-utils/spec/unit/dsl/platform_family_spec.rb
while it checks against the RUBY_PLATFORM to see if it is windows,
and so therefore the old name sort of makes sense, it does not make
sense in the context of all the rest of the chef platform helpers
that have the `_platform?` suffix.
=> rename windows_ruby_platform? to windows_ruby?

lib/chef/deprecated.rb
the work of implementing the warnings is happening in the chef-sugar gem but we need to not have an id collision.
=> reserve a number for chef-sugar deprecation warnings

.expeditor/verify.pipeline.yml, kitchen-tests/cookbooks/end_to_end/metadata.rb
The repo is defaulting to chef-sugar now. We'll continue to ship -ng to
support anyone that switched to it, but it's not the main gem.
=> Switch our tests back to chef-sugar

kitchen-tests/cookbooks/end_to_end/attributes/default.rb, kitchen-tests/cookbooks/end_to_end/libraries/chef-sugar.rb
=> Remove the use of Chef Sugar from the Kitchen tests

lib/chef/resource/windows_firewall_rule.rb, spec/unit/resource/windows_firewall_rule_spec.rb
Adds Array support to the `profile` property
https://github.com/chef/chef/issues/8808
=> Support multiple profiles in windows_firewall_rule

chef-utils/README.md, chef-utils/lib/chef-utils/dsl/platform_family.rb, chef-utils/spec/unit/dsl/platform_family_spec.rb
Kind of mixes up the distinction between platform_family vs platform_version helpers, but these seem to overwhelmingly make sense and are the kinds of things people will look for, and are common.
Stolen somewhat from facebook's helpers where they have `centos6/7/8?` helpers, but generalized instead to the rhel platform_family.  To get more specific users should probably `rhel6? && centos?` if they deeply care about centos versus actual redhat.
=> Additional chef-utils helpers for rhel6/7/8

lib/chef/resource/breakpoint.rb, lib/chef/resource/build_essential.rb, lib/chef/resource/sudo.rb, lib/chef/resource/windows_env.rb, lib/chef/resource/windows_feature.rb, lib/chef/resource/windows_feature_powershell.rb, tasks/docs.rb
Bring in a few more copy edits that were done on the website and improve the rake task so that it better creates docs that match the formatting we want.
=> Improve resource descriptions and the rake task for docs generation

lib/chef/resource/windows_package.rb, spec/unit/resource/windows_package_spec.rb, tasks/docs.rb
- Make sure the correct installer_type symbol is passed and provide a useful error message when a bogus value is provided instead of just saying it needs to be a symbol and hoping a user eventually stumbles onto the docs
- Add descriptions fields to all the properties and update them since the ones on the docs site right now aren't the best
- Coerce the provided checksum value to lowercase. Right now if it's uppercase, but valid the resource will fail and the message provided is not useful. See https://github.com/chef/chef/issues/6682
=> Improve input validation on windows_package

Rakefile, chef.gemspec
We only need the rspec task which gets run from within the gem artifact
in the test phase. Skips all the other stuff.
=> Don't ship the extra rake tasks in the gem

kitchen-tests/cookbooks/end_to_end/recipes/default.rb, lib/chef/resource/build_essential.rb, spec/unit/provider_resolver_spec.rb
- fixes bug inside the action which was breaking build_essential on rhel
- wires up some more testing in the provider resolver spec
- adds a property that we can turn on so that this kind of breakage will raise an error in our end-to-end testing
i'm not entirely sure raise_if_unsupported true should be the default behavior, but that would be a breaking change and we definitely need to be able to bypass that for testing.
closes #9107
=> Fix failures in build_essential on rhel platforms

ext/win32-eventlog/Rakefile
The chef source isn't in the load path. Make sure we get the file we're
expecting here.
=> Require relative in the win32-eventlog rakefile

spec/unit/util/selinux_spec.rb
i can only assume this was missed because /usr/local/[s]bin was already
in the PATH everywhere else this has passed tests locally and on
buildkite.  dunno why workstation's testers are different, but this
is an overlooked fix.
=> fix selinux specs for workstation

ext/win32-eventlog/Rakefile, lib/chef/dist.rb
Making sure windows event source defaults to `chef` once again
discussed in slack
=> restoring correct value to windows event source

lib/chef/resource/kernel_module.rb
This backports #8887 for Chef 14. I'm not sure what the policy is for backporting something like this, so please let me know if I did it correctly or if it's even possible.
=> kernel_module: Add new options property (backport from chef-15 to chef-14)

lib/chef/provider/support/yum_repo.erb
Properly indenting multiple baseurls for `yum_repository` resource
Fixes https://github.com/chef/chef/issues/9133
https://github.com/chef/chef/issues/9133
=> [yum_repository] Add indentation for multiple baseurls

omnibus/Gemfile.lock
This will drop our install size on disk by 4%
=> Update omnnibus-software to add further ruby cleanup

omnibus/omnibus-test.sh, spec/functional/resource/group_spec.rb
Unfortunately the MacOS Anka images still do not have sufficient `ulimit` settings and PR #9127 removed the `ulimit` setting in `omnibus-test.sh` resulting in MacOS pipeline failures.
Additionally, Solaris began failing when PR #9128 removed `:not_supported_on_solaris` from `"group manage action"` in `spec/functional/resource/group_spec.rb`.
=> Fix Chef-14 Test Failures

omnibus/Gemfile.lock
most notably pulls in the -fstack-protector-strong fix for rhel6
=> bump omnibus-software + rhel6 fix

lib/chef/node/common_api.rb, spec/unit/node/vivid_mash_spec.rb
The `Node.read!` method specifies an empty error message when it fails, which complicates debugging. I added the dot-separated path to the key it was attempting to read to the error message.
It is not perfect because ideally the user would like to know which key in the hierarchy does not exist; instead it always specifies the entire requested path. Since the code itself is not aware of which key exactly does not exist, retrieving this information and putting it into the error message would increase complexity, and require refactoring to prevent it from incurring a performance penalty for successful calls. This is why I decided for now to make a simple change that always returns the entire requested path instead. If we keep it this way, we may want to document it, but I could not find API …
=> Specify item path in Node.read! error message

chef-config/lib/chef-config/config.rb, chef-config/lib/chef-config/workstation_config_loader.rb, chef-config/spec/unit/workstation_config_loader_spec.rb
When loading the configs using `~/.chef/credentials`, any value set for `ssl_verify_mode` is always ignored, and `:verify_peer` is always used. Chef expects the value to be a ruby symbol, which we can't set via the TOML `credentials` file.
This takes the value for that config and converts it to a symbol along with handling if the user specifies a string that looks like a symbol.
Example configs: 
```
[default]
client_name     = "someuser"
client_key      = "/home/user/.chef/userkey.pem"
chef_server_url = "https://CHEF_SERVER_URL/organizations/SOMEORG"
ssl_verify_mode = "verify_none"
```
or
```
[default]
client_name     = "someuser"
client_key      = "/home/user/.chef/userkey.pem"
chef_server_url = "https://CHEF_SERVER_URL/organizations/SOMEORG"
ssl_verify_mode = ":verify_none"
```
=> Symbolize config for ssl_verify_mode in credentials

chef-bin/bin/chef-service-manager, chef-config/lib/chef-config/config.rb, chef-config/lib/chef-config/dist.rb, chef-config/spec/unit/config_spec.rb, lib/chef/application.rb, lib/chef/application/windows_service.rb, lib/chef/application/windows_service_manager.rb, lib/chef/cookbook_site_streaming_uploader.rb, lib/chef/deprecation/warnings.rb, lib/chef/dist.rb, lib/chef/exceptions.rb, lib/chef/shell/ext.rb
More work towards https://github.com/chef/chef/issues/8376
This one replaces the last known occurrences that need addressing of `/etc/chef` with a distro constant in chef-config.
I validated there's no more occurrences of `/opt/chef` too. Windows paths could also be addressed in this PR (another commit), or another PR if maintainers prefer that.
https://github.com/chef/chef/issues/9094
- [NA] I have updated the documentation accordingly.
- [NA] I have added tests to cover my changes.
=> Replace hardcoded /etc/chef with Chef::Dist::CONF_DIR

lib/chef/application/apply.rb, lib/chef/dist.rb
more work towards #8376. This commit was originally in PR 9065, moved here as per discussion on Slack.
=> Add a new distro constant for chef-apply

lib/chef/dist.rb
I somehow duplicated Chef::Dist::SHORT, this removes the  duplicate entry.
Obvious fix
=> Remove duplicate constant for Chef::Dist::SHORT

lib/chef/provider/user/mac.rb, omnibus/omnibus-test.sh
We need more defensive coding around the absense of the ShadowHashData.
Unfortunately I wasn't able to fix the tests on my mac where this
happens, and don't know how to introduce tests that would fail on
buildkite, so we have no coverage for this.  Testing was done
manually on the CLI.
Also removed some useless converge_by statements that were
effectively double-logging.  The methods that the converge_by's
were in are already wrapped by converge_by's in the superclass
so the resource is already "dirty" in the sense that it knows
that it is being updated, and the log message that e.g. the
user is being removed is already being printed.  Some of the
sub-action logging with sub-converge_by's here is still good
since it shows the details of how the user is being added or
removed or modified …
=> Fix mac_user breakage and logging

omnibus/omnibus-test.ps1, omnibus/omnibus-test.sh
i'm not going to have time to figure out why the unit + integ tests are
still busted before vacation.
=> revert back to only functional testing

lib/chef/resource/archive_file.rb
Currently, the `archive_file` file resource applies a `chown_R` to the entire destination directory, which could be dangerous if the user is extracting directly to places like `/etc` or `/bin`. This PR proposes fixing this by modifying ownership only of file listed in the archive, leaving the destination directory and anything else it contained prior to the run untouched.
I cheated; I'm skipping right to the PR. The docs said `owner` and `group` would be applied to the extracted files, so  presumably editing the destination directory itself is considered a bug.
- [N/A] I have updated the documentation accordingly.
- [N/A] I have added tests to cover my changes.
=> resource archive_file: apply ownership to extracted files only

lib/chef/event_loggers/windows_eventlog.rb, lib/chef/log/winevt.rb, spec/functional/event_loggers/windows_eventlog_spec.rb
This change fixes the description format of event logged message in event logger which originated due to name change of product from `chef` to `chef infra client`
- Due to constant `SOURCE`  change from 'Chef' to `Chef Infra Client`, Registry Key Sub key mismatched with event data source in `Chef v15`. This resulted into a weird message description like 
```
The description for Event ID 10000 from source Chef Infra Client cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer. 
If the event originated on another computer, the display information had to be saved with the event. 
The …
```
=> Fix event log message description format

CONTRIBUTING.md
Signed-off-by: susanev <susan.ra.evans@gmail.com>
added a sentence about how to sign off when using the GitHub web ui to make changes
=> Update CONTRIBUTING.md with info about signing off from the github ui

chef-utils/lib/chef-utils/dsl/architecture.rb, chef-utils/lib/chef-utils/dsl/introspection.rb, chef-utils/lib/chef-utils/dsl/platform_family.rb
I'm using these to generate the vscode snippets now so the comment is what we display to the end-user. I aligned everything that was platform_family to be a platform family check. Some of them are kinda silly since they almost entirely 1:1 match, but this way it's all consistent. I'm not too concerned about someone with OmniOS in vscode at this point, but it's all done.
=> Expand chef-utils yard comments and make consistent

lib/chef/provider/user/aix.rb
When a password is changed on aix using the chpasswd command the ADMCHG flag is set on the user. This flag will cause the user to be prompted to change their password on next login. This behaviour is different from for example the linux implementation where no reset is required on next login.
Adding the `-c` flag to the `chpasswd` command will clear this flag on the user and therefore makes sure that no password reset is required on next login
This might be a breaking change if people rely on the fact that a reset will be required on next login. But that seems unlikely to me. This could probably be solved by adding an option to the resource, but I do not know if this is desirable nor how to add such an option.
=> Clear password flags when setting the password on aix

.expeditor/release.omnibus.yml
Windows 2008 R2 is no longer a supported a supported platform by
Microsoft https://support.microsoft.com/en-us/help/4456235/end-of-support-for-windows-server-2008-and-windows-server-2008-r2
=> Do not build Chef Infra Client on Windows 2008 R2

lib/chef/mixin/openssl_helper.rb, lib/chef/resource/openssl_x509_certificate.rb, spec/unit/mixin/openssl_helper_spec.rb
This change add the capability to automatically renew a certificate in the x509_certificate resource. It adds a new property (renew_before_expiry) wich contains the number of days before expiration. If this limit is reached, the certificate will be renewed.
Merry christmas !
=> x509_certificate : Add the capability to automatically renew a certificate

lib/chef/knife/supermarket_install.rb
A user on discourse is seeing errors related to this old class. I'm not able to reproduce that failure, but we shouldn't be calling the deprecated class here. Changing this avoids a bogus deprecation warning that tells the user to stop using the legacy command when they're actually using the new command.
=> Use the right class in knife supermarket install

lib/chef/knife/bootstrap/templates/chef-full.erb, lib/chef/knife/core/bootstrap_context.rb
`CONF_DIR` is resolved based on the host system running chef-client/knife.  When we
use it in bootstrap template/context, we need a value based on the
target system that is being bootstrapped so that the paths are correct
(so that we don't try to create C:\chef on a linux system).
This needs to be verified cross environment (windows host, linux target; linux host, windows target). 
Fixes #9224
=> Use /etc/chef for bootstrapping instead of CONF_DIR

lib/chef/chef_fs/file_system/chef_server/cookbooks_dir.rb, lib/chef/cookbook_loader.rb, lib/chef/cookbook_uploader.rb, lib/chef/cookbook_version.rb, lib/chef/knife/cookbook_upload.rb, spec/data/cookbooks/apache2/metadata.json, spec/data/cookbooks/java/metadata.json, spec/integration/knife/chef_fs_data_store_spec.rb, spec/integration/knife/cookbook_upload_spec.rb, spec/integration/knife/upload_spec.rb, spec/unit/knife/cookbook_upload_spec.rb
Berkshelf generates metadata.json at the time of upload but knife cookbook upload / knife upload do not have similar behaviour.  
This change generates the metadata.json if it does not exist at the time of knife upload and knife cookbook upload and since it has the metadata.json uploaded on Chef Server it gets downloaded at the time of knife download.
#9003
=> Generate metadata.json from metadata.rb if not exist before knife cookbook upload or knife upload or berkshelf upload

lib/chef/provider/cron.rb, lib/chef/provider/cron/aix.rb, lib/chef/resource/cron.rb, lib/chef/resource/cron_d.rb, spec/unit/provider/cron_spec.rb
- Property accepts hash with timeout options as keys and their values in string
- Property also accepts Integer or String value
- Working fine for Linux, Need to check for AIX platforms
Add a possibility to set a max execution time for cron job
Closes [Chef-Client#324](https://github.com/chef-cookbooks/chef-client/issues/324)
=> Add time_out property in cron resource

.expeditor/release.omnibus.yml
Remove RHEL 6 s390x (zLinux) support
IBM is retiring support for RHEL 6 in their hosted Linux One cloud on Jan 17th 2020,
so we are no longer able to support this platform in our build matrix.
=> Remove RHEL 6 s390x (zLinux) support

lib/chef/resource/windows_feature_dism.rb, lib/chef/resource/windows_feature_powershell.rb, spec/unit/resource/windows_feature_dism_spec.rb, spec/unit/resource/windows_feature_powershell_spec.rb
These are EOL platforms that we no longer produce artifacts for. Let's
simplify / speedup these resources by removing legacy platform checks.
=> Remove support for Windows 7 / 2008 from windows_feature

.expeditor/verify.pipeline.yml, chef.gemspec
We support the last 2 releases of Ruby on Chef. Ruby 2.7 is out so we
should remove Ruby 2.5 at this point. We'll add Ruby 2.7 testing in the
near future.
=> Require Ruby 2.6+

chef-utils/lib/chef-utils.rb, chef-utils/lib/chef-utils/dsl/windows.rb, chef-utils/spec/spec_helper.rb, chef-utils/spec/unit/dsl/windows_spec.rb
I'm placing these in their own helper file since there are going to be
more of them and the only commonality is that they're for windows.
=> Add windows helpers for install type

lib/chef/node/mixin/immutablize_array.rb, lib/chef/node/mixin/immutablize_hash.rb, lib/chef/platform/priority_map.rb, lib/chef/property.rb, lib/chef/provider.rb, lib/chef/provider/service/systemd.rb, lib/chef/resource.rb, spec/unit/cookbook/metadata_spec.rb, spec/unit/node/attribute_spec.rb, spec/unit/property_spec.rb, spec/unit/provider/service/systemd_service_spec.rb
Fixes most of the spec failures for ruby 2.7
Also in the process converts the systemd service provider to using shell_out splat-args array style arg parsing (easiest way to fix it for 2.7 was to just do it right).
=> Fix most Ruby 2.7 test failures / systemd service provider splat args conversion

lib/chef/provider/launchd.rb
Changes the capitalization of the hard_resource_limits launchd key from "HardreSourceLimits" to "HardResourceLimits"
Seems to have been a typo.
You can check e.g. https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html or https://www.launchd.info/ for the proper capitalization.
Signed-off-by: Marc Seeger <mseeger@fb.com>
https://github.com/chef/chef/issues/9238
=> launchd: Fix capitalization of HardResourceLimits

omnibus/Gemfile.lock, omnibus/config/projects/chef.rb
This changes makes the neccessary changes to enable the pkg to pass apples notarization requirements.
1. Update omnibus and omnibus-software to versions that support deep signing
2. Drop 'Developer ID Installer:' from signing key. This lets sigining pick up the correct key for what is being signed.
Signed-off-by: Jon Morrow <jmorrow@chef.io>
https://github.com/chef/omnibus/pull/924
https://github.com/chef/omnibus-software/pull/1146
=> Fixes all notarization issues

lib/chef/chef_fs/file_system/chef_server/cookbook_artifacts_dir.rb, lib/chef/chef_fs/file_system/chef_server/versioned_cookbooks_dir.rb, lib/chef/chef_fs/file_system/repository/chef_repository_file_system_cookbook_artifact_dir.rb, lib/chef/chef_fs/file_system/repository/chef_repository_file_system_cookbook_dir.rb, lib/chef/chef_fs/file_system/repository/chef_repository_file_system_versioned_cookbook_dir.rb, spec/integration/knife/upload_spec.rb
We added a deprecation warning to load_cookbooks and this is going to cause a ton of console spam for end users.
=> Use .load! in the Cookbook loader not .load_cookbooks

lib/chef/chef_fs/file_system/chef_server/cookbook_artifacts_dir.rb, lib/chef/chef_fs/file_system/chef_server/versioned_cookbooks_dir.rb, lib/chef/chef_fs/file_system/repository/chef_repository_file_system_cookbook_artifact_dir.rb, lib/chef/chef_fs/file_system/repository/chef_repository_file_system_cookbook_dir.rb, lib/chef/chef_fs/file_system/repository/chef_repository_file_system_versioned_cookbook_dir.rb, lib/chef/cookbook/cookbook_version_loader.rb, spec/integration/knife/chef_fs_data_store_spec.rb, spec/integration/knife/deps_spec.rb, spec/integration/knife/upload_spec.rb, spec/unit/cookbook/cookbook_version_loader_spec.rb
Avoid load method deprecation warnings in knife that were introduced with the release of 15.7.30. Backported from Chef 16
=> Avoid load method deprecation warnings in knife

CONTRIBUTING.md
Recently, in [#9239](https://github.com/chef/chef/pull/9239#issuecomment-576812427) it became clear that the text that was added for describing signing off from the UI was unclear, this is a second attempt.
=> attempt #2 at describing adding a DCO when making a change from the GitHub UI

lib/chef/cookbook_uploader.rb
In order to fix skip syntax check for berks upload cookbook uploaded required to skip the validate_cookbooks method call.
Added `skip_syntax_check` options check while invoking the `validate_cookbooks` method.
Fixes https://github.com/berkshelf/berkshelf/issues/1835
=> berks upload skip syntax check fixes

.expeditor/verify.pipeline.yml
test against berkshelf so we know more immediately if we break anything
=> add berkshelf as an external test

lib/chef/knife/data_bag_secret_options.rb, spec/unit/knife/bootstrap_spec.rb
As we have planned to remove the data  bags `secret` short option in chef-16. earlier added deprecation warning in #8909 if someone uses -s for data bag.
Closes https://github.com/chef/chef/issues/4647
=> [chef-16] Remove the data bag secret short option

chef-config/lib/chef-config/config.rb
sites-cookbooks was the way to build out your Chef infrastructure circa
2010, but was long ago removed from documentation and we've slowly
killed off bits of the functionality like the merging.
Fixed #9123 
=> Remove the sites-cookbooks dir from the cookbook_path default config

lib/chef/resource/apt_repository.rb
When you're using a PPA there's a default here that doesn't apply to non-PPA repos.
=> apt_repository: add a description for components when using a PPA

lib/chef/knife/core/status_presenter.rb, lib/chef/knife/status.rb, spec/unit/knife/status_spec.rb
This way we get the public IP / hostname on Azure, GCE, DigitalOcean, Softlayer, etc.
=> Update knife status --long to use cloud attributes not ec2 specific attributes

lib/chef/knife.rb
We won't have a DK when we have Chef 16 so this shouldn't be there.
=> Remove DK wording from knife warning

lib/chef/search/query.rb, spec/unit/search/query_spec.rb
The knife CLI calls search with a `type` of `'node'` (a string) for node searches (or searches where the index is unspecified). The `if` statement here only checks for the symbol `:node` which meant that fuzzy searches from the knife CLI did not work.
This fixes the issue by checking if the type is  `:node` or `'node'`. I'm not sure if there's a preference to check this way or to just coerce it to a symbol beforehand. 
[#9285 - Knife cli fuzzy search does not work as documented](https://github.com/chef/chef/issues/9285)
=> Fix fuzzy node search to work when the search type is a string rather than a symbol

chef-utils/lib/chef-utils/dsl/windows.rb, chef-utils/spec/unit/dsl/windows_spec.rb
These both return version objects which means they can be compared without creating version objects first or .to_i / .to_f messes. Much simpler for users.
=> Add windows_nt_version and powershell_version helpers to chef-utils

lib/chef/dsl/declare_resource.rb
The code examples inconsistently refer to `/x/y.txy` as well as `x/y.txt`, it seems that the latter is intended.
Obvious fix.
Signed-off-by: Michel Alexandre Salim <michel@fb.com>
This makes the documentation more consistent, see e.g. https://www.rubydoc.info/github/opscode/chef/Chef/DSL/DeclareResource
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chef/chef/9273)
=> declare_resource.rb: consistently use `/x/y.txt`

chef-config/lib/chef-config/config.rb
Distros like Cinc are unable to use chef-zero as it hardcodes the `single_org` parameter to be "chef". While we currently patch it, this PR would bring the change upstream so everyone can benefit from it.
- [NA] I have updated the documentation accordingly.
- [NA] I have added tests to cover my changes.
- [NA] All new and existing tests passed.
=> revert to "chef"

lib/chef/knife.rb, lib/chef/knife/acl_add.rb, lib/chef/knife/acl_base.rb, lib/chef/knife/acl_bulk_add.rb, lib/chef/knife/acl_bulk_remove.rb, lib/chef/knife/acl_remove.rb, lib/chef/knife/acl_show.rb, lib/chef/knife/group_add.rb, lib/chef/knife/group_create.rb, lib/chef/knife/group_destroy.rb, lib/chef/knife/group_list.rb, lib/chef/knife/group_remove.rb, lib/chef/knife/group_show.rb, lib/chef/knife/user_dissociate.rb, lib/chef/knife/user_invite_add.rb, lib/chef/knife/user_invite_list.rb, lib/chef/knife/user_invite_recind.rb
Ship these knife commands so we can kill off knife-acl, but move them under their own namespaces.
=> Move knife-acl gem commands into chef in their own namespaces

chef-utils/README.md, chef-utils/lib/chef-utils/dsl/introspection.rb, chef-utils/spec/unit/dsl/introspection_spec.rb
The two argument version of this needed to have its arguments reversed to make the node optional (this is hopefully incredibly unlikely to be used, but a necessary API break).
=> Add chef-sugar include_recipe? helper

omnibus/Gemfile.lock, omnibus/resources/chef/pkg/entitlements.plist
ffi loads c code into memory in an unsigned way and this allows workstation
to work with the hardened runtime.
Signed-off-by: Jon Morrow <jmorrow@chef.io>
https://github.com/chef/omnibus/pull/928
=> Adding entitlement for unsigned memory execution

lib/chef/provider/user/mac.rb, lib/chef/resource/user/mac_user.rb
Goals:
- `mac_user` provider will now use the numeric GID when creating a user, instead of passing what was literally in the resource (e.g. it will use 80 instead of "admin")
- brings back support for `system true` from the old `dscl` provider.
- adds support for new property `hidden` which will set the `IsHidden` value in the user plist.
The GID will fix issues where the system does not recognize the user (for `chown` operations, or `id`, etc)
The `system: true` works, but there are still macOS quirks. For instance, if you run chef manually in terminal, you'll be prompted to give Terminal.app privacy protection rights to be able to set the UID.  When run via launchd, which is how most orgs would use chef, macOS just ignores the UID you pass and pulls its own (usually starting at 502 and …
=> mac_user: fixing gid and system properties, and adding hidden property

RELEASE_NOTES.md, lib/chef/resource/sysctl.rb
Adds optional comments to the sysctl resource, which are prepended to any settings. Allows for documentation of sysctls on the target system.
This is a new feature, so none.
=> Add comment block to sysctl resource

tasks/bin/run_external_test
Our external gem tests need to be pinned to the same branch of Ohai that
the Chef Client source code is. Otherwise we get a Bundler error.
https://buildkite.com/chef-oss/chef-chef-chef-15-verify/builds/77#29dfd399-1019-4707-8f3f-a19ea10cfac4
=> Pinning ohai branch to get tests building

chef-utils/lib/chef-utils/dsl/architecture.rb, chef-utils/lib/chef-utils/dsl/cloud.rb, chef-utils/lib/chef-utils/dsl/introspection.rb, chef-utils/lib/chef-utils/dsl/os.rb, chef-utils/lib/chef-utils/dsl/path_sanity.rb, chef-utils/lib/chef-utils/dsl/platform.rb, chef-utils/lib/chef-utils/dsl/platform_family.rb, chef-utils/lib/chef-utils/dsl/service.rb, chef-utils/lib/chef-utils/dsl/train_helpers.rb, chef-utils/lib/chef-utils/dsl/windows.rb
I'm generating the plugin off these comments. Clean them up a bit and add @since so I can get that information added to the plugin snippets.
=> Expand the chef-utils yard for better vscode plugin generation

chef-utils/README.md, chef-utils/lib/chef-utils.rb, chef-utils/lib/chef-utils/dsl/virtualization.rb, chef-utils/spec/spec_helper.rb, chef-utils/spec/unit/dsl/virtualization_spec.rb, lib/chef/node/attribute.rb, lib/chef/node/common_api.rb
this also adds `node.dig` as an alias for `node.read` so that Hashes can be used to mock Chef::Node because i don't want to break my own rule and take a dev time circular dep back on the chef gem (although VividMash probably needs to be moved into chef-utils eventually).
=> Add chef-sugar virtualization helpers

chef-utils/lib/chef-utils.rb, chef-utils/lib/chef-utils/dsl/platform.rb, chef-utils/lib/chef-utils/dsl/platform_version.rb, chef-utils/lib/chef-utils/version_string.rb
These are strictly necessary for backcompat with chef-sugar and
necessary for converting omnibus off of chef-sugar and onto
chef-utils.
=> Add some version string backcompat APIs

lib/chef/resource/windows_task.rb
This came up in https://github.com/chef/chef-web-docs/pull/2256 and we
should really be documenting that behavior here so we can generate the
docs with it.
=> Add a default_description in windows_task

chef-utils/README.md, chef-utils/lib/chef-utils/dsl/cloud.rb, chef-utils/lib/chef-utils/dsl/introspection.rb, chef-utils/lib/chef-utils/dsl/platform.rb, chef-utils/lib/chef-utils/dsl/platform_family.rb, chef-utils/lib/chef-utils/dsl/platform_version.rb, chef-utils/lib/chef-utils/dsl/service.rb, chef-utils/lib/chef-utils/dsl/virtualization.rb
X_platform? is the name we want to eventually use so make that the real
method name as make the alias the name we want people to stop using.
That way we document the right thing in yard and can skip all the
aliases when we generate the vscode snippets.
=> Swap the methods and the aliases in the chef-utils platforms

scripts/bk_tests/bk_win_functional.ps1
This should prevent failures when we get throttled pulling it from
Github
=> Pull the windows Ruby installer from S3 for tests

lib/chef/shell.rb, lib/chef/shell/ext.rb
- Remove the decade-old meme references
- Link to the docs page that includes usage information
- Provide simpler version output
- Improve the dist constants we use
Old:
```
loading configuration: none (standalone session)
true
Session type: standalone
Loading.................done.
This is the chef-shell.
Chef Infra Client Version: 16.0.52
https://chef.io
https://docs.chef.io/
run `help' for help, `exit' or ^D to quit.
Ohai2u tsmith@!
```
New:
```
loading configuration: none (standalone session)
true
Session type: standalone
Loading.........done.
Welcome to the chef-shell 16.0.51
For usage see https://docs.chef.io/chef_shell.html
run `help' for help, `exit' or ^D to quit.
```
=> Improve welcome text in chef-shell

lib/chef/knife/cookbook_upload.rb, spec/unit/knife/cookbook_upload_spec.rb
```
WARNING: Could not find any cookbooks in your cookbook path: '/Users/tsmith/dev/work/chef'. Use --cookbook-path to specify the desired path.
```
instead of:
```
WARNING: Could not find any cookbooks in your cookbook path: .. Use --cookbook-path to specify the desired path.
```
=> Expand the path in knife cookbook upload errors

chef-utils/lib/chef-utils/dsl/introspection.rb
We've had this in chef/chef since 12.11. True it's only been in
chef-utils since 15.5. This led a community member to believe they
couldn't use it since they required Chef 13+. We should make sure folks
know they can use this helper.
=> Update docker? help comment to show it's since 12.11

lib/chef/resource/notify_group.rb, lib/chef/resources.rb, spec/unit/resource/notify_group_spec.rb
This can be used to replace the abuse of the log resource for
grouping notifications.
Closes #3426
=> Add notify_group resource

lib/chef/resource/notify_group.rb, lib/chef/resources.rb, spec/unit/resource/notify_group_spec.rb
This can be used to replace the abuse of the log resource for
grouping notifications.
=> Add notify_group resource (Chef 15 backport)

lib/chef/provider/service/debian.rb, spec/unit/provider/service/debian_service_spec.rb
Hi Chefs :wave:
I stumbled upon this bug in Kitchen + Docker environment where Chef detects `:debian` service provider and shells out to `update-rc.d` to manage runlevels. I think all full distributions ship with another init system so this bug wouldn't affect most systems traditionally provisioned with Chef.
Docker on the other hand encourages minimal system and usually does not ship with any additional init, hence Chef falls back to `:debian` and `update-rc.d`.
The fix should allow more reliable testing if nothing else by making chef-client go through the same code path in docker and non-docker environments.
I ran a rspec tests locally, but some, unrelated to my changes, were failing to begin with. Otherwise tests related to the `Debian` service provider are passing.
Let me know what …
=> update syntax of `update-rc.d` commands in enable & disable actions

lib/chef/resource.rb, lib/chef/resource/build_essential.rb, lib/chef/resource/chef_gem.rb, lib/chef/resource/freebsd_package.rb, lib/chef/resource/hostname.rb, lib/chef/resource/ohai_hint.rb, lib/chef/resource_builder.rb
This eliminates one thing that people need to memorize
The ohai_hint and hostname resources still default to true
This also forces the resource to `action :nothing` in the
converge phase automatically, which is a behavior which has
been missed up until now.
=> Add compile_time property to all resources

lib/chef/knife/core/bootstrap_context.rb, spec/unit/knife/core/bootstrap_context_spec.rb
- Reflecting `file_cache_path` and `file_backup_path` value in `/etc/chef/client.rb`
Fixes: #9357
=> Allow setting file_cache_path and file_backup_path value in client.rb during bootstrap

lib/chef/resource/windows_ad_join.rb
Signed-off-by: srb3 <sbrown@chef.io>
A customer has an issue where they want the user who initiates the domain to join to be in a different domain to the one that is being joined to.
```
you cannot use the windows_ad_join resource to join a computer in for example domain-b, by a user in domain-a that has a trust between them
```
customer would like to do the following
```
windows_ad_join domain-b do
domain_user     username + "@domain-a"
domain_password domain_creds['password']
action          :join
notifies        :reboot_now, 'reboot[post-domain-join]', :immediately
end
```
however it ends up with something like this:
```username@domain-a@domain-b```
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] I have read the **CONTRIBUTING** document.
- [ x] All new and existing …
=> windows_ad_join: Fix joining specific domains when domain trusts are involved

spec/functional/run_lock_spec.rb, spec/functional/util/powershell/cmdlet_spec.rb, spec/functional/version_spec.rb, spec/unit/data_collector_spec.rb, spec/unit/json_compat_spec.rb, spec/unit/resource_reporter_spec.rb, spec/unit/run_lock_spec.rb, spec/unit/scan_access_control_spec.rb
Simplify how we include the spec_helper via the new cookstyle rule.
=> Use require_relative within the specs

lib/chef/chef_fs/command_line.rb, lib/chef/data_collector/config_validation.rb, lib/chef/dsl/platform_introspection.rb, lib/chef/http/json_output.rb, lib/chef/knife/data_bag_edit.rb, lib/chef/provider/package/yum/python_helper.rb, lib/chef/provider/package/yum/rpm_utils.rb, lib/chef/provider/route.rb, lib/chef/provider/windows_env.rb, lib/chef/util/diff.rb, lib/chef/util/selinux.rb, lib/chef/win32/error.rb, lib/chef/win32/registry.rb, spec/support/platform_helpers.rb
The new Rubocop detects more unnecessary returns. This fixes these ahead of time so we can roll out the new Rubocop engine without breaking builds later.
=> Chefstyle fixes identified with Rubocop 0.80

lib/chef/http/http_request.rb, lib/chef/provider/package/cab.rb, lib/chef/provider/package/msu.rb, lib/chef/provider/package/windows.rb, lib/chef/provider/remote_file/ftp.rb, lib/chef/provider/remote_file/local_file.rb, lib/chef/provider/remote_file/sftp.rb, lib/chef/resource/apt_repository.rb
Necessary for ruby 2.7 support
=> fix ruby 2.7 URI.unescape deprecation

lib/chef/monkey_patches/net_http.rb, lib/chef/resource/chef_vault_secret.rb, spec/integration/knife/data_bag_show_spec.rb
Avoid deprecation warnings. Also remove the monkeypatch that provided
HTTPClientException on older Ruby releases since we're 2.6+ now and we
don't need this.
=> Update HTTPServerException to be HTTPClientException

lib/chef/cookbook_version.rb, lib/chef/mixin/from_file.rb, lib/chef/recipe.rb
YAML is now being supported.
This implementation is restrictive and does not support arbitrary ruby code embedded in the YAML.  It is being done that way to support writing a YAML-to-ruby autoconverter (so that users have an easy way to back out of YAML-land to ruby-land since YAML-land will inherently always be limited).
What this means is that the syntax is limited right now, no control flow, no looping, not even the ability to render the node object values into properties.  That would need to be done via extending the "YAML DSL" to support those, in a structured way that allowed for autoconversion to ruby later.
=> Parse YAML recipes

chef-config/lib/chef-config/config.rb, chef-config/lib/chef-config/dist.rb, lib/chef/knife/bootstrap/templates/chef-full.erb, lib/chef/knife/bootstrap/templates/windows-chef-client-msi.erb, lib/chef/knife/core/windows_bootstrap_context.rb, spec/unit/knife/core/windows_bootstrap_context_spec.rb
Add distro constants to bootstrap templates, this time using the OS at the far end of the train  connection to evaluate paths as opposed to the workstation's OS
- [NA] I have updated the documentation accordingly.
- [NA] I have added tests to cover my changes. # See my kitchen-tf monstrosity https://github.com/bobchaos/bootstrap_integration_test
=> Add distro constants to the bootstrap templates to support non-Chef distros

lib/chef/knife/core/bootstrap_context.rb, spec/unit/knife/core/bootstrap_context_spec.rb
Signed-off-by: NAshwini <ashwini.nehate@msystechnologies.com>
Don't send empty runlist if do not pass it.
https://github.com/chef/chef/issues/9155
- [ -] Bug fix (non-breaking change which fixes an issue)
=> When bootstrapping don't send an empty run_list if we are using policyfiles instead

lib/chef/chef_fs/file_system/chef_server/rest_list_entry.rb, spec/integration/knife/raw_spec.rb, spec/integration/knife/show_spec.rb
Added default params in `knife download /environments` so that it's matched with `knife environment show  --format=json`
Fixes https://github.com/chef/chef/issues/4213
=> ChefFS & knife environment matching the output

Gemfile, Gemfile.lock, kitchen-tests/cookbooks/end_to_end/recipes/default.rb
we're probably getting packetfiltered or something now that we're
no longer using travis.
=> Remove reference to travis.org and pin ruby-prof

chef-utils/lib/chef-utils/version_string.rb, lib/chef/node.rb, spec/unit/node_spec.rb
`node[:platform_version] =~ "~> 1.2"` will now just work.
This might conceivably be breaking if people are doing really weird
things by the class changing (Chef::VersionString still inherits from
String though, so it'll have to be weirdness on par with the bad
`thing.class.to_s == "Mash"` kind of comparisons that were in ohai).
closes #9154
=> Convert the node[:platform_version] to a Chef::VersionString

lib/chef/provider/group/usermod.rb, lib/chef/provider/package/homebrew.rb, lib/chef/provider/package/zypper.rb, lib/chef/provider/route.rb, lib/chef/resource/homebrew_package.rb, lib/chef/resource/kernel_module.rb, lib/chef/resource/swap_file.rb, lib/chef/resource/timezone.rb, lib/chef/resource/windows_certificate.rb
I ran cookstyle against the resources and fixes a few minor issues:
- Remove the now default guard interpreter from a powershell_script
- Use our rdoc like header format everywhere
- Remove some duplicate copyrights
- Simplify a few platform case statements
=> Cookstyle fixes for our resources

lib/chef/resource/windows_package.rb, spec/unit/provider/package/windows/exe_spec.rb, spec/unit/resource/windows_package_spec.rb
This just means a reboot is necessary. A lot of people struggle with this and then eventually set the return code. We should just do that by default like we do in windows_feature already.
Fixes #9079 
=> Accept exit code 3010 as valid in windows_package

lib/chef/resource/rhsm_errata.rb, lib/chef/resource/rhsm_errata_level.rb, lib/chef/resource/rhsm_register.rb
These need to use dnf instead of yum_package where they can. I also
enabled these for unified_mode and moved some only_if logic outside the
resources for cleaner logging. These should really all just get
converted to use shell_out and a nice converge_by
=> Update the rhsm_erata* and rhsm_register resources for RHEL 8

lib/chef/platform/query_helpers.rb, lib/chef/resource/powershell_script.rb, spec/unit/provider/powershell_script_spec.rb
All the platforms we support have PowerShell 3.0+ now so this is always true.
=> Deprecate supports_powershell_execution_bypass? check

chef-config/lib/chef-config/path_helper.rb, spec/unit/provider/directory_spec.rb
There's no reason to test this behavior anymore since we don't support macOS < 10.13
=> directory resource: Remove support for macOS < 10.11

lib/chef/resource/freebsd_package.rb, lib/chef/resource/openbsd_package.rb
This comes for free with Resource and these are the only two resources that were doing it.
=> Don't require/include Mixin Shellout in freebsd_package and openbsd_package

lib/chef/dsl/platform_introspection.rb, lib/chef/resource/windows_feature_powershell.rb
Within Chef this is only used in the windows_feature_powershell resource which I've cleaned up.
=> Deprecate the older_than_win_2012_or_8? helper

lib/chef/resource/build_essential.rb
=> Update gcc pinning for solaris to 5.4.0

lib/chef/chef_fs/chef_fs_data_store.rb
Fix gsub so only file endings of .rb and .json are removed. Any file paths, like FQDNs with them in between will not be handeled.
Signed-off-by: Jörg Herzinger <joerg.herzinger@gmail.com>
Finding this gave us a really hard time. In Kitchen we started testing with fake nodes, but we had a new FQDN which contained a ".rb" in-between (like our.fqdn.rbsomething.com). Chef Zero gave us nasty 404 errors when we tried searching for node attributes so we started tracking it down and eventually found that this regex removes any .rb and .json even if they are not at the and of the path.
I also tried finding a test that I could duplicate to check this, but I did not find anything. If you want a test please point me to where such a test should be added.
Essentially this is a quite obvious fix in my …
=> Fix gsub so only file endings of .rb and .json are removed.

spec/functional/resource/windows_certificate_spec.rb, spec/functional/resource/windows_service_spec.rb, spec/functional/win32/service_manager_spec.rb, spec/integration/client/client_spec.rb, spec/spec_helper.rb
We don't have Appveyor anymore.
=> Remove the last bits of Appveyor from the specs

lib/chef/provider/package/chocolatey.rb, lib/chef/provider/windows_task.rb, lib/chef/resource/windows_ad_join.rb, lib/chef/resource/windows_feature_powershell.rb
This is in universal so we don't need to do it in these resources / providers. We had it in some, but not in others.
=> Remove the mixin powershell includes from resources

lib/chef/platform/query_helpers.rb, lib/chef/provider/package/windows/msi.rb, spec/unit/platform/query_helpers_spec.rb
This was put in place for Windows Server Nano which didn't support MSIs. That's not a platform anymore so it can go. Here's the original PR: https://github.com/chef/chef/pull/3939
=> Deprecate Chef::Platform.supports_msi?

Gemfile.lock, chef.gemspec, lib/chef/formatters/indentable_output_stream.rb, lib/chef/knife/core/ui.rb, spec/unit/knife/core/ui_spec.rb
Contributes to the removal of the 'heavy' highline dependency (#9359) by
switching from highline.color to pastel.decorate, which is a drop-in
replacement. Pastel is part of the tty[1] family of libraries.
[1] https://github.com/piotrmurach/tty#3-components
=> Replace highline.color with pastel.decorate

.rubocop.yml, Gemfile.lock
Does not seem to be any actual changes caused by the engine update other than the rename
=> Rename cop in the .rubocop.yml for new chefstyle

README.md, RELEASE_NOTES.md, docs/dev/design_documents/resource_guard_interpreters.md, docs/dev/how_to/upgrading_from_chef_12.md, habitat/default.toml, lib/chef/cookbook/metadata.rb, lib/chef/cookbook_loader.rb, lib/chef/deprecated.rb, lib/chef/dsl/platform_introspection.rb, lib/chef/dsl/reboot_pending.rb, lib/chef/knife.rb, lib/chef/knife/bootstrap/templates/README.md, lib/chef/knife/core/ui.rb, lib/chef/knife/edit.rb, lib/chef/mixin/api_version_request_handling.rb, lib/chef/provider/package/rubygems.rb, lib/chef/resource/cron.rb, lib/chef/resource/cron_d.rb, lib/chef/shell/ext.rb, omnibus/README.md, omnibus/resources/chef/msi/localization-en-us.wxl.erb, spec/data/cookbooks/starter/recipes/default.rb, spec/integration/knife/deps_spec.rb, spec/unit/data_collector_spec.rb, spec/unit/deprecated_spec.rb
When we migrated to hugo the URLs changed a bit. Nothing ends in .html and we moved all the resources into their own dir.
=> Update all our links to use the new docs site format / cleanup descriptions

lib/chef/resource/link.rb, lib/chef/win32/file.rb, spec/unit/provider/link_spec.rb, spec/unit/resource/link_spec.rb
Windows 2008+ has support for links. There's no reason to perform this check
every time on Windows. It's just wasting CPU cycles
Fixes #9416 
=> link resource: Remove checks for symoblic link support on Windows

spec/functional/resource/windows_certificate_spec.rb
We have an active issue filed to get these tests fixed, but for now we
need to make sure we can get builds to current so we can continue to
validate Chef 16 builds.
=> Disable failing windows tests while we troubleshoot

lib/chef/knife/core/node_presenter.rb, lib/chef/knife/core/status_presenter.rb
Right now we have a specific case for EC2. This extends the same logic
to all clouds by using the node['cloud'] data. This really only changes
things if you run knife status with the --long flag.
The output doesn't change for EC2 nodes:
bundle exec knife status --long
36666 hours ago, smith-0, smith-0, 172.16.1.13, ubuntu 14.04.
7411 hours ago, myhost, ec2-13-59-123-123.us-east-2.compute.amazonaws.com, 13.59.123.123, ubuntu 18.04.
7298 hours ago, tim_test, ec2-34-123-123-2.us-west-2.compute.amazonaws.com, 34.221.123.123, ubuntu 16.04.
7298 hours ago, tim_test2, ec2-52-88-123-123.us-west-2.compute.amazonaws.com, 52.88.123.123, redhat 7.6.
=> Use Ohai's cloud attributes in knife node / status presenters

scripts/bk_tests/bk_win_functional.ps1
This should fix our busted windows tests
=> Use the aws cli to download ruby in the windows tests

.expeditor/verify.pipeline.yml, scripts/bk_tests/bk_container_prep.sh
We're setting the same env vars in each job. Seems entirely pointless.
=> Set env vars in the container setup script

lib/chef/provider/service/debian.rb, spec/unit/provider/service/debian_service_spec.rb
This code supports sysv-rc < 2.88
Debian 8 comes with 2.88dsf-59
Debian 7 comes with 2.88dsf-41
So it seems that this code support Debian 6 which went EOL almost exactly 4 years ago.
=> Remove support in debian service init for old update-rc

kitchen-tests/cookbooks/end_to_end/recipes/chef-vault.rb, lib/chef/dsl/chef_vault.rb, lib/chef/dsl/universal.rb
Add these to universal so that existing users can use chef-vault data bags without the need for the cookbook. This allows us to deprecate that cookbook entirely.
=> Add the chef-vault helpers from the chef-vault cookbook

omnibus/config/projects/chef.rb, omnibus/config/software/more-ruby-cleanup.rb
This resulted in a pretty nice install time win / disk space win in Workstation. Let's see if we can achieve something similar in chef/chef.
This reduces the Ubuntu package size by 14%. I'll have additional install stats once our mac builder issues are resolved
=> Bring in the extended Ruby cleanup used in chef-workstation

spec/spec_helper.rb
Fixes the load path in rspec runs to always load the local version of sub-gems.
* Add the local versions of `chef-config` and `chef-utils` to the load path so that rspec will always load the local versions when called without bundler.
* Use `$LOAD_PATH` instead of the cryptic `$:`.
* Remove some unnecessary additions to the load path that are automatically done by rspec.
=> Fix load path in test runs.

chef-config/lib/chef-config/config.rb, kitchen-tests/kitchen.yml, lib/chef/application.rb, lib/chef/application/apply.rb, lib/chef/application/base.rb, lib/chef/provider/file.rb
This should be backwards compatible with ruby 2.6.5 behavior but
is most likely brittle.
The PR adds an --always-dump-stacktrace option and turns it on so that we can see where things blow up.
=> Add always_dump_stacktrace config option & workaround to fix the encoding bugs

lib/chef/resource/cron_access.rb
=> Fix typo in the cron_access docs

Gemfile.lock, omnibus/Gemfile.lock, omnibus/config/software/more-ruby-cleanup.rb
With this change we now have 25% fewer files than 15.8 and ~24% less space used on disk.
=> Cleanup a bunch more files and pull in the smaller license-acceptance

lib/chef/chef_fs/chef_fs_data_store.rb
Backport https://github.com/chef/chef/pull/9429
Any file paths, like FQDNs with them in between, will not be handled.
Signed-off-by: Jörg Herzinger <joerg.herzinger@gmail.com>
=> chef_fs: Fix gsub so only file endings of .rb and .json are removed. 

lib/chef/provider/package/powershell.rb, spec/unit/provider/package/powershell_spec.rb
Use Ohai data to determine if we have PowerShell installed
Fixed: https://github.com/chef/chef/issues/9398
=> powershell_package: Use ohai data to get the powershell release instead of shelling out

.expeditor/release.omnibus.yml, lib/chef/provider/package/dnf.rb, lib/chef/provider/package/dnf/dnf_helper.py, lib/chef/provider/package/dnf/python_helper.rb, lib/chef/provider/package/dnf/version.rb, lib/chef/provider/package/yum.rb, lib/chef/provider/package/yum/python_helper.rb, spec/functional/resource/dnf_package_spec.rb, spec/unit/provider/package/dnf/python_helper_spec.rb
This fixes a few open bugs in the DNF package provider, and there were a bunch of bugs fixed in the yum provider that have not yet been reported against DNF which it should fix as well.  Also fixes the functional tests for aarch64 el8 support.
closes #9189
closes #9013 
closes #9201
=> Refresh DNF package provider and add aarch el8 testing support

lib/chef/resource/windows_firewall_rule.rb
So far, changing Windows firewall rules with more than one associated profile will fail validation on loading the current state.
The reason is a `.ToString` conversion of an array in the Powershell helper, which is not reversed into individual symbols on loading state.
Also fixing a minor typo.
Related to issue #8808
=> Fix windows_firewall_rule resource for rules with multiple profiles

lib/chef/resource/windows_firewall_rule.rb, spec/unit/resource/windows_firewall_rule_spec.rb
This PR fixes:
- Changing description property to an own value does only work once and not all the time
- Add displayname as new property instead of only adding the firewall rule name as displayname
https://github.com/chef/chef/issues/9512
https://github.com/chef/chef/issues/9513
=> extend windows_firewall_rule abilities with displayname and description

lib/chef/mixin/shell_out.rb
I made a reference to this comment in #9509 and @lamont-granquist said it was outdated and should be removed.
https://github.com/chef/chef/pull/9509#issuecomment-600949638
=> Remove outdated comment about shell args on different platforms.

scripts/bk_tests/bk_win_functional.ps1
We're failing a lot when we try to remove this file. Just move on with
life.
=> If we can't remove the Ruby installer in windows tests that's cool

lib/chef/application/apply.rb, lib/chef/recipe.rb, spec/unit/application/apply_spec.rb, spec/unit/recipe_spec.rb
Enables `chef-apply foo.yml` and `chef-apply foo.whatever --yaml`.
Improves error messages around incorrectly formatted YAML.
**Also changes/enforces the YAML file format** 
This removes an unnecessary array that we had been using.
New format:
```
---
resources:
- name: "do something"
type: "execute"
```
```
{ "resources" => [ { "name" => "do something", "type" => "execute" } ] }
```
Old format:
```
---
- resources:
- name: "do something"
type: "execute"
```
```
[ { "resources" => [ { "name" => "do something", "type" => "execute" } ] } ]
```
=> Add support for parsing YAML recipes with chef-apply

lib/chef/resource/chef_client_cron.rb, lib/chef/resource/helpers/cron_validations.rb
- add instance methods to the module so it can be mixed in
- extend the module into the resource class
- use explicit methods for "currying" arguments to avoid the cognitive
overhead of the lambda syntax and allow using method()
- use method() to keep the callbacks readable
=> clean up chef_client_cron

lib/chef/resource/rhsm_register.rb, spec/unit/resource/rhsm_register_spec.rb
This will enable people to increase their security posture by verifying the remote satellite host SSL certificate.
N/A
=> Add : https_for_ca_consumer property to rhsm_register resource

spec/support/platforms/win32/spec_service.rb
Merging in this check broke the build tests on Windows hosts.
=> Switch to RUBY_PLATFORM for the windows check

.buildkite/hooks/pre-command
The `.buildkite/hooks/pre-command` script should only be executed within the `verify` pipeline.  This PR just adds a conditional to allow the script to exit successfully if the pipeline name doesn't end with "verify"
=> Modify pre-command hook to only run in verify pipeline

lib/chef/knife/core/ui.rb, lib/chef/knife/yaml_convert.rb
Very basic interface, reads in a YAML recipe, ruby recipe goes to stdout.
```
---
resources:
#
- type: "bash"
name: "new chef user"
code: "
touch /tmp/jmc/something ;
echo something >> /tmp/jmc/something ;
rm -f /tmp/jmc/bash ;
"
something:
- other: "dont use this"
```
gets converted to:
```
bash "new chef user" do
code " touch /tmp/jmc/something ; echo something >> /tmp/jmc/something ; rm -f /tmp/jmc/bash ; "
end
```
=> Add a `knife yaml convert` tool

lib/chef/resource/chef_client_cron.rb, lib/chef/resource/chef_client_scheduled_task.rb, spec/unit/resource/chef_client_cron_spec.rb, spec/unit/resource/chef_client_scheduled_task_spec.rb
- Add new accept_chef_license property
- Wire up config_directory property in chef_client_cron to match the chef_client_scheduled_task behavior
- Add run_on_battery property to chef_client_scheduled_task
- Move logic into helpers in chef_client_schedule_task
- Add more testing to chef_client_scheduled_task
=> Improve chef_client_* resources

lib/chef/resource/windows_share.rb, spec/unit/resource/windows_share_spec.rb
Compilation fails with error "can't modify frozen String". It shows error at path in the windows_share method.
fixed: https://github.com/chef/chef/issues/9166
=> Fixed windows share cannot modify frozen string bug

spec/functional/resource/ifconfig_spec.rb, spec/spec_helper.rb, spec/support/platform_helpers.rb
I'm looking at you Ubuntu 20.04
=> Skip the ifconfig functional tests if we don't have ifconfig

.expeditor/release.omnibus.yml
This PR just adds the new Ubuntu 20.04 x86_64 tester to the omnibus pipeline.
An adhoc build associated with this change can be found here:
https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/222
#9456
=> Add Ubuntu 20.04 (x86_64) Tester

lib/chef/resource/lwrp_base.rb
this restores the order that the magic wiring of LWRP / custom resources
to the cookbook_name + resource filename comes after the parsing of the
file that it is defined in.
i had moved this because i was running into issues with recursive calls
between provides and the resource_name method, which i later solved.
this restores the prior behavior, but calls provides instead of
resource_name, but relies on the implicit call to resource_name from
the first provides to be functionally identical to the prior behavior
anyway.
no idea if this actually fixes any bugs, but it was not really
intentional to change it.  stuff like chef_version_for_provides
needs to be called before calling provides, so it seems like the
behavior this fixes should have been buggy with respect to that
but it is …
=> restore magic resource name ordering

lib/chef/resource/build_essential.rb
We no longer support EOL SLES 11
=> Remove SLES 11 support from build_essential

lib/chef/resource/build_essential.rb, spec/unit/resource/build_essential_spec.rb, spec/unit/resource/data/InstallHistory_with_CLT.plist, spec/unit/resource/data/InstallHistory_without_CLT.plist
This picks off the last DCO signed off portion of #9178 so we can recreate the conversion to native Ruby without using the code we can't accept due to license concerns.
=> build_essential resource: fix macOS 10.15 and improve installation support with a new :upgrade action for macOS

chef-utils/lib/chef-utils/dsl/cloud.rb, chef-utils/spec/unit/dsl/cloud_spec.rb
Ohai always returns the cloud key so checking for the key isn't valid for cloud. We need to make sure it's not nil instead.
=> Fix cloud? helper to only report true on cloud instances

spec/functional/win32/version_info_spec.rb
Windows 10 1909 is a service pack, but without being called a service pack.
1909 is a very small update over 1903, and in fact most of the binaries are not rebuilt.
The version for 1909 is 10.0.18363, but the version in many files is still 10.0.18362, which was the version for 1903.
This caused this functional test to fail on 1909 because 10.0.18362 != 10.0.18363. Nowhere else are we concerned with the file versions matching the OS version, so the fix is to match less of the version. By matching only '10.0', we should not see this again.
=> Fix functional tests on Windows 10 by matching less

habitat/plan.ps1
Signed-off-by: John Snow <thelunaticscripter@outlook.com>
With the latest version of Habitat only checking the minor release will not work at 5 is less than 85. This fixes this by checking the full version for Habitat.
=> Make the hab version check a full version check not just minor release

Gemfile, Gemfile.lock, omnibus/Gemfile.lock, omnibus_overrides.rb
Ruby resolves 2 CVEs: https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-6-6-released/
Rake is bundled in Ruby
libarchive updated to 3.4.2 for multiple security issues including CVE-2019-19221 and  CVE-2020-9308
=> Update Ruby to 2.6.6, Rake to 12.3.3 and libarchive to 3.4.2

chef.gemspec
chef-zero 15.0 bumped the required Ruby from 2.4 to 2.6
Chef 14 only requires/uses 2.4.
=> Pin chef-zero < 15

lib/chef/action_collection.rb, lib/chef/data_collector/run_end_message.rb, lib/chef/event_dispatch/base.rb, lib/chef/provider.rb, lib/chef/resource/action_class.rb, spec/integration/recipes/resource_load_spec.rb, spec/unit/data_collector_spec.rb, spec/unit/resource/chocolatey_source_spec.rb
For custom resources which correctly implement load_current_value the
new after_resource comes for "free" and load_current_value will be
called twice to load the current_resource (should be renamed the
"before_resource" but that ship sailed) and then the after_resource.
Appropriate wiring is added for a new event and capturing that into
the action_collection and then the data_collector.  The resource_reporter
has not and will not be updated.
For old style resources which are difficult to convert to custom
resources (thinking here particularly of the 1:N model of the service
resource in core chef, or stuff that just may be a lot of work like the
file resource) then they can override the load_after_resource to
manually wire up their own after_resource.
closes #6036
=> Add after_resource to pair with current_resource

.expeditor/release.omnibus.yml, spec/functional/win32/version_info_spec.rb
Add a dedicated tester for Windows 10 instead of relying on WIndows 2019
=> Add a Windows 10 tester to the pipeline

omnibus/Gemfile.lock
This adjusts the versions where we apply an AIX patch that is necessary
for Ruby 2.6.6 on AIX
=> Update omnibus-software to fix Ruby 2.6.6 on AIX

lib/chef/resource/chef_vault_secret.rb
fixes the idempotent behavior of chef_vault_secret to also not
error out, even if it isn't actually idempotent.
=> fix chef_vault_secret after_resource breakage

lib/chef/resource/build_essential.rb, spec/unit/resource/build_essential_spec.rb, spec/unit/resource/data/InstallHistory_with_CLT.plist, spec/unit/resource/data/InstallHistory_without_CLT.plist
1) Don't rely on pkgutil to determine if the package is installed since this seems to get wiped during certain OS updates (10.15.4 being one)
2) Use pure ruby for parsing softwareupdate output which is faster and more reliable
3) Update the softwareupdate package parsing to support the new text output that shipped in macOS 10.15.
Big thanks to @w0de for kicking this off, @jazaval for the advice on pkgutil via plist parsing, and Microsoft for the plist parsing code.
=> build_essential: Support macOS 10.15 and improve idempotency

.expeditor/release.omnibus.yml
We no longer support EL6 on S390x
=> Remove S390x EL6 tester

.expeditor/release.omnibus.yml, RELEASE_NOTES.md
20.04 has testing issues right now.
=> Swap Ubuntu 20.04 for 18.04 aarch64

lib/chef/mixin/properties.rb, lib/chef/property.rb, lib/chef/resource.rb, lib/chef/resource/directory.rb, lib/chef/resource/execute.rb, lib/chef/resource/file.rb, lib/chef/resource/group.rb, lib/chef/resource/kernel_module.rb, lib/chef/resource/launchd.rb, lib/chef/resource/link.rb, lib/chef/resource/mdadm.rb, lib/chef/resource/mount.rb, lib/chef/resource/osx_profile.rb, lib/chef/resource/registry_key.rb, lib/chef/resource/route.rb, lib/chef/resource/ruby_block.rb, lib/chef/resource/scm.rb, lib/chef/resource/service.rb, lib/chef/resource/systemd_unit.rb, lib/chef/resource/user.rb, lib/chef/resource/windows_env.rb, lib/chef/resource_reporter.rb, spec/unit/property/state_spec.rb, spec/unit/property_spec.rb, spec/unit/resource_reporter_spec.rb
Setting `name_property: true` is now roughly equivalent to `name_property: true, identity: true, desired_state: false`.
If there is any other property which is marked as an identity though the name_property will no longer be considered an identity property.  A subtle detail of this is that the name_property itself is not marked as being `identity: true`, it is implemented via the `chef/mixin/properties.rb` mixin because the identity-ness of the name_property will be affected by other properties being marked as identity or not.  That means you have to inspect the whole property collection -- hence implemented in the properties mixin.  Consumers should check the identity_properties array on the resource class, and not inspect individual properties for being an identity themselves.
It makes …
=> Change the name_property to be the identity property by default, and to have desired_state: false by default

Gemfile, Gemfile.lock, omnibus/Gemfile, omnibus/Gemfile.lock
https://github.com/chef/omnibus-software/pull/1175 removed bundler from
a number of software definitions because Ruby 2.6+ includes bundler. But
Chef 14 still uses Ruby 2.5 so we need the bundler dependencies to get
bundle in the build.
=> Pin omnibus-software before the change that breaks Ruby < 2.6

omnibus/config/projects/chef.rb
Per 120c01a414db79a7111b3c89eba5999031718f96
=> Fix macos signing key

.expeditor/release.omnibus.yml
Drops 2008r2 (which we no longer have builders for)
Pulls in Windows 10, Ubuntu 20.04 x86_64, and Ubuntu 18.04 aarch64. Which are
very recently new.
=> Match platforms to chef-15

lib/chef/cookbook/metadata.rb, lib/chef/run_context/cookbook_compiler.rb, spec/integration/client/client_spec.rb, spec/integration/knife/cookbook_show_spec.rb, spec/support/shared/integration/knife_support.rb, spec/unit/cookbook/metadata_spec.rb, spec/unit/knife/cookbook_show_spec.rb
This implements RFC-40 from the old chef rfc repo:
https://github.com/chef-boneyard/chef-rfc/blob/master/rfc040-on-demand-cookbook-libraries.md
Closes #3494
As far as I can see we have recursively loaded libraries for some time, this offers some better options to not load any library files but to push them into the LOAD_PATH or to push them into the LOAD_PATH and load a single "bootstrapping" hook.
This should also help with vendoring gems, although vendoring multiple gems with this mechanism isn't super straight forwards and we might want to have a top level first class "gems" segment for a cookbook that ships a pile of gems, along with their gemspecs in order to handle getting the gems activated correctly.
=> Implement eager_load_libraries metadata option

scripts/bk_tests/bk_win_functional.ps1
The drive root has more restrictive permissions
=> 15: Use $env:temp instead of c:/ for functional tests

scripts/bk_tests/bk_win_functional.ps1
The drive root has more restrictive permissions
=> Use $env:temp instead of c:/ for functional tests

scripts/bk_tests/bk_win_functional.ps1
Adds more error checking and avoids trying to download Ruby if for some reason it already exists on disk and matches the SHA256 hash.
The primary issue discovered when troubleshooting this script was that aws.exe was running asynchronous. That was 'fixed' with '| Out-Null'.
=>  Improved Ruby download/install for functional tests

scripts/bk_tests/bk_win_functional.ps1
Adds more error checking and avoids trying to download Ruby if for some
reason it already exists on disk and matches the SHA256 hash.
The primary issue discovered when troubleshooting this script was that
aws.exe was running asynchronous. That was 'fixed' with '| Out-Null'.
Backport of #9603
=> 14 backport: Improved Ruby download/install for functional tests

scripts/bk_tests/bk_win_functional.ps1
Adds more error checking and avoids trying to download Ruby if for some
reason it already exists on disk and matches the SHA256 hash.
The primary issue discovered when troubleshooting this script was that
aws.exe was running asynchronous. That was 'fixed' with '| Out-Null'.
Backport of #9603
=> 15 backport: Improved Ruby download/install for functional tests

.expeditor/release.omnibus.yml, omnibus/Gemfile, omnibus/Gemfile.lock, omnibus_overrides.rb
Pull in from a new legacy_ruby branch in omnibus-software that is 52823134ba902daac1f18b1a75de0386558cc0a5 + the new CVE fixes to ruby.
The nokogiri bump brings us to the latest, which should be a no-op for how we use nokogiri, but matches our 15 release.
=> Update to Ruby 2.5.8 + nokogiri 1.10.9

lib/chef/provider/systemd_unit.rb, lib/chef/resource/systemd_unit.rb
Signed-off-by: sanga17 <sausekar@msystechnologies.com>
systemd_unit not respecting sensitive property
Fixed: https://github.com/chef/chef/issues/9539
=> Fixed systemd_unit not respecting sensitive property

Gemfile.lock, chef.gemspec
We need 2.x for ruby 2.7 compat and warning suppresion
=> Bump highline to 2.x

.expeditor/release.omnibus.yml
This PR adds the new Amazon Linux 2 Testers (x86_64 + aarch64) to the Omnibus pipeline.
An adhoc build is available here:
https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/237
=> Add Amazon Linux 2 Testers

lib/chef/provider.rb, lib/chef/resource.rb, lib/chef/run_context/cookbook_compiler.rb, spec/integration/recipes/notifies_spec.rb, spec/integration/recipes/use_partial_spec.rb
Resource partials are code fragments that are class_eval'd into the Resource (or Provider/ActionClass) which is being built.
As such they don't look like normal helpers and lack any "module" or "class" statement or any name, and are not `include`'d or `extend`'d.
Their primary purpose is to address reducing code duplication of `property` declarations across resources (although they're not limited to that use case at all).
The `property` declarations cannot be deduplicated by using a module since properties rely on inheritance and a module cannot inherit from Chef::Resource (and mixing in properties into module which is then mixed into a resource does not work).  Therefore this solution does not use modules or inheritance, and is just a `class_eval` which is the simplest kind of …
=> Add resource partials

lib/chef/resource/chef_client_cron.rb, lib/chef/resource/chef_client_scheduled_task.rb
The cron_d resource only works on systems that support and /etc/cron.d directory, which is Linux as far as I can tell. We want this resource to work on all the other *nix platforms so we need to fall back to the legacy cron resource for those hosts.
I also reordered all the properties so we can diff the 3 resources easier
=> Support non-Linux hosts in chef_client_cron

lib/chef/provider/user/mac.rb
This is actually a subclass of the mac user provider and not the Plist gem. This is a super confusing name btw. Plist passed Plist, but it's a different Plist.
=> Use the correct plist class in the mac user provider

omnibus/Gemfile.lock
This knows about the new location of the readme file for win32-api gem.
=> Update license scout to fix broken windows builds

lib/chef/provider/execute.rb, lib/chef/resource/dsc_resource.rb, lib/chef/resource/dsc_script.rb, lib/chef/resource/execute.rb, lib/chef/resource/paludis_package.rb, lib/chef/resource/portage_package.rb, lib/chef/resource/scm.rb, lib/chef/resource/ssh_known_hosts_entry.rb, lib/chef/resource/swap_file.rb, lib/chef/resource/windows_feature.rb, lib/chef/resource/windows_feature_dism.rb, lib/chef/resource/windows_feature_powershell.rb, lib/chef/resource/windows_package.rb
1) make sure they all have desired state false
2) Fix some indentation
3) Fix portage_package to have a type of String/Integer to match package
4) Add the String type to paludis_package to match the package default
5) Set the default timeout in the execute resource instead of overriding it in the provider
=> Updates to timeout properties in various resources

lib/chef/provider/package/cab.rb, lib/chef/provider/package/msu.rb, lib/chef/resource/msu_package.rb, spec/functional/resource/msu_package_spec.rb, spec/unit/resource/msu_package_spec.rb
-- Updated to match with version as well along with package name.
-- Identifies correct match for cumulative updates.
-- Added `timeout` property for setting new default 3600 because some packages which are larger in sizes gets time nearly 45mins to 60mins to complete.
Fixes: https://github.com/chef/chef/issues/9383
Fixes: #9245
=> msu_package: Fix cumulative updates installation and provide a 3600s default timeout

lib/chef/client.rb, spec/unit/client_spec.rb
We really want to encourage people to upgrade. One way we can do this is
to just warn them that they're on an EOL release. This simple warning
might nudge them to upgrade their client. It works off the base EOL
data of Chef 15 and takes the current release to add to that date. That
way we don't have to maintain anything and as long as we keep a yearly
release we're good. If we change the schedule then we either remove this
or update the logic. That's a risk in shipping code that doesn't fire
for 2 years.
=> Add a warning to the end of the chef run for EOL releses

.expeditor/release.omnibus.yml
This way we get Amazon 2 packages on the downloads site
=> Add build verification on Amazon Linux 2

lib/chef/provider/package/msu.rb
- We found that removal of msu_package also requires timeout for packages larger in size.
- So added the timeout to fix this behaviour.
=> msu_package: Removal also requires passing timeout property

lib/chef/client.rb, spec/unit/client_spec.rb
Warn at the end of the chef-client run after the end April 2021. Let people know when it's EOL.
=> Add deprecation warnings at the end of the run after the end of April 2021

chef-utils/README.md, chef-utils/lib/chef-utils/dsl/virtualization.rb
These generate the vscode helpers so there was a typo in that snippet
=> Fix typo in chef-utils comment

lib/chef/mixin/powershell_out.rb
=> Ruby 2.7 fix for powershell_out

spec/unit/node_spec.rb
I guess this is minimum viable testing to ensure this doesn't break in
the future.
=> Add unit tests around Chef::VersionString

lib/chef/property.rb, lib/chef/provider.rb, lib/chef/resource/windows_env.rb, spec/unit/property/validation_spec.rb
All required properties are now required for all actions by default
even if the action does not reference the property.
In order to only make the property required for a subset of the
actions, specify them as an array of symbols to the required
options on the property.
```
property :whatever, String, required: %i{start stop}
action :start do
end
action :stop do
end
action :enable do
end
action :disable do
end
```
That property will be required for start+stop but not for
enable+disable.
There's an unaddressed edge case here where if you reference the
property in an action which was not specified that it will also
fail validation.  That is correct behavior.  We should probably
dig into how to warn the user that they must either remove the
reference to the property from that action or else …
=> Force requiring properties

lib/chef/provider/package/homebrew.rb, lib/chef/resource/homebrew_package.rb, spec/unit/provider/package/homebrew_spec.rb
Issues:
- versions are pretty much ignored, but I think that makes sense with homebrew. It's a roll forward package system so you can't install a specific version. That's just not a concept of the package system.
=> Add multipackage support to homebrew

chef-utils/spec/unit/dsl/platform_family_spec.rb
Fix `WARNING: Fauxhai platform data for redhat 6.9 is deprecated and will be removed in the 9.0 release 3/2021`
=> CentOS 6.9 Fauxhai deprecation

habitat/plan.ps1
Signed-off-by: John Snow <thelunaticscripter@outlook.com>
This will set Chef 16 to use the new ruby 2.7 with the devkit when it's promoted to stable.
=> Bump ruby for windows to 2.7

lib/chef/cookbook/metadata.rb, spec/unit/cookbook/metadata_spec.rb
Remove deprecate Chef-10 constraint handling
I'll sign the DCO if this is the right thing to do 😄
=> Remove deprecated Chef-10 constraint handling

Gemfile.lock, omnibus/Gemfile.lock, omnibus/config/software/more-ruby-cleanup.rb
Bump the deps to current to bring in the latest omnibus that includes some of this cleanup natively
=> Move some of the ruby-cleanup logic into omnibus-software

Gemfile.lock
Fix openstack detection and also fix the builds
=> Bump Chefstyle to 1.0.3 and Ohai to 16.0.19

omnibus/Gemfile.lock
This exludes the debug group which prevents pulling in pry in ohai that
conflicts with the pry in the gemfile.lock
=> Bump omnibus-software to avoid double pry

Gemfile, Gemfile.lock, spec/spec_helper.rb
We're not actually running these coverage tests and even if we did they don't have high value since you can game the numbers without writing quality tests.
=> Remove the unused simplecov depedency

omnibus/Gemfile.lock
This updates how we appbundler Ohai which prevents us from shipping two copies of pry.
=> Update omnibus-software to resolve shipping 2 copies of pry

omnibus/Gemfile.lock
This changes how appbundler comes in
=> Update omnibus-software to avoid appbundler adding extra gems

.expeditor/release.omnibus.yml
This PR adds the Ubuntu 20.04 and SLES 15 aarch64 support
An adhoc build can be found here:
https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/246
=> Add Ubuntu 20.04 + SLES 15 aarch64 Testers

lib/chef/provider/package/chocolatey.rb, lib/chef/win32/api/command_line_helper.rb, spec/functional/resource/chocolatey_package_spec.rb, spec/unit/provider/package/chocolatey_spec.rb
- Whenever user was passing the installer arguments `--% -ia \"INSTALLDIR=\"#{path}\"\"` in `options` property of chocolatey_package, it wasn't installed where the user wanted, rather it is installed at the default location. so we have fixed it.
- Added `CommandLineToArgvW` function for split a string options into an array.
- Ensured chef-style on the code changes made.
Fixes: #9413
=> Fix for Chocolate_resource options causing extra quotes

lib/chef/resource/bff_package.rb, lib/chef/resource/cab_package.rb, lib/chef/resource/chef_gem.rb, lib/chef/resource/gem_package.rb, lib/chef/resource/ips_package.rb, lib/chef/resource/macports_package.rb, lib/chef/resource/msu_package.rb, lib/chef/resource/openbsd_package.rb, lib/chef/resource/paludis_package.rb, lib/chef/resource/portage_package.rb, lib/chef/resource/rpm_package.rb, lib/chef/resource/smartos_package.rb, lib/chef/resource/solaris_package.rb, lib/chef/resource/windows_package.rb
Right now these resources inherit package_name, versions, and options from the package resource which allows arrays. The problem is the actual providers for these package resources don't know what to do with arrays and they explode. They explode in ways that are really unfriendly to users. With this change they'll get a nice input validation error and they'll have a lot more of an idea of how to go about resolving the problem. This also means that our automatically generated documentation for the package resources will be correct since right now it documents everything as accepting an array.
=> Make sure all the non-multipackage packge resources can't take arrays

lib/chef/provider/service/windows.rb, lib/chef/resource/service.rb, lib/chef/resource/windows_service.rb, spec/unit/resource/service_spec.rb, spec/unit/resource/windows_service_spec.rb
This wasn't windows only. The shell_out helper will dynamically use the timeout property if it's set and uses a 900s default. Set it to 900s explicitly for the documentation generation and then set it to 60s on windows to match the hidden behavior previously done in the provider.
=> Set timeouts in service and windows_service correctly

lib/chef/resource/msu_package.rb
This is a bug, but we're going to need to live with it for now.
=> Allow Arrays in msu_package version again

chef-utils/spec/unit/dsl/platform_family_spec.rb
Use the latest fauxhai data to avoid a giant pile of spec warnings
=> Resolve deprecations in chef-utils specs

kitchen-tests/Gemfile
This avoids a giant pile of deprecation warnings
=> Use our fork of docker-api in the kitchen tests

Gemfile.lock, omnibus/Gemfile.lock
This fixes constant warnings when reloading Ohai plugins
=> Update Ohai to 16.0.20

lib/chef/resource/windows_share.rb
This was keeping this resource from working on Windows 8 / Windows
2012 which are 6.2. This works on all the versions of Windows we support
so there's no need to check this anymore.
=> Remove the Windows version check in windows_share

lib/chef/mixin/powershell_exec.rb, lib/chef/powershell.rb, spec/unit/mixin/powershell_exec_spec.rb
This is something we have in powershell_out! and shell_out! already and we use it a lot. This will make updating resources much easier.
=> Add powershell_exec! helper to make conversion from powershell_out! easier

Gemfile, Gemfile.lock
This provides working ed25519 ssh support for Windows under
Rubies 2.4-2.7.
I'm submitting this with the RC gem instead of waiting for
final release because because we don't have a timeline from the
maintainer when the RC will be finalized.
Part of this is because no decision as been made as to whether
to do a major version bump for the gem.
Before: 
After:
After:
Fixes #9639
=> Update bcrypt_pbkdf to 1.1.0.rc1

scripts/bk_tests/bk_run_choco.ps1, scripts/bk_tests/bk_win_functional.ps1, scripts/bk_tests/bk_win_integration.ps1, scripts/bk_tests/bk_win_unit.ps1
Need these so the PowerShell scripts will exit when bare commands fail.
Otherwise the build just keeps truckin' and the errors just pile up.
=> [CI] add exitstatus checks after bare commands in PowerShell scripts

spec/functional/resource/locale_spec.rb
This is breaking habitat and 32bit windows builds for now. It is 100% an
issue, but it's always been an issue. For now we need a build and we'll
track down those larger issues in future builds.
=> Disable the windows_exec test for now

spec/functional/resource/git_spec.rb
The output of this command seems to vary too much over different
git versions to make it reliable and actually work.
We should find something here that works, but determining what
git commands to use which are stable for parsing can be
very difficult.
=> Remove git func test for upstream

Rakefile, chef-bin/Rakefile
We're using Bundler::GemHelper without requiring it
We're requiring `lib/chef/dist.rb` which requires files out
of `chef-config/lib/chef-config` which will escape into the
main fileset if we don't push that libdir on there.
(Also:  all of `lib/chef/dist.rb` and
`chef-config/lib/chef-config/dist.rb` needs to be pushed into
chef-utils and reading values into `lib/chef/dist.rb` from
the Chef::Config itself seems like the wrong flow of information)
=> Fixes to support unbundled rake use

.expeditor/release.omnibus.yml
These work now. We should ship them for 15 as well.
=> Add SLES 15 / Ubuntu 20.04 aarch64 builds

lib/chef/knife/yaml_convert.rb
Potential fix for #9766.
A quick and dirty fix for the problems @chefrycar found:
* First off, unquoted strings in yaml are just strings, so there's not much to be done there.
* Symbols were not allowed previously, so now they are.
* Arrays are no longer quoted.
* Hashes are another thing that are probably not handled properly, but I did not make an attempt to do anything there.
With this input file:
```
Petes-MBP:chef pete$ cat temp.yml
---
resources:
- type: "package"
name: "httpd"
action: install
- type: "service"
name: "httpd"
action:
- "enable"
- "start"
- type: "nachos"
name: "httpd"
action:
- :enable
- :start
```
I now get this output:
```
Petes-MBP:chef pete$ ./bin/knife yaml convert temp.yml
WARNING: No knife configuration file found. See https://docs.chef.io/config_rb/ for …
```
=> Fix symbols and arrays in yaml conversion tool

lib/chef/resource/chef_client_cron.rb
Signed-off-by: dhaneshr <dhanesh_r@live.com>
This change is in address to the issue reported. #9780
Modified the permission of the directory created by the client 
The solution can solve the directory permission for client.
=> Modified client cron directory permission

lib/chef/resource/chef_client_cron.rb
This makes it so we cleanup the right cron job on Solaris / AIX systems
that don't support cron_d
Fixes #9781
=> chef_client_cron: cleanup the appropriate cron job

lib/chef/provider/package/homebrew.rb, lib/chef/provider/package/macports.rb
This seems entirely unnecessary
=> Avoid setting package to macports and then overriding to homebrew

lib/chef/provider/package/windows.rb
Remove the overriding of the action block entirely and clean up some
overly complicated code.
In the process it looks like the "unknown" version codepath is blatantly
entirely unused, so it was removed.  A bunch of extra unnecessary
indirection was also removed.
=> Fix windows package super bug and cleanup

Rakefile, habitat/plan.ps1, scripts/ci/ensure-minimum-viable-hab.ps1
Needed to install the gems-from-git-repos first. Those are the least likely to have missing dependencies. Then we move on to installing the gems that live in subdirectories of this repo. Sometimes that fails for non-obvious reasons, but a retry seems to succeed.
Added some checks for previous status code after bare commands to exit the PowerShell script with failure when those bare commands fail.
This is #9738 but on a branch within this repo instead of from a fork.
- ~New feature (non-breaking change which adds functionality)~
- ~Breaking change (fix or feature that would cause existing functionality to change)~
- ~Chore (non-breaking change that does not add functionality or fix an issue)~
- ~I have updated the documentation accordingly.~
- ~I have added tests to cover my changes.~
=> fix Habitat Windows package build

Gemfile, Gemfile.lock, docs/dev/how_to/updating_dependencies.md, tasks/dependencies.rb
=> Pin chef-telementry to 1.0.3 to avoid ffi build breakage 

lib/chef/resource/msu_package.rb, lib/chef/resource/windows_package.rb, spec/unit/resource/windows_package_spec.rb
Due to the way the resource is built we need to be able to store an
array of current versions. I added some tests and comments so we don't
refactor this away later.
=> Fix windows_package not allowing version to be an array

lib/chef/provider/launchd.rb, lib/chef/provider/service/macosx.rb, spec/unit/provider/launchd_spec.rb
the refactoring to use the DSL (orthogonal to setting this up as
a unified_mode resource) meant we have to care about lexical scoping
now.
=> fix launchd provider for chef-16

lib/chef/mixin/properties.rb
Wrap this example code in a code fence so it looks nicer.
=> Fix a small rdoc formatting bug for `copy_properties_from`.

lib/chef/resource/windows_printer.rb
This restores the previous behavior
=> Only require the driver_name property when creating printer ports

chef-config/lib/chef-config/config.rb
The backport to Chef-15 made me realize that this all needs to be
deleted.
The :hints looks necessary to initialize that to a Hash and to
create the config context to begin with.
=> Remove the config hash defaults

scripts/bk_tests/bk_container_prep.sh, scripts/bk_tests/bk_run_choco.ps1, scripts/bk_tests/bk_win_functional.ps1, scripts/bk_tests/bk_win_integration.ps1, scripts/bk_tests/bk_win_unit.ps1
Rubygems is built into ruby and we're not updating it anymore in our
builds. We get the version that ships in Ruby
=> Stop upgrading rubygems in tests

scripts/bk_tests/bk_win_functional.ps1
This just fixes the windows functional verify tests to use the correct sha for rubyinstaller-devkit-2.6.6-1-x64.exe`
=> Update rubyinstaller-devkit-2.6.6-1-x64.exe SHA

lib/chef/resource/windows_security_policy.rb, lib/chef/resource/windows_user_privilege.rb
Signed-off-by: IanMadd <imaddaus@chef.io>
Updates examples in windows_security_policy and windows_user_privilege resources.
Resource examples were updated in chef/chef-web-docs#2488
This adds those examples to chef/chef
=> Add examples to windows_security_policy

lib/chef/provider/package/cab.rb, lib/chef/provider/powershell_script.rb
Simple fix to avoid these with shell_out
=> Avoid ruby deprecation warnings in cab_package and powershell_script

.expeditor/verify.pipeline.yml
The rubydistros containers are now built for Ruby 2.7 and 2.6. This uses the 2.7 containers to do our various tests and moves some of our other testing to the rubydistros 2.6 containers.
=> Test PRs against Ruby 2.7

.expeditor/config.yml, .expeditor/verify_private.pipeline.yml, kitchen-tests/Gemfile
kitchen is run on a linux container
Also rename the verify/public pipeline back to verify. This keeps the
history and is otherwise really just a bikeshed because they show up in
different buildkite sites.
=> Switch end-to-end-windows-10 back to use the Linux scripts

Gemfile.lock, omnibus/Gemfile.lock
=> Update Chefstyle to 1.0.5, Ohai to 16.1.1, and cheffish to 15.0.3

lib/chef/provider/launchd.rb, lib/chef/provider/service/macosx.rb, spec/functional/resource/launchd_spec.rb, spec/unit/provider/launchd_spec.rb
Fixes both of the errors in #9868 
Adds a dozen functional test which gains some useful test coverage.  A couple of the useless unit tests that failed to catch the errors (but did blow up after I fixed them) have been removed.
replaces #9867
closes #9788
=> Fixes and tests for Chef-16 regression in launchd

lib/chef/knife/core/windows_bootstrap_context.rb, spec/unit/knife/core/windows_bootstrap_context_spec.rb
This fixes bootstrapping on Windows. All credit goes to Chad Jessup <chad.jessup@gmail.com>
but since the original PR was left without DCO I'm replicating it here, with valid DCO.
=> fix windows bootstrap; replicate chef/chef/pull/9839 by Chad Jessup

lib/chef/resource/hostname.rb, spec/support/shared/functional/windows_script.rb
=> Fix ruby 2.7 keyword argument warning.

chef-utils/lib/chef-utils/dsl/architecture.rb, chef-utils/spec/unit/dsl/architecture_spec.rb
armv6l is Raspberry Pi 1/Zero
armv7l is Raspberry Pi 2,3,4 BeagleBone Black
Tested with Raspbian 10, Debian 10, Centos 7
This support was present in chef-sugar.
Signed-off-by: Matt Ray <github@mattray.dev>
=> Added armv6l and armv7l to arm? and armhf? helpers

lib/chef/knife/bootstrap/templates/windows-chef-client-msi.erb, lib/chef/knife/core/windows_bootstrap_context.rb
Similar to the changes in #9371, we need c_chef_dir and c_opscode_dir in Chef::Knife::Core::WindowsBootstrapContext to be able to be hinted to act as if on Windows for the purposes of bootstrapping a windows system from a linux system. This also means that hint getting all the way to PathHelper.cleanpath.
Also fixes #9844 by putting some black magic worksforme in the windows bootstrap batch script.
=> Fix bootstrapping windows from linux

spec/functional/resource/dnf_package_spec.rb
looks like it was always `dnf install whatever = 1.2.3` that was supported and the `dnf install whatever == 1.2.3` syntax was recently dropped.  whatever it is, we support what the underlying distro supports and now our tests are green.
=> fix dnf tests

.expeditor/verify.pipeline.yml, scripts/bk_tests/bk_win_functional.ps1
This PR modifies the verify pipeline to use the rubydistros project's windows-2019 ruby 2.6 image.
https://github.com/chef/chef/issues/9853
=> Modify verify pipeline to use rubydistros windows-2019 docker image

.expeditor/verify_public.pipeline.yml, scripts/bk_tests/bk_win_functional.ps1, scripts/bk_tests/bk_win_integration.ps1, scripts/bk_tests/bk_win_prep.ps1
This PR modifies the verify pipeline to use Ruby 2.7 on a Windows 2019 docker image.
https://github.com/chef/chef/issues/9853
=> Refactor verify pipeline to use Ruby 2.7 on Windows docker image

lib/chef/chef_fs/file_system/chef_server/cookbook_file.rb, lib/chef/digester.rb, lib/chef/encrypted_data_bag_item/decryptor.rb, lib/chef/encrypted_data_bag_item/encryptor.rb, lib/chef/key.rb, lib/chef/mixin/openssl_helper.rb, lib/chef/provider/user/dscl.rb, lib/chef/provider/user/mac.rb, lib/chef/resource/windows_certificate.rb, lib/chef/resource/windows_user_privilege.rb, spec/support/chef_helpers.rb, spec/unit/mixin/openssl_helper_spec.rb
There's a RuboCop cop to fix these before Ruby 3 breaks it.
=> Update our usage of OpenSSL::Digest to avoid Ruby 3 breaking change

habitat/plan.sh
=> Pin habitat bundler to 1.17.3

Gemfile.lock, omnibus/Gemfile.lock
This resolves the rubygems perf regression in the release that shipped in Ruby 2.7.x
=> Pull in updated omnibus-software for rubygems perf patch

lib/chef/resource.rb, spec/unit/resource_spec.rb
This is a breaking change to fix an intentionally breaking change in Chef 16.0 to remove the canonical DSL #9206 with unintended side effects #9885.  Breaking behavior differently, but correctly, without the side effects.
The new behavior is that a resource which relies upon the resource_name
statement to wire the resource up to the DSL will fail (although the
very old wiring of the "<cookbook_name>_<resource_filename>" continues
to work).
So for a resource which does not get its DSL wiring from the filename,
only declaring a resource_name will fail:
```
resource_name :foo
```
This can be fixed by adding an explicit `provides` line (which is
backwards compatible):
```
resource_name :foo
provides :foo
```
If backwards compatibility is not a concern, then post-16.0 the
resource_name call …
=> Chef-16.1 breaking change

lib/chef/provider/execute.rb, lib/chef/resource/apt_package.rb, lib/chef/resource/execute.rb
Given an `execute` resource like this:
```
Petes-MBP:chef pete$ cat test_execute_stdin.rb
execute "wc -l > test_execute_stdin_output" do
input <<-INPUT
1
2
3
4
5
INPUT
end
```
... the `input` property is passed to the command on STDIN:
```
Petes-MBP:chef pete$ chef-apply test_execute_stdin.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
* execute[wc -l > test_execute_stdin_output] action run
- execute wc -l > test_execute_stdin_output
Petes-MBP:chef pete$ cat test_execute_stdin_output
5
```
`mixlib-shellout` has [a pretty dire warning](https://github.com/chef/mixlib-shellout/blob/master/lib/mixlib/shellout.rb#L143-L148) about doing this, but I tested on my local macOS environment, an ubuntu 18.04 VM, and a Windows 2019 VM and …
=> Add an input property to the execute resource for passing input on STDIN

lib/chef/http.rb, lib/chef/http/ssl_policies.rb, lib/chef/provider/remote_file/http.rb, lib/chef/resource/remote_file.rb, spec/unit/http/ssl_policies_spec.rb
Different servers have different https requirements and enforcing
the API policy on all `remote_file` resources isn't reasonable.
The logic around the HTTP clients and policies in Chef is... complex.
This approach seemed like the best one, but I'm open to others.
By default here if the user specifies nothing, `remote_file`'s http
clients will fall back to the API policy, otherwise, it'll use whatever
the specify.
And yes, Tim, I can add tests, but first I want to make sure this
approach is palatable. :)
This fixes #8897
=> Add ssl_verify option for remote_file

lib/chef/knife/bootstrap.rb
This is messy but thankfully its is against a codebranch which
will become extinct.  This isn't a backport, but a genesplicing.
=> Additional Chef-16 knife config API compatibility

lib/chef/http.rb, lib/chef/provider/remote_file/http.rb
So it turns out the `berkshelf` has been passing it's entire `options`
hash into `Chef::HTTP` this whole time, which, we should probably fix.
However, one of those options was `:ssl_verify_mode`. We ignore entries
in the `options` hash we don't recognize so this was fine, but suddenly
we recognize it. But we expected it to be class, and they're passing
in symbols. Whoops!
This makes that all work and puts the symbol->class conversion inside
of `Chef::HTTP`.
=> Update to ssl_verify_mode on remote_file

lib/chef/resource/hostname.rb
We don't support Solaris 5.10 in Chef anymore so there's no reason to make this check every time the resource runs on Solaris 5.11
=> hostname: Remove support for Solaris 5.10

spec/spec_helper.rb
This reverts commit de8d3a3299a18d4bfd2b419cb1303258441a862a.
This code works fine within Workstation, but it fails hard with DK. We
need to keep the DK verify checks running with Chef 15 until both of
these codebases go away. For now just revert this and roll forward with
life in master where we have the new paths
=> Revert the change to the load paths in the specs

lib/chef/deprecated.rb, lib/chef/resource/archive_file.rb, spec/unit/resource/archive_file_spec.rb
FileUtils.mkdir_p expects the mode to be in octal form. We accept Integers, but Ruby doesn't have a way to tell if what the user passed was octal or not. The safest thing to do here is to only accept mode as a String and then convert it to octal form with .to_i(8). This adds a new deprecation and correctly sets the file mode value as octal. 
**Old behavior**
String mode: applies wrong permission
Base 10 mode: applies wrong permissions
Octal mode: Works
**New behavior**
String mode: Works
Base 10 mode: Works but throws a deprecation warning
Octal mode: applies the wrong permissions and throws a deprecation warning
=> archive_file: better handle mode property and deprecate Integer values

.expeditor/cleanup_orphaned_test_resources.sh, .expeditor/config.yml
The private verify pipeline currently uses Test Kitchen Azure to test against Windows 10.
Unfortunately this approach does not clean up after itself and orphaned resource groups are typically left behind.  If this is not taken care of we'll exhaust our resource pool (esp. public ips).
This commit simply adds a nightly (1am) script to delete the Azure resource groups associated with the private verify pipeline.
=> Add nightly cleanup of orphaned test resources

kitchen-tests/cookbooks/end_to_end/recipes/_zypper.rb, kitchen-tests/cookbooks/end_to_end/recipes/linux.rb, lib/chef/provider/zypper_repository.rb, spec/unit/provider/zypper_repository_spec.rb
gpg 2.2 changed the output without a major version bump. Now we need to
get the gpg version and then shell out the appropriate command to
determine the fingerprint.
Unit tests incoming as well as a kitchen test to exercise this using the nginx repo
=> Fix zypper_repository key handling on SLES 15+

spec/functional/resource/windows_task_spec.rb, spec/unit/mixin/user_context_spec.rb, spec/unit/property_spec.rb, spec/unit/resource/chef_client_scheduled_task_spec.rb, spec/unit/resource/windows_dns_record_spec.rb, spec/unit/resource/windows_dns_zone_spec.rb, spec/unit/resource/windows_task_spec.rb, spec/unit/resource/windows_uac_spec.rb, spec/unit/resource/yum_repository_spec.rb, spec/unit/resource_spec.rb
I'm running a subset of the tests repeatedly and this is the majority of the output:
```
WARNING: Using `expect { }.not_to raise_error(SpecificErrorClass)` risks false positives, since literally any other error would cause the expectation to pass, including those raised by Ruby (e.g. NoMethodError, NameError and ArgumentError), meaning the code you are intending to test may not even get reached. Instead consider using `expect { }.not_to raise_error` or `expect { }.to raise_error(DifferentSpecificErrorClass)`. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. Called from /Users/pete/work/chef/spec/unit/resource_spec.rb:381:in `block (4 levels) in <top (required)>'.
```
=> Fix rspec warning about `not_to raise_error` with a specific exception.

lib/chef/provider/batch.rb, lib/chef/provider/powershell_script.rb, lib/chef/provider/script.rb, lib/chef/provider/windows_script.rb, spec/unit/provider/batch_spec.rb, spec/unit/provider/powershell_script_spec.rb, spec/unit/provider/script_spec.rb, spec/unit/resource/powershell_script_spec.rb
Modifies the code for script resources to avoid writing temp files when not needed to avoid problems like the one described in #3563. 
There is some not-strictly-necessary cleanup on the Batch, PowershellScript, and WindowsScript providers that I did when I thought I was going to have to refactor the inheritance relationship between WindowsScript and the Script provider.
=> Change script resources to use pipes rather than writing to temp files

lib/chef/resource/chef_client_scheduled_task.rb, spec/unit/mixin/user_context_spec.rb
These tests were broken in #9937 because they are doing exactly what that warning was about: hiding a real exception. It also turns out that the test was wrong because that code is supposed to raise an exception in this case.
=> Fix wrong unit test exposed by cleaning up rspec deprecations.

lib/chef/data_bag.rb, spec/unit/data_bag_spec.rb
Signed-off-by: Snehal Dwivedi <sdwivedi@msystechnologies.com>
- updated exception `Chef::Exceptions::InvalidDataBagPath` message
Fixes:  https://github.com/chef/chef-vault/issues/333
https://github.com/chef/chef-vault/issues/321
=> knife vault on windows 10 fails due to ERROR: Chef::Exceptions::InvalidDataBagPath

lib/chef/knife/bootstrap.rb
This makes it really clear that you're not using the right protocol when you're bootstrapping a Windows node:
```
❰tsmith❙~/dev/work/chef(git✱knife_password)❱✘≻ bundle exec knife bootstrap 172.16.1.233 -U ubuntu
Connecting to 172.16.1.233
```
becomes
```
❰tsmith❙~/dev/work/chef(git✱knife_password)❱✘≻ bundle exec knife bootstrap 172.16.1.233 -U ubuntu
Connecting to 172.16.1.233 using ssh
```
=> Let the user know what protocol we're using in knife bootstrap

lib/chef/knife/bootstrap.rb, spec/unit/knife/bootstrap_spec.rb
We should highly encourage users to move to validatorless bootstrapping
1) It's more secure
2) It requires less admin work since there no validation key to pass
around or rotate
This also provides an improved message helping the user to move off the
old keys and fixes some bad formatting where the 2nd line was indented
about 40 columns.
=> Warn during bootstrapping when using validation keys

.expeditor/release.omnibus.yml
Debian 8 went EOL June 6th: https://endoflife.software/operating-systems/linux/debian
=> Stop producing packages for EOL Debian 8

lib/chef/knife/bootstrap/templates/chef-full.erb
Use `/etc/chef` for bootstrapping instead of ChefConfig because `is_windows` from https://github.com/chef/chef/blob/master/chef-config/lib/chef-config/config.rb#L79 run on native windows and returns true always which evaluates to `C:\chef` and causes failure to bootstrap from windows---->linux
Fixes https://github.com/chef/chef/issues/9914
=> Use /etc/chef for bootstrapping instead of ChefConfig

kitchen-tests/cookbooks/end_to_end/recipes/_snap.rb, kitchen-tests/cookbooks/end_to_end/recipes/linux.rb, lib/chef/provider/package/snap.rb, spec/unit/provider/package/snap_spec.rb
First and foremost this fixes the bug in which #8827 where
`snap_package` hangs forever.
See the comment in the code for the nitty-gritty details, but snap never
returns an EOF so you have to jump through GREAT hoops not to hang
forever.
UNLESS you want to use nonblock+read, but it takes MUCH longer:
```
[phil@ldt-hardwired ~]$ time /tmp/test.rb char
real    0m0.252s
user    0m0.207s
sys     0m0.044s
[phil@ldt-hardwired ~]$ time /tmp/test.rb select
real    0m5.244s
user    0m0.183s
sys     0m0.056s
```
That's just for doing `GET /v2/snaps/black`
Second, if you try to install a snap that doesn't exist on the `stable`
channel then Chef crashes with a `undefined method [] on nil`, so let's
check for that explicitly.
And a bunch of other fixes that were required to even install anything:
* …
=> Fix snap_package bugs

lib/chef/application/apply.rb, spec/unit/application_spec.rb
I recently discovered that when using ``Chef::Application::Apply.new.run(enforce_license: false)``, chef-apply will still run the license verification when I expected it to be disabled. It seems this feature works if you install this as a gem, however if you build chef using omnibus with this set, it refuses to work. I suspect this might be something with appbundler.
I noticed that other binaries (i.e. solo) were using ``run(enforce_license: false)`` instead of ``run(enforce_license = false)`` which chef-apply uses. If I changed this to ``run(enforce_license: false)``, this worked as expected.
=> Fix how enforce_license is set in run method for chef-apply

lib/chef/formatters/error_inspectors/compile_error_inspector.rb, lib/chef/formatters/error_inspectors/resource_failure_inspector.rb
Signed-off-by: Zeal Wierslee <zeal@wierslee.me>
Add "most recent call first" to traceback message
Chef's tracebacks are formatted so that the most recent call is first, and older calls are below it.
Many developers use programming languages (like ruby and python) which use the opposite style, which formats it's stack traces with the most recent line at the bottom, and older calls above that.
For this reason, developers more comfortable working in other environments might have difficultly parsing the stack traces at a glance, since the calls will be in the opposite order.
This PR simply adds a "most recent call first" message to the traceback message, so the traceback ordering is explicit.
#9966 
(Calling this a "bug" is probably generous, but I think that category fits best).
=> Add "most recent call first" to traceback message

lib/chef/resource/cron/_cron_shared.rb, lib/chef/resource/execute.rb
In execute remove some complex examples that weren't adding much.  Also cleanup some of the ruby code so that it would pass cookstyle. Also improve the dist values we use, random formatting, and how we specify notes so they get parsed out correctly.
=> Cleanup more resource examples

spec/unit/util/threaded_job_queue_spec.rb
Before this, you'd see this confusing output:
```
Petes-MBP:chef pete$ rspec spec/unit/util/threaded_job_queue_spec.rb
WARNING: Shared example group 'with a chef repo' has been previously defined at:
/Users/pete/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/cheffish-16.0.2/lib/cheffish/rspec/repository_support.rb:12
...and you are now defining it at:
/Users/pete/work/chef/spec/support/shared/integration/integration_helper.rb:109
The new definition will overwrite the original one.
Run options:
include {:focus=>true}
exclude {:provider=>#<Proc:./spec/spec_helper.rb:210>, :arch=>#<Proc:./spec/spec_helper.rb:204>, :choco_installed=>true, :ruby=>"2.6.6", :chef=>"16.2.38", :not_intel_64bit=>true, :rhel_gte_8=>true, :rhel8=>true, …
```
=> Silence exception output in threaded test.

.expeditor/verify_public.pipeline.yml
To prevent developer annoyance, run the spellchecker in CI but don't let it fail builds.
=> Soft fail spellchecker in ci

lib/chef/resource/windows_audit_policy.rb
Originally coded this with a `.empty?` method so that it wouldn't iterate over subcategories if nobody was using the subcategory property.  However, not entering a value results in a `nil` value, not an empty array. So the test has been modified with a `.nil?` instead.
I didn't open an issue as I just found this last night, and wanted to get the fix I tested manually into a PR, hopefully before the next stable release of 16.2 comes out
=> Fix for windows_audit_policy bug for when a value for the subcategory property isn't entered

lib/chef/resource.rb, spec/unit/resource_spec.rb
Adds a umask property for all resources. Implements #3741.
Given a file resource like this:
```
Petes-MBP:chef pete$ cat ../test_file_resource.rb
file '/tmp/index.php' do
content '<html>This is a placeholder for the home page.</html>'
umask '111'
end
```
Running this with `chef-apply` creates the file with mode `0666`:
```
Petes-MBP:chef pete$ rm /tmp/index.php && chef-apply ../test_file_resource.rb && ls -l /tmp/index.php
Recipe: (chef-apply cookbook)::(chef-apply recipe)
* file[/tmp/index.php] action create
- create new file /tmp/index.php
- update content in file /tmp/index.php from none to 3d079e
--- /tmp/index.php  2020-06-15 18:33:40.877388343 -0700
+++ /tmp/.chef-index20200615-78177-e907h5.php       2020-06-15 18:33:40.877069714 -0700
@@ -1 +1,2 @@
+<html>This is a placeholder for …
```
=> Add a umask property for resources.

lib/chef/resource/windows_security_policy.rb
adds a couple of policies to the list of allowed security policies for the windows_security_policy resource.
Added policies are `LockoutDuration` and `ResetLockoutCount`
=> Update the list of allowed policies for the windows_security_policy resource

kitchen-tests/cookbooks/end_to_end/recipes/windows.rb, lib/chef/resource/windows_security_policy.rb
windows_security_policy broke with the 16.2 rollout of chef-client because it hadn't been udpated from using `resource_name` to using `provides`
=> windows_security_policy was using resource_name instead of provides

lib/chef/knife/config_use_profile.rb, spec/integration/knife/config_use_profile_spec.rb
After fix output:  "when user provides profile which does not exist in credentials file"
```
bundle exec knife config use-profile test -c ~/workspace/hosted-chef-repo/chef-repo/.chef/knife.rb 
ERROR: ChefConfig::ConfigurationError: Profile test doesn't exist. Please add it to /home/msys/.chef/credentials and if it is profile with DNS name check that you are not missing single quotes around it as per docs https://docs.chef.io/workstation/knife_setup/#knife-profiles.
```
#9686
=> Fix for knife config use-profile doesn't validate that the profile exist

lib/chef/resource/alternatives.rb, lib/chef/resource/dmg_package.rb, lib/chef/resource/ssh_known_hosts_entry.rb, lib/chef/resource/sudo.rb, lib/chef/resource/swap_file.rb, lib/chef/resource/timezone.rb
Also update the sudo resource command description based on an escalation. The commands need to be the full path to the command not just the command.
=> Add more examples to the resource code

lib/chef/resource/archive_file.rb
This way it always gets called in the action, but we can still avoid
spec failures on systems that don't have ffi-libarchive
=> archive_file: move ffi-libarchive into a simple helper method

lib/chef/provider/package/powershell.rb, spec/unit/provider/package/powershell_spec.rb
Fix Windows Server 2012 - 2016 to use TLS 1.2
Signed-off-by: sanga17 <sausekar@msystechnologies.com>
=> Fixed Powershell_Package does not throw error when it cannot connect to powershell gallery

lib/chef/deprecated.rb, lib/chef/resource/archive_file.rb, spec/unit/resource/archive_file_spec.rb
FileUtils.mkdir_p expects the mode to be in octal form. We accept Integers, but Ruby doesn't have a way to tell if what the user passed was octal or not. The safest thing to do here is to only accept mode as a String and then convert it to octal form with .to_i(8). This adds a new deprecation and correctly sets the file mode value as octal. 
**Old behavior**
String mode: applies wrong permission
Base 10 mode: applies wrong permissions
Octal mode: Works
**New behavior**
String mode: Works
Base 10 mode: Works but throws a deprecation warning
Octal mode: applies the wrong permissions and throws a deprecation warning
=> archive_file: better handle mode property and deprecate Integer values 

lib/chef/knife/bootstrap.rb, spec/unit/knife/bootstrap_spec.rb
Force subclasses to use the `config` hash directly.
This should not affect any knife plugins shipping in chef-workstation
since the calls to config_value have already been removed from all of
those plugins.  The multiple-argument version of config_value was not
actually used anywhere in those plugins and the single value version
was removed and replaced with accessing the config hash.  Since that
was introduced sometime in 15.x when the bootstrap changes went in,
it is not expected that many external knife plugins have picked up
the usage of config_value.
=> More aggressively deprecate config_value

lib/chef/knife/cookbook_upload.rb
Prevents these warnings:
/Users/pete/work/chef/lib/chef/knife/cookbook_upload.rb:26: warning:
already initialized constant Chef::Knife::CookbookUpload::CHECKSUM
/Users/pete/work/chef/lib/chef/knife/cookbook_upload.rb:26: warning:
previous definition of CHECKSUM was here
/Users/pete/work/chef/lib/chef/knife/cookbook_upload.rb:27: warning:
already initialized constant Chef::Knife::CookbookUpload::MATCH_CHECKSUM
/Users/pete/work/chef/lib/chef/knife/cookbook_upload.rb:27: warning:
previous definition of MATCH_CHECKSUM was here
=> Inline some constants to prevent redefenition warnings in tests.

habitat/plan.ps1
fixes #9754
This requires https://github.com/chef/chef-powershell-shim/pull/11 and for that chef-powershell-shim package to be build, uploaded and promoted.
This consumes that package which sets the `RUBY_DLL_PATH` and also `CHEF_POWERSHELL_BIN` which with the changes to the shim wrapper code will be where the .Net clr will look for the shim .net assemblies (Chef.Powershell.dll and Newtonsoft.Json.dll).
To test I built and uploaded to my mwrock origin and then built this in my mwrock origin and then ran:
```
hab pkg exec mwrock/chef-infra-client chef-apply.bat -e "puts (powershell_exec('write-output
`$PSVersionTable')).result"
```
This produced the expected powershell json result.
=> consume powershell shim DLLs from hab package

.expeditor/verify_public.pipeline.yml
🚧 will probably break berks at least until the latest PR there gets merged
=> Bump the external tests to 2.7

lib/chef/resource/windows_user_privilege.rb
It would be useful to have an action in the windows_user_privilege resource that would allow you to easily remove all users from using a Windows user right.  This pull request adds a `:clear` action that does this, by looking for any users assigned a specific user right and then removing them.
It would work like this:
```ruby
windows_user_privilege 'Allow any user the Network Logon right' do
privilege      'SeDenyNetworkLogonRight'
action         :clear
end
```
=> Update the windows_user_privilege resource to have a `:clear` action

habitat/tests/spec.ps1
The windows service that gets started in the windows service functional tests will not inherit the current shell's environment. So it fails because it's `GEM_PATH` is not set and therefore is unable to consume the `win32-service` gem. This adds the `chef-infra-client` packages `GEM_PATH` to the machine scoped `GEM_PATH`.
=> fix habitat based windows service tests

lib/chef/chef_fs/file_system/chef_server/cookbook_file.rb, lib/chef/digester.rb
We're going to have to figure out how to work around this before Ruby 3.0 this the constants go away.
=> Revert openssl digest update that broke FIPS

lib/chef/resource.rb, spec/unit/resource_spec.rb
Followup to #10000. As we're finding out in #10068, `File.umask` is not supported on Windows and its causing a test failure there. FWIW, Ruby skips umask tests if they're run [on Windows](https://github.com/ruby/ruby/blob/5c276e1cc91c5ab2a41fbf7827af2fed914a2bc0/spec/ruby/core/file/umask_spec.rb#L19-L47) or [non-POSIX systems](https://github.com/ruby/ruby/blob/204dc3f39f12b4e2640555306bd1dd4530344277/test/ruby/test_file_exhaustive.rb#L787-L795).
I should have caught this in #10000. 😞 
=> Update tests and docs for umask on Windows.

spec/unit/chef_fs/diff_spec.rb
We merged #10052 before realizing that the bug was actually upstream in diff-lcs and fixing that in #10057. The tests now pass without the changes from #10052 so we should revert them because they are unnecessary.
=> Revert "Merge pull request #10052 from chef/fix-diff-tests"

Gemfile.lock, chef.gemspec, omnibus/Gemfile.lock, omnibus/README.md, omnibus/config/software/more-ruby-cleanup.rb, omnibus/files/openssl-customization/windows/ssl_env_hack.rb, omnibus/omnibus.rb
- Pin diff-lcs since 1.4 has changed the output.  
- Bump Ohai and other deps while here. 
- Update some omnibus docs and comments to make diffing with workstation better and the docs a bit more accurate.
- Bring in the .gitkeep cleanup from Workstation to nuke those files in the install
=> Pin dff-lcs, bump ohai, & misc omnibus updates

spec/functional/resource/aix_service_spec.rb, spec/functional/resource/msu_package_spec.rb
Followup to #10088 and #10089. Still seeing failures but a lot fewer this round.
https://buildkite.com/chef/chef-chef-master-omnibus-release/builds/616#0a82bdc2-3ce8-4936-acdc-b69b56dd8fe3/5428-13593
=> Fix release build tests, part 3

lib/chef/application.rb, lib/chef/client.rb, spec/functional/resource/aix_service_spec.rb
This forces the formatter output off for users that use the
winevt or syslog options to the log_location.
This changes nothing about the logging behavior from Chef-15, those
never supported formatter output.
It creates some more clear consistency with how STDOUT behaves when
those options are used.
- We do not have the ability (fairly fundamentally in the Chef::Log
class itself) to have different log levels running at the same time
so either you get :warn or you get :info and we'll likely never
be able to support mix-and-match.
- Without mix-and-match if you're trying to use the formatter on
STDOUT the syslog logger you have to either pick :warn -- which
makes the syslog output totally useless, or else pick :info --
which intersperses all of the info logger output with the
formatter on …
=> Fix syslog logging on Chef-16

kitchen-tests/cookbooks/end_to_end/recipes/macos.rb, lib/chef/resource/build_essential.rb
This avoids a giant output in logs that includes our comments
=> Use bash not execute in build_essential for better output

chef-config/lib/chef-config/dist.rb, lib/chef/knife/bootstrap.rb
As a user of a community Chef distribution, I would like to be able to use knife
bootstrap without requiring the license check [1]. It's expected that that user
would not be installing a licensed version of Chef Infra Client, but instead a
community distribution.
This provides a similar feature as used in other places which makes it much
easier to disable the license check.
[1] https://gitlab.com/cinc-project/distribution/workstation/-/issues/3
=> Implement ENFORCE_LICENSE dist constant for knife bootstrap

lib/chef/node_map.rb
Update the message to reflect what's actually happening, remove the evil
double space after the period, and use branding.
=> Fix warning message for cb / core resource conflict

spec/unit/mixin/powershell_exec_spec.rb
This test was running the same code as the one right above it and expecting a different result.
=> Fix `powershell_exec!` test.

Gemfile.lock, chef-config/lib/chef-config/version.rb, chef-universal-mingw32.gemspec, chef-utils/lib/chef-utils/version.rb, lib/chef/version.rb, omnibus/Gemfile.lock
This release just drops Ruby 2.4 support and resolves Rubocop warnings.
=> Allow iso8601 gem version 0.13

lib/chef/resource/windows_dns_record.rb
This allows for managing DNS records on a remote DNS server
#10119
=> windows_dns_record: add dns_server property with default of localhost

spec/unit/provider/systemd_unit_spec.rb
The systemd resource has a `user` property but no `password`, and `Mixlib::Shellout` fails when setting a user with no password on Windows. This should only reasonably happen while running the unit tests on Windows, so guard against that case.
=> Fix systemd unit test on Windows.

spec/support/shared/integration/knife_support.rb
`cache_options` is deprecated and this is one of the last few references to it in the code.
https://github.com/chef/chef/blob/master/chef-config/lib/chef-config/config.rb#L804-L813
=> Remove reference to deprecated option in test helper.

lib/chef/knife/ssh.rb, spec/functional/knife/ssh_spec.rb
net-ssh 6.0 disabled these legacy keys by default. We need to enable the
support by passing this option.
=> Support legacy DSS host keys with knife-ssh

spec/integration/recipes/recipe_dsl_spec.rb, spec/unit/property_spec.rb
RuboCop 0.87 expanded this cop to detect these uses of non-ASCII
characters.
=> Disable Naming/AsciiIdentifiers in our specs

lib/chef/mixin/openssl_helper.rb
Attempt to locate `openssl.cnf` if it isn't in the default location indicated by OpenSSL. This initially seemed like a much bigger deal, but is apparently not really an issue.
https://github.com/ruby/openssl/blob/016a4f8cc48f6ec62c6fac06f20e22e46e92a84f/test/openssl/test_config.rb#L28-L35
https://bugs.ruby-lang.org/issues/6830 
=> Fix openssl config tests on Windows

spec/unit/provider/package/dnf/python_helper_spec.rb
Running this unit test on Windows gives a strange error:
```
3) Chef::Provider::Package::Dnf::PythonHelper propagates stacktraces on stderr from the forked subprocess
Failure/Error: expect { helper.package_query(:whatprovides, "tcpdump") }.to raise_error(/your hands in the air/)
expected /your hands in the air/, got #<ArgumentError: wrong file descriptor (5)> with backtrace:
```
While investigating trying to fix this test, I noticed that the code and spec for the yum version of this was very similar, except the yum version's spec is gated to only run on `:rhel`:
https://github.com/chef/chef/blob/master/spec/unit/provider/package/yum/python_helper_spec.rb#L25
Given that these two pieces of code are so similar, it seems likely that if one of them is only tested on RHEL the other should be …
=> Don't run the dnf test that Windows doesn't like on Windows.

spec/unit/win32/security_spec.rb
Fix two warnings that get logged while running this test:
```
<internal:warning>:43:in `warn': Mocks.configuration.allow_message_expectations_on_nil` to `true`. To disallow expectati
ons on `nil`, set `RSpec::Mocks.configuration.allow_message_expectations_on_nil` to `false`. Called from C:/vagrant/chef/spec/
unit/win32/security_spec.rb:86:in `block (4 levels) in <top (required)>'. (StructuredWarnings::BuiltInWarning)
```
and
```
<internal:warning>:43:in `warn': xceptions::Win32APIError: The filename, directory name, or volume label syntax is incorre
ct.
---- Begin Win32 API output ----
System Error Code: 123
System Error Message: The filename, directory name, or volume label syntax is incorrect.
---- End Win32 API output ----
>. Instead consider providing a specific error class or …
```
=> Fix two warnings in tests.

.expeditor/habitat-test.pipeline.yml
This PR fixes a typo in the `habitat-test.pipeline.yml` that caused the windows habitat validation to error:
https://buildkite.com/chef/chef-chef-master-habitat-test/builds/272#d31a4a70-77cf-4e07-9dc0-fc16f368997e/95-99
#9282
=> Fix extra quote in habitat test pipeline config

lib/chef/resource/execute.rb, spec/unit/resource/execute_spec.rb
The `execute` resource accepts an integer or string for the `user` parameter. There is some code that attempts to parse a domain name out of the `user` value that was blowing up if it was passed an integer.
With a simple resource like this:
```
bash "something" do
user 501
code "echo $(id)"
end
```
Running it would produce output like this:
```
Petes-MBP:chef pete$ sudo chef-apply test_bash_resource.rb  --log-level=debug
Password:
[2020-07-13T18:09:47-07:00] DEBUG: Reading products and relationships...
[2020-07-13T18:09:47-07:00] DEBUG: Successfully read products and relationships
[2020-07-13T18:09:47-07:00] DEBUG: Searching for the following licenses: ["infra-client", "inspec"]
[2020-07-13T18:09:47-07:00] DEBUG: Found license …
```
=> Fix execute resource with integer user parameter.

lib/chef/knife/cookbook_upload.rb, spec/integration/knife/cookbook_upload_spec.rb
- Fixed windows cookbooks upload issue.
- Updated cookbook_path option used  File::PATH_SEPARATOR to split path.
- Added rspec for upload multiple paths cookbooks.
#10082
=> Fixed `knife cookbook upload -o` windows path issue

spec/unit/provider/service/windows_spec.rb
Saw this one on CI:
```
/workdir/spec/unit/provider/service/windows_spec.rb:26: warning: already initialized constant Chef::ReservedNames::Win32::Security
/workdir/vendor/bundle/ruby/2.6.0/gems/rspec-mocks-3.9.1/lib/rspec/mocks/mutate_const.rb:229: warning: previous definition of Security was here
```
=> Use rspec constant stubbing.

omnibus/package-scripts/angrychef/postinst, omnibus/package-scripts/angrychef/postrm, omnibus/package-scripts/chef/postinst, omnibus/package-scripts/chef/postrm
We don't produce smartos packages and we never have. There's no reason
to carry around this baggage.
=> Remove smartos detection / support in our package scripts

lib/chef/knife/core/subcommand_loader.rb, lib/chef/knife/rehash.rb
This way we can use them in chef-cli to rehash any time we install a
gem.
=> Move the rehash methods into the subcommand loader

spec/functional/resource/windows_user_privilege_spec.rb, spec/functional/run_lock_spec.rb, spec/functional/util/powershell/cmdlet_spec.rb, spec/functional/version_spec.rb, spec/unit/data_collector_spec.rb, spec/unit/json_compat_spec.rb, spec/unit/knife/cookbook_upload_spec.rb, spec/unit/provider/ifconfig_spec.rb, spec/unit/provider/package/smartos_spec.rb, spec/unit/provider/service/redhat_spec.rb, spec/unit/resource_reporter_spec.rb, spec/unit/run_lock_spec.rb, spec/unit/scan_access_control_spec.rb
Running the unit tests on Windows I noticed that because of some funky ways used to require `spec_helper` that it was being loaded twice and I was getting warnings:
```
PS C:\vagrant\chef> bundle exec rspec .\spec\unit\provider\package\smartos_spec.rb .\spec\unit\provider\package\yum\python_hel
per_spec.rb
<internal:warning>:43:in `warn': opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/cheffish-16.0.2/lib/cheffish/rspec
/repository_support.rb:12
...and you are now defining it at:
//vboxsvr/vagrant/chef/spec/support/shared/integration/integration_helper.rb:109
The new definition will overwrite the original one. (StructuredWarnings::BuiltInWarning)
//vboxsvr/vagrant/chef/spec/spec_helper.rb:89:in `<top (required)>': already initialized constant OHAI_SYSTEM (StructuredWarni …
```
=> Avoid requiring spec_helper more than once

CHANGELOG.md
The original PR title where I updated the windows_security_policy resource to use powershell_out instead of powershell_exec didn't actually reflect what was updated. I updated the PR title after the Changelog was updated, but thought the better, more self explanatory title should also make it into the changelog.
#10107
=> update changelog reference to pull request for windows_security_policy 32bit windows compatibility PR

lib/chef/chef_fs/file_system/chef_server/cookbooks_dir.rb, lib/chef/cookbook_loader.rb, lib/chef/knife/cookbook_upload.rb, spec/unit/knife/cookbook_upload_spec.rb
An attempt at fixing #9860.
Some of the cheffish tests fail intermittently on CI: https://buildkite.com/chef-oss/chef-chef-master-verify/builds/5295#cfb74720-f5be-455e-8ba4-3bde3ed4cd0a
Running these tests locally, the same 3 tests fail consistently (with an occasional success), either getting the 404 HTTP error or various errors about being unable to read files:
```
1) Chef::Resource::ChefMirror When the Chef Zero server is in multi-org mode cookbook upload, chef_repo_path and versioned_cookbooks when the chef repo has cookbooks in non-versioned format chef_mirror :upload uploads everything
Failure/Error:
paths.collect!{|d| raise Errno::ENOENT, d unless File.exist?(d); d.dup}.each do |path|
path = path.to_path if path.respond_to? :to_path
enc = path.encoding == Encoding::US_ASCII ? …
```
=> Remove cookbook uploader global state

chef-utils/lib/chef-utils/dsl/path_sanity.rb, chef-utils/lib/chef-utils/dsl/service.rb, chef-utils/lib/chef-utils/internal.rb, lib/chef/dsl/platform_introspection.rb, lib/chef/mixin/chef_utils_wiring.rb, lib/chef/mixin/shell_out.rb, lib/chef/mixin/which.rb, lib/chef/platform/service_helpers.rb, lib/chef/provider/service.rb, lib/chef/resource/service.rb, spec/unit/mixin/shell_out_spec.rb
Okay I think I made some improvements which make this whole framework bound a lot less tightly bound to "global state" and calling class methods.  The `ChefUtils.systemd?` calling convention may be somewhat of a bad idea, but after ripping some of that out I put it back in due to not wanting to break public APIs, and I believe that this does not break public APIs.
What I did do though is in some of the modules that referenced class names, I instead switched to mixin in those modules and then calling the methods, which I believe (going forwards) is the more correct way of writing these -- it makes it easier to include those methods into external classes and override things like the __transport_connection, whereas if they call class methods then external software consumers would need to …
=> Extract shell_out helper method to chef-utils for reuse in ohai, etc

omnibus/Gemfile.lock, omnibus/config/software/more-ruby-cleanup.rb
These are confirmed safe and we do them in omnibus now.
=> Move some Ruby omnibus cleanup to omnibus-software

Gemfile.lock, chef.gemspec
The refactoring to chef-utils requires this new mixlib-shellout.
=> require mixlib-shellout 3.1.1+ and pull in new ohai

spec/functional/knife/ssh_spec.rb, spec/spec_helper.rb, spec/support/chef_helpers.rb, spec/support/shared/functional/file_resource.rb, spec/unit/application_spec.rb
Set the log level to :fatal for all tests after resetting the logger. Attempted fix for #10186.
=> Set log level to :fatal in test to prevent excess logging.

lib/chef/resource_inspector.rb
Rescue argumenterrors and just return the array unsorted.
I'd flip the inspect and sort, but that would result in incorrectly
sorted data.
=> Fix chef-resource-inspector to handle classes in equal_to

lib/chef/mixin/which.rb, spec/unit/mixin/which.rb
literally one character bugfix.
little bit surprised that only the el6 selinux tests blew up.
=> fix el6 selinux

.expeditor/config.yml
This functionality currently does not work so we need to disable it.
=> Disable docker in Expeditor for now

kitchen-tests/cookbooks/end_to_end/recipes/windows.rb, lib/chef/resource/hostname.rb
This improves the log output and probably speeds up the run since we're
not writing out a temporary script file anymore and then executing it. I
also removed some delcare_resource uses since we enabled unified_mode
for this resource. There's a ton more to remove here.
Fixes #9823
=> Use powershell_out vs. powershell_script in hostname

spec/unit/http/api_versions_spec.rb, spec/unit/server_api_spec.rb
`spec/unit/http/api_versions_spec.rb` could not run by itself because it had an unspecified dependency on a class defined in `spec/unit/server_api_spec.rb`. The code is kinda ugly, but defining constants in your specs is a bad practice IMO.
=> Define local test variables to avoid test load order bug.

lib/chef/http.rb, lib/chef/http/authenticator.rb, lib/chef/server_api_versions.rb, spec/unit/server_api_spec.rb
We generally always do protocol negotiation on the get of the node
object and the Chef::Node is an unversioned API, so we need to
test that we backoff the API version to the highest version the server
offers and then retry again.
=> Fix protocol negotiation for unversioned objects

.expeditor/build.docker.yml, .expeditor/update_version.sh, dobi.yaml
Chef used to use the EXPEDITOR_VERSION from the workload's metadata
when building images, reintroduce that so we can keep the same
functionality as before so that the VERSION of the repo can be bumped
but the docker images can be built off of the version being promoted.
Signed-off-by: Nathaniel Kierpiec <nkierpiec@chef.io>
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have read the **CONTRIBUTING** document.
- [x ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
=> Introduce EXPEDITOR_VERSION for docker image tag

cspell.json
=> Add a spellcheck exception for a word that snuck in.

spec/integration/knife/config_get_profile_spec.rb, spec/integration/knife/config_get_spec.rb, spec/integration/knife/config_list_profiles_spec.rb, spec/integration/knife/config_use_profile_spec.rb, spec/integration/knife/diff_spec.rb, spec/integration/knife/download_spec.rb, spec/integration/knife/upload_spec.rb, spec/support/shared/integration/integration_helper.rb
Because I get annoyed seeing this warning whenever I run tests:
```
WARNING: Shared example group 'with a chef repo' has been previously defined at:
/Users/pete/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/cheffish-16.0.2/lib/cheffish/rspec/repository_support.rb:12
...and you are now defining it at:
/Users/pete/work/chef/spec/support/shared/integration/integration_helper.rb:109
The new definition will overwrite the original one.
```
90% of the lines changed in this PR are indentation changes so viewing this with whitespace changes turned off will likely make this much more readable: https://github.com/chef/chef/pull/10232/files?w=1
=> Fix warning in test for redefined shared example group

omnibus/Gemfile.lock
new ca-certs file
curl w/o support for imap,smtp,gopher etc
libarchive w/o bsdcat binary
=> Update omnibus-software to slim our builds

omnibus/package-scripts/angrychef/postinst, omnibus/package-scripts/angrychef/postrm, omnibus/package-scripts/chef/postinst, omnibus/package-scripts/chef/postrm
Make sure we always detect darwin even if the output changes.
=> Make sure darwin is always detected

spec/unit/node/immutable_collections_spec.rb
This test reliably fails in my local env after I did some system updates, most likely related to this change in the recent libyaml-0.2.5 release: https://github.com/yaml/libyaml/pull/186
```
Petes-MBP:chef pete$ rspec spec/unit/node/immutable_collections_spec.rb
WARNING: Shared example group 'with a chef repo' has been previously defined at:
/Users/pete/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/cheffish-16.0.2/lib/cheffish/rspec/repository_support.rb:12
...and you are now defining it at:
/Users/pete/work/chef/spec/support/shared/integration/integration_helper.rb:109
The new definition will overwrite the original one.
Run options:
include {:focus=>true}
exclude {:provider=>#<Proc:./spec/spec_helper.rb:211>, …
```
=> Compensate for libyaml changes in yaml parsing test.

lib/chef/resource/windows_feature_powershell.rb, spec/unit/resource/windows_feature_powershell_spec.rb
windows features were not getting installed when it's InstallState was `Removed`
- This change handles installing features when state is removed or disabled(available)
- Works for single as well as multi-feature installation
- Earlier intersection of the features returned nil when state was `Removed` so feature was not getting installed.
- Ensured `Idempotent`  for the `windows_feature_powershell`
- Redundant test removed
Fixes https://github.com/chef/chef/issues/9536
```
PS C:\Users\Administrator\chef> Get-WindowsFeature -Name NET-Framework-Core
Display Name                                            Name                       Install State
------------                                            ---- …
```
=> Fix install windows features when install state is removed

omnibus_overrides.rb
More than likely we're going to need this to support the mac arm boxes. It has support for universal binaries on the mac. It's specific to PPC/Intel, but it's closer. This also has a bunch of PPC and aarch64 fixes. It's many many years of dev work compared to 3.2.1 which we used before.
=> Update libffi to 3.3

cspell.json, omnibus/config/software/more-ruby-cleanup.rb
Nuke more useless files in gems
Remove all the empty gem dirs for the ruby built in gems so we can skip shipping 41 empty folders
=> Cleanup more files from our package's gem installs

lib/chef/resource/apt_repository.rb, lib/chef/resource/windows_firewall_profile.rb
We still had a few of these. Avoid creating the match object.
=> Use .match? when we don't need data from a regex match

lib/chef/util/backup.rb
It's faster. See https://github.com/rubocop-hq/rubocop-performance/pull/130
=> Use sort.reverse instead of sort { |a, b| b <=> a }

lib/chef/property.rb, lib/chef/provider/template/content.rb, lib/chef/provider/user/dscl.rb, lib/chef/resource.rb
We don't need to create an array that we then search when we can just search the hash.
=> Use .key? instead of keys.include

lib/chef/resource/windows_share.rb
This is faster when you don't need a regex
=> Use tr not gsub for string replacement

lib/chef/run_context/cookbook_compiler.rb
Avoid creating an array only to count it.
=> Use .count instead of .select{}.count

lib/chef/mixin/openssl_helper.rb, lib/chef/resource/openssl_dhparam.rb, lib/chef/resource/openssl_ec_private_key.rb, lib/chef/resource/openssl_ec_public_key.rb, lib/chef/resource/openssl_rsa_private_key.rb, lib/chef/resource/openssl_rsa_public_key.rb, lib/chef/resource/openssl_x509_certificate.rb, lib/chef/resource/openssl_x509_crl.rb, lib/chef/resource/openssl_x509_request.rb
Mostly does what the title says, there wasn't much that depended on
compile/converge ordering and mostly this might fix a bug or two
in intention.
Renamed a method that had a misspelling.
Used tap in two places.
Removed the mutation of the new_resource in two places which is
the most disruptive part of this change.
=> Convert openssl resources to unified_mode

lib/chef/provider/cron/unix.rb, lib/chef/provider/group.rb, lib/chef/provider/ifconfig.rb, lib/chef/provider/mount.rb, lib/chef/provider/package.rb, lib/chef/provider/service/openbsd.rb, lib/chef/provider/systemd_unit.rb, lib/chef/provider/windows_task.rb
No need for this in the providers.
=> Remove unnecessary Mixin::ShellOut in providers

lib/chef/resource/windows_font.rb, spec/functional/resource/windows_font_spec.rb
When using the `windows_font` resource the first pass works appropriately, but on the second pass it fails to detect the font is already installed. This causes windows to give a prompt stating
```
The <name> font is already installed. Do you want to replace it?
```
Over winrm this causes the run to just hang, but locally you can cancel or accept.
Fixes https://github.com/chef/chef/issues/8779
=> Fix second chef run hang for windows_font resource

omnibus/Gemfile.lock
=> Remove lzma and bzip binaries from our builds

habitat/plan.ps1, habitat/plan.sh, omnibus/omnibus-test.sh, tasks/bin/run_external_test, tasks/rspec.rb
multi-job bundle install is the default in the next release, but for now
we should make sure we set it everywhere.
=> Speed up our bundle installs by always running 3 jobs

omnibus/config/software/more-ruby-cleanup.rb
Neither of these libraries let you skip building these. Directory cleanup has been removed since that happens in the omnibus-software ruby-cleanup def.
=> Cleanup extra binaries from libxml2 and libxslt

tasks/spellcheck.rb
Gives a nicer error message when cspell is not installed:
```
Petes-MBP:chef pete$ npm uninstall -g cspell
removed 87 packages in 0.617s
Petes-MBP:chef pete$ rake spellcheck
cspell is needed to run the spellcheck tasks. Run `npm install -g cspell` to install.
For more information: https://www.npmjs.com/package/cspell
```
=> Update spellcheck config with nice stuff from other repos.

kitchen-tests/cookbooks/end_to_end/recipes/linux.rb, lib/chef/resource/chef_client_systemd_timer.rb
Get the actual systemd action right. Add a kitchen test for this as well.
=> chef_client_systemd_timer: Fix failures in the :remove action

lib/chef/provider/powershell_script.rb, lib/chef/resource/execute.rb, lib/chef/resource/powershell_script.rb, spec/unit/provider/powershell_script_spec.rb, spec/unit/resource/powershell_script_spec.rb
Some code I had sitting in a local branch. If I remember right this was part of a bigger change that I abandoned and I forgot to PR the remainder.
=> powershell_script: Use native properties and don't coerce user provided flags with powershell defaults

spec/unit/resource/execute_spec.rb
This test defines a `shared_context` and then immediately includes it. Lots of indentation changes so view this one with whitespace turned off.
=> Remove an unnecessary shared_context from execute resource tests

spec/support/shared/unit/script_resource.rb, spec/support/shared/unit/windows_script_resource.rb, spec/unit/resource/batch_spec.rb, spec/unit/resource/powershell_script_spec.rb, spec/unit/resource/script_spec.rb
Followup to #10274. In these tests it is easy to introduce a recursive `let` reference because of all the shared context indirection going on. The big changes are to stop using instance variables and to use more specific variable names in the shared contexts.
=> Clean up some interdependencies in script resource tests.

lib/chef/action_collection.rb, lib/chef/data_collector/run_end_message.rb, spec/unit/data_collector_spec.rb
- Resources with `ignore_failure true` error backtrace and detail are not populating to A2.
- In order to solve this add error_description to action_collection of the resource-based object.
- Add error hash message class, message, and detail to end-run message resource object.
https://github.com/chef/chef/issues/10099
=> client-run per resource error detail

lib/chef/resource/execute.rb
In the example on line 163,
```
execute 'test_rule' do
command 'command_to_run
--option value
--option value
--source #{node[:name_of_node][:ipsec][:local][:subnet]}
-j test_rule'
action :nothing
end
```
that example command would not run correctly because the variable #{node{node[:name_of_node][:ipsec][:local][:subnet]}
would not be evaluated.  
changing to double quotes fixes the example.  
Obvious fix.
=> double quotes in example for string interpolation

lib/chef/resource/homebrew_update.rb
This is the one we should be using vs. the alias.
=> Use macos? helper in homebrew_update

lib/chef/application.rb, lib/chef/client.rb, lib/chef/dsl/platform_introspection.rb, lib/chef/encrypted_data_bag_item/decryptor.rb, lib/chef/json_compat.rb, lib/chef/knife/core/generic_presenter.rb, lib/chef/knife/yaml_convert.rb, lib/chef/mixin/shell_out.rb, lib/chef/mixin/which.rb, lib/chef/platform/service_helpers.rb, lib/chef/provider/ifconfig.rb, lib/chef/provider/package/snap.rb, lib/chef/provider/route.rb, lib/chef/recipe.rb
Only require external libraries if we need to. Also use require_relative
everywhere we can.
=> Optimize requires for non-omnibus installs

spec/functional/resource/link_spec.rb, spec/support/platform_helpers.rb
Use match? to make sure we always get a bool back. Rename os_x? to
macos?
=> Minor tweaks to the platform checks in the specs

lib/chef/resource/powershell_package_source.rb
Signed-off-by: Jeremy Kimber <jeremykimberh@gmail.com>
This removes the requirement for the `url` property to be defined within the `powershell_package_source` resource for all actions. Since the `remove` action doesn't have any interaction with the url, it doesn't make sense to require that property.
N/A
=> do not require source when removing powershell package source

lib/chef/exceptions.rb, lib/chef/mixin/checksum.rb, lib/chef/provider/file.rb
When working with templates, people can get confused by a checksum mismatch displaying an apparently shorter hash and subsequently trying to add this one to the recipe:
```
Chef::Exceptions::ChecksumMismatch
----------------------------------
Checksum on resource (1de48f) does not match checksum on content (8222e7)
``` 
I propose to add ellipsis ("...") and the end to show this is a truncated hash instead.
No filed issue, small usability improvement only
=> Change output to clearly show checksums are displayed incompletely

omnibus/config/software/more-ruby-cleanup.rb
We're not bundling Fauxhai for cookbook testing by end users. We're bundling it to test our own chef-utils logic. We can remove all the deprecated definitions that we're not using anyways. This shaves 2 megs off our install in 22 files. Long term I'd like to just ship fauxhai w/o the definitions as fauxhai-lite, but this will get us what we need until that time.
=> Delete deprecated Fauxhai definitions

lib/chef/http.rb
net/https just calls openssl and net/http. We can just do that ourselves
and avoid the extra layer
=> Use net/http and openssl instead of net/https

Gemfile.lock, chef-universal-mingw32.gemspec, omnibus/Gemfile.lock
I'm not seeing this being required anywhere in our kit.
=> Remove the unused win32-dir dependency

lib/chef/resource/osx_profile.rb
Typo: `Bug Sur` > `Big Sur`
macOS Eval Logic: Change `> 10.15` to `>= 11.0`
Currently this resource fails on 10.15.6 thinking that the node is on macOS Big Sur (11.0/10.16).
#10318
=> Fix typo and macOS version evaluation logic in `osx_profile` resource

lib/chef/resource/osx_profile.rb, spec/unit/resource/osx_profile_spec.rb
I don't think this ever worked, but now it does
=> Fix removing non-existent profile with osx_profile

lib/chef/resource/windows_package.rb
In response to #10336.
The quirks of the `package_name` property were already mentioned, but it was buried in the description of the `source` property and only mentioned it in context of the `:remove` action. 
The text was copied from the docs for the `windows_package` resource on the docs site and modified: https://docs.chef.io/resources/windows_package/
=> More prominently mention quirks of package_name in windows_package resource docs.

.expeditor/release.omnibus.yml
Testing if chef-16 builds okay on s390x.
https://buildkite.com/chef/chef-chef-master-omnibus-adhoc/builds/345#0834c6ff-ac9e-487c-90c9-c210d84f1118
This reverts commit a7012bfe35dc3923537ee936417144a0328970ab.
=> Start building S390x packages again

omnibus/omnibus-test.ps1
I added the `--profile` arg at the last minute in #10339 and it thinks the path is the profile count and thus running all specs together 3 times.
The font test can only run once. Not sure why and may be worth investigating so the last 2 fail.
=> separate omnibus rspec path from options

tasks/spellcheck.rb
`Bundler.which` did not detect cspell on Windows:
```
PS C:\vagrant\chef> ruby -rbundler -e "puts Bundler.which('cspell')"
PS C:\vagrant\chef> cspell --version
4.1.0
```
But it does work everywhere else:
```
Petes-MacBook-Pro:chef pete$ ruby -rbundler -e "puts Bundler.which('cspell')"
/Users/pete/.nvm/versions/node/v12.13.1/bin/cspell
Petes-MacBook-Pro:chef pete$ cspell --version
4.1.0
```
=> Fix spellcheck task on Windows.

.expeditor/verify.pipeline.yml, cspell.json, lib/chef/knife/config_list.rb, omnibus/omnibus-test.ps1, spec/integration/knife/config_list_spec.rb, spec/integration/knife/config_use_spec.rb
* #10346 broke some integration tests that were checking the output of knife commands because they were not updated to either include the newly introduced deprecation warning or point at the new command aliases. 
* #10341 made changes to `knife config list-profiles` but did not make the same changes to the aliased command introduced in #10346. 
* Fixed a few spelling violations that had been added.
=> Fix some CI failures

.expeditor/verify.pipeline.yml, habitat/tests/test.sh, scripts/ci/install-hab.sh, scripts/ci/verify-plan.sh
With the extra debug information added, I could see that the failure was printing this message:
```
ERROR: chef-client is not the expected version. Expected '16.5.15', got 'hab-pkg-exec 1.6.139/20200824142405'
```
See: https://buildkite.com/chef-oss/chef-chef-master-verify/builds/6001#54bd468a-7edc-42fc-999d-c7ba90c380fa
That second string is the version of hab. Since these testing scripts pull the latest release of habitat, something must have changed in the way hab parses CLI flags that caused this to break.
=> Fix habitat test script

Gemfile.lock
This switches it over to chef-utils for which/shellout
=> Update Ohai to 16.4.13

lib/chef/resource/chef_client_cron.rb, spec/unit/resource/chef_client_cron_spec.rb
This was in the cookbook recipe before and was useful for low resource
systems where the client could impact host operations. Since we support
this in launchd now, it makes sense to do it here as well.
=> Add back nice functionality to chef_client_cron

lib/chef/resource/chef_client_launchd.rb
Use 750 as we do in the cron resource
Fix property order so we can diff things more easily
=> chef_client_launchd: reorder properties and fix log permissions

spec/unit/shell/shell_ext_spec.rb, spec/unit/shell/shell_session_spec.rb, spec/unit/shell_spec.rb
I recently noticed that one test was printing a lot of output in the unit tests, as can be seen in this recent buildkite output: https://buildkite.com/chef-oss/chef-chef-master-verify/builds/6053#4785c4cb-14f3-4937-b6ca-f42a83a6f3ec/86-886
The test was running ohai when it was supposed to be stubbed, meaning it was printing a lot of output and taking a lot longer than it should. In CI it was a few hundred lines and 1.5 seconds, but in my local environment it was several thousand lines of output and the test took ~15 seconds.
* The first commit is rearranging some test code to remove unspecified dependencies in the tests so that each file could be run separately.
* The second commit is cleaning up the test code to be more consistent to allow me to see the differences in test …
=> Shell test cleanup

kitchen-tests/cookbooks/end_to_end/recipes/linux.rb, lib/chef/resource/chef_client_systemd_timer.rb, spec/unit/resource/chef_client_systemd_timer_spec.rb
This allows us to set a quota like 50% on everything handled by the chef-client including all the sub-processes like ohai or inspec. I looked at using systemd's nice functionality since that would give us a unified property for all the *nix processes, but that only applies to the chef-client process itself. This is much more powerful and gives users what user's probably really want which is "chef and all its stuff should not consume all the CPU on my host".
=> chef_client_systemd_timer: Add the ability to set CPUQuota on the chef-client unit

lib/chef/resource/osx_profile.rb
Users may want to cleanup old profiles after upgrading a Catalina box to
Big Sur. We should allow for that. It's just installing new profiles
where we need to fail hard.
=> Allow removing profiles in osx_profile on Big Sur

lib/chef/mixin/deep_merge.rb, spec/unit/mixin/deep_merge_spec.rb
While this behavior was fixed for attributes a long, long time ago it
turns out we don't use this deep_merge mixin for constructing the
deep merge of attribute precedence levels any more.
This bug however surfaces because we still use deep_merge to merge
json attributes into normal attributes.  That means that it is not
possible to pass a nil / null value in through -j and have it override
a normal attribute which is pulled back in from the node object on
the chef-server.
So this fixes that behavior to be consistent with the behavior of
attributes that we've had for several years now.
=> Fix nil deep_merging

lib/chef/resource/windows_ad_join.rb
In many situations, when using the windows_ad_join resource, you can't utilize the build-in reboot functionality because the windows system reboots too quickly and the chef run can't close out with the proper error code. We often see this failure when in test-kitchen, where the appropriate chef exit codes don't get passed to test-kitchen in order for it to trigger a retry.
I've added a `:reboot_delay` property to the resource to leverage the `:delay_mins` property in the `reboot` resource.  This will allow users to leverage that `:delay_mins` property without having to use a `notify` call from their use of the `windows_ad_join` resource.
Example:
** Join a domain and reboot the system after a 2 minute delay **
```ruby
windows_ad_join …
```
=> Add a :reboot_delay property to the windows_ad_join resource

lib/chef/application/apply.rb
I needed this for testing and it just sorta seems like something we
should support. Yes that means people may be using chef-apply with some
sort of init system, but if that's something they wanna do then why not
just let them roll with that. This just copies the option from the
base.rb file and it works fine for me locally.
=> Add --logfile to chef-apply command

habitat/tests/test.pester.ps1
Followup to #10350.
Fixes this failure on the "Windows plan" CI job:
```
Describing chef-infra-client
Context chef-client
[+] is an executable 591ms
[-] is the expected version 139ms
RuntimeException: You cannot call a method on a null-valued expression.
at <ScriptBlock>, C:\bk7f8d9d78\habitat\tests\test.pester.ps1: line 16
Context ohai
[+] is an executable 166ms
Context chef-shell
[+] is an executable 83ms
Context chef-apply
[+] is an executable 58ms
Context knife
[+] is an executable 61ms
Context chef-solo
[+] is an executable 58ms
Tests completed in 1.16s
Passed: 6 Failed: 1 Skipped: 0 Pending: 0 Inconclusive: 0
package didn't pass the test suite
At C:\bk7f8d9d78\scripts\ci\verify-plan.ps1:37 char:16
+ if (-not $?) { throw "package …
```
=> Fix windows habitat CI test script

lib/chef/resource/chef_client_launchd.rb
Launchd doesn't have the concept of a reload aka restart. Instead to update a daemon config you have to unload it and then reload the new plist. That's usually fine (actually just like upstart), but not if Chef is trying to restart itself. Currently if you change the nice level or interval the client will unload its own config which kills the run and it never gets started back up.  So to work around this we're going to install a launchd daemon that has a watcher on the chef-client daemon plist file. It's only job to to unload and reload the client. That way when the daemonized chef-client process updates the plist the restarter job will handle the restart. To ensure we're not in the middle of the next recipe we use a chef_sleep resource to sleep a bit post launchd update.
I also updated …
=> chef_client_launchd: create a launchd daemon to handle the client restart

lib/chef/resource/rhsm_register.rb, spec/unit/resource/rhsm_register_spec.rb
Switch to shell_out
Use include? instead of a regex
Add some simple YARD
Memoize the rhsm registration check to avoid potentially running that check twice
Stop using grep to find text. Let ruby do it all
May help with:
https://github.com/chef/chef/issues/9295
=> rhsm_register: Avoid potentially checking if we need to register twice

spec/unit/provider/route_spec.rb
We were looping over the same object twice here.
=> Remove a redundant spec loop

lib/chef/knife/bootstrap.rb
I had previously done this for the `chef-client` scenario but missed this which is pulled in when loading knife commands. The deps of license_acceptance/acceptor are pretty heavy.
=> autoload license_acceptance/acceptor in knife loading

.expeditor/release.omnibus.yml
Enable s390x RHEL8 and SLES15 platforms
Enable s390x RHEL8 and SLES15 platforms
=> Enable s390x RHEL8 and SLES15 platforms

lib/chef/resource/chef_client_systemd_timer.rb, spec/unit/resource/chef_client_systemd_timer_spec.rb
Turns out on multi-core boxes these are valid.
=> Allow cpu_quota values > 100

spec/integration/ohai/ohai_spec.rb
I disabled the first test here entirely because we don't seem to have stable enough timing to shell_out to ohai so that we wouldn't suffer, so it all becomes a bit more aspirational than functional.
The second test should be good enough to find busted DNS issues like the one last week though.
=> Add an ohai timing test to find busted DNS on CI testers

kitchen-tests/cookbooks/end_to_end/recipes/windows.rb, lib/chef/resource/windows_firewall_profile.rb
This pull request should fix the NoMethodError being seen when using this resource.  Because the load_current_value section was using a method defined in the action_class, and therefore couldn't find it because it's not part of the action...  I've moved it into a private section (to mirror what's done in the windows_firewall_rule resource) which fixes the issue.
I've also added kitchen tests for this resource to ensure this is working correctly in both the enable and disable actions.
#10411
=> Update the windows_firewall_profile resource to fix NoMethodError

lib/chef/provider/package/snap.rb
No need for this here. Thanks for pointing it out @jaymzh 
=> Remove debug puts from snap_package

lib/chef/resource/rhsm_register.rb, spec/unit/resource/rhsm_register_spec.rb
This change allows specifying an alternative name when registering the node.
N/A
=> Add system_name property to rhsm_register resource

lib/chef/resource/sysctl.rb
We don't do the backup mess anymore and we never did when this resource was in chef-client itself.
=> Update sysctl resource description to match reality

azure-pipelines.yml
We test this same stuff in the dokken based BK tests and this one is
failing outside of the Chef run.
=> Remove the Ubuntu azure pipeline test

chef-config/lib/chef-config/mixin/credentials.rb, chef-config/lib/chef-config/mixin/train_transport.rb, chef-utils/lib/chef-utils/dsl/train_helpers.rb, lib/chef/run_context.rb, lib/chef/train_transport.rb, spec/unit/train_transport_spec.rb
Also pull in some helpers from the Ohai work so that Ohai can
use them later.
This is code rearrangement to support the remote ohai work but
does not change any existing behavior yet.
=> Move TrainTransport to ChefConfig

lib/chef/resource/bff_package.rb, lib/chef/resource/breakpoint.rb, lib/chef/resource/cab_package.rb, lib/chef/resource/chef_gem.rb, lib/chef/resource/chef_handler.rb, lib/chef/resource/ohai_hint.rb, lib/chef/resource/openssl_dhparam.rb, lib/chef/resource/openssl_ec_private_key.rb, lib/chef/resource/openssl_rsa_private_key.rb, lib/chef/resource/openssl_x509_certificate.rb, lib/chef/resource/openssl_x509_crl.rb, lib/chef/resource/openssl_x509_request.rb, lib/chef/resource/osx_profile.rb, lib/chef/resource/powershell_package_source.rb
Mostly just formatting differs from the docs side except for chef_handler which got some significant changes to make it *potentially* work IRL.
=> More resource documentation improvements

lib/chef/chef_fs/parallelizer.rb, lib/chef/cookbook_site_streaming_uploader.rb, lib/chef/knife/bootstrap/chef_vault_handler.rb, lib/chef/provider/launchd.rb, lib/chef/provider/package/zypper.rb, lib/chef/provider/route.rb, lib/chef/provider/service/macosx.rb, lib/chef/provider/template_finder.rb, lib/chef/provider_resolver.rb, lib/chef/recipe.rb, lib/chef/resource/execute.rb, lib/chef/util/threaded_job_queue.rb, spec/tiny_server.rb, spec/unit/runner_spec.rb
**Lint/RedundantRequireStatement:** These are required by Ruby out of the box so lets avoid trying to require them again.
**Style/RedundantCondition:** This lets us nuke a pile of ternary operators and other checks for values that weren't necessary
=> Resolve Lint/RedundantRequireStatement & Style/RedundantCondition warnings

spec/unit/mixin/openssl_helper_spec.rb
This was one of our top 10 slow specs
Before:
```
Chef::Mixin::OpenSSLHelper#dhparam_pem_valid? When the dhparam.pem file does exist, and does contain a vaild dhparam key returns true
2.71 seconds ./spec/unit/mixin/openssl_helper_spec.rb:101
```
After:
```
Chef::Mixin::OpenSSLHelper#dhparam_pem_valid? When the dhparam.pem file does exist, and does contain a vaild dhparam key returns true
0.01844 seconds ./spec/unit/mixin/openssl_helper_spec.rb:101
```
=> Speed up a openssl helper specs

RELEASE_NOTES.md, lib/chef/resource/osx_profile.rb, spec/unit/resource/osx_profile_spec.rb
This had 2 different issues that were causing it to not fetch the current resource state properly. The resource didn't fail, but it would converge each time because it believed the profile was not installed.
1) The profiles command was failing to write the profile state to disk because the temp file already existed. We don't actually need to write to disk and we can avoid that extra disk space / IO entirely by writing to stdout and parsing that.
2) Our fetching of the current profile state from node.state was always returning nil because of an extra logger at the end of the method. That has been moved to the top so that we return the objects correctly.
=> Fix idempotency in the osx_profile resource and avoid writing data to disk

lib/chef/policy_builder/dynamic.rb
This was coming in for free before somehow, but now it's causing
failures in the Chef Workstation specs.
ERROR: Chef Infra failed to converge: uninitialized constant Chef::PolicyBuilder::Dynamic::ExpandNodeObject from file /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/policy_builder/dynamic.rb:158:in `select_implementation'
Caused by: (NameError) uninitialized constant Chef::PolicyBuilder::Dynamic::ExpandNodeObject
=> Add missing requires to chef/policy_builder/dynamic

lib/chef/provider/package/homebrew.rb
I was running into an issue where Homebrew formulae would fail to install using the full name, e.g. 
```
homebrew_package 'homebrew/core/vim'
homebrew_package 'derailed/k9s/k9s'
```
In the `package_info` method, I added an additional check for the `full_name` when the short-name isn't found and the method iterates over the entire hash.
Mostly a work-around, but seems to solve the issue without changing any existing behavior. This doesn't change the behavior of failure when the prefixed tap isn't previously installed (e.g. `derailed/k9s/k9s` will still fail if the tap doesn't exist locally).
I'm not really familiar with the Ruby/Chef ecosystem/internals. I wasn't able to successfully get the rspec unit tests running on my workstation. I planned to add some additional `context`s to the …
=> Check for full names in Homebrew package info

lib/chef/resource/chef_handler.rb
There was a missing code fence causing some bad formatting.
=> Fix examples markdown in chef_handler resource.

lib/chef/knife/search.rb
Related to  #10464 and #10452. This file doesn't reference `Addressable::URI`.
=> Remove unnecessary require.

lib/chef/resource_reporter.rb
These libs are not used in this file, and no requires are faster than no requires.
=> Remove unnecessary requires from ResourceReporter.

spec/unit/data_collector_spec.rb
I was trying to find where this setting was used and found it being set in this test file even though `Chef::DataCollector` does not use it.
=> Remove unncessary test state.

Gemfile.lock, omnibus/Gemfile.lock, omnibus_overrides.rb
This resolves CVE-2020-25613 and a large number of misc bugs
=> Update to Ruby 2.7.2 / Rubygems 3.1.4

spec/functional/mixin/powershell_out_spec.rb, spec/unit/mixin/powershell_exec_spec.rb
Some of our tests are interrogating the `PSEdition` property of `$PSVersionTable`. This prop does not exist in versions of powershell under 5.1. So we either check the version of the existence of `CLRVersion`.
=> fix specs on powershell v4 and below

lib/chef/provider/ifconfig.rb, lib/chef/provider/ifconfig/debian.rb, lib/chef/provider/ifconfig/redhat.rb
Changing ifconfig provider to use '-' trim_mode for its ERB templates and updating the redhat and debian ifconfigs to leverage the trim_mode so they are not constructed with any blank lines when nil values are encountered.
This addresses https://github.com/chef/chef/issues/10457
This improves the `ifconfig` templates defined for debian and redhat so that `nil` values do not generate blank lines in the resulting ifconfig file.
Ruby ERB supports a `trim_mode` parameter of `'-'` to `"-  omit blank lines ending in -%>"`
I've changed the ERB call in https://github.com/chef/chef/blob/master/lib/chef/provider/ifconfig.rb#L239 to leverage this trim mode.
I've also changed each of the distro's template generation scripts to generate a template that omits blank lines when a `nil` value is …
=> Changing ifconfig provider to reduce blank lines in redhat and debian ifconfigs

lib/chef/application/client.rb, lib/chef/client.rb
This replaces the old kinda hacked up support for platform detection via inspec with proper remote ohai execution.
The `--target` option now supports train-style URIs (or the existing chef .credentials file)
=> Support for ohai target mode

lib/chef/resource/file.rb, lib/chef/resource/powershell_script.rb, lib/chef/resource/registry_key.rb
Prevent tagging a resource new in Chef 11. No one cares
Use the full product name instead of the client name in another spot
Improve the powershell_script description to mention we allow PowerShell Core now.
=> More resource documentation improvement

tasks/docs.rb
We need a boolean for the docs site here, but we get back an array now.
For now let's just treat it like a boolean.
=> Update docs generation task to handle Chef 16 required format

lib/chef/provider/package/freebsd/base.rb
This is 2.66X slower than just throwing the data in there.
=> Avoid a slow hash merge

lib/chef/provider/ifconfig.rb, lib/chef/provider/mount/mount.rb, lib/chef/provider/package/apt.rb, lib/chef/provider/user/aix.rb, lib/chef/resource/hostname.rb, lib/chef/util/dsc/local_configuration_manager.rb
The ifconfig part needs a complete rewrite, but this is better. At least it's not doing a regex twice for each thing it wants to match per line. It still does 5 regexes even if it matches on the first.
=> Avoid using complex regexes when we can use include?

lib/chef/resource/lwrp_base.rb
=> Fix bad formatting in a deprecation message

lib/chef/mixin/convert_to_class_name.rb
It doesn't look like we're using this anymore and the comment states
that we wouldn't need the implementation after Ruby 2.0 anyways.
=> Remove constantize method from Chef::Mixin::ConvertToClassName

chef-config/chef-config.gemspec, chef-utils/chef-utils.gemspec
These are getting pulled in all over and that's causing problems on
older Ruby releases.
=> Add required_ruby_version to chef-utils and chef-config

lib/chef/provider/ifconfig/debian.rb, spec/unit/resource/ifconfig_spec.rb
We don't need to check around ancient EOL versions that we don't provide packages for anymore.
=> Simplify the ifconfig provides statement on Ubuntu/Debian

lib/chef/guard_interpreter/resource_guard_interpreter.rb, lib/chef/resource/powershell_script.rb, spec/support/shared/unit/script_resource.rb, spec/support/shared/unit/windows_script_resource.rb, spec/unit/guard_interpreter/resource_guard_interpreter_spec.rb, spec/unit/resource/powershell_script_spec.rb
I started refactoring ResourceGuardInterpreter as part of a different PR a few months ago but moved the changes onto a different branch when I realized I didn't have to change it for that PR's behavior. This doesn't fix anything other than making the code a lot easier to follow (IMO).
=> Refactor ResourceGuardInterpreter

lib/chef/mixin/properties.rb, lib/chef/resource/lwrp_base.rb
Stick it right next to the property def so it's pretty obvious how this works.
=> Move the alias for attribute to property right into the property mixin

lib/chef/provider/ifconfig/redhat.rb, lib/chef/resource/ifconfig.rb
I don't see any documentation mentioning this being used on Debian, but
it's a thing in the legacy interface configs on RHEL
This wraps up https://github.com/chef/chef/issues/3509
=> Add bridge property to ifconfig for RHEL based systems

lib/chef/provider/ifconfig/debian.rb
We're in unified mode. There's no need to work with classes when we can just use the DSL here.
=> Use a native resource in the ifconfig debian provider

kitchen-tests/kitchen.yml
This is in the dokken image now.
=> Remove insserv-compat from opensuse now that it's there by default

lib/chef/resource/lwrp_base.rb
In `lib/chef/provider/lwrp_base.rb` the `build_from_file` method tries to avoid rebuilding LWRPs, but incorrectly stores "true" instead of the built resource in the cache.
This way, two different data types are returned.
Return values are only used in the resource inspector, so impact is mimimal.
-
=> Fix LWRP build cache

.expeditor/verify.pipeline.yml, Gemfile, Rakefile, azure-pipelines.yml
If someone wants the yard docs locally they can just gem install yard and then run yard. This is way overthinking the problem and requires us to exclude the group all over the place.
=> Remove the yard doc generation task / group

omnibus/config/software/more-ruby-cleanup.rb
Nuke a few more binstubs that have nothing to do with chef and shouldn't
be shipped.
=> Remove coderay and ffi-yajl-bench binstubs

spec/unit/provider/subversion_spec.rb
=> Remove an empty before block in a spec

.expeditor/verify.pipeline.yml, kitchen-tests/kitchen.yml
We can bump this up to the latest non-LTS release every 6 months to
determine if there's any resource updates we need to make in advance of
the LTS release.
=> Add Test Kitchen testing on Ubuntu 20.10

kitchen-tests/cookbooks/end_to_end/recipes/_ifconfig.rb, lib/chef/resource/ifconfig.rb
This resource only works with the legacy redhat /etc/networks configuration format. That format was slapped onto NetworkManager when RHEL moved off legacy init scripts. Fedora 33 switches to the keyfile format so this resource no longer works on those systems. Stop testing it there and add a note to the resource description so we get that up on the docs site.
=> ifconfig is not compatible with Fedora 33 or later

lib/chef/provider/mount.rb, lib/chef/provider/mount/mount.rb, spec/unit/provider/mount_spec.rb
- Moved `device_fstab` method from `provider/mount/mount.rb` to `provider/mount.rb`
- Compare current resource device with new resource `device_fstab` value.
- Added specs for `device_unchanged?` method changes.
#8260
=> Mount resources not idempotent with label fixes

tasks/docs.rb
Resolve a few valid warnings there and then add a few more resources where we should be showing package warnings.
=> Improve the package docs generation + resolve rubocop warnings

tasks/docs.rb
This data actually needed to be under resource_description_list and not at the top level.
=> Correctly generate docs yaml files to include package warnings

lib/chef/resource/scm/_scm.rb, lib/chef/resource/scm/git.rb, lib/chef/resource/scm/subversion.rb, lib/chef/resource/systemd_unit.rb, lib/chef/resource/windows_service.rb, lib/chef/resource/windows_task.rb
Get closer to just being able to auto-generate the world
=> Improve resource documentation

lib/chef/resource/scm/git.rb, lib/chef/resource/scm/subversion.rb
Get the spellcheck tests green again.
=> Fix some spelling / cookstyle errors in the git examples

chef-utils/README.md, chef-utils/lib/chef-utils/dsl/platform.rb, chef-utils/lib/chef-utils/dsl/platform_family.rb, cspell.json, lib/chef/provider/package/ips.rb, lib/chef/provider/package/solaris.rb, lib/chef/provider/user/solaris.rb, lib/chef/resource/solaris_package.rb, lib/chef/resource/windows_service.rb, spec/functional/resource/cron_spec.rb, spec/unit/provider_resolver_spec.rb, spec/unit/resource/solaris_package_spec.rb
https://en.wikipedia.org/wiki/Nexenta_OS
"In late 2011, the Nexenta OS brand was terminated and replaced with Illumian, which is derived from community development for illumos and OpenIndiana, but was distinguished by its use of Debian packaging. Illumian version 1.0 was released in February 2012. Following the initial release of Illumian in 2012, the Illumian project was discontinued.[3]"
and
"Final release	3.1.3.5 (October 31, 2012; 7 years ago)"
https://en.wikipedia.org/wiki/OpenSolaris
"OpenSolaris is a discontinued open source computer operating system based on Solaris and created by Sun Microsystems."
and
Latest release	2009.06 / June 1, 2009; 11 years ago
These are beyond dead and we never supported either of them officially. Just nuke it along with the helpers. There's no way …
=> Remove support for nexentacore and opensolaris which are both a decade EOL

Gemfile, Gemfile.lock, chef-config/Gemfile, omnibus/omnibus-test.ps1, omnibus/omnibus-test.sh
This was added a long time ago (https://github.com/chef/chef/commit/87612bf41873efd9c783be7732415c23a171f58d) and exists to write test output in junit format to a file named "test.xml" that does not appear to be consumed by anything.
I figure if this breaks something we'll find out pretty quickly.
=> Remove rspec_junit_formatter and rspec version pins

habitat/tests/spec.ps1, habitat/tests/test.sh
This output can be useful occasionally, but more often its just annoying to have to scroll past 10k lines of output to see what the failures are.
Example: https://buildkite.com/chef-oss/chef-chef-master-verify/builds/6766#0278bdf8-27a6-4e40-9e12-d35438b1fdfc
=> Don't run rspec with documentation formatter.

lib/chef/provider/package/solaris.rb, lib/chef/resource/solaris_package.rb
This only worked on Solaris 5.10, which we don't support anymore. Just
nuke the line entirely
=> Remove the provides :package for solaris_package

lib/chef/knife/core/windows_bootstrap_context.rb, lib/chef/resource/windows_service.rb
Adding tls1.2 support for powershell.
Knife bootstrap on TLS 1.2 enabled servers can fail to bootstrap when downloading using powershell with the error: Could not create SSL/TLS secure channel.
https://github.com/chef/chef/issues/8713
=> Fix download errors during knife bootstrap on windows due to lack of TLS 1.2 support

.expeditor/verify.pipeline.yml, lib/chef/powershell.rb, lib/chef/provider/package/chocolatey.rb, lib/chef/resource/hostname.rb, lib/chef/resource/powershell_package_source.rb, lib/chef/resource/windows_ad_join.rb, lib/chef/resource/windows_certificate.rb, lib/chef/resource/windows_dfs_server.rb, lib/chef/resource/windows_firewall_profile.rb, lib/chef/resource/windows_firewall_rule.rb, lib/chef/resource/windows_security_policy.rb, lib/chef/resource/windows_share.rb, lib/chef/resource/windows_workgroup.rb, spec/functional/resource/chocolatey_package_spec.rb, spec/functional/resource/dsc_script_spec.rb, spec/functional/resource/powershell_package_source_spec.rb, spec/functional/resource/windows_certificate_spec.rb, spec/functional/resource/windows_firewall_rule_spec.rb, spec/functional/resource/windows_share_spec.rb, spec/support/platform_helpers.rb, spec/unit/provider/package/chocolatey_spec.rb, spec/unit/resource/powershell_package_source_spec.rb
`powershell_package` and `windows_feature_powershell` are still using powershell_out due to timeout.
I've tested every affected resource and added functional tests where feasible. Interestingly a couple resources were busted and I don't think the `windows_dfs_server` could have ever possibly worked at all.
=> Improve Windows resource performance by converting powershell_out usage to powershell_exec

kitchen-tests/cookbooks/end_to_end/recipes/macos.rb, lib/chef/resource/homebrew_update.rb
@johnmccrae noticed that the `homebrew_update` resource would fail with an undefined constant error. This PR adds some basic homebrew usage to the kitchen tests and fixes the bad reference.
=> Fix homebrew_update

chef-bin/bin/chef-resource-inspector, lib/chef/resource_inspector.rb, spec/unit/resource_inspector_spec.rb, tasks/docs.rb
On #10547 I was seeing errors like this on CI:
```
An error occurred while loading ./spec/unit/resource_inspector_spec.rb.
Failure/Error: module ResourceInspector
TypeError:
ResourceInspector is not a module
Run options:
include {:focus=>true}
exclude {:provider=>#<Proc:./spec/spec_helper.rb:213>, :arch=>#<Proc:./spec/spec_helper.rb:207>, :pwsh_installed=>true, :choco_installed=>true, :ruby=>"2.6.6", :chef=>"16.7.20", :not_intel_64bit=>true, :rhel_gte_8=>true, :rhel8=>true, :rhel7=>true, :rhel6=>true, :rhel=>true, :not_wpar=>true, :broken=>true, :openssl_lt_101=>true, :requires_unprivileged_user=>true, :selinux_only=>true, :opensuse=>true, :suse_only=>true, :aix_only=>true, :system_windows_service_gem_only=>true, :solaris_only=>true, …
```
=> Namespace ResourceInspector to avoid conflicts with Inspec's

lib/chef/exceptions.rb, lib/chef/provider/package/chocolatey.rb
This is 3-5x faster from the benchmarks I've run locally. There's a cop
coming in the next release of RuboCop to enforce this going forward.
=> Use .compact instead of .select/.reject to remove nils

lib/chef/knife/bootstrap.rb, lib/chef/knife/config_show.rb, lib/chef/provider/package/freebsd/pkgng.rb, spec/unit/provider/mount/solaris_spec.rb
We can do this with strings alone
=> Don't uses regexes in splits when we don't need to

lib/chef/json_compat.rb
Removed an unused constant, some confusing inaccurate comments, and refactor `to_json_pretty` to avoid creating a hash.
=> Cleanup Chef::JSONCompat

kitchen-tests/test/integration/end-to-end/_chef_client_config.rb, lib/chef/resource/support/client.erb
Address two issues in the chef_client_config resource. It removes unneeded `=` signs and fixes logic for log_location
#10606 
#10607 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
=> chef_client_config: Resolve invalid configuration in client.rb

lib/chef/provider/mount.rb, lib/chef/provider/mount/linux.rb, lib/chef/provider/mount/mount.rb, lib/chef/resource/mount.rb, spec/unit/provider/mount/linux_spec.rb, spec/unit/resource/mount_spec.rb
- Fixes for CIFS mount not idempotent issue.
- Added spec for network device found as mounted.
- Removed '/' from end of the device value.
#10453
=> mount: Fixes for findmount output causing idempotency issues

lib/chef/resource/registry_key.rb
=> Prevent failures generating docs

lib/chef/provider/package.rb, lib/chef/provider/package/zypper.rb, spec/functional/resource/zypper_package_spec.rb, spec/unit/provider/package/zypper_spec.rb, spec/unit/provider/package_spec.rb
Previously the candidate_version in zypper_package was only ever the latest version, even if the new_resource.version was attempting to pin to a prior version or do a downgrade.  This changes how the candidate_version is calculated in order to fix that.  This allows the additional idempotency check in here which is a requirement for fixing dnf_package and which broke the old version of zypper_package.  There's also an old unit test that was always slightly broken and having the wrong candidate_version for the requested new_resource.version which needed fixing.  Some conversion to the overall style of the yum+dnf package providers was done so that it will be easier to extend the functionality of the zypper package provider in the future to handle whatever aliases/virtual packages and other …
=> Change how zypper_package calculates the candidate_version

Gemfile.lock, omnibus/Gemfile.lock
This is our last usage of chef-sugar
=> Update omnibus to remove the chef-sugar dep

spec/unit/provider/mount_spec.rb
- Added `not_supported_on_solaris` because it can't cope with `LABEL` and `UUID` device type.
Fixes https://github.com/chef/chef/issues/10615
=> mount: changes to fix solaris test failure

lib/chef/provider/mount/mount.rb, spec/unit/provider/mount/mount_spec.rb
- Updated `enabled?` method in mount provider.
- Added `update_or_delete_fs` method to fix the order change
- Added spec for the changes
- Fixed test case failure.
#2908
=> mount: Changes to fix creating multiple entries in fstab

Gemfile, Gemfile.lock
pry-remote is questionably useful for our user base and hasn't seen a release for doing on 7 years. Removing it removes 2 gem deps total.
=> Remove pry-remote from the package

Gemfile.lock, omnibus/Gemfile.lock
This loads the user env when specifying alternative windows users.
=> Update mixlib-shellout to 3.2.2

lib/chef/provider/group.rb, lib/chef/provider/user.rb, lib/chef/provider/user/mac.rb, lib/chef/provider/user/windows.rb, spec/unit/provider/user_spec.rb
Fixes #10645
Linux:
```
[2020-11-18T12:09:31-08:00] INFO: Processing linux_user[bin] action create (/var/chef/cache/cookbooks/fb_users/resources/default.rb line 118)
[2020-11-18T12:09:32-08:00] INFO: linux_user[bin] altered, change shell from /usr/sbin/phil to /usr/sbin/nologin
```
Windows:
```
[2020-11-18T12:18:02-08:00] INFO: windows_user[john] altered, update password
```
Note this does not fix an ongoing but where no matter waht you set the
password to it always thinks it needs to be updated, likely a bug
somewhere in Chef::Util::Windows::NetUser, and vaguely related to #10455
=> user: Log what changed when updating a user

tasks/docs.rb
The format has been simplified so we can remove some of the logic from
our generation scripts.
=> Update the docs generation for the new format

omnibus/config/projects/chef.rb
Speed up our windows builds by removing appx packaging since we're not
actually using that.
=> Skip appx packaging on Windows

lib/chef/provider/user/mac.rb
The m variable is never defined. This should be attr. The variable was m before, but https://github.com/chef/chef/pull/10656 refactored to attr.
=> Resolve NameError running mac_user resource

lib/chef/application/base.rb, lib/chef/knife/bootstrap/train_connector.rb
RuboCop claims that URI.regexp is the obsolete way of doing this. Both produce the same regex.
=> Use URI::DEFAULT_PARSER.make_regexp instead of URI.regexp

Dockerfile
These are the same package, but in a while we're getting rid of RHEL 6 and this will break.
@ramereth inspired this
=> Update the Docker file to use the RHEL 7 package

CHANGELOG.md
Some pr's never were executed in Expeditor, this should preserve their changelog updates.
Signed-off-by: Nathaniel Kierpiec <nkierpiec@chef.io>
- [x ] Chore (non-breaking change that does not add functionality or fix an issue)
=> Update changelog with missing updates from previous prs

Gemfile, Gemfile.lock, lib/chef/encrypted_data_bag_item/assertions.rb, lib/chef/provider/git.rb, lib/chef/resource/template.rb, lib/chef/resource_collection/resource_set.rb, omnibus/Gemfile.lock, spec/unit/knife/core/node_editor_spec.rb
We have an inspec / rubocop conflict that's getting worked out right now, but for now we need to make sure a bundle update doesn't downgrade inspec.
=> Pin our InSpec version and use Chefstyle from rubygems for now

lib/chef/http/ssl_policies.rb, spec/unit/http/ssl_policies_spec.rb
- Use the `SSL_CERT_FILE` environment variable to specify the location for the SSL certificate authority (CA)
- Ensured chefstyle on the code changes made
Fixes: #5944
=> Allow remote_file consider certificates stored under /etc/chef/trusted_certs

lib/chef/knife/core/ui.rb
Fix for #10705.
Before:
```
Petes-MacBook-Pro:chef pete$ bundle exec knife ssh "foobar" -P
WARNING: No knife configuration file found. See https://docs.chef.io/config_rb/ for details.
ERROR: knife encountered an unexpected error
This may be a bug in the 'ssh' knife command or plugin
Please collect the output of this command with the `-VVV` option before filing a bug report.
Exception: NameError: uninitialized constant Chef::Knife::UI::TTY
```
After:
```
Petes-MacBook-Pro:chef pete$ bundle exec knife ssh "foobar" -P
WARNING: No knife configuration file found. See https://docs.chef.io/config_rb/ for details.
Enter your password:  
```
=> Add missing require for TTY::Prompt.

spec/unit/provider/systemd_unit_spec.rb
fixes #10695 
These is no reason to run systemd unit tests on windows. On our omnibus pipeline, these consumed several minutes. What is baffling is why they are super fast locally and in our verify pipeline. They are also fast in a manually spun up omnibus image. After profiling, the bottleneck is in the shell out to systemd. It makes sense that would be where the bottleneck is but I'm still confused why the slow down is isolated to the omnibus pipeline.
In the end it does make sense to just remove them from windows.
=> only run systemd unit tests on linux
